export const DISEASE_PROFILES: Record<string, { name: string; category: string }> = {
  'aaa': { name: 'Abdominal Aortic Aneurysm', category: 'cardiology' },
  'abdominal_aortic_aneurysm': { name: 'Abdominal Aortic Aneurysm (Leaking)', category: 'cardiology' },
  'abscess': { name: 'Pyogenic Abscess', category: 'infectious' },
  'ac_joint_arthritis': { name: 'Acromioclavicular Joint Arthritis', category: 'orthopaedics' },
  'achilles_tendinopathy': { name: 'Achilles Tendinopathy / Tear', category: 'ent' },
  'achlasia': { name: 'Achalasia', category: 'general_medicine' },
  'acoustic_neuroma': { name: 'Acoustic Neuroma', category: 'ent' },
  'acute_mountain_sickness': { name: 'High-Altitude Pulmonary Edema', category: 'respiratory' },
  'acute_otitis_media': { name: 'Acute Otitis Media', category: 'ent' },
  'acute_pancreatitis': { name: 'Acute Pancreatitis (Referred)', category: 'surgical' },
  'acute_respiratory_distress_syndrome': { name: 'ARDS', category: 'respiratory' },
  'addisons_crisis': { name: 'Adrenal Crisis (Addison\'s Disease)', category: 'urology' },
  'addisons_disease': { name: 'Adrenal Insufficiency', category: 'urology' },
  'adjustment_disorder': { name: 'Adjustment Disorder with Anxiety', category: 'psychiatry' },
  'af_ep': { name: 'Atrial Fibrillation', category: 'general_medicine' },
  'agoraphobia': { name: 'Agoraphobia / Panic with Avoidance', category: 'general_medicine' },
  'alcohol_intoxication': { name: 'Alcohol Intoxication', category: 'general_medicine' },
  'alcohol_withdrawal': { name: 'Alcohol Withdrawal Tremor', category: 'general' },
  'allergic_reaction': { name: 'Allergic Reaction / Urticaria', category: 'general_medicine' },
  'allergic_rhinitis': { name: 'Allergic Rhinitis', category: 'ent' },
  'alzheimers_disease': { name: 'Alzheimer\'s Disease', category: 'neurology' },
  'amoebiasis': { name: 'Amebic Dysentery', category: 'ent' },
  'anal_fissure': { name: 'Anal Fissure', category: 'surgical' },
  'anaphylaxis': { name: 'Anaphylaxis', category: 'PAED' },
  'anemia': { name: 'Severe Anemia', category: 'PAED' },
  'angiodysplasia': { name: 'Angiodysplasia / Vascular Ectasia', category: 'general_medicine' },
  'ankle_sprain': { name: 'Ankle Sprain (Ligament Injury)', category: 'orthopaedics' },
  'ankylosing_spondylitis': { name: 'Ankylosing Spondylitis', category: 'rheumatology' },
  'anterior_cruciate_ligament': { name: 'ACL Rupture', category: 'orthopaedics' },
  'anterior_epistaxis': { name: 'Anterior Epistaxis (Kiesselbach Plexus)', category: 'general_medicine' },
  'anticoagulant_use': { name: 'Anticoagulant / Antiplatelet Therapy', category: 'general_medicine' },
  'anxiety': { name: 'Anxiety / Hypervigilance', category: 'psychiatry' },
  'anxiety_disorder': { name: 'Anxiety Disorder (comorbid)', category: 'psychiatry' },
  'anxiety_hyperventilation': { name: 'Anxiety / Hyperventilation Syndrome', category: 'psychiatry' },
  'anxiety_panic': { name: 'Anxiety / Panic Attack', category: 'psychiatry' },
  'aortic_dissection': { name: 'Aortic Dissection', category: 'emergency_medicine' },
  'appendicitis': { name: 'Appendicitis', category: 'surgical' },
  'ascites': { name: 'Ascites (Liver Disease, Heart Failure)', category: 'cardiology' },
  'asthma_exacerbation': { name: 'Severe Asthma Exacerbation', category: 'respiratory' },
  'asthma_pulm': { name: 'Bronchial Asthma', category: 'respiratory' },
  'atrophic_rhinitis': { name: 'Atrophic Rhinitis', category: 'general_medicine' },
  'autoimmune': { name: 'Autoimmune Disease', category: 'general_medicine' },
  'avascular_necrosis': { name: 'Avascular Necrosis of Femoral Head', category: 'general_medicine' },
  'behcets_disease': { name: 'Behcet\'s Disease (Oral + Genital Ulcers)', category: 'general_medicine' },
  'bicipital_tendinopathy': { name: 'Bicipital Tendinopathy', category: 'general_medicine' },
  'bipolar_disorder': { name: 'Bipolar Disorder (Depressive Episode / Mixed)', category: 'psychiatry' },
  'borderline_personality_disorder': { name: 'Borderline Personality Disorder', category: 'PSYCH' },
  'bowel_obstruction': { name: 'Bowel Obstruction', category: 'surgical' },
  'bppv': { name: 'Benign Paroxysmal Positional Vertigo', category: 'general_medicine' },
  'brain_tumor': { name: 'Brain Tumor', category: 'neurology' },
  'bronchiectasis': { name: 'Bronchiectasis', category: 'respiratory' },
  'brucellosis': { name: 'Brucellosis', category: 'infectious_disease' },
  'burns': { name: 'Major Burns (Fluid Loss via Skin)', category: 'emergency' },
  'c_diff': { name: 'C. Difficile Colitis', category: 'general_medicine' },
  'candidiasis': { name: 'Candidiasis (Superficial Erosions)', category: 'gynaecology' },
  'carbon_monoxide': { name: 'Carbon Monoxide Poisoning', category: 'general_medicine' },
  'carbon_monoxide_poisoning': { name: 'Carbon Monoxide Poisoning', category: 'general' },
  'cardiac_arrhythmia': { name: 'Cardiac Arrhythmia', category: 'cardiology' },
  'cardiac_pain': { name: 'Cardiac Chest Pain (ACS Mimic)', category: 'cardiology' },
  'carpal_tunnel': { name: 'Carpal Tunnel Syndrome', category: 'general_medicine' },
  'cauda_equina': { name: 'Cauda Equina Syndrome', category: 'general_medicine' },
  'celiac_disease': { name: 'Celiac Disease', category: 'gastroenterology' },
  'cellulitis': { name: 'Cellulitis', category: 'surgical' },
  'cellulitis_foot': { name: 'Cellulitis of Foot', category: 'dermatology' },
  'cerebellar_ataxia': { name: 'Cerebellar Ataxia', category: 'general_medicine' },
  'cerebellar_disease': { name: 'Cerebellar Disease (Intention Tremor)', category: 'ent' },
  'cervical_myelopathy': { name: 'Cervical Myelopathy', category: 'general_medicine' },
  'cervical_radiculopathy': { name: 'Cervical Radiculopathy', category: 'general_medicine' },
  'cervical_spondylosis': { name: 'Cervical Vertigo', category: 'general_medicine' },
  'chancroid': { name: 'Chancroid (Haemophilus Ducreyi)', category: 'general_medicine' },
  'chest_pain': { name: 'Acute Coronary Syndrome', category: 'cardiology' },
  'chickenpox': { name: 'Chickenpox / Herpes Zoster', category: 'general_medicine' },
  'cholecystitis': { name: 'Cholecystitis', category: 'surgical' },
  'cholera': { name: 'Cholera', category: 'infectious' },
  'chronic_fatigue': { name: 'Chronic Fatigue Syndrome', category: 'IM' },
  'chronic_infection': { name: 'Chronic Infection (e.g. fungal)', category: 'infectious' },
  'chronic_pain': { name: 'Chronic Pain Conditions', category: 'general_medicine' },
  'chronic_pain_illness': { name: 'Chronic Pain / Terminal Illness', category: 'general_medicine' },
  'chronic_subdural_hematoma': { name: 'Chronic Subdural Hematoma', category: 'general_medicine' },
  'chronic_suppurative_otitis_media': { name: 'Chronic Suppurative Otitis Media', category: 'ent' },
  'chronic_venous_insufficiency': { name: 'Chronic Venous Insufficiency', category: 'general' },
  'circadian_disorder': { name: 'Circadian Rhythm Sleep Disorder (Shift Work)', category: 'general_medicine' },
  'cirrhosis': { name: 'Liver Cirrhosis', category: 'hepatology' },
  'ckd': { name: 'Chronic Kidney Disease', category: 'urology' },
  'cluster_headache': { name: 'Cluster Headache', category: 'NEURO' },
  'coagulopathy': { name: 'Coagulopathy (Hemophilia, VWD, Liver Disease)', category: 'hematology' },
  'collateral_ligament_injury': { name: 'MCL / LCL Injury', category: 'orthopaedics' },
  'colonic_polyp': { name: 'Colonic Polyp', category: 'general_medicine' },
  'colorectal_cancer': { name: 'Colorectal Cancer', category: 'surgical' },
  'common_cold': { name: 'Viral Upper Respiratory Tract Infection', category: 'respiratory' },
  'compression_fracture': { name: 'Vertebral Compression Fracture', category: 'orthopaedics' },
  'compressive_neuropathy': { name: 'Compressive Neuropathy (Ulnar, Radial, Peroneal)', category: 'general_medicine' },
  'congenital_heart_disease': { name: 'Congenital Heart Disease (Tetralogy of Fallot, TGA)', category: 'cardiology' },
  'constipation': { name: 'Constipation', category: 'gastroenterology' },
  'copd_exacerbation': { name: 'COPD Exacerbation', category: 'respiratory' },
  'copd_pulm': { name: 'COPD', category: 'respiratory' },
  'costochondritis': { name: 'Costochondritis', category: 'general_medicine' },
  'covid': { name: 'COVID-19', category: 'infectious' },
  'croup': { name: 'Croup', category: 'general_medicine' },
  'csf_rhinorrhea': { name: 'CSF Rhinorrhea', category: 'general_medicine' },
  'cushings_syndrome': { name: 'Cushing\'s Syndrome / Disease', category: 'endocrinology' },
  'deep_vein_thrombosis': { name: 'Deep Vein Thrombosis (Unilateral)', category: 'surgical' },
  'dehydration': { name: 'Dehydration', category: 'general_medicine' },
  'delirium': { name: 'Delirium (Acute Confusional State)', category: 'psychiatry' },
  'dementia_lewy_body': { name: 'Dementia with Lewy Bodies', category: 'neurology' },
  'dengue': { name: 'Dengue Fever', category: 'infectious-disease' },
  'dental_referred': { name: 'Dental Pain (Referred)', category: 'ent' },
  'depression': { name: 'Depression', category: 'psychiatry' },
  'deviated_septum': { name: 'Deviated Nasal Septum', category: 'ent' },
  'diabetes_insipidus': { name: 'Diabetes Insipidus (Central / Nephrogenic)', category: 'endocrinology' },
  'diabetes_mellitus': { name: 'Diabetes Mellitus (Type 1 / 2)', category: 'endocrinology' },
  'diabetes_mellitus_t1': { name: 'Diabetes Mellitus Type 1', category: 'endocrinology' },
  'diabetes_mellitus_t2': { name: 'Diabetes Mellitus Type 2', category: 'endocrinology' },
  'diabetes_t1': { name: 'Diabetes Mellitus', category: 'endocrinology' },
  'diabetes_t2': { name: 'Diabetes Mellitus', category: 'endocrinology' },
  'diabetic_foot_ulcer': { name: 'Diabetic Foot Ulcer / Neuropathic', category: 'general_medicine' },
  'diabetic_ketoacidosis': { name: 'Diabetic Ketoacidosis', category: 'general_medicine' },
  'diabetic_neuropathy': { name: 'Diabetic Peripheral Neuropathy', category: 'general_medicine' },
  'disc_herniation': { name: 'Intervertebral Disc Herniation', category: 'surgery' },
  'diuretic_overuse': { name: 'Diuretic Overuse / Abuse', category: 'general_medicine' },
  'diverticular_disease': { name: 'Diverticular Disease / Diverticulitis', category: 'general_medicine' },
  'diverticulitis': { name: 'Diverticulitis', category: 'general_medicine' },
  'donovanosis': { name: 'Donovanosis (Granuloma Inguinale)', category: 'general_medicine' },
  'drug_eruption': { name: 'Drug Eruption', category: 'general_medicine' },
  'drug_fever': { name: 'Drug Fever', category: 'general_medicine' },
  'drug_induced': { name: 'Drug-Induced (stimulants)', category: 'general_medicine' },
  'drug_side_effect': { name: 'Medication Side Effect', category: 'general_medicine' },
  'dvt': { name: 'Deep Vein Thrombosis', category: 'general_medicine' },
  'ear_infection': { name: 'Otitis Media / Labyrinthitis', category: 'infectious' },
  'eating_disorder': { name: 'Eating Disorder (Anorexia, Bulimia, BED)', category: 'general_medicine' },
  'ectopic_pregnancy': { name: 'Ectopic Pregnancy', category: 'OB' },
  'eczema': { name: 'Eczema / Atopic Dermatitis', category: 'dermatology' },
  'electrolyte_disorder': { name: 'Electrolyte Disorder', category: 'general_medicine' },
  'electrolyte_imbalance': { name: 'Electrolyte Imbalance', category: 'general' },
  'eosinophilic_esophagitis': { name: 'Eosinophilic Esophagitis', category: 'general_medicine' },
  'epiglottitis': { name: 'Epiglottitis', category: 'respiratory' },
  'esophageal_cancer': { name: 'Esophageal Cancer', category: 'surgical' },
  'esophageal_spasm': { name: 'Esophageal Spasm', category: 'general_medicine' },
  'esophageal_stricture': { name: 'Esophageal Stricture', category: 'general_medicine' },
  'essential_tremor': { name: 'Essential Tremor', category: 'NEURO' },
  'eustachian_tube_dysfunction': { name: 'Eustachian Tube Dysfunction', category: 'general_medicine' },
  'femoral_neck_fracture': { name: 'Femoral Neck Fracture', category: 'orthopaedics' },
  'fibromyalgia': { name: 'Fibromyalgia', category: 'rheumatology' },
  'fixed_drug_eruption': { name: 'Fixed Drug Eruption', category: 'general_medicine' },
  'flat_feet': { name: 'Pes Planus (Flat Feet)', category: 'general_medicine' },
  'food_poisoning': { name: 'Food Poisoning', category: 'general_medicine' },
  'foreign_body': { name: 'Foreign Body Impaction', category: 'general_medicine' },
  'foreign_body_aspiration': { name: 'Foreign Body Aspiration', category: 'general_medicine' },
  'foreign_body_ear': { name: 'Foreign Body in Ear', category: 'ent' },
  'foreign_body_nose': { name: 'Foreign Body (especially pediatric)', category: 'ent' },
  'fracture': { name: 'Lower Limb Fracture (Acute)', category: 'orthopaedics' },
  'fracture_clavicle': { name: 'Clavicle Fracture', category: 'orthopaedics' },
  'frontotemporal_dementia': { name: 'Frontotemporal Dementia', category: 'neurology' },
  'frozen_shoulder': { name: 'Adhesive Capsulitis (Frozen Shoulder)', category: 'general_medicine' },
  'functional_dyspepsia': { name: 'Functional Dyspepsia', category: 'general_medicine' },
  'functional_tremor': { name: 'Functional (Psychogenic) Tremor', category: 'general_medicine' },
  'fungal_infection': { name: 'Fungal Skin Infection', category: 'infectious' },
  'fungal_pneumonia': { name: 'Fungal Pneumonia', category: 'respiratory' },
  'gastritis': { name: 'Acute Gastritis', category: 'gastroenterology' },
  'gastroenteritis': { name: 'Acute Gastroenteritis', category: 'ent' },
  'gastroparesis': { name: 'Gastroparesis (Diabetic / Idiopathic)', category: 'gastroenterology' },
  'generalized_anxiety_disorder': { name: 'Generalized Anxiety Disorder (GAD)', category: 'psychiatry' },
  'gerd': { name: 'GERD', category: 'gastroenterology' },
  'gi_disorder': { name: 'Gastrointestinal Disorder (PUD, IBD, Gastritis)', category: 'general_medicine' },
  'giardiasis': { name: 'Giardiasis (Parasitic)', category: 'general_medicine' },
  'glenohumeral_osteoarthritis': { name: 'Glenohumeral Osteoarthritis', category: 'orthopaedics' },
  'gout': { name: 'Gout', category: 'rheumatology' },
  'guillain_barre': { name: 'Guillain-Barre Syndrome', category: 'NEURO' },
  'hallux_valgus': { name: 'Hallux Valgus (Bunion)', category: 'general_medicine' },
  'head_injury': { name: 'Head Injury / Concussion', category: 'emergency' },
  'heart_failure': { name: 'Heart Failure (Fluid Retention / Edema)', category: 'cardiology' },
  'heart_failure_card': { name: 'Heart Failure', category: 'cardiology' },
  'heat_exhaustion': { name: 'Heat Exhaustion / Heat Stroke', category: 'neurology' },
  'hemarthrosis': { name: 'Hemarthrosis', category: 'general_medicine' },
  'hemorrhagic_fever': { name: 'Hemorrhagic Fever (Dengue, Yellow Fever, Ebola)', category: 'general_medicine' },
  'hemorrhoids': { name: 'Hemorrhoids (Internal / External)', category: 'surgical' },
  'hepatic_encephalopathy': { name: 'Hepatic Encephalopathy (Asterixis)', category: 'general_medicine' },
  'hepatitis': { name: 'Viral Hepatitis', category: 'PAED' },
  'hereditary_hemorrhagic_telangiectasia': { name: 'Hereditary Hemorrhagic Telangiectasia (Osler-Weber-Rendu)', category: 'general_medicine' },
  'hernia': { name: 'Hernia (strangulated)', category: 'surgery' },
  'herpes_simplex': { name: 'Genital Herpes Simplex (HSV-1 / HSV-2)', category: 'general_medicine' },
  'herpes_zoster': { name: 'Herpes Zoster (prodromal)', category: 'dermatology' },
  'hiatal_hernia': { name: 'Hiatal Hernia', category: 'surgical' },
  'hip_osteoarthritis': { name: 'Hip Osteoarthritis', category: 'orthopaedics' },
  'hiv': { name: 'HIV / AIDS', category: 'PAED' },
  'hiv_enteropathy': { name: 'HIV Enteropathy', category: 'infectious' },
  'hypercalcemia': { name: 'Hypercalcemia', category: 'endocrinology' },
  'hyperemesis_gravidarum': { name: 'Hyperemesis Gravidarum (Pregnancy)', category: 'OB' },
  'hypertension': { name: 'Hypertensive Headache', category: 'general_medicine' },
  'hyperthyroidism': { name: 'Hyperthyroidism', category: 'endocrinology' },
  'hypoglycemia': { name: 'Hypoglycemia', category: 'general_medicine' },
  'hypokalemia': { name: 'Hypokalemia', category: 'general_medicine' },
  'hypothyroidism': { name: 'Hypothyroidism', category: 'endocrinology' },
  'ibd': { name: 'Inflammatory Bowel Disease', category: 'surgery' },
  'ibs': { name: 'Irritable Bowel Syndrome', category: 'surgery' },
  'infectious_colitis': { name: 'Infectious Colitis (Shigella, Campylobacter, E. coli O157)', category: 'infectious' },
  'infective_endocarditis': { name: 'Infective Endocarditis', category: 'general_medicine' },
  'inferior_vena_cava_obstruction': { name: 'IVC Obstruction / Compression', category: 'surgery' },
  'inflammatory_bowel_disease': { name: 'Inflammatory Bowel Disease (Ulcerative Colitis, Crohn\'s)', category: 'gastroenterology' },
  'inguinal_hernia': { name: 'Inguinal Hernia (Referred)', category: 'surgical' },
  'insufficient_intake': { name: 'Reduced Oral Intake (Dementia, Disability, Neglect)', category: 'neurology' },
  'insulinoma': { name: 'Insulinoma (Hypoglycemia-Driven Overeating)', category: 'general_medicine' },
  'intestinal_tuberculosis': { name: 'Intestinal TB', category: 'infectious' },
  'intracranial_hemorrhage': { name: 'Intracranial Hemorrhage', category: 'general_medicine' },
  'irritable_bowel_syndrome': { name: 'Irritable Bowel Syndrome (IBS)', category: 'gastroenterology' },
  'ischemic_colitis': { name: 'Ischemic Colitis', category: 'general_medicine' },
  'knee_osteoarthritis': { name: 'Knee Osteoarthritis', category: 'orthopaedics' },
  'labral_tear': { name: 'Acetabular Labral Tear', category: 'ent' },
  'labyrinthitis': { name: 'Labyrinthitis', category: 'general_medicine' },
  'lactose_intolerance': { name: 'Lactose Intolerance', category: 'general_medicine' },
  'lipedema': { name: 'Lipedema (Bilateral Lower Extremities, Painful)', category: 'general_medicine' },
  'liver_cirrhosis': { name: 'Liver Cirrhosis (Ascites)', category: 'general_medicine' },
  'lung_cancer': { name: 'Lung Cancer', category: 'oncology' },
  'lymphadenitis': { name: 'Cervical Lymphadenitis', category: 'general_medicine' },
  'lymphedema': { name: 'Lymphoedema', category: 'general_medicine' },
  'lymphogranuloma_venereum': { name: 'Lymphogranuloma Venereum (LGV)', category: 'general_medicine' },
  'lymphoma': { name: 'Cutaneous Lymphoma', category: 'PAED' },
  'major_depressive_disorder': { name: 'Major Depressive Disorder (comorbid)', category: 'psychiatry' },
  'malabsorption': { name: 'Malabsorption Syndrome', category: 'general_medicine' },
  'malaria': { name: 'Malaria', category: 'PAED' },
  'malignancy': { name: 'Underlying Malignancy', category: 'general_medicine' },
  'malignancy_fever': { name: 'Malignancy-Related Fever', category: 'general_medicine' },
  'malignancy_metastasis': { name: 'Cervical Spine Metastasis / Tumor', category: 'orthopaedics' },
  'malnutrition': { name: 'Malnutrition / Hypoalbuminemia', category: 'PAED' },
  'mastoiditis': { name: 'Mastoiditis', category: 'ent' },
  'measles': { name: 'Measles', category: 'PAED' },
  'mechanical_neck_pain': { name: 'Mechanical Neck Pain (Cervical Strain)', category: 'general_medicine' },
  'medial_meniscus_tear': { name: 'Medial Meniscus Tear', category: 'orthopaedics' },
  'medication_overuse': { name: 'Medication Overuse Headache', category: 'general_medicine' },
  'medication_side_effect': { name: 'Medication-Induced Diarrhoea', category: 'general_medicine' },
  'menieres': { name: 'Meniere Disease', category: 'general_medicine' },
  'menieres_disease': { name: 'Meniere\'s Disease', category: 'general_medicine' },
  'meningitis': { name: 'Meningitis', category: 'PAED' },
  'meningitis_encephalitis': { name: 'Meningitis / Encephalitis', category: 'infectious' },
  'meningococcal': { name: 'Meningococcal Rash', category: 'dermatology' },
  'metatarsalgia': { name: 'Metatarsalgia', category: 'general_medicine' },
  'methemoglobinemia': { name: 'Methemoglobinemia (Drug-Induced, Congenital)', category: 'pediatrics' },
  'migraine': { name: 'Migraine', category: 'neurology' },
  'migraine_vestibular': { name: 'Vestibular Migraine', category: 'neurology' },
  'mild_cognitive_impairment': { name: 'Mild Cognitive Impairment (MCI)', category: 'geriatrics' },
  'mitral_valve_prolapse': { name: 'Mitral Valve Prolapse', category: 'general_medicine' },
  'mixed_incontinence': { name: 'Mixed Incontinence', category: 'general_medicine' },
  'morton_neuroma': { name: 'Morton\'s Neuroma (Interdigital)', category: 'general_medicine' },
  'multiple_sclerosis': { name: 'Multiple Sclerosis', category: 'neurology' },
  'muscular_strain': { name: 'Muscular / Ligamentous Strain', category: 'orthopaedics' },
  'musculoskeletal': { name: 'Musculoskeletal Chest Pain', category: 'general_medicine' },
  'myasthenia_gravis': { name: 'Myasthenia Gravis', category: 'NEURO' },
  'myopathy': { name: 'Myopathy / Muscular Dystrophy (Waddling Gait)', category: 'NEURO' },
  'nasal_foreign_body': { name: 'Nasal Foreign Body (Pediatric)', category: 'ent' },
  'nasal_polyp': { name: 'Nasal Polyps', category: 'ent' },
  'nasal_trauma': { name: 'Nasal Trauma', category: 'ent' },
  'nasal_tumor': { name: 'Nasal / Sinonasal Tumor', category: 'ent' },
  'nasopharyngeal_cancer': { name: 'Nasopharyngeal Carcinoma', category: 'general_medicine' },
  'nephrotic_syndrome': { name: 'Nephrotic Syndrome', category: 'nephrology' },
  'neurological_bladder': { name: 'Neurogenic Bladder (Spinal Cord, MS, Diabetes)', category: 'neurology' },
  'noise_induced_hearing_loss': { name: 'Noise-Induced Hearing Loss', category: 'ent' },
  'normal_pressure_hydrocephalus': { name: 'Normal Pressure Hydrocephalus (Magnetic Gait)', category: 'general_medicine' },
  'oa': { name: 'Osteoarthritis', category: 'orthopaedics' },
  'oa_spine': { name: 'Osteoarthritis (Spine)', category: 'orthopaedics' },
  'obesity': { name: 'Obesity (Caloric Excess + Sedentary Lifestyle)', category: 'ent' },
  'obsessive_compulsive_disorder': { name: 'Obsessive-Compulsive Disorder (OCD)', category: 'PSYCH' },
  'orthostatic_hypotension': { name: 'Orthostatic Hypotension', category: 'orthopaedics' },
  'osgood_schlatter': { name: 'Osgood-Schlatter Disease (Adolescent)', category: 'ent' },
  'osteoarthritis_hip_knee': { name: 'Osteoarthritis (Hip/Knee) - Antalgic Gait', category: 'orthopaedics' },
  'otitis_externa': { name: 'Otitis Externa / Swimmer\'s Ear', category: 'ent' },
  'ototoxic_drugs': { name: 'Ototoxic Medications', category: 'ent' },
  'ovarian_cancer': { name: 'Ovarian Cancer (Persistent Bloating - New Onset >50)', category: 'oncology' },
  'overactive_bladder': { name: 'Urge Incontinence / Overactive Bladder', category: 'URO' },
  'overflow_incontinence': { name: 'Overflow Incontinence (Chronic Retention)', category: 'ent' },
  'pancreatic_insufficiency': { name: 'Exocrine Pancreatic Insufficiency', category: 'general_medicine' },
  'pancreatitis': { name: 'Pancreatitis', category: 'surgery' },
  'panic_disorder': { name: 'Panic Disorder', category: 'PSYCH' },
  'papillary_necrosis': { name: 'Renal Papillary Necrosis', category: 'urology' },
  'parkinson_disease': { name: 'Parkinson Disease', category: 'neurology' },
  'patellar_tendinopathy': { name: 'Patellar Tendinopathy (Jumper\'s Knee)', category: 'general_medicine' },
  'patellofemoral_pain': { name: 'Patellofemoral Pain Syndrome', category: 'general_medicine' },
  'pcos': { name: 'Polycystic Ovary Syndrome (PCOS)', category: 'gynecology' },
  'pelvic_organ_prolapse': { name: 'Pelvic Organ Prolapse (Cystocele, Rectocele)', category: 'GYN' },
  'peptic_ulcer': { name: 'Peptic Ulcer Disease', category: 'surgical' },
  'peptic_ulcer_disease': { name: 'Peptic Ulcer Disease', category: 'gastroenterology' },
  'pericarditis': { name: 'Pericarditis', category: 'general_medicine' },
  'peripheral_neuropathy': { name: 'Peripheral Neuropathy (Sensory Ataxia)', category: 'NEURO' },
  'peripheral_neuropathy_other': { name: 'Other Peripheral Neuropathy (Alcohol, Toxin)', category: 'general_medicine' },
  'pharyngitis': { name: 'Pharyngitis / Tonsillitis', category: 'ent' },
  'pheochromocytoma': { name: 'Pheochromocytoma', category: 'general_medicine' },
  'physiologic_tremor': { name: 'Exaggerated Physiologic Tremor (Fatigue, Caffeine, Stress)', category: 'general_medicine' },
  'pid': { name: 'Pelvic Inflammatory Disease', category: 'gynecology' },
  'plantar_fasciitis': { name: 'Plantar Fasciitis', category: 'rheumatology' },
  'pleural_effusion': { name: 'Pleural Effusion', category: 'general_medicine' },
  'pleurisy': { name: 'Pleurisy', category: 'general_medicine' },
  'plummer_vinson': { name: 'Plummer-Vinson Syndrome', category: 'general_medicine' },
  'pneumonia': { name: 'Severe Pneumonia', category: 'respiratory' },
  'pneumonia_pulm': { name: 'Pneumonia', category: 'respiratory' },
  'pneumothorax': { name: 'Pneumothorax', category: 'surgical' },
  'polymyalgia_rheumatica': { name: 'Polymyalgia Rheumatica', category: 'general_medicine' },
  'popliteal_cyst': { name: 'Popliteal (Baker\'s) Cyst', category: 'general_medicine' },
  'post_concussion': { name: 'Post-Concussion Syndrome', category: 'general_medicine' },
  'post_infectious': { name: 'Post-Infectious Fatigue', category: 'infectious' },
  'post_nasal_drip': { name: 'Post-Nasal Drip / UACS', category: 'ent' },
  'post_traumatic_stress_disorder': { name: 'Post-Traumatic Stress Disorder (PTSD)', category: 'psychiatry' },
  'posterior_epistaxis': { name: 'Posterior Epistaxis', category: 'general_medicine' },
  'postoperative_incontinence': { name: 'Post-Prostatectomy / Post-Pelvic Surgery', category: 'urology' },
  'pregnancy': { name: 'Pregnancy / Hyperemesis Gravidarum', category: 'obstetrics' },
  'prepatellar_bursitis': { name: 'Prepatellar Bursitis', category: 'general_medicine' },
  'presbycusis': { name: 'Presbycusis (Age-Related)', category: 'ent' },
  'primary_insomnia': { name: 'Primary Insomnia (Psychophysiological)', category: 'general_medicine' },
  'prostate_cancer': { name: 'Prostate Cancer (Advanced)', category: 'urology' },
  'prostate_enlargement': { name: 'Benign Prostatic Hyperplasia', category: 'urology' },
  'prostatism': { name: 'Benign Prostatic Hyperplasia (Nocturia)', category: 'general_medicine' },
  'pseudotumor': { name: 'Idiopathic Intracranial HTN', category: 'general_medicine' },
  'psoas_abscess': { name: 'Psoas Abscess', category: 'infectious' },
  'psoriasis': { name: 'Psoriasis', category: 'dermatology' },
  'psoriatic_arthritis': { name: 'Psoriatic Arthritis', category: 'rheumatology' },
  'psychogenic_polydipsia': { name: 'Psychogenic Polydipsia (Primary Polydipsia)', category: 'general_medicine' },
  'pulmonary_embolism': { name: 'Pulmonary Embolism', category: 'respiratory' },
  'pulmonary_hypertension': { name: 'Pulmonary Hypertension', category: 'respiratory' },
  'pvc': { name: 'Premature Ventricular Contractions', category: 'ent' },
  'pyelonephritis': { name: 'Pyelonephritis', category: 'general_medicine' },
  'pyloric_stenosis': { name: 'Infantile Hypertrophic Pyloric Stenosis', category: 'pediatrics' },
  'radiation_proctitis': { name: 'Radiation Proctitis', category: 'general_medicine' },
  'reactive_arthritis': { name: 'Reactive Arthritis', category: 'rheumatology' },
  'rectal_prolapse': { name: 'Rectal Prolapse (Mucosal Friability)', category: 'surgical' },
  'referred_cardiac': { name: 'Referred Cardiac Pain (Left Shoulder)', category: 'cardiology' },
  'referred_lumbar_spine': { name: 'Referred from Lumbar Spine (L1-L2 Radiculopathy)', category: 'orthopaedics' },
  'renal_abscess': { name: 'Renal / Perinephric Abscess', category: 'infectious' },
  'renal_colic': { name: 'Renal Colic / Ureteric Stone', category: 'urology' },
  'renal_disease': { name: 'Chronic Kidney Disease', category: 'urology' },
  'renal_infarction': { name: 'Renal Infarction / Thromboembolism', category: 'urology' },
  'renal_trauma': { name: 'Renal Trauma / Contusion', category: 'urology' },
  'respiratory_failure': { name: 'Respiratory Failure', category: 'respiratory' },
  'restless_legs_syndrome': { name: 'Restless Legs Syndrome / PLMD', category: 'general_medicine' },
  'rheumatic_fever': { name: 'Acute Rheumatic Fever', category: 'general_medicine' },
  'rheumatoid_arthritis': { name: 'Rheumatoid Arthritis', category: 'rheumatology' },
  'rhinitis_medicamentosa': { name: 'Rhinitis Medicamentosa (Decongestant Overuse)', category: 'ent' },
  'rickettsial': { name: 'Rickettsial Infection', category: 'infectious' },
  'rotator_cuff_tendinopathy': { name: 'Rotator Cuff Tendinopathy / Tear', category: 'ent' },
  'sacroiliitis': { name: 'Sacroiliitis', category: 'general_medicine' },
  'scabies': { name: 'Scabies', category: 'dermatology' },
  'schizophrenia': { name: 'Schizophrenia (Command Hallucinations)', category: 'psychiatry' },
  'scleroderma': { name: 'Systemic Sclerosis', category: 'general_medicine' },
  'scurvy': { name: 'Scurvy', category: 'general_medicine' },
  'seizure': { name: 'Post-Ictal State (Todd\'s Paresis / Aphasia)', category: 'neurology' },
  'sepsis': { name: 'Sepsis', category: 'infectious_disease' },
  'septic_arthritis': { name: 'Septic Arthritis', category: 'general_medicine' },
  'septic_arthritis_hip': { name: 'Septic Arthritis of Hip', category: 'general_medicine' },
  'septic_arthritis_knee': { name: 'Septic Arthritis of Knee', category: 'general_medicine' },
  'shoulder_dislocation': { name: 'Glenohumeral Dislocation / Instability', category: 'general_medicine' },
  'sickle_cell': { name: 'Sickle Cell Crisis', category: 'hematology' },
  'sinusitis': { name: 'Sinusitis', category: 'ent' },
  'sjogrens_syndrome': { name: 'Sjogren\'s Syndrome (Dry Mouth)', category: 'rheumatology' },
  'sle': { name: 'Systemic Lupus Erythematosus', category: 'general_medicine' },
  'sleep_apnea': { name: 'Obstructive Sleep Apnea', category: 'general_medicine' },
  'small_intestinal_bacterial_overgrowth': { name: 'SIBO (Small Intestinal Bacterial Overgrowth)', category: 'infectious' },
  'social_anxiety': { name: 'Social Anxiety Disorder', category: 'psychiatry' },
  'specific_phobia': { name: 'Specific Phobia', category: 'psychiatry' },
  'spinal_infection': { name: 'Spinal Infection / Discitis', category: 'infectious' },
  'spinal_metastasis': { name: 'Spinal Metastasis', category: 'general_medicine' },
  'spinal_stenosis': { name: 'Spinal Stenosis', category: 'general_medicine' },
  'splenic_infarction': { name: 'Splenic Infarction (Left Flank)', category: 'general_medicine' },
  'squamous_cell_carcinoma': { name: 'Squamous Cell Carcinoma (Non-Healing Ulcer)', category: 'dermatology' },
  'stress_fracture': { name: 'Femoral Neck Stress Fracture', category: 'orthopaedics' },
  'stress_fracture_metatarsal': { name: 'Metatarsal Stress Fracture (March Fracture)', category: 'orthopaedics' },
  'stress_incontinence': { name: 'Stress Urinary Incontinence', category: 'URO' },
  'stroke': { name: 'Stroke / Hemiparesis', category: 'neurology' },
  'stroke_pseudo': { name: 'Pseudobulbar Palsy / Stroke', category: 'neurology' },
  'stroke_tia': { name: 'TIA / Stroke', category: 'neurology' },
  'subacromial_bursitis': { name: 'Subacromial Bursitis', category: 'general_medicine' },
  'subarachnoid_hemorrhage': { name: 'Subarachnoid Hemorrhage', category: 'neurology' },
  'substance_induced': { name: 'Substance-Induced Depression / Intoxication', category: 'psychiatry' },
  'substance_induced_anxiety': { name: 'Substance-Induced Anxiety (Caffeine, Stimulants, Withdrawal)', category: 'psychiatry' },
  'substance_use': { name: 'Substance-Induced (Caffeine, Alcohol, Stimulants)', category: 'general_medicine' },
  'svt': { name: 'Supraventricular Tachycardia', category: 'CARD' },
  'syphilis': { name: 'Syphilis (Primary Chancre)', category: 'general_medicine' },
  'tarsal_tunnel_syndrome': { name: 'Tarsal Tunnel Syndrome', category: 'general_medicine' },
  'tb_pulm': { name: 'Pulmonary Tuberculosis', category: 'respiratory' },
  'temporal_arteritis': { name: 'Giant Cell Arteritis', category: 'general_medicine' },
  'temporomandibular_disorder': { name: 'Temporomandibular Joint Disorder', category: 'orthopaedics' },
  'tension_headache': { name: 'Tension Headache', category: 'NEURO' },
  'thyroid_disorder': { name: 'Myxedema (Hypothyroidism)', category: 'endocrinology' },
  'tmj_disorder': { name: 'TMJ Disorder', category: 'general_medicine' },
  'transient_ischemic_attack': { name: 'Transient Ischemic Attack (TIA)', category: 'ent' },
  'trauma': { name: 'Traumatic Ulcer', category: 'emergency' },
  'trochanteric_bursitis': { name: 'Greater Trochanteric Bursitis', category: 'general_medicine' },
  'typhoid': { name: 'Typhoid Fever', category: 'infectious' },
  'uremia': { name: 'Uremia (CKD)', category: 'general_medicine' },
  'ureteropelvic_junction_obstruction': { name: 'UPJ Obstruction (Hydronephrosis)', category: 'surgery' },
  'uti': { name: 'Urinary Tract Infection', category: 'PAED' },
  'vascular_dementia': { name: 'Vascular Dementia', category: 'neurology' },
  'vascular_malformation': { name: 'Vascular Malformation (Pulsatile)', category: 'general_medicine' },
  'vasomotor_rhinitis': { name: 'Vasomotor (Non-Allergic) Rhinitis', category: 'general_medicine' },
  'vertebrobasilar_insufficiency': { name: 'Vertebrobasilar Insufficiency / TIA', category: 'general_medicine' },
  'vertigo': { name: 'Vestibular Disorder / Vertigo', category: 'general_medicine' },
  'vestibular_disorder': { name: 'Vestibular Disorder', category: 'general_medicine' },
  'vestibular_neuritis': { name: 'Vestibular Neuritis', category: 'general_medicine' },
  'viral_arthritis': { name: 'Viral Arthritis (e.g. Chikungunya)', category: 'infectious' },
  'viral_hepatitis': { name: 'Viral Hepatitis', category: 'infectious' },
  'vitamin_b12_deficiency': { name: 'Vitamin B12 Deficiency', category: 'hematology' },
  'vitamin_deficiency': { name: 'Vitamin B12 / D Deficiency', category: 'general_medicine' },
  'wax_impaction': { name: 'Wax Impaction', category: 'general_medicine' },
  'whiplash': { name: 'Whiplash-Associated Disorder', category: 'general_medicine' },
  'whooping_cough': { name: 'Pertussis', category: 'general_medicine' },
};

export function getDiseaseCategory(diseaseId: string): string {
  const profile = DISEASE_PROFILES[diseaseId];
  if (!profile) return 'general_medicine';
  const cat = profile.category.toLowerCase();
  // Normalize KG-specific category names
  const norm: Record<string, string> = {
    'paed': 'pediatrics', 'ped': 'pediatrics',
    'neuro': 'neurology', 'card': 'cardiology',
    'psych': 'psychiatry', 'uro': 'urology',
    'gyn': 'gynecology', 'ob': 'obstetrics',
    'surgical': 'surgery', 'im': 'internal_medicine',
    'infectious_disease': 'infectious', 'infectious-disease': 'infectious',
    'general': 'general_medicine', 'emergency_medicine': 'emergency',
    'ent': 'ent',
  };
  return norm[cat] || cat;
}

export function getDiseaseName(diseaseId: string): string {
  return DISEASE_PROFILES[diseaseId]?.name || diseaseId.replace(/_/g, ' ');
}

// Stat: 401 diseases
//   general_medicine: 150
//   ent: 32
//   orthopaedics: 22
//   infectious: 19
//   neurology: 17
//   respiratory: 16
//   psychiatry: 16
//   surgical: 15
//   urology: 11
//   endocrinology: 11
//   cardiology: 10
//   PAED: 10
//   gastroenterology: 8
//   rheumatology: 8
//   dermatology: 7
//   surgery: 7
//   NEURO: 7
//   general: 4
//   hematology: 3
//   emergency: 3
//   PSYCH: 3
//   oncology: 2
//   infectious_disease: 2
//   OB: 2
//   gynecology: 2
//   URO: 2
//   pediatrics: 2
//   infectious-disease: 1
//   emergency_medicine: 1
//   IM: 1
//   obstetrics: 1
//   CARD: 1
//   nephrology: 1
//   hepatology: 1
//   geriatrics: 1
//   GYN: 1
//   gynaecology: 1
