export interface HistoryFeature {
  id: string;
  label: string;
  description?: string;
  type: 'boolean' | 'select' | 'multi_select' | 'number' | 'text';
  options?: string[];
  category: 'symptom_detail' | 'risk_factor' | 'exam_finding' | 'social' | 'occupation' | 'constitutional' | 'lab_finding';
  diseaseWeights: Record<string, number>;
  condition?: string;
  negativePredictorFor?: { diseaseId: string; reduction: number }[];
  isRedFlag?: boolean;
  redFlagSeverity?: 'critical' | 'high' | 'moderate';
  redFlagMessage?: string;
}

const HISTORY_FEATURE_REGISTRY: Record<string, HistoryFeature> = {
  // ── COUGH FEATURES ──
  cough_productive: {
    id: 'cough_productive',
    label: 'Productive Cough',
    description: 'Cough producing sputum/phlegm',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { tb_pulm: 2, pneumonia_pulm: 4, asthma_pulm: -3, copd_pulm: 3, bronchiectasis: 4, lung_cancer: 1 },
  },
  sputum_blood: {
    id: 'sputum_blood',
    label: 'Hemoptysis (Blood in Sputum)',
    description: 'Coughing up blood or blood-stained sputum',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { tb_pulm: 5, pneumonia_pulm: 2, lung_cancer: 6, bronchiectasis: 4, pulmonary_embolism: 2 },
    isRedFlag: true,
    redFlagSeverity: 'high',
    redFlagMessage: 'Hemoptysis requires investigation — consider TB, lung cancer, bronchiectasis',
  },
  sputum_color_yellow: {
    id: 'sputum_color_yellow',
    label: 'Yellow/Yellowish Sputum',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { pneumonia_pulm: 3, bronchiectasis: 3, copd_pulm: 2 },
  },
  sputum_color_green: {
    id: 'sputum_color_green',
    label: 'Green Sputum',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { pneumonia_pulm: 3, bronchiectasis: 4, copd_pulm: 3 },
  },
  sputum_color_rusty: {
    id: 'sputum_color_rusty',
    label: 'Rusty-Coloured Sputum',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { pneumonia_pulm: 5, tb_pulm: 1 },
  },
  sputum_blood_stained: {
    id: 'sputum_blood_stained',
    label: 'Blood-Stained Sputum',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { tb_pulm: 5, lung_cancer: 5, bronchiectasis: 3 },
  },
  cough_duration_gt_2weeks: {
    id: 'cough_duration_gt_2weeks',
    label: 'Cough >2 Weeks Duration',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { tb_pulm: 6, asthma_pulm: 1, copd_pulm: 2, lung_cancer: 3, post_nasal_drip: 3 },
  },
  cough_duration_gt_8weeks: {
    id: 'cough_duration_gt_8weeks',
    label: 'Chronic Cough (>8 Weeks)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { tb_pulm: 5, asthma_pulm: 2, copd_pulm: 2, gerd: 3, post_nasal_drip: 4, bronchiectasis: 3, lung_cancer: 2 },
  },
  night_cough: {
    id: 'night_cough',
    label: 'Nocturnal Cough / Worse at Night',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { asthma_pulm: 4, gerd: 3, heart_failure_card: 2, post_nasal_drip: 1 },
  },
  cough_wheeze: {
    id: 'cough_wheeze',
    label: 'Associated Wheezing',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { asthma_pulm: 6, copd_pulm: 4, bronchiectasis: 2, anaphylaxis: 2, foreign_body_aspiration: 3 },
  },
  cough_exercise_induced: {
    id: 'cough_exercise_induced',
    label: 'Exercise-Induced Cough',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { asthma_pulm: 5, copd_pulm: 1 },
  },
  cough_positional: {
    id: 'cough_positional',
    label: 'Cough Worse When Lying Down',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { gerd: 5, heart_failure_card: 3, post_nasal_drip: 2 },
  },

  // ── FEVER FEATURES ──
  rigors: {
    id: 'rigors',
    label: 'Rigors (Severe Shaking Chills)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { malaria: 5, sepsis: 4, pneumonia_pulm: 3, uti: 3, infective_endocarditis: 2 },
    isRedFlag: true,
    redFlagSeverity: 'high',
    redFlagMessage: 'Rigors suggest significant systemic infection — consider malaria, sepsis, pneumonia',
  },
  fever_pattern_continuous: {
    id: 'fever_pattern_continuous',
    label: 'Continuous Fever',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { typhoid: 4, pneumonia_pulm: 2, uti: 2 },
  },
  fever_pattern_intermittent: {
    id: 'fever_pattern_intermittent',
    label: 'Intermittent Fever',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { malaria: 4, sepsis: 2, abscess: 2 },
  },
  fever_pattern_relapsing: {
    id: 'fever_pattern_relapsing',
    label: 'Relapsing Fever',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { malaria: 3, brucellosis: 4, typhoid: 1, lymphoma: 3 },
  },
  fever_night_sweats: {
    id: 'fever_night_sweats',
    label: 'Night Sweats',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { tb_pulm: 6, lymphoma: 4, hiv: 3, infective_endocarditis: 2, brucellosis: 3, malignancy: 2 },
    isRedFlag: true,
    redFlagSeverity: 'moderate',
    redFlagMessage: 'Night sweats — consider TB, lymphoma, HIV',
  },

  // ── CHEST PAIN FEATURES ──
  chest_pain_crushing: {
    id: 'chest_pain_crushing',
    label: 'Crushing / Squeezing Chest Pain',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { chest_pain: 6, anxiety_panic: 1, costochondritis: 1 },
    isRedFlag: true,
    redFlagSeverity: 'critical',
    redFlagMessage: 'Crushing chest pain — HIGH RISK ACS',
  },
  chest_pain_radiation_arm: {
    id: 'chest_pain_radiation_arm',
    label: 'Pain Radiating to Left Arm/Jaw',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { chest_pain: 6 },
    isRedFlag: true,
    redFlagSeverity: 'critical',
    redFlagMessage: 'Radiation of chest pain to arm/jaw — HIGH RISK ACS',
  },
  chest_pain_pleuritic: {
    id: 'chest_pain_pleuritic',
    label: 'Pleuritic Chest Pain (Sharp, Worse on Breathing)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { pneumonia_pulm: 4, pulmonary_embolism: 4, pericarditis: 5, pleurisy: 4, pneumothorax: 3 },
  },
  chest_pain_positional: {
    id: 'chest_pain_positional',
    label: 'Positional Chest Pain (Better Leaning Forward)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { pericarditis: 5 },
  },
  chest_pain_exertional: {
    id: 'chest_pain_exertional',
    label: 'Exertional Chest Pain',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { chest_pain: 5, aortic_stenosis: 2, hypertrophic_cardiomyopathy: 2 },
  },
  associated_sweating: {
    id: 'associated_sweating',
    label: 'Associated Sweating / Diaphoresis',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { chest_pain: 4, anxiety_panic: 3, hypoglycemia: 2, sepsis: 2 },
  },

  // ── DYSPNEA FEATURES ──
  orthopnea: {
    id: 'orthopnea',
    label: 'Orthopnea (Breathless When Lying Flat)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { heart_failure_card: 6, copd_pulm: 2, asthma_pulm: 1 },
  },
  pnd: {
    id: 'pnd',
    label: 'Paroxysmal Nocturnal Dyspnea',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { heart_failure_card: 6 },
  },
  wheeze: {
    id: 'wheeze',
    label: 'Audible Wheeze',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { asthma_pulm: 6, copd_pulm: 4, anaphylaxis: 3, foreign_body_aspiration: 3, bronchiectasis: 2 },
  },
  stridor: {
    id: 'stridor',
    label: 'Stridor (High-Pitched Breathing Sound)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { croup: 5, epiglottitis: 5, foreign_body_aspiration: 5, anaphylaxis: 3 },
    isRedFlag: true,
    redFlagSeverity: 'critical',
    redFlagMessage: 'Stridor indicates upper airway obstruction — emergency',
  },

  // ── CONSTITUTIONAL ──
  weight_loss_unintentional: {
    id: 'weight_loss_unintentional',
    label: 'Unintentional Weight Loss',
    type: 'boolean',
    category: 'constitutional',
    diseaseWeights: { tb_pulm: 6, malignancy: 5, hyperthyroidism: 3, diabetes_t1: 3, hiv: 4, depression: 2, ibd: 2 },
    isRedFlag: true,
    redFlagSeverity: 'moderate',
    redFlagMessage: 'Unintentional weight loss — consider TB, malignancy, HIV, hyperthyroidism',
  },
  night_sweats: {
    id: 'night_sweats',
    label: 'Night Sweats (Soaking)',
    type: 'boolean',
    category: 'constitutional',
    diseaseWeights: { tb_pulm: 6, lymphoma: 4, hiv: 3, infective_endocarditis: 2, brucellosis: 2, malignancy: 2 },
  },
  anorexia: {
    id: 'anorexia',
    label: 'Loss of Appetite',
    type: 'boolean',
    category: 'constitutional',
    diseaseWeights: { tb_pulm: 3, malignancy: 3, depression: 3, liver_disease: 2, ckd: 2, heart_failure_card: 1, appendicitis: 6, gastroenteritis: 3, typhoid: 4, hepatitis: 3 },
  },
  fatigue_profound: {
    id: 'fatigue_profound',
    label: 'Profound/Unusual Fatigue',
    type: 'boolean',
    category: 'constitutional',
    diseaseWeights: { anemia: 4, depression: 3, hypothyroidism: 3, diabetes_t2: 2, ckd: 2, tb_pulm: 2, sle: 2, chronic_fatigue: 4 },
  },

  // ── TB-SPECIFIC ──
  tb_contact: {
    id: 'tb_contact',
    label: 'Known TB Contact',
    type: 'boolean',
    category: 'risk_factor',
    diseaseWeights: { tb_pulm: 7 },
    negativePredictorFor: [{ diseaseId: 'tb_pulm', reduction: 4 }],
  },
  previous_tb: {
    id: 'previous_tb',
    label: 'Previous TB Treatment',
    type: 'boolean',
    category: 'risk_factor',
    diseaseWeights: { tb_pulm: 3, bronchiectasis: 2 },
  },

  // ── HIV ──
  hiv_positive: {
    id: 'hiv_positive',
    label: 'Known HIV Positive',
    type: 'boolean',
    category: 'risk_factor',
    diseaseWeights: { tb_pulm: 4, pneumonia_pulm: 2, hiv: 5, meningitis: 2, malignancy: 1 },
  },

  // ── SMOKING ──
  smoking_current: {
    id: 'smoking_current',
    label: 'Current Smoker',
    type: 'boolean',
    category: 'risk_factor',
    diseaseWeights: { copd_pulm: 6, lung_cancer: 6, pneumonia_pulm: 2, chest_pain: 3, peptic_ulcer: 1 },
  },
  smoking_pack_years_gt_20: {
    id: 'smoking_pack_years_gt_20',
    label: 'Smoking History >20 Pack-Years',
    type: 'boolean',
    category: 'risk_factor',
    diseaseWeights: { lung_cancer: 7, copd_pulm: 5, chest_pain: 3 },
  },

  // ── ABDOMINAL ──
  abdominal_pain_rlq: {
    id: 'abdominal_pain_rlq',
    label: 'Pain Localized to Right Lower Quadrant',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { appendicitis: 6, ibd: 1, ectopic_pregnancy: 2, pid: 1 },
  },
  abdominal_pain_ruq: {
    id: 'abdominal_pain_ruq',
    label: 'Pain Localized to Right Upper Quadrant',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { cholecystitis: 6, peptic_ulcer: 2, hepatitis: 2, pancreatitis: 1 },
  },
  abdominal_pain_epigastric: {
    id: 'abdominal_pain_epigastric',
    label: 'Epigastric Pain',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { peptic_ulcer: 5, gerd: 4, pancreatitis: 3, gastritis: 4, cholecystitis: 1 },
  },
  peritonism: {
    id: 'peritonism',
    label: 'Peritoneal Signs (Guarding/Rigidity)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { appendicitis: 5, cholecystitis: 3, bowel_obstruction: 3, pancreatitis: 3, typhoid: 3 },
    isRedFlag: true,
    redFlagSeverity: 'critical',
    redFlagMessage: 'Peritoneal signs — likely surgical abdomen, urgent assessment needed',
  },
  vomiting_blood: {
    id: 'vomiting_blood',
    label: 'Hematemesis (Vomiting Blood)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { peptic_ulcer: 6, gerd: 1, esophageal_varices: 5, gastritis: 3, mallory_weiss: 3 },
    isRedFlag: true,
    redFlagSeverity: 'critical',
    redFlagMessage: 'Hematemesis — urgent upper GI source needed',
  },
  melena: {
    id: 'melena',
    label: 'Melena (Black Tarry Stools)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { peptic_ulcer: 6, gastritis: 3, esophageal_varices: 3, malignancy: 1 },
    isRedFlag: true,
    redFlagSeverity: 'critical',
    redFlagMessage: 'Melena — upper GI bleeding source',
  },

  // ── HEADACHE ──
  headache_thunderclap: {
    id: 'headache_thunderclap',
    label: 'Thunderclap Headache (Sudden, Worst of Life)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { subarachnoid_hemorrhage: 7, intracranial_hemorrhage: 5, meningitis: 2 },
    isRedFlag: true,
    redFlagSeverity: 'critical',
    redFlagMessage: 'Thunderclap headache — possible subarachnoid hemorrhage',
  },
  headache_neck_stiffness: {
    id: 'headache_neck_stiffness',
    label: 'Headache with Neck Stiffness',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { meningitis: 6, subarachnoid_hemorrhage: 3 },
    isRedFlag: true,
    redFlagSeverity: 'high',
    redFlagMessage: 'Headache + neck stiffness — possible meningitis',
  },
  headache_photophobia: {
    id: 'headache_photophobia',
    label: 'Photophobia (Sensitivity to Light)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { meningitis: 4, migraine: 4, subarachnoid_hemorrhage: 2 },
  },

  // ── OCCUPATION EXPOSURES ──
  occupation_farmer: {
    id: 'occupation_farmer',
    label: 'Farmer',
    type: 'boolean',
    category: 'occupation',
    diseaseWeights: { brucellosis: 3, leptospirosis: 2, fungal_pneumonia: 2, tb_pulm: 1, heat_stroke: 1 },
  },
  occupation_miner: {
    id: 'occupation_miner',
    label: 'Miner',
    type: 'boolean',
    category: 'occupation',
    diseaseWeights: { tb_pulm: 4, silicosis: 5, copd_pulm: 3, lung_cancer: 2 },
  },
  occupation_healthcare: {
    id: 'occupation_healthcare',
    label: 'Healthcare Worker',
    type: 'boolean',
    category: 'occupation',
    diseaseWeights: { tb_pulm: 3, covid: 3, hepatitis_b: 2, hiv: 1 },
  },

  // ── FUNCTIONAL IMPACT ──
  unable_to_work: {
    id: 'unable_to_work',
    label: 'Unable to Work Due to Illness',
    type: 'boolean',
    category: 'social',
    diseaseWeights: {},
  },
  bedridden: {
    id: 'bedridden',
    label: 'Bedridden / Confined to Bed',
    type: 'boolean',
    category: 'social',
    diseaseWeights: {},
    isRedFlag: true,
    redFlagSeverity: 'high',
    redFlagMessage: 'Patient bedridden — indicates severe functional impairment',
  },

  // ── APPENDICITIS FEATURES ───────────────────────────────────────────
  abdominal_pain: {
    id: 'abdominal_pain',
    label: 'Abdominal Pain (non-specific)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { appendicitis: 5, gastroenteritis: 4, intestinal_obstruction: 5, perforated_ulcer: 4, mesenteric_adenitis: 3, ureteric_colic: 3 },
  },
  periumbilical_pain: {
    id: 'periumbilical_pain',
    label: 'Periumbilical Pain (early)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { appendicitis: 5, gastroenteritis: 4, mesenteric_adenitis: 3, small_bowel_obstruction: 3 },
  },
  pain_migration_to_RIF: {
    id: 'pain_migration_to_RIF',
    label: 'Pain Migration to Right Iliac Fossa',
    description: 'Pain started around umbilicus then moved to RLQ',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { appendicitis: 9, mesenteric_adenitis: 1 },
    condition: 'Classic migration is a near-pathognomonic feature',
  },
  right_iliac_fossa_pain: {
    id: 'right_iliac_fossa_pain',
    label: 'Right Iliac Fossa Pain (localized)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { appendicitis: 8, mesenteric_adenitis: 4, ovarian_torsion: 5, ureteric_colic: 4, ectopic_pregnancy: 5, crohn_terminal_ileitis: 4, cecal_diverticulitis: 5 },
  },
  nausea: {
    id: 'nausea',
    label: 'Nausea',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { appendicitis: 3, gastroenteritis: 4, migraine: 3, cyclic_vomiting: 3, intestinal_obstruction: 3 },
  },
  vomiting: {
    id: 'vomiting',
    label: 'Vomiting',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { appendicitis: 3, gastroenteritis: 5, intestinal_obstruction: 5, pancreatitis: 3, migraine: 2 },
  },
  pain_before_vomiting: {
    id: 'pain_before_vomiting',
    label: 'Pain Precedes Vomiting',
    description: 'Abdominal pain started before vomiting began',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { appendicitis: 4, intestinal_obstruction: 3, pancreatitis: 3, perforated_ulcer: 4 },
    condition: 'Key distinction from gastroenteritis where vomiting precedes pain',
  },
  pain_aggravated_by_movement: {
    id: 'pain_aggravated_by_movement',
    label: 'Pain Aggravated by Movement',
    description: 'Coughing, walking, or bumps worsen the pain',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { appendicitis: 5, peritonitis_any: 5, perforated_ulcer: 4 },
  },
  pain_on_coughing: {
    id: 'pain_on_coughing',
    label: 'Pain on Coughing (Cough Sign)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { appendicitis: 4, peritonitis_any: 4 },
  },
  pain_on_walking: {
    id: 'pain_on_walking',
    label: 'Pain on Walking / Limping',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { appendicitis: 4, peritonitis_any: 3 },
  },
  low_grade_fever: {
    id: 'low_grade_fever',
    label: 'Low-Grade Fever (37.2-37.7°C)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { appendicitis: 2, typhoid: 3, tb_pulm: 2, malignancy_fever: 1 },
  },
  malaise: {
    id: 'malaise',
    label: 'General Malaise',
    type: 'boolean',
    category: 'constitutional',
    diseaseWeights: { appendicitis: 1, typhoid: 2, sepsis: 2, tb_pulm: 2, viral_illness: 2 },
  },

  // ── APPENDICITIS — EXAMINATION SIGNS ───────────────────────────────
  RIF_tenderness: {
    id: 'RIF_tenderness',
    label: 'Right Iliac Fossa Tenderness',
    description: 'Tenderness on palpation over McBurney\'s point',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { appendicitis: 10, mesenteric_adenitis: 3, ovarian_torsion: 4, ectopic_pregnancy: 4, ureteric_colic: 2 },
  },
  mcburney_tenderness: {
    id: 'mcburney_tenderness',
    label: 'McBurney\'s Point Tenderness',
    description: 'Point tenderness at 1/3 distance from ASIS to umbilicus',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { appendicitis: 10, mesenteric_adenitis: 2 },
  },
  rebound_tenderness: {
    id: 'rebound_tenderness',
    label: 'Rebound Tenderness (Blumberg\'s Sign)',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { appendicitis: 8, peritonitis_any: 8, perforated_ulcer: 7, typhlitis: 5, cholecystitis: 6 },
  },
  localized_guarding: {
    id: 'localized_guarding',
    label: 'Localized Muscle Guarding (RLQ)',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { appendicitis: 8, mesenteric_adenitis: 2, ovarian_torsion: 4 },
  },
  rovsing_sign: {
    id: 'rovsing_sign',
    label: 'Rovsing\'s Sign',
    description: 'RLQ pain with deep palpation of left iliac fossa',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { appendicitis: 8, mesenteric_adenitis: 1 },
  },
  psoas_sign: {
    id: 'psoas_sign',
    label: 'Psoas Sign',
    description: 'RLQ pain with passive extension of right hip or active flexion against resistance',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { appendicitis: 7, psoas_abscess: 6, retrocecal_appendicitis: 8 },
  },
  obturator_sign: {
    id: 'obturator_sign',
    label: 'Obturator Sign',
    description: 'RLQ pain with internal rotation of a flexed right hip',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { appendicitis: 7, pelvic_appendicitis: 8, pelvic_abscess: 5, ovarian_torsion: 3 },
  },
  percussion_tenderness: {
    id: 'percussion_tenderness',
    label: 'Percussion Tenderness (RLQ)',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { appendicitis: 6, peritonitis_any: 6 },
  },
  rigidity: {
    id: 'rigidity',
    label: 'Right-Sided Abdominal Rigidity',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { appendicitis: 9, peritonitis_any: 8, perforated_ulcer: 8 },
  },
  generalized_guarding: {
    id: 'generalized_guarding',
    label: 'Generalized Abdominal Guarding',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { appendicitis: 10, peritonitis_any: 10, perforated_ulcer: 9, typhlitis: 7 },
    isRedFlag: true,
    redFlagSeverity: 'critical',
    redFlagMessage: 'Generalized guarding indicates perforation with peritonitis — emergency surgical exploration needed',
  },
  generalized_rigidity: {
    id: 'generalized_rigidity',
    label: 'Generalized Abdominal Rigidity (Wooden Board)',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { appendicitis: 10, peritonitis_any: 10, perforated_ulcer: 10, pancreatitis: 6 },
    isRedFlag: true,
    redFlagSeverity: 'critical',
    redFlagMessage: 'Generalized rigidity is a surgical emergency — indicates perforated viscus with generalized peritonitis',
  },
  cough_sign: {
    id: 'cough_sign',
    label: 'Cough Sign (Dunphy\'s Sign)',
    description: 'Localized RLQ pain on coughing',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { appendicitis: 6, peritonitis_any: 5 },
  },

  // ── APPENDICITIS — NEGATIVE PREDICTORS ─────────────────────────────
  no_abdominal_pain: {
    id: 'no_abdominal_pain',
    label: 'No Abdominal Pain at Any Point',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 15 }],
    condition: 'Abdominal pain is present in essentially 100% of appendicitis cases',
  },
  no_RIF_tenderness: {
    id: 'no_RIF_tenderness',
    label: 'No Right Iliac Fossa Tenderness on Examination',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 12 }],
    condition: 'RLQ tenderness is present in 96% of appendicitis patients',
  },
  no_abdominal_tenderness: {
    id: 'no_abdominal_tenderness',
    label: 'No Abdominal Tenderness at All',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 15 }, { diseaseId: 'peritonitis_any', reduction: 15 }],
    condition: 'Essentially rules out acute surgical abdomen',
  },
  pain_present_for_months: {
    id: 'pain_present_for_months',
    label: 'Chronic Pain Over Months (not acute)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 10 }, { diseaseId: 'perforated_ulcer', reduction: 8 }],
    condition: 'Appendicitis is an acute process — chronic pain suggests alternative pathology (IBS, gynaecological, IBD)',
  },
  multiple_identical_recurrences: {
    id: 'multiple_identical_recurrences',
    label: 'Multiple Identical Recurrent Episodes',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 7 }],
    condition: 'True appendicitis rarely presents as multiple identical episodes without progression',
  },
  clear_gastroenteritis_pattern: {
    id: 'clear_gastroenteritis_pattern',
    label: 'Clear Gastroenteritis Pattern (vomiting before pain, diarrhea dominant)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 8 }],
    condition: 'Gastroenteritis is the most common mimic — vomiting before pain and profuse diarrhea suggest GE over appendicitis',
  },
  clear_urinary_source: {
    id: 'clear_urinary_source',
    label: 'Clear Urinary Tract Source (dysuria, hematuria, CVA tenderness)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 8 }, { diseaseId: 'ureteric_colic', reduction: 0 }],
  },
  positive_pregnancy_with_gyn_pattern: {
    id: 'positive_pregnancy_with_gyn_pattern',
    label: 'Positive Pregnancy Test with Gynaecological Pattern',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 10 }],
    isRedFlag: true,
    redFlagSeverity: 'critical',
    redFlagMessage: 'Positive pregnancy test with RLQ pain — must exclude ectopic pregnancy as a surgical emergency',
  },

  // ── BOWEL OBSTRUCTION FEATURES ──────────────────────────────────────
  colicky_abdominal_pain: {
    id: 'colicky_abdominal_pain',
    label: 'Colicky Abdominal Pain (Wave-like)',
    description: 'Pain that comes and goes in waves, typical of visceral obstruction',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { intestinal_obstruction: 7, small_bowel_obstruction: 7, large_bowel_obstruction: 6, ureteric_colic: 8, biliary_colic: 6 },
  },
  abdominal_distension: {
    id: 'abdominal_distension',
    label: 'Abdominal Distension (Swelling)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { intestinal_obstruction: 6, large_bowel_obstruction: 7, small_bowel_obstruction: 5, ascites: 4, pseudo_obstruction: 5 },
  },
  constipation_obstipation: {
    id: 'constipation_obstipation',
    label: 'Constipation / Obstipation (Unable to Pass Stool)',
    description: 'Absolute constipation — no stool passed, especially in complete obstruction',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { intestinal_obstruction: 8, large_bowel_obstruction: 8, small_bowel_obstruction: 6, severe_constipation: 5, pseudo_obstruction: 5 },
  },
  flatus_cessation: {
    id: 'flatus_cessation',
    label: 'Inability to Pass Gas (Flatus Cessation)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { intestinal_obstruction: 7, large_bowel_obstruction: 7, small_bowel_obstruction: 6, pseudo_obstruction: 4 },
  },
  colicky_to_constant_pain_transition: {
    id: 'colicky_to_constant_pain_transition',
    label: 'Pain Changing from Colicky to Constant',
    description: 'Progression from wave-like to unrelenting constant pain — ominous sign',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { intestinal_obstruction: 9, strangulated_obstruction: 10, mesenteric_ischemia: 8 },
    isRedFlag: true,
    redFlagSeverity: 'critical',
    redFlagMessage: 'Transition from colicky to constant pain suggests bowel ischemia or strangulation — emergency surgical exploration needed',
  },
  visible_or_palpable_hernia: {
    id: 'visible_or_palpable_hernia',
    label: 'Visible or Palpable Hernia at Groin/Umbilicus/Scar',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { obstructed_hernia: 8, inguinal_hernia: 5, intestinal_obstruction: 6, femoral_hernia: 5 },
  },
  high_pitched_bowel_sounds: {
    id: 'high_pitched_bowel_sounds',
    label: 'High-Pitched, Tinkling Bowel Sounds (Early Obstruction)',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { intestinal_obstruction: 7, small_bowel_obstruction: 8 },
  },
  absent_bowel_sounds: {
    id: 'absent_bowel_sounds',
    label: 'Absent Bowel Sounds (Late / Strangulation)',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { intestinal_obstruction: 6, strangulated_obstruction: 7, peritonitis_any: 6, paralytic_ileus: 5 },
  },
  visible_peristalsis: {
    id: 'visible_peristalsis',
    label: 'Visible Peristalsis',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { intestinal_obstruction: 5, gastric_outlet_obstruction: 6, pyloric_stenosis: 5 },
  },
  tympanic_percussion: {
    id: 'tympanic_percussion',
    label: 'Tympanic (Hyperresonant) Percussion',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { intestinal_obstruction: 4, large_bowel_obstruction: 5, pneumoperitoneum: 3 },
  },
  fecal_mass_on_dre: {
    id: 'fecal_mass_on_dre',
    label: 'Fecal Mass on Digital Rectal Exam',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { fecal_impaction: 8, severe_constipation: 6, intestinal_obstruction: 4 },
  },

  // ── BOWEL OBSTRUCTION — NEGATIVE PREDICTORS ─────────────────────────
  no_abdominal_distension: {
    id: 'no_abdominal_distension',
    label: 'No Abdominal Distension',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'intestinal_obstruction', reduction: 8 }, { diseaseId: 'large_bowel_obstruction', reduction: 10 }],
    condition: 'Distension is present in >90% of large bowel obstruction and most small bowel obstruction',
  },
  diarrhea_as_primary_symptom: {
    id: 'diarrhea_as_primary_symptom',
    label: 'Diarrhea as Primary Symptom',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'intestinal_obstruction', reduction: 10 }],
    condition: 'Complete obstruction causes absolute constipation — diarrhea essentially rules out complete mechanical obstruction',
  },
  no_previous_abdominal_surgery: {
    id: 'no_previous_abdominal_surgery',
    label: 'No Prior Abdominal Surgery',
    type: 'boolean',
    category: 'risk_factor',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'intestinal_obstruction', reduction: 5 }],
    condition: 'Adhesions from prior surgery are the most common cause of SBO in adults',
  },
  pain_relieved_by_passing_stool_or_gas: {
    id: 'pain_relieved_by_passing_stool_or_gas',
    label: 'Pain Relieved by Passing Stool or Gas',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'intestinal_obstruction', reduction: 8 }],
    condition: 'Pain relieved by defecation or flatus suggests IBS or constipation, not mechanical obstruction',
  },

  // ── CHOLECYSTITIS FEATURES ──────────────────────────────────────────
  right_upper_quadrant_pain: {
    id: 'right_upper_quadrant_pain',
    label: 'Right Upper Quadrant Pain',
    description: 'Pain localized to the right upper quadrant, often after fatty meals',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { cholecystitis: 8, biliary_colic: 6, hepatitis: 4, liver_abscess: 5, pneumonia: 3, Fitz_Hugh_Curtis: 4, hepatic_flexure_tumor: 3 },
  },
  fever: {
    id: 'fever',
    label: 'Fever',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { cholecystitis: 5, appendicitis: 2, pancreatitis: 3, pneumonia: 6, malaria: 7, typhoid: 7, sepsis: 5, urinary_tract_infection: 5 },
  },
  fatty_food_intolerance: {
    id: 'fatty_food_intolerance',
    label: 'Fatty Food Intolerance (Pain after Fried/Fatty Meals)',
    description: 'Abdominal pain or bloating triggered by fatty or fried foods',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { cholecystitis: 5, biliary_colic: 6, gallstone_disease: 5, dyspepsia: 3 },
  },
  previous_biliary_colic: {
    id: 'previous_biliary_colic',
    label: 'Previous Episodes of Biliary Colic',
    description: 'Self-limiting attacks of RUQ pain in the past',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { cholecystitis: 5, biliary_colic: 6, gallstone_disease: 5 },
  },
  jaundice_dark_urine_pale_stool: {
    id: 'jaundice_dark_urine_pale_stool',
    label: 'Jaundice + Dark Urine + Pale Stool (Obstructive Jaundice Pattern)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { choledocholithiasis: 8, cholecystitis: 6, pancreatic_cancer: 7, cholangiocarcinoma: 7, hepatitis: 5, mirizzi_syndrome: 6 },
  },
  murphy_sign: {
    id: 'murphy_sign',
    label: 'Murphy\'s Sign (Arrest of Inspiration on RUQ Palpation)',
    description: 'Patient catches their breath or stops inhaling when RUQ is palpated',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { cholecystitis: 10, biliary_colic: 2, hepatitis: 3 },
    condition: 'Nearly pathognomonic for acute cholecystitis when present',
  },
  ruq_tenderness: {
    id: 'ruq_tenderness',
    label: 'Right Upper Quadrant Tenderness',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { cholecystitis: 5, hepatitis: 4, liver_abscess: 5, Fitz_Hugh_Curtis: 4, biliary_colic: 3 },
  },
  guarding_ruq: {
    id: 'guarding_ruq',
    label: 'Guarding in Right Upper Quadrant',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { cholecystitis: 4, hepatitis: 3, liver_abscess: 4, perforated_ulcer: 5 },
  },
  palpable_gallbladder_mass: {
    id: 'palpable_gallbladder_mass',
    label: 'Palpable Gallbladder Mass (Courvoisier\'s Sign)',
    description: 'Palpable, non-tender gallbladder in jaundiced patient',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { cholecystitis: 4, pancreatic_cancer: 7, cholangiocarcinoma: 6, gallbladder_hydrops: 5 },
  },
  boas_sign: {
    id: 'boas_sign',
    label: 'Boas\' Sign (Right Infrascapular Hyperesthesia)',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { cholecystitis: 3 },
  },
  jaundice: {
    id: 'jaundice',
    label: 'Jaundice (Icterus)',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { hepatitis: 7, choledocholithiasis: 6, cholecystitis: 4, pancreatic_cancer: 7, cirrhosis: 5, hemolytic_anemia: 4, malaria: 4, gilbert_syndrome: 5, dubin_johnson_syndrome: 4 },
  },

  // ── CHOLECYSTITIS — NEGATIVE PREDICTORS ─────────────────────────────
  no_ruq_tenderness: {
    id: 'no_ruq_tenderness',
    label: 'No Right Upper Quadrant Tenderness',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'cholecystitis', reduction: 10 }],
    condition: 'RUQ tenderness is present in >95% of acute cholecystitis',
  },
  negative_murphy_sign: {
    id: 'negative_murphy_sign',
    label: 'Murphy\'s Sign Negative',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'cholecystitis', reduction: 12 }],
    condition: 'A positive Murphy\'s sign is present in >90% of acute cholecystitis; negative sign makes diagnosis unlikely',
  },
  no_gallstones_on_imaging: {
    id: 'no_gallstones_on_imaging',
    label: 'No Gallstones on Ultrasound',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'cholecystitis', reduction: 8 }],
    condition: '>90% of acute cholecystitis is calculous (associated with gallstones)',
  },
  pain_not_related_to_food: {
    id: 'pain_not_related_to_food',
    label: 'Pain Not Related to Meals',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'cholecystitis', reduction: 5 }, { diseaseId: 'biliary_colic', reduction: 7 }],
    condition: 'Biliary pain is typically post-prandial, especially after fatty meals',
  },

  // ── PANCREATITIS FEATURES ───────────────────────────────────────────
  epigastric_pain: {
    id: 'epigastric_pain',
    label: 'Epigastric Pain (Upper Middle Abdomen)',
    description: 'Pain localized to the epigastrium, often radiating to the back',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { pancreatitis: 8, perforated_ulcer: 8, gastritis: 5, peptic_ulcer: 6, mi_inferior: 5, cholecystitis: 4, gerd: 4, gastric_cancer: 4 },
  },
  alcohol_abuse: {
    id: 'alcohol_abuse',
    label: 'Alcohol Abuse (Excessive/Regular Consumption)',
    type: 'boolean',
    category: 'risk_factor',
    diseaseWeights: { pancreatitis: 6, alcoholic_hepatitis: 7, cirrhosis: 6, gastritis: 4, peptic_ulcer: 3, gerd: 3, mi_inferior: 2 },
  },
  gallstones: {
    id: 'gallstones',
    label: 'Known Gallstones (on prior imaging)',
    type: 'boolean',
    category: 'risk_factor',
    diseaseWeights: { cholecystitis: 6, pancreatitis: 6, biliary_colic: 7, choledocholithiasis: 6, gallstone_ileus: 5 },
  },
  pain_relieved_by_leaning_forward: {
    id: 'pain_relieved_by_leaning_forward',
    label: 'Pain Relieved by Leaning Forward / Sitting Up',
    description: 'Classic pancreatic pain behavior — patient prefers to sit up and lean forward',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { pancreatitis: 8, pancreatic_cancer: 5, retroperitoneal_abscess: 4 },
    condition: 'Highly suggestive of pancreatic origin — takes tension off the pancreas',
  },
  hypertriglyceridemia_history: {
    id: 'hypertriglyceridemia_history',
    label: 'History of High Triglycerides (>500 mg/dL)',
    type: 'boolean',
    category: 'risk_factor',
    diseaseWeights: { pancreatitis: 4, metabolic_syndrome: 3 },
  },
  epigastric_tenderness: {
    id: 'epigastric_tenderness',
    label: 'Epigastric Tenderness to Palpation',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { pancreatitis: 8, perforated_ulcer: 7, gastritis: 4, peptic_ulcer: 5, cholecystitis: 3 },
  },
  guarding: {
    id: 'guarding',
    label: 'Abdominal Guarding (Voluntary or Involuntary)',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { peritonitis_any: 6, pancreatitis: 4, cholecystitis: 4, appendicitis: 5, perforated_ulcer: 5 },
  },
  absent_bowel_sounds_ileus: {
    id: 'absent_bowel_sounds_ileus',
    label: 'Absent / Reduced Bowel Sounds (Ileus)',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { pancreatitis: 4, peritonitis_any: 6, intestinal_obstruction: 6, paralytic_ileus: 5 },
  },
  grey_turner_sign_flank_ecchymosis: {
    id: 'grey_turner_sign_flank_ecchymosis',
    label: 'Grey-Turner\'s Sign (Flank Ecchymosis)',
    description: 'Bruising in the flanks — indicates retroperitoneal hemorrhage',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { pancreatitis: 4, retroperitoneal_hemorrhage: 6, ruptured_aaa: 5 },
    isRedFlag: true,
    redFlagSeverity: 'critical',
    redFlagMessage: 'Grey-Turner\'s sign indicates severe necrotizing pancreatitis or ruptured AAA with retroperitoneal bleeding',
  },
  cullen_sign_periumbilical_ecchymosis: {
    id: 'cullen_sign_periumbilical_ecchymosis',
    label: 'Cullen\'s Sign (Periumbilical Ecchymosis)',
    description: 'Bruising around the umbilicus — retroperitoneal hemorrhage tracking along falciform ligament',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { pancreatitis: 4, ruptured_ectopic: 6, retroperitoneal_hemorrhage: 5, ruptured_aaa: 4 },
    isRedFlag: true,
    redFlagSeverity: 'critical',
    redFlagMessage: 'Cullen\'s sign suggests severe retroperitoneal bleeding — likely necrotizing pancreatitis or ruptured AAA',
  },
  pleural_effusion_left: {
    id: 'pleural_effusion_left',
    label: 'Left-Sided Pleural Effusion',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { pancreatitis: 4, malignancy_pleural: 4, tb_pleural: 5, parapneumonic_effusion: 4 },
  },
  hypotension_septic_shock: {
    id: 'hypotension_septic_shock',
    label: 'Hypotension / Septic Shock',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { sepsis: 6, pancreatitis: 5, peritonitis_any: 6, perforated_ulcer: 5, cholangitis: 6, ruptured_aaa: 8 },
    isRedFlag: true,
    redFlagSeverity: 'critical',
    redFlagMessage: 'Hypotension in acute abdomen requires immediate resuscitation and surgical review',
  },

  // ── PANCREATITIS — NEGATIVE PREDICTORS ──────────────────────────────
  no_epigastric_tenderness: {
    id: 'no_epigastric_tenderness',
    label: 'No Epigastric Tenderness on Examination',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'pancreatitis', reduction: 10 }],
    condition: 'Epigastric tenderness is present in essentially all cases of acute pancreatitis',
  },
  normal_amylase_lipase: {
    id: 'normal_amylase_lipase',
    label: 'Normal Serum Amylase and Lipase',
    type: 'boolean',
    category: 'lab_finding',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'pancreatitis', reduction: 15 }],
    condition: 'Lipase >3x ULN is the diagnostic gold standard for pancreatitis; normal levels essentially rule it out',
  },
  pain_not_radiating_to_back: {
    id: 'pain_not_radiating_to_back',
    label: 'Pain Does Not Radiate to the Back',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'pancreatitis', reduction: 7 }],
    condition: 'Boring pain radiating to the back is a classic feature of pancreatitis',
  },
  no_relief_with_leaning_forward: {
    id: 'no_relief_with_leaning_forward',
    label: 'Pain Not Relieved by Leaning Forward',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'pancreatitis', reduction: 6 }],
    condition: 'Leaning forward typically provides partial relief in acute pancreatitis',
  },

  // ── PERFORATED ULCER FEATURES ───────────────────────────────────────
  previous_dyspepsia_or_ulcer: {
    id: 'previous_dyspepsia_or_ulcer',
    label: 'Previous History of Dyspepsia / Peptic Ulcer',
    type: 'boolean',
    category: 'risk_factor',
    diseaseWeights: { perforated_ulcer: 6, peptic_ulcer: 7, gastritis: 4, gerd: 3 },
  },
  nsaid_use: {
    id: 'nsaid_use',
    label: 'NSAID Use (Ibuprofen, Diclofenac, Aspirin)',
    type: 'boolean',
    category: 'risk_factor',
    diseaseWeights: { perforated_ulcer: 6, peptic_ulcer: 6, gastritis: 5, acute_kidney_injury: 3, upper_gi_bleed: 5 },
  },
  hematemesis_melena: {
    id: 'hematemesis_melena',
    label: 'Hematemesis (Vomiting Blood) or Melena (Black Stool)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { upper_gi_bleed: 9, perforated_ulcer: 3, peptic_ulcer: 5, esophageal_varices: 7, mallory_weiss: 6, gastric_cancer: 4 },
    isRedFlag: true,
    redFlagSeverity: 'high',
    redFlagMessage: 'Upper GI bleeding requires urgent endoscopy and resuscitation',
  },
  board_like_rigidity: {
    id: 'board_like_rigidity',
    label: 'Board-Like Abdominal Rigidity',
    description: 'Entire abdomen is rigid and hard to palpation — surgical peritonitis',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { perforated_ulcer: 10, peritonitis_any: 9, typhoid_perforation: 8, appendicitis_perforation: 8 },
    isRedFlag: true,
    redFlagSeverity: 'critical',
    redFlagMessage: 'Board-like rigidity indicates generalized peritonitis from a perforated viscus — emergency laparotomy required',
  },
  tachycardia: {
    id: 'tachycardia',
    label: 'Tachycardia (Heart Rate >100 bpm)',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { sepsis: 5, perforated_ulcer: 4, pancreatitis: 4, hypovolemia: 4, hemorrhagic_shock: 6, svt: 4, afib: 4 },
  },
  liver_dullness_obliteration: {
    id: 'liver_dullness_obliteration',
    label: 'Liver Dullness Obliteration on Percussion',
    description: 'Gas in peritoneal cavity displaces the liver, making the normally dull percussion note resonant',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { perforated_ulcer: 6, pneumoperitoneum: 8 },
    condition: 'Sign of free intraperitoneal air — nearly diagnostic of perforated viscus',
  },
  shoulder_tip_pain_referred: {
    id: 'shoulder_tip_pain_referred',
    label: 'Referred Shoulder Tip Pain (Phrenic Nerve Irritation)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { perforated_ulcer: 3, subphrenic_abscess: 5, ruptured_ectopic: 4, splenic_rupture: 4, liver_abscess: 3 },
  },

  // ── PERFORATED ULCER — NEGATIVE PREDICTORS ──────────────────────────
  no_free_air_on_imaging: {
    id: 'no_free_air_on_imaging',
    label: 'No Free Air on Erect CXR or CT',
    type: 'boolean',
    category: 'lab_finding',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'perforated_ulcer', reduction: 10 }],
    condition: 'Free air under diaphragm is present in 70-80% of perforated PUD',
  },
  no_board_like_rigidity: {
    id: 'no_board_like_rigidity',
    label: 'No Board-Like Rigidity',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'perforated_ulcer', reduction: 10 }],
    condition: 'Board-like rigidity is the hallmark sign of generalized peritonitis from perforation',
  },
  no_ulcer_history_no_nsaids: {
    id: 'no_ulcer_history_no_nsaids',
    label: 'No Ulcer History and No NSAID Use',
    type: 'boolean',
    category: 'risk_factor',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'perforated_ulcer', reduction: 6 }],
    condition: 'Most perforated ulcers occur in patients with known ulcer disease or NSAID use',
  },
  pain_relieved_by_antacids: {
    id: 'pain_relieved_by_antacids',
    label: 'Pain Relieved by Antacids or Food',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: {},
    negativePredictorFor: [{ diseaseId: 'perforated_ulcer', reduction: 7 }],
    condition: 'Pain from perforation is continuous and not relieved by food or antacids',
  },

  // ── APPENDICITIS MIMICS — KEY FEATURES ──────────────────────────────

  // MEckel's Diverticulitis
  meckel_diverticulitis_suspected: {
    id: 'meckel_diverticulitis_suspected',
    label: 'Suspected Meckel\'s Diverticulitis',
    description: 'Clinically identical to appendicitis — often diagnosed intraoperatively. Pain may be more central or in RLQ.',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { meckel_diverticulitis: 8 },
    condition: 'Consider in children with RLQ pain and rectal bleeding or prior self-limiting episodes',
  },
  pain_more_central_than_rlq: {
    id: 'pain_more_central_than_rlq',
    label: 'Pain More Central (not classic RIF)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { meckel_diverticulitis: 3, mesenteric_adenitis: 4, gastroenteritis: 3 },
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 4 }],
  },
  rectal_bleeding: {
    id: 'rectal_bleeding',
    label: 'Rectal Bleeding / Blood in Stool',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { meckel_diverticulitis: 6, intussusception: 5, colorectal_cancer: 6, hemorrhoids: 4, ibd: 5, diverticulitis: 4 },
    isRedFlag: true,
    redFlagSeverity: 'high',
    redFlagMessage: 'Rectal bleeding in acute abdomen requires investigation — consider Meckel\'s, intussusception, or colitis',
  },

  // Ruptured Ovarian Cyst
  sudden_pelvic_pain_mid_cycle: {
    id: 'sudden_pelvic_pain_mid_cycle',
    label: 'Sudden Pelvic Pain — Mid-Cycle (Mittelschmerz pattern)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { ruptured_ovarian_cyst: 7, ovarian_torsion: 3, ectopic_pregnancy: 2 },
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 5 }],
    condition: 'Mid-cycle pain suggests ruptured ovarian cyst rather than appendicitis',
  },

  // Testicular Torsion / Epididymitis
  testicular_pain_swelling: {
    id: 'testicular_pain_swelling',
    label: 'Testicular Pain / Swelling',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { testicular_torsion: 8, epididymitis: 7, orchitis: 6, hernia_strangulated: 4, referred_pain_appendicitis: 2 },
    isRedFlag: true,
    redFlagSeverity: 'high',
    redFlagMessage: 'Testicular pain with acute abdomen may indicate referred pain from appendicitis (inflamed appendix lying in pelvis)',
  },
  cremasteric_reflex_absent: {
    id: 'cremasteric_reflex_absent',
    label: 'Absent Cremasteric Reflex',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { testicular_torsion: 8, epididymitis: 2 },
    negativePredictorFor: [{ diseaseId: 'testicular_torsion', reduction: 6 }],
  },
  testicular_high_lying_transverse: {
    id: 'testicular_high_lying_transverse',
    label: 'High-Lying / Transverse Testicle',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { testicular_torsion: 9 },
  },
  prehn_sign_positive: {
    id: 'prehn_sign_positive',
    label: 'Prehn\'s Sign Positive (Elevation Relieves Pain)',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { epididymitis: 6 },
    negativePredictorFor: [{ diseaseId: 'testicular_torsion', reduction: 5 }],
  },

  // Ovarian Torsion
  sudden_severe_pelvic_adnexal_pain: {
    id: 'sudden_severe_pelvic_adnexal_pain',
    label: 'Sudden Severe Pelvic / Adnexal Pain',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { ovarian_torsion: 9, ruptured_ovarian_cyst: 6, ectopic_pregnancy: 5, pid: 3 },
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 4 }],
    condition: 'Sudden severe pelvic pain with nausea suggests ovarian torsion',
  },
  adnexal_mass_tenderness: {
    id: 'adnexal_mass_tenderness',
    label: 'Palpable Adnexal Mass / Tenderness on Bimanual Exam',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { ovarian_torsion: 7, ruptured_ovarian_cyst: 5, ectopic_pregnancy: 5, pid: 4, ovarian_cyst: 5 },
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 3 }],
  },
  cervical_motion_tenderness: {
    id: 'cervical_motion_tenderness',
    label: 'Cervical Motion Tenderness (Chandelier Sign)',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { pid: 8, ectopic_pregnancy: 5, ruptured_ovarian_cyst: 3, ovarian_torsion: 3 },
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 5 }],
    condition: 'Cervical motion tenderness is classic for PID and points away from appendicitis',
  },
  vaginal_discharge_abnormal: {
    id: 'vaginal_discharge_abnormal',
    label: 'Abnormal Vaginal Discharge',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { pid: 7, vaginitis: 5, std: 4 },
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 4 }],
  },

  // Terminal Ileitis (Crohn's)
  chronic_recurrent_rlq_pain: {
    id: 'chronic_recurrent_rlq_pain',
    label: 'Chronic / Recurrent RLQ Pain Over Weeks to Months',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { crohn_terminal_ileitis: 7, ibs: 3, appendicitis: 1 },
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 7 }],
    condition: 'Chronic recurrent RLQ pain with weight loss suggests Crohn\'s terminal ileitis, not acute appendicitis',
  },
  weight_loss_chronic_diarrhea: {
    id: 'weight_loss_chronic_diarrhea',
    label: 'Weight Loss with Chronic Diarrhea',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { crohn_terminal_ileitis: 6, ibd: 6, colorectal_cancer: 5, tb_intestinal: 5, malabsorption: 4, hiv: 3 },
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 6 }],
  },
  perianal_fistula_fissure: {
    id: 'perianal_fistula_fissure',
    label: 'Perianal Fistula / Fissure / Abscess',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { crohn_terminal_ileitis: 7, ibd: 6, tb_intestinal: 3 },
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 4 }],
  },

  // Right Lower Lobe Pneumonia
  cough_with_sputum: {
    id: 'cough_with_sputum',
    label: 'Cough with Sputum Production',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { pneumonia_rll: 8, pneumonia_any: 8, bronchitis: 6, tb_pulm: 5, covid: 5, aspiration_pneumonia: 5 },
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 6 }],
    condition: 'Cough with abdominal pain suggests referred pain from lower lobe pneumonia, especially in children',
  },
  pleuritic_chest_pain: {
    id: 'pleuritic_chest_pain',
    label: 'Pleuritic Chest Pain (Worse on Inspiration)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { pneumonia_rll: 7, pleurisy: 7, pulmonary_embolism: 6, pericarditis: 5, rib_fracture: 4 },
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 5 }],
  },
  chest_crackles_consolidation: {
    id: 'chest_crackles_consolidation',
    label: 'Crackles / Bronchial Breathing / Dullness on Chest Exam',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { pneumonia_rll: 9, pneumonia_any: 8, tb_pulm: 6, pleural_effusion: 5, lung_abscess: 5 },
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 7 }],
    isRedFlag: true,
    redFlagSeverity: 'high',
    redFlagMessage: 'Chest findings + abdominal pain = consider referred pain from pneumonia rather than surgical abdomen',
  },

  // Colonic Carcinoma (elderly)
  change_in_bowel_habits: {
    id: 'change_in_bowel_habits',
    label: 'Change in Bowel Habits (Constipation/Diarrhea Alternating)',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { colorectal_cancer: 7, ibs: 5, diverticulitis: 3, constipation: 3 },
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 4 }],
    condition: 'Change in bowel habits with RLQ pain in elderly suggests cecal/right colon tumor rather than appendicitis',
  },
  weight_loss_anemia: {
    id: 'weight_loss_anemia',
    label: 'Unexplained Weight Loss + Pallor/Anemia',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { colorectal_cancer: 7, gastric_cancer: 6, pancreatic_cancer: 5, tb_intestinal: 5, hiv: 3, malabsorption: 3 },
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 5 }, { diseaseId: 'cholecystitis', reduction: 3 }],
    isRedFlag: true,
    redFlagSeverity: 'high',
    redFlagMessage: 'Weight loss with anemia requires investigation for underlying malignancy',
  },
  palpable_rlq_mass: {
    id: 'palpable_rlq_mass',
    label: 'Palpable Right Iliac Fossa Mass',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { appendiceal_mass: 7, colorectal_cancer: 6, crohn_terminal_ileitis: 5, tb_ileocecal: 5, psoas_abscess: 4, ovarian_mass: 4 },
    condition: 'Mass in RLQ could be appendix mass/phlegmon, cecal tumor, Crohn\'s phlegmon, or TB ileocecal',
  },

  // General Urinary Mimics (UPEC)
  dysuria_frequency: {
    id: 'dysuria_frequency',
    label: 'Dysuria / Urinary Frequency / Urgency',
    type: 'boolean',
    category: 'symptom_detail',
    diseaseWeights: { urinary_tract_infection: 8, ureteric_colic: 4, appendicitis: 1 },
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 5 }],
  },
  cva_tenderness: {
    id: 'cva_tenderness',
    label: 'Costovertebral Angle Tenderness',
    type: 'boolean',
    category: 'exam_finding',
    diseaseWeights: { pyelonephritis: 9, ureteric_colic: 5, renal_abscess: 5, appendicitis: 1 },
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 6 }],
  },
  hematuria: {
    id: 'hematuria',
    label: 'Hematuria (Blood in Urine)',
    type: 'boolean',
    category: 'lab_finding',
    diseaseWeights: { ureteric_colic: 7, urinary_tract_infection: 4, glomerulonephritis: 5, bladder_tumor: 5, prostatitis: 3, appendicitis: 1 },
    negativePredictorFor: [{ diseaseId: 'appendicitis', reduction: 4 }],
  },
};

export function getFeature(id: string): HistoryFeature | undefined {
  return HISTORY_FEATURE_REGISTRY[id];
}

export function getFeaturesByCategory(category: string): HistoryFeature[] {
  return Object.values(HISTORY_FEATURE_REGISTRY).filter(f => f.category === category);
}

export function getRedFlags(): HistoryFeature[] {
  return Object.values(HISTORY_FEATURE_REGISTRY).filter(f => f.isRedFlag);
}

export function getFeaturesForDisease(diseaseId: string): { feature: HistoryFeature; weight: number }[] {
  const result: { feature: HistoryFeature; weight: number }[] = [];
  for (const f of Object.values(HISTORY_FEATURE_REGISTRY)) {
    const w = f.diseaseWeights[diseaseId];
    if (w) result.push({ feature: f, weight: w });
  }
  return result.sort((a, b) => b.weight - a.weight);
}

export default HISTORY_FEATURE_REGISTRY;
