// ── PDF GENERATOR ──
// Generates proper PDF documents (not webpage print) for clinical encounter documentation

export async function generatePDF(
  title: string,
  content: string,
  patientName: string,
  date: string,
  encounterId: string
): Promise<void> {
  // Build the HTML document optimized for PDF rendering
  const styles = `
    @page { margin: 20mm 15mm; size: A4; }
    body {
      font-family: 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;
      font-size: 11pt;
      line-height: 1.6;
      color: #1a1a2e;
      background: white;
      padding: 0;
      margin: 0;
    }
    .header {
      text-align: center;
      border-bottom: 2px solid #0d9488;
      padding-bottom: 10px;
      margin-bottom: 20px;
    }
    .header h1 { font-size: 18pt; color: #0d9488; margin: 0; }
    .header p { font-size: 9pt; color: #666; margin: 4px 0 0 0; }
    .meta {
      display: flex;
      justify-content: space-between;
      font-size: 9pt;
      color: #555;
      margin-bottom: 15px;
      padding: 8px 12px;
      background: #f8fafc;
      border-radius: 4px;
    }
    .section-title {
      font-size: 13pt;
      font-weight: bold;
      color: #0d9488;
      border-bottom: 1px solid #e2e8f0;
      padding-bottom: 4px;
      margin-top: 18px;
      margin-bottom: 8px;
    }
    .subsection-title {
      font-size: 11pt;
      font-weight: 600;
      color: #334155;
      margin-top: 12px;
      margin-bottom: 4px;
    }
    .content { white-space: pre-wrap; font-size: 10.5pt; }
    .content-line { margin: 2px 0; }
    .bullet { margin-left: 15px; }
    .footer {
      margin-top: 30px;
      padding-top: 10px;
      border-top: 1px solid #e2e8f0;
      font-size: 8pt;
      color: #999;
      text-align: center;
    }
    .highlight-box {
      background: #f0fdfa;
      border-left: 4px solid #0d9488;
      padding: 10px 14px;
      margin: 10px 0;
      border-radius: 4px;
    }
    hr { border: none; border-top: 1px solid #e2e8f0; margin: 8px 0; }
  `;

  const formattedContent = content
    .split('\n')
    .map(line => {
      if (line.startsWith('═')) return '<hr/>';
      if (line.startsWith('─')) return '';
      if (line.startsWith('  •')) return `<div class="content-line bullet">${line}</div>`;
      if (line.match(/^\d+\.\s/)) return `<div class="section-title">${line}</div>`;
      if (line.match(/^[A-Z\s]{4,}/)) return `<div class="subsection-title">${line}</div>`;
      if (line.trim() === '') return '<br/>';
      return `<div class="content-line">${line}</div>`;
    })
    .join('\n');

  const html = `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>${escapeHtml(title)}</title><style>${styles}</style></head>
<body>
  <div class="header">
    <h1>AMEXAN — Clinical Clerking Note</h1>
    <p>Comprehensive Patient Encounter Documentation</p>
  </div>
  <div class="meta">
    <span>Patient: <strong>${escapeHtml(patientName)}</strong></span>
    <span>Date: ${date}</span>
    <span>ID: ${encounterId}</span>
  </div>
  <div class="content">${formattedContent}</div>
  <div class="footer">
    <p>Generated by AMEXAN Clinical Engine | ${new Date().toLocaleString()}</p>
    <p>This document is for clinical purposes only.</p>
  </div>
</body>
</html>`;

  // Open in new window for native browser PDF (works best across devices)
  const pdfWindow = window.open('', '_blank');
  if (!pdfWindow) {
    // Fallback: download as blob HTML if popup blocked
    downloadAsFile(html, `${encounterId}_${sanitizeFilename(patientName)}.html`, 'text/html');
    return;
  }
  pdfWindow.document.write(html);
  pdfWindow.document.close();

  // Trigger browser print (Save as PDF option)
  setTimeout(() => {
    pdfWindow.focus();
    pdfWindow.print();
  }, 500);
}

// ── Alternative: Download using Blob (works when popup blocked) ──
export function downloadAsPDFBlob(
  title: string,
  content: string,
  patientName: string,
  encounterId: string
): void {
  const date = new Date().toLocaleDateString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric',
  });

  const styles = `
    body { font-family: Arial, sans-serif; font-size: 11pt; line-height: 1.6; color: #333; padding: 20mm; }
    h1 { font-size: 18pt; color: #0d9488; text-align: center; border-bottom: 2px solid #0d9488; padding-bottom: 10px; }
    .meta { font-size: 9pt; color: #666; margin: 10px 0; }
    hr { border: 1px solid #eee; }
  `;

  const html = `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>${escapeHtml(title)}</title>
<style>${styles}</style></head>
<body>
<h1>AMEXAN — Clinical Clerking Note</h1>
<div class="meta">Patient: ${escapeHtml(patientName)} | Date: ${date} | ID: ${encounterId}</div>
<hr>
<pre style="font-family: Arial, sans-serif; white-space: pre-wrap; font-size: 10.5pt;">${escapeHtml(content)}</pre>
<hr>
<p style="font-size: 8pt; color: #999; text-align: center;">Generated by AMEXAN | ${new Date().toLocaleString()}</p>
</body></html>`;

  downloadAsFile(html, `AMEXAN_${encounterId}_${sanitizeFilename(patientName)}.html`, 'text/html');
}

function downloadAsFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function escapeHtml(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function sanitizeFilename(name: string): string {
  return name.replace(/[^a-zA-Z0-9_-]/g, '_').substring(0, 50);
}
