// ═══════════════════════════════════════════════════════════════════════════════
// Abdominal Pain Symptom Node — SX000007
// Sources: Hutchison Clinical Methods 25e, WHO IMCI, WSES Guidelines
// Universal Core + Pediatric + Obstetric + Surgical adapters
// ═══════════════════════════════════════════════════════════════════════════════

import type { SymptomNode } from '../symptom-types';

export const ABDOMINAL_PAIN_NODE: SymptomNode = {
  identity: {
    id: 'SX000007',
    canonicalName: 'Abdominal Pain',
    synonyms: ['Stomach pain', 'Belly pain', 'Abdominal discomfort'],
    layTerms: ['Tummy ache', 'Stomach ache', 'Belly ache'],
    translations: {},
    snomed: '21522001',
    icd10: 'R10.9',
    umls: 'C0000737',
    bodySystem: 'Gastrointestinal',
    primarySpecialty: 'General Surgery',
    emergencyWeight: 4,
  },

  metadata: {
    version: '1.0.0',
    author: 'AMEXAN Clinical Constitution',
    evidenceLevel: 'consensus',
    lastUpdated: '2026-07-13',
    source: 'Hutchison Clinical Methods 25e, WHO IMCI guidelines, WSES acute abdomen guidelines',
  },

  activation: {
    chiefComplaint: true,
    hpiMention: true,
    ros: true,
    referralLetter: true,
    voiceTranscription: true,
    keywords: ['abdominal pain', 'stomach pain', 'belly pain', 'tummy pain', 'abdomen pain', 'stomach ache', 'belly ache'],
  },

  timeline: {
    allowed: ['acute', 'subacute', 'chronic', 'recurrent', 'unknown'],
    defaultCategory: 'acute',
  },

  objectives: [
    { id: 'obj_char', label: 'Characterization', description: 'Establish site, character, and radiation of pain', order: 1, required: true, questionIds: ['q_site', 'q_character', 'q_radiation'] },
    { id: 'obj_timeline', label: 'Timeline', description: 'Onset, duration, progression', order: 2, required: true, questionIds: ['q_onset', 'q_duration', 'q_progression'] },
    { id: 'obj_severity', label: 'Severity', description: 'Assess intensity and impact', order: 3, required: true, questionIds: ['q_severity', 'q_aggravating', 'q_relieving'] },
    { id: 'obj_associated', label: 'Associated Symptoms', description: 'Identify accompanying GI and systemic symptoms', order: 4, required: true, questionIds: ['q_nausea_vomiting', 'q_fever', 'q_appetite', 'q_bowel_habit'] },
    { id: 'obj_previous', label: 'Previous History', description: 'Relevant surgical and medical history', order: 5, required: false, questionIds: ['q_previous_surgeries', 'q_previous_episodes', 'q_menstrual', 'q_urinary'] },
    { id: 'obj_pediatric', label: 'Pediatric Assessment', description: 'Age-appropriate abdominal pain assessment', order: 6, required: false, questionIds: ['q_ped_feeding', 'q_ped_crying'] },
    { id: 'obj_red_flags', label: 'Red Flags', description: 'Identify warning signs requiring urgent surgical attention', order: 7, required: true, questionIds: ['q_rigidity', 'q_guarding', 'q_rebound', 'q_bleeding_gi'] },
  ],

  questions: [
    // ── Characterization ──
    {
      id: 'q_site',
      text: 'Where is the pain located?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Where does the tummy hurt?' },
      ],
      type: 'chips',
      chips: ['Right upper quadrant', 'Epigastrium', 'Left upper quadrant', 'Right lower quadrant', 'Periumbilical', 'Left lower quadrant', 'Suprapubic', 'Generalized / all over'],
      required: true,
      importance: 2,
      reasoningWeight: 30,
      factKey: 'abdominal_pain_site',
      documentationPhrase: 'Pain located in {value}',
    },
    {
      id: 'q_character',
      text: 'How would you describe the pain?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'What does the pain feel like?' },
      ],
      type: 'chips',
      chips: ['Colicky / comes and goes', 'Burning', 'Sharp / stabbing', 'Dull / aching', 'Cramping', 'Tearing', 'Constant / pressure'],
      required: true,
      importance: 2,
      reasoningWeight: 25,
      factKey: 'abdominal_pain_character',
      documentationPhrase: 'Pain described as {value}',
    },
    {
      id: 'q_radiation',
      text: 'Does the pain travel anywhere?',
      alternatives: [],
      type: 'chips',
      chips: ['No radiation', 'To back', 'To right shoulder', 'To left shoulder', 'To groin', 'Down legs'],
      required: false,
      importance: 1,
      reasoningWeight: 15,
      factKey: 'abdominal_pain_radiation',
      documentationPhrase: 'Pain radiates {value}',
    },

    // ── Timeline ──
    {
      id: 'q_onset',
      text: 'When did the pain start?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'When did the tummy ache start?' },
      ],
      type: 'chips',
      chips: ['Hours ago', '1-2 days ago', '3-5 days ago', '1-2 weeks ago', 'More than 2 weeks ago'],
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'abdominal_pain_onset',
      documentationPhrase: 'Pain started {value} ago',
    },
    {
      id: 'q_duration',
      text: 'How long has the pain lasted?',
      alternatives: [],
      type: 'chips',
      chips: ['Less than 24 hours', '1-3 days', '3-7 days', 'More than 7 days'],
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'abdominal_pain_duration',
      documentationPhrase: 'Pain duration: {value}',
    },
    {
      id: 'q_progression',
      text: 'Is the pain getting better, worse, or staying the same?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Is the pain getting better or worse?' },
      ],
      type: 'chips',
      chips: ['Getting better', 'Getting worse', 'Staying the same', 'Moved from one area to another'],
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'abdominal_pain_progression',
      documentationPhrase: 'Pain progression: {value}',
    },

    // ── Severity ──
    {
      id: 'q_severity',
      text: 'How severe is the pain on a scale of 0-10?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'How much does it hurt? Does it make the child cry?' },
      ],
      type: 'chips',
      chips: ['Mild (1-3) — noticeable but tolerable', 'Moderate (4-6) — interferes with activity', 'Severe (7-10) — unable to move or find comfortable position'],
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'abdominal_pain_severity',
      documentationPhrase: 'Severity: {value}',
    },
    {
      id: 'q_aggravating',
      text: 'What makes the pain worse?',
      alternatives: [],
      type: 'chips',
      chips: ['Eating', 'Movement / coughing', 'Lying still', 'Passing stool', 'Nothing in particular'],
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'abdominal_pain_aggravating',
      documentationPhrase: 'Aggravated by {value}',
    },
    {
      id: 'q_relieving',
      text: 'What makes the pain better?',
      alternatives: [],
      type: 'chips',
      chips: ['Lying still / not moving', 'Passing stool / flatus', 'Bending over', 'Medication', 'Nothing provides relief'],
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'abdominal_pain_relieving',
      documentationPhrase: 'Relieved by {value}',
    },

    // ── Associated Symptoms ──
    {
      id: 'q_nausea_vomiting',
      text: 'Do you have nausea or vomiting?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child feel sick or vomit?' },
      ],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'abdominal_pain_nausea_vomiting',
      documentationPhrase: 'Associated nausea/vomiting',
    },
    {
      id: 'q_fever',
      text: 'Do you have a fever?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child have a fever?' },
      ],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'abdominal_pain_fever',
      documentationPhrase: 'Associated with fever',
    },
    {
      id: 'q_appetite',
      text: 'Has your appetite changed?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Is the child eating normally?' },
      ],
      type: 'chips',
      chips: ['Normal appetite', 'Reduced appetite', 'No appetite / anorexia', 'Increased appetite'],
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'abdominal_pain_appetite',
      documentationPhrase: 'Appetite: {value}',
    },
    {
      id: 'q_bowel_habit',
      text: 'Any change in your bowel habits?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Has the child been pooping normally?' },
      ],
      type: 'chips',
      chips: ['Normal', 'Constipated', 'Diarrhea', 'Unable to pass stool or flatus'],
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'abdominal_pain_bowel_habit',
      documentationPhrase: 'Bowel habit: {value}',
    },

    // ── Previous History ──
    {
      id: 'q_previous_surgeries',
      text: 'Have you had any abdominal surgeries in the past?',
      alternatives: [],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 25,
      factKey: 'abdominal_pain_previous_surgeries',
      documentationPhrase: 'Previous abdominal surgeries',
    },
    {
      id: 'q_previous_episodes',
      text: 'Have you had similar abdominal pain before?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Has the child had similar tummy pain before?' },
      ],
      type: 'boolean',
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'abdominal_pain_previous_episodes',
      documentationPhrase: 'Previous similar episodes',
    },
    {
      id: 'q_menstrual',
      text: '(If female) When was your last menstrual period?',
      alternatives: [],
      type: 'chips',
      chips: ['Within normal cycle', 'Missed / late period', 'Pregnant', 'Not applicable'],
      required: false,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'abdominal_pain_menstrual',
      documentationPhrase: 'Menstrual history: {value}',
    },
    {
      id: 'q_urinary',
      text: 'Any urinary symptoms (pain, frequency, blood)?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does it hurt when the child passes urine?' },
      ],
      type: 'boolean',
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'abdominal_pain_urinary',
      documentationPhrase: 'Associated urinary symptoms',
    },

    // ── Pediatric ──
    {
      id: 'q_ped_feeding',
      text: 'How is the child feeding?',
      alternatives: [],
      type: 'chips',
      chips: ['Feeding well', 'Feeding less', 'Refusing feeds', 'Vomiting all feeds'],
      required: false,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'abdominal_pain_ped_feeding',
      documentationPhrase: 'Feeding: {value}',
    },
    {
      id: 'q_ped_crying',
      text: 'Does the child cry constantly or in episodes?',
      alternatives: [],
      type: 'chips',
      chips: ['No unusual crying', 'Episodic / colicky crying', 'Constant crying / inconsolable'],
      required: false,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'abdominal_pain_ped_crying',
      documentationPhrase: 'Crying pattern: {value}',
    },

    // ── Red Flags ──
    {
      id: 'q_rigidity',
      text: 'Does the abdomen feel hard or rigid?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child\'s tummy feel hard?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 45,
      factKey: 'abdominal_pain_rigidity',
      documentationPhrase: 'Abdominal rigidity present',
    },
    {
      id: 'q_guarding',
      text: 'Do you tense your muscles when the abdomen is touched?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child tense up when the tummy is touched?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 40,
      factKey: 'abdominal_pain_guarding',
      documentationPhrase: 'Voluntary guarding present',
    },
    {
      id: 'q_rebound',
      text: 'Does the pain get worse when pressure is released suddenly?',
      alternatives: [],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 45,
      factKey: 'abdominal_pain_rebound',
      documentationPhrase: 'Rebound tenderness present',
    },
    {
      id: 'q_bleeding_gi',
      text: 'Any blood in vomit or stool?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Any blood in the child\'s vomit or poop?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 40,
      factKey: 'abdominal_pain_bleeding',
      documentationPhrase: 'GI bleeding present',
    },
  ],

  contextAdapters: {
    pediatric: {
      label: 'Pediatric Abdominal Pain Extension',
      additionalObjectives: [],
      additionalQuestions: [
        {
          id: 'q_ped_currant_jelly',
          text: 'Has the child passed any red, jelly-like stool?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 45,
          factKey: 'abdominal_pain_ped_currant_jelly',
          documentationPhrase: 'Currant jelly stool (intussusception)',
        },
        {
          id: 'q_ped_pallor',
          text: 'Does the child look pale or unwell?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 2,
          reasoningWeight: 25,
          factKey: 'abdominal_pain_ped_pallor',
          documentationPhrase: 'Pallor / unwell appearance',
        },
      ],
      suppressedQuestionIds: ['q_menstrual'],
      modifiedQuestions: [
        { id: 'q_severity', text: 'Is the pain bad enough to wake the child or stop play?' },
      ],
    },
    obstetric: {
      label: 'Obstetric Abdominal Pain Extension',
      additionalObjectives: [],
      additionalQuestions: [
        {
          id: 'q_obs_gestational_age',
          text: 'What is the gestational age?',
          alternatives: [],
          type: 'chips',
          chips: ['First trimester', 'Second trimester', 'Third trimester', 'Postpartum'],
          required: true,
          importance: 2,
          reasoningWeight: 20,
          factKey: 'abdominal_pain_obs_gestational',
          documentationPhrase: 'Gestational age: {value}',
        },
        {
          id: 'q_obs_vaginal_bleeding',
          text: 'Any vaginal bleeding?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 40,
          factKey: 'abdominal_pain_obs_bleeding',
          documentationPhrase: 'Vaginal bleeding present',
        },
        {
          id: 'q_obs_contractions',
          text: 'Are you having contractions?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 35,
          factKey: 'abdominal_pain_obs_contractions',
          documentationPhrase: 'Uterine contractions',
        },
      ],
      suppressedQuestionIds: [],
      modifiedQuestions: [
        { id: 'q_site', text: 'Where is the pain located? (particularly any pelvic or suprapubic pain)' },
      ],
    },
    surgical: {
      label: 'Surgical Abdominal Pain Extension',
      additionalObjectives: [],
      additionalQuestions: [
        {
          id: 'q_surg_psoas',
          text: 'Does the pain worsen when you lift your right leg against resistance?',
          alternatives: [],
          type: 'boolean',
          required: false,
          importance: 2,
          reasoningWeight: 30,
          factKey: 'abdominal_pain_surg_psoas',
          documentationPhrase: 'Positive psoas sign',
        },
        {
          id: 'q_surg_obturator',
          text: 'Does rotating your bent right leg inward cause pain?',
          alternatives: [],
          type: 'boolean',
          required: false,
          importance: 2,
          reasoningWeight: 30,
          factKey: 'abdominal_pain_surg_obturator',
          documentationPhrase: 'Positive obturator sign',
        },
      ],
      suppressedQuestionIds: [],
      modifiedQuestions: [],
    },
  },

  factExtraction: [
    { questionId: 'q_site', extract: (a) => [{ key: 'abdominal_pain_site', value: String(a), type: 'reported', questionId: 'q_site', documentationPhrase: 'Pain located in ' + a }] },
    { questionId: 'q_character', extract: (a) => [{ key: 'abdominal_pain_character', value: String(a), type: 'reported', questionId: 'q_character', documentationPhrase: 'Pain described as ' + a }] },
    { questionId: 'q_radiation', extract: (a) => [{ key: 'abdominal_pain_radiation', value: String(a), type: 'reported', questionId: 'q_radiation', documentationPhrase: 'Pain radiates ' + a }] },
    { questionId: 'q_onset', extract: (a) => [{ key: 'abdominal_pain_onset', value: String(a), type: 'reported', questionId: 'q_onset', documentationPhrase: 'Started ' + a + ' ago' }] },
    { questionId: 'q_duration', extract: (a) => [{ key: 'abdominal_pain_duration', value: String(a), type: 'reported', questionId: 'q_duration', documentationPhrase: 'Duration: ' + a }] },
    { questionId: 'q_progression', extract: (a) => [{ key: 'abdominal_pain_progression', value: String(a), type: 'reported', questionId: 'q_progression', documentationPhrase: 'Progression: ' + a }] },
    { questionId: 'q_severity', extract: (a) => [{ key: 'abdominal_pain_severity', value: String(a), type: 'reported', questionId: 'q_severity', documentationPhrase: 'Severity: ' + a }] },
    { questionId: 'q_nausea_vomiting', extract: (a) => a ? [{ key: 'abdominal_pain_nausea_vomiting', value: true, type: 'reported', questionId: 'q_nausea_vomiting', documentationPhrase: 'Associated nausea/vomiting' }] : [] },
    { questionId: 'q_fever', extract: (a) => a ? [{ key: 'abdominal_pain_fever', value: true, type: 'reported', questionId: 'q_fever', documentationPhrase: 'Associated with fever' }] : [] },
    { questionId: 'q_rigidity', extract: (a) => a ? [{ key: 'abdominal_pain_rigidity', value: true, type: 'reported', questionId: 'q_rigidity', documentationPhrase: 'Abdominal rigidity present' }] : [] },
    { questionId: 'q_guarding', extract: (a) => a ? [{ key: 'abdominal_pain_guarding', value: true, type: 'reported', questionId: 'q_guarding', documentationPhrase: 'Voluntary guarding present' }] : [] },
    { questionId: 'q_rebound', extract: (a) => a ? [{ key: 'abdominal_pain_rebound', value: true, type: 'reported', questionId: 'q_rebound', documentationPhrase: 'Rebound tenderness present' }] : [] },
    { questionId: 'q_bleeding_gi', extract: (a) => a ? [{ key: 'abdominal_pain_bleeding', value: true, type: 'reported', questionId: 'q_bleeding_gi', documentationPhrase: 'GI bleeding present' }] : [] },
    { questionId: 'q_previous_surgeries', extract: (a) => a ? [{ key: 'abdominal_pain_previous_surgeries', value: true, type: 'reported', questionId: 'q_previous_surgeries', documentationPhrase: 'Previous abdominal surgeries' }] : [] },
    { questionId: 'q_bowel_habit', extract: (a) => [{ key: 'abdominal_pain_bowel_habit', value: String(a), type: 'reported', questionId: 'q_bowel_habit', documentationPhrase: 'Bowel habit: ' + a }] },
    { questionId: 'q_menstrual', extract: (a) => [{ key: 'abdominal_pain_menstrual', value: String(a), type: 'reported', questionId: 'q_menstrual', documentationPhrase: 'Menstrual history: ' + a }] },
  ],

  relationships: [
    { targetSymptomId: 'SX000001', type: 'associated_with', strength: 0.5, description: 'May be associated with fever' },
    { targetSymptomId: 'SX000004', type: 'associated_with', strength: 0.7, description: 'Commonly associated with vomiting' },
    { targetSymptomId: 'SX000006', type: 'associated_with', strength: 0.5, description: 'May be associated with diarrhea' },
    { targetSymptomId: 'SX000003', type: 'associated_with', strength: 0.2, description: 'May be associated with body aches' },
  ],

  phenotypes: [
    {
      id: 'phen_abd_pain_appendicitis',
      label: 'Acute Appendicitis Phenotype',
      description: 'Periumbilical pain migrating to RLQ, with fever, anorexia, nausea',
      criteria: [
        { factKey: 'abdominal_pain_site', operator: 'contains', value: 'Right lower quadrant' },
        { factKey: 'abdominal_pain_fever', operator: 'eq', value: true },
      ],
      probability: 0.5,
      suggestsMechanisms: ['Appendiceal luminal obstruction', 'Bacterial overgrowth', 'Inflammatory distension', 'Perforation risk'],
      suggestsDifferentials: ['Acute appendicitis', 'Mesenteric adenitis', 'Meckel diverticulitis'],
      emergencyWeight: 75,
    },
    {
      id: 'phen_abd_pain_cholecystitis',
      label: 'Cholecystitis Phenotype',
      description: 'RUQ pain radiating to right shoulder, with fever, fatty food intolerance',
      criteria: [
        { factKey: 'abdominal_pain_site', operator: 'contains', value: 'Right upper quadrant' },
        { factKey: 'abdominal_pain_fever', operator: 'eq', value: true },
      ],
      probability: 0.5,
      suggestsMechanisms: ['Gallbladder outlet obstruction', 'Biliary stasis', 'Inflammatory edema'],
      suggestsDifferentials: ['Acute cholecystitis', 'Cholangitis', 'Biliary colic', 'Hepatic abscess'],
      emergencyWeight: 65,
    },
    {
      id: 'phen_abd_pain_pancreatitis',
      label: 'Pancreatitis Phenotype',
      description: 'Epigastric pain radiating to back, with vomiting, relieved by leaning forward',
      criteria: [
        { factKey: 'abdominal_pain_site', operator: 'contains', value: 'Epigastrium' },
        { factKey: 'abdominal_pain_character', operator: 'contains', value: 'Sharp' },
      ],
      probability: 0.4,
      suggestsMechanisms: ['Premature pancreatic enzyme activation', 'Acinar cell injury', 'Retroperitoneal inflammation'],
      suggestsDifferentials: ['Acute pancreatitis', 'Chronic pancreatitis', 'Pancreatic pseudocyst'],
      emergencyWeight: 70,
    },
    {
      id: 'phen_abd_pain_perforation',
      label: 'Perforation Phenotype',
      description: 'Sudden severe diffuse pain with board-like rigidity and peritonitis',
      criteria: [
        { factKey: 'abdominal_pain_rigidity', operator: 'eq', value: true },
        { factKey: 'abdominal_pain_rebound', operator: 'eq', value: true },
      ],
      probability: 0.6,
      suggestsMechanisms: ['Hollow viscus perforation', 'Chemical peritonitis', 'Bacterial contamination'],
      suggestsDifferentials: ['Peptic ulcer perforation', 'Diverticular perforation', 'Appendiceal perforation'],
      emergencyWeight: 95,
    },
    {
      id: 'phen_abd_pain_obstruction',
      label: 'Intestinal Obstruction Phenotype',
      description: 'Colicky pain with vomiting, distension, constipation, previous surgeries',
      criteria: [
        { factKey: 'abdominal_pain_character', operator: 'contains', value: 'Colicky' },
        { factKey: 'abdominal_pain_bowel_habit', operator: 'contains', value: 'Unable' },
      ],
      probability: 0.5,
      suggestsMechanisms: ['Mechanical bowel obstruction', 'Adhesions', 'Strangulation risk'],
      suggestsDifferentials: ['Small bowel obstruction', 'Large bowel obstruction', 'Paralytic ileus'],
      emergencyWeight: 85,
    },
    {
      id: 'phen_abd_pain_dyspepsia',
      label: 'Dyspepsia Phenotype',
      description: 'Epigastric burning or discomfort related to meals',
      criteria: [
        { factKey: 'abdominal_pain_site', operator: 'contains', value: 'Epigastrium' },
        { factKey: 'abdominal_pain_character', operator: 'contains', value: 'Burning' },
      ],
      probability: 0.5,
      suggestsMechanisms: ['Gastric acid hypersecretion', 'Mucosal irritation', 'Helicobacter pylori infection'],
      suggestsDifferentials: ['Gastritis', 'GERD', 'Peptic ulcer disease', 'Functional dyspepsia'],
      emergencyWeight: 15,
    },
    {
      id: 'phen_abd_pain_ibs',
      label: 'IBS Phenotype',
      description: 'Chronic recurrent abdominal pain with altered bowel habit, no red flags',
      criteria: [
        { factKey: 'abdominal_pain_previous_episodes', operator: 'eq', value: true },
        { factKey: 'abdominal_pain_bowel_habit', operator: 'contains', value: 'Normal' },
      ],
      probability: 0.3,
      suggestsMechanisms: ['Visceral hypersensitivity', 'Altered gut motility', 'Gut-brain axis dysregulation'],
      suggestsDifferentials: ['Irritable bowel syndrome', 'Functional abdominal pain', 'Visceral hyperalgesia'],
      emergencyWeight: 10,
    },
  ],

  documentation: [
    { id: 'doc_site', condition: { factKey: 'abdominal_pain_site', operator: 'present' }, template: 'Abdominal pain located in {{abdominal_pain_site}}.', priority: 1 },
    { id: 'doc_character', condition: { factKey: 'abdominal_pain_character', operator: 'present' }, template: 'Pain is {{abdominal_pain_character}} in nature.', priority: 1 },
    { id: 'doc_radiation', condition: { factKey: 'abdominal_pain_radiation', operator: 'present' }, template: 'Pain radiates {{abdominal_pain_radiation}}.', priority: 2 },
    { id: 'doc_duration', condition: { factKey: 'abdominal_pain_duration', operator: 'present' }, template: 'Duration: {{abdominal_pain_duration}}.', priority: 1 },
    { id: 'doc_severity', condition: { factKey: 'abdominal_pain_severity', operator: 'present' }, template: 'Severity: {{abdominal_pain_severity}}.', priority: 1 },
    { id: 'doc_fever', condition: { factKey: 'abdominal_pain_fever', operator: 'eq', value: true }, template: 'Associated with fever.', priority: 2 },
    { id: 'doc_nausea_vomiting', condition: { factKey: 'abdominal_pain_nausea_vomiting', operator: 'eq', value: true }, template: 'Associated nausea/vomiting.', priority: 2 },
    { id: 'doc_rigidity', condition: { factKey: 'abdominal_pain_rigidity', operator: 'eq', value: true }, template: 'ABDOMINAL RIGIDITY — peritonitis suspected.', priority: 1 },
    { id: 'doc_rebound', condition: { factKey: 'abdominal_pain_rebound', operator: 'eq', value: true }, template: 'REBOUND TENDERNESS — peritoneal irritation.', priority: 1 },
    { id: 'doc_bleeding', condition: { factKey: 'abdominal_pain_bleeding', operator: 'eq', value: true }, template: 'GI BLEEDING — urgent surgical referral.', priority: 1 },
    { id: 'doc_previous_surgeries', condition: { factKey: 'abdominal_pain_previous_surgeries', operator: 'eq', value: true }, template: 'Previous abdominal surgeries.', priority: 2 },
  ],

  reasoningHooks: [
    {
      id: 'rh_peritonitis',
      trigger: { on: 'fact_captured', ref: 'abdominal_pain_rigidity' },
      action: 'flag_red_flag',
      payload: ['Abdominal rigidity with pain — suspect peritonitis, urgent surgical consult, erect CXR for free air'],
    },
    {
      id: 'rh_rebound',
      trigger: { on: 'fact_captured', ref: 'abdominal_pain_rebound' },
      action: 'flag_red_flag',
      payload: ['Rebound tenderness — peritoneal irritation, surgical abdomen, CT scan and surgical evaluation'],
    },
    {
      id: 'rh_gi_bleeding',
      trigger: { on: 'fact_captured', ref: 'abdominal_pain_bleeding' },
      action: 'flag_red_flag',
      payload: ['GI bleeding with abdominal pain — urgent endoscopy, cross-match, surgical consult'],
    },
    {
      id: 'rh_rlq_pain_fever',
      trigger: { on: 'fact_captured', ref: 'abdominal_pain_site' },
      action: 'suggest_investigations',
      payload: ['RLQ pain with fever — urgent surgical evaluation for appendicitis, ultrasound/CT, blood count'],
    },
    {
      id: 'rh_obstruction',
      trigger: { on: 'fact_captured', ref: 'abdominal_pain_previous_surgeries' },
      action: 'suggest_differentials',
      payload: ['History of abdominal surgery with colicky pain — consider adhesive bowel obstruction, abdominal X-ray'],
    },
  ],

  completion: {
    objectives: [
      { objectiveId: 'obj_char', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_timeline', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_severity', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_associated', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_previous', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_pediatric', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_red_flags', status: 'not_started', answeredQuestions: [], percentage: 0 },
    ],
    overall: 0,
  },
};
