// ═══════════════════════════════════════════════════════════════════════════════
// Chest Pain Symptom Node — SX000009
// Sources: Hutchison Clinical Methods 25e, ACC/AHA Chest Pain Guidelines, WHO IMCI
// Universal Core + Pediatric + Obstetric + Emergency adapters
// ═══════════════════════════════════════════════════════════════════════════════

import type { SymptomNode } from '../symptom-types';

const chestPainHelpers = {
  makeExtract: (questionId: string, factKey: string, phrase: string) => ({
    questionId,
    extract: (answer: any) => {
      if (answer === undefined || answer === null || answer === '') return [];
      return [{ key: factKey, value: typeof answer === 'string' ? answer : String(answer), type: 'reported' as const, questionId, documentationPhrase: phrase }];
    },
  }),
  makeBooleanExtract: (questionId: string, factKey: string, phraseIfYes: string, phraseIfNo: string) => ({
    questionId,
    extract: (answer: any) => {
      if (answer === undefined || answer === null) return [];
      const isYes = answer === true || answer === 'yes' || answer === 'Yes';
      return [{ key: factKey, value: isYes, type: 'reported' as const, questionId, documentationPhrase: isYes ? phraseIfYes : phraseIfNo }];
    },
  }),
};

const CHEST_PAIN_OBJECTIVES = [
  { id: 'obj_char', label: 'Characterization', description: 'Establish site, quality, and radiation of chest pain', order: 1, required: true, questionIds: ['q_site', 'q_quality', 'q_radiation'] },
  { id: 'obj_timeline', label: 'Timeline', description: 'Onset, duration, progression, temporal pattern', order: 2, required: true, questionIds: ['q_onset', 'q_duration', 'q_progression', 'q_pattern'] },
  { id: 'obj_severity', label: 'Severity', description: 'Assess pain intensity and impact', order: 3, required: true, questionIds: ['q_severity', 'q_functional_impact'] },
  { id: 'obj_aggravating', label: 'Aggravating/Relieving', description: 'Identify triggers and relieving factors', order: 4, required: true, questionIds: ['q_aggravated_by', 'q_relieved_by', 'q_posture_relation'] },
  { id: 'obj_associated_cardiac', label: 'Cardiac Symptoms', description: 'Identify associated cardiac symptoms', order: 5, required: true, questionIds: ['q_palpitations', 'q_dyspnea', 'q_diaphoresis', 'q_nausea_associated', 'q_syncope'] },
  { id: 'obj_associated_resp', label: 'Respiratory Symptoms', description: 'Identify associated respiratory symptoms', order: 6, required: false, questionIds: ['q_cough_associated', 'q_fever_associated', 'q_hemoptysis'] },
  { id: 'obj_risk_factors', label: 'Risk Factors', description: 'Assess cardiovascular and thrombotic risk', order: 7, required: true, questionIds: ['q_hypertension', 'q_diabetes', 'q_smoking', 'q_family_cardiac', 'q_previous_cardiac'] },
  { id: 'obj_red_flags', label: 'Red Flag Screening', description: 'Identify life-threatening causes', order: 8, required: true, questionIds: ['q_crushing', 'q_tearing', 'q_hemodynamic', 'q_profound_weakness'] },
  { id: 'obj_previous', label: 'Previous Episodes', description: 'History of similar episodes', order: 9, required: false, questionIds: ['q_previous_episodes', 'q_previous_evaluation'] },
  { id: 'obj_pediatric', label: 'Pediatric Assessment', description: 'Age-appropriate chest pain assessment', order: 10, required: false, questionIds: ['q_trauma', 'q_exercise', 'q_anxiety'] },
];

export const CHEST_PAIN_NODE: SymptomNode = {
  identity: {
    id: 'SX000009',
    canonicalName: 'Chest Pain',
    synonyms: ['Thoracic pain', 'Precordial pain', 'Retrosternal pain', 'Angina pectoris', 'Substernal pain'],
    layTerms: ['Chest discomfort', 'Pain in the chest', 'Heart pain', 'Tightness in chest', 'Heaviness in chest'],
    translations: { sw: 'Maumivu ya kifua', lu: 'Aoho koonda', mer: 'Mwiru nkoromo', kis: 'Erori egamba' },
    snomed: '29857009',
    icd10: 'R07.9',
    umls: 'C0008031',
    bodySystem: 'Cardiovascular',
    primarySpecialty: 'Cardiology',
    emergencyWeight: 5,
  },

  metadata: {
    version: '1.0.0',
    author: 'AMEXAN Clinical Constitution',
    evidenceLevel: 'consensus',
    lastUpdated: '2026-07-13',
    source: 'Hutchison Clinical Methods 25e, ACC/AHA Chest Pain Guidelines, WHO IMCI',
  },

  activation: {
    chiefComplaint: true,
    hpiMention: true,
    ros: true,
    referralLetter: true,
    voiceTranscription: true,
    keywords: ['chest pain', 'chest tightness', 'chest discomfort', 'precordial pain', 'angina', 'retrosternal', 'substernal', 'heart pain', 'maumivu ya kifua'],
  },

  timeline: {
    allowed: ['acute', 'subacute', 'chronic', 'recurrent', 'unknown'],
    defaultCategory: 'acute',
  },

  objectives: CHEST_PAIN_OBJECTIVES,

  questions: [
    // ── Characterization ──
    {
      id: 'q_site',
      text: 'Where exactly is the pain located?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Where does it hurt? Can you point to the spot?' },
      ],
      type: 'chips',
      chips: ['Center of chest (retrosternal)', 'Left side of chest', 'Right side of chest', 'Under left breast', 'Across entire chest', 'Upper abdomen / epigastric'],
      required: true,
      importance: 2,
      reasoningWeight: 25,
      factKey: 'chest_pain_site',
      documentationPhrase: 'Pain located {value}',
    },
    {
      id: 'q_quality',
      text: 'How would you describe the pain?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Can you describe the pain? Does it feel sharp, heavy, or something else?' },
      ],
      type: 'chips',
      chips: ['Crushing / pressure / heaviness', 'Sharp / stabbing', 'Burning', 'Aching / dull', 'Tearing / ripping', 'Tight / squeezing', 'Stinging'],
      required: true,
      importance: 3,
      reasoningWeight: 30,
      factKey: 'chest_pain_quality',
      documentationPhrase: 'Pain is {value} in nature',
    },
    {
      id: 'q_radiation',
      text: 'Does the pain spread anywhere else?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the pain move to anywhere else?' },
      ],
      type: 'chips',
      chips: ['Left arm / shoulder', 'Right arm / shoulder', 'Jaw / neck', 'Back', 'Between shoulder blades', 'Epigastric', 'No radiation'],
      required: true,
      importance: 3,
      reasoningWeight: 25,
      factKey: 'chest_pain_radiation',
      documentationPhrase: 'Pain radiates to {value}',
    },

    // ── Timeline ──
    {
      id: 'q_onset',
      text: 'When did the pain start?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'When did the pain start?' },
      ],
      type: 'chips',
      chips: ['Minutes ago', 'Hours ago', 'Yesterday', 'Days ago', 'Weeks ago'],
      required: true,
      importance: 3,
      reasoningWeight: 30,
      factKey: 'chest_pain_onset',
      documentationPhrase: 'Pain started {value} ago',
    },
    {
      id: 'q_duration',
      text: 'How long does the pain last each time?',
      alternatives: [],
      type: 'chips',
      chips: ['Seconds', 'Minutes', 'Hours', 'Continuous / constant', 'Comes and goes'],
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'chest_pain_duration',
      documentationPhrase: 'Pain episodes last {value}',
    },
    {
      id: 'q_progression',
      text: 'How has the pain changed since it started?',
      alternatives: [],
      type: 'chips',
      chips: ['Getting worse', 'Staying the same', 'Getting better', 'Comes and goes'],
      required: false,
      importance: 1,
      reasoningWeight: 15,
      factKey: 'chest_pain_progression',
      documentationPhrase: 'Pain is {value}',
    },
    {
      id: 'q_pattern',
      text: 'Is the pain constant or does it come and go?',
      alternatives: [],
      type: 'chips',
      chips: ['Constant', 'Intermittent (comes and goes)', 'Related to activity', 'Occurs at rest', 'Awakens from sleep'],
      required: false,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'chest_pain_pattern',
      documentationPhrase: 'Pain pattern: {value}',
    },

    // ── Severity ──
    {
      id: 'q_severity',
      text: 'How severe is the pain on a scale of 0-10?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'How bad is the pain? Does it stop them from playing?' },
      ],
      type: 'scale',
      required: true,
      importance: 3,
      reasoningWeight: 25,
      factKey: 'chest_pain_severity',
      documentationPhrase: 'Pain severity {value}/10',
    },
    {
      id: 'q_functional_impact',
      text: 'How has the pain affected your daily activities?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Has the pain stopped the child from playing or going to school?' },
      ],
      type: 'chips',
      chips: ['Unable to move / bedridden', 'Difficulty walking', 'Can function but limited', 'No limitation'],
      required: true,
      importance: 2,
      reasoningWeight: 15,
      factKey: 'chest_pain_functional_impact',
      documentationPhrase: 'Functional impact: {value}',
    },

    // ── Aggravating Factors ──
    {
      id: 'q_aggravated_by',
      text: 'What makes the pain worse?',
      alternatives: [],
      type: 'chips',
      chips: ['Exertion / exercise', 'Deep breathing', 'Coughing / sneezing', 'Lying flat', 'Swallowing', 'Moving / changing position', 'Stress / emotion', 'Nothing specific'],
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'chest_pain_aggravated_by',
      documentationPhrase: 'Aggravated by {value}',
    },
    {
      id: 'q_relieved_by',
      text: 'What makes the pain better?',
      alternatives: [],
      type: 'chips',
      chips: ['Rest / sitting still', 'Sitting up / leaning forward', 'Pain medications', 'Deep breaths', 'Nothing helps'],
      required: true,
      importance: 2,
      reasoningWeight: 15,
      factKey: 'chest_pain_relieved_by',
      documentationPhrase: 'Relieved by {value}',
    },
    {
      id: 'q_posture_relation',
      text: 'Is the pain related to your body position?',
      alternatives: [],
      type: 'chips',
      chips: ['Worse lying flat', 'Worse on left side', 'Better sitting up', 'Better leaning forward', 'No relation'],
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'chest_pain_posture',
      documentationPhrase: 'Pain related to posture: {value}',
    },

    // ── Associated Cardiac Symptoms ──
    {
      id: 'q_palpitations',
      text: 'Do you feel your heart racing, skipping, or pounding?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child complain of heart racing?' },
      ],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'chest_pain_palpitations',
      documentationPhrase: 'Associated palpitations',
    },
    {
      id: 'q_dyspnea',
      text: 'Do you have shortness of breath with the pain?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child have difficulty breathing with the pain?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 30,
      factKey: 'chest_pain_dyspnea',
      documentationPhrase: 'Associated with dyspnea',
    },
    {
      id: 'q_diaphoresis',
      text: 'Do you break into a cold sweat with the pain?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child feel sweaty or clammy?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 25,
      factKey: 'chest_pain_diaphoresis',
      documentationPhrase: 'Associated with diaphoresis',
    },
    {
      id: 'q_nausea_associated',
      text: 'Do you feel nauseous or have vomited?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Has the child vomited or felt sick?' },
      ],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 15,
      factKey: 'chest_pain_nausea',
      documentationPhrase: 'Associated with nausea/vomiting',
    },
    {
      id: 'q_syncope',
      text: 'Did you faint or feel like you might faint?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Did the child collapse or feel dizzy?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 35,
      factKey: 'chest_pain_syncope',
      documentationPhrase: 'Associated with syncope or presyncope',
    },

    // ── Associated Respiratory Symptoms ──
    {
      id: 'q_cough_associated',
      text: 'Do you have a cough?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child have a cough?' },
      ],
      type: 'boolean',
      required: true,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'chest_pain_cough',
      documentationPhrase: 'Associated with cough',
    },
    {
      id: 'q_fever_associated',
      text: 'Do you have a fever?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child have a fever?' },
      ],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 15,
      factKey: 'chest_pain_fever',
      documentationPhrase: 'Associated with fever',
    },

    // ── Risk Factors ──
    {
      id: 'q_hypertension',
      text: 'Do you have high blood pressure?',
      alternatives: [],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'chest_pain_hypertension',
      documentationPhrase: 'History of hypertension',
    },
    {
      id: 'q_diabetes',
      text: 'Do you have diabetes?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child have diabetes?' },
      ],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'chest_pain_diabetes',
      documentationPhrase: 'History of diabetes',
    },
    {
      id: 'q_smoking',
      text: 'Do you smoke or use tobacco?',
      alternatives: [
        { condition: { ageMax: 13 }, text: 'Has anyone in the home been smoking around the child?' },
        { condition: { ageMax: 5 }, text: '', type: 'boolean' },
      ],
      type: 'chips',
      chips: ['Current smoker', 'Former smoker', 'Never smoked', 'Passive smoke exposure'],
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'chest_pain_smoking',
      documentationPhrase: 'Tobacco use: {value}',
    },
    {
      id: 'q_family_cardiac',
      text: 'Any family history of early heart disease or sudden death?',
      alternatives: [],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'chest_pain_family_cardiac',
      documentationPhrase: 'Family history of early cardiac disease',
    },
    {
      id: 'q_previous_cardiac',
      text: 'Have you ever been told you have a heart condition?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Has the child ever been diagnosed with a heart condition?' },
      ],
      type: 'chips',
      chips: ['Heart attack / MI', 'Angina', 'Heart failure', 'Arrhythmia', 'Valve disease', 'No prior cardiac history'],
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'chest_pain_previous_cardiac',
      documentationPhrase: 'Prior cardiac history: {value}',
    },

    // ── Red Flags ──
    {
      id: 'q_crushing',
      text: 'Is the pain a crushing or heavy pressure sensation?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the chest feel like something heavy is pressing on it?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 40,
      factKey: 'chest_pain_crushing',
      documentationPhrase: 'Crushing / heavy pressure sensation',
    },
    {
      id: 'q_tearing',
      text: 'Is the pain a tearing or ripping sensation?',
      alternatives: [],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 45,
      factKey: 'chest_pain_tearing',
      documentationPhrase: 'Tearing / ripping sensation',
    },
    {
      id: 'q_hemodynamic',
      text: 'Do you feel dizzy, lightheaded, or that you might pass out?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child seem unusually drowsy or difficult to wake?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 35,
      factKey: 'chest_pain_hemodynamic',
      documentationPhrase: 'Hemodynamic instability symptoms',
    },
    {
      id: 'q_profound_weakness',
      text: 'Do you feel sudden profound weakness or fatigue?',
      alternatives: [],
      type: 'boolean',
      required: false,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'chest_pain_weakness',
      documentationPhrase: 'Profound weakness',
    },

    // ── Previous Episodes ──
    {
      id: 'q_previous_episodes',
      text: 'Have you had similar chest pain before?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Has the child had similar pain before?' },
      ],
      type: 'boolean',
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'chest_pain_previous_episodes',
      documentationPhrase: 'Previous similar episodes',
    },
    {
      id: 'q_previous_evaluation',
      text: 'Have you been evaluated for chest pain before? (ECG, stress test, etc.)',
      alternatives: [],
      type: 'boolean',
      required: false,
      importance: 1,
      reasoningWeight: 5,
      factKey: 'chest_pain_previous_evaluation',
      documentationPhrase: 'Previously evaluated for chest pain',
    },

    // ── Pediatric-specific ──
    {
      id: 'q_trauma',
      text: 'Has there been any recent injury to the chest?',
      alternatives: [],
      type: 'boolean',
      required: false,
      importance: 2,
      reasoningWeight: 15,
      factKey: 'chest_pain_trauma',
      documentationPhrase: 'Recent chest trauma',
    },
    {
      id: 'q_exercise',
      text: 'Does the pain happen during or after exercise?',
      alternatives: [],
      type: 'boolean',
      required: false,
      importance: 2,
      reasoningWeight: 15,
      factKey: 'chest_pain_exercise',
      documentationPhrase: 'Exertion-related chest pain',
    },
    {
      id: 'q_anxiety',
      text: 'Has the child been anxious or stressed recently?',
      alternatives: [],
      type: 'boolean',
      required: false,
      importance: 1,
      reasoningWeight: 5,
      factKey: 'chest_pain_anxiety',
      documentationPhrase: 'Anxiety identified as possible contributor',
    },
  ],

  contextAdapters: {
    pediatric: {
      label: 'Pediatric Chest Pain Extension',
      additionalObjectives: [
        { id: 'obj_ped_congenital', label: 'Congenital Assessment', description: 'Assess for congenital heart disease', order: 11, required: false, questionIds: ['q_ped_congenital'] },
      ],
      additionalQuestions: [
        {
          id: 'q_ped_congenital',
          text: 'Known congenital heart disease?',
          alternatives: [],
          type: 'boolean',
          required: false,
          importance: 3,
          reasoningWeight: 25,
          factKey: 'chest_pain_ped_congenital',
          documentationPhrase: 'Known congenital heart disease',
        },
      ],
      suppressedQuestionIds: ['q_hypertension', 'q_diabetes', 'q_smoking', 'q_family_cardiac'],
      modifiedQuestions: [
        { id: 'q_previous_cardiac', text: 'Has the child been diagnosed with any heart problem?' },
      ],
    },
    obstetric: {
      label: 'Obstetric Chest Pain Extension',
      additionalObjectives: [],
      additionalQuestions: [
        {
          id: 'q_ob_preeclampsia',
          text: 'Do you have high blood pressure or swelling in your legs/face?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 40,
          factKey: 'chest_pain_ob_preeclampsia',
          documentationPhrase: 'Assessed for pre-eclampsia',
        },
        {
          id: 'q_ob_pulmonary_embolism',
          text: 'Any sudden onset shortness of breath or calf pain/swelling?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 40,
          factKey: 'chest_pain_ob_pe',
          documentationPhrase: 'Assessed for pulmonary embolism',
        },
      ],
      suppressedQuestionIds: [],
      modifiedQuestions: [],
    },
    emergency: {
      label: 'Emergency Chest Pain Extension',
      additionalObjectives: [
        { id: 'obj_emergency', label: 'Emergency Screening', description: 'ABCDE assessment for chest pain', order: 0, required: true, questionIds: ['q_abcde'] },
      ],
      additionalQuestions: [
        {
          id: 'q_abcde',
          text: 'Any ABCDE danger signs? (Airway compromise, respiratory distress, shock, altered consciousness)',
          alternatives: [],
          type: 'multiple',
          chips: ['Airway compromise', 'Severe respiratory distress', 'Shock / hypotension', 'Altered consciousness', 'Cardiac arrest', 'None'],
          required: true,
          importance: 3,
          reasoningWeight: 50,
          factKey: 'chest_pain_abcde',
          documentationPhrase: 'ABCDE: {value}',
        },
      ],
      suppressedQuestionIds: [],
      modifiedQuestions: [],
    },
  },

  factExtraction: [
    chestPainHelpers.makeExtract('q_site', 'chest_pain_site', 'Pain location'),
    chestPainHelpers.makeExtract('q_quality', 'chest_pain_quality', 'Pain quality'),
    chestPainHelpers.makeExtract('q_radiation', 'chest_pain_radiation', 'Pain radiation'),
    chestPainHelpers.makeExtract('q_onset', 'chest_pain_onset', 'Pain onset'),
    chestPainHelpers.makeExtract('q_duration', 'chest_pain_duration', 'Pain duration'),
    chestPainHelpers.makeExtract('q_severity', 'chest_pain_severity', 'Pain severity'),
    chestPainHelpers.makeExtract('q_aggravated_by', 'chest_pain_aggravated_by', 'Aggravating factors'),
    chestPainHelpers.makeExtract('q_relieved_by', 'chest_pain_relieved_by', 'Relieving factors'),
    chestPainHelpers.makeBooleanExtract('q_dyspnea', 'chest_pain_dyspnea', 'Dyspnea present', 'No dyspnea'),
    chestPainHelpers.makeBooleanExtract('q_diaphoresis', 'chest_pain_diaphoresis', 'Diaphoresis present', 'No diaphoresis'),
    chestPainHelpers.makeBooleanExtract('q_palpitations', 'chest_pain_palpitations', 'Palpitations present', 'No palpitations'),
    chestPainHelpers.makeBooleanExtract('q_nausea_associated', 'chest_pain_nausea', 'Nausea present', 'No nausea'),
    chestPainHelpers.makeBooleanExtract('q_syncope', 'chest_pain_syncope', 'Syncope/presyncope present', 'No syncope'),
    chestPainHelpers.makeBooleanExtract('q_crushing', 'chest_pain_crushing', 'Crushing chest pain', 'No crushing sensation'),
    chestPainHelpers.makeBooleanExtract('q_tearing', 'chest_pain_tearing', 'Tearing chest pain', 'No tearing sensation'),
    chestPainHelpers.makeBooleanExtract('q_cough_associated', 'chest_pain_cough', 'Cough present', 'No cough'),
    chestPainHelpers.makeBooleanExtract('q_fever_associated', 'chest_pain_fever', 'Fever present', 'No fever'),
    chestPainHelpers.makeBooleanExtract('q_hypertension', 'chest_pain_hypertension', 'History of hypertension', 'No hypertension'),
    chestPainHelpers.makeBooleanExtract('q_diabetes', 'chest_pain_diabetes', 'History of diabetes', 'No diabetes'),
    chestPainHelpers.makeExtract('q_smoking', 'chest_pain_smoking', 'Smoking history'),
    chestPainHelpers.makeExtract('q_previous_cardiac', 'chest_pain_previous_cardiac', 'Prior cardiac history'),
    chestPainHelpers.makeBooleanExtract('q_family_cardiac', 'chest_pain_family_cardiac', 'Family history of cardiac disease', 'No family cardiac history'),
    chestPainHelpers.makeBooleanExtract('q_syncope', 'chest_pain_syncope', 'Syncope reported', 'No syncope'),
  ],

  relationships: [
    { targetSymptomId: 'SX000008', type: 'associated_with', strength: 0.7, description: 'Often accompanied by shortness of breath' },
    { targetSymptomId: 'SX000001', type: 'associated_with', strength: 0.5, description: 'May be accompanied by fever' },
    { targetSymptomId: 'SX000005', type: 'associated_with', strength: 0.4, description: 'May be associated with cough' },
    { targetSymptomId: 'SX000004', type: 'associated_with', strength: 0.3, description: 'May be associated with nausea/vomiting' },
  ],

  phenotypes: [
    {
      id: 'phen_chest_pain_acs',
      label: 'Acute Coronary Syndrome Phenotype',
      description: 'Crushing substernal chest pain with radiation to left arm/jaw, dyspnea, diaphoresis, nausea',
      criteria: [
        { factKey: 'chest_pain_quality', operator: 'contains', value: 'Crushing' },
        { factKey: 'chest_pain_dyspnea', operator: 'eq', value: true },
      ],
      probability: 0.5,
      suggestsMechanisms: ['acute_myocardial_ischemia', 'coronary_thrombosis', 'myocardial_oxygen_demand_mismatch'],
      suggestsDifferentials: ['ST-elevation myocardial infarction', 'Non-ST-elevation myocardial infarction', 'Unstable angina'],
      emergencyWeight: 95,
    },
    {
      id: 'phen_chest_pain_pericarditis',
      label: 'Pericarditis Phenotype',
      description: 'Sharp chest pain worse lying flat, better sitting forward, with fever, recent viral illness',
      criteria: [
        { factKey: 'chest_pain_quality', operator: 'contains', value: 'Sharp' },
        { factKey: 'chest_pain_posture', operator: 'contains', value: 'Worse lying flat' },
      ],
      probability: 0.4,
      suggestsMechanisms: ['pericardial_inflammation', 'serosal_inflammation'],
      suggestsDifferentials: ['Acute pericarditis', 'Myopericarditis'],
      emergencyWeight: 60,
    },
    {
      id: 'phen_chest_pain_pulmonary_embolism',
      label: 'Pulmonary Embolism Phenotype',
      description: 'Sudden pleuritic chest pain with dyspnea, hemoptysis, syncope, risk factors',
      criteria: [
        { factKey: 'chest_pain_quality', operator: 'contains', value: 'Sharp' },
        { factKey: 'chest_pain_aggravated_by', operator: 'contains', value: 'Deep breathing' },
        { factKey: 'chest_pain_dyspnea', operator: 'eq', value: true },
      ],
      probability: 0.4,
      suggestsMechanisms: ['pulmonary_artery_occlusion', 'ventilation_perfusion_mismatch'],
      suggestsDifferentials: ['Pulmonary embolism', 'Pulmonary infarction'],
      emergencyWeight: 90,
    },
    {
      id: 'phen_chest_pain_aortic_dissection',
      label: 'Aortic Dissection Phenotype',
      description: 'Sudden severe tearing chest pain radiating to back, with hypertension, syncope',
      criteria: [
        { factKey: 'chest_pain_quality', operator: 'contains', value: 'Tearing' },
      ],
      probability: 0.3,
      suggestsMechanisms: ['aortic_wall_dissection', 'acute_aortic_syndrome'],
      suggestsDifferentials: ['Aortic dissection', 'Aortic intramural hematoma'],
      emergencyWeight: 98,
    },
    {
      id: 'phen_chest_pain_msk',
      label: 'Musculoskeletal Chest Pain Phenotype',
      description: 'Sharp localized chest wall pain reproducible with palpation or movement',
      criteria: [
        { factKey: 'chest_pain_quality', operator: 'contains', value: 'Sharp' },
        { factKey: 'chest_pain_aggravated_by', operator: 'contains', value: 'Moving' },
      ],
      probability: 0.4,
      suggestsMechanisms: ['chest_wall_tenderness', 'costochondral_inflammation', 'muscle_spasm'],
      suggestsDifferentials: ['Costochondritis', 'Chest wall strain', 'Rib fracture', 'Fibromyalgia'],
      emergencyWeight: 10,
    },
    {
      id: 'phen_chest_pain_pleuritic',
      label: 'Pleuritic Pain Phenotype',
      description: 'Sharp pain with deep breathing/coughing, associated with cough and fever',
      criteria: [
        { factKey: 'chest_pain_aggravated_by', operator: 'contains', value: 'Deep breathing' },
        { factKey: 'chest_pain_cough', operator: 'eq', value: true },
      ],
      probability: 0.3,
      suggestsMechanisms: ['pleural_inflammation', 'parenchymal_inflammation'],
      suggestsDifferentials: ['Pleurisy', 'Pneumonia with pleural involvement', 'Pneumothorax'],
      emergencyWeight: 40,
    },
  ],

  documentation: [
    { id: 'doc_site', condition: { factKey: 'chest_pain_site', operator: 'present' }, template: 'Chest pain located {{chest_pain_site}}.', priority: 1 },
    { id: 'doc_quality', condition: { factKey: 'chest_pain_quality', operator: 'present' }, template: 'Pain described as {{chest_pain_quality}}.', priority: 1 },
    { id: 'doc_radiation', condition: { factKey: 'chest_pain_radiation', operator: 'present' }, template: 'Pain radiates to {{chest_pain_radiation}}.', priority: 1 },
    { id: 'doc_severity', condition: { factKey: 'chest_pain_severity', operator: 'present' }, template: 'Severity rated {{chest_pain_severity}}/10.', priority: 1 },
    { id: 'doc_crushing', condition: { factKey: 'chest_pain_crushing', operator: 'eq', value: true }, template: 'CRUSHING CHEST PAIN — RED FLAG for acute coronary syndrome.', priority: 1 },
    { id: 'doc_tearing', condition: { factKey: 'chest_pain_tearing', operator: 'eq', value: true }, template: 'TEARING CHEST PAIN — RED FLAG for aortic dissection.', priority: 1 },
    { id: 'doc_dyspnea', condition: { factKey: 'chest_pain_dyspnea', operator: 'eq', value: true }, template: 'Associated with dyspnea.', priority: 2 },
    { id: 'doc_diaphoresis', condition: { factKey: 'chest_pain_diaphoresis', operator: 'eq', value: true }, template: 'Associated with diaphoresis.', priority: 2 },
    { id: 'doc_syncope', condition: { factKey: 'chest_pain_syncope', operator: 'eq', value: true }, template: 'Associated with syncope/presyncope.', priority: 1 },
    { id: 'doc_radiation_arm', condition: { factKey: 'chest_pain_radiation', operator: 'present' }, template: 'Radiation to arm — classic for cardiac ischemia.', priority: 2 },
    { id: 'doc_hypertension', condition: { factKey: 'chest_pain_hypertension', operator: 'eq', value: true }, template: 'History of hypertension — increased cardiovascular risk.', priority: 2 },
    { id: 'doc_diabetes', condition: { factKey: 'chest_pain_diabetes', operator: 'eq', value: true }, template: 'History of diabetes — increased cardiovascular risk.', priority: 2 },
  ],

  reasoningHooks: [
    {
      id: 'rh_crushing_pain',
      trigger: { on: 'fact_captured', ref: 'chest_pain_crushing' },
      action: 'flag_red_flag',
      payload: ['Crushing chest pain — red flag for ACS — obtain ECG, cardiac enzymes STAT'],
    },
    {
      id: 'rh_tearing_pain',
      trigger: { on: 'fact_captured', ref: 'chest_pain_tearing' },
      action: 'flag_red_flag',
      payload: ['Tearing chest pain — red flag for aortic dissection — urgent imaging needed'],
    },
    {
      id: 'rh_syncope',
      trigger: { on: 'fact_captured', ref: 'chest_pain_syncope' },
      action: 'flag_red_flag',
      payload: ['Chest pain with syncope — high risk for life-threatening cardiac event'],
    },
    {
      id: 'rh_dyspnea_diaphoresis',
      trigger: { on: 'fact_captured', ref: 'chest_pain_dyspnea' },
      action: 'suggest_investigations',
      payload: ['ECG', 'Cardiac troponin', 'Chest X-ray', 'D-dimer'],
    },
    {
      id: 'rh_ob_preeclampsia',
      trigger: { on: 'fact_captured', ref: 'chest_pain_ob_preeclampsia' },
      action: 'flag_red_flag',
      payload: ['Pregnant with chest pain and hypertension — pre-eclampsia until proven otherwise'],
    },
    {
      id: 'rh_ob_pe',
      trigger: { on: 'fact_captured', ref: 'chest_pain_ob_pe' },
      action: 'flag_red_flag',
      payload: ['Pregnant with chest pain and dyspnea — pulmonary embolism in pregnancy'],
    },
  ],

  completion: {
    objectives: CHEST_PAIN_OBJECTIVES.map(o => ({
      objectiveId: o.id,
      status: 'not_started' as const,
      answeredQuestions: [] as string[],
      percentage: 0,
    })),
    overall: 0,
  },
};
