// ═══════════════════════════════════════════════════════════════════════════════
// Cough Symptom Node — SX000005
// Sources: Hutchison Clinical Methods 25e, WHO IMCI, BTS Cough Guidelines
// Universal Core + Pediatric adapter
// ═══════════════════════════════════════════════════════════════════════════════

import type { SymptomNode } from '../symptom-types';

export const COUGH_NODE: SymptomNode = {
  identity: {
    id: 'SX000005',
    canonicalName: 'Cough',
    synonyms: ['Tussis', 'Expectoration', 'Productive cough', 'Dry cough'],
    layTerms: ['Coughing', 'Clearing throat', 'Hacking cough', 'Barking cough', 'Wet cough'],
    translations: { sw: 'Kikohozi', lu: 'Orifwo', mer: 'Mukororo', kis: 'Egese' },
    snomed: '49727002',
    icd10: 'R05',
    umls: 'C0010200',
    bodySystem: 'Respiratory',
    primarySpecialty: 'Pulmonology',
    emergencyWeight: 3,
  },

  metadata: {
    version: '1.0.0',
    author: 'AMEXAN Clinical Constitution',
    evidenceLevel: 'consensus',
    lastUpdated: '2026-07-13',
    source: 'Hutchison Clinical Methods 25e, British Thoracic Society guidelines, WHO IMCI',
  },

  activation: {
    chiefComplaint: true,
    hpiMention: true,
    ros: true,
    referralLetter: true,
    voiceTranscription: true,
    keywords: ['cough', 'coughing', 'kikohozi', 'expectoration', 'hacking', 'barking cough', 'whooping', 'wet cough'],
  },

  timeline: {
    allowed: ['acute', 'subacute', 'chronic', 'recurrent', 'unknown'],
    defaultCategory: 'acute',
  },

  objectives: [
    { id: 'obj_char', label: 'Characterization', description: 'Establish cough type, quality, timing', order: 1, required: true, questionIds: ['q_type', 'q_timing', 'q_dry_vs_wet'] },
    { id: 'obj_timeline', label: 'Timeline', description: 'Onset, duration, progression', order: 2, required: true, questionIds: ['q_onset', 'q_duration', 'q_progression'] },
    { id: 'obj_severity', label: 'Severity', description: 'Assess intensity and impact', order: 3, required: true, questionIds: ['q_severity', 'q_sleep_disturbance'] },
    { id: 'obj_sputum', label: 'Sputum Characteristics', description: 'Assess sputum volume, color, consistency', order: 4, required: false, questionIds: ['q_sputum_color', 'q_sputum_volume', 'q_hemoptysis'] },
    { id: 'obj_associated', label: 'Associated Symptoms', description: 'Identify accompanying respiratory and systemic symptoms', order: 5, required: true, questionIds: ['q_fever', 'q_dyspnea', 'q_chest_pain', 'q_wheeze', 'q_nasal', 'q_hoarseness'] },
    { id: 'obj_exposure', label: 'Exposure History', description: 'Identify infectious and environmental exposures', order: 6, required: false, questionIds: ['q_sick_contact', 'q_smoking', 'q_tb_contact', 'q_occupational'] },
    { id: 'obj_previous', label: 'Previous Episodes', description: 'History of similar episodes or chronic conditions', order: 7, required: false, questionIds: ['q_previous_episodes', 'q_asthma_history', 'q_reflux'] },
    { id: 'obj_pediatric', label: 'Pediatric Assessment', description: 'Age-appropriate cough assessment', order: 8, required: false, questionIds: ['q_immunization', 'q_feeding', 'q_stridor', 'q_whoop'] },
    { id: 'obj_red_flags', label: 'Red Flags', description: 'Identify warning signs requiring urgent attention', order: 9, required: true, questionIds: ['q_hemoptysis', 'q_dyspnea_rest', 'q_cyanosis', 'q_chest_pain_severe', 'q_weight_loss'] },
  ],

  questions: [
    // ── Characterization ──
    {
      id: 'q_type',
      text: 'What type of cough is it?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'What kind of cough does the child have?' },
      ],
      type: 'chips',
      chips: ['Dry / hacking', 'Productive / wet', 'Barking / croupy', 'Paroxysmal / in fits', 'Whooping', 'Honking'],
      required: true,
      importance: 2,
      reasoningWeight: 25,
      factKey: 'cough_type',
      documentationPhrase: 'Cough is {value} in type',
    },
    {
      id: 'q_timing',
      text: 'When does the cough occur?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'When does the cough happen?' },
      ],
      type: 'chips',
      chips: ['Throughout the day', 'Only at night', 'Early morning', 'After meals', 'With activity / exercise', 'Continuous'],
      required: true,
      importance: 1,
      reasoningWeight: 15,
      factKey: 'cough_timing',
      documentationPhrase: 'Cough occurs {value}',
    },
    {
      id: 'q_dry_vs_wet',
      text: 'Does the cough bring up any phlegm or mucus?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child cough up phlegm?' },
      ],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'cough_productive',
      documentationPhrase: 'Cough is {value}',
    },

    // ── Timeline ──
    {
      id: 'q_onset',
      text: 'When did the cough start?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'When did the cough start?' },
      ],
      type: 'chips',
      chips: ['Hours ago', '1-3 days ago', '4-7 days ago', '1-2 weeks ago', '2-4 weeks ago', 'More than 4 weeks ago'],
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'cough_onset',
      documentationPhrase: 'Cough started {value} ago',
    },
    {
      id: 'q_duration',
      text: 'How long has the cough lasted?',
      alternatives: [],
      type: 'chips',
      chips: ['Less than 3 weeks (acute)', '3-8 weeks (subacute)', 'More than 8 weeks (chronic)'],
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'cough_duration',
      documentationPhrase: 'Cough duration: {value}',
    },
    {
      id: 'q_progression',
      text: 'Is the cough getting better, worse, or staying the same?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Is the cough getting better or worse?' },
      ],
      type: 'chips',
      chips: ['Getting better', 'Getting worse', 'Staying the same', 'Comes and goes'],
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'cough_progression',
      documentationPhrase: 'Cough is {value}',
    },

    // ── Severity ──
    {
      id: 'q_severity',
      text: 'How severe is the cough? Does it interfere with breathing, eating, or sleeping?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the cough stop the child from eating, sleeping, or playing?' },
      ],
      type: 'chips',
      chips: ['Mild — barely noticeable', 'Moderate — interferes with daily life', 'Severe — cannot eat/sleep/speak', 'Debilitating — causes vomiting or exhaustion'],
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'cough_severity',
      documentationPhrase: 'Cough severity: {value}',
    },
    {
      id: 'q_sleep_disturbance',
      text: 'Does the cough wake you up at night?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the cough wake the child at night?' },
      ],
      type: 'boolean',
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'cough_sleep_disturbance',
      documentationPhrase: 'Cough disturbs sleep',
    },

    // ── Sputum ──
    {
      id: 'q_sputum_color',
      text: 'What color is the phlegm?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'What color is the phlegm that comes up?' },
      ],
      type: 'chips',
      chips: ['Clear / white', 'Yellow', 'Green', 'Rust-colored', 'Blood-streaked', 'No phlegm'],
      required: false,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'cough_sputum_color',
      documentationPhrase: 'Sputum is {value}',
    },
    {
      id: 'q_sputum_volume',
      text: 'How much phlegm do you cough up?',
      alternatives: [],
      type: 'chips',
      chips: ['A little (teaspoon)', 'Moderate (tablespoon)', 'A lot (cupful)', 'No phlegm'],
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'cough_sputum_volume',
      documentationPhrase: 'Sputum volume: {value}',
    },
    {
      id: 'q_hemoptysis',
      text: 'Have you coughed up blood?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Has the child coughed up blood?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 50,
      factKey: 'cough_hemoptysis',
      documentationPhrase: 'Hemoptysis present',
    },

    // ── Associated Symptoms ──
    {
      id: 'q_fever',
      text: 'Do you have a fever?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child have a fever?' },
      ],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 25,
      factKey: 'cough_fever',
      documentationPhrase: 'Associated with fever',
    },
    {
      id: 'q_dyspnea',
      text: 'Do you feel short of breath?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child seem to breathe faster than normal?' },
      ],
      type: 'chips',
      chips: ['No dyspnea', 'With exertion only', 'At rest', 'Worse when lying flat'],
      required: true,
      importance: 3,
      reasoningWeight: 35,
      factKey: 'cough_dyspnea',
      documentationPhrase: 'Dyspnea: {value}',
    },
    {
      id: 'q_chest_pain',
      text: 'Any chest pain?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child complain of chest pain?' },
      ],
      type: 'boolean',
      required: false,
      importance: 1,
      reasoningWeight: 15,
      factKey: 'cough_chest_pain',
      documentationPhrase: 'Associated chest pain',
    },
    {
      id: 'q_wheeze',
      text: 'Any wheezing or whistling sound when breathing?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child make a whistling sound when breathing?' },
      ],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 25,
      factKey: 'cough_wheeze',
      documentationPhrase: 'Associated wheeze',
    },
    {
      id: 'q_nasal',
      text: 'Any runny or blocked nose?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child have a runny nose?' },
      ],
      type: 'boolean',
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'cough_nasal',
      documentationPhrase: 'Associated nasal congestion',
    },
    {
      id: 'q_hoarseness',
      text: 'Any hoarseness or loss of voice?',
      alternatives: [],
      type: 'boolean',
      required: false,
      importance: 1,
      reasoningWeight: 5,
      factKey: 'cough_hoarseness',
      documentationPhrase: 'Associated hoarseness',
    },

    // ── Exposure ──
    {
      id: 'q_sick_contact',
      text: 'Contact with anyone with similar symptoms?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Has anyone at home or school had similar cough?' },
      ],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'cough_sick_contact',
      documentationPhrase: 'Contact with similarly ill person',
    },
    {
      id: 'q_smoking',
      text: 'Do you smoke or live with a smoker?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does anyone smoke at home?' },
      ],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'cough_smoking',
      documentationPhrase: 'Smoking exposure',
    },
    {
      id: 'q_tb_contact',
      text: 'Contact with someone with TB or chronic cough?',
      alternatives: [],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 35,
      factKey: 'cough_tb_contact',
      documentationPhrase: 'TB contact identified',
    },
    {
      id: 'q_occupational',
      text: 'Exposure to dust, chemicals, or fumes at work?',
      alternatives: [],
      type: 'boolean',
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'cough_occupational',
      documentationPhrase: 'Occupational exposure',
    },

    // ── Previous Episodes ──
    {
      id: 'q_previous_episodes',
      text: 'Have you had similar cough episodes before?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Has the child had similar cough before?' },
      ],
      type: 'boolean',
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'cough_previous_episodes',
      documentationPhrase: 'Previous similar episodes',
    },
    {
      id: 'q_asthma_history',
      text: 'Do you have asthma or a history of wheezing?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child have asthma?' },
      ],
      type: 'boolean',
      required: false,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'cough_asthma_history',
      documentationPhrase: 'History of asthma',
    },
    {
      id: 'q_reflux',
      text: 'Do you have heartburn or acid reflux?',
      alternatives: [],
      type: 'boolean',
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'cough_reflux',
      documentationPhrase: 'Associated reflux',
    },

    // ── Pediatric ──
    {
      id: 'q_immunization',
      text: 'Are the child\'s immunizations up to date? (especially pertussis)',
      alternatives: [],
      type: 'boolean',
      required: false,
      importance: 2,
      reasoningWeight: 15,
      factKey: 'cough_immunization',
      documentationPhrase: 'Immunization status: {value}',
    },
    {
      id: 'q_feeding',
      text: 'How is the child feeding?',
      alternatives: [],
      type: 'chips',
      chips: ['Feeding well', 'Feeding poorly', 'Refusing feeds', 'Vomiting after feeds'],
      required: false,
      importance: 2,
      reasoningWeight: 15,
      factKey: 'cough_feeding',
      documentationPhrase: 'Feeding: {value}',
    },
    {
      id: 'q_stridor',
      text: 'Does the child make a noise when breathing IN? (stridor)',
      alternatives: [],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 40,
      factKey: 'cough_stridor',
      documentationPhrase: 'Associated with stridor',
    },
    {
      id: 'q_whoop',
      text: 'Does the cough end with a whooping sound or vomiting?',
      alternatives: [],
      type: 'boolean',
      required: false,
      importance: 2,
      reasoningWeight: 25,
      factKey: 'cough_whoop',
      documentationPhrase: 'Paroxysmal cough with whoop',
    },

    // ── Red Flags ──
    {
      id: 'q_dyspnea_rest',
      text: 'Are you short of breath at rest?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child struggle to breathe even when sitting still?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 45,
      factKey: 'cough_dyspnea_rest',
      documentationPhrase: 'Dyspnea at rest',
    },
    {
      id: 'q_cyanosis',
      text: 'Have your lips or fingers turned blue?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Have the child\'s lips or fingernails turned blue?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 50,
      factKey: 'cough_cyanosis',
      documentationPhrase: 'Cyanosis noted',
    },
    {
      id: 'q_chest_pain_severe',
      text: 'Severe chest pain or tightness?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child complain of severe chest pain?' },
      ],
      type: 'boolean',
      required: false,
      importance: 2,
      reasoningWeight: 25,
      factKey: 'cough_chest_pain_severe',
      documentationPhrase: 'Severe chest pain',
    },
    {
      id: 'q_weight_loss',
      text: 'Have you lost weight unintentionally?',
      alternatives: [],
      type: 'boolean',
      required: false,
      importance: 2,
      reasoningWeight: 25,
      factKey: 'cough_weight_loss',
      documentationPhrase: 'Unintentional weight loss',
    },
  ],

  contextAdapters: {
    pediatric: {
      label: 'Pediatric Cough Extension',
      additionalObjectives: [],
      additionalQuestions: [
        {
          id: 'q_ped_indrawing',
          text: 'Does the child have chest indrawing (chest sinking in)?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 40,
          factKey: 'cough_ped_indrawing',
          documentationPhrase: 'Chest indrawing present',
        },
        {
          id: 'q_ped_nasal_flaring',
          text: 'Does the child have nostril flaring when breathing?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 35,
          factKey: 'cough_ped_nasal_flaring',
          documentationPhrase: 'Nasal flaring present',
        },
        {
          id: 'q_ped_head_nodding',
          text: 'Does the child\'s head move up and down with each breath?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 40,
          factKey: 'cough_ped_head_nodding',
          documentationPhrase: 'Head nodding with respiration',
        },
      ],
      suppressedQuestionIds: ['q_smoking', 'q_occupational', 'q_reflux'],
      modifiedQuestions: [
        { id: 'q_severity', text: 'How severe is the cough? Does it interfere with feeding or play?' },
      ],
    },
    neonatal: {
      label: 'Neonatal Cough Extension',
      additionalObjectives: [],
      additionalQuestions: [
        {
          id: 'q_neonatal_apnea',
          text: 'Does the baby stop breathing for periods?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 50,
          factKey: 'cough_neonatal_apnea',
          documentationPhrase: 'Apneic episodes',
        },
        {
          id: 'q_neonatal_grunting',
          text: 'Does the baby grunt when breathing out?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 40,
          factKey: 'cough_neonatal_grunting',
          documentationPhrase: 'Expiratory grunting',
        },
      ],
      suppressedQuestionIds: ['q_smoking', 'q_occupational', 'q_reflux', 'q_asthma_history', 'q_whoop'],
      modifiedQuestions: [
        { id: 'q_type', text: 'What does the baby\'s cough sound like?' },
        { id: 'q_feeding', text: 'How is the baby feeding?' },
      ],
    },
  },

  factExtraction: [
    { questionId: 'q_type', extract: (a) => [{ key: 'cough_type', value: String(a), type: 'reported', questionId: 'q_type', documentationPhrase: 'Cough is ' + a }] },
    { questionId: 'q_severity', extract: (a) => [{ key: 'cough_severity', value: String(a), type: 'reported', questionId: 'q_severity', documentationPhrase: 'Severity: ' + a }] },
    { questionId: 'q_productive', extract: (a) => [{ key: 'cough_productive', value: a ? true : false, type: 'reported', questionId: 'q_productive', documentationPhrase: a ? 'Productive cough' : 'Dry cough' }] },
    { questionId: 'q_sputum_color', extract: (a) => [{ key: 'cough_sputum_color', value: String(a), type: 'reported', questionId: 'q_sputum_color', documentationPhrase: 'Sputum: ' + a }] },
    { questionId: 'q_hemoptysis', extract: (a) => a ? [{ key: 'cough_hemoptysis', value: true, type: 'reported', questionId: 'q_hemoptysis', documentationPhrase: 'Hemoptysis present' }] : [] },
    { questionId: 'q_fever', extract: (a) => a ? [{ key: 'cough_fever', value: true, type: 'reported', questionId: 'q_fever', documentationPhrase: 'Associated with fever' }] : [] },
    { questionId: 'q_dyspnea', extract: (a) => [{ key: 'cough_dyspnea', value: String(a), type: 'reported', questionId: 'q_dyspnea', documentationPhrase: 'Dyspnea: ' + a }] },
    { questionId: 'q_wheeze', extract: (a) => a ? [{ key: 'cough_wheeze', value: true, type: 'reported', questionId: 'q_wheeze', documentationPhrase: 'Associated wheeze' }] : [] },
    { questionId: 'q_stridor', extract: (a) => a ? [{ key: 'cough_stridor', value: true, type: 'reported', questionId: 'q_stridor', documentationPhrase: 'Associated with stridor' }] : [] },
    { questionId: 'q_whoop', extract: (a) => a ? [{ key: 'cough_whoop', value: true, type: 'reported', questionId: 'q_whoop', documentationPhrase: 'Paroxysmal cough with whoop' }] : [] },
    { questionId: 'q_cyanosis', extract: (a) => a ? [{ key: 'cough_cyanosis', value: true, type: 'reported', questionId: 'q_cyanosis', documentationPhrase: 'Cyanosis noted' }] : [] },
    { questionId: 'q_tb_contact', extract: (a) => a ? [{ key: 'cough_tb_contact', value: true, type: 'reported', questionId: 'q_tb_contact', documentationPhrase: 'TB contact identified' }] : [] },
    { questionId: 'q_sick_contact', extract: (a) => a ? [{ key: 'cough_sick_contact', value: true, type: 'reported', questionId: 'q_sick_contact', documentationPhrase: 'Contact with similarly ill person' }] : [] },
    { questionId: 'q_duration', extract: (a) => [{ key: 'cough_duration', value: String(a), type: 'reported', questionId: 'q_duration', documentationPhrase: 'Duration: ' + a }] },
    { questionId: 'q_onset', extract: (a) => [{ key: 'cough_onset', value: String(a), type: 'reported', questionId: 'q_onset', documentationPhrase: 'Started ' + a + ' ago' }] },
  ],

  relationships: [
    { targetSymptomId: 'SX000001', type: 'associated_with', strength: 0.8, description: 'Commonly associated with fever' },
    { targetSymptomId: 'SX000002', type: 'associated_with', strength: 0.3, description: 'May be associated with headache' },
    { targetSymptomId: 'SX000004', type: 'associated_with', strength: 0.3, description: 'May be associated with vomiting' },
  ],

  phenotypes: [
    {
      id: 'phen_cough_upper_respiratory',
      label: 'Upper Respiratory Infection Phenotype',
      description: 'Acute cough with nasal congestion, fever, sore throat',
      criteria: [
        { factKey: 'cough_type', operator: 'contains', value: 'Dry' },
        { factKey: 'cough_duration', operator: 'contains', value: 'acute' },
      ],
      probability: 0.5,
      suggestsMechanisms: ['viral_mucosal_inflammation', 'upper_airway_irritation'],
      suggestsDifferentials: ['Common cold', 'Acute pharyngitis', 'Viral upper respiratory infection'],
      emergencyWeight: 15,
    },
    {
      id: 'phen_cough_lower_respiratory',
      label: 'Lower Respiratory Infection Phenotype',
      description: 'Productive cough with fever, dyspnea, chest pain, sputum',
      criteria: [
        { factKey: 'cough_productive', operator: 'eq', value: true },
        { factKey: 'cough_fever', operator: 'eq', value: true },
      ],
      probability: 0.5,
      suggestsMechanisms: ['alveolar_inflammation', 'parenchymal_consolidation', 'bronchial_mucosal_infection'],
      suggestsDifferentials: ['Pneumonia', 'Bronchitis', 'Bronchiectasis'],
      emergencyWeight: 60,
    },
    {
      id: 'phen_cough_asthma',
      label: 'Asthma Phenotype',
      description: 'Recurrent cough with wheeze, worse at night/early morning, with triggers',
      criteria: [
        { factKey: 'cough_wheeze', operator: 'eq', value: true },
        { factKey: 'cough_timing', operator: 'contains', value: 'night' },
      ],
      probability: 0.5,
      suggestsMechanisms: ['bronchial_hyperresponsiveness', 'airway_inflammation', 'smooth_muscle_constriction'],
      suggestsDifferentials: ['Asthma', 'Cough variant asthma'],
      emergencyWeight: 40,
    },
    {
      id: 'phen_cough_pertussis',
      label: 'Pertussis Phenotype',
      description: 'Paroxysmal cough with whoop, post-tussive vomiting, no fever',
      criteria: [
        { factKey: 'cough_whoop', operator: 'eq', value: true },
      ],
      probability: 0.6,
      suggestsMechanisms: ['bordetella_infection', 'respiratory_mucosal_inflammation'],
      suggestsDifferentials: ['Pertussis (whooping cough)', 'Parainfluenza infection'],
      emergencyWeight: 40,
    },
    {
      id: 'phen_cough_tb',
      label: 'Tuberculosis Phenotype',
      description: 'Chronic cough with weight loss, night sweats, hemoptysis, TB contact',
      criteria: [
        { factKey: 'cough_duration', operator: 'contains', value: 'chronic' },
        { factKey: 'cough_tb_contact', operator: 'eq', value: true },
      ],
      probability: 0.5,
      suggestsMechanisms: ['mycobacterial_infection', 'granulomatous_inflammation', 'parenchymal_destruction'],
      suggestsDifferentials: ['Pulmonary tuberculosis', 'Extrapulmonary tuberculosis'],
      emergencyWeight: 70,
    },
    {
      id: 'phen_cough_croup',
      label: 'Croup Phenotype',
      description: 'Barking cough with stridor, worse at night, in young children',
      criteria: [
        { factKey: 'cough_type', operator: 'contains', value: 'Barking' },
        { factKey: 'cough_stridor', operator: 'eq', value: true },
      ],
      probability: 0.6,
      suggestsMechanisms: ['laryngeal_inflammation', 'airway_edema'],
      suggestsDifferentials: ['Croup (laryngotracheobronchitis)', 'Epiglottitis', 'Bacterial tracheitis'],
      emergencyWeight: 70,
    },
  ],

  documentation: [
    { id: 'doc_type', condition: { factKey: 'cough_type', operator: 'present' }, template: 'Cough is {{cough_type}} in nature.', priority: 1 },
    { id: 'doc_duration', condition: { factKey: 'cough_duration', operator: 'present' }, template: 'Cough duration: {{cough_duration}}.', priority: 1 },
    { id: 'doc_productive', condition: { factKey: 'cough_productive', operator: 'eq', value: true }, template: 'Cough is productive.', priority: 1 },
    { id: 'doc_sputum', condition: { factKey: 'cough_sputum_color', operator: 'present' }, template: 'Sputum is {{cough_sputum_color}} in color.', priority: 2 },
    { id: 'doc_hemoptysis', condition: { factKey: 'cough_hemoptysis', operator: 'eq', value: true }, template: 'HEMOPTYSIS PRESENT.', priority: 1 },
    { id: 'doc_fever', condition: { factKey: 'cough_fever', operator: 'eq', value: true }, template: 'Associated with fever.', priority: 2 },
    { id: 'doc_dyspnea', condition: { factKey: 'cough_dyspnea', operator: 'present' }, template: 'Dyspnea: {{cough_dyspnea}}.', priority: 1 },
    { id: 'doc_wheeze', condition: { factKey: 'cough_wheeze', operator: 'eq', value: true }, template: 'Associated wheeze.', priority: 2 },
    { id: 'doc_stridor', condition: { factKey: 'cough_stridor', operator: 'eq', value: true }, template: 'STRIDOR PRESENT.', priority: 1 },
    { id: 'doc_whoop', condition: { factKey: 'cough_whoop', operator: 'eq', value: true }, template: 'Paroxysmal cough with whoop.', priority: 2 },
    { id: 'doc_cyanosis', condition: { factKey: 'cough_cyanosis', operator: 'eq', value: true }, template: 'CYANOSIS PRESENT.', priority: 1 },
    { id: 'doc_tb_contact', condition: { factKey: 'cough_tb_contact', operator: 'eq', value: true }, template: 'TB contact identified.', priority: 2 },
    { id: 'doc_indrawing', condition: { factKey: 'cough_ped_indrawing', operator: 'eq', value: true }, template: 'Chest indrawing present.', priority: 1 },
  ],

  reasoningHooks: [
    {
      id: 'rh_hemoptysis',
      trigger: { on: 'fact_captured', ref: 'cough_hemoptysis' },
      action: 'flag_red_flag',
      payload: ['Hemoptysis — investigate for TB, bronchiectasis, or malignancy'],
    },
    {
      id: 'rh_cyanosis',
      trigger: { on: 'fact_captured', ref: 'cough_cyanosis' },
      action: 'flag_red_flag',
      payload: ['Cyanosis with cough — severe respiratory compromise requiring urgent oxygen therapy'],
    },
    {
      id: 'rh_stridor',
      trigger: { on: 'fact_captured', ref: 'cough_stridor' },
      action: 'flag_red_flag',
      payload: ['Stridor with cough — assess for upper airway obstruction (croup, epiglottitis)'],
    },
    {
      id: 'rh_dyspnea_rest',
      trigger: { on: 'fact_captured', ref: 'cough_dyspnea_rest' },
      action: 'flag_red_flag',
      payload: ['Dyspnea at rest with cough — severe respiratory distress'],
    },
    {
      id: 'rh_severe_cough',
      trigger: { on: 'fact_captured', ref: 'cough_severity' },
      action: 'suggest_investigations',
      payload: ['Chest X-ray', 'Full blood count', 'CRP'],
    },
    {
      id: 'rh_tb_suspicion',
      trigger: { on: 'fact_captured', ref: 'cough_tb_contact' },
      action: 'suggest_investigations',
      payload: ['Chest X-ray', 'GeneXpert', 'Sputum AFB', 'TST/IGRA'],
    },
  ],

  completion: {
    objectives: [
      { objectiveId: 'obj_char', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_timeline', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_severity', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_sputum', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_associated', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_exposure', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_previous', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_pediatric', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_red_flags', status: 'not_started', answeredQuestions: [], percentage: 0 },
    ],
    overall: 0,
  },
};
