// ═══════════════════════════════════════════════════════════════════════════════
// Headache Symptom Node — SX000002
// Sources: Hutchison Clinical Methods 25e, WHO Headache Disorders, ICHD-3
// Universal Core + Pediatric + Obstetric adapters
// ═══════════════════════════════════════════════════════════════════════════════

import type { SymptomNode } from '../symptom-types';

export const HEADACHE_NODE: SymptomNode = {
  identity: {
    id: 'SX000002',
    canonicalName: 'Headache',
    synonyms: ['Cephalalgia', 'Head pain', 'Cranial pain'],
    layTerms: ['Head pain', 'Pain in the head', 'Head hurting', 'Migraine'],
    translations: { sw: 'Maumivu ya kichwa', lu: 'Aoho wiye', mer: 'Mwiru kĩrĩma', kis: 'Erori kĩrĩma' },
    snomed: '25064002',
    icd10: 'R51',
    umls: 'C0018681',
    bodySystem: 'Nervous',
    primarySpecialty: 'Neurology',
    emergencyWeight: 3,
  },

  metadata: {
    version: '1.0.0',
    author: 'AMEXAN Clinical Constitution',
    evidenceLevel: 'consensus',
    lastUpdated: '2026-07-13',
    source: 'Hutchison Clinical Methods 25e, ICHD-3 Beta, WHO guidelines',
  },

  activation: {
    chiefComplaint: true,
    hpiMention: true,
    ros: true,
    referralLetter: true,
    voiceTranscription: true,
    keywords: ['headache', 'head pain', 'migraine', 'cephalalgia', 'head hurting', 'maumivu ya kichwa'],
  },

  timeline: {
    allowed: ['acute', 'subacute', 'chronic', 'recurrent', 'relapsing', 'unknown'],
    defaultCategory: 'acute',
  },

  objectives: [
    { id: 'obj_char', label: 'Characterization', description: 'Establish presence, site, and quality of head pain', order: 1, required: true, questionIds: ['q_site', 'q_quality', 'q_side'] },
    { id: 'obj_timeline', label: 'Timeline', description: 'Onset, duration, frequency, temporal pattern', order: 2, required: true, questionIds: ['q_onset', 'q_duration', 'q_frequency', 'q_progression'] },
    { id: 'obj_severity', label: 'Severity', description: 'Assess pain intensity and functional impact', order: 3, required: true, questionIds: ['q_severity', 'q_functional_impact'] },
    { id: 'obj_aggravating', label: 'Aggravating Factors', description: 'Identify triggers and relieving factors', order: 4, required: false, questionIds: ['q_aggravated_by', 'q_relieved_by', 'q_relationship_to_activity'] },
    { id: 'obj_associated', label: 'Associated Symptoms', description: 'Identify accompanying features', order: 5, required: true, questionIds: ['q_nausea', 'q_photophobia', 'q_phonophobia', 'q_visual', 'q_neck_pain', 'q_fever_associated', 'q_nasal'] },
    { id: 'obj_aura', label: 'Aura / Prodrome', description: 'Assess for preceding neurological symptoms', order: 6, required: false, questionIds: ['q_aura_visual', 'q_aura_sensory', 'q_prodrome'] },
    { id: 'obj_previous', label: 'Previous Episodes', description: 'History of similar headaches', order: 7, required: false, questionIds: ['q_previous_episodes', 'q_previous_diagnosis'] },
    { id: 'obj_triggers', label: 'Triggers', description: 'Identify precipitating factors', order: 8, required: false, questionIds: ['q_food_triggers', 'q_stress', 'q_sleep', 'q_hormonal'] },
    { id: 'obj_red_flags', label: 'Red Flag Screening', description: 'Exclude serious intracranial pathology', order: 9, required: true, questionIds: ['q_worst', 'q_neck_stiffness', 'q_rash', 'q_trauma', 'q_immunosuppressed', 'q_exertion'] },
    { id: 'obj_complications', label: 'Complications', description: 'Assess impact on daily life', order: 10, required: false, questionIds: ['q_work_impact', 'q_medication_use'] },
  ],

  questions: [
    // ── Characterization ──
    {
      id: 'q_site',
      text: 'Where is the pain located?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Where does it hurt? Can you point?' },
      ],
      type: 'chips',
      chips: ['Forehead / behind eyes', 'One side of head', 'Both sides', 'Back of head', 'Around eye', 'Whole head', 'Top of head'],
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'headache_site',
      documentationPhrase: 'Pain located in {value}',
    },
    {
      id: 'q_quality',
      text: 'How would you describe the pain?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'How does it feel?' },
      ],
      type: 'chips',
      chips: ['Throbbing / Pulsating', 'Pressing / Tightening', 'Sharp / Stabbing', 'Burning', 'Dull ache', 'Band-like pressure'],
      required: true,
      importance: 2,
      reasoningWeight: 25,
      factKey: 'headache_quality',
      documentationPhrase: 'Pain described as {value}',
    },
    {
      id: 'q_side',
      text: 'Is the pain on one side or both?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Is the pain on one side or everywhere?' },
      ],
      type: 'chips',
      chips: ['One side (unilateral)', 'Both sides (bilateral)', 'Alternating sides', 'Central / midline'],
      required: false,
      importance: 1,
      reasoningWeight: 15,
      factKey: 'headache_side',
      documentationPhrase: 'Pain is {value}',
    },

    // ── Timeline ──
    {
      id: 'q_onset',
      text: 'When did the headache start?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'When did the headache start?' },
      ],
      type: 'chips',
      chips: ['Minutes ago', 'Hours ago', 'Yesterday', 'Days ago', 'Weeks ago', 'Months ago', 'Ongoing for years'],
      required: true,
      importance: 3,
      reasoningWeight: 30,
      factKey: 'headache_onset',
      documentationPhrase: 'Headache started {value} ago',
    },
    {
      id: 'q_duration',
      text: 'How long does each headache episode last?',
      alternatives: [],
      type: 'chips',
      chips: ['Minutes to hours', '4-72 hours', 'Days', 'Constant / continuous'],
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'headache_duration',
      documentationPhrase: 'Episodes last {value}',
    },
    {
      id: 'q_frequency',
      text: 'How often do you get these headaches?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'How often does this happen?' },
      ],
      type: 'chips',
      chips: ['First time ever', 'Daily', 'Weekly', 'Monthly', 'A few times a year', 'Rarely'],
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'headache_frequency',
      documentationPhrase: 'Frequency: {value}',
    },
    {
      id: 'q_progression',
      text: 'How has the headache changed since it started?',
      alternatives: [],
      type: 'chips',
      chips: ['Getting worse', 'Staying the same', 'Getting better', 'Comes and goes'],
      required: false,
      importance: 1,
      reasoningWeight: 15,
      factKey: 'headache_progression',
      documentationPhrase: 'Headache is {value}',
    },

    // ── Severity ──
    {
      id: 'q_severity',
      text: 'How severe is the pain on a scale of 0-10?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'How bad is the pain? Does it stop them from playing?' },
      ],
      type: 'scale',
      required: true,
      importance: 2,
      reasoningWeight: 25,
      factKey: 'headache_severity',
      documentationPhrase: 'Pain severity {value}/10',
    },
    {
      id: 'q_functional_impact',
      text: 'Does the headache interfere with daily activities?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does it stop the child from eating, playing, or going to school?' },
      ],
      type: 'chips',
      chips: ['Unable to work / school', 'Reduced activity', 'Can function normally', 'Must lie down'],
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'headache_functional_impact',
      documentationPhrase: 'Functional impact: {value}',
    },

    // ── Aggravating Factors ──
    {
      id: 'q_aggravated_by',
      text: 'What makes the headache worse?',
      alternatives: [],
      type: 'chips',
      chips: ['Movement / activity', 'Light', 'Sound', 'Bending over', 'Coughing / sneezing', 'Straining', 'Nothing specific'],
      required: false,
      importance: 1,
      reasoningWeight: 15,
      factKey: 'headache_aggravated_by',
      documentationPhrase: 'Aggravated by {value}',
    },
    {
      id: 'q_relieved_by',
      text: 'What makes the headache better?',
      alternatives: [],
      type: 'chips',
      chips: ['Rest / sleep', 'Dark room', 'Pain medication', 'Cold compress', 'Eating', 'Nothing'],
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'headache_relieved_by',
      documentationPhrase: 'Relieved by {value}',
    },
    {
      id: 'q_relationship_to_activity',
      text: 'Is the headache related to specific activities?',
      alternatives: [],
      type: 'chips',
      chips: ['Screen time', 'Reading', 'Physical exertion', 'Stressful situations', 'Specific times of day', 'No relation'],
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'headache_activity_relation',
      documentationPhrase: 'Related to {value}',
    },

    // ── Associated Symptoms ──
    {
      id: 'q_nausea',
      text: 'Do you feel nauseous or have you vomited?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Has the child vomited or felt sick to the stomach?' },
      ],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'headache_nausea',
      documentationPhrase: 'Associated with nausea or vomiting',
    },
    {
      id: 'q_photophobia',
      text: 'Does light bother you during the headache?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does light bother the child?' },
      ],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 15,
      factKey: 'headache_photophobia',
      documentationPhrase: 'Associated with photophobia',
    },
    {
      id: 'q_phonophobia',
      text: 'Does sound bother you during the headache?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does noise bother the child?' },
      ],
      type: 'boolean',
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'headache_phonophobia',
      documentationPhrase: 'Associated with phonophobia',
    },
    {
      id: 'q_visual',
      text: 'Any changes in vision? (flashing lights, blind spots, blurring)',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Has the child seen things that aren\'t there, or had blurry vision?' },
      ],
      type: 'chips',
      chips: ['Flashing lights / zigzag lines', 'Blind spots', 'Blurred vision', 'Double vision', 'None'],
      required: true,
      importance: 3,
      reasoningWeight: 30,
      factKey: 'headache_visual',
      documentationPhrase: 'Visual changes: {value}',
    },
    {
      id: 'q_neck_pain',
      text: 'Do you have neck pain or stiffness?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child have a stiff neck? (difficulty touching chin to chest)' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 35,
      factKey: 'headache_neck_stiffness',
      documentationPhrase: 'Associated with neck stiffness',
    },
    {
      id: 'q_fever_associated',
      text: 'Do you have a fever or feel hot?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child have a fever?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 25,
      factKey: 'headache_fever',
      documentationPhrase: 'Associated with fever',
    },
    {
      id: 'q_nasal',
      text: 'Do you have nasal congestion or sinus pain?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child have a blocked nose or sinus pain?' },
      ],
      type: 'boolean',
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'headache_nasal',
      documentationPhrase: 'Associated with nasal congestion',
    },

    // ── Aura / Prodrome ──
    {
      id: 'q_aura_visual',
      text: 'Before the headache, do you see flashing lights or zigzag lines?',
      alternatives: [],
      type: 'boolean',
      required: false,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'headache_aura_visual',
      documentationPhrase: 'Preceded by visual aura',
    },
    {
      id: 'q_aura_sensory',
      text: 'Before the headache, do you have numbness, tingling, or difficulty speaking?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Before the headache, does the child seem confused or have trouble speaking?' },
      ],
      type: 'boolean',
      required: false,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'headache_aura_sensory',
      documentationPhrase: 'Preceded by sensory or speech aura',
    },
    {
      id: 'q_prodrome',
      text: 'Do you have any warning signs before the headache starts? (mood changes, food cravings, fatigue)',
      alternatives: [],
      type: 'chips',
      chips: ['Mood changes', 'Food cravings', 'Fatigue / yawning', 'Neck stiffness', 'No warning'],
      required: false,
      importance: 1,
      reasoningWeight: 5,
      factKey: 'headache_prodrome',
      documentationPhrase: 'Prodromal symptoms: {value}',
    },

    // ── Previous Episodes ──
    {
      id: 'q_previous_episodes',
      text: 'Have you had similar headaches before?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Has the child had similar episodes before?' },
      ],
      type: 'boolean',
      required: false,
      importance: 2,
      reasoningWeight: 15,
      factKey: 'headache_previous_episodes',
      documentationPhrase: 'Previous similar episodes',
    },
    {
      id: 'q_previous_diagnosis',
      text: 'Have you been diagnosed with a headache disorder before?',
      alternatives: [],
      type: 'chips',
      chips: ['Migraine', 'Tension headache', 'Cluster headache', 'Sinus headache', 'Post-traumatic', 'No prior diagnosis'],
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'headache_previous_diagnosis',
      documentationPhrase: 'Prior diagnosis: {value}',
    },

    // ── Triggers ──
    {
      id: 'q_food_triggers',
      text: 'Do certain foods trigger the headache?',
      alternatives: [],
      type: 'chips',
      chips: ['Cheese / aged foods', 'Chocolate', 'Caffeine', 'Alcohol', 'Processed meats', 'MSG', 'None identified'],
      required: false,
      importance: 1,
      reasoningWeight: 5,
      factKey: 'headache_food_triggers',
      documentationPhrase: 'Food triggers: {value}',
    },
    {
      id: 'q_stress',
      text: 'Is the headache related to stress or emotional changes?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Has the child been stressed or anxious recently?' },
      ],
      type: 'boolean',
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'headache_stress',
      documentationPhrase: 'Related to stress',
    },
    {
      id: 'q_sleep',
      text: 'How is your sleep? (quality, duration, changes)',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'How is the child sleeping?' },
      ],
      type: 'chips',
      chips: ['Poor sleep quality', 'Too little sleep', 'Too much sleep', 'Sleep unchanged', 'Wakes with headache'],
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'headache_sleep',
      documentationPhrase: 'Sleep: {value}',
    },
    {
      id: 'q_hormonal',
      text: 'Is the headache related to your menstrual cycle?',
      alternatives: [
        { condition: { sex: 'male' }, text: '', type: 'boolean' },
      ],
      type: 'boolean',
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'headache_hormonal',
      documentationPhrase: 'Related to menstrual cycle',
    },

    // ── Red Flag Screening ──
    {
      id: 'q_worst',
      text: 'Is this the worst headache of your life?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Is this the worst headache the child has ever had?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 50,
      factKey: 'headache_worst',
      documentationPhrase: 'Described as worst ever',
    },
    {
      id: 'q_rash',
      text: 'Do you have a rash?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child have a rash?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 40,
      factKey: 'headache_rash',
      documentationPhrase: 'Associated with rash',
    },
    {
      id: 'q_trauma',
      text: 'Have you had any recent head injury?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Has the child hit their head recently?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 35,
      factKey: 'headache_trauma',
      documentationPhrase: 'Recent head trauma',
    },
    {
      id: 'q_immunosuppressed',
      text: 'Do you have a weakened immune system? (HIV, cancer, steroids, chemotherapy)',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child have any condition that weakens immunity?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 30,
      factKey: 'headache_immunosuppressed',
      documentationPhrase: 'Immunocompromised host',
    },
    {
      id: 'q_exertion',
      text: 'Is the headache brought on by exertion, coughing, or sexual activity?',
      alternatives: [],
      type: 'boolean',
      required: false,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'headache_exertion',
      documentationPhrase: 'Exertion-related headache',
    },

    // ── Complications ──
    {
      id: 'q_work_impact',
      text: 'How many days have you missed from work/school due to headaches?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'How many school days has the child missed?' },
      ],
      type: 'text',
      required: false,
      importance: 1,
      reasoningWeight: 5,
      factKey: 'headache_missed_days',
      documentationPhrase: 'Missed {value} days',
    },
    {
      id: 'q_medication_use',
      text: 'How often do you take pain medication for headaches?',
      alternatives: [],
      type: 'chips',
      chips: ['Daily or almost daily', 'Weekly', 'Monthly', 'Rarely', 'Never'],
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'headache_medication_frequency',
      documentationPhrase: 'Medication use: {value}',
    },
  ],

  contextAdapters: {
    pediatric: {
      label: 'Pediatric Headache Extension',
      additionalObjectives: [],
      additionalQuestions: [
        {
          id: 'q_ped_school_performance',
          text: 'Has the headache affected school performance?',
          alternatives: [],
          type: 'boolean',
          required: false,
          importance: 2,
          reasoningWeight: 5,
          factKey: 'headache_ped_school',
          documentationPhrase: 'School performance affected',
        },
        {
          id: 'q_ped_behavior_change',
          text: 'Have you noticed any changes in behavior or mood?',
          alternatives: [],
          type: 'chips',
          chips: ['Irritability', 'Withdrawn', 'Clingy', 'No change'],
          required: false,
          importance: 2,
          reasoningWeight: 5,
          factKey: 'headache_ped_behavior',
          documentationPhrase: 'Behavior change: {value}',
        },
      ],
      suppressedQuestionIds: ['q_hormonal', 'q_alcohol'],
      modifiedQuestions: [
        { id: 'q_previous_diagnosis', text: 'Has a doctor ever said what type of headache this is?' },
      ],
    },
    obstetric: {
      label: 'Obstetric Headache Extension',
      additionalObjectives: [],
      additionalQuestions: [
        {
          id: 'q_ob_gestational_age',
          text: 'What is the gestational age?',
          alternatives: [],
          type: 'text',
          required: false,
          importance: 3,
          reasoningWeight: 25,
          factKey: 'headache_ob_ga',
          documentationPhrase: 'Gestational age: {value}',
        },
        {
          id: 'q_ob_blood_pressure',
          text: 'Has your blood pressure been high?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 40,
          factKey: 'headache_ob_hypertension',
          documentationPhrase: 'Associated with hypertension',
        },
        {
          id: 'q_ob_visual_disturbance',
          text: 'Any visual disturbances? (flashing lights, blurring, dots)',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 35,
          factKey: 'headache_ob_visual',
          documentationPhrase: 'Visual disturbance in pregnancy',
        },
        {
          id: 'q_ob_epigastric',
          text: 'Any pain in the upper abdomen?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 30,
          factKey: 'headache_ob_epigastric',
          documentationPhrase: 'Epigastric pain',
        },
      ],
      suppressedQuestionIds: [],
      modifiedQuestions: [
        { id: 'q_worst', text: 'Is this the worst headache you have ever had? (especially if pregnant)' },
      ],
    },
  },

  factExtraction: [
    { questionId: 'q_site', extract: (a) => [{ key: 'headache_site', value: String(a), type: 'reported', questionId: 'q_site', documentationPhrase: 'Pain located in ' + a }] },
    { questionId: 'q_quality', extract: (a) => [{ key: 'headache_quality', value: String(a), type: 'reported', questionId: 'q_quality', documentationPhrase: 'Pain described as ' + a }] },
    { questionId: 'q_severity', extract: (a) => [{ key: 'headache_severity', value: typeof a === 'number' ? a : Number(a) || 0, type: 'reported', questionId: 'q_severity', documentationPhrase: 'Severity ' + String(a) + '/10' }] },
    { questionId: 'q_worst', extract: (a) => a ? [{ key: 'headache_worst', value: true, type: 'reported', questionId: 'q_worst', documentationPhrase: 'Worst headache ever' }] : [] },
    { questionId: 'q_neck_stiffness', extract: (a) => a ? [{ key: 'headache_neck_stiffness', value: true, type: 'reported', questionId: 'q_neck_stiffness', documentationPhrase: 'Associated with neck stiffness' }] : [] },
    { questionId: 'q_fever_associated', extract: (a) => a ? [{ key: 'headache_fever', value: true, type: 'reported', questionId: 'q_fever_associated', documentationPhrase: 'Associated with fever' }] : [] },
    { questionId: 'q_nausea', extract: (a) => a ? [{ key: 'headache_nausea', value: true, type: 'reported', questionId: 'q_nausea', documentationPhrase: 'Associated with nausea/vomiting' }] : [] },
    { questionId: 'q_photophobia', extract: (a) => a ? [{ key: 'headache_photophobia', value: true, type: 'reported', questionId: 'q_photophobia', documentationPhrase: 'Associated with photophobia' }] : [] },
    { questionId: 'q_aura_visual', extract: (a) => a ? [{ key: 'headache_aura_visual', value: true, type: 'reported', questionId: 'q_aura_visual', documentationPhrase: 'Preceded by visual aura' }] : [] },
    { questionId: 'q_trauma', extract: (a) => a ? [{ key: 'headache_trauma', value: true, type: 'reported', questionId: 'q_trauma', documentationPhrase: 'Recent head trauma' }] : [] },
    { questionId: 'q_rash', extract: (a) => a ? [{ key: 'headache_rash', value: true, type: 'reported', questionId: 'q_rash', documentationPhrase: 'Associated with rash' }] : [] },
    { questionId: 'q_immunosuppressed', extract: (a) => a ? [{ key: 'headache_immunosuppressed', value: true, type: 'reported', questionId: 'q_immunosuppressed', documentationPhrase: 'Immunocompromised' }] : [] },
    { questionId: 'q_duration', extract: (a) => [{ key: 'headache_duration', value: String(a), type: 'reported', questionId: 'q_duration', documentationPhrase: 'Duration: ' + a }] },
    { questionId: 'q_frequency', extract: (a) => [{ key: 'headache_frequency', value: String(a), type: 'reported', questionId: 'q_frequency', documentationPhrase: 'Frequency: ' + a }] },
    { questionId: 'q_functional_impact', extract: (a) => [{ key: 'headache_functional_impact', value: String(a), type: 'reported', questionId: 'q_functional_impact', documentationPhrase: 'Functional impact: ' + a }] },
  ],

  relationships: [
    { targetSymptomId: 'SX000001', type: 'associated_with', strength: 0.8, description: 'Commonly associated with fever' },
    { targetSymptomId: 'SX000004', type: 'associated_with', strength: 0.4, description: 'May be associated with vomiting' },
    { targetSymptomId: 'SX000003', type: 'associated_with', strength: 0.5, description: 'May be accompanied by body aches' },
    { targetSymptomId: 'SX000005', type: 'associated_with', strength: 0.3, description: 'May be associated with cough' },
  ],

  phenotypes: [
    {
      id: 'phen_headache_migraine',
      label: 'Migraine Phenotype',
      description: 'Unilateral throbbing pain with nausea, photophobia, phonophobia, aura',
      criteria: [
        { factKey: 'headache_quality', operator: 'contains', value: 'Throbbing' },
        { factKey: 'headache_nausea', operator: 'eq', value: true },
      ],
      probability: 0.6,
      suggestsMechanisms: ['vascular_dysregulation', 'trigeminal_nerve_activation', 'cortical_spreading_depression'],
      suggestsDifferentials: ['Migraine with aura', 'Migraine without aura', 'Chronic migraine'],
      emergencyWeight: 20,
    },
    {
      id: 'phen_headache_tension',
      label: 'Tension-Type Headache Phenotype',
      description: 'Bilateral pressing/tightening pain, no nausea, no photophobia/phonophobia',
      criteria: [
        { factKey: 'headache_quality', operator: 'contains', value: 'Pressing' },
        { factKey: 'headache_side', operator: 'contains', value: 'both' },
      ],
      probability: 0.5,
      suggestsMechanisms: ['musculoskeletal_tension'],
      suggestsDifferentials: ['Tension-type headache', 'Chronic tension-type headache'],
      emergencyWeight: 10,
    },
    {
      id: 'phen_headache_cluster',
      label: 'Cluster Headache Phenotype',
      description: 'Unilateral severe pain around eye with autonomic features',
      criteria: [
        { factKey: 'headache_site', operator: 'contains', value: 'Around eye' },
        { factKey: 'headache_quality', operator: 'contains', value: 'Sharp' },
      ],
      probability: 0.4,
      suggestsMechanisms: ['trigeminal_autonomic_reflex', 'hypothalamic_activation'],
      suggestsDifferentials: ['Cluster headache', 'Trigeminal autonomic cephalalgia'],
      emergencyWeight: 15,
    },
    {
      id: 'phen_headache_cns_infection',
      label: 'CNS Infection Phenotype',
      description: 'Headache with neck stiffness, fever, rash, altered consciousness',
      criteria: [
        { factKey: 'headache_neck_stiffness', operator: 'eq', value: true },
        { factKey: 'headache_fever', operator: 'eq', value: true },
      ],
      probability: 0.6,
      suggestsMechanisms: ['meningeal_inflammation', 'intracranial_infection', 'elevated_intracranial_pressure'],
      suggestsDifferentials: ['Meningitis', 'Encephalitis', 'Cerebral abscess'],
      emergencyWeight: 90,
    },
    {
      id: 'phen_headache_hemorrhage',
      label: 'Subarachnoid Hemorrhage Phenotype',
      description: 'Sudden onset worst headache of life, with neck stiffness',
      criteria: [
        { factKey: 'headache_worst', operator: 'eq', value: true },
        { factKey: 'headache_neck_stiffness', operator: 'eq', value: true },
      ],
      probability: 0.5,
      suggestsMechanisms: ['subarachnoid_bleeding', 'aneurysmal_rupture', 'elevated_intracranial_pressure'],
      suggestsDifferentials: ['Subarachnoid hemorrhage', 'Intracranial hemorrhage'],
      emergencyWeight: 95,
    },
    {
      id: 'phen_headache_sinus',
      label: 'Sinus Headache Phenotype',
      description: 'Frontal headache with nasal congestion, worse on bending',
      criteria: [
        { factKey: 'headache_site', operator: 'contains', value: 'Forehead' },
        { factKey: 'headache_nasal', operator: 'eq', value: true },
      ],
      probability: 0.3,
      suggestsMechanisms: ['sinus_mucosal_inflammation'],
      suggestsDifferentials: ['Acute sinusitis', 'Allergic rhinitis'],
      emergencyWeight: 10,
    },
  ],

  documentation: [
    { id: 'doc_site', condition: { factKey: 'headache_site', operator: 'present' }, template: 'Headache located in {{headache_site}}.', priority: 1 },
    { id: 'doc_quality', condition: { factKey: 'headache_quality', operator: 'present' }, template: 'Pain is {{headache_quality}} in nature.', priority: 1 },
    { id: 'doc_severity', condition: { factKey: 'headache_severity', operator: 'present' }, template: 'Severity rated {{headache_severity}}/10.', priority: 1 },
    { id: 'doc_worst', condition: { factKey: 'headache_worst', operator: 'eq', value: true }, template: 'Described as the worst headache ever experienced — red flag for subarachnoid hemorrhage.', priority: 1 },
    { id: 'doc_neck_stiffness', condition: { factKey: 'headache_neck_stiffness', operator: 'eq', value: true }, template: 'NECK STIFFNESS PRESENT — urgent assessment for meningitis or subarachnoid hemorrhage.', priority: 1 },
    { id: 'doc_fever', condition: { factKey: 'headache_fever', operator: 'eq', value: true }, template: 'Fever present with headache — consider CNS infection.', priority: 1 },
    { id: 'doc_nausea', condition: { factKey: 'headache_nausea', operator: 'eq', value: true }, template: 'Associated nausea/vomiting.', priority: 2 },
    { id: 'doc_photophobia', condition: { factKey: 'headache_photophobia', operator: 'eq', value: true }, template: 'Associated photophobia.', priority: 2 },
    { id: 'doc_aura', condition: { factKey: 'headache_aura_visual', operator: 'eq', value: true }, template: 'Preceded by visual aura.', priority: 2 },
    { id: 'doc_trauma', condition: { factKey: 'headache_trauma', operator: 'eq', value: true }, template: 'Recent head trauma reported.', priority: 2 },
    { id: 'doc_rash', condition: { factKey: 'headache_rash', operator: 'eq', value: true }, template: 'RASH PRESENT with headache — high suspicion for meningococcemia.', priority: 1 },
    { id: 'doc_duration', condition: { factKey: 'headache_duration', operator: 'present' }, template: 'Episodes last {{headache_duration}}.', priority: 2 },
    { id: 'doc_frequency', condition: { factKey: 'headache_frequency', operator: 'present' }, template: 'Frequency: {{headache_frequency}}.', priority: 2 },
  ],

  reasoningHooks: [
    {
      id: 'rh_worst_headache',
      trigger: { on: 'fact_captured', ref: 'headache_worst' },
      action: 'flag_red_flag',
      payload: ['Sudden severe headache — exclude subarachnoid hemorrhage'],
    },
    {
      id: 'rh_neck_stiffness',
      trigger: { on: 'fact_captured', ref: 'headache_neck_stiffness' },
      action: 'flag_red_flag',
      payload: ['Neck stiffness with headache — urgent assessment for meningitis'],
    },
    {
      id: 'rh_fever_headache',
      trigger: { on: 'fact_captured', ref: 'headache_fever' },
      action: 'flag_red_flag',
      payload: ['Fever with headache — exclude CNS infection'],
    },
    {
      id: 'rh_migraine_criteria',
      trigger: { on: 'phenotype_matched', ref: 'phen_headache_migraine' },
      action: 'suggest_differentials',
      payload: ['dx_migraine'],
    },
    {
      id: 'rh_trauma',
      trigger: { on: 'fact_captured', ref: 'headache_trauma' },
      action: 'suggest_investigations',
      payload: ['CT head', 'Neurological observation'],
    },
    {
      id: 'rh_obstetric_hypertension',
      trigger: { on: 'fact_captured', ref: 'headache_ob_hypertension' },
      action: 'flag_red_flag',
      payload: ['Pregnant with headache and hypertension — rule out pre-eclampsia'],
    },
  ],

  completion: {
    objectives: [
      { objectiveId: 'obj_char', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_timeline', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_severity', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_aggravating', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_associated', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_aura', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_previous', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_triggers', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_red_flags', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_complications', status: 'not_started', answeredQuestions: [], percentage: 0 },
    ],
    overall: 0,
  },
};
