// ═══════════════════════════════════════════════════════════════════════════════
// Shortness of Breath Symptom Node — SX000008
// Sources: Hutchison Clinical Methods 25e, WHO IMCI, BTS/ATS Guidelines
// Universal Core + Pediatric + Neonatal + Obstetric + Emergency adapters
// ═══════════════════════════════════════════════════════════════════════════════

import type { SymptomNode } from '../symptom-types';

export const SHORTNESS_OF_BREATH_NODE: SymptomNode = {
  identity: {
    id: 'SX000008',
    canonicalName: 'Shortness of Breath',
    synonyms: ['Dyspnea', 'Breathlessness', 'Respiratory distress'],
    layTerms: ['Difficulty breathing', 'Can\'t breathe', 'Breathing hard', 'Out of breath'],
    translations: {},
    snomed: '267036007',
    icd10: 'R06.0',
    umls: 'C0013404',
    bodySystem: 'Respiratory',
    primarySpecialty: 'Pulmonology',
    emergencyWeight: 5,
  },

  metadata: {
    version: '1.0.0',
    author: 'AMEXAN Clinical Constitution',
    evidenceLevel: 'consensus',
    lastUpdated: '2026-07-13',
    source: 'Hutchison Clinical Methods 25e, WHO IMCI respiratory distress guidelines, BTS/ATS guidelines',
  },

  activation: {
    chiefComplaint: true,
    hpiMention: true,
    ros: true,
    referralLetter: true,
    voiceTranscription: true,
    keywords: ['shortness of breath', 'dyspnea', 'breathless', 'difficulty breathing', 'can\'t breathe', 'hard to breathe', 'out of breath', 'respiratory distress'],
  },

  timeline: {
    allowed: ['acute', 'subacute', 'chronic', 'recurrent', 'unknown'],
    defaultCategory: 'acute',
  },

  objectives: [
    { id: 'obj_char', label: 'Characterization', description: 'Establish nature and severity of dyspnea', order: 1, required: true, questionIds: ['q_onset', 'q_severity', 'q_position'] },
    { id: 'obj_timeline', label: 'Timeline', description: 'Onset, duration, progression, triggers', order: 2, required: true, questionIds: ['q_duration', 'q_triggers', 'q_exertion'] },
    { id: 'obj_severity', label: 'Severity', description: 'Assess respiratory effort and functional status', order: 3, required: true, questionIds: ['q_at_rest', 'q_mrc_scale'] },
    { id: 'obj_associated', label: 'Associated Symptoms', description: 'Identify accompanying respiratory and cardiovascular symptoms', order: 4, required: true, questionIds: ['q_cough', 'q_wheeze', 'q_chest_pain', 'q_fever', 'q_sputum', 'q_palpitations', 'q_leg_swelling'] },
    { id: 'obj_previous', label: 'Previous History', description: 'History of similar episodes or chronic conditions', order: 5, required: false, questionIds: ['q_previous_episodes', 'q_asthma_copd', 'q_smoking'] },
    { id: 'obj_pediatric', label: 'Pediatric Assessment', description: 'Respiratory distress signs in children', order: 6, required: false, questionIds: ['q_ped_indrawing', 'q_ped_grunt', 'q_ped_nasal_flare', 'q_ped_head_nod'] },
    { id: 'obj_red_flags', label: 'Red Flags', description: 'Identify life-threatening causes', order: 7, required: true, questionIds: ['q_cyanosis', 'q_orthopnea', 'q_pnd', 'q_stridor', 'q_silent_chest'] },
  ],

  questions: [
    // ── Characterization ──
    {
      id: 'q_onset',
      text: 'Did the shortness of breath come on suddenly or gradually?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Did the breathing problem start suddenly or slowly?' },
      ],
      type: 'chips',
      chips: ['Sudden — minutes to hours', 'Gradual — days', 'Gradual — weeks to months', 'Came and went several times'],
      required: true,
      importance: 2,
      reasoningWeight: 25,
      factKey: 'sob_onset_pattern',
      documentationPhrase: 'Dyspnea onset: {value}',
    },
    {
      id: 'q_severity',
      text: 'How severe is the shortness of breath?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'How much trouble does the child have breathing?' },
      ],
      type: 'chips',
      chips: ['Mild — only with heavy exertion', 'Moderate — with minimal activity', 'Severe — at rest', 'Critical — gasping for air'],
      required: true,
      importance: 2,
      reasoningWeight: 30,
      factKey: 'sob_severity',
      documentationPhrase: 'Dyspnea severity: {value}',
    },
    {
      id: 'q_position',
      text: 'Is your breathing affected by position?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child breathe better sitting up?' },
      ],
      type: 'chips',
      chips: ['No positional change', 'Worse when lying flat (orthopnea)', 'Better when sitting up', 'Wakes up gasping (PND)'],
      required: true,
      importance: 2,
      reasoningWeight: 30,
      factKey: 'sob_position',
      documentationPhrase: 'Positional dyspnea: {value}',
    },

    // ── Timeline ──
    {
      id: 'q_duration',
      text: 'How long have you been short of breath?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'How long has the child been breathing this way?' },
      ],
      type: 'chips',
      chips: ['Minutes to hours', '1-3 days', '4-7 days', '1-4 weeks', 'More than 4 weeks'],
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'sob_duration',
      documentationPhrase: 'Duration: {value}',
    },
    {
      id: 'q_triggers',
      text: 'What triggers the shortness of breath?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'What brings on the breathing problem?' },
      ],
      type: 'chips',
      chips: ['Exercise / exertion', 'Lying flat', 'Allergens / dust', 'Cold air', 'Infections / colds', 'Stress / anxiety', 'No specific trigger'],
      required: false,
      importance: 1,
      reasoningWeight: 15,
      factKey: 'sob_triggers',
      documentationPhrase: 'Triggers: {value}',
    },
    {
      id: 'q_exertion',
      text: 'How much activity brings on shortness of breath?',
      alternatives: [],
      type: 'chips',
      chips: ['Walking up slight incline', 'Walking on flat ground', 'Dressing / bathing', 'At rest', 'Minimal exertion'],
      required: true,
      importance: 2,
      reasoningWeight: 25,
      factKey: 'sob_exertion',
      documentationPhrase: 'Dyspnea on exertion: {value}',
    },

    // ── Severity ──
    {
      id: 'q_at_rest',
      text: 'Are you short of breath even at rest?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child struggle to breathe even when sitting still?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 45,
      factKey: 'sob_at_rest',
      documentationPhrase: 'Dyspnea at rest',
    },
    {
      id: 'q_mrc_scale',
      text: 'On the MRC scale, how would you rate your breathlessness?',
      alternatives: [],
      type: 'chips',
      chips: ['MRC 1 — only with strenuous exercise', 'MRC 2 — hurrying on level ground', 'MRC 3 — walking slower than peers', 'MRC 4 — stops after 100m', 'MRC 5 — too breathless to leave house'],
      required: false,
      importance: 1,
      reasoningWeight: 15,
      factKey: 'sob_mrc_scale',
      documentationPhrase: 'MRC dyspnea grade: {value}',
    },

    // ── Associated Symptoms ──
    {
      id: 'q_cough',
      text: 'Do you have a cough?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child have a cough?' },
      ],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'sob_cough',
      documentationPhrase: 'Associated cough',
    },
    {
      id: 'q_wheeze',
      text: 'Any wheezing or whistling sound when breathing?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child make a whistling sound when breathing?' },
      ],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 25,
      factKey: 'sob_wheeze',
      documentationPhrase: 'Associated wheeze',
    },
    {
      id: 'q_chest_pain',
      text: 'Any chest pain or tightness?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child complain of chest pain?' },
      ],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 25,
      factKey: 'sob_chest_pain',
      documentationPhrase: 'Associated chest pain',
    },
    {
      id: 'q_fever',
      text: 'Do you have a fever?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child have a fever?' },
      ],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'sob_fever',
      documentationPhrase: 'Associated with fever',
    },
    {
      id: 'q_sputum',
      text: 'Do you cough up any phlegm?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child cough up phlegm?' },
      ],
      type: 'chips',
      chips: ['No sputum', 'Clear / white', 'Yellow / green', 'Blood-stained', 'Frothy / pink'],
      required: false,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'sob_sputum',
      documentationPhrase: 'Sputum: {value}',
    },
    {
      id: 'q_palpitations',
      text: 'Do you feel any palpitations or pounding heart?',
      alternatives: [],
      type: 'boolean',
      required: false,
      importance: 1,
      reasoningWeight: 15,
      factKey: 'sob_palpitations',
      documentationPhrase: 'Associated palpitations',
    },
    {
      id: 'q_leg_swelling',
      text: 'Do you have any swelling in your legs or ankles?',
      alternatives: [],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 25,
      factKey: 'sob_leg_swelling',
      documentationPhrase: 'Leg swelling / pedal edema',
    },

    // ── Previous History ──
    {
      id: 'q_previous_episodes',
      text: 'Have you had similar episodes of shortness of breath before?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Has the child had breathing trouble before?' },
      ],
      type: 'boolean',
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'sob_previous_episodes',
      documentationPhrase: 'Previous similar episodes',
    },
    {
      id: 'q_asthma_copd',
      text: 'Do you have asthma, COPD, or any chronic lung condition?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child have asthma or other lung problems?' },
      ],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 25,
      factKey: 'sob_asthma_copd',
      documentationPhrase: 'History of lung disease: {value}',
    },
    {
      id: 'q_smoking',
      text: 'Do you smoke or have you ever smoked?',
      alternatives: [],
      type: 'boolean',
      required: false,
      importance: 1,
      reasoningWeight: 15,
      factKey: 'sob_smoking',
      documentationPhrase: 'Smoking history',
    },

    // ── Pediatric ──
    {
      id: 'q_ped_indrawing',
      text: 'Does the child have chest indrawing (chest sinking in)?',
      alternatives: [],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 40,
      factKey: 'sob_ped_indrawing',
      documentationPhrase: 'Chest indrawing present',
    },
    {
      id: 'q_ped_grunt',
      text: 'Does the child grunt when breathing out?',
      alternatives: [],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 40,
      factKey: 'sob_ped_grunt',
      documentationPhrase: 'Expiratory grunting',
    },
    {
      id: 'q_ped_nasal_flare',
      text: 'Does the child have nostril flaring when breathing?',
      alternatives: [],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 35,
      factKey: 'sob_ped_nasal_flare',
      documentationPhrase: 'Nasal flaring present',
    },
    {
      id: 'q_ped_head_nod',
      text: 'Does the child\'s head move up and down with each breath?',
      alternatives: [],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 40,
      factKey: 'sob_ped_head_nod',
      documentationPhrase: 'Head nodding with respiration',
    },

    // ── Red Flags ──
    {
      id: 'q_cyanosis',
      text: 'Have your lips or fingers turned blue?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Have the child\'s lips or fingernails turned blue?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 50,
      factKey: 'sob_cyanosis',
      documentationPhrase: 'CYANOSIS PRESENT',
    },
    {
      id: 'q_orthopnea',
      text: 'Do you need to sleep sitting up with multiple pillows?',
      alternatives: [],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 35,
      factKey: 'sob_orthopnea',
      documentationPhrase: 'Orthopnea requiring pillows',
    },
    {
      id: 'q_pnd',
      text: 'Do you wake up at night gasping for air?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child wake up unable to breathe?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 40,
      factKey: 'sob_pnd',
      documentationPhrase: 'Paroxysmal nocturnal dyspnea',
    },
    {
      id: 'q_stridor',
      text: 'Is there a harsh noise when breathing IN? (stridor)',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child make a noise when breathing in?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 45,
      factKey: 'sob_stridor',
      documentationPhrase: 'Stridor present',
    },
    {
      id: 'q_silent_chest',
      text: 'Is the chest silent — no breath sounds at all?',
      alternatives: [],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 50,
      factKey: 'sob_silent_chest',
      documentationPhrase: 'SILENT CHEST — critical airway obstruction',
    },
  ],

  contextAdapters: {
    pediatric: {
      label: 'Pediatric Respiratory Distress Extension',
      additionalObjectives: [],
      additionalQuestions: [
        {
          id: 'q_ped_central_cyanosis',
          text: 'Is the child\'s tongue or mouth blue?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 50,
          factKey: 'sob_ped_central_cyanosis',
          documentationPhrase: 'Central cyanosis present',
        },
        {
          id: 'q_ped_trach tug',
          text: 'Does the child have tracheal tug?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 35,
          factKey: 'sob_ped_tracheal_tug',
          documentationPhrase: 'Tracheal tug present',
        },
      ],
      suppressedQuestionIds: ['q_smoking', 'q_mrc_scale', 'q_asthma_copd'],
      modifiedQuestions: [
        { id: 'q_severity', text: 'How severe is the breathing difficulty? Does it interfere with feeding or play?' },
      ],
    },
    neonatal: {
      label: 'Neonatal Respiratory Distress Extension',
      additionalObjectives: [],
      additionalQuestions: [
        {
          id: 'q_neonatal_apnea',
          text: 'Does the baby have episodes of not breathing (apnea)?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 50,
          factKey: 'sob_neonatal_apnea',
          documentationPhrase: 'Apneic episodes',
        },
        {
          id: 'q_neonatal_prematurity',
          text: 'Was the baby born prematurely?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 2,
          reasoningWeight: 25,
          factKey: 'sob_neonatal_prematurity',
          documentationPhrase: 'Prematurity',
        },
      ],
      suppressedQuestionIds: ['q_smoking', 'q_mrc_scale', 'q_asthma_copd', 'q_previous_episodes'],
      modifiedQuestions: [
        { id: 'q_onset', text: 'Did the breathing problem start immediately after birth?' },
      ],
    },
    obstetric: {
      label: 'Obstetric Dyspnea Extension',
      additionalObjectives: [],
      additionalQuestions: [
        {
          id: 'q_obs_gestational_age',
          text: 'What is the gestational age?',
          alternatives: [],
          type: 'chips',
          chips: ['First trimester', 'Second trimester', 'Third trimester', 'Postpartum'],
          required: true,
          importance: 1,
          reasoningWeight: 10,
          factKey: 'sob_obs_gestational',
          documentationPhrase: 'Gestational age: {value}',
        },
        {
          id: 'q_obs_leg_pain',
          text: 'Do you have any calf pain or swelling?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 40,
          factKey: 'sob_obs_leg_pain',
          documentationPhrase: 'Calf pain/swelling present',
        },
      ],
      suppressedQuestionIds: [],
      modifiedQuestions: [
        { id: 'q_position', text: 'Does lying flat make the breathlessness worse? (common in late pregnancy)' },
      ],
    },
    emergency: {
      label: 'Emergency Dyspnea Extension',
      additionalObjectives: [],
      additionalQuestions: [
        {
          id: 'q_emerg_airway',
          text: 'Is the patient able to speak in full sentences?',
          alternatives: [],
          type: 'chips',
          chips: ['Full sentences', 'Short phrases only', 'Single words', 'Unable to speak'],
          required: true,
          importance: 3,
          reasoningWeight: 45,
          factKey: 'sob_emerg_sentences',
          documentationPhrase: 'Speech: {value}',
        },
        {
          id: 'q_emerg_accessory',
          text: 'Is the patient using accessory muscles (neck, shoulder) to breathe?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 40,
          factKey: 'sob_emerg_accessory',
          documentationPhrase: 'Accessory muscle use',
        },
      ],
      suppressedQuestionIds: ['q_mrc_scale', 'q_asthma_copd'],
      modifiedQuestions: [
        { id: 'q_severity', text: 'Assess severity: Can the patient speak? Are accessory muscles being used?' },
      ],
    },
  },

  factExtraction: [
    { questionId: 'q_onset', extract: (a) => [{ key: 'sob_onset_pattern', value: String(a), type: 'reported', questionId: 'q_onset', documentationPhrase: 'Dyspnea onset: ' + a }] },
    { questionId: 'q_severity', extract: (a) => [{ key: 'sob_severity', value: String(a), type: 'reported', questionId: 'q_severity', documentationPhrase: 'Dyspnea severity: ' + a }] },
    { questionId: 'q_position', extract: (a) => [{ key: 'sob_position', value: String(a), type: 'reported', questionId: 'q_position', documentationPhrase: 'Positional dyspnea: ' + a }] },
    { questionId: 'q_duration', extract: (a) => [{ key: 'sob_duration', value: String(a), type: 'reported', questionId: 'q_duration', documentationPhrase: 'Duration: ' + a }] },
    { questionId: 'q_exertion', extract: (a) => [{ key: 'sob_exertion', value: String(a), type: 'reported', questionId: 'q_exertion', documentationPhrase: 'Dyspnea on exertion: ' + a }] },
    { questionId: 'q_at_rest', extract: (a) => a ? [{ key: 'sob_at_rest', value: true, type: 'reported', questionId: 'q_at_rest', documentationPhrase: 'Dyspnea at rest' }] : [] },
    { questionId: 'q_cough', extract: (a) => a ? [{ key: 'sob_cough', value: true, type: 'reported', questionId: 'q_cough', documentationPhrase: 'Associated cough' }] : [] },
    { questionId: 'q_wheeze', extract: (a) => a ? [{ key: 'sob_wheeze', value: true, type: 'reported', questionId: 'q_wheeze', documentationPhrase: 'Associated wheeze' }] : [] },
    { questionId: 'q_chest_pain', extract: (a) => a ? [{ key: 'sob_chest_pain', value: true, type: 'reported', questionId: 'q_chest_pain', documentationPhrase: 'Associated chest pain' }] : [] },
    { questionId: 'q_fever', extract: (a) => a ? [{ key: 'sob_fever', value: true, type: 'reported', questionId: 'q_fever', documentationPhrase: 'Associated with fever' }] : [] },
    { questionId: 'q_leg_swelling', extract: (a) => a ? [{ key: 'sob_leg_swelling', value: true, type: 'reported', questionId: 'q_leg_swelling', documentationPhrase: 'Leg swelling present' }] : [] },
    { questionId: 'q_sputum', extract: (a) => [{ key: 'sob_sputum', value: String(a), type: 'reported', questionId: 'q_sputum', documentationPhrase: 'Sputum: ' + a }] },
    { questionId: 'q_cyanosis', extract: (a) => a ? [{ key: 'sob_cyanosis', value: true, type: 'reported', questionId: 'q_cyanosis', documentationPhrase: 'CYANOSIS PRESENT' }] : [] },
    { questionId: 'q_orthopnea', extract: (a) => a ? [{ key: 'sob_orthopnea', value: true, type: 'reported', questionId: 'q_orthopnea', documentationPhrase: 'Orthopnea requiring pillows' }] : [] },
    { questionId: 'q_pnd', extract: (a) => a ? [{ key: 'sob_pnd', value: true, type: 'reported', questionId: 'q_pnd', documentationPhrase: 'Paroxysmal nocturnal dyspnea' }] : [] },
    { questionId: 'q_stridor', extract: (a) => a ? [{ key: 'sob_stridor', value: true, type: 'reported', questionId: 'q_stridor', documentationPhrase: 'Stridor present' }] : [] },
    { questionId: 'q_silent_chest', extract: (a) => a ? [{ key: 'sob_silent_chest', value: true, type: 'reported', questionId: 'q_silent_chest', documentationPhrase: 'SILENT CHEST' }] : [] },
    { questionId: 'q_asthma_copd', extract: (a) => [{ key: 'sob_asthma_copd', value: a ? true : false, type: 'reported', questionId: 'q_asthma_copd', documentationPhrase: a ? 'History of lung disease' : 'No history of lung disease' }] },
    { questionId: 'q_previous_episodes', extract: (a) => a ? [{ key: 'sob_previous_episodes', value: true, type: 'reported', questionId: 'q_previous_episodes', documentationPhrase: 'Previous similar episodes' }] : [] },
  ],

  relationships: [
    { targetSymptomId: 'SX000001', type: 'associated_with', strength: 0.5, description: 'May be associated with fever (pneumonia, sepsis)' },
    { targetSymptomId: 'SX000005', type: 'associated_with', strength: 0.7, description: 'Commonly associated with cough' },
    { targetSymptomId: 'SX000003', type: 'associated_with', strength: 0.2, description: 'May be associated with body aches' },
    { targetSymptomId: 'SX000007', type: 'associated_with', strength: 0.1, description: 'Rarely associated with referred abdominal pain' },
  ],

  phenotypes: [
    {
      id: 'phen_sob_asthma',
      label: 'Acute Asthma Exacerbation Phenotype',
      description: 'Acute dyspnea with wheeze, cough, chest tightness, triggered by allergens/infection',
      criteria: [
        { factKey: 'sob_wheeze', operator: 'eq', value: true },
        { factKey: 'sob_onset_pattern', operator: 'contains', value: 'Sudden' },
      ],
      probability: 0.5,
      suggestsMechanisms: ['smooth_muscle_constriction', 'airway_inflammation', 'mucous_plugging'],
      suggestsDifferentials: ['Acute asthma exacerbation', 'Allergic bronchospasm', 'Exercise-induced asthma'],
      emergencyWeight: 65,
    },
    {
      id: 'phen_sob_pneumonia',
      label: 'Pneumonia Phenotype',
      description: 'Dyspnea with fever, productive cough, sputum, pleuritic chest pain',
      criteria: [
        { factKey: 'sob_fever', operator: 'eq', value: true },
        { factKey: 'sob_cough', operator: 'eq', value: true },
      ],
      probability: 0.5,
      suggestsMechanisms: ['parenchymal_infection', 'parenchymal_consolidation', 'alveolar_inflammation'],
      suggestsDifferentials: ['Community-acquired pneumonia', 'Hospital-acquired pneumonia', 'Aspiration pneumonia'],
      emergencyWeight: 70,
    },
    {
      id: 'phen_sob_pulmonary_edema',
      label: 'Pulmonary Edema Phenotype',
      description: 'Acute dyspnea with orthopnea, PND, frothy sputum, leg swelling',
      criteria: [
        { factKey: 'sob_orthopnea', operator: 'eq', value: true },
        { factKey: 'sob_leg_swelling', operator: 'eq', value: true },
      ],
      probability: 0.5,
      suggestsMechanisms: ['left_ventricular_failure', 'increased_pulmonary_capillary_pressure', 'airway_edema'],
      suggestsDifferentials: ['Acute pulmonary edema', 'Congestive heart failure exacerbation', 'Cardiogenic shock'],
      emergencyWeight: 90,
    },
    {
      id: 'phen_sob_pulmonary_embolism',
      label: 'Pulmonary Embolism Phenotype',
      description: 'Sudden severe dyspnea with pleuritic chest pain, hemoptysis, risk factors',
      criteria: [
        { factKey: 'sob_onset_pattern', operator: 'contains', value: 'Sudden' },
        { factKey: 'sob_chest_pain', operator: 'eq', value: true },
      ],
      probability: 0.3,
      suggestsMechanisms: ['pulmonary_artery_occlusion', 'ventilation_perfusion_mismatch', 'parenchymal_destruction'],
      suggestsDifferentials: ['Pulmonary embolism', 'Acute PE with hemodynamic compromise'],
      emergencyWeight: 95,
    },
    {
      id: 'phen_sob_copd',
      label: 'COPD Exacerbation Phenotype',
      description: 'Worsening dyspnea with cough, sputum, smoking history, chronic course',
      criteria: [
        { factKey: 'sob_asthma_copd', operator: 'eq', value: true },
        { factKey: 'sob_smoking', operator: 'eq', value: true },
      ],
      probability: 0.4,
      suggestsMechanisms: ['airway_obstruction', 'mucus_hypersecretion', 'smooth_muscle_constriction'],
      suggestsDifferentials: ['COPD exacerbation', 'Chronic bronchitis exacerbation', 'Emphysema with infection'],
      emergencyWeight: 60,
    },
    {
      id: 'phen_sob_pneumothorax',
      label: 'Pneumothorax Phenotype',
      description: 'Sudden sharp chest pain with ipsilateral dyspnea, absent breath sounds',
      criteria: [
        { factKey: 'sob_onset_pattern', operator: 'contains', value: 'Sudden' },
        { factKey: 'sob_chest_pain', operator: 'eq', value: true },
      ],
      probability: 0.3,
      suggestsMechanisms: ['intrapleural_air', 'parenchymal_destruction'],
      suggestsDifferentials: ['Spontaneous pneumothorax', 'Tension pneumothorax', 'Traumatic pneumothorax'],
      emergencyWeight: 85,
    },
  ],

  documentation: [
    { id: 'doc_onset', condition: { factKey: 'sob_onset_pattern', operator: 'present' }, template: 'Dyspnea onset: {{sob_onset_pattern}}.', priority: 1 },
    { id: 'doc_severity', condition: { factKey: 'sob_severity', operator: 'present' }, template: 'Dyspnea severity: {{sob_severity}}.', priority: 1 },
    { id: 'doc_position', condition: { factKey: 'sob_position', operator: 'present' }, template: 'Positional dyspnea: {{sob_position}}.', priority: 1 },
    { id: 'doc_exertion', condition: { factKey: 'sob_exertion', operator: 'present' }, template: 'Dyspnea on exertion: {{sob_exertion}}.', priority: 2 },
    { id: 'doc_at_rest', condition: { factKey: 'sob_at_rest', operator: 'eq', value: true }, template: 'Dyspnea at rest.', priority: 1 },
    { id: 'doc_cyanosis', condition: { factKey: 'sob_cyanosis', operator: 'eq', value: true }, template: 'CYANOSIS PRESENT.', priority: 1 },
    { id: 'doc_orthopnea', condition: { factKey: 'sob_orthopnea', operator: 'eq', value: true }, template: 'Orthopnea — requires sitting up.', priority: 2 },
    { id: 'doc_pnd', condition: { factKey: 'sob_pnd', operator: 'eq', value: true }, template: 'Paroxysmal nocturnal dyspnea.', priority: 2 },
    { id: 'doc_stridor', condition: { factKey: 'sob_stridor', operator: 'eq', value: true }, template: 'STRIDOR — upper airway obstruction.', priority: 1 },
    { id: 'doc_silent_chest', condition: { factKey: 'sob_silent_chest', operator: 'eq', value: true }, template: 'SILENT CHEST — critical, immediate intervention.', priority: 1 },
    { id: 'doc_wheeze', condition: { factKey: 'sob_wheeze', operator: 'eq', value: true }, template: 'Associated wheeze.', priority: 2 },
    { id: 'doc_leg_swelling', condition: { factKey: 'sob_leg_swelling', operator: 'eq', value: true }, template: 'Leg swelling present.', priority: 2 },
    { id: 'doc_sputum', condition: { factKey: 'sob_sputum', operator: 'present' }, template: 'Sputum: {{sob_sputum}}.', priority: 2 },
  ],

  reasoningHooks: [
    {
      id: 'rh_cyanosis',
      trigger: { on: 'fact_captured', ref: 'sob_cyanosis' },
      action: 'flag_red_flag',
      payload: ['Cyanosis with dyspnea — severe hypoxemia, urgent oxygen therapy, ABG, chest X-ray'],
    },
    {
      id: 'rh_silent_chest',
      trigger: { on: 'fact_captured', ref: 'sob_silent_chest' },
      action: 'flag_red_flag',
      payload: ['Silent chest — critical airway obstruction, immediate bronchodilator, intubation may be needed'],
    },
    {
      id: 'rh_stridor',
      trigger: { on: 'fact_captured', ref: 'sob_stridor' },
      action: 'flag_red_flag',
      payload: ['Stridor with dyspnea — upper airway obstruction, assess for croup, epiglottitis, foreign body'],
    },
    {
      id: 'rh_sudden_dyspnea',
      trigger: { on: 'fact_captured', ref: 'sob_onset_pattern' },
      action: 'suggest_differentials',
      payload: ['Sudden onset dyspnea — consider pulmonary embolism, pneumothorax, acute asthma, foreign body'],
    },
    {
      id: 'rh_orthopnea_pnd',
      trigger: { on: 'fact_captured', ref: 'sob_orthopnea' },
      action: 'suggest_investigations',
      payload: ['Orthopnea and PND — suspect pulmonary edema, BNP, echocardiogram, chest X-ray, diuretics'],
    },
  ],

  completion: {
    objectives: [
      { objectiveId: 'obj_char', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_timeline', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_severity', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_associated', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_previous', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_pediatric', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_red_flags', status: 'not_started', answeredQuestions: [], percentage: 0 },
    ],
    overall: 0,
  },
};
