// ═══════════════════════════════════════════════════════════════════════════════
// Vomiting Symptom Node — SX000004
// Sources: Hutchison Clinical Methods 25e, WHO IMCI, ESPGHAN Guidelines
// Universal Core + Pediatric (IMCI) + Neonatal + Obstetric (Hyperemesis) adapters
// ═══════════════════════════════════════════════════════════════════════════════

import type { SymptomNode } from '../symptom-types';

export const VOMITING_NODE: SymptomNode = {
  identity: {
    id: 'SX000004',
    canonicalName: 'Vomiting',
    synonyms: ['Emesis', 'Sickness', 'Bringing up', 'Regurgitation'],
    layTerms: ['Throwing up', 'Being sick', 'Puking'],
    translations: {},
    snomed: '24962000',
    icd10: 'R11',
    umls: 'C0042963',
    bodySystem: 'Gastrointestinal',
    primarySpecialty: 'General Medicine',
    emergencyWeight: 3,
  },

  metadata: {
    version: '1.0.0',
    author: 'AMEXAN Clinical Constitution',
    evidenceLevel: 'consensus',
    lastUpdated: '2026-07-13',
    source: 'Hutchison Clinical Methods 25e, WHO IMCI guidelines, ESPGHAN gastroenteritis guidelines',
  },

  activation: {
    chiefComplaint: true,
    hpiMention: true,
    ros: true,
    referralLetter: true,
    voiceTranscription: true,
    keywords: ['vomit', 'vomiting', 'sickness', 'nausea', 'throwing up', 'puking', 'regurgitation', 'emesis'],
  },

  timeline: {
    allowed: ['acute', 'subacute', 'chronic', 'recurrent', 'unknown'],
    defaultCategory: 'acute',
  },

  objectives: [
    { id: 'obj_char', label: 'Characterization', description: 'Establish nature and content of vomiting', order: 1, required: true, questionIds: ['q_content', 'q_color'] },
    { id: 'obj_timeline', label: 'Timeline', description: 'Onset, duration, frequency', order: 2, required: true, questionIds: ['q_onset', 'q_duration', 'q_frequency'] },
    { id: 'obj_severity', label: 'Severity', description: 'Assess severity and dehydration risk', order: 3, required: true, questionIds: ['q_keep_fluids', 'q_dehydration_signs'] },
    { id: 'obj_associated', label: 'Associated Symptoms', description: 'Identify accompanying GI and systemic symptoms', order: 4, required: true, questionIds: ['q_nausea', 'q_abdominal_pain', 'q_diarrhea', 'q_fever'] },
    { id: 'obj_previous', label: 'Previous Episodes', description: 'History of similar episodes or underlying conditions', order: 5, required: false, questionIds: ['q_previous_episodes', 'q_surgeries'] },
    { id: 'obj_pediatric', label: 'Pediatric Assessment', description: 'IMCI-based dehydration classification', order: 6, required: false, questionIds: ['q_ped_feeding', 'q_ped_urine_output'] },
    { id: 'obj_red_flags', label: 'Red Flags', description: 'Identify warning signs requiring urgent attention', order: 7, required: true, questionIds: ['q_hematemesis', 'q_bilious', 'q_feculent'] },
  ],

  questions: [
    // ── Characterization ──
    {
      id: 'q_content',
      text: 'What is the content of the vomit?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'What does the vomit look like?' },
      ],
      type: 'chips',
      chips: ['Undigested food', 'Partly digested food', 'Bile (green/yellow)', 'Blood (red/dark)', 'Feculent (brown/smelly)', 'Watery / clear fluid'],
      required: true,
      importance: 2,
      reasoningWeight: 30,
      factKey: 'vomiting_content',
      documentationPhrase: 'Vomitus contains {value}',
    },
    {
      id: 'q_color',
      text: 'What color is the vomit?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'What color is the vomit?' },
      ],
      type: 'chips',
      chips: ['Clear / white', 'Yellow / green (bile)', 'Red / bright red blood', 'Coffee ground / dark', 'Brown / feculent'],
      required: true,
      importance: 2,
      reasoningWeight: 25,
      factKey: 'vomiting_color',
      documentationPhrase: 'Vomitus color: {value}',
    },

    // ── Timeline ──
    {
      id: 'q_onset',
      text: 'When did the vomiting start?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'When did the vomiting start?' },
      ],
      type: 'chips',
      chips: ['Hours ago', '1-2 days ago', '3-5 days ago', 'More than 5 days ago'],
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'vomiting_onset',
      documentationPhrase: 'Vomiting started {value} ago',
    },
    {
      id: 'q_duration',
      text: 'How long has the vomiting lasted?',
      alternatives: [],
      type: 'chips',
      chips: ['Less than 24 hours', '1-3 days', '3-7 days', 'More than 7 days'],
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'vomiting_duration',
      documentationPhrase: 'Duration of vomiting: {value}',
    },
    {
      id: 'q_frequency',
      text: 'How many times have you vomited in the past 24 hours?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'How many times has the child vomited today?' },
      ],
      type: 'chips',
      chips: ['1-2 times', '3-5 times', '6-10 times', 'More than 10 times'],
      required: true,
      importance: 2,
      reasoningWeight: 25,
      factKey: 'vomiting_frequency',
      documentationPhrase: 'Frequency: {value} per 24 hours',
    },

    // ── Severity ──
    {
      id: 'q_keep_fluids',
      text: 'Are you able to keep down any fluids?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Can the child keep any fluids down?' },
      ],
      type: 'chips',
      chips: ['Can keep all fluids down', 'Can keep some fluids down', 'Vomits everything, even water'],
      required: true,
      importance: 3,
      reasoningWeight: 30,
      factKey: 'vomiting_keep_fluids',
      documentationPhrase: 'Able to keep fluids: {value}',
    },
    {
      id: 'q_dehydration_signs',
      text: 'Do you have any signs of dehydration (dry mouth, excessive thirst, reduced urine)?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child have dry mouth, sunken eyes, or reduced tears?' },
      ],
      type: 'chips',
      chips: ['No signs', 'Mild — dry mouth, thirsty', 'Moderate — sunken eyes, reduced urine', 'Severe — lethargic, no urine'],
      required: true,
      importance: 3,
      reasoningWeight: 35,
      factKey: 'vomiting_dehydration',
      documentationPhrase: 'Dehydration signs: {value}',
    },

    // ── Associated Symptoms ──
    {
      id: 'q_nausea',
      text: 'Do you feel nauseous before vomiting?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child feel sick before vomiting?' },
      ],
      type: 'boolean',
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'vomiting_nausea',
      documentationPhrase: 'Preceded by nausea',
    },
    {
      id: 'q_abdominal_pain',
      text: 'Do you have any abdominal pain?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child have a tummy ache?' },
      ],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'vomiting_abdominal_pain',
      documentationPhrase: 'Associated abdominal pain',
    },
    {
      id: 'q_diarrhea',
      text: 'Do you have any diarrhea?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child have diarrhea?' },
      ],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'vomiting_diarrhea',
      documentationPhrase: 'Associated diarrhea',
    },
    {
      id: 'q_fever',
      text: 'Do you have a fever?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Does the child have a fever?' },
      ],
      type: 'boolean',
      required: true,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'vomiting_fever',
      documentationPhrase: 'Associated with fever',
    },

    // ── Previous Episodes ──
    {
      id: 'q_previous_episodes',
      text: 'Have you had similar episodes of vomiting before?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Has the child had vomiting like this before?' },
      ],
      type: 'boolean',
      required: false,
      importance: 1,
      reasoningWeight: 10,
      factKey: 'vomiting_previous_episodes',
      documentationPhrase: 'Previous similar episodes',
    },
    {
      id: 'q_surgeries',
      text: 'Have you had any abdominal surgeries in the past?',
      alternatives: [],
      type: 'boolean',
      required: false,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'vomiting_surgeries',
      documentationPhrase: 'Previous abdominal surgeries',
    },

    // ── Pediatric ──
    {
      id: 'q_ped_feeding',
      text: 'How is the child\'s feeding?',
      alternatives: [],
      type: 'chips',
      chips: ['Feeding well', 'Feeding less than usual', 'Refusing all feeds', 'Vomiting after every feed'],
      required: false,
      importance: 2,
      reasoningWeight: 20,
      factKey: 'vomiting_ped_feeding',
      documentationPhrase: 'Feeding status: {value}',
    },
    {
      id: 'q_ped_urine_output',
      text: 'Has the child passed urine in the last 6 hours?',
      alternatives: [],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 30,
      factKey: 'vomiting_ped_urine',
      documentationPhrase: 'Urine output: {value}',
    },

    // ── Red Flags ──
    {
      id: 'q_hematemesis',
      text: 'Have you vomited blood?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Has the child vomited blood?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 50,
      factKey: 'vomiting_hematemesis',
      documentationPhrase: 'HEMATEMESIS PRESENT',
    },
    {
      id: 'q_bilious',
      text: 'Is the vomit green or yellow (bile)?',
      alternatives: [
        { condition: { ageMax: 5 }, text: 'Is the vomit green or yellow?' },
      ],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 45,
      factKey: 'vomiting_bilious',
      documentationPhrase: 'Bilious vomiting',
    },
    {
      id: 'q_feculent',
      text: 'Does the vomit smell like stool (feculent)?',
      alternatives: [],
      type: 'boolean',
      required: true,
      importance: 3,
      reasoningWeight: 50,
      factKey: 'vomiting_feculent',
      documentationPhrase: 'Feculent vomiting',
    },
  ],

  contextAdapters: {
    pediatric: {
      label: 'Pediatric Vomiting Extension (IMCI)',
      additionalObjectives: [],
      additionalQuestions: [
        {
          id: 'q_ped_sunken_eyes',
          text: 'Does the child have sunken eyes?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 30,
          factKey: 'vomiting_ped_sunken_eyes',
          documentationPhrase: 'Sunken eyes present',
        },
        {
          id: 'q_ped_skin_turgor',
          text: 'Does the child\'s skin pinch go back slowly?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 30,
          factKey: 'vomiting_ped_skin_turgor',
          documentationPhrase: 'Reduced skin turgor',
        },
        {
          id: 'q_ped_tears',
          text: 'Does the child have tears when crying?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 2,
          reasoningWeight: 20,
          factKey: 'vomiting_ped_tears',
          documentationPhrase: 'Absent tears',
        },
      ],
      suppressedQuestionIds: ['q_surgeries'],
      modifiedQuestions: [
        { id: 'q_dehydration_signs', text: 'Does the child have dry mouth, sunken eyes, or reduced tears? (WHO IMCI assessment)' },
      ],
    },
    neonatal: {
      label: 'Neonatal Vomiting Extension',
      additionalObjectives: [],
      additionalQuestions: [
        {
          id: 'q_neonatal_projectile',
          text: 'Is the vomiting projectile?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 40,
          factKey: 'vomiting_neonatal_projectile',
          documentationPhrase: 'Projectile vomiting',
        },
        {
          id: 'q_neonatal_fontanelle',
          text: 'Is the anterior fontanelle sunken?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 3,
          reasoningWeight: 30,
          factKey: 'vomiting_neonatal_fontanelle',
          documentationPhrase: 'Sunken fontanelle',
        },
      ],
      suppressedQuestionIds: ['q_surgeries', 'q_previous_episodes', 'q_nausea'],
      modifiedQuestions: [
        { id: 'q_content', text: 'What does the baby bring up? (milk, bile, blood)' },
        { id: 'q_frequency', text: 'How many times has the baby vomited today?' },
      ],
    },
    obstetric: {
      label: 'Obstetric Vomiting Extension (Hyperemesis)',
      additionalObjectives: [],
      additionalQuestions: [
        {
          id: 'q_obs_weight_loss',
          text: 'Have you lost weight since pregnancy?',
          alternatives: [],
          type: 'boolean',
          required: true,
          importance: 2,
          reasoningWeight: 25,
          factKey: 'vomiting_obs_weight_loss',
          documentationPhrase: 'Pregnancy weight loss',
        },
        {
          id: 'q_obs_ketones',
          text: 'Have you been tested for ketones in urine?',
          alternatives: [],
          type: 'boolean',
          required: false,
          importance: 2,
          reasoningWeight: 15,
          factKey: 'vomiting_obs_ketones',
          documentationPhrase: 'Urine ketones: {value}',
        },
      ],
      suppressedQuestionIds: [],
      modifiedQuestions: [
        { id: 'q_duration', text: 'How many weeks of pregnancy have you had vomiting?' },
      ],
    },
  },

  factExtraction: [
    { questionId: 'q_content', extract: (a) => [{ key: 'vomiting_content', value: String(a), type: 'reported', questionId: 'q_content', documentationPhrase: 'Vomitus contains ' + a }] },
    { questionId: 'q_color', extract: (a) => [{ key: 'vomiting_color', value: String(a), type: 'reported', questionId: 'q_color', documentationPhrase: 'Vomitus color: ' + a }] },
    { questionId: 'q_onset', extract: (a) => [{ key: 'vomiting_onset', value: String(a), type: 'reported', questionId: 'q_onset', documentationPhrase: 'Started ' + a + ' ago' }] },
    { questionId: 'q_duration', extract: (a) => [{ key: 'vomiting_duration', value: String(a), type: 'reported', questionId: 'q_duration', documentationPhrase: 'Duration: ' + a }] },
    { questionId: 'q_frequency', extract: (a) => [{ key: 'vomiting_frequency', value: String(a), type: 'reported', questionId: 'q_frequency', documentationPhrase: 'Frequency: ' + a + ' per 24 hours' }] },
    { questionId: 'q_keep_fluids', extract: (a) => [{ key: 'vomiting_keep_fluids', value: String(a), type: 'reported', questionId: 'q_keep_fluids', documentationPhrase: 'Able to keep fluids: ' + a }] },
    { questionId: 'q_dehydration_signs', extract: (a) => [{ key: 'vomiting_dehydration', value: String(a), type: 'reported', questionId: 'q_dehydration_signs', documentationPhrase: 'Dehydration: ' + a }] },
    { questionId: 'q_abdominal_pain', extract: (a) => a ? [{ key: 'vomiting_abdominal_pain', value: true, type: 'reported', questionId: 'q_abdominal_pain', documentationPhrase: 'Associated abdominal pain' }] : [] },
    { questionId: 'q_diarrhea', extract: (a) => a ? [{ key: 'vomiting_diarrhea', value: true, type: 'reported', questionId: 'q_diarrhea', documentationPhrase: 'Associated diarrhea' }] : [] },
    { questionId: 'q_fever', extract: (a) => a ? [{ key: 'vomiting_fever', value: true, type: 'reported', questionId: 'q_fever', documentationPhrase: 'Associated with fever' }] : [] },
    { questionId: 'q_hematemesis', extract: (a) => a ? [{ key: 'vomiting_hematemesis', value: true, type: 'reported', questionId: 'q_hematemesis', documentationPhrase: 'HEMATEMESIS PRESENT' }] : [] },
    { questionId: 'q_bilious', extract: (a) => a ? [{ key: 'vomiting_bilious', value: true, type: 'reported', questionId: 'q_bilious', documentationPhrase: 'Bilious vomiting' }] : [] },
    { questionId: 'q_feculent', extract: (a) => a ? [{ key: 'vomiting_feculent', value: true, type: 'reported', questionId: 'q_feculent', documentationPhrase: 'Feculent vomiting' }] : [] },
    { questionId: 'q_previous_episodes', extract: (a) => a ? [{ key: 'vomiting_previous_episodes', value: true, type: 'reported', questionId: 'q_previous_episodes', documentationPhrase: 'Previous similar episodes' }] : [] },
    { questionId: 'q_nausea', extract: (a) => a ? [{ key: 'vomiting_nausea', value: true, type: 'reported', questionId: 'q_nausea', documentationPhrase: 'Preceded by nausea' }] : [] },
    { questionId: 'q_ped_urine', extract: (a) => [{ key: 'vomiting_ped_urine', value: a ? true : false, type: 'reported', questionId: 'q_ped_urine', documentationPhrase: a ? 'Urine output present' : 'No urine output' }] },
  ],

  relationships: [
    { targetSymptomId: 'SX000001', type: 'associated_with', strength: 0.6, description: 'Commonly associated with fever in gastroenteritis' },
    { targetSymptomId: 'SX000002', type: 'associated_with', strength: 0.2, description: 'May be associated with headache (migraine)' },
    { targetSymptomId: 'SX000006', type: 'associated_with', strength: 0.7, description: 'Commonly associated with diarrhea (gastroenteritis)' },
    { targetSymptomId: 'SX000007', type: 'associated_with', strength: 0.6, description: 'Commonly associated with abdominal pain' },
  ],

  phenotypes: [
    {
      id: 'phen_vomiting_gastroenteritis',
      label: 'Gastroenteritis Phenotype',
      description: 'Acute vomiting with diarrhea, fever, abdominal cramps',
      criteria: [
        { factKey: 'vomiting_diarrhea', operator: 'eq', value: true },
        { factKey: 'vomiting_duration', operator: 'contains', value: 'Less' },
      ],
      probability: 0.6,
      suggestsMechanisms: ['Infectious enteritis', 'Mucosal inflammation', 'Decreased intestinal absorption'],
      suggestsDifferentials: ['Viral gastroenteritis', 'Bacterial gastroenteritis', 'Food poisoning'],
      emergencyWeight: 30,
    },
    {
      id: 'phen_vomiting_bilious',
      label: 'Bilious Vomiting Phenotype',
      description: 'Green or yellow vomit, suggesting possible obstruction',
      criteria: [
        { factKey: 'vomiting_bilious', operator: 'eq', value: true },
      ],
      probability: 0.5,
      suggestsMechanisms: ['Intestinal obstruction', 'Bile reflux', 'Distal duodenal or jejunal obstruction'],
      suggestsDifferentials: ['Intestinal obstruction', 'Superior mesenteric artery syndrome', 'Midgut volvulus'],
      emergencyWeight: 80,
    },
    {
      id: 'phen_vomiting_feculent',
      label: 'Feculent Vomiting Phenotype',
      description: 'Brown, foul-smelling vomit indicating distal obstruction',
      criteria: [
        { factKey: 'vomiting_feculent', operator: 'eq', value: true },
      ],
      probability: 0.7,
      suggestsMechanisms: ['Distal intestinal obstruction', 'Bacterial overgrowth', 'Fecal reflux'],
      suggestsDifferentials: ['Large bowel obstruction', 'Intestinal perforation', 'Peritonitis'],
      emergencyWeight: 95,
    },
    {
      id: 'phen_vomiting_hematemesis',
      label: 'Hematemesis Phenotype',
      description: 'Vomiting of blood from upper GI source',
      criteria: [
        { factKey: 'vomiting_hematemesis', operator: 'eq', value: true },
      ],
      probability: 0.5,
      suggestsMechanisms: ['Upper GI bleeding', 'Mucosal erosion', 'Variceal rupture', 'Mallory-Weiss tear'],
      suggestsDifferentials: ['Peptic ulcer disease', 'Esophageal varices', 'Mallory-Weiss tear', 'Gastritis'],
      emergencyWeight: 90,
    },
    {
      id: 'phen_vomiting_cyclic',
      label: 'Cyclic Vomiting Syndrome Phenotype',
      description: 'Recurrent stereotypical episodes of vomiting with pain-free intervals',
      criteria: [
        { factKey: 'vomiting_previous_episodes', operator: 'eq', value: true },
        { factKey: 'vomiting_duration', operator: 'contains', value: 'Less' },
      ],
      probability: 0.3,
      suggestsMechanisms: ['Autonomic dysfunction', 'Mitochondrial dysfunction', 'Migraine variant'],
      suggestsDifferentials: ['Cyclic vomiting syndrome', 'Abdominal migraine', 'Cannabinoid hyperemesis'],
      emergencyWeight: 15,
    },
  ],

  documentation: [
    { id: 'doc_content', condition: { factKey: 'vomiting_content', operator: 'present' }, template: 'Vomitus contains {{vomiting_content}}.', priority: 1 },
    { id: 'doc_duration', condition: { factKey: 'vomiting_duration', operator: 'present' }, template: 'Duration: {{vomiting_duration}}.', priority: 1 },
    { id: 'doc_frequency', condition: { factKey: 'vomiting_frequency', operator: 'present' }, template: 'Frequency: {{vomiting_frequency}}.', priority: 1 },
    { id: 'doc_dehydration', condition: { factKey: 'vomiting_dehydration', operator: 'present' }, template: 'Dehydration: {{vomiting_dehydration}}.', priority: 1 },
    { id: 'doc_keep_fluids', condition: { factKey: 'vomiting_keep_fluids', operator: 'present' }, template: 'Able to keep fluids: {{vomiting_keep_fluids}}.', priority: 2 },
    { id: 'doc_hematemesis', condition: { factKey: 'vomiting_hematemesis', operator: 'eq', value: true }, template: 'HEMATEMESIS PRESENT.', priority: 1 },
    { id: 'doc_bilious', condition: { factKey: 'vomiting_bilious', operator: 'eq', value: true }, template: 'BILIOUS VOMITING — suspect obstruction.', priority: 1 },
    { id: 'doc_feculent', condition: { factKey: 'vomiting_feculent', operator: 'eq', value: true }, template: 'FECULENT VOMITING — urgent surgical review.', priority: 1 },
    { id: 'doc_diarrhea', condition: { factKey: 'vomiting_diarrhea', operator: 'eq', value: true }, template: 'Associated with diarrhea.', priority: 2 },
    { id: 'doc_abdominal_pain', condition: { factKey: 'vomiting_abdominal_pain', operator: 'eq', value: true }, template: 'Associated abdominal pain.', priority: 2 },
  ],

  reasoningHooks: [
    {
      id: 'rh_hematemesis',
      trigger: { on: 'fact_captured', ref: 'vomiting_hematemesis' },
      action: 'flag_red_flag',
      payload: ['Hematemesis — urgent upper GI endoscopy, check hemoglobin, cross-match blood'],
    },
    {
      id: 'rh_bilious_vomiting',
      trigger: { on: 'fact_captured', ref: 'vomiting_bilious' },
      action: 'flag_red_flag',
      payload: ['Bilious vomiting — suspect intestinal obstruction, urgent surgical consult, abdominal X-ray'],
    },
    {
      id: 'rh_feculent_vomiting',
      trigger: { on: 'fact_captured', ref: 'vomiting_feculent' },
      action: 'flag_red_flag',
      payload: ['Feculent vomiting — distal obstruction or peritonitis, emergency surgical evaluation'],
    },
    {
      id: 'rh_severe_dehydration',
      trigger: { on: 'fact_captured', ref: 'vomiting_dehydration' },
      action: 'flag_red_flag',
      payload: ['Severe dehydration with vomiting — IV fluids, hospital admission, monitor UOP'],
    },
    {
      id: 'rh_cyclic_vomiting',
      trigger: { on: 'fact_captured', ref: 'vomiting_previous_episodes' },
      action: 'suggest_differentials',
      payload: ['Recurrent vomiting episodes — consider cyclic vomiting syndrome, abdominal migraine, metabolic disorders'],
    },
  ],

  completion: {
    objectives: [
      { objectiveId: 'obj_char', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_timeline', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_severity', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_associated', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_previous', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_pediatric', status: 'not_started', answeredQuestions: [], percentage: 0 },
      { objectiveId: 'obj_red_flags', status: 'not_started', answeredQuestions: [], percentage: 0 },
    ],
    overall: 0,
  },
};
