import type { YamlDisease } from './yaml-schema';

export const MISSING_DISEASES_3: YamlDisease[] = [
  {
    id: 'disease_cystic_fibrosis', name: 'Cystic Fibrosis', icd10: 'E84', snomed: '190905008',
    synonyms: ['CF', 'Mucoviscidosis', 'CFTR deficiency'],
    specialty: ['pulmonology', 'pediatrics', 'genetics'],
    emergencyLevel: 'orange',
    mechanisms: ['mech_mucociliary_dysfunction', 'mech_bronchiectasis', 'mech_airway_inflammation'],
    phenotypes: ['phen_chronic_productive', 'phen_neonatal_cough', 'phen_hemoptysis'],
    symptoms: [
      { symptomId: 'cough', frequency: 'always' }, { symptomId: 'sputum', frequency: 'always' },
      { symptomId: 'dyspnea', frequency: 'common' }, { symptomId: 'failure_to_thrive', frequency: 'common' },
      { symptomId: 'steatorrhea', frequency: 'common' }, { symptomId: 'recurrent_infections', frequency: 'always' },
    ],
    signs: [
      { signId: 'crackles', frequency: 'always' }, { signId: 'clubbing', frequency: 'common' },
      { signId: 'wasting', frequency: 'common' }, { signId: 'barrel_chest', frequency: 'uncommon' },
    ],
    riskFactors: ['family_history_cf', 'northern_european_ancestry', 'consanguinity'],
    etiologies: ['cftr_gene_mutation'],
    complications: ['bronchiectasis', 'respiratory_failure', 'pancreatic_insufficiency', 'diabetes_related_to_cf', 'infertility', 'liver_disease'],
    investigations: [
      { investigationId: 'inv_sweat_chloride', purpose: 'Gold standard diagnosis', timing: 'initial' },
      { investigationId: 'inv_cftr_genetic_testing', purpose: 'Identify mutation', timing: 'confirmatory' },
      { investigationId: 'inv_hrct', purpose: 'Assess bronchiectasis', timing: 'initial' },
      { investigationId: 'inv_pft', purpose: 'Assess lung function decline', timing: 'monitoring' },
      { investigationId: 'inv_sputum_culture', purpose: 'Identify colonizing organisms', timing: 'initial' },
    ],
    treatments: [
      { treatmentId: 'tx_airway_clearance_cf', firstLine: true },
      { treatmentId: 'tx_dornase_alfa', firstLine: true },
      { treatmentId: 'tx_cftr_modulator', firstLine: true },
      { treatmentId: 'tx_antibiotics_prolonged', firstLine: true },
      { treatmentId: 'tx_pancreatic_enzymes', firstLine: true },
    ],
    guidelines: ['guideline_cff_cf', 'guideline_ecfs_cf'],
    scores: ['score_brooke_bronchiectasis'],
    monitoring: ['pft_quarterly', 'sputum_culture_every_visit', 'nutritional_status', 'cxr_ct_annual'],
    differentials: ['disease_bronchiectasis', 'disease_primary_ciliary_dyskinesia', 'disease_asthma', 'disease_immunodeficiency'],
  },
  {
    id: 'disease_primary_ciliary_dyskinesia', name: 'Primary Ciliary Dyskinesia', icd10: 'J98', snomed: '72366004',
    synonyms: ['PCD', 'Kartagener syndrome', 'Immotile cilia syndrome'],
    specialty: ['pulmonology', 'pediatrics', 'ent'],
    emergencyLevel: 'yellow',
    mechanisms: ['mech_mucociliary_dysfunction', 'mech_bronchiectasis'],
    phenotypes: ['phen_chronic_productive', 'phen_neonatal_cough', 'phen_recurrent_pneumonia'],
    symptoms: [
      { symptomId: 'cough', frequency: 'always' }, { symptomId: 'sputum', frequency: 'always' },
      { symptomId: 'neonatal_respiratory_distress', frequency: 'common' }, { symptomId: 'recurrent_sinusitis', frequency: 'always' },
      { symptomId: 'recurrent_otitis', frequency: 'common' }, { symptomId: 'infertility', frequency: 'common' },
    ],
    signs: [
      { signId: 'crackles', frequency: 'always' }, { signId: 'clubbing', frequency: 'common' },
      { signId: 'situs_inversus', frequency: 'uncommon' },
    ],
    riskFactors: ['family_history_pcd', 'consanguinity', 'situs_inversus'],
    etiologies: ['genetic_mutations_dynein_arm'],
    complications: ['bronchiectasis', 'chronic_sinusitis', 'infertility', 'respiratory_failure'],
    investigations: [
      { investigationId: 'inv_nasal_nitric_oxide', purpose: 'Low levels diagnostic', timing: 'initial' },
      { investigationId: 'inv_ciliary_biopsy', purpose: 'EM shows ultrastructural defect', timing: 'confirmatory' },
      { investigationId: 'inv_hrct', purpose: 'Assess bronchiectasis', timing: 'initial' },
      { investigationId: 'inv_genetic_testing_pcd', purpose: 'Identify mutation', timing: 'confirmatory' },
    ],
    treatments: [
      { treatmentId: 'tx_airway_clearance_cf', firstLine: true },
      { treatmentId: 'tx_antibiotics_prolonged', firstLine: true },
      { treatmentId: 'tx_influenza_vaccine', firstLine: true },
      { treatmentId: 'tx_pneumococcal_vaccine', firstLine: true },
    ],
    guidelines: ['guideline_ers_pcd'],
    scores: [],
    monitoring: ['pft_annual', 'sputum_culture', 'ct_interval'],
    differentials: ['disease_cystic_fibrosis', 'disease_bronchiectasis', 'disease_asthma', 'disease_immunodeficiency'],
  },
  {
    id: 'disease_hiv_related_cough', name: 'HIV-Related Cough / PCP', icd10: 'B20', snomed: '86466007',
    synonyms: ['HIV pulmonary disease', 'AIDS-related respiratory infection'],
    specialty: ['infectious_disease', 'pulmonology', 'hiv_medicine'],
    emergencyLevel: 'red',
    mechanisms: ['mech_airway_inflammation', 'mech_immunocompromised', 'mech_fungal_invasion'],
    phenotypes: ['phen_immunocompromised_cough', 'phen_fungal_cough', 'phen_constitutional', 'phen_dry_cough'],
    symptoms: [
      { symptomId: 'cough', frequency: 'always' }, { symptomId: 'dyspnea', frequency: 'always' },
      { symptomId: 'fever', frequency: 'always' }, { symptomId: 'weight_loss', frequency: 'common' },
      { symptomId: 'night_sweats', frequency: 'common' },
    ],
    signs: [
      { signId: 'crackles', frequency: 'common' }, { signId: 'tachypnea', frequency: 'common' },
      { signId: 'hypoxia', frequency: 'common' }, { signId: 'wasting', frequency: 'common' },
    ],
    riskFactors: ['hiv_positive', 'low_cd4_count', 'not_on_art', 'poor_art_adherence'],
    etiologies: ['pneumocystis_jirovecii', 'mycobacterium_tuberculosis', 'cryptococcus', 'cytomegalovirus', 'bacterial_pathogens'],
    complications: ['respiratory_failure', 'disseminated_infection', 'immune_reconstitution_syndrome', 'death'],
    investigations: [
      { investigationId: 'inv_cd4_count', purpose: 'Assess immune status', timing: 'initial' },
      { investigationId: 'inv_hiv_viral_load', purpose: 'HIV control assessment', timing: 'initial' },
      { investigationId: 'inv_cxr', purpose: 'Typical patterns', timing: 'initial' },
      { investigationId: 'inv_bronchoscopy_bal', purpose: 'Identify opportunistic infections', timing: 'initial' },
      { investigationId: 'inv_sputum_afb', purpose: 'TB co-infection screen', timing: 'initial' },
    ],
    treatments: [
      { treatmentId: 'tx_art_initiation', firstLine: true },
      { treatmentId: 'tx_tmp_smx', firstLine: true },
      { treatmentId: 'tx_tb_treatment_hiv', firstLine: false },
      { treatmentId: 'tx_steroids_pcp', firstLine: false },
    ],
    guidelines: ['guideline_who_hiv_respiratory'],
    scores: ['score_cd4_stratification'],
    monitoring: ['cd4_count', 'viral_load', 'art_adherence', 'sputum_conversion'],
    differentials: ['disease_pulmonary_tuberculosis', 'disease_pcp', 'disease_cap', 'disease_invasive_aspergillosis'],
  },
  {
    id: 'disease_vocal_cord_dysfunction', name: 'Vocal Cord Dysfunction', icd10: 'J38', snomed: '703283000',
    synonyms: ['VCD', 'Paradoxical vocal fold motion', 'Munchausen stridor'],
    specialty: ['pulmonology', 'ent', 'speech_therapy'],
    emergencyLevel: 'orange',
    mechanisms: ['mech_vocal_cord_dysfunction', 'mech_upper_airway_stimulation'],
    phenotypes: ['phen_dry_cough', 'phen_wheeze_dominant', 'phen_stridor'],
    symptoms: [
      { symptomId: 'cough', frequency: 'always' }, { symptomId: 'stridor_symptom', frequency: 'common' },
      { symptomId: 'dyspnea', frequency: 'always' }, { symptomId: 'throat_tightness', frequency: 'common' },
      { symptomId: 'voice_change', frequency: 'common' },
    ],
    signs: [
      { signId: 'stridor_sign', frequency: 'common' }, { signId: 'no_chest_findings', frequency: 'common' },
    ],
    riskFactors: ['female', 'age_20_40', 'anxiety', 'gerd', 'exercise', 'irritant_exposure'],
    etiologies: ['paradoxical_vocal_cord_adduction', 'functional_upper_airway_obstruction'],
    complications: ['misdiagnosis_as_asthma', 'intubation', 'tracheostomy'],
    investigations: [
      { investigationId: 'inv_laryngoscopy', purpose: 'Visualize vocal cord adduction', timing: 'initial' },
      { investigationId: 'inv_spirometry_flow_loop', purpose: 'Extrathoracic obstruction pattern', timing: 'initial' },
    ],
    treatments: [
      { treatmentId: 'tx_speech_therapy', firstLine: true },
      { treatmentId: 'tx_breathing_techniques', firstLine: true },
      { treatmentId: 'tx_gerd_treatment', firstLine: false },
    ],
    guidelines: [],
    scores: [],
    monitoring: ['symptom_diary', 'laryngoscopy_follow_up'],
    differentials: ['disease_asthma', 'disease_croup', 'disease_epiglottitis', 'disease_foreign_body_aspiration'],
  },
  {
    id: 'disease_psychogenic_cough', name: 'Psychogenic / Habit Cough', icd10: 'F45.8', snomed: '44644005',
    synonyms: ['Habit cough', 'Tic cough', 'Somatic cough syndrome'],
    specialty: ['pulmonology', 'psychiatry', 'pediatrics'],
    emergencyLevel: 'green',
    mechanisms: ['mech_psychogenic', 'mech_neurological_cough'],
    phenotypes: ['phen_psychogenic_cough', 'phen_dry_cough'],
    symptoms: [
      { symptomId: 'cough', frequency: 'always' }, { symptomId: 'cough_during_waking_hours', frequency: 'always' },
    ],
    signs: [
      { signId: 'no_chest_findings', frequency: 'always' },
    ],
    riskFactors: ['children', 'anxiety', 'stress', 'family_dysfunction', 'history_of_tic_disorder'],
    etiologies: ['psychogenic', 'habit', 'tic_disorder'],
    complications: ['school_absence', 'social_isolation'],
    investigations: [],
    treatments: [
      { treatmentId: 'tx_reassurance', firstLine: true },
      { treatmentId: 'tx_speech_therapy', firstLine: false },
      { treatmentId: 'tx_cognitive_behavioral_therapy', firstLine: false },
      { treatmentId: 'tx_hypnosis', firstLine: false },
    ],
    guidelines: [],
    scores: [],
    monitoring: ['symptom_diary', 'school_attendance'],
    differentials: ['disease_asthma', 'disease_gerd', 'disease_tourette_syndrome', 'disease_postnasal_drip'],
  },
  {
    id: 'disease_ards', name: 'Acute Respiratory Distress Syndrome', icd10: 'J80', snomed: '67782003',
    synonyms: ['ARDS', 'Acute lung injury', 'Shock lung'],
    specialty: ['intensive_care', 'pulmonology'],
    emergencyLevel: 'red',
    mechanisms: ['mech_alveolar_filling', 'mech_pulmonary_oedema'],
    phenotypes: ['phen_ards_cough', 'phen_acute_onset', 'phen_productive_with_fever'],
    symptoms: [
      { symptomId: 'dyspnea', frequency: 'always' }, { symptomId: 'cough', frequency: 'common' },
      { symptomId: 'hypoxia', frequency: 'always' },
    ],
    signs: [
      { signId: 'hypoxia', frequency: 'always' }, { signId: 'tachypnea', frequency: 'always' },
      { signId: 'crackles', frequency: 'always' }, { signId: 'accessory_muscle_use', frequency: 'always' },
    ],
    riskFactors: ['sepsis', 'pneumonia', 'aspiration', 'trauma', 'pancreatitis', 'massive_transfusion', 'burns', 'drug_overdose'],
    etiologies: ['direct_lung_injury', 'indirect_lung_injury', 'sepsis', 'pneumonia', 'aspiration', 'non_pulmonary_sepsis'],
    complications: ['ventilator_associated_lung_injury', 'multi_organ_failure', 'pulmonary_fibrosis', 'neuromuscular_weakness', 'death'],
    investigations: [
      { investigationId: 'inv_cxr', purpose: 'Bilateral infiltrates', timing: 'initial' },
      { investigationId: 'inv_arterial_blood_gas', purpose: 'PaO2/FiO2 ratio', timing: 'initial' },
      { investigationId: 'inv_echocardiogram', purpose: 'Exclude cardiogenic pulmonary edema', timing: 'initial' },
      { investigationId: 'inv_ct_chest', purpose: 'Characterize lung involvement', timing: 'initial' },
    ],
    treatments: [
      { treatmentId: 'tx_lung_protective_ventilation', firstLine: true },
      { treatmentId: 'tx_prone_positioning', firstLine: true },
      { treatmentId: 'tx_neuromuscular_blockade', firstLine: false },
      { treatmentId: 'tx_ecmo', firstLine: false },
    ],
    guidelines: ['guideline_esicm_ards', 'guideline_ats_ards'],
    scores: ['score_berlin_ards', 'score_murray_lis'],
    monitoring: ['pao2_fio2_trend', 'lung_compliance', 'plateau_pressure', 'ventilator_settings'],
    differentials: ['disease_cap', 'disease_heart_failure', 'disease_vap', 'disease_pulmonary_embolism'],
  },
  {
    id: 'disease_postop_atelectasis', name: 'Post-Operative Atelectasis', icd10: 'J98.1', snomed: '197922004',
    synonyms: ['Collapsed lung post-surgery', 'Post-anesthesia atelectasis'],
    specialty: ['intensive_care', 'pulmonology', 'anesthesiology'],
    emergencyLevel: 'yellow',
    mechanisms: ['mech_atelectasis', 'mech_ventilator_associated'],
    phenotypes: ['phen_postop_cough', 'phen_dry_cough', 'phen_acute_onset'],
    symptoms: [
      { symptomId: 'cough', frequency: 'always' }, { symptomId: 'dyspnea', frequency: 'common' },
      { symptomId: 'low_grade_fever', frequency: 'common' },
    ],
    signs: [
      { signId: 'reduced_breath_sounds', frequency: 'common' }, { signId: 'crackles', frequency: 'common' },
      { signId: 'tachypnea', frequency: 'common' }, { signId: 'hypoxia', frequency: 'common' },
    ],
    riskFactors: ['general_anesthesia', 'upper_abdominal_surgery', 'thoracic_surgery', 'obesity', 'copd', 'smoking'],
    etiologies: ['reduced_functional_residual_capacity', 'diaphragmatic_dysfunction', 'mucous_plugging'],
    complications: ['pneumonia', 'hypoxia', 'prolonged_mechanical_ventilation', 'icu_readmission'],
    investigations: [
      { investigationId: 'inv_cxr', purpose: 'Linear opacities, volume loss', timing: 'initial' },
      { investigationId: 'inv_oxyhemoglobin', purpose: 'Assess oxygenation', timing: 'initial' },
    ],
    treatments: [
      { treatmentId: 'tx_incentive_spirometry', firstLine: true },
      { treatmentId: 'tx_early_mobilization', firstLine: true },
      { treatmentId: 'tx_chest_physiotherapy', firstLine: true },
      { treatmentId: 'tx_bilevel_positive_airway_pressure', firstLine: false },
    ],
    guidelines: [],
    scores: [],
    monitoring: ['oxygen_saturation', 'cxr_resolution', 'lung_auscultation'],
    differentials: ['disease_pneumonia', 'disease_pulmonary_embolism', 'disease_heart_failure', 'disease_pneumothorax'],
  },
  {
    id: 'disease_hemothorax', name: 'Hemothorax', icd10: 'J94.2', snomed: '263734006',
    synonyms: ['Blood in pleural space'],
    specialty: ['emergency_medicine', 'cardiothoracic_surgery', 'trauma'],
    emergencyLevel: 'red',
    mechanisms: ['mech_pleural_effusion', 'mech_trauma'],
    phenotypes: ['phen_trauma_cough', 'phen_acute_onset', 'phen_pleuritic_cough'],
    symptoms: [
      { symptomId: 'chest_pain', frequency: 'always' }, { symptomId: 'dyspnea', frequency: 'always' },
      { symptomId: 'cough', frequency: 'common' }, { symptomId: 'hemoptysis', frequency: 'uncommon' },
    ],
    signs: [
      { signId: 'dull_percussion', frequency: 'always' }, { signId: 'reduced_breath_sounds', frequency: 'always' },
      { signId: 'tachypnea', frequency: 'always' }, { signId: 'hypotension', frequency: 'common' },
    ],
    riskFactors: ['chest_trauma', 'thoracic_surgery', 'coagulopathy', 'anticoagulation', 'ruptured_aortic_aneurysm'],
    etiologies: ['traumatic_chest_injury', 'iatrogenic_post_surgery', 'ruptured_neoplasm', 'coagulopathy'],
    complications: ['hypovolemic_shock', 'fibrothorax', 'empyema', 'respiratory_failure'],
    investigations: [
      { investigationId: 'inv_cxr', purpose: 'Pleural opacity', timing: 'initial' },
      { investigationId: 'inv_ct_chest', purpose: 'Characterize hemothorax', timing: 'initial' },
      { investigationId: 'inv_pleural_ultrasound', purpose: 'Guide drainage', timing: 'initial' },
    ],
    treatments: [
      { treatmentId: 'tx_chest_drain_insertion', firstLine: true },
      { treatmentId: 'tx_video_assisted_thoracoscopic_surgery', firstLine: false },
      { treatmentId: 'tx_blood_transfusion', firstLine: false },
      { treatmentId: 'tx_thoracotomy', firstLine: false },
    ],
    guidelines: ['guideline_ats_chest_trauma'],
    scores: [],
    monitoring: ['drain_output', 'hemoglobin_trend', 'cxr_follow_up', 'coagulation_profile'],
    differentials: ['disease_pneumothorax', 'disease_pleural_effusion', 'disease_pulmonary_contusion', 'disease_hemorrhagic_shock'],
  },
];
