import type { YamlDisease } from './yaml-schema';

export const MISSING_DISEASES_1: YamlDisease[] = [
  {
    id: 'disease_hap', name: 'Hospital-Acquired Pneumonia', icd10: 'J15', snomed: '385628006',
    synonyms: ['Nosocomial pneumonia', 'HAP'],
    specialty: ['pulmonology', 'infectious_disease', 'intensive_care'],
    emergencyLevel: 'red',
    mechanisms: ['mech_alveolar_filling', 'mech_ventilator_associated'],
    phenotypes: ['phen_productive_with_fever', 'phen_acute_productive', 'phen_immunocompromised_cough'],
    symptoms: [
      { symptomId: 'cough', frequency: 'always' }, { symptomId: 'fever', frequency: 'always' },
      { symptomId: 'dyspnea', frequency: 'always' }, { symptomId: 'purulent_sputum', frequency: 'common' },
    ],
    signs: [
      { signId: 'crackles', frequency: 'always' }, { signId: 'fever_sign', frequency: 'always' },
      { signId: 'tachypnea', frequency: 'common' }, { signId: 'hypoxia', frequency: 'common' },
    ],
    riskFactors: ['mechanical_ventilation', 'prolonged_icu_stay', 'prior_antibiotics', 'immunosuppression', 'surgery'],
    etiologies: ['pseudomonas_aeruginosa', 'klebsiella_pneumoniae', 'acinetobacter', 'mrsa', 'escherichia_coli'],
    complications: ['sepsis', 'respiratory_failure', 'empyema', 'multidrug_resistance', 'death'],
    investigations: [
      { investigationId: 'inv_cxr', purpose: 'Confirm new infiltrate', timing: 'initial' },
      { investigationId: 'inv_blood_culture', purpose: 'Identify pathogen', timing: 'initial' },
      { investigationId: 'inv_sputum_culture', purpose: 'Tracheal aspirate culture', timing: 'initial' },
      { investigationId: 'inv_procalcitonin', purpose: 'Assess bacterial infection', timing: 'initial' },
      { investigationId: 'inv_ct_chest', purpose: 'Characterize infiltrates', timing: 'confirmatory' },
    ],
    treatments: [
      { treatmentId: 'tx_anti_pseudomonal_beta_lactam', firstLine: true },
      { treatmentId: 'tx_aminoglycoside', firstLine: false },
      { treatmentId: 'tx_vancomycin', firstLine: false },
    ],
    guidelines: ['guideline_ats_hap', 'guideline_ers_hap'],
    scores: ['score_qsofa', 'score_cpisd'],
    monitoring: ['culture_results', 'white_cell_count', 'crp_trend', 'oxygen_saturation'],
    differentials: ['disease_cap', 'disease_vap', 'disease_lung_abscess', 'disease_pulmonary_embolism'],
  },
  {
    id: 'disease_vap', name: 'Ventilator-Associated Pneumonia', icd10: 'J95.851', snomed: '194905004',
    synonyms: ['VAP', 'Ventilator-acquired pneumonia'],
    specialty: ['intensive_care', 'pulmonology', 'infectious_disease'],
    emergencyLevel: 'red',
    mechanisms: ['mech_ventilator_associated', 'mech_alveolar_filling'],
    phenotypes: ['phen_productive_with_fever', 'phen_immunocompromised_cough', 'phen_vap_syndrome'],
    symptoms: [
      { symptomId: 'cough', frequency: 'always' }, { symptomId: 'fever', frequency: 'always' },
      { symptomId: 'increased_secretions', frequency: 'always' }, { symptomId: 'hypoxia', frequency: 'common' },
    ],
    signs: [
      { signId: 'crackles', frequency: 'always' }, { signId: 'fever_sign', frequency: 'always' },
      { signId: 'hypoxia', frequency: 'common' }, { signId: 'tachypnea', frequency: 'common' },
    ],
    riskFactors: ['prolonged_ventilation', 'reintubation', 'aspiration', 'sedation', 'h2_blocker_use'],
    etiologies: ['pseudomonas_aeruginosa', 'mrsa', 'acinetobacter_baumannii', 'sterile_tracheal_aspirate'],
    complications: ['sepsis', 'prolonged_ventilation', 'tracheostomy', 'bronchopleural_fistula', 'death'],
    investigations: [
      { investigationId: 'inv_cxr', purpose: 'New or progressive infiltrate', timing: 'initial' },
      { investigationId: 'inv_tracheal_aspirate', purpose: 'Quantitative culture', timing: 'initial' },
      { investigationId: 'inv_blood_culture', purpose: 'Identify bacteremia', timing: 'initial' },
      { investigationId: 'inv_procalcitonin', purpose: 'Guide antibiotic duration', timing: 'monitoring' },
    ],
    treatments: [
      { treatmentId: 'tx_anti_pseudomonal_beta_lactam', firstLine: true },
      { treatmentId: 'tx_vancomycin', firstLine: true },
      { treatmentId: 'tx_aminoglycoside', firstLine: false },
    ],
    guidelines: ['guideline_ats_vap'],
    scores: ['score_cpisd'],
    monitoring: ['cps_score', 'oxygenation', 'tracheal_aspirate_gram_stain', 'white_cell_trend'],
    differentials: ['disease_hap', 'disease_ards', 'disease_atelectasis', 'disease_pulmonary_edema'],
  },
  {
    id: 'disease_empyema', name: 'Empyema Thoracis', icd10: 'J86', snomed: '358200005',
    synonyms: ['Pleural empyema', 'Pyothorax'],
    specialty: ['pulmonology', 'cardiothoracic_surgery', 'infectious_disease'],
    emergencyLevel: 'red',
    mechanisms: ['mech_pleural_irritation', 'mech_pleural_effusion'],
    phenotypes: ['phen_pleuritic_cough', 'phen_productive_with_fever', 'phen_constitutional'],
    symptoms: [
      { symptomId: 'fever', frequency: 'always' }, { symptomId: 'chest_pain', frequency: 'always' },
      { symptomId: 'dyspnea', frequency: 'always' }, { symptomId: 'cough', frequency: 'common' },
      { symptomId: 'weight_loss', frequency: 'common' },
    ],
    signs: [
      { signId: 'fever_sign', frequency: 'always' }, { signId: 'dull_percussion', frequency: 'always' },
      { signId: 'reduced_breath_sounds', frequency: 'always' }, { signId: 'tachypnea', frequency: 'common' },
    ],
    riskFactors: ['pneumonia', 'lung_abscess', 'thoracic_surgery', 'trauma', 'immunosuppression', 'diabetes'],
    etiologies: ['streptococcus_milleri', 'staphylococcus_aureus', 'anaerobes', 'tuberculosis'],
    complications: ['bronchopleural_fistula', 'restrictive_lung_disease', 'sepsis', 'chest_wall_infection'],
    investigations: [
      { investigationId: 'inv_cxr', purpose: 'Pleural effusion', timing: 'initial' },
      { investigationId: 'inv_ct_chest', purpose: 'Characterize empyema', timing: 'initial' },
      { investigationId: 'inv_pleural_ultrasound', purpose: 'Guide thoracentesis', timing: 'initial' },
      { investigationId: 'inv_pleural_fluid_analysis', purpose: 'Confirm empyema', timing: 'initial' },
      { investigationId: 'inv_pleural_fluid_culture', purpose: 'Identify organism', timing: 'initial' },
    ],
    treatments: [
      { treatmentId: 'tx_chest_drain_insertion', firstLine: true },
      { treatmentId: 'tx_antibiotics_prolonged', firstLine: true },
      { treatmentId: 'tx_video_assisted_thoracoscopic_surgery', firstLine: false },
      { treatmentId: 'tx_decortication', firstLine: false },
    ],
    guidelines: ['guideline_bts_pleural_infection'],
    scores: ['score_rapid'],
    monitoring: ['drain_output', 'temperature_trend', 'crp_trend', 'cxr_resolution'],
    differentials: ['disease_cap', 'disease_pulmonary_tuberculosis', 'disease_lung_abscess', 'disease_malignant_pleural_effusion'],
  },
  {
    id: 'disease_influenza', name: 'Influenza', icd10: 'J10', snomed: '6142004',
    synonyms: ['Seasonal flu', 'Influenza virus infection'],
    specialty: ['infectious_disease', 'pulmonology', 'internal_medicine'],
    emergencyLevel: 'orange',
    mechanisms: ['mech_influenza_viral', 'mech_airway_inflammation'],
    phenotypes: ['phen_acute_productive', 'phen_dry_cough', 'phen_constitutional'],
    symptoms: [
      { symptomId: 'fever', frequency: 'always' }, { symptomId: 'cough', frequency: 'always' },
      { symptomId: 'myalgia', frequency: 'always' }, { symptomId: 'sore_throat', frequency: 'common' },
      { symptomId: 'headache', frequency: 'common' }, { symptomId: 'fatigue', frequency: 'always' },
    ],
    signs: [
      { signId: 'fever_sign', frequency: 'always' }, { signId: 'pharyngeal_erythema', frequency: 'common' },
      { signId: 'crackles', frequency: 'uncommon' },
    ],
    riskFactors: ['age_>65', 'pregnancy', 'obesity', 'chronic_lung_disease', 'immunosuppression', 'healthcare_worker'],
    etiologies: ['influenza_a', 'influenza_b', 'influenza_c'],
    complications: ['pneumonia_viral', 'pneumonia_bacterial', 'acute_respiratory_distress', 'myocarditis', 'encephalitis', 'death'],
    investigations: [
      { investigationId: 'inv_np_swab_pcr', purpose: 'Influenza PCR', timing: 'initial' },
      { investigationId: 'inv_rapid_antigen', purpose: 'Rapid influenza test', timing: 'initial' },
      { investigationId: 'inv_cxr', purpose: 'Assess for pneumonia', timing: 'initial' },
    ],
    treatments: [
      { treatmentId: 'tx_oseltamivir', firstLine: true },
      { treatmentId: 'tx_supportive_care', firstLine: true },
      { treatmentId: 'tx_oxygen_therapy', firstLine: false },
    ],
    guidelines: ['guideline_who_influenza', 'guideline_cdc_influenza'],
    scores: [],
    monitoring: ['oxygen_saturation', 'temperature', 'symptom_progression'],
    differentials: ['disease_covid19', 'disease_cap', 'disease_viral_urti', 'disease_acute_bronchitis'],
  },
  {
    id: 'disease_aspiration_pneumonia', name: 'Aspiration Pneumonia', icd10: 'J69.0', snomed: '36955009',
    synonyms: ['Aspiration pneumonitis', 'Chemical pneumonitis'],
    specialty: ['pulmonology', 'intensive_care', 'internal_medicine'],
    emergencyLevel: 'orange',
    mechanisms: ['mech_aspiration_chemical', 'mech_alveolar_filling'],
    phenotypes: ['phen_aspiration_syndrome', 'phen_acute_onset', 'phen_productive_with_fever'],
    symptoms: [
      { symptomId: 'cough', frequency: 'always' }, { symptomId: 'fever', frequency: 'common' },
      { symptomId: 'dyspnea', frequency: 'common' }, { symptomId: 'dysphagia', frequency: 'common' },
    ],
    signs: [
      { signId: 'crackles', frequency: 'always' }, { signId: 'fever_sign', frequency: 'common' },
      { signId: 'hypoxia', frequency: 'common' }, { signId: 'tachypnea', frequency: 'common' },
    ],
    riskFactors: ['stroke', 'dementia', 'seizure', 'alcohol_intoxication', 'general_anesthesia', 'gerd', 'neurological_dysphagia'],
    etiologies: ['anaerobic_bacteria', 'gram_negative_bacilli', 'streptococcus', 'aspiration_of_gastric_contents'],
    complications: ['lung_abscess', 'empyema', 'bronchopleural_fistula', 'respiratory_failure', 'ards'],
    investigations: [
      { investigationId: 'inv_cxr', purpose: 'Infiltrate in dependent segments', timing: 'initial' },
      { investigationId: 'inv_ct_chest', purpose: 'Characterize aspiration', timing: 'initial' },
      { investigationId: 'inv_swallow_assessment', purpose: 'Assess swallowing function', timing: 'initial' },
    ],
    treatments: [
      { treatmentId: 'tx_antibiotics_anaerobic', firstLine: true },
      { treatmentId: 'tx_supportive_care', firstLine: true },
      { treatmentId: 'tx_aspiration_precautions', firstLine: true },
      { treatmentId: 'tx_enteral_feeding_plan', firstLine: false },
    ],
    guidelines: ['guideline_aspiration_pneumonia'],
    scores: [],
    monitoring: ['oxygen_saturation', 'swallowing_function', 'recurrent_aspiration_episodes'],
    differentials: ['disease_cap', 'disease_lung_abscess', 'disease_gerd', 'disease_pulmonary_edema'],
  },
  {
    id: 'disease_invasive_aspergillosis', name: 'Invasive Aspergillosis', icd10: 'B44', snomed: '186576006',
    synonyms: ['Aspergillus pneumonia', 'Angioinvasive aspergillosis'],
    specialty: ['infectious_disease', 'pulmonology', 'hematology'],
    emergencyLevel: 'red',
    mechanisms: ['mech_fungal_invasion', 'mech_consolidation_cavitation'],
    phenotypes: ['phen_fungal_cough', 'phen_hemoptysis', 'phen_immunocompromised_cough'],
    symptoms: [
      { symptomId: 'fever', frequency: 'always' }, { symptomId: 'cough', frequency: 'always' },
      { symptomId: 'hemoptysis', frequency: 'common' }, { symptomId: 'chest_pain', frequency: 'common' },
      { symptomId: 'dyspnea', frequency: 'common' },
    ],
    signs: [
      { signId: 'fever_sign', frequency: 'always' }, { signId: 'crackles', frequency: 'common' },
      { signId: 'pleural_rub', frequency: 'uncommon' },
    ],
    riskFactors: ['neutropenia', 'hematological_malignancy', 'stem_cell_transplant', 'prolonged_steroids', 'immunosuppression'],
    etiologies: ['aspergillus_fumigatus', 'aspergillus_flavus', 'aspergillus_niger'],
    complications: ['massive_hemoptysis', 'disseminated_aspergillosis', 'respiratory_failure', 'bronchopleural_fistula'],
    investigations: [
      { investigationId: 'inv_ct_chest', purpose: 'Halo sign, air crescent sign', timing: 'initial' },
      { investigationId: 'inv_galactomannan', purpose: 'Serum or BAL galactomannan', timing: 'initial' },
      { investigationId: 'inv_beta_d_glucan', purpose: 'Fungal marker', timing: 'initial' },
      { investigationId: 'inv_bronchoscopy_bal', purpose: 'Bronchoalveolar lavage for culture', timing: 'confirmatory' },
      { investigationId: 'inv_lung_biopsy', purpose: 'Histological confirmation', timing: 'confirmatory' },
    ],
    treatments: [
      { treatmentId: 'tx_voriconazole', firstLine: true },
      { treatmentId: 'tx_amphotericin_b', firstLine: false },
      { treatmentId: 'tx_echinocandin', firstLine: false },
    ],
    guidelines: ['guideline_escmid_fungal', 'guideline_ats_fungal'],
    scores: [],
    monitoring: ['galactomannan_trend', 'ct_chest_follow_up', 'renal_function', 'liver_function'],
    differentials: ['disease_pulmonary_tuberculosis', 'disease_cap', 'disease_pcp', 'disease_lung_cancer'],
  },
  {
    id: 'disease_pcp', name: 'Pneumocystis Jirovecii Pneumonia', icd10: 'B59', snomed: '57524000',
    synonyms: ['PCP', 'Pneumocystis pneumonia'],
    specialty: ['infectious_disease', 'pulmonology', 'hiv_medicine'],
    emergencyLevel: 'red',
    mechanisms: ['mech_fungal_invasion', 'mech_alveolar_filling'],
    phenotypes: ['phen_immunocompromised_cough', 'phen_dry_cough', 'phen_fungal_cough'],
    symptoms: [
      { symptomId: 'dyspnea', frequency: 'always' }, { symptomId: 'cough', frequency: 'always' },
      { symptomId: 'fever', frequency: 'always' }, { symptomId: 'fatigue', frequency: 'common' },
    ],
    signs: [
      { signId: 'tachypnea', frequency: 'always' }, { signId: 'hypoxia', frequency: 'always' },
      { signId: 'crackles', frequency: 'common' }, { signId: 'fever_sign', frequency: 'always' },
    ],
    riskFactors: ['hiv_with_low_cd4', 'organ_transplant', 'hematological_malignancy', 'prolonged_steroids', 'immunosuppression'],
    etiologies: ['pneumocystis_jirovecii'],
    complications: ['respiratory_failure', 'pneumothorax', 'ards', 'death'],
    investigations: [
      { investigationId: 'inv_cxr', purpose: 'Bilateral interstitial infiltrates', timing: 'initial' },
      { investigationId: 'inv_ct_chest', purpose: 'Ground glass opacities', timing: 'initial' },
      { investigationId: 'inv_bronchoscopy_bal', purpose: 'Identify P. jirovecii', timing: 'initial' },
      { investigationId: 'inv_beta_d_glucan', purpose: 'Elevated in PCP', timing: 'initial' },
      { investigationId: 'inv_hiv_test', purpose: 'Rule out HIV', timing: 'initial' },
    ],
    treatments: [
      { treatmentId: 'tx_tmp_smx', firstLine: true },
      { treatmentId: 'tx_steroids_pcp', firstLine: true },
      { treatmentId: 'tx_pentamidine', firstLine: false },
    ],
    guidelines: ['guideline_who_pcp', 'guideline_ats_pcp'],
    scores: [],
    monitoring: ['oxygen_saturation', 'cxr_resolution', 'cd4_count', 'arterial_blood_gas'],
    differentials: ['disease_cap', 'disease_pulmonary_tuberculosis', 'disease_invasive_aspergillosis', 'disease_viral_pneumonia'],
  },
  {
    id: 'disease_histoplasmosis', name: 'Pulmonary Histoplasmosis', icd10: 'B39', snomed: '38205000',
    synonyms: ['Histoplasma pneumonia', 'Ohio Valley disease'],
    specialty: ['infectious_disease', 'pulmonology'],
    emergencyLevel: 'yellow',
    mechanisms: ['mech_fungal_invasion', 'mech_granulomatous'],
    phenotypes: ['phen_fungal_cough', 'phen_chronic_productive', 'phen_constitutional'],
    symptoms: [
      { symptomId: 'fever', frequency: 'always' }, { symptomId: 'cough', frequency: 'always' },
      { symptomId: 'chest_pain', frequency: 'common' }, { symptomId: 'weight_loss', frequency: 'common' },
    ],
    signs: [
      { signId: 'fever_sign', frequency: 'always' }, { signId: 'crackles', frequency: 'common' },
      { signId: 'lymphadenopathy', frequency: 'common' },
    ],
    riskFactors: ['travel_to_endemic_area', 'immunosuppression', 'exposure_to_bat_or_bird_droppings'],
    etiologies: ['histoplasma_capsulatum'],
    complications: ['chronic_cavitary_histoplasmosis', 'mediastinal_fibrosis', 'pericarditis', 'disseminated_disease'],
    investigations: [
      { investigationId: 'inv_ct_chest', purpose: 'Granulomatous nodules, cavitation', timing: 'initial' },
      { investigationId: 'inv_histoplasma_antigen', purpose: 'Urine or serum antigen', timing: 'initial' },
      { investigationId: 'inv_bronchoscopy_bal', purpose: 'Fungal culture', timing: 'confirmatory' },
    ],
    treatments: [
      { treatmentId: 'tx_itrazonazole', firstLine: true },
      { treatmentId: 'tx_amphotericin_b', firstLine: false },
    ],
    guidelines: ['guideline_ats_fungal'],
    scores: [],
    monitoring: ['antigen_levels', 'cxr_follow_up', 'symptom_resolution'],
    differentials: ['disease_pulmonary_tuberculosis', 'disease_sarcoidosis', 'disease_lung_cancer', 'disease_cap'],
  },
];
