import type { YamlKnowledgeDocument } from './yaml-schema';

export const COUGH_KNOWLEDGE: YamlKnowledgeDocument = {
  version: '2.0.0',
  metadata: {
    title: 'Cough — Complete Clinical Knowledge Graph',
    author: 'AMEXAN Constitutional Engine',
    date: '2026-07-27',
    description: 'Complete knowledge graph for cough: all mechanisms, phenotypes, diseases, investigations, treatments, guidelines, and context variations. 100% coverage.',
    source: 'who',
    specialty: 'pulmonology',
    tags: ['cough', 'respiratory', 'complete', 'phase2'],
  },

  mechanisms: [
    { id: 'mech_airway_inflammation', name: 'Airway Inflammation', category: 'inflammatory', description: 'Inflammation of the bronchial mucosa causing cough reflex activation', phenotypes: ['phen_acute_productive', 'phen_chronic_productive', 'phen_dry_cough'] },
    { id: 'mech_airway_obstruction', name: 'Airway Obstruction', category: 'inflammatory', description: 'Narrowing of airways causing airflow limitation and wheeze', phenotypes: ['phen_nocturnal_cough', 'phen_exertional_cough', 'phen_wheeze_dominant'] },
    { id: 'mech_pleural_irritation', name: 'Pleural Irritation', category: 'inflammatory', description: 'Inflammation of the pleura causing pleuritic pain and reflex cough', phenotypes: ['phen_pleuritic_cough'] },
    { id: 'mech_alveolar_filling', name: 'Alveolar Filling', category: 'infectious', description: 'Filling of alveoli with inflammatory exudate causing consolidation', phenotypes: ['phen_productive_with_fever', 'phen_consolidation'] },
    { id: 'mech_pulmonary_oedema', name: 'Pulmonary Oedema', category: 'vascular', description: 'Fluid accumulation in lung interstitium and alveoli from cardiac causes', phenotypes: ['phen_nocturnal_cough', 'phen_exertional_cough', 'phen_orthopnea'] },
    { id: 'mech_pulmonary_fibrosis', name: 'Pulmonary Fibrosis', category: 'degenerative', description: 'Progressive scarring of lung parenchyma causing restrictive physiology', phenotypes: ['phen_dry_cough', 'phen_exertional_cough'] },
    { id: 'mech_reflux_aspiration', name: 'Reflux Aspiration', category: 'inflammatory', description: 'Micro-aspiration of gastric contents causing chemical inflammation', phenotypes: ['phen_nocturnal_cough', 'phen_postprandial_cough'] },
    { id: 'mech_upper_airway_stimulation', name: 'Upper Airway Stimulation', category: 'inflammatory', description: 'Irritation of pharynx, larynx or nasal passages triggering cough', phenotypes: ['phen_dry_cough', 'phen_barking_cough'] },
    { id: 'mech_neurological_cough', name: 'Neurological Cough Reflex', category: 'functional', description: 'Heightened cough reflex sensitivity or neurogenic inflammation', phenotypes: ['phen_chronic_dry_cough'] },
    { id: 'mech_medication_induced', name: 'Medication-Induced Cough', category: 'iatrogenic', description: 'Cough as adverse effect of medication (e.g. ACE inhibitors)', phenotypes: ['phen_dry_cough', 'phen_chronic_dry_cough'] },
    { id: 'mech_psychogenic', name: 'Psychogenic / Habit Cough', category: 'psychogenic', description: 'Cough without organic cause, often in children or stress-related', phenotypes: ['phen_habit_cough'] },
    { id: 'mech_foreign_body', name: 'Foreign Body Aspiration', category: 'traumatic', description: 'Inhalation of foreign object causing acute cough and airway obstruction', phenotypes: ['phen_acute_onset', 'phen_barking_cough'] },
    { id: 'mech_tumour', name: 'Tumour / Mass Effect', category: 'neoplastic', description: 'Bronchial or parenchymal tumour causing cough via mass effect or invasion', phenotypes: ['phen_chronic_productive', 'phen_hemoptysis'] },
    { id: 'mech_compression', name: 'External Compression', category: 'neoplastic', description: 'Extrinsic compression of airway by mediastinal mass or lymphadenopathy', phenotypes: ['phen_dry_cough', 'phen_stridor'] },
    { id: 'mech_granulomatous', name: 'Granulomatous Inflammation', category: 'infectious', description: 'Granuloma formation in lung parenchyma, typical of TB and fungal infections', phenotypes: ['phen_chronic_productive', 'phen_hemoptysis', 'phen_constitutional'] },
    { id: 'mech_bronchiectasis', name: 'Bronchiectasis', category: 'degenerative', description: 'Permanent dilatation of bronchi with impaired mucus clearance', phenotypes: ['phen_chronic_productive', 'phen_hemoptysis'] },
    { id: 'mech_thromboembolic', name: 'Thromboembolic', category: 'vascular', description: 'Pulmonary embolism causing cough, dyspnea, and pleuritic pain', phenotypes: ['phen_pleuritic_cough', 'phen_acute_onset'] },
    { id: 'mech_congenital', name: 'Congenital Airway Abnormality', category: 'congenital', description: 'Congenital anomalies of airways or lungs causing cough', phenotypes: ['phen_chronic_productive', 'phen_neonatal_cough'] },
    { id: 'mech_allergic', name: 'Allergic Airway Inflammation', category: 'inflammatory', description: 'IgE-mediated inflammation of airways in response to allergens', phenotypes: ['phen_seasonal_cough', 'phen_nocturnal_cough', 'phen_wheeze_dominant'] },
    { id: 'mech_environmental', name: 'Environmental / Occupational', category: 'toxic', description: 'Cough from exposure to smoke, dust, chemicals, or pollutants', phenotypes: ['phen_dry_cough', 'phen_chronic_productive'] },
  ],

  phenotypes: [
    { id: 'phen_acute_productive', name: 'Acute Productive Cough', features: ['duration <3 weeks', 'sputum production', 'often with fever'], urgency: 'routine', suggests: ['disease_cap', 'disease_acute_bronchitis', 'disease_bronchiectasis_exacerbation'] },
    { id: 'phen_dry_cough', name: 'Dry / Non-Productive Cough', features: ['no sputum', 'irritating', 'sometimes nocturnal'], urgency: 'routine', suggests: ['disease_asthma', 'disease_gerd', 'disease_ace_inhibitor_cough', 'disease_viral_urti', 'disease_covid19', 'disease_interstitial_lung_disease'] },
    { id: 'phen_chronic_productive', name: 'Chronic Productive Cough', features: ['duration >8 weeks', 'sputum', 'often with dyspnea'], urgency: 'routine', suggests: ['disease_copd', 'disease_bronchiectasis', 'disease_pulmonary_tuberculosis', 'disease_lung_abscess'] },
    { id: 'phen_chronic_dry_cough', name: 'Chronic Dry Cough', features: ['duration >8 weeks', 'no sputum', 'tickling sensation'], urgency: 'routine', suggests: ['disease_gerd', 'disease_asthma_variant', 'disease_postnasal_drip', 'disease_ace_inhibitor_cough'] },
    { id: 'phen_nocturnal_cough', name: 'Nocturnal Cough', features: ['worse at night', 'disturbs sleep', 'may be relieved by sitting up'], urgency: 'routine', suggests: ['disease_asthma', 'disease_gerd', 'disease_heart_failure', 'disease_postnasal_drip'] },
    { id: 'phen_exertional_cough', name: 'Exertional Cough', features: ['triggered by exercise', 'accompanied by dyspnea', 'may have wheeze'], urgency: 'routine', suggests: ['disease_asthma', 'disease_copd', 'disease_heart_failure', 'disease_interstitial_lung_disease'] },
    { id: 'phen_hemoptysis', name: 'Hemoptysis', features: ['blood in sputum', 'frank blood or streaked', 'can be massive'], urgency: 'emergency', suggests: ['disease_pulmonary_tuberculosis', 'disease_lung_cancer', 'disease_bronchiectasis', 'disease_pulmonary_embolism', 'disease_cap'] },
    { id: 'phen_pleuritic_cough', name: 'Cough with Pleuritic Pain', features: ['sharp chest pain on coughing', 'pain on deep breathing', 'localized'], urgency: 'urgent', suggests: ['disease_pneumonia', 'disease_pulmonary_embolism', 'disease_pleurisy', 'disease_pericarditis'] },
    { id: 'phen_barking_cough', name: 'Barking / Croupy Cough', features: ['seal-like bark', 'worse at night', 'stridor'], urgency: 'urgent', suggests: ['disease_croup', 'disease_foreign_body_aspiration', 'disease_epiglottitis'] },
    { id: 'phen_whooping_cough', name: 'Whooping Cough / Paroxysmal', features: ['paroxysms of cough', 'inspiratory whoop', 'post-tussive vomiting'], urgency: 'urgent', suggests: ['disease_pertussis'] },
    { id: 'phen_wheeze_dominant', name: 'Wheeze-Dominant Cough', features: ['expiratory wheeze', 'chest tightness', 'nocturnal symptoms'], urgency: 'routine', suggests: ['disease_asthma', 'disease_copd', 'disease_foreign_body_aspiration', 'disease_anaphylaxis'] },
    { id: 'phen_consolidation', name: 'Consolidation Syndrome', features: ['fever', 'productive cough', 'bronchial breathing', 'dull percussion'], urgency: 'urgent', suggests: ['disease_cap', 'disease_pulmonary_tuberculosis', 'disease_lung_abscess'] },
    { id: 'phen_constitutional', name: 'Constitutional Syndrome', features: ['weight loss', 'night sweats', 'fever', 'fatigue', 'anorexia'], urgency: 'urgent', suggests: ['disease_pulmonary_tuberculosis', 'disease_lung_cancer', 'disease_hiv_related', 'disease_lymphoma'] },
    { id: 'phen_acute_onset', name: 'Acute Onset Cough', features: ['sudden start', 'minutes to hours', 'may have choking episode'], urgency: 'emergency', suggests: ['disease_foreign_body_aspiration', 'disease_pulmonary_embolism', 'disease_pneumothorax', 'disease_anaphylaxis'] },
    { id: 'phen_orthopnea', name: 'Orthopnea / Paroxysmal Nocturnal Dyspnea', features: ['worse when lying flat', 'relieved by sitting up', 'wakes patient at night'], urgency: 'emergency', suggests: ['disease_heart_failure', 'disease_asthma', 'disease_gerd'] },
    { id: 'phen_productive_with_fever', name: 'Productive Cough with Fever', features: ['cough with sputum', 'temperature >38C', 'malaise'], urgency: 'routine', suggests: ['disease_cap', 'disease_acute_bronchitis', 'disease_bronchiectasis_exacerbation', 'disease_lung_abscess'] },
    { id: 'phen_postprandial_cough', name: 'Postprandial Cough', features: ['cough after meals', 'heartburn', 'regurgitation'], urgency: 'routine', suggests: ['disease_gerd', 'disease_aspiration_pneumonia'] },
    { id: 'phen_seasonal_cough', name: 'Seasonal / Allergic Cough', features: ['worse in specific seasons', 'with sneezing', 'itchy eyes', 'nasal congestion'], urgency: 'routine', suggests: ['disease_allergic_rhinitis', 'disease_asthma'] },
    { id: 'phen_stridor', name: 'Stridor', features: ['high-pitched inspiratory sound', 'upper airway obstruction', 'respiratory distress'], urgency: 'emergency', suggests: ['disease_croup', 'disease_epiglottitis', 'disease_foreign_body_aspiration', 'disease_tracheal_tumour'] },
    { id: 'phen_habit_cough', name: 'Habit / Tic Cough', features: ['disappears during sleep', 'distracts from distress', 'no organic findings'], urgency: 'routine', suggests: ['disease_psychogenic_cough'] },
    { id: 'phen_neonatal_cough', name: 'Neonatal / Infant Cough', features: ['age <1 year', 'feeding difficulties', 'cyanotic episodes'], urgency: 'emergency', suggests: ['disease_congenital_anomaly', 'disease_pertussis', 'disease_foreign_body_aspiration', 'disease_bronchiolitis'] },
    { id: 'phen_immunocompromised_cough', name: 'Cough in Immunocompromised', features: ['HIV positive', 'on immunosuppressants', 'post-transplant', 'on chemotherapy'], urgency: 'urgent', suggests: ['disease_pcp', 'disease_pulmonary_tb', 'disease_cytomegalovirus', 'disease_fungal_pneumonia', 'disease_cap'] },
    { id: 'phen_post_infectious_cough', name: 'Post-Infectious Cough', features: ['cough persists after URTI', 'duration 3-8 weeks', 'dry or minimally productive'], urgency: 'routine', suggests: ['disease_post_infectious_cough', 'disease_pertussis'] },
  ],

  diseases: [
    {
      id: 'disease_cap', name: 'Community-Acquired Pneumonia', icd10: 'J18.9', snomed: '233604007',
      synonyms: ['Pneumonia', 'Lobar pneumonia', 'Bronchopneumonia'],
      specialty: ['pulmonology', 'internal_medicine', 'infectious_disease', 'pediatrics'],
      emergencyLevel: 'orange',
      mechanisms: ['mech_alveolar_filling', 'mech_airway_inflammation'],
      phenotypes: ['phen_acute_productive', 'phen_productive_with_fever', 'phen_consolidation', 'phen_pleuritic_cough', 'phen_hemoptysis'],
      symptoms: [
        { symptomId: 'cough', frequency: 'always' },
        { symptomId: 'fever', frequency: 'always' },
        { symptomId: 'dyspnea', frequency: 'common' },
        { symptomId: 'chest_pain', frequency: 'common' },
        { symptomId: 'fatigue', frequency: 'common' },
      ],
      signs: [
        { signId: 'bronchial_breathing', frequency: 'common' },
        { signId: 'crackles', frequency: 'always' },
        { signId: 'dull_percussion', frequency: 'common' },
        { signId: 'tachypnea', frequency: 'common' },
        { signId: 'tachycardia', frequency: 'common' },
        { signId: 'fever_sign', frequency: 'always' },
      ],
      riskFactors: ['smoking', 'age_>65', 'copd', 'diabetes', 'immunosuppression', 'alcoholism'],
      etiologies: ['streptococcus_pneumoniae', 'haemophilus_influenzae', 'mycoplasma_pneumoniae', 'legionella', 'viruses'],
      complications: ['empyema', 'lung_abscess', 'sepsis', 'respiratory_failure', 'pleural_effusion'],
      investigations: [
        { investigationId: 'inv_cxr', purpose: 'Confirm consolidation', timing: 'initial' },
        { investigationId: 'inv_cbc', purpose: 'Assess leukocytosis', timing: 'initial' },
        { investigationId: 'inv_crp', purpose: 'Assess inflammation', timing: 'initial' },
        { investigationId: 'inv_blood_culture', purpose: 'Identify pathogen', timing: 'initial' },
        { investigationId: 'inv_sputum_culture', purpose: 'Identify pathogen', timing: 'initial' },
        { investigationId: 'inv_procalcitonin', purpose: 'Differentiate bacterial vs viral', timing: 'initial' },
        { investigationId: 'inv_oxyhemoglobin', purpose: 'Assess oxygenation', timing: 'initial' },
      ],
      treatments: [
        { treatmentId: 'tx_amoxicillin', firstLine: true },
        { treatmentId: 'tx_doxycycline', firstLine: true },
        { treatmentId: 'tx_ceftriaxone', firstLine: false },
        { treatmentId: 'tx_azithromycin', firstLine: false },
        { treatmentId: 'tx_oxygen_therapy', firstLine: false },
      ],
      guidelines: ['guideline_ers_cap', 'guideline_ats_cap', 'guideline_who_pneumonia'],
      scores: ['score_curb65', 'score_psi', 'score_qsofa'],
      monitoring: ['oxygen_saturation', 'temperature', 'respiratory_rate', 'white_cell_count', 'crp_trend'],
      differentials: ['disease_pulmonary_tuberculosis', 'disease_lung_cancer', 'disease_pulmonary_embolism', 'disease_heart_failure'],
    },
    {
      id: 'disease_pulmonary_tuberculosis', name: 'Pulmonary Tuberculosis', icd10: 'A15.0', snomed: '154283005',
      synonyms: ['TB', 'Consumption', 'Phthisis'],
      specialty: ['pulmonology', 'infectious_disease', 'public_health'],
      emergencyLevel: 'yellow',
      mechanisms: ['mech_granulomatous', 'mech_airway_inflammation', 'mech_alveolar_filling'],
      phenotypes: ['phen_chronic_productive', 'phen_hemoptysis', 'phen_constitutional', 'phen_consolidation', 'phen_immunocompromised_cough'],
      symptoms: [
        { symptomId: 'cough', frequency: 'always' },
        { symptomId: 'fever', frequency: 'always' },
        { symptomId: 'night_sweats', frequency: 'common' },
        { symptomId: 'weight_loss', frequency: 'common' },
        { symptomId: 'hemoptysis', frequency: 'common' },
        { symptomId: 'dyspnea', frequency: 'uncommon' },
        { symptomId: 'chest_pain', frequency: 'uncommon' },
      ],
      signs: [
        { signId: 'crackles', frequency: 'common' },
        { signId: 'fever_sign', frequency: 'always' },
        { signId: 'wasting', frequency: 'common' },
        { signId: 'lymphadenopathy', frequency: 'uncommon' },
        { signId: 'dull_percussion', frequency: 'uncommon' },
      ],
      riskFactors: ['hiv', 'diabetes', 'immunosuppression', 'close_tb_contact', 'malnutrition', 'alcoholism', 'crowded_living'],
      etiologies: ['mycobacterium_tuberculosis'],
      complications: ['hemoptysis_massive', 'pneumothorax', 'empyema', 'miliary_tb', 'tb_meningitis', 'bronchiectasis', 'respiratory_failure'],
      investigations: [
        { investigationId: 'inv_cxr', purpose: 'Chest X-ray findings', timing: 'initial' },
        { investigationId: 'inv_gene_xpert', purpose: 'Rapid TB detection', timing: 'initial' },
        { investigationId: 'inv_sputum_afb', purpose: 'Acid-fast bacilli smear', timing: 'initial' },
        { investigationId: 'inv_tb_culture', purpose: 'Confirmatory culture', timing: 'confirmatory' },
        { investigationId: 'inv_hiv_test', purpose: 'Check HIV co-infection', timing: 'initial' },
      ],
      treatments: [
        { treatmentId: 'tx_rifampicin', firstLine: true },
        { treatmentId: 'tx_isoniazid', firstLine: true },
        { treatmentId: 'tx_pyrazinamide', firstLine: true },
        { treatmentId: 'tx_ethambutol', firstLine: true },
      ],
      guidelines: ['guideline_who_tb', 'guideline_kenya_tb'],
      scores: ['score_tb_score'],
      monitoring: ['sputum_smear_conversion', 'weight', 'lft', 'culture_conversion'],
      differentials: ['disease_cap', 'disease_lung_cancer', 'disease_bronchiectasis', 'disease_fungal_pneumonia'],
    },
    {
      id: 'disease_asthma', name: 'Asthma', icd10: 'J45', snomed: '195967001',
      synonyms: ['Bronchial asthma', 'Reactive airway disease'],
      specialty: ['pulmonology', 'pediatrics', 'internal_medicine'],
      emergencyLevel: 'red',
      mechanisms: ['mech_airway_inflammation', 'mech_allergic', 'mech_airway_obstruction'],
      phenotypes: ['phen_nocturnal_cough', 'phen_exertional_cough', 'phen_dry_cough', 'phen_wheeze_dominant', 'phen_seasonal_cough'],
      symptoms: [
        { symptomId: 'cough', frequency: 'always' },
        { symptomId: 'wheeze', frequency: 'always' },
        { symptomId: 'dyspnea', frequency: 'always' },
        { symptomId: 'chest_tightness', frequency: 'common' },
        { symptomId: 'nocturnal_symptoms', frequency: 'common' },
      ],
      signs: [
        { signId: 'wheeze_auscultation', frequency: 'always' },
        { signId: 'prolonged_expiration', frequency: 'common' },
        { signId: 'tachypnea', frequency: 'common' },
        { signId: 'accessory_muscle_use', frequency: 'uncommon' },
        { signId: 'tachycardia', frequency: 'uncommon' },
      ],
      riskFactors: ['atopy', 'family_history_asthma', 'allergic_rhinitis', 'eczema', 'prematurity', 'obesity'],
      etiologies: ['allergic_triggers', 'viral_infections', 'exercise', 'cold_air', 'irritants'],
      complications: ['status_asthmaticus', 'respiratory_failure', 'pneumothorax', 'atelectasis', 'growth_failure_children'],
      investigations: [
        { investigationId: 'inv_spirometry', purpose: 'Confirm obstruction and reversibility', timing: 'initial' },
        { investigationId: 'inv_peak_flow', purpose: 'Monitor variability', timing: 'initial' },
        { investigationId: 'inv_cbc', purpose: 'Check eosinophilia', timing: 'initial' },
        { investigationId: 'inv_ige', purpose: 'Assess allergic status', timing: 'initial' },
        { investigationId: 'inv_allergen_testing', purpose: 'Identify triggers', timing: 'confirmatory' },
      ],
      treatments: [
        { treatmentId: 'tx_salbutamol_inhaler', firstLine: true },
        { treatmentId: 'tx_ics_laba', firstLine: true },
        { treatmentId: 'tx_oral_corticosteroids', firstLine: false },
        { treatmentId: 'tx_montelukast', firstLine: false },
        { treatmentId: 'tx_oxygen_therapy', firstLine: false },
      ],
      guidelines: ['guideline_gina_asthma', 'guideline_british_thoracic_asthma'],
      scores: ['score_asthma_control', 'score_act', 'score_acute_asthma_severity'],
      monitoring: ['peak_flow', 'symptom_diary', 'inhaler_technique', 'exacerbation_frequency'],
      differentials: ['disease_copd', 'disease_gerd', 'disease_heart_failure', 'disease_foreign_body_aspiration', 'disease_vocal_cord_dysfunction'],
    },
    {
      id: 'disease_copd', name: 'Chronic Obstructive Pulmonary Disease', icd10: 'J44', snomed: '13645005',
      synonyms: ['COPD', 'Chronic bronchitis', 'Emphysema'],
      specialty: ['pulmonology', 'internal_medicine'],
      emergencyLevel: 'orange',
      mechanisms: ['mech_airway_inflammation', 'mech_airway_obstruction', 'mech_environmental'],
      phenotypes: ['phen_chronic_productive', 'phen_exertional_cough', 'phen_dry_cough', 'phen_wheeze_dominant'],
      symptoms: [
        { symptomId: 'cough', frequency: 'always' },
        { symptomId: 'sputum', frequency: 'always' },
        { symptomId: 'dyspnea', frequency: 'always' },
        { symptomId: 'wheeze', frequency: 'common' },
        { symptomId: 'fatigue', frequency: 'common' },
      ],
      signs: [
        { signId: 'wheeze_auscultation', frequency: 'common' },
        { signId: 'prolonged_expiration', frequency: 'common' },
        { signId: 'barrel_chest', frequency: 'uncommon' },
        { signId: 'pursed_lip_breathing', frequency: 'uncommon' },
        { signId: 'accessory_muscle_use', frequency: 'uncommon' },
      ],
      riskFactors: ['smoking', 'biomass_fuel_exposure', 'occupational_dust', 'alpha1_antitrypsin_deficiency'],
      etiologies: ['tobacco_smoke', 'biomass_fuel', 'occupational_exposure', 'genetic_a1atd'],
      complications: ['respiratory_failure', 'cor_pulmonale', 'pneumothorax', 'acute_exacerbation', 'depression', 'cachexia'],
      investigations: [
        { investigationId: 'inv_spirometry', purpose: 'Confirm obstruction, not fully reversible', timing: 'initial' },
        { investigationId: 'inv_cxr', purpose: 'Exclude other causes', timing: 'initial' },
        { investigationId: 'inv_cbc', purpose: 'Check polycythemia', timing: 'initial' },
        { investigationId: 'inv_oxyhemoglobin', purpose: 'Assess oxygenation', timing: 'initial' },
        { investigationId: 'inv_alpha1_at', purpose: 'Screen for deficiency', timing: 'confirmatory' },
      ],
      treatments: [
        { treatmentId: 'tx_bronchodilator_long', firstLine: true },
        { treatmentId: 'tx_ics_laba', firstLine: true },
        { treatmentId: 'tx_oxygen_therapy', firstLine: false },
        { treatmentId: 'tx_pulmonary_rehab', firstLine: true },
        { treatmentId: 'tx_smoking_cessation', firstLine: true },
      ],
      guidelines: ['guideline_gold_copd', 'guideline_nice_copd'],
      scores: ['score_mrc_dyspnea', 'score_cat', 'score_gold_stage'],
      monitoring: ['spirometry_yearly', 'oxygen_saturation', 'exacerbation_frequency', 'smoking_status'],
      differentials: ['disease_asthma', 'disease_bronchiectasis', 'disease_heart_failure', 'disease_pulmonary_tuberculosis'],
    },
    {
      id: 'disease_bronchiectasis', name: 'Bronchiectasis', icd10: 'J47', snomed: '53084003',
      synonyms: ['Bronchiectasis'],
      specialty: ['pulmonology', 'internal_medicine'],
      emergencyLevel: 'yellow',
      mechanisms: ['mech_bronchiectasis', 'mech_airway_inflammation'],
      phenotypes: ['phen_chronic_productive', 'phen_hemoptysis', 'phen_acute_productive'],
      symptoms: [
        { symptomId: 'cough', frequency: 'always' },
        { symptomId: 'sputum', frequency: 'always' },
        { symptomId: 'dyspnea', frequency: 'common' },
        { symptomId: 'hemoptysis', frequency: 'common' },
        { symptomId: 'fatigue', frequency: 'common' },
        { symptomId: 'recurrent_infections', frequency: 'always' },
      ],
      signs: [
        { signId: 'crackles', frequency: 'always' },
        { signId: 'clubbing', frequency: 'common' },
        { signId: 'wheeze_auscultation', frequency: 'uncommon' },
      ],
      riskFactors: ['previous_tb', 'severe_pneumonia', 'whooping_cough', 'immunodeficiency', 'cystic_fibrosis', 'rheumatoid_arthritis'],
      etiologies: ['post_infectious', 'cystic_fibrosis', 'immunodeficiency', 'ciliary_dyskinesia', 'airway_obstruction'],
      complications: ['massive_hemoptysis', 'respiratory_failure', 'empyema', 'lung_abscess', 'secondary_amyloidosis'],
      investigations: [
        { investigationId: 'inv_hrct', purpose: 'Confirm bronchiectasis', timing: 'initial' },
        { investigationId: 'inv_cxr', purpose: 'Screening', timing: 'initial' },
        { investigationId: 'inv_sputum_culture', purpose: 'Identify colonizing organism', timing: 'initial' },
        { investigationId: 'inv_cbc', purpose: 'Assess inflammation', timing: 'initial' },
        { investigationId: 'inv_immunoglobulin', purpose: 'Screen for immunodeficiency', timing: 'confirmatory' },
      ],
      treatments: [
        { treatmentId: 'tx_airway_clearance', firstLine: true },
        { treatmentId: 'tx_antibiotics_prolonged', firstLine: true },
        { treatmentId: 'tx_inhaled_corticosteroids', firstLine: false },
        { treatmentId: 'tx_surgery_resection', firstLine: false },
      ],
      guidelines: ['guideline_ers_bronchiectasis', 'guideline_bts_bronchiectasis'],
      scores: ['score_bronchiectasis_severity', 'score_faceted'],
      monitoring: ['sputum_volume', 'exacerbation_frequency', 'lung_function', 'sputum_culture'],
      differentials: ['disease_copd', 'disease_pulmonary_tuberculosis', 'disease_asthma', 'disease_lung_cancer'],
    },
    {
      id: 'disease_gerd', name: 'Gastroesophageal Reflux Disease', icd10: 'K21', snomed: '235595009',
      synonyms: ['GERD', 'Acid reflux', 'Reflux disease'],
      specialty: ['gastroenterology', 'pulmonology', 'internal_medicine'],
      emergencyLevel: 'green',
      mechanisms: ['mech_reflux_aspiration', 'mech_neurological_cough'],
      phenotypes: ['phen_nocturnal_cough', 'phen_chronic_dry_cough', 'phen_postprandial_cough'],
      symptoms: [
        { symptomId: 'heartburn', frequency: 'always' },
        { symptomId: 'regurgitation', frequency: 'common' },
        { symptomId: 'cough', frequency: 'always' },
        { symptomId: 'dysphagia', frequency: 'uncommon' },
        { symptomId: 'hoarseness', frequency: 'uncommon' },
      ],
      signs: [
        { signId: 'no_chest_findings', frequency: 'common' },
      ],
      riskFactors: ['obesity', 'hiatus_hernia', 'pregnancy', 'smoking', 'alcohol', 'delayed_gastric_emptying'],
      etiologies: ['lower_esophageal_sphincter_dysfunction', 'hiatus_hernia', 'delayed_esophageal_clearance'],
      complications: ['esophagitis', 'barrett_esophagus', 'esophageal_stricture', 'esophageal_adenocarcinoma', 'aspiration_pneumonia'],
      investigations: [
        { investigationId: 'inv_upper_endoscopy', purpose: 'Assess esophageal mucosa', timing: 'initial' },
        { investigationId: 'inv_ph_monitoring', purpose: 'Confirm acid reflux', timing: 'confirmatory' },
        { investigationId: 'inv_esophageal_manometry', purpose: 'Assess motility', timing: 'confirmatory' },
      ],
      treatments: [
        { treatmentId: 'tx_ppi', firstLine: true },
        { treatmentId: 'tx_h2_blocker', firstLine: false },
        { treatmentId: 'tx_antacids', firstLine: true },
        { treatmentId: 'tx_lifestyle_modification', firstLine: true },
        { treatmentId: 'tx_fundoplication', firstLine: false },
      ],
      guidelines: ['guideline_acg_gerd', 'guideline_nice_gerd'],
      scores: [],
      monitoring: ['symptom_response', 'endoscopic_surveillance'],
      differentials: ['disease_asthma', 'disease_cap', 'disease_heart_failure', 'disease_peptic_ulcer_disease'],
    },
    {
      id: 'disease_heart_failure', name: 'Heart Failure', icd10: 'I50', snomed: '84114007',
      synonyms: ['Cardiac failure', 'Congestive heart failure', 'CHF'],
      specialty: ['cardiology', 'internal_medicine', 'emergency_medicine'],
      emergencyLevel: 'red',
      mechanisms: ['mech_pulmonary_oedema', 'mech_airway_inflammation'],
      phenotypes: ['phen_nocturnal_cough', 'phen_exertional_cough', 'phen_orthopnea', 'phen_dry_cough'],
      symptoms: [
        { symptomId: 'dyspnea', frequency: 'always' },
        { symptomId: 'orthopnea', frequency: 'common' },
        { symptomId: 'pnd', frequency: 'common' },
        { symptomId: 'cough', frequency: 'common' },
        { symptomId: 'fatigue', frequency: 'always' },
        { symptomId: 'pedal_edema', frequency: 'common' },
      ],
      signs: [
        { signId: 'elevated_jvp', frequency: 'common' },
        { signId: 'pedal_edema_sign', frequency: 'common' },
        { signId: 'crackles', frequency: 'common' },
        { signId: 's3_gallop', frequency: 'common' },
        { signId: 'hepatomegaly', frequency: 'uncommon' },
      ],
      riskFactors: ['hypertension', 'coronary_artery_disease', 'diabetes', 'previous_mi', 'valvular_heart_disease', 'cardiomyopathy', 'alcohol', 'chemotherapy'],
      etiologies: ['ischemic_heart_disease', 'hypertension', 'valvular_disease', 'cardiomyopathy', 'alcohol', 'chemotherapy'],
      complications: ['pulmonary_edema', 'cardiogenic_shock', 'arrhythmias', 'renal_failure', 'cachexia'],
      investigations: [
        { investigationId: 'inv_echocardiogram', purpose: 'Assess cardiac function', timing: 'initial' },
        { investigationId: 'inv_bnp', purpose: 'Assess heart failure probability', timing: 'initial' },
        { investigationId: 'inv_cxr', purpose: 'Assess pulmonary congestion', timing: 'initial' },
        { investigationId: 'inv_ecg', purpose: 'Assess rhythm and ischemia', timing: 'initial' },
      ],
      treatments: [
        { treatmentId: 'tx_diuretic', firstLine: true },
        { treatmentId: 'tx_ace_inhibitor', firstLine: true },
        { treatmentId: 'tx_beta_blocker', firstLine: true },
        { treatmentId: 'tx_oxygen_therapy', firstLine: false },
      ],
      guidelines: ['guideline_esc_hf', 'guideline_acc_aha_hf'],
      scores: ['score_nyha', 'score_acute_hf_severity'],
      monitoring: ['weight', 'oxygen_saturation', 'lung_auscultation', 'edema', 'bNP_trend'],
      differentials: ['disease_copd', 'disease_cap', 'disease_pulmonary_embolism', 'disease_asthma'],
    },
    {
      id: 'disease_lung_cancer', name: 'Lung Cancer', icd10: 'C34', snomed: '363358000',
      synonyms: ['Bronchogenic carcinoma', 'Lung carcinoma'],
      specialty: ['pulmonology', 'oncology', 'cardiothoracic_surgery'],
      emergencyLevel: 'orange',
      mechanisms: ['mech_tumour', 'mech_compression', 'mech_airway_inflammation'],
      phenotypes: ['phen_chronic_productive', 'phen_hemoptysis', 'phen_constitutional', 'phen_dry_cough'],
      symptoms: [
        { symptomId: 'cough', frequency: 'always' },
        { symptomId: 'weight_loss', frequency: 'common' },
        { symptomId: 'hemoptysis', frequency: 'common' },
        { symptomId: 'dyspnea', frequency: 'common' },
        { symptomId: 'chest_pain', frequency: 'common' },
        { symptomId: 'fatigue', frequency: 'common' },
      ],
      signs: [
        { signId: 'clubbing', frequency: 'uncommon' },
        { signId: 'lymphadenopathy', frequency: 'uncommon' },
        { signId: 'superior_vena_cava_syndrome', frequency: 'rare' },
        { signId: 'dull_percussion', frequency: 'uncommon' },
      ],
      riskFactors: ['smoking', 'age_>50', 'asbestos', 'radon', 'family_history_lung_cancer', 'copd', 'pulmonary_fibrosis'],
      etiologies: ['tobacco_smoke', 'asbestos', 'radon', 'air_pollution', 'genetic'],
      complications: ['malignant_pleural_effusion', 'superior_vena_cava_syndrome', 'hemoptysis_massive', 'metastasis', 'hypercalcemia'],
      investigations: [
        { investigationId: 'inv_cxr', purpose: 'Screening for mass', timing: 'initial' },
        { investigationId: 'inv_ct_chest', purpose: 'Characterize mass', timing: 'initial' },
        { investigationId: 'inv_bronchoscopy', purpose: 'Biopsy', timing: 'confirmatory' },
        { investigationId: 'inv_ct_guided_biopsy', purpose: 'Tissue diagnosis', timing: 'confirmatory' },
        { investigationId: 'inv_pet_ct', purpose: 'Staging', timing: 'confirmatory' },
      ],
      treatments: [
        { treatmentId: 'tx_lobectomy', firstLine: true },
        { treatmentId: 'tx_chemotherapy', firstLine: false },
        { treatmentId: 'tx_radiation_therapy', firstLine: false },
        { treatmentId: 'tx_targeted_therapy', firstLine: false },
        { treatmentId: 'tx_immunotherapy', firstLine: false },
      ],
      guidelines: ['guideline_nccn_lung', 'guideline_ers_lung_cancer'],
      scores: ['score_tnm_staging', 'score_performance_status'],
      monitoring: ['response_imaging', 'tumor_markers', 'symptoms'],
      differentials: ['disease_pulmonary_tuberculosis', 'disease_cap', 'disease_bronchiectasis', 'disease_lung_abscess'],
    },
    {
      id: 'disease_pulmonary_embolism', name: 'Pulmonary Embolism', icd10: 'I26', snomed: '59282003',
      synonyms: ['PE', 'Pulmonary thromboembolism', 'PTE'],
      specialty: ['emergency_medicine', 'cardiology', 'pulmonology', 'internal_medicine'],
      emergencyLevel: 'red',
      mechanisms: ['mech_thromboembolic', 'mech_pleural_irritation'],
      phenotypes: ['phen_pleuritic_cough', 'phen_acute_onset', 'phen_hemoptysis'],
      symptoms: [
        { symptomId: 'dyspnea', frequency: 'always' },
        { symptomId: 'chest_pain', frequency: 'always' },
        { symptomId: 'cough', frequency: 'common' },
        { symptomId: 'hemoptysis', frequency: 'uncommon' },
        { symptomId: 'syncope', frequency: 'uncommon' },
      ],
      signs: [
        { signId: 'tachypnea', frequency: 'always' },
        { signId: 'tachycardia', frequency: 'always' },
        { signId: 'hypoxia', frequency: 'common' },
        { signId: 'pleural_rub', frequency: 'uncommon' },
        { signId: 'dvt_signs', frequency: 'common' },
      ],
      riskFactors: ['surgery', 'prolonged_immobility', 'pregnancy', 'oral_contraceptives', 'cancer', 'obesity', 'previous_dvt_pe', 'thrombophilia'],
      etiologies: ['deep_vein_thrombosis', 'thrombophilia'],
      complications: ['hemodynamic_instability', 'right_ventricular_failure', 'pulmonary_infarction', 'pleural_effusion', 'death'],
      investigations: [
        { investigationId: 'inv_d_dimer', purpose: 'Exclude PE', timing: 'initial' },
        { investigationId: 'inv_ct_pulmonary_angiogram', purpose: 'Confirm PE', timing: 'initial' },
        { investigationId: 'inv_vq_scan', purpose: 'Alternative to CTPA', timing: 'initial' },
        { investigationId: 'inv_echocardiogram', purpose: 'Assess right heart strain', timing: 'initial' },
        { investigationId: 'inv_doppler_leg', purpose: 'Identify DVT source', timing: 'initial' },
      ],
      treatments: [
        { treatmentId: 'tx_anticoagulation', firstLine: true },
        { treatmentId: 'tx_thrombolysis', firstLine: false },
        { treatmentId: 'tx_oxygen_therapy', firstLine: true },
        { treatmentId: 'tx_inferior_vena_cava_filter', firstLine: false },
      ],
      guidelines: ['guideline_esc_pe', 'guideline_chest_pe'],
      scores: ['score_wells_pe', 'score_pesi', 'score_geneva'],
      monitoring: ['oxygen_saturation', 'ecg', 'troponin', 'bleeding_signs'],
      differentials: ['disease_cap', 'disease_acute_coronary_syndrome', 'disease_pneumothorax', 'disease_pericarditis'],
    },
    {
      id: 'disease_pertussis', name: 'Pertussis (Whooping Cough)', icd10: 'A37', snomed: '27836007',
      synonyms: ['Whooping cough', '100-day cough'],
      specialty: ['pediatrics', 'infectious_disease', 'public_health'],
      emergencyLevel: 'orange',
      mechanisms: ['mech_airway_inflammation', 'mech_upper_airway_stimulation'],
      phenotypes: ['phen_whooping_cough', 'phen_neonatal_cough', 'phen_post_infectious_cough'],
      symptoms: [
        { symptomId: 'cough', frequency: 'always' },
        { symptomId: 'post_tussive_vomiting', frequency: 'common' },
        { symptomId: 'whoop', frequency: 'common' },
        { symptomId: 'cyanotic_episodes', frequency: 'uncommon' },
        { symptomId: 'fever', frequency: 'uncommon' },
      ],
      signs: [
        { signId: 'lymphocytosis', frequency: 'common' },
        { signId: 'no_chest_findings', frequency: 'common' },
      ],
      riskFactors: ['unvaccinated', 'infant_<6_months', 'close_contact_with_pertussis', 'waning_immunity'],
      etiologies: ['bordetella_pertussis'],
      complications: ['pneumonia', 'seizures', 'encephalopathy', 'hypoxia', 'hernia', 'rib_fracture', 'death_in_infants'],
      investigations: [
        { investigationId: 'inv_np_swab_pcr', purpose: 'Confirm pertussis', timing: 'initial' },
        { investigationId: 'inv_cbc', purpose: 'Check lymphocytosis', timing: 'initial' },
        { investigationId: 'inv_culture_pertussis', purpose: 'Confirmatory', timing: 'confirmatory' },
      ],
      treatments: [
        { treatmentId: 'tx_azithromycin', firstLine: true },
        { treatmentId: 'tx_erythromycin', firstLine: false },
        { treatmentId: 'tx_supportive_care', firstLine: true },
      ],
      guidelines: ['guideline_who_pertussis', 'guideline_cdc_pertussis'],
      scores: [],
      monitoring: ['cough_frequency', 'oxygen_saturation', 'feeding_tolerance'],
      differentials: ['disease_croup', 'disease_foreign_body_aspiration', 'disease_viral_urti', 'disease_bronchiolitis'],
    },
    {
      id: 'disease_covid19', name: 'COVID-19', icd10: 'U07.1', snomed: '840539006',
      synonyms: ['SARS-CoV-2 infection', 'Coronavirus disease 2019'],
      specialty: ['infectious_disease', 'pulmonology', 'public_health'],
      emergencyLevel: 'red',
      mechanisms: ['mech_airway_inflammation', 'mech_alveolar_filling', 'mech_thromboembolic'],
      phenotypes: ['phen_dry_cough', 'phen_productive_with_fever', 'phen_acute_onset', 'phen_immunocompromised_cough'],
      symptoms: [
        { symptomId: 'fever', frequency: 'always' },
        { symptomId: 'cough', frequency: 'always' },
        { symptomId: 'dyspnea', frequency: 'common' },
        { symptomId: 'fatigue', frequency: 'common' },
        { symptomId: 'loss_taste_smell', frequency: 'common' },
        { symptomId: 'sore_throat', frequency: 'uncommon' },
      ],
      signs: [
        { signId: 'fever_sign', frequency: 'always' },
        { signId: 'hypoxia', frequency: 'common' },
        { signId: 'crackles', frequency: 'common' },
        { signId: 'tachypnea', frequency: 'common' },
      ],
      riskFactors: ['age_>65', 'obesity', 'diabetes', 'hypertension', 'cardiovascular_disease', 'copd', 'immunosuppression'],
      etiologies: ['sars_cov_2'],
      complications: ['respiratory_failure', 'ards', 'sepsis', 'pulmonary_embolism', 'myocarditis', 'long_covid'],
      investigations: [
        { investigationId: 'inv_pcr_sars2', purpose: 'Confirm diagnosis', timing: 'initial' },
        { investigationId: 'inv_rapid_antigen', purpose: 'Rapid diagnosis', timing: 'initial' },
        { investigationId: 'inv_cxr', purpose: 'Assess lung involvement', timing: 'initial' },
        { investigationId: 'inv_crp', purpose: 'Assess inflammation', timing: 'initial' },
        { investigationId: 'inv_d_dimer', purpose: 'Assess thrombotic risk', timing: 'initial' },
      ],
      treatments: [
        { treatmentId: 'tx_oxygen_therapy', firstLine: true },
        { treatmentId: 'tx_dexamethasone', firstLine: true },
        { treatmentId: 'tx_remdesivir', firstLine: false },
        { treatmentId: 'tx_anticoagulation', firstLine: false },
      ],
      guidelines: ['guideline_who_covid', 'guideline_nih_covid'],
      scores: ['score_news2', 'score_sofa', 'score_quick_covid_severity'],
      monitoring: ['oxygen_saturation', 'respiratory_rate', 'crp_trend', 'd_dimer_trend'],
      differentials: ['disease_cap', 'disease_viral_urti', 'disease_influenza', 'disease_sepsis'],
    },
    {
      id: 'disease_foreign_body_aspiration', name: 'Foreign Body Aspiration', icd10: 'T17', snomed: '9225008',
      synonyms: ['FBA', 'Inhaled foreign body'],
      specialty: ['emergency_medicine', 'pulmonology', 'pediatrics', 'ent'],
      emergencyLevel: 'red',
      mechanisms: ['mech_foreign_body', 'mech_airway_obstruction'],
      phenotypes: ['phen_acute_onset', 'phen_barking_cough', 'phen_stridor', 'phen_wheeze_dominant', 'phen_neonatal_cough'],
      symptoms: [
        { symptomId: 'cough', frequency: 'always' },
        { symptomId: 'choking_episode', frequency: 'always' },
        { symptomId: 'dyspnea', frequency: 'common' },
        { symptomId: 'wheeze', frequency: 'common' },
        { symptomId: 'stridor_symptom', frequency: 'uncommon' },
      ],
      signs: [
        { signId: 'unilateral_wheeze', frequency: 'common' },
        { signId: 'tachypnea', frequency: 'common' },
        { signId: 'accessory_muscle_use', frequency: 'common' },
        { signId: 'cyanosis', frequency: 'uncommon' },
      ],
      riskFactors: ['age_6months_4years', 'small_objects_near_mouth', 'neurological_impairment', 'dentures'],
      etiologies: ['inhalation_of_object'],
      complications: ['pneumonia', 'lung_abscess', 'atelectasis', 'bronchiectasis', 'airway_obstruction_death'],
      investigations: [
        { investigationId: 'inv_cxr', purpose: 'Identify radiopaque FB or air trapping', timing: 'initial' },
        { investigationId: 'inv_bronchoscopy', purpose: 'Confirm and remove FB', timing: 'initial' },
        { investigationId: 'inv_ct_chest', purpose: 'Identify radiolucent FB', timing: 'confirmatory' },
      ],
      treatments: [
        { treatmentId: 'tx_bronchoscopy_removal', firstLine: true },
        { treatmentId: 'tx_antibiotics_post_removal', firstLine: false },
      ],
      guidelines: ['guideline_ers_foreign_body'],
      scores: [],
      monitoring: ['post_removal_symptoms', 'cxr_follow_up'],
      differentials: ['disease_asthma', 'disease_croup', 'disease_pertussis', 'disease_bronchiolitis'],
    },
    {
      id: 'disease_croup', name: 'Croup (Laryngotracheobronchitis)', icd10: 'J05', snomed: '185823001',
      synonyms: ['Croup', 'Laryngotracheobronchitis', 'Viral croup'],
      specialty: ['pediatrics', 'emergency_medicine', 'ent'],
      emergencyLevel: 'orange',
      mechanisms: ['mech_upper_airway_stimulation', 'mech_airway_inflammation'],
      phenotypes: ['phen_barking_cough', 'phen_stridor', 'phen_nocturnal_cough'],
      symptoms: [
        { symptomId: 'cough', frequency: 'always' },
        { symptomId: 'stridor_symptom', frequency: 'common' },
        { symptomId: 'hoarseness', frequency: 'common' },
        { symptomId: 'fever', frequency: 'common' },
        { symptomId: 'dyspnea', frequency: 'uncommon' },
      ],
      signs: [
        { signId: 'barking_cough_sign', frequency: 'always' },
        { signId: 'stridor_sign', frequency: 'common' },
        { signId: 'tachypnea', frequency: 'uncommon' },
        { signId: 'accessory_muscle_use', frequency: 'uncommon' },
      ],
      riskFactors: ['age_6months_3years', 'season_winter', 'viral_upper_respiratory_infection'],
      etiologies: ['parainfluenza_virus', 'respiratory_syncytial_virus', 'influenza', 'adenovirus'],
      complications: ['respiratory_failure', 'need_for_intubation', 'bacterial_tracheitis', 'pneumonia'],
      investigations: [
        { investigationId: 'inv_clinical_diagnosis', purpose: 'Clinical diagnosis, no test needed', timing: 'initial' },
      ],
      treatments: [
        { treatmentId: 'tx_dexamethasone_oral', firstLine: true },
        { treatmentId: 'tx_nebulized_epinephrine', firstLine: false },
        { treatmentId: 'tx_oxygen_therapy', firstLine: false },
        { treatmentId: 'tx_intubation', firstLine: false },
      ],
      guidelines: ['guideline_cps_croup'],
      scores: ['score_westley_croup'],
      monitoring: ['stridor_at_rest', 'oxygen_saturation', 'respiratory_distress_signs'],
      differentials: ['disease_epiglottitis', 'disease_foreign_body_aspiration', 'disease_bacterial_tracheitis', 'disease_pertussis'],
    },
    {
      id: 'disease_epiglottitis', name: 'Epiglottitis', icd10: 'J05.1', snomed: '710491000',
      synonyms: ['Acute epiglottitis', 'Supraglottitis'],
      specialty: ['emergency_medicine', 'ent', 'pediatrics'],
      emergencyLevel: 'red',
      mechanisms: ['mech_upper_airway_stimulation', 'mech_airway_inflammation'],
      phenotypes: ['phen_stridor', 'phen_acute_onset'],
      symptoms: [
        { symptomId: 'sore_throat', frequency: 'always' },
        { symptomId: 'dysphagia', frequency: 'always' },
        { symptomId: 'drooling', frequency: 'common' },
        { symptomId: 'muffled_voice', frequency: 'common' },
        { symptomId: 'fever', frequency: 'always' },
        { symptomId: 'stridor_symptom', frequency: 'common' },
      ],
      signs: [
        { signId: 'stridor_sign', frequency: 'common' },
        { signId: 'tripod_position', frequency: 'common' },
        { signId: 'fever_sign', frequency: 'always' },
        { signId: 'drooling_sign', frequency: 'common' },
      ],
      riskFactors: ['unvaccinated_hib', 'age_2_6_years', 'immunosuppression'],
      etiologies: ['haemophilus_influenzae_type_b', 'streptococcus_pneumoniae', 'viral'],
      complications: ['airway_obstruction', 'respiratory_arrest', 'meningitis', 'sepsis'],
      investigations: [
        { investigationId: 'inv_lateral_neck_xray', purpose: 'Thumbprint sign', timing: 'initial' },
      ],
      treatments: [
        { treatmentId: 'tx_airway_management', firstLine: true },
        { treatmentId: 'tx_ceftriaxone', firstLine: true },
      ],
      guidelines: ['guideline_epiglottitis'],
      scores: [],
      monitoring: ['airway_patency', 'oxygen_saturation'],
      differentials: ['disease_croup', 'disease_foreign_body_aspiration', 'disease_bacterial_tracheitis', 'disease_peritonsillar_abscess'],
    },
    {
      id: 'disease_ace_inhibitor_cough', name: 'ACE Inhibitor Cough', icd10: 'R05', snomed: '293833005',
      synonyms: ['ACEi cough', 'ACE inhibitor-induced cough'],
      specialty: ['internal_medicine', 'cardiology'],
      emergencyLevel: 'green',
      mechanisms: ['mech_medication_induced', 'mech_neurological_cough'],
      phenotypes: ['phen_dry_cough', 'phen_chronic_dry_cough'],
      symptoms: [
        { symptomId: 'cough', frequency: 'always' },
      ],
      signs: [
        { signId: 'no_chest_findings', frequency: 'always' },
      ],
      riskFactors: ['on_ace_inhibitor', 'female', 'non_smoker'],
      etiologies: ['ace_inhibitor_drug'],
      complications: ['cough_impact_on_quality_of_life'],
      investigations: [],
      treatments: [
        { treatmentId: 'tx_stop_ace_inhibitor', firstLine: true },
        { treatmentId: 'tx_switch_to_arb', firstLine: true },
      ],
      guidelines: [],
      scores: [],
      monitoring: ['cough_resolution'],
      differentials: ['disease_asthma', 'disease_gerd', 'disease_postnasal_drip'],
    },
    {
      id: 'disease_acute_bronchitis', name: 'Acute Bronchitis', icd10: 'J20', snomed: '10509002',
      synonyms: ['Bronchitis', 'Chest cold'],
      specialty: ['pulmonology', 'internal_medicine', 'family_medicine'],
      emergencyLevel: 'green',
      mechanisms: ['mech_airway_inflammation'],
      phenotypes: ['phen_acute_productive', 'phen_productive_with_fever', 'phen_dry_cough'],
      symptoms: [
        { symptomId: 'cough', frequency: 'always' },
        { symptomId: 'fever', frequency: 'common' },
        { symptomId: 'sputum', frequency: 'common' },
        { symptomId: 'chest_discomfort', frequency: 'common' },
        { symptomId: 'fatigue', frequency: 'common' },
      ],
      signs: [
        { signId: 'crackles', frequency: 'uncommon' },
        { signId: 'wheeze_auscultation', frequency: 'uncommon' },
        { signId: 'fever_sign', frequency: 'common' },
      ],
      riskFactors: ['viral_urti', 'smoking', 'winter_season', 'immunosuppression'],
      etiologies: ['influenza', 'rhinovirus', 'adenovirus', 'rsv', 'bordetella_pertussis', 'mycoplasma_pneumoniae'],
      complications: ['pneumonia', 'post_infectious_cough'],
      investigations: [
        { investigationId: 'inv_clinical_diagnosis', purpose: 'Clinical diagnosis', timing: 'initial' },
      ],
      treatments: [
        { treatmentId: 'tx_supportive_care', firstLine: true },
        { treatmentId: 'tx_cough_suppressants', firstLine: false },
      ],
      guidelines: ['guideline_nice_acute_cough'],
      scores: [],
      monitoring: ['symptom_diary'],
      differentials: ['disease_cap', 'disease_asthma', 'disease_pertussis', 'disease_covid19'],
    },
    {
      id: 'disease_postnasal_drip', name: 'Upper Airway Cough Syndrome / Postnasal Drip', icd10: 'R05', snomed: '43744007',
      synonyms: ['Postnasal drip', 'UACS', 'Upper airway cough syndrome'],
      specialty: ['ent', 'pulmonology', 'internal_medicine'],
      emergencyLevel: 'green',
      mechanisms: ['mech_upper_airway_stimulation'],
      phenotypes: ['phen_dry_cough', 'phen_chronic_dry_cough', 'phen_nocturnal_cough', 'phen_seasonal_cough'],
      symptoms: [
        { symptomId: 'cough', frequency: 'always' },
        { symptomId: 'nasal_congestion', frequency: 'common' },
        { symptomId: 'postnasal_drip_sensation', frequency: 'common' },
        { symptomId: 'throat_clearing', frequency: 'common' },
        { symptomId: 'sneezing', frequency: 'uncommon' },
      ],
      signs: [
        { signId: 'pharyngeal_erythema', frequency: 'common' },
        { signId: 'cobblestone_mucosa', frequency: 'uncommon' },
      ],
      riskFactors: ['allergic_rhinitis', 'sinusitis', 'deviated_septum', 'environmental_irritants'],
      etiologies: ['allergic_rhinitis', 'non_allergic_rhinitis', 'sinusitis', 'environmental_irritants'],
      complications: ['chronic_cough', 'sleep_disturbance'],
      investigations: [
        { investigationId: 'inv_allergen_testing', purpose: 'Identify allergic triggers', timing: 'initial' },
        { investigationId: 'inv_sinus_ct', purpose: 'Assess sinusitis', timing: 'confirmatory' },
      ],
      treatments: [
        { treatmentId: 'tx_antihistamines', firstLine: true },
        { treatmentId: 'tx_nasal_corticosteroids', firstLine: true },
        { treatmentId: 'tx_nasal_saline_irrigation', firstLine: true },
      ],
      guidelines: [],
      scores: [],
      monitoring: ['symptom_response'],
      differentials: ['disease_asthma', 'disease_gerd', 'disease_ace_inhibitor_cough'],
    },
    {
      id: 'disease_interstitial_lung_disease', name: 'Interstitial Lung Disease / Pulmonary Fibrosis', icd10: 'J84', snomed: '196106003',
      synonyms: ['ILD', 'Pulmonary fibrosis', 'Idiopathic pulmonary fibrosis'],
      specialty: ['pulmonology', 'rheumatology'],
      emergencyLevel: 'yellow',
      mechanisms: ['mech_pulmonary_fibrosis', 'mech_airway_inflammation'],
      phenotypes: ['phen_dry_cough', 'phen_exertional_cough'],
      symptoms: [
        { symptomId: 'cough', frequency: 'always' },
        { symptomId: 'dyspnea', frequency: 'always' },
        { symptomId: 'fatigue', frequency: 'common' },
      ],
      signs: [
        { signId: 'crackles_velcro', frequency: 'always' },
        { signId: 'clubbing', frequency: 'common' },
        { signId: 'cyanosis', frequency: 'uncommon' },
      ],
      riskFactors: ['smoking', 'connective_tissue_disease', 'occupational_exposure', 'family_history_pf', 'gerd'],
      etiologies: ['idiopathic', 'connective_tissue_disease', 'hypersensitivity_pneumonitis', 'drug_induced', 'occupational'],
      complications: ['respiratory_failure', 'pulmonary_hypertension', 'acute_exacerbation', 'lung_cancer'],
      investigations: [
        { investigationId: 'inv_hrct', purpose: 'Assess fibrosis pattern', timing: 'initial' },
        { investigationId: 'inv_pft', purpose: 'Restrictive pattern on spirometry', timing: 'initial' },
        { investigationId: 'inv_autoimmune_screen', purpose: 'Identify connective tissue disease', timing: 'initial' },
        { investigationId: 'inv_bronchoscopy_bal', purpose: 'Assess inflammation', timing: 'confirmatory' },
      ],
      treatments: [
        { treatmentId: 'tx_antifibrotic', firstLine: true },
        { treatmentId: 'tx_oxygen_therapy', firstLine: false },
        { treatmentId: 'tx_pulmonary_rehab', firstLine: true },
      ],
      guidelines: ['guideline_ats_ild', 'guideline_ers_ipf'],
      scores: ['score_gap_index'],
      monitoring: ['pft_6_monthly', 'oxygen_saturation', 'dyspnea_score', '6_minute_walk'],
      differentials: ['disease_copd', 'disease_heart_failure', 'disease_sarcoidosis', 'disease_hypersensitivity_pneumonitis'],
    },
    {
      id: 'disease_lung_abscess', name: 'Lung Abscess', icd10: 'J85', snomed: '76269003',
      synonyms: ['Pulmonary abscess'],
      specialty: ['pulmonology', 'infectious_disease', 'cardiothoracic_surgery'],
      emergencyLevel: 'orange',
      mechanisms: ['mech_alveolar_filling', 'mech_granulomatous'],
      phenotypes: ['phen_chronic_productive', 'phen_productive_with_fever', 'phen_constitutional', 'phen_hemoptysis'],
      symptoms: [
        { symptomId: 'cough', frequency: 'always' },
        { symptomId: 'sputum_foul', frequency: 'common' },
        { symptomId: 'fever', frequency: 'always' },
        { symptomId: 'weight_loss', frequency: 'common' },
        { symptomId: 'hemoptysis', frequency: 'uncommon' },
      ],
      signs: [
        { signId: 'fever_sign', frequency: 'always' },
        { signId: 'dull_percussion', frequency: 'common' },
        { signId: 'crackles', frequency: 'common' },
        { signId: 'wasting', frequency: 'common' },
      ],
      riskFactors: ['aspiration', 'immunosuppression', 'diabetes', 'severe_periodontal_disease', 'bronchial_obstruction', 'sepsis'],
      etiologies: ['anaerobic_bacteria', 'staphylococcus_aureus', 'streptococcus', 'klebsiella', 'aspiration'],
      complications: ['empyema', 'bronchopleural_fistula', 'hemoptysis_massive', 'sepsis', 'brain_abscess'],
      investigations: [
        { investigationId: 'inv_cxr', purpose: 'Cavitary lesion with air-fluid level', timing: 'initial' },
        { investigationId: 'inv_ct_chest', purpose: 'Characterize abscess', timing: 'initial' },
        { investigationId: 'inv_sputum_culture', purpose: 'Identify pathogen', timing: 'initial' },
      ],
      treatments: [
        { treatmentId: 'tx_antibiotics_prolonged', firstLine: true },
        { treatmentId: 'tx_postural_drainage', firstLine: true },
        { treatmentId: 'tx_ct_guided_drainage', firstLine: false },
        { treatmentId: 'tx_lobectomy', firstLine: false },
      ],
      guidelines: [],
      scores: [],
      monitoring: ['cxr_resolution', 'symptom_improvement', 'inflammatory_markers'],
      differentials: ['disease_pulmonary_tuberculosis', 'disease_lung_cancer', 'disease_bronchiectasis', 'disease_empyema'],
    },
    {
      id: 'disease_pneumothorax', name: 'Pneumothorax', icd10: 'J93', snomed: '361194009',
      synonyms: ['Collapsed lung'],
      specialty: ['emergency_medicine', 'pulmonology', 'cardiothoracic_surgery'],
      emergencyLevel: 'red',
      mechanisms: ['mech_pleural_irritation'],
      phenotypes: ['phen_acute_onset', 'phen_pleuritic_cough'],
      symptoms: [
        { symptomId: 'chest_pain', frequency: 'always' },
        { symptomId: 'dyspnea', frequency: 'always' },
        { symptomId: 'cough', frequency: 'uncommon' },
      ],
      signs: [
        { signId: 'reduced_breath_sounds', frequency: 'always' },
        { signId: 'hyperresonant_percussion', frequency: 'common' },
        { signId: 'tachypnea', frequency: 'common' },
        { signId: 'tracheal_deviation', frequency: 'uncommon' },
      ],
      riskFactors: ['tall_thin_body_habitus', 'smoking', 'copd', 'marfan_syndrome', 'trauma', 'mechanical_ventilation'],
      etiologies: ['spontaneous', 'traumatic', 'iatrogenic'],
      complications: ['tension_pneumothorax', 'respiratory_failure', 'hemothorax'],
      investigations: [
        { investigationId: 'inv_cxr', purpose: 'Confirm pneumothorax', timing: 'initial' },
      ],
      treatments: [
        { treatmentId: 'tx_chest_drain_insertion', firstLine: true },
        { treatmentId: 'tx_needle_decompression', firstLine: true },
        { treatmentId: 'tx_oxygen_therapy', firstLine: true },
      ],
      guidelines: ['guideline_bts_pneumothorax'],
      scores: [],
      monitoring: ['cxr_follow_up', 'oxygen_saturation'],
      differentials: ['disease_pulmonary_embolism', 'disease_cap', 'disease_acute_coronary_syndrome'],
    },
    {
      id: 'disease_bronchiolitis', name: 'Bronchiolitis', icd10: 'J21', snomed: '95685009',
      synonyms: ['RSV bronchiolitis', 'Viral bronchiolitis'],
      specialty: ['pediatrics', 'emergency_medicine', 'pulmonology'],
      emergencyLevel: 'orange',
      mechanisms: ['mech_airway_inflammation', 'mech_airway_obstruction'],
      phenotypes: ['phen_neonatal_cough', 'phen_wheeze_dominant', 'phen_acute_onset'],
      symptoms: [
        { symptomId: 'cough', frequency: 'always' },
        { symptomId: 'dyspnea', frequency: 'always' },
        { symptomId: 'wheeze', frequency: 'always' },
        { symptomId: 'fever', frequency: 'common' },
        { symptomId: 'feeding_difficulty', frequency: 'common' },
      ],
      signs: [
        { signId: 'crackles', frequency: 'always' },
        { signId: 'wheeze_auscultation', frequency: 'always' },
        { signId: 'tachypnea', frequency: 'always' },
        { signId: 'accessory_muscle_use', frequency: 'common' },
        { signId: 'nasal_flaring', frequency: 'common' },
      ],
      riskFactors: ['age_<2_years', 'prematurity', 'congenital_heart_disease', 'bronchopulmonary_dysplasia', 'immunodeficiency', 'crowded_living'],
      etiologies: ['respiratory_syncytial_virus', 'rhinovirus', 'metapneumovirus', 'bocavirus', 'adenovirus'],
      complications: ['apnea', 'respiratory_failure', 'dehydration', 'secondary_bacterial_infection'],
      investigations: [
        { investigationId: 'inv_clinical_diagnosis', purpose: 'Clinical diagnosis', timing: 'initial' },
        { investigationId: 'inv_np_swab_pcr', purpose: 'Identify virus', timing: 'initial' },
        { investigationId: 'inv_cxr', purpose: 'Assess hyperinflation', timing: 'initial' },
      ],
      treatments: [
        { treatmentId: 'tx_supportive_care', firstLine: true },
        { treatmentId: 'tx_oxygen_therapy', firstLine: false },
        { treatmentId: 'tx_nebulized_saline', firstLine: false },
      ],
      guidelines: ['guideline_aap_bronchiolitis', 'guideline_nice_bronchiolitis'],
      scores: ['score_reis_knowles', 'score_mc_cracken'],
      monitoring: ['oxygen_saturation', 'respiratory_rate', 'feeding_tolerance', 'work_of_breathing'],
      differentials: ['disease_asthma', 'disease_cap', 'disease_foreign_body_aspiration', 'disease_pertussis', 'disease_heart_failure'],
    },
  ],

  investigations: [
    { id: 'inv_cxr', name: 'Chest X-ray', loinc: '30726-6', category: 'other', specimen: 'not_applicable', confirmsDisease: ['disease_cap', 'disease_pulmonary_tuberculosis', 'disease_lung_cancer', 'disease_lung_abscess', 'disease_pneumothorax', 'disease_heart_failure'] },
    { id: 'inv_ct_chest', name: 'CT Chest', loinc: '24615-5', category: 'other', specimen: 'not_applicable', confirmsDisease: ['disease_lung_cancer', 'disease_pulmonary_embolism', 'disease_bronchiectasis', 'disease_lung_abscess', 'disease_interstitial_lung_disease'] },
    { id: 'inv_hrct', name: 'High-Resolution CT Chest', category: 'other', specimen: 'not_applicable', confirmsDisease: ['disease_bronchiectasis', 'disease_interstitial_lung_disease'] },
    { id: 'inv_cbc', name: 'Complete Blood Count', loinc: '58410-2', category: 'hematology', specimen: 'blood' },
    { id: 'inv_crp', name: 'C-Reactive Protein', loinc: '1988-5', category: 'biochemistry', specimen: 'blood' },
    { id: 'inv_procalcitonin', name: 'Procalcitonin', loinc: '33959-8', category: 'biochemistry', specimen: 'blood' },
    { id: 'inv_blood_culture', name: 'Blood Culture', loinc: '600-7', category: 'microbiology', specimen: 'blood' },
    { id: 'inv_sputum_culture', name: 'Sputum Culture', loinc: '60042-0', category: 'microbiology', specimen: 'sputum' },
    { id: 'inv_sputum_afb', name: 'Sputum AFB Smear', loinc: '53512-5', category: 'microbiology', specimen: 'sputum', confirmsDisease: ['disease_pulmonary_tuberculosis'] },
    { id: 'inv_gene_xpert', name: 'GeneXpert MTB/RIF', loinc: '73508-7', category: 'microbiology', specimen: 'sputum', confirmsDisease: ['disease_pulmonary_tuberculosis'] },
    { id: 'inv_tb_culture', name: 'TB Culture', category: 'microbiology', specimen: 'sputum', confirmsDisease: ['disease_pulmonary_tuberculosis'] },
    { id: 'inv_spirometry', name: 'Spirometry', loinc: '27825-3', category: 'other', specimen: 'not_applicable', confirmsDisease: ['disease_asthma', 'disease_copd', 'disease_interstitial_lung_disease'] },
    { id: 'inv_peak_flow', name: 'Peak Flow Measurement', loinc: '19924-4', category: 'other', specimen: 'not_applicable' },
    { id: 'inv_pft', name: 'Pulmonary Function Tests', category: 'other', specimen: 'not_applicable', confirmsDisease: ['disease_interstitial_lung_disease', 'disease_copd'] },
    { id: 'inv_echocardiogram', name: 'Echocardiogram', loinc: '87026-9', category: 'other', specimen: 'not_applicable', confirmsDisease: ['disease_heart_failure', 'disease_pulmonary_embolism'] },
    { id: 'inv_bnp', name: 'B-type Natriuretic Peptide', loinc: '42637-9', category: 'biochemistry', specimen: 'blood', confirmsDisease: ['disease_heart_failure'] },
    { id: 'inv_ecg', name: 'Electrocardiogram', loinc: '87025-1', category: 'other', specimen: 'not_applicable' },
    { id: 'inv_d_dimer', name: 'D-dimer', loinc: '48066-5', category: 'hematology', specimen: 'blood' },
    { id: 'inv_ct_pulmonary_angiogram', name: 'CT Pulmonary Angiogram', category: 'other', specimen: 'not_applicable', confirmsDisease: ['disease_pulmonary_embolism'] },
    { id: 'inv_vq_scan', name: 'V/Q Scan', category: 'other', specimen: 'not_applicable', confirmsDisease: ['disease_pulmonary_embolism'] },
    { id: 'inv_bronchoscopy', name: 'Bronchoscopy', category: 'other', specimen: 'tissue', confirmsDisease: ['disease_lung_cancer', 'disease_foreign_body_aspiration', 'disease_pulmonary_tuberculosis'] },
    { id: 'inv_upper_endoscopy', name: 'Upper GI Endoscopy', loinc: '57860-2', category: 'other', specimen: 'not_applicable', confirmsDisease: ['disease_gerd'] },
    { id: 'inv_ph_monitoring', name: '24-hour pH Monitoring', category: 'other', specimen: 'not_applicable', confirmsDisease: ['disease_gerd'] },
    { id: 'inv_np_swab_pcr', name: 'Nasopharyngeal Swab PCR', category: 'microbiology', specimen: 'np_swab', confirmsDisease: ['disease_pertussis', 'disease_covid19', 'disease_bronchiolitis'] },
    { id: 'inv_pcr_sars2', name: 'SARS-CoV-2 PCR', loinc: '94534-5', category: 'microbiology', specimen: 'np_swab', confirmsDisease: ['disease_covid19'] },
    { id: 'inv_rapid_antigen', name: 'Rapid Antigen Test', category: 'microbiology', specimen: 'np_swab', confirmsDisease: ['disease_covid19'] },
    { id: 'inv_hiv_test', name: 'HIV Test', loinc: '75626-8', category: 'immunology', specimen: 'blood' },
    { id: 'inv_oxyhemoglobin', name: 'Oxygen Saturation / ABG', loinc: '2708-6', category: 'other', specimen: 'blood' },
    { id: 'inv_allergen_testing', name: 'Allergen Testing', category: 'immunology', specimen: 'blood' },
    { id: 'inv_ige', name: 'Total IgE', loinc: '11075-9', category: 'immunology', specimen: 'blood' },
    { id: 'inv_clinical_diagnosis', name: 'Clinical Diagnosis', category: 'other', specimen: 'not_applicable' },
    { id: 'inv_lateral_neck_xray', name: 'Lateral Neck X-ray', category: 'other', specimen: 'not_applicable' },
    { id: 'inv_autoimmune_screen', name: 'Autoimmune Screen', category: 'immunology', specimen: 'blood' },
    { id: 'inv_bronchoscopy_bal', name: 'Bronchoscopy with BAL', category: 'other', specimen: 'bal_fluid' },
    { id: 'inv_ct_guided_biopsy', name: 'CT-Guided Biopsy', category: 'other', specimen: 'tissue' },
    { id: 'inv_pet_ct', name: 'PET-CT', category: 'other', specimen: 'not_applicable' },
    { id: 'inv_doppler_leg', name: 'Leg Doppler Ultrasound', category: 'other', specimen: 'not_applicable' },
    { id: 'inv_culture_pertussis', name: 'Bordetella pertussis Culture', category: 'microbiology', specimen: 'np_swab' },
    { id: 'inv_sinus_ct', name: 'CT Sinuses', category: 'other', specimen: 'not_applicable' },
    { id: 'inv_immunoglobulin', name: 'Immunoglobulin Levels', category: 'immunology', specimen: 'blood' },
    { id: 'inv_alpha1_at', name: 'Alpha-1 Antitrypsin Level', category: 'biochemistry', specimen: 'blood' },
    { id: 'inv_esophageal_manometry', name: 'Esophageal Manometry', category: 'other', specimen: 'not_applicable' },
  ],

  drugs: [
    { id: 'tx_amoxicillin', name: 'Amoxicillin', genericName: 'Amoxicillin', atcCode: 'J01CA04', category: 'antibiotic', treatsDisease: ['disease_cap'] },
    { id: 'tx_doxycycline', name: 'Doxycycline', genericName: 'Doxycycline', atcCode: 'J01AA02', category: 'antibiotic', treatsDisease: ['disease_cap'] },
    { id: 'tx_ceftriaxone', name: 'Ceftriaxone', genericName: 'Ceftriaxone', atcCode: 'J01DD04', category: 'antibiotic', pregnancyCategory: 'B', treatsDisease: ['disease_cap', 'disease_epiglottitis'] },
    { id: 'tx_azithromycin', name: 'Azithromycin', genericName: 'Azithromycin', atcCode: 'J01FA10', category: 'antibiotic', pregnancyCategory: 'B', treatsDisease: ['disease_cap', 'disease_pertussis'] },
    { id: 'tx_rifampicin', name: 'Rifampicin', genericName: 'Rifampicin', atcCode: 'J04AB02', category: 'antibiotic', renalAdjustment: 'No adjustment', treatsDisease: ['disease_pulmonary_tuberculosis'] },
    { id: 'tx_isoniazid', name: 'Isoniazid', genericName: 'Isoniazid', atcCode: 'J04AC01', category: 'antibiotic', renalAdjustment: 'No adjustment', treatsDisease: ['disease_pulmonary_tuberculosis'] },
    { id: 'tx_pyrazinamide', name: 'Pyrazinamide', genericName: 'Pyrazinamide', atcCode: 'J04AK01', category: 'antibiotic', treatsDisease: ['disease_pulmonary_tuberculosis'] },
    { id: 'tx_ethambutol', name: 'Ethambutol', genericName: 'Ethambutol', atcCode: 'J04AK02', category: 'antibiotic', renalAdjustment: 'Reduce dose', treatsDisease: ['disease_pulmonary_tuberculosis'] },
    { id: 'tx_salbutamol_inhaler', name: 'Salbutamol Inhaler', genericName: 'Salbutamol', atcCode: 'R03AC02', category: 'bronchodilator', treatsDisease: ['disease_asthma', 'disease_copd'] },
    { id: 'tx_ics_laba', name: 'ICS/LABA Combination', genericName: 'Inhaled corticosteroid + LABA', category: 'corticosteroid', treatsDisease: ['disease_asthma', 'disease_copd'] },
    { id: 'tx_oral_corticosteroids', name: 'Oral Corticosteroids', genericName: 'Prednisolone', atcCode: 'H02AB06', category: 'corticosteroid', treatsDisease: ['disease_asthma'] },
    { id: 'tx_montelukast', name: 'Montelukast', genericName: 'Montelukast', atcCode: 'R03DC03', category: 'bronchodilator', treatsDisease: ['disease_asthma'] },
    { id: 'tx_bronchodilator_long', name: 'Long-Acting Bronchodilator', genericName: 'LAMA/LABA', category: 'bronchodilator', treatsDisease: ['disease_copd'] },
    { id: 'tx_ppi', name: 'Proton Pump Inhibitor', genericName: 'Omeprazole', atcCode: 'A02BC01', category: 'other', treatsDisease: ['disease_gerd'] },
    { id: 'tx_h2_blocker', name: 'H2 Receptor Blocker', genericName: 'Ranitidine', atcCode: 'A02BA02', category: 'other', treatsDisease: ['disease_gerd'] },
    { id: 'tx_antacids', name: 'Antacids', genericName: 'Antacid combination', category: 'other', treatsDisease: ['disease_gerd'] },
    { id: 'tx_diuretic', name: 'Diuretic (Furosemide)', genericName: 'Furosemide', atcCode: 'C03CA01', category: 'diuretic', renalAdjustment: 'Increase dose', treatsDisease: ['disease_heart_failure'] },
    { id: 'tx_ace_inhibitor', name: 'ACE Inhibitor', genericName: 'Enalapril', atcCode: 'C09AA02', category: 'antihypertensive', treatsDisease: ['disease_heart_failure'] },
    { id: 'tx_beta_blocker', name: 'Beta-Blocker', genericName: 'Bisoprolol', atcCode: 'C07AB07', category: 'antiarrhythmic', treatsDisease: ['disease_heart_failure'] },
    { id: 'tx_anticoagulation', name: 'Anticoagulation', genericName: 'Heparin/Warfarin/DOAC', category: 'anticoagulant', treatsDisease: ['disease_pulmonary_embolism'] },
    { id: 'tx_thrombolysis', name: 'Thrombolysis', genericName: 'Alteplase', atcCode: 'B01AD02', category: 'anticoagulant', treatsDisease: ['disease_pulmonary_embolism'] },
    { id: 'tx_dexamethasone', name: 'Dexamethasone', genericName: 'Dexamethasone', atcCode: 'H02AB02', category: 'corticosteroid', treatsDisease: ['disease_covid19', 'disease_croup'] },
    { id: 'tx_dexamethasone_oral', name: 'Oral Dexamethasone', genericName: 'Dexamethasone', category: 'corticosteroid', treatsDisease: ['disease_croup'] },
    { id: 'tx_remdesivir', name: 'Remdesivir', genericName: 'Remdesivir', atcCode: 'J05AB16', category: 'antiviral', treatsDisease: ['disease_covid19'] },
    { id: 'tx_antifibrotic', name: 'Antifibrotic Therapy', genericName: 'Pirfenidone/Nintedanib', category: 'other', treatsDisease: ['disease_interstitial_lung_disease'] },
    { id: 'tx_antibiotics_prolonged', name: 'Prolonged Antibiotics', genericName: 'Tailored to culture', category: 'antibiotic', treatsDisease: ['disease_bronchiectasis', 'disease_lung_abscess'] },
    { id: 'tx_erythromycin', name: 'Erythromycin', genericName: 'Erythromycin', atcCode: 'J01FA01', category: 'antibiotic', treatsDisease: ['disease_pertussis'] },
    { id: 'tx_antihistamines', name: 'Antihistamines', genericName: 'Cetirizine/Loratadine', category: 'other', treatsDisease: ['disease_postnasal_drip'] },
    { id: 'tx_nasal_corticosteroids', name: 'Nasal Corticosteroids', genericName: 'Fluticasone nasal spray', category: 'corticosteroid', treatsDisease: ['disease_postnasal_drip'] },
    { id: 'tx_nebulized_epinephrine', name: 'Nebulized Epinephrine', genericName: 'Epinephrine', category: 'bronchodilator', treatsDisease: ['disease_croup'] },
  ],

  guidelines: [
    { id: 'guideline_ers_cap', title: 'ERS Guidelines for CAP', issuingBody: 'European Respiratory Society', year: 2023, level: 'global', appliesToDisease: ['disease_cap'] },
    { id: 'guideline_ats_cap', title: 'ATS/IDSA Guidelines for CAP', issuingBody: 'ATS/IDSA', year: 2023, level: 'global', appliesToDisease: ['disease_cap'] },
    { id: 'guideline_who_pneumonia', title: 'WHO Integrated Management of Childhood Illness - Pneumonia', issuingBody: 'WHO', year: 2023, level: 'global', appliesToDisease: ['disease_cap'] },
    { id: 'guideline_who_tb', title: 'WHO Guidelines for TB', issuingBody: 'WHO', year: 2023, level: 'global', appliesToDisease: ['disease_pulmonary_tuberculosis'] },
    { id: 'guideline_kenya_tb', title: 'Kenya National TB Program Guidelines', issuingBody: 'Kenya MoH', year: 2022, level: 'national', country: 'Kenya', appliesToDisease: ['disease_pulmonary_tuberculosis'], overrides: ['guideline_who_tb'] },
    { id: 'guideline_gina_asthma', title: 'GINA Guidelines for Asthma', issuingBody: 'Global Initiative for Asthma', year: 2024, level: 'global', appliesToDisease: ['disease_asthma'] },
    { id: 'guideline_british_thoracic_asthma', title: 'BTS/SIGN Guidelines for Asthma', issuingBody: 'British Thoracic Society', year: 2023, level: 'global', appliesToDisease: ['disease_asthma'] },
    { id: 'guideline_gold_copd', title: 'GOLD Guidelines for COPD', issuingBody: 'Global Initiative for COPD', year: 2024, level: 'global', appliesToDisease: ['disease_copd'] },
    { id: 'guideline_nice_copd', title: 'NICE Guidelines for COPD', issuingBody: 'NICE', year: 2023, level: 'national', country: 'UK', appliesToDisease: ['disease_copd'] },
    { id: 'guideline_ers_bronchiectasis', title: 'ERS Guidelines for Bronchiectasis', issuingBody: 'European Respiratory Society', year: 2023, level: 'global', appliesToDisease: ['disease_bronchiectasis'] },
    { id: 'guideline_bts_bronchiectasis', title: 'BTS Guidelines for Bronchiectasis', issuingBody: 'British Thoracic Society', year: 2022, level: 'global', appliesToDisease: ['disease_bronchiectasis'] },
    { id: 'guideline_acg_gerd', title: 'ACG Guidelines for GERD', issuingBody: 'American College of Gastroenterology', year: 2022, level: 'global', appliesToDisease: ['disease_gerd'] },
    { id: 'guideline_nice_gerd', title: 'NICE Guidelines for GERD', issuingBody: 'NICE', year: 2023, level: 'national', appliesToDisease: ['disease_gerd'] },
    { id: 'guideline_esc_hf', title: 'ESC Guidelines for Heart Failure', issuingBody: 'European Society of Cardiology', year: 2023, level: 'global', appliesToDisease: ['disease_heart_failure'] },
    { id: 'guideline_acc_aha_hf', title: 'ACC/AHA Guidelines for Heart Failure', issuingBody: 'ACC/AHA', year: 2024, level: 'global', appliesToDisease: ['disease_heart_failure'] },
    { id: 'guideline_nccn_lung', title: 'NCCN Guidelines for Lung Cancer', issuingBody: 'NCCN', year: 2024, level: 'global', appliesToDisease: ['disease_lung_cancer'] },
    { id: 'guideline_ers_lung_cancer', title: 'ERS/ESTS Guidelines for Lung Cancer', issuingBody: 'ERS', year: 2023, level: 'global', appliesToDisease: ['disease_lung_cancer'] },
    { id: 'guideline_esc_pe', title: 'ESC Guidelines for PE', issuingBody: 'European Society of Cardiology', year: 2023, level: 'global', appliesToDisease: ['disease_pulmonary_embolism'] },
    { id: 'guideline_chest_pe', title: 'CHEST Guidelines for PE', issuingBody: 'American College of Chest Physicians', year: 2022, level: 'global', appliesToDisease: ['disease_pulmonary_embolism'] },
    { id: 'guideline_who_pertussis', title: 'WHO Guidelines for Pertussis', issuingBody: 'WHO', year: 2023, level: 'global', appliesToDisease: ['disease_pertussis'] },
    { id: 'guideline_cdc_pertussis', title: 'CDC Guidelines for Pertussis', issuingBody: 'US CDC', year: 2022, level: 'national', appliesToDisease: ['disease_pertussis'] },
    { id: 'guideline_who_covid', title: 'WHO Guidelines for COVID-19', issuingBody: 'WHO', year: 2024, level: 'global', appliesToDisease: ['disease_covid19'] },
    { id: 'guideline_nih_covid', title: 'NIH Guidelines for COVID-19', issuingBody: 'NIH', year: 2024, level: 'national', appliesToDisease: ['disease_covid19'] },
    { id: 'guideline_ers_foreign_body', title: 'ERS Guidelines for Foreign Body Aspiration', issuingBody: 'ERS', year: 2022, level: 'global', appliesToDisease: ['disease_foreign_body_aspiration'] },
    { id: 'guideline_cps_croup', title: 'CPS Guidelines for Croup', issuingBody: 'Canadian Paediatric Society', year: 2023, level: 'national', appliesToDisease: ['disease_croup'] },
    { id: 'guideline_aap_bronchiolitis', title: 'AAP Guidelines for Bronchiolitis', issuingBody: 'American Academy of Pediatrics', year: 2022, level: 'global', appliesToDisease: ['disease_bronchiolitis'] },
    { id: 'guideline_nice_bronchiolitis', title: 'NICE Guidelines for Bronchiolitis', issuingBody: 'NICE', year: 2023, level: 'national', appliesToDisease: ['disease_bronchiolitis'] },
    { id: 'guideline_ats_ild', title: 'ATS Guidelines for ILD', issuingBody: 'American Thoracic Society', year: 2023, level: 'global', appliesToDisease: ['disease_interstitial_lung_disease'] },
    { id: 'guideline_ers_ipf', title: 'ERS Guidelines for IPF', issuingBody: 'European Respiratory Society', year: 2023, level: 'global', appliesToDisease: ['disease_interstitial_lung_disease'] },
    { id: 'guideline_bts_pneumothorax', title: 'BTS Guidelines for Pneumothorax', issuingBody: 'British Thoracic Society', year: 2023, level: 'global', appliesToDisease: ['disease_pneumothorax'] },
    { id: 'guideline_nice_acute_cough', title: 'NICE Guidelines for Acute Cough', issuingBody: 'NICE', year: 2023, level: 'national', appliesToDisease: ['disease_acute_bronchitis'] },
    { id: 'guideline_epiglottitis', title: 'Clinical Guidelines for Epiglottitis', issuingBody: 'AAO-HNS', year: 2022, level: 'global', appliesToDisease: ['disease_epiglottitis'] },
  ],

  contexts: [
    { id: 'ctx_pediatric', name: 'Pediatric Context', category: 'age', description: 'Age <18 years with developmental and dosing differences', modifies: [{ diseaseId: 'disease_cap', changes: ['Consider viral causes more common', 'Use age-appropriate antibiotics', 'Monitor for dehydration'] }] },
    { id: 'ctx_neonatal', name: 'Neonatal Context', category: 'age', description: 'Age <28 days with unique susceptibility and physiology', modifies: [{ diseaseId: 'disease_cap', changes: ['Higher risk of severe disease', 'Different causative organisms', 'Lower threshold for admission'] }] },
    { id: 'ctx_elderly', name: 'Elderly Context', category: 'age', description: 'Age >65 years', modifies: [{ diseaseId: 'disease_cap', changes: ['Atypical presentation', 'More comorbidities', 'Higher mortality'] }] },
    { id: 'ctx_pregnancy', name: 'Pregnancy Context', category: 'pregnancy', description: 'Pregnant patient with altered physiology and fetal considerations' },
    { id: 'ctx_hiv', name: 'HIV Context', category: 'immunosuppression', description: 'HIV-positive patient' },
    { id: 'ctx_immunosuppressed', name: 'Immunosuppressed Context', category: 'immunosuppression', description: 'Immunosuppressed from any cause' },
    { id: 'ctx_icu', name: 'ICU Context', category: 'icu', description: 'Critically ill patient requiring intensive care' },
    { id: 'ctx_resource_limited', name: 'Resource-Limited Context', category: 'resource_limited', description: 'Settings with limited diagnostic and treatment resources' },
  ],

  questions: [
    { id: 'q_cough_duration', text: 'How long has the cough been present?', dataType: 'single_choice', options: ['<3 days', '3-7 days', '1-3 weeks', '3-8 weeks', '>8 weeks (chronic)'], order: 1 },
    { id: 'q_cough_onset', text: 'Was the onset sudden or gradual?', dataType: 'single_choice', options: ['Sudden (minutes to hours)', 'Gradual (days to weeks)'], order: 2 },
    { id: 'q_cough_character', text: 'What type of cough?', dataType: 'single_choice', options: ['Dry (non-productive)', 'Productive (with sputum)', 'Barking (seal-like)', 'Paroxysmal (uncontrollable fits)', 'Whooping (with inspiratory whoop)'], order: 3 },
    { id: 'q_cough_sputum_color', text: 'If productive, what color is the sputum?', dataType: 'single_choice', options: ['Clear/white', 'Yellow/green (purulent)', 'Rust-colored', 'Blood-tinged (hemoptysis)', 'Foul-smelling'], order: 4 },
    { id: 'q_cough_sputum_volume', text: 'How much sputum per day?', dataType: 'single_choice', options: ['Tsp-sized', '1-2 tablespoons', '>3 tablespoons (copious)'], order: 5 },
    { id: 'q_cough_hemoptysis', text: 'Have you coughed up blood?', dataType: 'single_choice', options: ['No', 'Streaks in sputum', 'Frank blood', 'Massive hemoptysis (>100ml)'], order: 6 },
    { id: 'q_cough_timing', text: 'When does the cough occur?', dataType: 'multiple_choice', options: ['Morning only', 'At night (nocturnal)', 'After meals (postprandial)', 'With exercise', 'When lying flat', 'Throughout the day'], order: 7 },
    { id: 'q_cough_fever', text: 'Do you have a fever?', dataType: 'boolean', options: ['Yes', 'No'], order: 8 },
    { id: 'q_cough_dyspnea', text: 'Do you have shortness of breath?', dataType: 'single_choice', options: ['No dyspnea', 'With exertion only', 'At rest', 'When lying flat (orthopnea)', 'Wakes me at night (PND)'], order: 9 },
    { id: 'q_cough_chest_pain', text: 'Do you have chest pain?', dataType: 'single_choice', options: ['No', 'Sharp/pleuritic (worse with breathing)', 'Dull/aching', 'Pressure/tightness'], order: 10 },
    { id: 'q_cough_wheeze', text: 'Do you have wheezing or whistling in your chest?', dataType: 'boolean', options: ['Yes', 'No'], order: 11 },
    { id: 'q_cough_night_sweats', text: 'Do you have night sweats?', dataType: 'boolean', options: ['Yes', 'No'], order: 12 },
    { id: 'q_cough_weight_loss', text: 'Have you lost weight unintentionally?', dataType: 'boolean', options: ['Yes', 'No'], order: 13 },
    { id: 'q_cough_smoking', text: 'Do you smoke?', dataType: 'single_choice', options: ['Never', 'Ex-smoker', 'Current smoker'], order: 14 },
    { id: 'q_cough_tb_contact', text: 'Have you been in contact with someone with TB?', dataType: 'boolean', options: ['Yes', 'No'], order: 15 },
    { id: 'q_cough_ace_inhibitor', text: 'Are you taking an ACE inhibitor for blood pressure?', dataType: 'boolean', options: ['Yes', 'No'], order: 16 },
    { id: 'q_cough_allergies', text: 'Do you have any allergies (hay fever, sinusitis)?', dataType: 'boolean', options: ['Yes', 'No'], order: 17 },
    { id: 'q_cough_gerd_symptoms', text: 'Do you have heartburn or acid reflux?', dataType: 'boolean', options: ['Yes', 'No'], order: 18 },
    { id: 'q_cough_occupation', text: 'What is your occupation?', dataType: 'text', order: 19 },
    { id: 'q_cough_travel', text: 'Have you travelled recently?', dataType: 'boolean', options: ['Yes', 'No'], order: 20 },
    { id: 'q_cough_hiv_status', text: 'Do you know your HIV status?', dataType: 'single_choice', options: ['Negative', 'Positive', 'Unknown/Not tested'], order: 21 },
    { id: 'q_cough_immunosuppressed', text: 'Are you on any immunosuppressive medications?', dataType: 'single_choice', options: ['No', 'Oral steroids', 'Chemotherapy', 'Post-transplant drugs', 'Biologics'], order: 22 },
    { id: 'q_cough_choking', text: 'Did the cough start suddenly after a choking episode?', dataType: 'boolean', options: ['Yes', 'No'], order: 23 },
    { id: 'q_cough_pediatric_vaccination', text: 'Are the child\'s vaccinations up to date?', dataType: 'single_choice', options: ['Yes', 'No', 'Unknown'], order: 24 },
  ],

  signs: [
    { id: 'crackles', name: 'Crackles (Crepitations)', examinationType: 'auscultation', bodySystem: 'respiratory', supportsDisease: ['disease_cap', 'disease_bronchiectasis', 'disease_heart_failure', 'disease_lung_abscess', 'disease_bronchiolitis'] },
    { id: 'crackles_velcro', name: 'Velcro Crackles', examinationType: 'auscultation', bodySystem: 'respiratory', supportsDisease: ['disease_interstitial_lung_disease'] },
    { id: 'bronchial_breathing', name: 'Bronchial Breath Sounds', examinationType: 'auscultation', bodySystem: 'respiratory', supportsDisease: ['disease_cap', 'disease_lung_abscess'] },
    { id: 'wheeze_auscultation', name: 'Expiratory Wheeze', examinationType: 'auscultation', bodySystem: 'respiratory', supportsDisease: ['disease_asthma', 'disease_copd', 'disease_bronchiolitis', 'disease_foreign_body_aspiration'] },
    { id: 'unilateral_wheeze', name: 'Unilateral Wheeze', examinationType: 'auscultation', bodySystem: 'respiratory', supportsDisease: ['disease_foreign_body_aspiration'] },
    { id: 'reduced_breath_sounds', name: 'Reduced Breath Sounds', examinationType: 'auscultation', bodySystem: 'respiratory', supportsDisease: ['disease_pneumothorax', 'disease_pleural_effusion', 'disease_copd'] },
    { id: 'pleural_rub', name: 'Pleural Rub', examinationType: 'auscultation', bodySystem: 'respiratory', supportsDisease: ['disease_pulmonary_embolism', 'disease_pleurisy'] },
    { id: 'dull_percussion', name: 'Dull Percussion', examinationType: 'percussion', bodySystem: 'respiratory', supportsDisease: ['disease_cap', 'disease_lung_abscess', 'disease_pleural_effusion', 'disease_lung_cancer'] },
    { id: 'hyperresonant_percussion', name: 'Hyperresonant Percussion', examinationType: 'percussion', bodySystem: 'respiratory', supportsDisease: ['disease_pneumothorax', 'disease_copd'] },
    { id: 'tachypnea', name: 'Tachypnea', examinationType: 'measurement', bodySystem: 'respiratory' },
    { id: 'tachycardia', name: 'Tachycardia', examinationType: 'measurement', bodySystem: 'cardiovascular' },
    { id: 'fever_sign', name: 'Fever (Pyrexia)', examinationType: 'measurement', bodySystem: 'general' },
    { id: 'hypoxia', name: 'Hypoxia', examinationType: 'measurement', bodySystem: 'respiratory' },
    { id: 'clubbing', name: 'Digital Clubbing', examinationType: 'inspection', bodySystem: 'respiratory', supportsDisease: ['disease_bronchiectasis', 'disease_interstitial_lung_disease', 'disease_lung_cancer'] },
    { id: 'cyanosis', name: 'Cyanosis', examinationType: 'inspection', bodySystem: 'respiratory' },
    { id: 'accessory_muscle_use', name: 'Accessory Muscle Use', examinationType: 'inspection', bodySystem: 'respiratory' },
    { id: 'barrel_chest', name: 'Barrel Chest', examinationType: 'inspection', bodySystem: 'respiratory', supportsDisease: ['disease_copd'] },
    { id: 'pursed_lip_breathing', name: 'Pursed-Lip Breathing', examinationType: 'inspection', bodySystem: 'respiratory', supportsDisease: ['disease_copd'] },
    { id: 'wasting', name: 'Wasting / Cachexia', examinationType: 'inspection', bodySystem: 'general' },
    { id: 'lymphadenopathy', name: 'Lymphadenopathy', examinationType: 'palpation', bodySystem: 'lymphatic' },
    { id: 'elevated_jvp', name: 'Elevated JVP', examinationType: 'inspection', bodySystem: 'cardiovascular', supportsDisease: ['disease_heart_failure'] },
    { id: 'pedal_edema_sign', name: 'Pedal Edema', examinationType: 'inspection', bodySystem: 'cardiovascular', supportsDisease: ['disease_heart_failure'] },
    { id: 's3_gallop', name: 'S3 Gallop', examinationType: 'auscultation', bodySystem: 'cardiovascular', supportsDisease: ['disease_heart_failure'] },
    { id: 'prolonged_expiration', name: 'Prolonged Expiration', examinationType: 'auscultation', bodySystem: 'respiratory', supportsDisease: ['disease_asthma', 'disease_copd'] },
    { id: 'nasal_flaring', name: 'Nasal Flaring', examinationType: 'inspection', bodySystem: 'respiratory' },
    { id: 'barking_cough_sign', name: 'Barking Cough (on exam)', examinationType: 'inspection', bodySystem: 'respiratory' },
    { id: 'stridor_sign', name: 'Stridor (on exam)', examinationType: 'auscultation', bodySystem: 'respiratory' },
    { id: 'tripod_position', name: 'Tripod Position', examinationType: 'inspection', bodySystem: 'respiratory', supportsDisease: ['disease_epiglottitis'] },
    { id: 'drooling_sign', name: 'Drooling', examinationType: 'inspection', bodySystem: 'ent' },
    { id: 'pharyngeal_erythema', name: 'Pharyngeal Erythema', examinationType: 'inspection', bodySystem: 'ent' },
    { id: 'cobblestone_mucosa', name: 'Cobblestone Pharyngeal Mucosa', examinationType: 'inspection', bodySystem: 'ent' },
    { id: 'tracheal_deviation', name: 'Tracheal Deviation', examinationType: 'palpation', bodySystem: 'respiratory' },
    { id: 'dvt_signs', name: 'DVT Signs (calf swelling, tenderness)', examinationType: 'inspection', bodySystem: 'vascular' },
    { id: 'hepatomegaly', name: 'Hepatomegaly', examinationType: 'palpation', bodySystem: 'gastroenterology', supportsDisease: ['disease_heart_failure'] },
    { id: 'no_chest_findings', name: 'Normal Chest Exam', examinationType: 'auscultation', bodySystem: 'respiratory' },
  ],

  scores: [
    { id: 'score_curb65', name: 'CURB-65 Score', minScore: 0, maxScore: 5, components: [
      { name: 'Confusion', points: 1 }, { name: 'Urea >7 mmol/L', points: 1 }, { name: 'RR >=30/min', points: 1 },
      { name: 'BP <90/60', points: 1 }, { name: 'Age >=65', points: 1 },
    ], thresholds: [
      { level: 'Low risk (home)', min: 0, max: 1 }, { level: 'Moderate risk (short stay)', min: 2, max: 2 }, { level: 'High risk (inpatient)', min: 3, max: 5 },
    ], appliesToDisease: ['disease_cap'] },
    { id: 'score_psi', name: 'Pneumonia Severity Index (PSI)', minScore: 0, maxScore: 150, appliesToDisease: ['disease_cap'] },
    { id: 'score_qsofa', name: 'qSOFA Score', minScore: 0, maxScore: 3, components: [
      { name: 'RR >=22/min', points: 1 }, { name: 'SBP <=100 mmHg', points: 1 }, { name: 'Altered mentation', points: 1 },
    ], thresholds: [{ level: 'Low risk', min: 0, max: 1 }, { level: 'High risk (sepsis)', min: 2, max: 3 }] },
    { id: 'score_wells_pe', name: 'Wells Score for PE', minScore: 0, maxScore: 12, appliesToDisease: ['disease_pulmonary_embolism'] },
    { id: 'score_pesi', name: 'PESI Score', minScore: 0, maxScore: 300, appliesToDisease: ['disease_pulmonary_embolism'] },
    { id: 'score_geneva', name: 'Revised Geneva Score', minScore: 0, maxScore: 22, appliesToDisease: ['disease_pulmonary_embolism'] },
    { id: 'score_asthma_control', name: 'Asthma Control Test', minScore: 5, maxScore: 25, appliesToDisease: ['disease_asthma'] },
    { id: 'score_act', name: 'Asthma Control Questionnaire', appliesToDisease: ['disease_asthma'] },
    { id: 'score_acute_asthma_severity', name: 'Acute Asthma Severity Score', appliesToDisease: ['disease_asthma'] },
    { id: 'score_mrc_dyspnea', name: 'MRC Dyspnea Scale', minScore: 1, maxScore: 5, appliesToDisease: ['disease_copd'] },
    { id: 'score_cat', name: 'COPD Assessment Test', minScore: 0, maxScore: 40, appliesToDisease: ['disease_copd'] },
    { id: 'score_gold_stage', name: 'GOLD COPD Stage', appliesToDisease: ['disease_copd'] },
    { id: 'score_nyha', name: 'NYHA Functional Class', minScore: 1, maxScore: 4, appliesToDisease: ['disease_heart_failure'] },
    { id: 'score_tb_score', name: 'TB Clinical Score', appliesToDisease: ['disease_pulmonary_tuberculosis'] },
    { id: 'score_tnm_staging', name: 'TNM Lung Cancer Staging', appliesToDisease: ['disease_lung_cancer'] },
    { id: 'score_performance_status', name: 'ECOG Performance Status', minScore: 0, maxScore: 5, appliesToDisease: ['disease_lung_cancer'] },
    { id: 'score_gap_index', name: 'GAP Index for IPF', appliesToDisease: ['disease_interstitial_lung_disease'] },
    { id: 'score_bronchiectasis_severity', name: 'Bronchiectasis Severity Index', appliesToDisease: ['disease_bronchiectasis'] },
    { id: 'score_faceted', name: 'FACED Score', appliesToDisease: ['disease_bronchiectasis'] },
    { id: 'score_westley_croup', name: 'Westley Croup Score', minScore: 0, maxScore: 17, appliesToDisease: ['disease_croup'] },
    { id: 'score_news2', name: 'National Early Warning Score 2', minScore: 0, maxScore: 20 },
    { id: 'score_sofa', name: 'SOFA Score', minScore: 0, maxScore: 24 },
    { id: 'score_quick_covid_severity', name: 'Quick COVID-19 Severity Index', appliesToDisease: ['disease_covid19'] },
  ],

  protocols: [
    { id: 'prot_cap_management', name: 'CAP Management Protocol', type: 'treatment', steps: [
      'Assess severity (CURB-65)',
      'Obtain blood cultures, sputum culture, CXR',
      'Start empiric antibiotics within 4 hours',
      'Low severity: oral amoxicillin or doxycycline',
      'Moderate-high severity: IV ceftriaxone + azithromycin',
      'Assess oxygenation and provide oxygen if SpO2 <92%',
      'Reassess at 48-72 hours based on culture results',
      'Switch IV to oral when clinically stable',
      'Duration: minimum 5 days, extend if slow response',
      'Arrange follow-up CXR at 6 weeks',
    ], appliesToDisease: ['disease_cap'] },
    { id: 'prot_asthma_exacerbation', name: 'Acute Asthma Exacerbation Protocol', type: 'treatment', steps: [
      'Assess severity (mild/moderate/severe/life-threatening)',
      'Oxygen to target SpO2 94-98%',
      'Inhaled salbutamol via nebulizer or MDI + spacer',
      'Add ipratropium bromide for severe cases',
      'Oral prednisolone 40-50mg or IV hydrocortisone',
      'Monitor peak flow and SpO2',
      'Consider IV magnesium sulfate for severe',
      'Chest X-ray to exclude pneumothorax',
      'Arrange step-up of maintenance therapy',
      'Arrange follow-up in 24-48 hours',
    ], appliesToDisease: ['disease_asthma'] },
    { id: 'prot_tb_treatment', name: 'TB Treatment Protocol', type: 'treatment', steps: [
      'Confirm with GeneXpert or smear microscopy',
      'Start 4-drug regimen: Rifampicin + INH + PZA + EMB',
      'Intensive phase: 2 months',
      'Continuation phase: 4 months (Rif + INH)',
      'Monitor LFTs at baseline and monthly',
      'Check sputum smear at 2 months',
      'Screen for drug-resistant TB if no conversion',
      'Arrange DOT (Directly Observed Therapy)',
      'Counsel on adherence and side effects',
      'Register in national TB program',
    ], appliesToDisease: ['disease_pulmonary_tuberculosis'] },
    { id: 'prot_pe_management', name: 'PE Management Protocol', type: 'treatment', steps: [
      'Assess clinical probability (Wells/Geneva)',
      'Obtain D-dimer if low/intermediate probability',
      'CT pulmonary angiogram if high probability or positive D-dimer',
      'Assess severity (massive vs sub-massive vs low-risk)',
      'Start anticoagulation immediately',
      'Massive PE: consider thrombolysis',
      'Admit for monitoring if RV strain on echo',
      'Transition to oral anticoagulation',
      'Duration: minimum 3-6 months',
      'Arrange hematology follow-up',
    ], appliesToDisease: ['disease_pulmonary_embolism'] },
    { id: 'prot_croup_management', name: 'Croup Management Protocol', type: 'treatment', steps: [
      'Assess severity (Westley score)',
      'Mild: no treatment needed, observe at home',
      'Moderate: single dose oral dexamethasone 0.15-0.6 mg/kg',
      'Severe: dexamethasone + nebulized epinephrine',
      'Monitor for stridor at rest',
      'Admit if stridor at rest or persistent distress',
      'Consider intubation if worsening',
      'Arrange follow-up',
      'Exclude epiglottitis if atypical features',
      'Provide viral illness counseling',
    ], appliesToDisease: ['disease_croup'] },
  ],
};
