import type { YamlDisease } from './yaml-schema';

export const MISSING_DISEASES_2: YamlDisease[] = [
  {
    id: 'disease_mitral_stenosis', name: 'Mitral Stenosis', icd10: 'I05.0', snomed: '79619009',
    synonyms: ['Mitral valve stenosis'],
    specialty: ['cardiology', 'cardiothoracic_surgery'],
    emergencyLevel: 'orange',
    mechanisms: ['mech_mitral_valve_dysfunction', 'mech_pulmonary_hypertension'],
    phenotypes: ['phen_cardiac_cough', 'phen_exertional_cough', 'phen_hemoptysis', 'phen_orthopnea'],
    symptoms: [
      { symptomId: 'dyspnea', frequency: 'always' }, { symptomId: 'cough', frequency: 'always' },
      { symptomId: 'orthopnea', frequency: 'common' }, { symptomId: 'hemoptysis', frequency: 'common' },
      { symptomId: 'palpitations', frequency: 'common' }, { symptomId: 'fatigue', frequency: 'common' },
    ],
    signs: [
      { signId: 'opening_snap', frequency: 'always' }, { signId: 'diastolic_murmur', frequency: 'always' },
      { signId: 'elevated_jvp', frequency: 'common' }, { signId: 'pedal_edema_sign', frequency: 'common' },
    ],
    riskFactors: ['rheumatic_fever', 'female', 'age_30_50', 'developing_country'],
    etiologies: ['rheumatic_heart_disease', 'congenital_mitral_stenosis', 'degenerative_calcification'],
    complications: ['atrial_fibrillation', 'pulmonary_hypertension', 'right_heart_failure', 'systemic_embolism', 'infective_endocarditis'],
    investigations: [
      { investigationId: 'inv_echocardiogram', purpose: 'Assess valve area, gradient', timing: 'initial' },
      { investigationId: 'inv_ecg', purpose: 'Assess rhythm', timing: 'initial' },
      { investigationId: 'inv_cxr', purpose: 'Assess pulmonary congestion', timing: 'initial' },
    ],
    treatments: [
      { treatmentId: 'tx_diuretic', firstLine: true }, { treatmentId: 'tx_beta_blocker', firstLine: true },
      { treatmentId: 'tx_mitral_valve_replacement', firstLine: false }, { treatmentId: 'tx_mitral_valvuloplasty', firstLine: false },
    ],
    guidelines: ['guideline_esc_valvular', 'guideline_aha_valvular'],
    scores: ['score_nyha'],
    monitoring: ['echocardiogram_yearly', 'symptom_progression', 'rhythm_monitoring'],
    differentials: ['disease_heart_failure', 'disease_pulmonary_hypertension', 'disease_asthma', 'disease_pulmonary_embolism'],
  },
  {
    id: 'disease_pulmonary_hypertension', name: 'Pulmonary Hypertension', icd10: 'I27.0', snomed: '70995007',
    synonyms: ['PH', 'Pulmonary arterial hypertension'],
    specialty: ['cardiology', 'pulmonology'],
    emergencyLevel: 'red',
    mechanisms: ['mech_pulmonary_hypertension', 'mech_pulmonary_oedema'],
    phenotypes: ['phen_cardiac_cough', 'phen_exertional_cough', 'phen_dry_cough'],
    symptoms: [
      { symptomId: 'dyspnea', frequency: 'always' }, { symptomId: 'fatigue', frequency: 'always' },
      { symptomId: 'cough', frequency: 'common' }, { symptomId: 'chest_pain', frequency: 'common' },
      { symptomId: 'syncope', frequency: 'uncommon' },
    ],
    signs: [
      { signId: 'elevated_jvp', frequency: 'common' }, { signId: 'right_ventricular_heave', frequency: 'common' },
      { signId: 'loud_p2', frequency: 'always' }, { signId: 'pedal_edema_sign', frequency: 'common' },
    ],
    riskFactors: ['connective_tissue_disease', 'congenital_heart_disease', 'hiv', 'portal_hypertension', 'family_history', 'anorexigen_drugs'],
    etiologies: ['idiopathic', 'heritable', 'drug_induced', 'associated_with_ctd', 'congenital_heart_disease'],
    complications: ['right_heart_failure', 'arrhythmias', 'sudden_cardiac_death'],
    investigations: [
      { investigationId: 'inv_echocardiogram', purpose: 'Estimate pulmonary artery pressure', timing: 'initial' },
      { investigationId: 'inv_right_heart_catheterization', purpose: 'Confirm and measure pressures', timing: 'confirmatory' },
      { investigationId: 'inv_pft', purpose: 'Exclude lung disease', timing: 'initial' },
      { investigationId: 'inv_vq_scan', purpose: 'Exclude chronic PE', timing: 'initial' },
    ],
    treatments: [
      { treatmentId: 'tx_prostacyclin_analogues', firstLine: true },
      { treatmentId: 'tx_endothelin_receptor_antagonist', firstLine: true },
      { treatmentId: 'tx_phosphodiesterase_inhibitor', firstLine: true },
      { treatmentId: 'tx_oxygen_therapy', firstLine: true },
    ],
    guidelines: ['guideline_esc_ph', 'guideline_ers_ph'],
    scores: ['score_who_functional_class'],
    monitoring: ['right_heart_catheterization', 'echocardiogram', 'six_minute_walk', 'bnp'],
    differentials: ['disease_heart_failure', 'disease_copd', 'disease_pulmonary_embolism', 'disease_interstitial_lung_disease'],
  },
  {
    id: 'disease_sarcoidosis', name: 'Pulmonary Sarcoidosis', icd10: 'D86.0', snomed: '19383002',
    synonyms: ['Sarcoidosis', 'Boeck disease'],
    specialty: ['pulmonology', 'rheumatology'],
    emergencyLevel: 'yellow',
    mechanisms: ['mech_granulomatous_nonnecrotizing', 'mech_pulmonary_fibrosis'],
    phenotypes: ['phen_dry_cough', 'phen_exertional_cough'],
    symptoms: [
      { symptomId: 'cough', frequency: 'always' }, { symptomId: 'dyspnea', frequency: 'common' },
      { symptomId: 'fatigue', frequency: 'common' }, { symptomId: 'weight_loss', frequency: 'uncommon' },
    ],
    signs: [
      { signId: 'crackles', frequency: 'uncommon' }, { signId: 'lymphadenopathy', frequency: 'common' },
      { signId: 'erythema_nodosum', frequency: 'uncommon' },
    ],
    riskFactors: ['african_american', 'scandinavian', 'age_20_40', 'family_history'],
    etiologies: ['unknown_immune_mediated'],
    complications: ['pulmonary_fibrosis', 'pulmonary_hypertension', 'cardiac_sarcoidosis', 'neuro_sarcoidosis', 'hypercalcemia'],
    investigations: [
      { investigationId: 'inv_cxr', purpose: 'Bilateral hilar lymphadenopathy', timing: 'initial' },
      { investigationId: 'inv_ct_chest', purpose: 'Assess parenchymal involvement', timing: 'initial' },
      { investigationId: 'inv_pft', purpose: 'Restrictive pattern', timing: 'initial' },
      { investigationId: 'inv_ace_level', purpose: 'Elevated ACE', timing: 'initial' },
      { investigationId: 'inv_bronchoscopy_bal', purpose: 'Non-caseating granulomas', timing: 'confirmatory' },
    ],
    treatments: [
      { treatmentId: 'tx_oral_corticosteroids', firstLine: true },
      { treatmentId: 'tx_methotrexate', firstLine: false },
      { treatmentId: 'tx_biologics_anti_tnf', firstLine: false },
    ],
    guidelines: ['guideline_ats_sarcoidosis'],
    scores: ['score_scadding_stage'],
    monitoring: ['cxr_stage', 'pft_yearly', 'symptom_progression', 'calcium_level'],
    differentials: ['disease_pulmonary_tuberculosis', 'disease_lymphoma', 'disease_interstitial_lung_disease', 'disease_fungal_pneumonia'],
  },
  {
    id: 'disease_hypersensitivity_pneumonitis', name: 'Hypersensitivity Pneumonitis', icd10: 'J67', snomed: '41552004',
    synonyms: ['Extrinsic allergic alveolitis', 'HP'],
    specialty: ['pulmonology', 'occupational_medicine'],
    emergencyLevel: 'yellow',
    mechanisms: ['mech_hypersensitivity_pneumonitis', 'mech_pulmonary_fibrosis'],
    phenotypes: ['phen_dry_cough', 'phen_acute_onset', 'phen_exertional_cough', 'phen_occupational_cough'],
    symptoms: [
      { symptomId: 'cough', frequency: 'always' }, { symptomId: 'dyspnea', frequency: 'always' },
      { symptomId: 'fever', frequency: 'common' }, { symptomId: 'fatigue', frequency: 'common' },
    ],
    signs: [
      { signId: 'crackles', frequency: 'always' }, { signId: 'tachypnea', frequency: 'common' },
      { signId: 'hypoxia', frequency: 'common' },
    ],
    riskFactors: ['farming', 'bird_exposure', 'humidifier_exposure', 'mold_exposure', 'occupational_antigen_exposure'],
    etiologies: ['farmer_lung', 'bird_fancier_lung', 'humidifier_lung', 'chemical_worker_lung'],
    complications: ['pulmonary_fibrosis', 'chronic_respiratory_failure', 'pulmonary_hypertension'],
    investigations: [
      { investigationId: 'inv_hrct', purpose: 'Centrilobular nodules, mosaic attenuation', timing: 'initial' },
      { investigationId: 'inv_pft', purpose: 'Restrictive with reduced DLCO', timing: 'initial' },
      { investigationId: 'inv_serum_precipitins', purpose: 'Identify specific antigen', timing: 'initial' },
      { investigationId: 'inv_bronchoscopy_bal', purpose: 'Lymphocytosis', timing: 'confirmatory' },
    ],
    treatments: [
      { treatmentId: 'tx_antigen_avoidance', firstLine: true },
      { treatmentId: 'tx_oral_corticosteroids', firstLine: true },
      { treatmentId: 'tx_immunosuppressant', firstLine: false },
    ],
    guidelines: ['guideline_ats_hp'],
    scores: [],
    monitoring: ['pft_6_monthly', 'oxygen_saturation', 'antigen_exposure_status'],
    differentials: ['disease_interstitial_lung_disease', 'disease_sarcoidosis', 'disease_copd', 'disease_asthma'],
  },
  {
    id: 'disease_mediastinal_mass', name: 'Mediastinal Mass', icd10: 'R22.2', snomed: '263980008',
    synonyms: ['Mediastinal tumor', 'Mediastinal lymphadenopathy'],
    specialty: ['pulmonology', 'cardiothoracic_surgery', 'oncology'],
    emergencyLevel: 'orange',
    mechanisms: ['mech_compression', 'mech_lymphoproliferative'],
    phenotypes: ['phen_dry_cough', 'phen_stridor', 'phen_constitutional'],
    symptoms: [
      { symptomId: 'cough', frequency: 'always' }, { symptomId: 'dyspnea', frequency: 'common' },
      { symptomId: 'chest_pain', frequency: 'common' }, { symptomId: 'weight_loss', frequency: 'common' },
      { symptomId: 'superior_vena_cava_syndrome_symptom', frequency: 'uncommon' },
    ],
    signs: [
      { signId: 'lymphadenopathy', frequency: 'common' }, { signId: 'superior_vena_cava_syndrome', frequency: 'uncommon' },
      { signId: 'stridor_sign', frequency: 'uncommon' },
    ],
    riskFactors: ['smoking', 'age_>50', 'family_history_cancer', 'hiv', 'ebv_infection'],
    etiologies: ['thymoma', 'lymphoma', 'germ_cell_tumor', 'thyroid_mass', 'neurogenic_tumor', 'lymphadenopathy'],
    complications: ['superior_vena_cava_obstruction', 'airway_compression', 'spinal_cord_compression', 'pericardial_effusion'],
    investigations: [
      { investigationId: 'inv_ct_chest', purpose: 'Characterize mass', timing: 'initial' },
      { investigationId: 'inv_mri_chest', purpose: 'Better soft tissue characterization', timing: 'initial' },
      { investigationId: 'inv_pet_ct', purpose: 'Assess metabolic activity', timing: 'initial' },
      { investigationId: 'inv_bronchoscopy', purpose: 'Assess airway compression', timing: 'initial' },
      { investigationId: 'inv_ct_guided_biopsy', purpose: 'Tissue diagnosis', timing: 'confirmatory' },
    ],
    treatments: [
      { treatmentId: 'tx_surgical_resection', firstLine: false },
      { treatmentId: 'tx_chemotherapy', firstLine: false },
      { treatmentId: 'tx_radiation_therapy', firstLine: false },
    ],
    guidelines: [],
    scores: [],
    monitoring: ['imaging_follow_up', 'symptom_progression', 'tumor_markers'],
    differentials: ['disease_lung_cancer', 'disease_lymphoma', 'disease_pulmonary_tuberculosis', 'disease_sarcoidosis'],
  },
  {
    id: 'disease_lymphoma_pulmonary', name: 'Pulmonary Lymphoma', icd10: 'C85', snomed: '118599009',
    synonyms: ['Lymphomatous involvement of lung', 'Primary pulmonary lymphoma'],
    specialty: ['oncology', 'pulmonology', 'hematology'],
    emergencyLevel: 'orange',
    mechanisms: ['mech_lymphoproliferative', 'mech_tumour'],
    phenotypes: ['phen_dry_cough', 'phen_constitutional', 'phen_exertional_cough'],
    symptoms: [
      { symptomId: 'cough', frequency: 'always' }, { symptomId: 'weight_loss', frequency: 'always' },
      { symptomId: 'fever', frequency: 'common' }, { symptomId: 'night_sweats', frequency: 'common' },
      { symptomId: 'dyspnea', frequency: 'common' }, { symptomId: 'lymphadenopathy_symptom', frequency: 'common' },
    ],
    signs: [
      { signId: 'lymphadenopathy', frequency: 'always' }, { signId: 'fever_sign', frequency: 'common' },
      { signId: 'wasting', frequency: 'common' }, { signId: 'hepatomegaly', frequency: 'uncommon' },
    ],
    riskFactors: ['immunosuppression', 'hiv', 'organ_transplant', 'autoimmune_disease', 'ebv'],
    etiologies: ['non_hodgkin_lymphoma', 'hodgkin_lymphoma', 'malt_lymphoma'],
    complications: ['airway_obstruction', 'superior_vena_cava_syndrome', 'pleural_effusion', 'bone_marrow_failure'],
    investigations: [
      { investigationId: 'inv_ct_chest', purpose: 'Mass, nodules, infiltrates', timing: 'initial' },
      { investigationId: 'inv_pet_ct', purpose: 'Staging and metabolic activity', timing: 'initial' },
      { investigationId: 'inv_ct_guided_biopsy', purpose: 'Tissue diagnosis', timing: 'confirmatory' },
      { investigationId: 'inv_bronchoscopy', purpose: 'Endobronchial biopsy', timing: 'confirmatory' },
      { investigationId: 'inv_flow_cytometry', purpose: 'Immunophenotyping', timing: 'confirmatory' },
    ],
    treatments: [
      { treatmentId: 'tx_chemotherapy', firstLine: true },
      { treatmentId: 'tx_radiation_therapy', firstLine: false },
      { treatmentId: 'tx_immunotherapy', firstLine: false },
    ],
    guidelines: ['guideline_nccn_lymphoma'],
    scores: ['score_ipi'],
    monitoring: ['pet_ct_follow_up', 'ldh_trend', 'symptom_assessment'],
    differentials: ['disease_lung_cancer', 'disease_sarcoidosis', 'disease_pulmonary_tuberculosis', 'disease_mediastinal_mass'],
  },
  {
    id: 'disease_occupational_asthma', name: 'Occupational Asthma', icd10: 'J45.0', snomed: '413840005',
    synonyms: ['Work-related asthma', 'OA'],
    specialty: ['pulmonology', 'occupational_medicine'],
    emergencyLevel: 'orange',
    mechanisms: ['mech_allergic', 'mech_airway_obstruction'],
    phenotypes: ['phen_occupational_cough', 'phen_wheeze_dominant', 'phen_dry_cough'],
    symptoms: [
      { symptomId: 'cough', frequency: 'always' }, { symptomId: 'wheeze', frequency: 'always' },
      { symptomId: 'dyspnea', frequency: 'always' }, { symptomId: 'chest_tightness', frequency: 'common' },
    ],
    signs: [
      { signId: 'wheeze_auscultation', frequency: 'always' }, { signId: 'prolonged_expiration', frequency: 'common' },
    ],
    riskFactors: ['isocyanates_exposure', 'bakery_dust', 'laboratory_animal_exposure', 'wood_dust', 'latex', 'welding_fumes'],
    etiologies: ['occupational_sensitizers', 'workplace_irritants'],
    complications: ['chronic_asthma', 'irreversible_airflow_obstruction', 'respiratory_failure'],
    investigations: [
      { investigationId: 'inv_peak_flow_serial', purpose: 'Workplace peak flow monitoring', timing: 'initial' },
      { investigationId: 'inv_spirometry', purpose: 'Assess reversibility', timing: 'initial' },
      { investigationId: 'inv_methacholine_challenge', purpose: 'Assess airway hyperresponsiveness', timing: 'initial' },
      { investigationId: 'inv_specific_ige', purpose: 'Identify sensitizer', timing: 'confirmatory' },
    ],
    treatments: [
      { treatmentId: 'tx_workplace_avoidance', firstLine: true },
      { treatmentId: 'tx_salbutamol_inhaler', firstLine: true },
      { treatmentId: 'tx_ics_laba', firstLine: true },
    ],
    guidelines: ['guideline_ats_occupational_asthma'],
    scores: ['score_asthma_control'],
    monitoring: ['peak_flow_diary', 'workplace_monitoring', 'serial_spirometry'],
    differentials: ['disease_asthma', 'disease_copd', 'disease_hypersensitivity_pneumonitis', 'disease_vocal_cord_dysfunction'],
  },
  {
    id: 'disease_silicosis', name: 'Silicosis', icd10: 'J62', snomed: '1534002',
    synonyms: ['Silica lung', 'Miners lung'],
    specialty: ['pulmonology', 'occupational_medicine'],
    emergencyLevel: 'yellow',
    mechanisms: ['mech_environmental', 'mech_pulmonary_fibrosis'],
    phenotypes: ['phen_occupational_cough', 'phen_chronic_productive', 'phen_exertional_cough'],
    symptoms: [
      { symptomId: 'cough', frequency: 'always' }, { symptomId: 'dyspnea', frequency: 'always' },
      { symptomId: 'sputum', frequency: 'common' },
    ],
    signs: [
      { signId: 'crackles', frequency: 'common' }, { signId: 'tachypnea', frequency: 'common' },
    ],
    riskFactors: ['mining', 'sandblasting', 'stone_cutting', 'foundry_work', 'construction_demolition'],
    etiologies: ['crystalline_silica_inhalation'],
    complications: ['pulmonary_fibrosis_massive', 'pulmonary_hypertension', 'respiratory_failure', 'tuberculosis_silicotuberculosis', 'lung_cancer'],
    investigations: [
      { investigationId: 'inv_cxr', purpose: 'Upper lobe nodular opacities', timing: 'initial' },
      { investigationId: 'inv_hrct', purpose: 'Characterize nodular pattern', timing: 'initial' },
      { investigationId: 'inv_pft', purpose: 'Restrictive pattern', timing: 'initial' },
    ],
    treatments: [
      { treatmentId: 'tx_supportive_care', firstLine: true },
      { treatmentId: 'tx_oxygen_therapy', firstLine: false },
      { treatmentId: 'tx_lung_transplant', firstLine: false },
    ],
    guidelines: ['guideline_occupational_lung_disease'],
    scores: [],
    monitoring: ['cxr_progression', 'pft_trend', 'symptom_progression'],
    differentials: ['disease_copd', 'disease_pulmonary_tuberculosis', 'disease_sarcoidosis', 'disease_interstitial_lung_disease'],
  },
  {
    id: 'disease_asbestosis', name: 'Asbestosis', icd10: 'J61', snomed: '15250000',
    synonyms: ['Asbestos-related lung disease'],
    specialty: ['pulmonology', 'occupational_medicine'],
    emergencyLevel: 'yellow',
    mechanisms: ['mech_environmental', 'mech_pulmonary_fibrosis'],
    phenotypes: ['phen_occupational_cough', 'phen_exertional_cough', 'phen_dry_cough'],
    symptoms: [
      { symptomId: 'dyspnea', frequency: 'always' }, { symptomId: 'cough', frequency: 'always' },
      { symptomId: 'chest_pain', frequency: 'uncommon' },
    ],
    signs: [
      { signId: 'crackles', frequency: 'always' }, { signId: 'clubbing', frequency: 'common' },
    ],
    riskFactors: ['asbestos_mining', 'shipbuilding', 'construction', 'insulation_work', 'brake_repair'],
    etiologies: ['asbestos_fiber_inhalation'],
    complications: ['mesothelioma', 'lung_cancer', 'pleural_plaques', 'pleural_effusion', 'diffuse_pulmonary_fibrosis'],
    investigations: [
      { investigationId: 'inv_cxr', purpose: 'Pleural plaques, lower zone fibrosis', timing: 'initial' },
      { investigationId: 'inv_hrct', purpose: 'Characterize pleural and parenchymal changes', timing: 'initial' },
      { investigationId: 'inv_pft', purpose: 'Restrictive pattern with reduced DLCO', timing: 'initial' },
    ],
    treatments: [
      { treatmentId: 'tx_supportive_care', firstLine: true },
      { treatmentId: 'tx_oxygen_therapy', firstLine: false },
      { treatmentId: 'tx_pulmonary_rehab', firstLine: true },
    ],
    guidelines: ['guideline_occupational_lung_disease'],
    scores: [],
    monitoring: ['cxr_ct_progression', 'pft_trend', 'lung_cancer_screening'],
    differentials: ['disease_copd', 'disease_interstitial_lung_disease', 'disease_silicosis', 'disease_mesothelioma'],
  },
];
