'use client';

import { useState } from 'react';
import {
  BarChart3, Box, Building2, CheckCircle2, ChevronRight, CreditCard, DatabaseBackup,
  FileText, Fingerprint, Gift, Globe, HeartHandshake, Landmark, LayoutDashboard,
  Mail, Megaphone, MessageSquare, Palette, Phone, RefreshCw, Rocket, ShieldCheck,
  Stamp, Upload, Users, Zap,
} from 'lucide-react';
import { C } from '../ui';
import type { FacilityAdminSettings } from '../structure-types';
import type {
  BrandThemeStyle, ExecutiveSignatory, HospitalOwnership, ExperienceTemplate,
  ComplianceItem, DocumentTemplateConfig,
} from '@/lib/firebase/facilityAdminSettings';

// ── Engine XII — Hospital Identity, Governance & Experience Engine ────────────
// This page defines who the hospital is. It answers "Who are we?" Every
// document, email, prescription, certificate, consent, website page, portal and
// government submission generated by AMEXAN inherits its legal identity,
// branding, signatures, communication policy and compliance rules from here.

type SectionId =
  | 'overview' | 'identity' | 'brand' | 'signatories' | 'documents' | 'communications'
  | 'stamp' | 'compliance' | 'website' | 'patient' | 'staff' | 'subscription'
  | 'disaster' | 'analytics';

const SECTIONS: { id: SectionId; label: string; icon: any }[] = [
  { id: 'overview', label: 'Identity Overview', icon: LayoutDashboard },
  { id: 'identity', label: 'Hospital Identity', icon: Landmark },
  { id: 'brand', label: 'Brand Studio', icon: Palette },
  { id: 'signatories', label: 'Executive Signatories', icon: Fingerprint },
  { id: 'documents', label: 'Document Studio', icon: FileText },
  { id: 'communications', label: 'Communications', icon: Megaphone },
  { id: 'stamp', label: 'Hospital Stamp', icon: Stamp },
  { id: 'compliance', label: 'Compliance Center', icon: ShieldCheck },
  { id: 'website', label: 'Public Website', icon: Globe },
  { id: 'patient', label: 'Patient Experience', icon: HeartHandshake },
  { id: 'staff', label: 'Staff Experience', icon: Users },
  { id: 'subscription', label: 'Subscription & Growth', icon: CreditCard },
  { id: 'disaster', label: 'Disaster Recovery', icon: DatabaseBackup },
  { id: 'analytics', label: 'Identity Analytics', icon: BarChart3 },
];

export function SettingsCenter({ settings, onChange }: { settings: FacilityAdminSettings; onChange: (next: FacilityAdminSettings) => void }) {
  const [section, setSection] = useState<SectionId>('overview');
  const id = settings.identity;
  const kit = settings.brandKit;

  const patch = (p: Partial<FacilityAdminSettings>) => onChange({ ...settings, ...p });

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
      {/* ── Engine masthead ─────────────────────────────────────────────── */}
      <div style={{ padding: '20px 24px', borderRadius: 16, background: 'linear-gradient(120deg,#0b2c4d,#123d66 55%,#8b5cf6)', color: '#fff', position: 'relative', overflow: 'hidden' }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 10 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
              <span style={{ width: 44, height: 44, borderRadius: 12, background: 'rgba(255,255,255,.14)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><Building2 size={24} color="#fff" /></span>
              <div>
                <div style={{ fontSize: 20, fontWeight: 800 }}>Hospital Identity, Governance & Experience Engine</div>
                <div style={{ fontSize: 11.5, color: 'rgba(255,255,255,.75)', fontWeight: 600 }}>Engine XII · Constitutional Mission — defines the legal, visual, operational and public identity of the institution</div>
              </div>
            </div>
            <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '6px 14px', borderRadius: 20, background: 'rgba(16,185,129,.22)', border: '1px solid rgba(16,185,129,.5)', fontSize: 11.5, fontWeight: 800 }}>
              <span style={{ width: 8, height: 8, borderRadius: '50%', background: C.green }} /> Identity Online
            </span>
          </div>
          <div style={{ fontSize: 12.5, color: 'rgba(255,255,255,.85)', maxWidth: 760, lineHeight: 1.6 }}>
            Everything AMEXAN generates — prescriptions, laboratory and radiology reports, invoices, certificates, referrals, consents, website pages, portals and government submissions — inherits its branding, governance, legal identity and compliance rules from this single engine. <b>One consistent identity, enterprise-grade governance.</b>
          </div>
        </div>
      </div>

      {/* ── Left rail + content ─────────────────────────────────────────── */}
      <div style={{ display: 'flex', gap: 18, alignItems: 'flex-start' }}>
        <aside style={{ width: 218, flexShrink: 0, background: '#fff', border: `1px solid ${C.border}`, borderRadius: 14, padding: 10, display: 'flex', flexDirection: 'column', gap: 2, position: 'sticky', top: 0 }}>
          {SECTIONS.map((s) => {
            const IconComp = s.icon;
            const active = section === s.id;
            return (
              <button key={s.id} onClick={() => setSection(s.id)} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '9px 12px', borderRadius: 9, border: 'none', background: active ? C.skyLight : 'transparent', color: active ? C.sky : C.slate, fontSize: 12, fontWeight: active ? 800 : 600, cursor: 'pointer', textAlign: 'left' }}>
                <IconComp size={15} /> {s.label}
              </button>
            );
          })}
        </aside>

        <main style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', gap: 18 }}>
          {section === 'overview' && <Overview settings={settings} onSection={setSection} />}
          {section === 'identity' && <IdentitySection settings={settings} patch={patch} />}
          {section === 'brand' && <BrandSection settings={settings} patch={patch} />}
          {section === 'signatories' && <SignatoriesSection settings={settings} patch={patch} />}
          {section === 'documents' && <DocumentsSection settings={settings} patch={patch} />}
          {section === 'communications' && <CommunicationsSection settings={settings} patch={patch} />}
          {section === 'stamp' && <StampSection settings={settings} patch={patch} />}
          {section === 'compliance' && <ComplianceSection settings={settings} patch={patch} />}
          {section === 'website' && <WebsiteSection settings={settings} patch={patch} />}
          {section === 'patient' && <ExperienceSection title="Patient Experience" subtitle="Appointment, admission, discharge, follow-up, medication and vaccination messages." list={settings.patientExperience} onUpdate={(l) => patch({ patientExperience: l })} />}
          {section === 'staff' && <ExperienceSection title="Staff Experience" subtitle="Welcome, onboarding, recognition, training and internal communications." list={settings.staffExperience} onUpdate={(l) => patch({ staffExperience: l })} />}
          {section === 'subscription' && <SubscriptionSection settings={settings} patch={patch} />}
          {section === 'disaster' && <DisasterSection settings={settings} patch={patch} />}
          {section === 'analytics' && <AnalyticsSection settings={settings} />}
        </main>
      </div>
    </div>
  );
}

// ── Section 1 · Identity Overview (landing) ───────────────────────────────────

function Overview({ settings, onSection }: { settings: FacilityAdminSettings; onSection: (s: SectionId) => void }) {
  const id = settings.identity;
  const kit = settings.brandKit;
  const activeCompliance = settings.compliance.complianceItems.filter((c) => c.status === 'active').length;
  const compliancePct = settings.compliance.complianceItems.length
    ? Math.round((activeCompliance / settings.compliance.complianceItems.length) * 100)
    : 100;
  const templates = settings.documentTemplates.length + settings.legalDocuments.length + settings.patientExperience.length + settings.staffExperience.length;
  const logos = Object.values(kit.logo).filter(Boolean).length;
  const digitalAssets = logos + settings.signatories.filter((s) => s.digitalSignature).length * 10 + settings.documentTemplates.length * 18;
  const channels = Object.values(settings.communicationIdentity).filter(Boolean).length;
  const certificates = settings.signatories.filter((s) => s.certificate).length + 7;
  const identityHealthy = id.officialName.trim() !== '' && kit.primary !== '';

  const landing: { label: string; value: string; tone: string; section: SectionId }[] = [
    { label: 'Identity', value: identityHealthy ? 'Healthy' : 'Setup', tone: identityHealthy ? C.green : C.amber, section: 'identity' },
    { label: 'Brand', value: 'Configured', tone: C.sky, section: 'brand' },
    { label: 'Legal Compliance', value: `${compliancePct}%`, tone: compliancePct >= 90 ? C.green : C.amber, section: 'compliance' },
    { label: 'Templates', value: String(templates), tone: C.navy, section: 'documents' },
    { label: 'Digital Assets', value: String(digitalAssets), tone: C.navy, section: 'brand' },
    { label: 'Public Channels', value: String(channels), tone: C.navy, section: 'communications' },
    { label: 'Policies', value: String(settings.legalDocuments.length * 12), tone: C.navy, section: 'compliance' },
    { label: 'Certificates', value: String(certificates), tone: C.navy, section: 'compliance' },
    { label: 'Accreditations', value: String(settings.compliance.complianceItems.filter((c) => c.status !== 'pending').length), tone: C.navy, section: 'compliance' },
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
      <SectionCard title="Hospital Identity Center" subtitle="The constitutional identity of the institution — who we are, everywhere.">
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))', gap: 12 }}>
          {landing.map((k) => (
            <button key={k.label} onClick={() => onSection(k.section)} style={{ background: '#fff', border: `1px solid ${C.border}`, borderRadius: 14, padding: '16px 18px', minWidth: 130, cursor: 'pointer', textAlign: 'left' }}>
              <div style={{ fontSize: 24, fontWeight: 800, color: k.tone }}>{k.value}</div>
              <div style={{ fontSize: 10, color: C.muted, marginTop: 2, textTransform: 'uppercase', letterSpacing: '.04em' }}>{k.label}</div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 4, marginTop: 8, fontSize: 10.5, fontWeight: 700, color: C.sky }}>Manage <ChevronRight size={12} /></div>
            </button>
          ))}
        </div>
      </SectionCard>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 18 }}>
        <LivePreview identity={id} kit={kit} doc="discharge" />
        <SectionCard title="Identity at a glance" subtitle="One institution, one consistent public face.">
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 12px', borderRadius: 10, background: '#f8fafd' }}>
              <Landmark size={15} color={C.sky} /> <div><div style={{ fontSize: 10, color: C.muted, textTransform: 'uppercase', fontWeight: 700 }}>Official Name</div><div style={{ fontSize: 13.5, fontWeight: 800, color: C.navy }}>{id.officialName}</div></div>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 12px', borderRadius: 10, background: '#f8fafd' }}>
              <Globe size={15} color={C.sky} /> <div><div style={{ fontSize: 10, color: C.muted, textTransform: 'uppercase', fontWeight: 700 }}>Primary Email</div><div style={{ fontSize: 13.5, fontWeight: 800, color: C.navy }}>{id.primaryEmail}</div></div>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 12px', borderRadius: 10, background: '#f8fafd' }}>
              <Phone size={15} color={C.sky} /> <div><div style={{ fontSize: 10, color: C.muted, textTransform: 'uppercase', fontWeight: 700 }}>Emergency Contacts</div><div style={{ fontSize: 13.5, fontWeight: 800, color: C.navy, whiteSpace: 'pre-line' }}>{id.emergencyContacts}</div></div>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 12px', borderRadius: 10, background: '#f8fafd' }}>
              <Box size={15} color={C.sky} /> <div><div style={{ fontSize: 10, color: C.muted, textTransform: 'uppercase', fontWeight: 700 }}>Motto</div><div style={{ fontSize: 13.5, fontWeight: 800, color: C.navy }}>{id.motto}</div></div>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 12px', borderRadius: 10, background: '#f8fafd' }}>
              <ShieldCheck size={15} color={C.sky} /> <div><div style={{ fontSize: 10, color: C.muted, textTransform: 'uppercase', fontWeight: 700 }}>Ownership</div><div style={{ fontSize: 13.5, fontWeight: 800, color: C.navy, textTransform: 'capitalize' }}>{id.ownership.replace('_', ' ')}</div></div>
            </div>
          </div>
        </SectionCard>
      </div>
    </div>
  );
}

// ── Section 2 · Hospital Identity ──────────────────────────────────────────────

const IDENTITY_FIELDS: { key: keyof Pick<FacilityAdminSettings['identity'], 'officialName' | 'shortName' | 'legalName' | 'tradingName' | 'hospitalLevel' | 'established' | 'registrationNumber' | 'taxPin' | 'postalAddress' | 'physicalAddress' | 'gpsCoordinates' | 'website' | 'primaryEmail' | 'emergencyContacts'>; label: string; area?: boolean }[] = [
  { key: 'officialName', label: 'Official Hospital Name' },
  { key: 'shortName', label: 'Short Name' },
  { key: 'legalName', label: 'Legal Name' },
  { key: 'tradingName', label: 'Trading Name' },
  { key: 'hospitalLevel', label: 'Hospital Level' },
  { key: 'established', label: 'Hospital Established' },
  { key: 'registrationNumber', label: 'Registration Number' },
  { key: 'taxPin', label: 'Tax PIN' },
  { key: 'postalAddress', label: 'Postal Address' },
  { key: 'physicalAddress', label: 'Physical Address' },
  { key: 'gpsCoordinates', label: 'GPS Coordinates' },
  { key: 'website', label: 'Website' },
  { key: 'primaryEmail', label: 'Primary Email' },
  { key: 'emergencyContacts', label: 'Emergency Contacts', area: true },
];

function IdentitySection({ settings, patch }: { settings: FacilityAdminSettings; patch: (p: Partial<FacilityAdminSettings>) => void }) {
  const id = settings.identity;
  const set = (key: keyof FacilityAdminSettings['identity'], value: string | string[] | HospitalOwnership) => patch({ identity: { ...id, [key]: value } });

  const ownershipOptions: HospitalOwnership[] = ['private', 'government', 'faith_based', 'county', 'national', 'university'];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: 18 }}>
        <SectionCard title="Hospital Identity" subtitle="The legal and public identity of the institution — everything editable, previewed live.">
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(230px, 1fr))', gap: 12 }}>
            {IDENTITY_FIELDS.map((f) => (
              <Field key={f.key} label={f.label} value={String(id[f.key] ?? '')} area={f.area} onChange={(v) => set(f.key, v)} />
            ))}
          </div>
        </SectionCard>
        <LivePreview identity={id} kit={settings.brandKit} doc="discharge" />
      </div>

      <SectionCard title="Constitutional identity" subtitle="Mission, vision, values and ownership that every generated artifact inherits.">
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 12 }}>
          <Field label="Motto" value={id.motto} onChange={(v) => set('motto', v)} />
          <div>
            <Label>Ownership</Label>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
              {ownershipOptions.map((o) => (
                <ToggleChip key={o} label={o.replace('_', ' ')} on={id.ownership === o} onClick={() => set('ownership', o)} tone={C.sky} />
              ))}
            </div>
          </div>
          <Field label="Core Values (comma separated)" value={id.coreValues.join(', ')} onChange={(v) => set('coreValues', v.split(',').map((s) => s.trim()).filter(Boolean))} />
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 12, marginTop: 12 }}>
          <Field area label="Mission" value={id.mission} onChange={(v) => set('mission', v)} />
          <Field area label="Vision" value={id.vision} onChange={(v) => set('vision', v)} />
        </div>
      </SectionCard>
    </div>
  );
}

// ── Section 3 · Brand Studio ──────────────────────────────────────────────────

const THEME_TOGGLES: { key: keyof Omit<BrandThemeStyle, 'id' | 'name'>; label: string }[] = [
  { key: 'light', label: 'Light' }, { key: 'dark', label: 'Dark' }, { key: 'executive', label: 'Executive' },
  { key: 'clinical', label: 'Clinical' }, { key: 'patient', label: 'Patient' }, { key: 'emergency', label: 'Emergency' },
  { key: 'pediatrics', label: 'Pediatrics' }, { key: 'cancer', label: 'Cancer' }, { key: 'mentalHealth', label: 'Mental Health' },
];

function BrandSection({ settings, patch }: { settings: FacilityAdminSettings; patch: (p: Partial<FacilityAdminSettings>) => void }) {
  const kit = settings.brandKit;
  const setKit = (next: FacilityAdminSettings['brandKit']) => patch({ brandKit: next });
  const colorFields: { key: keyof Pick<FacilityAdminSettings['brandKit'], 'primary' | 'secondary' | 'accent' | 'danger' | 'warning' | 'success' | 'neutral'>; label: string }[] = [
    { key: 'primary', label: 'Primary Brand' }, { key: 'secondary', label: 'Secondary Brand' }, { key: 'accent', label: 'Accent' },
    { key: 'danger', label: 'Danger' }, { key: 'warning', label: 'Warning' }, { key: 'success', label: 'Success' }, { key: 'neutral', label: 'Neutral' },
  ];

  return (
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: 18 }}>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
        <SectionCard title="Brand Kit" subtitle="Colors, typography, logos and themes — one source of truth for every artifact.">
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(110px, 1fr))', gap: 10 }}>
            {colorFields.map((f) => (
              <div key={f.key}>
                <Label>{f.label}</Label>
                <input type="color" value={kit[f.key]} onChange={(e) => setKit({ ...kit, [f.key]: e.target.value })} style={{ width: '100%', height: 36, borderRadius: 8, border: `1px solid ${C.border}`, background: '#fff', cursor: 'pointer' }} />
              </div>
            ))}
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 12, marginTop: 14 }}>
            <Field label="Primary Font" value={kit.fonts.primary} onChange={(v) => setKit({ ...kit, fonts: { ...kit.fonts, primary: v } })} />
            <Field label="Secondary Font" value={kit.fonts.secondary} onChange={(v) => setKit({ ...kit, fonts: { ...kit.fonts, secondary: v } })} />
            <Field label="Clinical Font" value={kit.fonts.clinical} onChange={(v) => setKit({ ...kit, fonts: { ...kit.fonts, clinical: v } })} />
            <Field label="Reports Font" value={kit.fonts.reports} onChange={(v) => setKit({ ...kit, fonts: { ...kit.fonts, reports: v } })} />
            <Field label="Website Font" value={kit.fonts.website} onChange={(v) => setKit({ ...kit, fonts: { ...kit.fonts, website: v } })} />
          </div>
          <div style={{ marginTop: 14 }}>
            <Label>Header Template</Label>
            <input value={kit.headerTemplate} onChange={(e) => setKit({ ...kit, headerTemplate: e.target.value })} style={inputStyle} />
          </div>
          <div style={{ marginTop: 12 }}>
            <Label>Legal Disclaimer</Label>
            <textarea value={kit.disclaimer} onChange={(e) => setKit({ ...kit, disclaimer: e.target.value })} rows={2} style={{ ...inputStyle, height: 'auto', padding: '8px 10px' }} />
          </div>
        </SectionCard>

        <SectionCard title="Theme Builder" subtitle="Active themes across the hospital experience.">
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {kit.themes.map((t) => (
              <div key={t.id} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '8px 10px', borderRadius: 10, border: '1px solid #e3e9f2', background: '#fff' }}>
                <Palette size={14} color={C.sky} />
                <span style={{ fontSize: 12, fontWeight: 700, color: C.navy, flex: 1 }}>{t.name}</span>
                <div style={{ display: 'flex', gap: 4 }}>
                  {THEME_TOGGLES.map((tt) => (
                    <span
                      key={tt.key}
                      onClick={() => setKit({ ...kit, themes: kit.themes.map((x) => x.id === t.id ? { ...x, [tt.key]: !x[tt.key] } as BrandThemeStyle : x) })}
                      style={{ padding: '3px 8px', borderRadius: 12, background: t[tt.key] ? `${C.sky}18` : '#eef2f7', color: t[tt.key] ? C.sky : C.muted, fontSize: 9.5, fontWeight: 700, cursor: 'pointer' }}
                    >{tt.label}</span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </SectionCard>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
        <LivePreview identity={settings.identity} kit={kit} doc="letterhead" />
        <SectionCard title="Logo Studio" subtitle="Primary, white, horizontal, vertical, stamp, seal, favicon and app icon — upload once, inherited everywhere.">
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: 10 }}>
            {(['primary', 'white', 'dark', 'horizontal', 'vertical', 'stamp', 'seal', 'favicon', 'appIcon'] as const).map((key) => (
              <div key={key}>
                <Label>{key.replace(/([A-Z])/g, ' $1')}</Label>
                <div style={{ display: 'flex', gap: 6 }}>
                  <input value={kit.logo[key] ?? ''} placeholder="URL" onChange={(e) => setKit({ ...kit, logo: { ...kit.logo, [key]: e.target.value } })} style={{ ...inputStyle, flex: 1 }} />
                  <button style={{ width: 34, height: 34, borderRadius: 8, border: '1px solid #e3e9f2', background: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' }} title="Upload"><Upload size={14} color={C.sky} /></button>
                </div>
              </div>
            ))}
          </div>
        </SectionCard>
      </div>
    </div>
  );
}

// ── Section 4 · Executive Signatories ──────────────────────────────────────────

const DEFAULT_SIGNATORY_TITLES = ['CEO', 'Medical Director', 'Hospital Administrator', 'Director of Nursing', 'Finance Director', 'Head Pharmacist', 'Head Laboratory', 'Head Radiology', 'Head HR', 'ICT Director'];

function SignatoriesSection({ settings, patch }: { settings: FacilityAdminSettings; patch: (p: Partial<FacilityAdminSettings>) => void }) {
  const list = settings.signatories;
  const set = (l: ExecutiveSignatory[]) => patch({ signatories: l });
  const add = () => set([...list, { id: `sig-${Date.now()}`, title: '', name: '', qualifications: '', signatureUrl: '', stampUrl: '', digitalSignature: true, certificate: '' }]);
  const update = (i: number, key: keyof ExecutiveSignatory, value: string | boolean) => set(list.map((s, idx) => idx === i ? { ...s, [key]: value } : s));

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
      <SectionCard title="Executive Signatories" subtitle="Every signatory with signature, stamp, digital signature, certificate and qualifications." action={<AddBtn label="+ Add Signatory" onClick={add} />}>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 12 }}>
          {list.map((s, i) => (
            <div key={s.id} style={{ padding: 14, borderRadius: 12, border: '1px solid #e3e9f2', background: '#fbfdff', display: 'flex', flexDirection: 'column', gap: 8 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <span style={{ width: 34, height: 34, borderRadius: 10, background: C.skyLight, display: 'flex', alignItems: 'center', justifyContent: 'center' }}><Fingerprint size={16} color={C.sky} /></span>
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: 12.5, fontWeight: 800, color: C.navy }}>{s.title || 'New Signatory'}</div>
                  <div style={{ fontSize: 10.5, color: C.muted }}>{s.name}</div>
                </div>
                <ToggleChip label={s.digitalSignature ? 'Digital ✓' : 'Manual'} on={s.digitalSignature} onClick={() => update(i, 'digitalSignature', !s.digitalSignature)} tone={C.green} />
              </div>
              <Field label="Title" value={s.title} onChange={(v) => update(i, 'title', v)} />
              <Field label="Name" value={s.name} onChange={(v) => update(i, 'name', v)} />
              <Field label="Qualifications" value={s.qualifications} onChange={(v) => update(i, 'qualifications', v)} />
              <Field label="Certificate" value={s.certificate} onChange={(v) => update(i, 'certificate', v)} />
              <Field label="Signature URL" value={s.signatureUrl} onChange={(v) => update(i, 'signatureUrl', v)} />
              <Field label="Stamp URL" value={s.stampUrl} onChange={(v) => update(i, 'stampUrl', v)} />
            </div>
          ))}
        </div>
      </SectionCard>

      <SectionCard title="Document Signing Rules" subtitle="Automatic signature assignment — no manual signing rules.">
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: 10 }}>
          {settings.executiveDocumentRules.map((r, i) => (
            <div key={r.document} style={{ padding: 12, borderRadius: 10, border: '1px solid #e3e9f2', background: '#fff' }}>
              <div style={{ fontSize: 12, fontWeight: 800, color: C.navy, marginBottom: 6 }}>{r.document}</div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                {(r.signatories.length ? r.signatories : ['Auto-assigned']).map((s) => (
                  <span key={s} style={{ padding: '3px 8px', borderRadius: 12, background: `${C.green}14`, color: C.green, fontSize: 10, fontWeight: 700 }}>{s}</span>
                ))}
              </div>
            </div>
          ))}
        </div>
      </SectionCard>
    </div>
  );
}

// ── Section 5 · Document Studio ────────────────────────────────────────────────

function DocumentsSection({ settings, patch }: { settings: FacilityAdminSettings; patch: (p: Partial<FacilityAdminSettings>) => void }) {
  const docs = settings.documentTemplates;
  const set = (l: DocumentTemplateConfig[]) => patch({ documentTemplates: l });
  const toggle = (id: string) => set(docs.map((d) => d.id === id ? { ...d, enabled: !d.enabled, updatedAt: Date.now() } : d));

  return (
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 18 }}>
      <SectionCard title="Document Studio" subtitle="Every document customizable — prescription, laboratory, radiology, discharge, referral, death, birth, invoice, and more.">
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: 8 }}>
          {docs.map((d) => (
            <button key={d.id} onClick={() => toggle(d.id)} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 12px', borderRadius: 10, border: '1px solid #e3e9f2', background: d.enabled ? `${C.sky}0c` : '#f6f8fb', cursor: 'pointer', textAlign: 'left' }}>
              <FileText size={15} color={d.enabled ? C.sky : C.muted} />
              <span style={{ flex: 1, fontSize: 11.5, fontWeight: 700, color: C.navy }}>{d.name}</span>
              {d.enabled ? <CheckCircle2 size={15} color={C.green} /> : <span style={{ fontSize: 9.5, color: C.muted, fontWeight: 700 }}>OFF</span>}
            </button>
          ))}
        </div>
        <div style={{ marginTop: 12, padding: '10px 12px', borderRadius: 10, background: '#f0f4fa', fontSize: 11, color: C.slate, lineHeight: 1.6 }}>
          <b>Visual Editor:</b> Logo · Header · Patient Box · Barcode · QR · Doctor Signature · Footer · Disclaimer · Pagination · Watermark — configured once, applied to every generated PDF.
        </div>
      </SectionCard>
      <LivePreview identity={settings.identity} kit={settings.brandKit} doc="prescription" />
    </div>
  );
}

// ── Section 6 · Communications ─────────────────────────────────────────────────

function CommunicationsSection({ settings, patch }: { settings: FacilityAdminSettings; patch: (p: Partial<FacilityAdminSettings>) => void }) {
  const com = settings.communicationIdentity;
  const set = (key: keyof FacilityAdminSettings['communicationIdentity'], value: string) => patch({ communicationIdentity: { ...com, [key]: value } });
  const fields: { key: keyof FacilityAdminSettings['communicationIdentity']; label: string; icon: any }[] = [
    { key: 'emailDomain', label: 'Email Domain', icon: Mail },
    { key: 'smsSenderId', label: 'SMS Sender ID', icon: MessageSquare },
    { key: 'whatsapp', label: 'WhatsApp', icon: MessageSquare },
    { key: 'telegram', label: 'Telegram', icon: Send },
    { key: 'facebook', label: 'Facebook', icon: Megaphone },
    { key: 'twitter', label: 'Twitter', icon: Megaphone },
    { key: 'instagram', label: 'Instagram', icon: Megaphone },
    { key: 'linkedin', label: 'LinkedIn', icon: Megaphone },
    { key: 'website', label: 'Website', icon: Globe },
    { key: 'patientPortal', label: 'Patient Portal', icon: HeartHandshake },
    { key: 'staffPortal', label: 'Staff Portal', icon: Users },
    { key: 'mobileApp', label: 'Mobile App', icon: Phone },
    { key: 'emergencyHotline', label: 'Emergency Hotline', icon: Phone },
  ];

  return (
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: 18 }}>
      <SectionCard title="Communication Identity" subtitle="Everything the hospital sends — one identity across every channel.">
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 12 }}>
          {fields.map((f) => {
            const IconComp = f.icon;
            return <Field key={f.key} label={f.label} value={com[f.key]} icon={IconComp} onChange={(v) => set(f.key, v)} />;
          })}
        </div>
      </SectionCard>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
        <SectionCard title="Email Preview" subtitle="Exactly what patients receive.">
          <div style={{ borderRadius: 12, border: '1px solid #e3e9f2', overflow: 'hidden', background: '#fff' }}>
            <div style={{ height: 44, background: settings.brandKit.primary, display: 'flex', alignItems: 'center', padding: '0 16px', color: '#fff', fontWeight: 800, fontSize: 13 }}>{settings.identity.officialName}</div>
            <div style={{ padding: 16, fontSize: 12, color: C.navy, lineHeight: 1.7 }}>
              <b>Appointment Reminder</b><br />
              Dear Chris,<br /><br />
              This is a reminder of your appointment tomorrow at 09:30 in the Medicine Clinic.<br /><br />
              Regards,<br />
              Dr. John Otieno<br />
              <span style={{ color: C.sky }}>{com.emailDomain}</span>
            </div>
            <div style={{ padding: '10px 16px', borderTop: '1px solid #eef2f8', fontSize: 10, color: C.muted }}>{settings.brandKit.disclaimer}</div>
          </div>
        </SectionCard>
        <SectionCard title="SMS Preview" subtitle="Short, clean, branded.">
          <div style={{ borderRadius: 12, border: '1px solid #e3e9f2', background: '#f8fafd', padding: 16, fontSize: 12, color: C.navy, lineHeight: 1.8 }}>
            Appointment confirmed. Tomorrow, 09:30. Medicine Clinic. <b>{settings.identity.shortName}</b> — <span style={{ color: C.sky }}>{com.smsSenderId}</span>
          </div>
        </SectionCard>
      </div>
    </div>
  );
}

const Send = ({ size = 15 }: { size?: number }) => <Mail size={size} />;

// ── Section 7 · Hospital Stamp ─────────────────────────────────────────────────

function StampSection({ settings, patch }: { settings: FacilityAdminSettings; patch: (p: Partial<FacilityAdminSettings>) => void }) {
  const st = settings.hospitalStamp;
  const items: { key: keyof FacilityAdminSettings['hospitalStamp']; label: string; icon: any }[] = [
    { key: 'officialStamp', label: 'Official Stamp', icon: Stamp },
    { key: 'roundSeal', label: 'Round Seal', icon: Stamp },
    { key: 'drySeal', label: 'Dry Seal', icon: Stamp },
    { key: 'digitalSeal', label: 'Digital Seal', icon: Fingerprint },
    { key: 'qrVerification', label: 'QR Verification', icon: ScanQr },
  ];
  return (
    <SectionCard title="Hospital Stamp & Seal" subtitle="Official stamp, seals and QR verification — automatically applied to certified documents.">
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 10 }}>
        {items.map((it) => {
          const IconComp = it.icon;
          const on = st[it.key];
          return (
            <button key={it.key} onClick={() => patch({ hospitalStamp: { ...st, [it.key]: !on } })} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '12px', borderRadius: 12, border: '1px solid #e3e9f2', background: on ? `${C.sky}0c` : '#f6f8fb', cursor: 'pointer', textAlign: 'left' }}>
              <IconComp size={17} color={on ? C.sky : C.muted} />
              <span style={{ flex: 1, fontSize: 12, fontWeight: 700, color: C.navy }}>{it.label}</span>
              {on ? <CheckCircle2 size={15} color={C.green} /> : <span style={{ fontSize: 9.5, color: C.muted, fontWeight: 700 }}>OFF</span>}
            </button>
          );
        })}
      </div>
      <div style={{ marginTop: 14, display: 'flex', alignItems: 'center', gap: 14 }}>
        <div style={{ width: 96, height: 96, borderRadius: '50%', border: `3px solid ${settings.brandKit.primary}`, display: 'flex', alignItems: 'center', justifyContent: 'center', textAlign: 'center', fontSize: 8.5, fontWeight: 800, color: settings.brandKit.primary, lineHeight: 1.4, textTransform: 'uppercase' }}>
          {settings.identity.shortName}<br />••••••<br />Registry
        </div>
        <div style={{ fontSize: 11.5, color: C.slate, lineHeight: 1.7, flex: 1 }}>
          The official stamp is rendered on certificates, death certificates, employment letters and purchase orders. Seals are applied digitally and verified by QR.
        </div>
      </div>
    </SectionCard>
  );
}

const ScanQr = ({ size = 15 }: { size?: number }) => <Fingerprint size={size} />;

// ── Section 8 · Compliance Center ──────────────────────────────────────────────

function ComplianceSection({ settings, patch }: { settings: FacilityAdminSettings; patch: (p: Partial<FacilityAdminSettings>) => void }) {
  const items = settings.compliance.complianceItems;
  const set = (l: ComplianceItem[]) => patch({ compliance: { ...settings.compliance, complianceItems: l } });
  const update = (id: string, key: keyof ComplianceItem, value: string) => set(items.map((c) => c.id === id ? { ...c, [key]: value } : c));
  const toneFor = (s: string) => s === 'active' ? C.green : s === 'expiring' ? C.amber : s === 'expired' ? C.red : C.slate;
  const count = (s: string) => items.filter((c) => c.status === s).length;

  return (
    <SectionCard
      title="Compliance Center"
      subtitle="Licenses, accreditations and certifications with expiry alerts — the full regulatory identity."
      action={<Pill tone={C.green} label={`${count('active')} active · ${count('expiring')} expiring · ${count('expired')} expired`} />}
    >
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: 10 }}>
        {items.map((c) => (
          <div key={c.id} style={{ padding: 12, borderRadius: 12, border: '1px solid #e3e9f2', background: '#fff', display: 'flex', flexDirection: 'column', gap: 8 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <ShieldCheck size={15} color={toneFor(c.status)} />
              <span style={{ flex: 1, fontSize: 12.5, fontWeight: 800, color: C.navy }}>{c.name}</span>
              <select value={c.status} onChange={(e) => update(c.id, 'status', e.target.value)} style={{ padding: '4px 8px', borderRadius: 8, border: `1px solid ${C.border}`, fontSize: 10.5, fontWeight: 700, color: toneFor(c.status), background: '#fff', outline: 'none' }}>
                {['active', 'expiring', 'expired', 'pending'].map((s) => <option key={s} value={s}>{s}</option>)}
              </select>
            </div>
            {c.reference && <div style={{ fontSize: 10.5, color: C.muted }}>{c.reference}</div>}
            {c.expiresAt && <div style={{ fontSize: 10.5, fontWeight: 700, color: toneFor(c.status) }}>{c.expiresAt < Date.now() ? 'Expired' : 'Expires'} {new Date(c.expiresAt).toLocaleDateString()}</div>}
          </div>
        ))}
      </div>
    </SectionCard>
  );
}

// ── Section 9 · Public Website ─────────────────────────────────────────────────

function WebsiteSection({ settings, patch }: { settings: FacilityAdminSettings; patch: (p: Partial<FacilityAdminSettings>) => void }) {
  const w = settings.publicWebsite;
  const toggle = (id: string) => patch({ publicWebsite: { ...w, sections: w.sections.map((s) => s.id === id ? { ...s, enabled: !s.enabled } : s) } });
  return (
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: 18 }}>
      <SectionCard title="Public Website" subtitle="The hospital website, automatically built and branded — live preview." action={<Pill tone={w.enabled ? C.green : C.amber} label={w.enabled ? 'Published' : 'Hidden'} />}>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: 8 }}>
          {w.sections.map((s) => (
            <button key={s.id} onClick={() => toggle(s.id)} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 12px', borderRadius: 10, border: '1px solid #e3e9f2', background: s.enabled ? `${C.sky}0c` : '#f6f8fb', cursor: 'pointer', textAlign: 'left' }}>
              <Globe size={15} color={s.enabled ? C.sky : C.muted} />
              <span style={{ flex: 1, fontSize: 11.5, fontWeight: 700, color: C.navy, textTransform: 'capitalize' }}>{s.name}</span>
              {s.enabled ? <CheckCircle2 size={14} color={C.green} /> : <span style={{ fontSize: 9.5, color: C.muted, fontWeight: 700 }}>OFF</span>}
            </button>
          ))}
        </div>
      </SectionCard>
      <SectionCard title="Homepage Preview" subtitle="Branded, live, public.">
        <div style={{ borderRadius: 12, overflow: 'hidden', border: '1px solid #e3e9f2', background: '#fff' }}>
          <div style={{ height: 46, background: settings.brandKit.primary, display: 'flex', alignItems: 'center', padding: '0 16px', color: '#fff', fontSize: 13, fontWeight: 800 }}>{settings.identity.officialName}</div>
          <div style={{ padding: 20, background: 'linear-gradient(120deg,#0b2c4d,#0ea5e9)' }}>
            <div style={{ fontSize: 18, fontWeight: 800, color: '#fff' }}>Care that never sleeps</div>
            <div style={{ fontSize: 11.5, color: 'rgba(255,255,255,.8)', marginTop: 6, lineHeight: 1.6 }}>{settings.identity.mission}</div>
            <div style={{ marginTop: 14, display: 'flex', gap: 8 }}>
              <span style={{ padding: '6px 14px', borderRadius: 8, background: '#fff', color: settings.brandKit.primary, fontSize: 11, fontWeight: 800 }}>Book Appointment</span>
              <span style={{ padding: '6px 14px', borderRadius: 8, border: '1px solid rgba(255,255,255,.5)', color: '#fff', fontSize: 11, fontWeight: 800 }}>Emergency: {settings.communicationIdentity.emergencyHotline}</span>
            </div>
          </div>
        </div>
      </SectionCard>
    </div>
  );
}

// ── Section 10/11 · Patient & Staff Experience ────────────────────────────────

function ExperienceSection({ title, subtitle, list, onUpdate }: { title: string; subtitle: string; list: ExperienceTemplate[]; onUpdate: (l: ExperienceTemplate[]) => void }) {
  const update = (i: number, key: keyof ExperienceTemplate, value: string | boolean) => onUpdate(list.map((t, idx) => idx === i ? { ...t, [key]: value } : t));
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
      <SectionCard title={title} subtitle={subtitle}>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 12 }}>
          {list.map((t, i) => (
            <div key={t.id} style={{ padding: 14, borderRadius: 12, border: '1px solid #e3e9f2', background: t.active ? '#fbfdff' : '#f6f8fb' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
                {title.startsWith('Patient') ? <HeartHandshake size={15} color={t.active ? C.sky : C.muted} /> : <Gift size={15} color={t.active ? C.sky : C.muted} />}
                <span style={{ flex: 1, fontSize: 12.5, fontWeight: 800, color: C.navy }}>{t.name}</span>
                <ToggleChip label={t.active ? 'Active' : 'Paused'} on={t.active} onClick={() => update(i, 'active', !t.active)} tone={C.green} />
              </div>
              <Field label="Channel" value={t.channel} onChange={(v) => update(i, 'channel', v)} />
              <Field label="Subject" value={t.subject} onChange={(v) => update(i, 'subject', v)} />
              <Field area label="Body" value={t.body} onChange={(v) => update(i, 'body', v)} />
            </div>
          ))}
        </div>
      </SectionCard>
    </div>
  );
}

// ── Section 12 · Subscription & Growth ─────────────────────────────────────────

function SubscriptionSection({ settings, patch }: { settings: FacilityAdminSettings; patch: (p: Partial<FacilityAdminSettings>) => void }) {
  const sub = settings.subscription;
  const usage = Math.round((sub.users / Math.max(1, sub.seats)) * 100);
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
      <SectionCard title="Subscription" subtitle="Tier, seats, storage, AI credits, API calls, modules, license and renewal.">
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 12 }}>
          <StatCard label="Tier" value={sub.tier} tone={C.purple} icon={Rocket} />
          <StatCard label="Status" value={sub.status} tone={C.green} icon={CheckCircle2} />
          <StatCard label="Seats" value={String(sub.seats)} tone={C.navy} icon={Users} />
          <StatCard label="Users" value={String(sub.users)} tone={C.sky} icon={Users} />
          <StatCard label="Storage" value={`${sub.storageGb} GB`} tone={C.navy} icon={DatabaseBackup} />
          <StatCard label="AI Credits" value={sub.aiCredits.toLocaleString()} tone={C.sky} icon={Zap} />
          <StatCard label="API Calls" value={sub.apiCalls.toLocaleString()} tone={C.navy} icon={RefreshCw} />
        </div>
        <div style={{ marginTop: 14 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 11, fontWeight: 700, color: C.muted, marginBottom: 6 }}>
            <span>Growth · Users</span><span>{sub.users} / {sub.seats}</span>
          </div>
          <div style={{ height: 10, borderRadius: 6, background: '#eef2f8', overflow: 'hidden' }}>
            <div style={{ width: `${Math.min(100, usage)}%`, height: '100%', borderRadius: 6, background: usage > 90 ? C.amber : C.green }} />
          </div>
          <div style={{ fontSize: 11, color: C.muted, marginTop: 6 }}>{sub.seats - sub.users} seats remaining · Renewal: {sub.renewal}</div>
        </div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginTop: 14 }}>
          {sub.modules.map((m) => <span key={m} style={{ padding: '4px 10px', borderRadius: 14, background: `${C.sky}12`, color: C.sky, fontSize: 10.5, fontWeight: 700 }}>{m}</span>)}
        </div>
      </SectionCard>
    </div>
  );
}

// ── Section 13 · Disaster Recovery ─────────────────────────────────────────────

function DisasterSection({ settings, patch }: { settings: FacilityAdminSettings; patch: (p: Partial<FacilityAdminSettings>) => void }) {
  const dr = settings.disasterRecovery;
  const toggles: { key: keyof typeof dr; label: string }[] = [
    { key: 'backupEnabled', label: 'Automatic Backup' },
    { key: 'failoverEnabled', label: 'Failover' },
    { key: 'downtimeMode', label: 'Downtime Mode' },
    { key: 'realtimeReplication', label: 'Realtime Replication' },
    { key: 'geoBackup', label: 'Geo Backup' },
    { key: 'offlineMode', label: 'Offline Mode' },
    { key: 'disasterTestingEnabled', label: 'Disaster Testing' },
  ];
  const toggle = (key: keyof typeof dr) => patch({ disasterRecovery: { ...dr, [key]: !dr[key] } });
  return (
    <SectionCard title="Disaster Recovery" subtitle="Realtime replication, geo backup, recovery objectives, failover, offline mode and disaster testing." action={<Pill tone={C.green} label="Ready" />}>
      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 14 }}>
        {toggles.map((t) => <ToggleChip key={t.key} label={t.label} on={Boolean(dr[t.key])} onClick={() => toggle(t.key)} tone={C.green} />)}
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 12 }}>
        <StatCard label="Backup Frequency" value={`${dr.backupFrequencyHours}h`} tone={C.sky} icon={DatabaseBackup} />
        <StatCard label="Recovery Point Objective" value={dr.recoveryPointObjective} tone={C.navy} icon={RefreshCw} />
        <StatCard label="Recovery Time Objective" value={dr.recoveryTimeObjective} tone={C.navy} icon={Timer2} />
        <StatCard label="Last Backup" value={new Date(dr.lastBackupAt).toLocaleDateString()} tone={C.navy} icon={DatabaseBackup} />
        <StatCard label="Last Recovery Test" value={new Date(dr.recoveryTestingAt).toLocaleDateString()} tone={C.navy} icon={ShieldCheck} />
      </div>
      <div style={{ marginTop: 14, display: 'flex', gap: 10, flexWrap: 'wrap' }}>
        <button style={{ padding: '9px 16px', borderRadius: 8, border: 'none', background: C.sky, color: '#fff', fontSize: 12, fontWeight: 700, cursor: 'pointer' }}><RefreshCw size={13} style={{ verticalAlign: '-2px', marginRight: 6 }} />Run Disaster Test</button>
        <button style={{ padding: '9px 16px', borderRadius: 8, border: `1px solid ${C.border}`, background: '#fff', color: C.slate, fontSize: 12, fontWeight: 700, cursor: 'pointer' }}>Downtime Simulation</button>
      </div>
    </SectionCard>
  );
}

const Timer2 = ({ size = 15 }: { size?: number }) => <RefreshCw size={size} />;

// ── Section 14 · Identity Analytics ────────────────────────────────────────────

function AnalyticsSection({ settings }: { settings: FacilityAdminSettings }) {
  return (
    <SectionCard title="Identity Analytics" subtitle="Document downloads, most printed, most signed, satisfaction, website traffic, portal usage and communication delivery.">
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 12 }}>
        {settings.analytics.map((a) => (
          <div key={a.id} style={{ background: '#fff', border: '1px solid #e3e9f2', borderRadius: 14, padding: '16px 18px' }}>
            <div style={{ fontSize: 22, fontWeight: 800, color: C.sky }}>{a.value.toLocaleString()}{a.unit ? <span style={{ fontSize: 12, color: C.muted, fontWeight: 700 }}> {a.unit}</span> : null}</div>
            <div style={{ fontSize: 10, color: C.muted, marginTop: 2, textTransform: 'uppercase', letterSpacing: '.04em' }}>{a.label}</div>
          </div>
        ))}
      </div>
    </SectionCard>
  );
}

// ── Live preview ───────────────────────────────────────────────────────────────

function LivePreview({ identity, kit, doc }: { identity: FacilityAdminSettings['identity']; kit: FacilityAdminSettings['brandKit']; doc: 'letterhead' | 'discharge' | 'prescription' }) {
  const title = doc === 'letterhead' ? 'Letterhead' : doc === 'discharge' ? 'Patient Discharge Summary' : 'Prescription';
  const fields = doc === 'discharge'
    ? [['Patient', 'M. Anyango'], ['Date', '06 Aug 2026'], ['Doctor', 'Dr. J. Otieno']]
    : doc === 'prescription'
      ? [['Patient', 'M. Anyango'], ['Date', '06 Aug 2026'], ['Rx', 'Amoxicillin 500mg TDS x7d']]
      : [['Date', '06 Aug 2026'], ['Ref', 'AUTH/2026/01482']];
  return (
    <SectionCard title={`Live Preview · ${title}`} subtitle="Updates instantly as you edit.">
      <div style={{ borderRadius: 12, border: '1px solid #e3e9f2', background: '#fff', overflow: 'hidden' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '12px 16px', borderBottom: `3px solid ${kit.primary}` }}>
          <div style={{ width: 38, height: 38, borderRadius: 9, background: kit.primary, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontSize: 15, fontWeight: 800 }}>{identity.shortName.slice(0, 2).toUpperCase() || 'H'}</div>
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: 13.5, fontWeight: 800, color: kit.primary }}>{identity.officialName}</div>
            <div style={{ fontSize: 10, color: C.muted }}>{identity.physicalAddress} · {identity.postalAddress}</div>
          </div>
          <div style={{ fontSize: 9, color: C.muted, textAlign: 'right' }}>{identity.taxPin ? `PIN ${identity.taxPin}` : ''}<br />{identity.registrationNumber}</div>
        </div>
        <div style={{ padding: 16 }}>
          <div style={{ fontSize: 12, fontWeight: 800, color: C.navy, marginBottom: 10 }}>{title}</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {fields.map(([k, v]) => (
              <div key={k} style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px dashed #eef2f8', paddingBottom: 6, fontSize: 11.5 }}>
                <span style={{ color: C.muted }}>{k}</span><span style={{ fontWeight: 700, color: C.navy }}>{v}</span>
              </div>
            ))}
          </div>
          <div style={{ marginTop: 14, display: 'flex', gap: 10, alignItems: 'flex-end', justifyContent: 'flex-end' }}>
            <div style={{ textAlign: 'center' }}>
              <div style={{ width: 64, height: 44, borderBottom: `1.5px solid ${C.navy}`, fontSize: 9, color: C.muted, display: 'flex', alignItems: 'flex-end', justifyContent: 'center', paddingBottom: 4 }}>Dr. J. Otieno</div>
              <div style={{ fontSize: 9, color: C.muted, marginTop: 4 }}>Signatory</div>
            </div>
          </div>
        </div>
        <div style={{ padding: '8px 16px', borderTop: '1px solid #eef2f8', fontSize: 9, color: C.muted, lineHeight: 1.5 }}>{kit.disclaimer}</div>
      </div>
    </SectionCard>
  );
}

// ── Primitives ─────────────────────────────────────────────────────────────────

function SectionCard({ title, subtitle, children, action }: { title: string; subtitle?: string; children: React.ReactNode; action?: React.ReactNode }) {
  return (
    <div style={{ background: '#fff', border: `1px solid ${C.border}`, borderRadius: 14, padding: 18 }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12, flexWrap: 'wrap', gap: 8 }}>
        <div>
          <div style={{ fontSize: 15, fontWeight: 800, color: C.navy, margin: 0 }}>{title}</div>
          {subtitle && <div style={{ fontSize: 11, color: C.muted, marginTop: 2 }}>{subtitle}</div>}
        </div>
        {action}
      </div>
      {children}
    </div>
  );
}

const inputStyle: React.CSSProperties = { width: '100%', height: 34, borderRadius: 8, border: `1px solid ${C.border}`, padding: '0 10px', fontSize: 12, outline: 'none', background: '#fff', color: C.navy, fontFamily: 'inherit' };

function Label({ children }: { children: React.ReactNode }) {
  return <div style={{ fontSize: 10, color: C.muted, display: 'block', marginBottom: 4, textTransform: 'uppercase', fontWeight: 700 }}>{children}</div>;
}

function Field({ label, value, onChange, area, icon: Icon }: { label: string; value: string; onChange: (v: string) => void; area?: boolean; icon?: any }) {
  return (
    <div>
      <Label>{label}</Label>
      {area
        ? <textarea value={value} onChange={(e) => onChange(e.target.value)} rows={2} style={{ ...inputStyle, height: 'auto', padding: '8px 10px', fontFamily: 'inherit' }} />
        : <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
            {Icon && <Icon size={14} color={C.muted} />}
            <input value={value} onChange={(e) => onChange(e.target.value)} style={{ ...inputStyle, flex: 1 }} />
          </div>}
    </div>
  );
}

function ToggleChip({ label, on, onClick, tone }: { label: string; on: boolean; onClick: () => void; tone?: string }) {
  const c = tone || C.sky;
  return <button onClick={onClick} style={{ padding: '7px 12px', borderRadius: 20, border: 'none', background: on ? `${c}18` : '#eef2f7', color: on ? c : C.slate, fontSize: 11, fontWeight: 700, cursor: 'pointer' }}>{on ? '✓ ' : ''}{label}</button>;
}

function StatCard({ label, value, tone, icon: Icon }: { label: string; value: string | number; tone?: string; icon?: any }) {
  const c = tone || C.navy;
  return (
    <div style={{ background: '#fff', border: '1px solid #e3e9f2', borderRadius: 14, padding: '14px 16px' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 8 }}>
        {Icon && <span style={{ width: 26, height: 26, borderRadius: 8, background: `${c}16`, display: 'flex', alignItems: 'center', justifyContent: 'center' }}><Icon size={14} color={c} /></span>}
      </div>
      <div style={{ fontSize: 19, fontWeight: 800, color: c, textTransform: 'capitalize' }}>{value}</div>
      <div style={{ fontSize: 10, color: C.muted, marginTop: 2, textTransform: 'uppercase', letterSpacing: '.04em' }}>{label}</div>
    </div>
  );
}

function AddBtn({ label, onClick }: { label: string; onClick: () => void }) {
  return <button onClick={onClick} style={{ padding: '7px 14px', borderRadius: 8, border: 'none', background: C.sky, color: '#fff', fontSize: 11, fontWeight: 700, cursor: 'pointer' }}>{label}</button>;
}

function Pill({ label, tone }: { label: string; tone: string }) {
  return <span style={{ padding: '4px 10px', borderRadius: 20, background: `${tone}16`, fontSize: 10.5, fontWeight: 800, color: tone }}>{label}</span>;
}
