import type { DiseaseNode, FeatureRecord } from '../../diseaseNode';
import { getFeature, getLrPlus, getLrMinus } from '../../features/featureLibrary';

function feat(id: string, sens: number, spec: number, overrides?: Partial<FeatureRecord>): FeatureRecord {
  const base = getFeature(id);
  return { ...base, sensitivity: sens, specificity: spec, LR_positive: getLrPlus({ ...base, sensitivity: sens, specificity: spec }), LR_negative: getLrMinus({ ...base, sensitivity: sens, specificity: spec }), ...overrides };
}
function sym(id: string, sens: number, spec: number, overrides?: Partial<FeatureRecord>): FeatureRecord {
  return feat(id, sens, spec, { ...overrides, category: 'symptom' });
}

export const constipation: DiseaseNode = {
  id: 'constipation', name: 'Constipation / Faecal Impaction', icdCode: 'K59.0', system: 'medical',
  organSystem: 'GI', acuity: 'routine', acuityTier: 4,
  epidemiology: { ageMin: 1, ageMax: 90, agePeak: [60, 80], sexRisk: { male: 0.7, female: 1.3 }, backgroundPrevalence: 0.15, riskFactors: [{ featureId: 'recent_travel', label: 'Low fibre diet', LR_positive: 2.0, prevalenceInDisease: 0.3 }, { featureId: 'prior_abdominal_surgery', label: 'Opioid use', LR_positive: 3.0, prevalenceInDisease: 0.2 }, { featureId: 'constipation', label: 'Immobility', LR_positive: 2.5, prevalenceInDisease: 0.25 }, { featureId: 'anorexia', label: 'Dehydration', LR_positive: 1.5, prevalenceInDisease: 0.3 }] },
  pathophysiology: { mechanism: 'Infrequent or difficult passage of stool due to prolonged colonic transit, pelvic floor dysfunction, or dietary factors. Faecal impaction can present with overflow diarrhoea, abdominal distension, and vomiting in severe cases.', timelineStages: [{ stageId: 1, label: 'Early constipation', typicalHoursFromOnset: [0, 72], dominantSymptoms: [sym('constipation', 0.9, 0.5), sym('pain_character', 0.3, 0.5)], examFindings: [], severityTrajectory: 'worsening', painCharacterTypical: 'Cramping lower abdominal pain', painLocationTypical: 'Left lower quadrant or suprapubic', painRadiationTypical: 'None' }, { stageId: 2, label: 'Established impaction', typicalHoursFromOnset: [72, 168], dominantSymptoms: [sym('constipation', 0.9, 0.5), sym('abdominal_distension', 0.6, 0.6), sym('bloating', 0.7, 0.5)], examFindings: [], severityTrajectory: 'worsening', painCharacterTypical: 'Constant dull ache', painLocationTypical: 'Diffuse lower abdomen', painRadiationTypical: 'None' }], progressionRule: 'Without treatment, progresses to faecal impaction with overflow incontinence.' },
  features: { symptoms: [sym('constipation', 0.9, 0.5, { stageRelevance: [1, 2] }), sym('pain_character', 0.3, 0.5, { stageRelevance: [1, 2] }), sym('pain_initial_location', 0.3, 0.5, { stageRelevance: [1] }), sym('pain_location_now', 0.3, 0.4, { stageRelevance: [2] }), sym('abdominal_distension', 0.6, 0.6, { stageRelevance: [2] }), sym('bloating', 0.7, 0.5, { stageRelevance: [1, 2] }), sym('anorexia', 0.3, 0.5, { stageRelevance: [2] }), sym('nausea', 0.3, 0.5, { stageRelevance: [2] }), sym('vomiting', 0.15, 0.7, { stageRelevance: [2] }), sym('constipation_duration_days', 0.6, 0.6, { stageRelevance: [1] }), sym('constipation_stool_consistency', 0.7, 0.6, { stageRelevance: [1] }), sym('constipation_straining', 0.7, 0.5, { stageRelevance: [1] }), sym('constipation_incomplete_evacuation', 0.6, 0.5, { stageRelevance: [1] }), sym('constipation_laxative_use', 0.5, 0.6, { stageRelevance: [1] })], signs: [], investigations: [] },
  importantNegatives: { rulingOut: [sym('vomiting', 0, 0, { sensitivity: 0, specificity: 0, LR_negative: 0.6 }), sym('hematochezia', 0, 0, { sensitivity: 0, specificity: 0, LR_negative: 0.5 })], supporting: [] },
  differential: { mimics: ['intestinal_obstruction', 'ibs', 'colon_cancer', 'constipation_simple'], distinguishingFeatures: [{ fromDiseaseId: 'intestinal_obstruction', featureIds: ['vomiting', 'obstipation', 'abdominal_distension'] }, { fromDiseaseId: 'colon_cancer', featureIds: ['weight_loss', 'hematochezia', 'family_history_gi_cancer'] }], neverCloseConditions: ['intestinal_obstruction'] },
  complications: [{ name: 'Faecal impaction', warningFeatures: ['abdominal_distension', 'vomiting'], riskFactors: ['opioid_use', 'immobility'], timeWindowHours: [72, 336], severityTier: 'moderate', description: 'Hardened stool in rectum unable to pass spontaneously.' }, { name: 'Overflow incontinence', warningFeatures: ['diarrhea'], riskFactors: ['chronic_constipation'], timeWindowHours: [168, 2160], severityTier: 'mild', description: 'Liquid stool leaking around impacted faeces.' }],
  clinicalScores: [],
  redFlagFeatureIds: ['hematochezia', 'weight_loss'],
};

export const infectiousColitis: DiseaseNode = {
  id: 'infectious_colitis', name: 'Infectious Colitis', icdCode: 'A09', system: 'medical',
  organSystem: 'GI', acuity: 'semi_urgent', acuityTier: 3,
  epidemiology: { ageMin: 1, ageMax: 90, agePeak: [20, 40], sexRisk: { male: 1, female: 1 }, backgroundPrevalence: 0.02, riskFactors: [{ featureId: 'recent_travel', label: 'Recent travel', LR_positive: 3.0, prevalenceInDisease: 0.3 }, { featureId: 'sick_contacts', label: 'Sick contacts', LR_positive: 4.0, prevalenceInDisease: 0.4 }, { featureId: 'hiv_status', label: 'Immunosuppression', LR_positive: 2.0, prevalenceInDisease: 0.1 }] },
  pathophysiology: { mechanism: 'Inflammation of the colon caused by bacterial (Salmonella, Shigella, Campylobacter, E. coli, C. difficile), viral, or parasitic pathogens. Presents with diarrhoea, abdominal cramps, and tenesmus. Vomiting is variable depending on pathogen.', timelineStages: [{ stageId: 1, label: 'Acute colitis', typicalHoursFromOnset: [0, 48], dominantSymptoms: [sym('diarrhea', 0.9, 0.5), sym('fever', 0.7, 0.5), sym('pain_character', 0.6, 0.5)], examFindings: [], severityTrajectory: 'worsening', painCharacterTypical: 'Cramping lower abdominal pain', painLocationTypical: 'Lower abdomen, often LLQ', painRadiationTypical: 'None' }], progressionRule: 'Most cases self-limited in 3\u20137 days. C. difficile may recur. Severe cases progress to toxic megacolon.' },
  features: { symptoms: [sym('diarrhea', 0.9, 0.5, { stageRelevance: [1] }), sym('fever', 0.7, 0.5, { stageRelevance: [1] }), sym('fever_chills', 0.5, 0.6, { stageRelevance: [1] }), sym('pain_character', 0.6, 0.5, { stageRelevance: [1] }), sym('pain_initial_location', 0.4, 0.5, { stageRelevance: [1] }), sym('pain_location_now', 0.4, 0.5, { stageRelevance: [1] }), sym('hematochezia', 0.5, 0.7, { stageRelevance: [1] }), sym('tenesmus', 0.5, 0.6, { stageRelevance: [1] }), sym('mucus_stool', 0.4, 0.6, { stageRelevance: [1] }), sym('nausea', 0.6, 0.5, { stageRelevance: [1] }), sym('vomiting', 0.4, 0.6, { stageRelevance: [1] }), sym('anorexia', 0.5, 0.5, { stageRelevance: [1] }), sym('recent_travel', 0.3, 0.7, { stageRelevance: [1] }), sym('prior_abdominal_surgery', 0.1, 0.6, { stageRelevance: [1] }), sym('diarrhea_duration_days', 0.6, 0.5, { stageRelevance: [1] }), sym('diarrhea_frequency', 0.7, 0.5, { stageRelevance: [1] }), sym('diarrhea_consistency', 0.6, 0.5, { stageRelevance: [1] })], signs: [], investigations: [] },
  importantNegatives: { rulingOut: [], supporting: [] },
  differential: { mimics: ['ulcerative_colitis', 'crohns_disease', 'diverticulitis', 'appendicitis', 'amoebic_colitis'], distinguishingFeatures: [{ fromDiseaseId: 'ulcerative_colitis', featureIds: ['recent_travel', 'fever'] }, { fromDiseaseId: 'diverticulitis', featureIds: ['diarrhea', 'hematochezia'] }], neverCloseConditions: [] },
  complications: [{ name: 'Toxic megacolon', warningFeatures: ['abdominal_distension', 'fever', 'hematochezia'], riskFactors: ['c_difficile', 'immunosuppression'], timeWindowHours: [48, 168], severityTier: 'critical', description: 'Colonic dilation with systemic toxicity requiring surgical intervention.' }],
  clinicalScores: [],
  redFlagFeatureIds: ['hematochezia', 'syncope'],
};

export const epididymitis: DiseaseNode = {
  id: 'epididymitis', name: 'Epididymitis', icdCode: 'N45.0', system: 'surgical',
  organSystem: 'urological', acuity: 'semi_urgent', acuityTier: 3,
  epidemiology: { ageMin: 15, ageMax: 60, agePeak: [20, 40], sexRisk: { male: 1, female: 0 }, backgroundPrevalence: 0.003, riskFactors: [{ featureId: 'recent_travel', label: 'Sexually transmitted infection', LR_positive: 3.0, prevalenceInDisease: 0.4 }, { featureId: 'dysuria', label: 'Urinary tract infection', LR_positive: 2.5, prevalenceInDisease: 0.3 }, { featureId: 'prior_abdominal_surgery', label: 'Recent catheterisation', LR_positive: 2.0, prevalenceInDisease: 0.05 }] },
  pathophysiology: { mechanism: 'Inflammation of the epididymis, usually from ascending infection (STI in young men, coliforms in older men). Presents with gradual onset of testicular pain and swelling. Nausea/vomiting are mild and secondary to pain.', timelineStages: [{ stageId: 1, label: 'Acute epididymitis', typicalHoursFromOnset: [0, 72], dominantSymptoms: [sym('testicular_pain', 0.9, 0.5), sym('dysuria', 0.6, 0.5), sym('fever', 0.5, 0.5)], examFindings: [], severityTrajectory: 'worsening', painCharacterTypical: 'Dull ache in the testicle', painLocationTypical: 'Scrotal/testicular', painRadiationTypical: 'Groin' }], progressionRule: 'Resolves with antibiotics. Abscess formation if untreated.' },
  features: { symptoms: [sym('testicular_pain', 0.9, 0.5, { stageRelevance: [1] }), sym('scrotal_swelling', 0.7, 0.6, { stageRelevance: [1] }), sym('dysuria', 0.6, 0.5, { stageRelevance: [1] }), sym('urinary_frequency', 0.5, 0.5, { stageRelevance: [1] }), sym('fever', 0.5, 0.5, { stageRelevance: [1] }), sym('fever_chills', 0.3, 0.6, { stageRelevance: [1] }), sym('nausea', 0.3, 0.5, { stageRelevance: [1] }), sym('pain_onset', 0.4, 0.5, { stageRelevance: [1] }), sym('pain_character', 0.4, 0.5, { stageRelevance: [1] })], signs: [], investigations: [] },
  importantNegatives: { rulingOut: [], supporting: [] },
  differential: { mimics: ['testicular_torsion', 'incarcerated_hernia', 'ureteric_colic'], distinguishingFeatures: [{ fromDiseaseId: 'testicular_torsion', featureIds: ['pain_onset', 'fever', 'dysuria'] }], neverCloseConditions: ['testicular_torsion'] },
  complications: [{ name: 'Epididymal abscess', warningFeatures: ['fever', 'scrotal_swelling'], riskFactors: [], timeWindowHours: [72, 336], severityTier: 'moderate', description: 'Localised abscess requiring drainage.' }],
  clinicalScores: [],
  redFlagFeatureIds: [],
};

export const adenomyosis: DiseaseNode = {
  id: 'adenomyosis', name: 'Adenomyosis', icdCode: 'N80.0', system: 'gynaecological',
  organSystem: 'reproductive_female', acuity: 'routine', acuityTier: 4,
  epidemiology: { ageMin: 30, ageMax: 55, agePeak: [40, 50], sexRisk: { male: 0, female: 1 }, backgroundPrevalence: 0.15, riskFactors: [{ featureId: 'prior_abdominal_surgery', label: 'Multiparity', LR_positive: 2.0, prevalenceInDisease: 0.5 }, { featureId: 'prior_abdominal_surgery', label: 'Prior uterine surgery', LR_positive: 1.5, prevalenceInDisease: 0.2 }] },
  pathophysiology: { mechanism: 'Ectopic endometrial tissue within the myometrium causing an enlarged, tender uterus. Presents with heavy menstrual bleeding, dysmenorrhea, and chronic pelvic pain. Nausea is secondary to severe cramping.', timelineStages: [{ stageId: 1, label: 'Symptomatic adenomyosis', typicalHoursFromOnset: [0, 720], dominantSymptoms: [sym('dysmenorrhea', 0.8, 0.5), sym('menorrhagia', 0.7, 0.5), sym('pain_character', 0.5, 0.5)], examFindings: [], severityTrajectory: 'worsening', painCharacterTypical: 'Cramping pelvic pain, worse during menses', painLocationTypical: 'Suprapubic/pelvic', painRadiationTypical: 'Lower back or thighs' }], progressionRule: 'Chronic, progressive until menopause.' },
  features: { symptoms: [sym('dysmenorrhea', 0.8, 0.5, { stageRelevance: [1] }), sym('menorrhagia', 0.7, 0.5, { stageRelevance: [1] }), sym('pain_character', 0.5, 0.5, { stageRelevance: [1] }), sym('pain_initial_location', 0.4, 0.5, { stageRelevance: [1] }), sym('pain_location_now', 0.4, 0.5, { stageRelevance: [1] }), sym('dyspareunia', 0.4, 0.6, { stageRelevance: [1] }), sym('nausea', 0.4, 0.5, { stageRelevance: [1] }), sym('fatigue', 0.5, 0.5, { stageRelevance: [1] }), sym('vaginal_bleeding_volume', 0.6, 0.5, { stageRelevance: [1] }), sym('vaginal_bleeding_duration_days', 0.5, 0.5, { stageRelevance: [1] })], signs: [], investigations: [] },
  importantNegatives: { rulingOut: [sym('pregnancy_status', 0, 0, { sensitivity: 0, specificity: 0, LR_negative: 0.3 })], supporting: [] },
  differential: { mimics: ['endometriosis', 'fibroids', 'ovarian_cancer', 'pid'], distinguishingFeatures: [{ fromDiseaseId: 'endometriosis', featureIds: ['dyspareunia', 'pain_worsening_factors'] }, { fromDiseaseId: 'fibroids', featureIds: ['menorrhagia', 'pain_character'] }], neverCloseConditions: [] },
  complications: [{ name: 'Anaemia', warningFeatures: ['fatigue', 'menorrhagia'], riskFactors: ['heavy_bleeding'], timeWindowHours: [2160, 21600], severityTier: 'mild', description: 'Iron deficiency anaemia from chronic heavy menstrual bleeding.' }],
  clinicalScores: [],
  redFlagFeatureIds: [],
};

export const ovarianCancer: DiseaseNode = {
  id: 'ovarian_cancer', name: 'Ovarian Cancer', icdCode: 'C56', system: 'gynaecological',
  organSystem: 'reproductive_female', acuity: 'urgent', acuityTier: 2,
  epidemiology: { ageMin: 30, ageMax: 85, agePeak: [55, 75], sexRisk: { male: 0, female: 1 }, backgroundPrevalence: 0.002, riskFactors: [{ featureId: 'family_history_gi_cancer', label: 'Family history', LR_positive: 3.0, prevalenceInDisease: 0.15 }, { featureId: 'known_cancer', label: 'BRCA mutation', LR_positive: 5.0, prevalenceInDisease: 0.1 }, { featureId: 'prior_abdominal_surgery', label: 'Nulliparity', LR_positive: 1.5, prevalenceInDisease: 0.3 }] },
  pathophysiology: { mechanism: 'Malignancy arising from ovarian epithelium. Presents insidiously with abdominal distension, bloating, early satiety, and pelvic pain. Late-stage disease causes ascites, omental cake, and bowel obstruction.', timelineStages: [{ stageId: 1, label: 'Early disease', typicalHoursFromOnset: [0, 4320], dominantSymptoms: [sym('bloating', 0.6, 0.5), sym('pain_character', 0.3, 0.5)], examFindings: [], severityTrajectory: 'worsening', painCharacterTypical: 'Vague pelvic discomfort', painLocationTypical: 'Suprapubic/pelvic', painRadiationTypical: 'None' }, { stageId: 2, label: 'Advanced disease', typicalHoursFromOnset: [2160, 21600], dominantSymptoms: [sym('abdominal_distension', 0.8, 0.6), sym('weight_loss', 0.6, 0.7), sym('anorexia', 0.7, 0.5)], examFindings: [], severityTrajectory: 'worsening', painCharacterTypical: 'Persistent pelvic or abdominal pain', painLocationTypical: 'Diffuse abdomen', painRadiationTypical: 'None' }], progressionRule: 'Silent until advanced. 5-year survival <50% for late-stage disease.' },
  features: { symptoms: [sym('bloating', 0.6, 0.5, { stageRelevance: [1] }), sym('abdominal_distension', 0.8, 0.6, { stageRelevance: [2] }), sym('pain_character', 0.3, 0.5, { stageRelevance: [1, 2] }), sym('pain_initial_location', 0.3, 0.5, { stageRelevance: [1] }), sym('pain_location_now', 0.4, 0.5, { stageRelevance: [2] }), sym('weight_loss', 0.6, 0.7, { stageRelevance: [2] }), sym('weight_loss_amount_kg', 0.5, 0.6, { stageRelevance: [2] }), sym('weight_loss_period_weeks', 0.5, 0.5, { stageRelevance: [2] }), sym('anorexia', 0.7, 0.5, { stageRelevance: [1, 2] }), sym('nausea', 0.4, 0.5, { stageRelevance: [2] }), sym('vomiting', 0.2, 0.7, { stageRelevance: [2] }), sym('fatigue', 0.6, 0.5, { stageRelevance: [1, 2] }), sym('last_menstrual_period', 0.3, 0.5, { stageRelevance: [1] }), sym('family_history_gi_cancer', 0.15, 0.9, { stageRelevance: [1] }), sym('known_cancer', 0.1, 0.8, { stageRelevance: [1] })], signs: [], investigations: [] },
  importantNegatives: { rulingOut: [], supporting: [] },
  differential: { mimics: ['ibs', 'endometriosis', 'ovarian_cyst_rupture', 'functional_abdominal_pain'], distinguishingFeatures: [{ fromDiseaseId: 'ibs', featureIds: ['weight_loss', 'abdominal_distension', 'age'] }], neverCloseConditions: [] },
  complications: [{ name: 'Bowel obstruction', warningFeatures: ['vomiting', 'abdominal_distension', 'obstipation'], riskFactors: ['advanced_disease'], timeWindowHours: [4320, 21600], severityTier: 'severe', description: 'Malignant bowel obstruction requiring palliative surgery.' }],
  clinicalScores: [],
  redFlagFeatureIds: ['weight_loss', 'abdominal_distension'],
};

export const miscarriage: DiseaseNode = {
  id: 'miscarriage', name: 'Miscarriage / Spontaneous Abortion', icdCode: 'O03', system: 'obstetric',
  organSystem: 'reproductive_female', acuity: 'urgent', acuityTier: 2,
  epidemiology: { ageMin: 15, ageMax: 45, agePeak: [25, 35], sexRisk: { male: 0, female: 1 }, backgroundPrevalence: 0.15, riskFactors: [{ featureId: 'smoking', label: 'Advanced maternal age', LR_positive: 2.0, prevalenceInDisease: 0.3 }, { featureId: 'prior_abdominal_surgery', label: 'Previous miscarriage', LR_positive: 2.5, prevalenceInDisease: 0.2 }, { featureId: 'smoking', label: 'Smoking', LR_positive: 1.5, prevalenceInDisease: 0.2 }] },
  pathophysiology: { mechanism: 'Spontaneous pregnancy loss before 20 weeks gestation. Presents with vaginal bleeding, cramping abdominal pain, and passage of tissue. Nausea/vomiting of pregnancy may persist or abruptly resolve.', timelineStages: [{ stageId: 1, label: 'Threatened miscarriage', typicalHoursFromOnset: [0, 24], dominantSymptoms: [sym('vaginal_bleeding', 0.9, 0.5), sym('pain_character', 0.5, 0.5)], examFindings: [], severityTrajectory: 'worsening', painCharacterTypical: 'Cramping suprapubic pain', painLocationTypical: 'Suprapubic', painRadiationTypical: 'Lower back' }, { stageId: 2, label: 'Inevitable / complete miscarriage', typicalHoursFromOnset: [24, 72], dominantSymptoms: [sym('vaginal_bleeding', 0.9, 0.5), sym('pain_severity', 0.6, 0.5)], examFindings: [], severityTrajectory: 'worsening', painCharacterTypical: 'Heavy cramping, passage of tissue', painLocationTypical: 'Suprapubic', painRadiationTypical: 'Lower back' }], progressionRule: 'Threatened may resolve; inevitable progresses to complete or incomplete miscarriage.' },
  features: { symptoms: [sym('vaginal_bleeding', 0.9, 0.5, { stageRelevance: [1, 2] }), sym('vaginal_bleeding_volume', 0.6, 0.5, { stageRelevance: [1, 2] }), sym('vaginal_bleeding_color', 0.4, 0.5, { stageRelevance: [1, 2] }), sym('pain_character', 0.5, 0.5, { stageRelevance: [1, 2] }), sym('pain_severity', 0.6, 0.5, { stageRelevance: [2] }), sym('pain_initial_location', 0.4, 0.5, { stageRelevance: [1] }), sym('pain_location_now', 0.4, 0.5, { stageRelevance: [2] }), sym('last_menstrual_period', 0.8, 0.6, { stageRelevance: [1] }), sym('pregnancy_status', 0.9, 0.8, { stageRelevance: [1] }), sym('nausea', 0.4, 0.5, { stageRelevance: [1] }), sym('vomiting', 0.2, 0.6, { stageRelevance: [1] }), sym('syncope', 0.3, 0.8, { stageRelevance: [2] })], signs: [], investigations: [] },
  importantNegatives: { rulingOut: [sym('pregnancy_status', 0, 0, { sensitivity: 0, specificity: 0, LR_negative: 0.02, label: 'Not pregnant \u2014 miscarriage excluded' })], supporting: [] },
  differential: { mimics: ['ectopic_pregnancy', 'placental_abruption', 'preterm_labour', 'ovarian_cyst_rupture'], distinguishingFeatures: [{ fromDiseaseId: 'ectopic_pregnancy', featureIds: ['pain_onset', 'vaginal_bleeding', 'syncope'] }], neverCloseConditions: ['ectopic_pregnancy'] },
  complications: [{ name: 'Haemorrhage', warningFeatures: ['syncope', 'vaginal_bleeding_volume'], riskFactors: [], timeWindowHours: [0, 24], severityTier: 'severe', description: 'Life-threatening haemorrhage requiring emergency evacuation.' }, { name: 'Septic miscarriage', warningFeatures: ['fever', 'vaginal_discharge'], riskFactors: ['retained_tissue'], timeWindowHours: [24, 168], severityTier: 'critical', description: 'Infection of retained products of conception.' }],
  clinicalScores: [],
  redFlagFeatureIds: ['syncope'],
};

export const placentaPraevia: DiseaseNode = {
  id: 'placenta_praevia', name: 'Placenta Praevia', icdCode: 'O44', system: 'obstetric',
  organSystem: 'reproductive_female', acuity: 'urgent', acuityTier: 2,
  epidemiology: { ageMin: 15, ageMax: 45, agePeak: [25, 35], sexRisk: { male: 0, female: 1 }, backgroundPrevalence: 0.005, riskFactors: [{ featureId: 'prior_abdominal_surgery', label: 'Previous caesarean section', LR_positive: 3.0, prevalenceInDisease: 0.3 }, { featureId: 'prior_abdominal_surgery', label: 'Multiparity', LR_positive: 2.0, prevalenceInDisease: 0.5 }, { featureId: 'smoking', label: 'Advanced maternal age', LR_positive: 2.0, prevalenceInDisease: 0.3 }, { featureId: 'smoking', label: 'Smoking', LR_positive: 1.5, prevalenceInDisease: 0.2 }] },
  pathophysiology: { mechanism: 'Placenta partially or completely covering the internal cervical os. Presents with painless vaginal bleeding in the third trimester. Bleeding is often recurrent and can be catastrophic.', timelineStages: [{ stageId: 1, label: 'Antepartum haemorrhage', typicalHoursFromOnset: [0, 72], dominantSymptoms: [sym('vaginal_bleeding', 0.9, 0.5)], examFindings: [], severityTrajectory: 'worsening', painCharacterTypical: 'Painless \u2014 no abdominal pain', painLocationTypical: 'None', painRadiationTypical: 'None' }], progressionRule: 'Recurrent bleeding episodes. Emergency caesarean section required.' },
  features: { symptoms: [sym('vaginal_bleeding', 0.9, 0.5, { stageRelevance: [1] }), sym('vaginal_bleeding_volume', 0.6, 0.5, { stageRelevance: [1] }), sym('vaginal_bleeding_color', 0.3, 0.5, { stageRelevance: [1] }), sym('pregnancy_status', 0.95, 0.9, { stageRelevance: [1] }), sym('pregnancy_gestational_age', 0.8, 0.7, { stageRelevance: [1] }), sym('last_menstrual_period', 0.7, 0.5, { stageRelevance: [1] }), sym('syncope', 0.3, 0.8, { stageRelevance: [1] }), sym('prior_abdominal_surgery', 0.3, 0.7, { stageRelevance: [1] })], signs: [], investigations: [] },
  importantNegatives: { rulingOut: [sym('pain_character', 0, 0, { sensitivity: 0, specificity: 0, LR_negative: 0.3, label: 'Painless bleeding argues against abruption or labour' }), sym('pregnancy_status', 0, 0, { sensitivity: 0, specificity: 0, LR_negative: 0.02 })], supporting: [] },
  differential: { mimics: ['placental_abruption', 'preterm_labour', 'miscarriage', 'uterine_rupture'], distinguishingFeatures: [{ fromDiseaseId: 'placental_abruption', featureIds: ['pain_character', 'pain_severity'] }], neverCloseConditions: [] },
  complications: [{ name: 'Maternal haemorrhage', warningFeatures: ['syncope', 'vaginal_bleeding_volume'], riskFactors: [], timeWindowHours: [0, 24], severityTier: 'critical', description: 'Catastrophic haemorrhage requiring emergency caesarean.' }],
  clinicalScores: [],
  redFlagFeatureIds: ['syncope'],
};

export const pretermLabour: DiseaseNode = {
  id: 'preterm_labour', name: 'Preterm Labour', icdCode: 'O60', system: 'obstetric',
  organSystem: 'reproductive_female', acuity: 'urgent', acuityTier: 2,
  epidemiology: { ageMin: 15, ageMax: 45, agePeak: [25, 35], sexRisk: { male: 0, female: 1 }, backgroundPrevalence: 0.1, riskFactors: [{ featureId: 'prior_abdominal_surgery', label: 'Previous preterm birth', LR_positive: 3.0, prevalenceInDisease: 0.2 }, { featureId: 'prior_abdominal_surgery', label: 'Multiple pregnancy', LR_positive: 3.0, prevalenceInDisease: 0.05 }, { featureId: 'smoking', label: 'Smoking', LR_positive: 1.5, prevalenceInDisease: 0.2 }] },
  pathophysiology: { mechanism: 'Regular uterine contractions with cervical change before 37 weeks gestation. Presents with rhythmic abdominal pain, lower back pain, vaginal pressure, and possible rupture of membranes.', timelineStages: [{ stageId: 1, label: 'Early preterm labour', typicalHoursFromOnset: [0, 24], dominantSymptoms: [sym('pain_character', 0.8, 0.5), sym('pain_initial_location', 0.5, 0.5)], examFindings: [], severityTrajectory: 'worsening', painCharacterTypical: 'Rhythmic cramping \u2014 contractions', painLocationTypical: 'Suprapubic and lower back', painRadiationTypical: 'Thighs' }], progressionRule: 'Progresses to delivery if not arrested with tocolytics.' },
  features: { symptoms: [sym('pain_character', 0.8, 0.5, { stageRelevance: [1] }), sym('pain_initial_location', 0.5, 0.5, { stageRelevance: [1] }), sym('pain_location_now', 0.5, 0.5, { stageRelevance: [1] }), sym('pain_severity', 0.6, 0.5, { stageRelevance: [1] }), sym('pain_worsening_factors', 0.4, 0.5, { stageRelevance: [1] }), sym('vaginal_bleeding', 0.2, 0.6, { stageRelevance: [1] }), sym('vaginal_discharge', 0.3, 0.6, { stageRelevance: [1] }), sym('nausea', 0.3, 0.5, { stageRelevance: [1] }), sym('pregnancy_status', 0.95, 0.9, { stageRelevance: [1] }), sym('pregnancy_gestational_age', 0.8, 0.7, { stageRelevance: [1] }), sym('last_menstrual_period', 0.7, 0.5, { stageRelevance: [1] }), sym('prior_abdominal_surgery', 0.2, 0.6, { stageRelevance: [1] })], signs: [], investigations: [] },
  importantNegatives: { rulingOut: [sym('pregnancy_status', 0, 0, { sensitivity: 0, specificity: 0, LR_negative: 0.02 }), sym('pain_worsening_factors', 0, 0, { sensitivity: 0, specificity: 0, LR_negative: 0.3, label: 'Pain not rhythmic \u2014 against labour' })], supporting: [] },
  differential: { mimics: ['placental_abruption', 'miscarriage', 'preterm_labour', 'urinary_tract_infection'], distinguishingFeatures: [{ fromDiseaseId: 'placental_abruption', featureIds: ['pain_onset', 'vaginal_bleeding'] }], neverCloseConditions: [] },
  complications: [{ name: 'Preterm delivery', warningFeatures: ['pain_severity', 'vaginal_discharge'], riskFactors: [], timeWindowHours: [0, 48], severityTier: 'critical', description: 'Delivery before 37 weeks with neonatal complications.' }],
  clinicalScores: [],
  redFlagFeatureIds: ['vaginal_bleeding'],
};

export const migraine: DiseaseNode = {
  id: 'migraine', name: 'Migraine Headache', icdCode: 'G43', system: 'medical',
  organSystem: 'neurological', acuity: 'semi_urgent', acuityTier: 3,
  epidemiology: { ageMin: 10, ageMax: 65, agePeak: [25, 45], sexRisk: { male: 0.4, female: 1.6 }, backgroundPrevalence: 0.12, riskFactors: [{ featureId: 'family_history_gi_cancer', label: 'Family history', LR_positive: 3.0, prevalenceInDisease: 0.4 }, { featureId: 'hiv_status', label: 'Female sex', LR_positive: 2.0, prevalenceInDisease: 0.6 }] },
  pathophysiology: { mechanism: 'A complex neurological disorder involving cortical spreading depression and trigeminovascular activation. Presents with episodic, unilateral, throbbing headache lasting 4\u201372 hours. Nausea and vomiting are core autonomic features. Photophobia and phonophobia are typical.', timelineStages: [{ stageId: 1, label: 'Prodrome', typicalHoursFromOnset: [0, 24], dominantSymptoms: [sym('headache', 0.3, 0.5), sym('nausea', 0.3, 0.5)], examFindings: [], severityTrajectory: 'worsening', painCharacterTypical: 'No headache yet; mood changes, food cravings', painLocationTypical: 'None', painRadiationTypical: 'None' }, { stageId: 2, label: 'Migraine attack', typicalHoursFromOnset: [4, 72], dominantSymptoms: [sym('headache', 0.9, 0.5), sym('nausea', 0.8, 0.5), sym('vomiting', 0.5, 0.6)], examFindings: [], severityTrajectory: 'worsening', painCharacterTypical: 'Throbbing, unilateral headache', painLocationTypical: 'Head (may have associated abdominal pain in children)', painRadiationTypical: 'None' }], progressionRule: 'Episodic attacks. Frequency varies from weekly to yearly.' },
  features: { symptoms: [sym('headache', 0.9, 0.5, { stageRelevance: [2] }), sym('nausea', 0.8, 0.5, { stageRelevance: [1, 2] }), sym('vomiting', 0.5, 0.6, { stageRelevance: [2] }), sym('vomiting_timing', 0.4, 0.5, { stageRelevance: [2] }), sym('vomiting_frequency', 0.3, 0.5, { stageRelevance: [2] }), sym('vomiting_description', 0.2, 0.6, { stageRelevance: [2] }), sym('pain_character', 0.3, 0.5, { stageRelevance: [1, 2] }), sym('pain_severity', 0.6, 0.5, { stageRelevance: [2] }), sym('previous_similar_episodes', 0.8, 0.7, { stageRelevance: [1, 2] }), sym('anorexia', 0.4, 0.5, { stageRelevance: [2] }), sym('syncope', 0.1, 0.8, { stageRelevance: [2] })], signs: [], investigations: [] },
  importantNegatives: { rulingOut: [sym('fever', 0, 0, { sensitivity: 0, specificity: 0, LR_negative: 0.5 }), sym('vomiting_timing', 0, 0, { sensitivity: 0, specificity: 0, LR_negative: 0.4, label: 'Vomiting after pain onset suggests abdominal cause over migraine' })], supporting: [sym('previous_similar_episodes', 0, 0, { sensitivity: 0, specificity: 0, LR_negative: 0.3 })] },
  differential: { mimics: ['raised_icp', 'cyclic_vomiting', 'gastroenteritis', 'meningitis'], distinguishingFeatures: [{ fromDiseaseId: 'raised_icp', featureIds: ['headache', 'vomiting_timing'] }, { fromDiseaseId: 'gastroenteritis', featureIds: ['previous_similar_episodes', 'diarrhea'] }], neverCloseConditions: ['raised_icp', 'meningitis'] },
  complications: [{ name: 'Status migrainosus', warningFeatures: ['vomiting_frequency', 'syncope'], riskFactors: [], timeWindowHours: [72, 168], severityTier: 'moderate', description: 'Migraine attack lasting >72 hours requiring emergency treatment.' }],
  clinicalScores: [],
  redFlagFeatureIds: ['syncope'],
};

export const medicationInduced: DiseaseNode = {
  id: 'medication_induced', name: 'Medication-Induced Nausea and Vomiting', icdCode: 'T50.Z', system: 'medical',
  organSystem: 'GI', acuity: 'routine', acuityTier: 4,
  epidemiology: { ageMin: 1, ageMax: 90, agePeak: [40, 80], sexRisk: { male: 1, female: 1.2 }, backgroundPrevalence: 0.05, riskFactors: [{ featureId: 'prior_abdominal_surgery', label: 'Polypharmacy', LR_positive: 3.0, prevalenceInDisease: 0.3 }, { featureId: 'diabetes', label: 'Opioid use', LR_positive: 4.0, prevalenceInDisease: 0.2 }, { featureId: 'smoking', label: 'Antibiotic use', LR_positive: 2.5, prevalenceInDisease: 0.3 }] },
  pathophysiology: { mechanism: 'Nausea and vomiting caused by medications through direct GI irritation (NSAIDs, iron), stimulation of the chemoreceptor trigger zone (opioids, digoxin), or delayed gastric emptying (GLP-1 agonists). The temporal relationship to drug initiation is the key diagnostic clue.', timelineStages: [{ stageId: 1, label: 'Drug-induced vomiting', typicalHoursFromOnset: [0, 72], dominantSymptoms: [sym('nausea', 0.8, 0.5), sym('vomiting', 0.7, 0.5)], examFindings: [], severityTrajectory: 'worsening', painCharacterTypical: 'No abdominal pain or mild epigastric discomfort', painLocationTypical: 'None or epigastric', painRadiationTypical: 'None' }], progressionRule: 'Resolves within days of stopping the causative drug.' },
  features: { symptoms: [sym('nausea', 0.8, 0.5, { stageRelevance: [1] }), sym('vomiting', 0.7, 0.5, { stageRelevance: [1] }), sym('vomiting_timing', 0.4, 0.5, { stageRelevance: [1] }), sym('vomiting_frequency', 0.4, 0.5, { stageRelevance: [1] }), sym('vomiting_description', 0.3, 0.6, { stageRelevance: [1] }), sym('pain_character', 0.2, 0.5, { stageRelevance: [1] }), sym('anorexia', 0.4, 0.5, { stageRelevance: [1] }), sym('headache', 0.1, 0.5, { stageRelevance: [1] })], signs: [], investigations: [] },
  importantNegatives: { rulingOut: [sym('pain_character', 0, 0, { sensitivity: 0, specificity: 0, LR_negative: 0.3, label: 'Absence of significant abdominal pain suggests non-surgical cause' })], supporting: [] },
  differential: { mimics: ['gastroenteritis', 'functional_dyspepsia', 'cyclic_vomiting', 'alcohol_withdrawal'], distinguishingFeatures: [{ fromDiseaseId: 'gastroenteritis', featureIds: ['diarrhea', 'fever'] }], neverCloseConditions: [] },
  complications: [{ name: 'Dehydration', warningFeatures: ['vomiting_frequency', 'syncope'], riskFactors: ['elderly'], timeWindowHours: [24, 168], severityTier: 'moderate', description: 'Fluid and electrolyte depletion requiring IV rehydration.' }],
  clinicalScores: [],
  redFlagFeatureIds: ['syncope'],
};

export const alcoholWithdrawal: DiseaseNode = {
  id: 'alcohol_withdrawal', name: 'Alcohol Withdrawal Syndrome', icdCode: 'F10.23', system: 'medical',
  organSystem: 'neurological', acuity: 'urgent', acuityTier: 2,
  epidemiology: { ageMin: 20, ageMax: 70, agePeak: [35, 55], sexRisk: { male: 2, female: 0.5 }, backgroundPrevalence: 0.005, riskFactors: [{ featureId: 'alcohol_use', label: 'Chronic heavy alcohol use', LR_positive: 10.0, prevalenceInDisease: 0.9 }, { featureId: 'previous_similar_episodes', label: 'Previous withdrawal seizures', LR_positive: 5.0, prevalenceInDisease: 0.2 }, { featureId: 'prior_abdominal_surgery', label: 'DT history', LR_positive: 4.0, prevalenceInDisease: 0.15 }] },
  pathophysiology: { mechanism: 'A syndrome of autonomic hyperactivity following cessation or reduction of heavy alcohol intake. GABA/glutamate imbalance causes tremors, tachycardia, hypertension, and psychomotor agitation. Nausea and vomiting are prominent GI manifestations, often worst in the morning.', timelineStages: [{ stageId: 1, label: 'Early withdrawal', typicalHoursFromOnset: [6, 24], dominantSymptoms: [sym('headache', 0.4, 0.5), sym('nausea', 0.6, 0.5), sym('vomiting', 0.5, 0.5)], examFindings: [], severityTrajectory: 'worsening', painCharacterTypical: 'Generalised abdominal discomfort', painLocationTypical: 'Epigastric', painRadiationTypical: 'None' }, { stageId: 2, label: 'Severe withdrawal / DTs', typicalHoursFromOnset: [24, 72], dominantSymptoms: [sym('vomiting', 0.7, 0.5), sym('headache', 0.5, 0.5)], examFindings: [], severityTrajectory: 'worsening', painCharacterTypical: 'Epigastric pain from associated gastritis', painLocationTypical: 'Epigastric', painRadiationTypical: 'None' }], progressionRule: 'Peaks at 24\u201372 hours. May progress to delirium tremens (DTs) with mortality 5\u201315% without treatment.' },
  features: { symptoms: [sym('nausea', 0.6, 0.5, { stageRelevance: [1, 2] }), sym('vomiting', 0.5, 0.5, { stageRelevance: [1, 2] }), sym('vomiting_timing', 0.4, 0.5, { stageRelevance: [1, 2] }), sym('vomiting_frequency', 0.4, 0.5, { stageRelevance: [2] }), sym('vomiting_description', 0.3, 0.6, { stageRelevance: [1, 2] }), sym('headache', 0.4, 0.5, { stageRelevance: [1, 2] }), sym('pain_character', 0.3, 0.5, { stageRelevance: [1, 2] }), sym('pain_initial_location', 0.3, 0.5, { stageRelevance: [1] }), sym('anorexia', 0.4, 0.5, { stageRelevance: [1, 2] }), sym('alcohol_use', 0.9, 0.8, { stageRelevance: [1, 2] }), sym('syncope', 0.2, 0.8, { stageRelevance: [2] }), sym('previous_similar_episodes', 0.5, 0.7, { stageRelevance: [1, 2] })], signs: [], investigations: [] },
  importantNegatives: { rulingOut: [], supporting: [sym('alcohol_use', 0, 0, { sensitivity: 0, specificity: 0, LR_negative: 0.05, label: 'No alcohol history \u2014 withdrawal excluded' })] },
  differential: { mimics: ['gastroenteritis', 'pancreatitis', 'gastritis', 'medication_induced', 'raised_icp'], distinguishingFeatures: [{ fromDiseaseId: 'gastroenteritis', featureIds: ['alcohol_use', 'diarrhea'] }, { fromDiseaseId: 'pancreatitis', featureIds: ['alcohol_use', 'pain_radiation'] }], neverCloseConditions: ['raised_icp'] },
  complications: [{ name: 'Delirium tremens', warningFeatures: ['syncope', 'vomiting_frequency', 'headache'], riskFactors: ['chronic_alcoholism'], timeWindowHours: [24, 72], severityTier: 'critical', description: 'Life-threatening withdrawal with confusion, hallucinations, and autonomic instability.' }, { name: 'Withdrawal seizures', warningFeatures: ['syncope'], riskFactors: ['previous_seizures'], timeWindowHours: [12, 48], severityTier: 'critical', description: 'Generalised tonic-clonic seizures.' }],
  clinicalScores: [],
  redFlagFeatureIds: ['syncope'],
};

export const MISSING2_NODES: DiseaseNode[] = [
  constipation, infectiousColitis, epididymitis, adenomyosis, ovarianCancer,
  miscarriage, placentaPraevia, pretermLabour, migraine, medicationInduced, alcoholWithdrawal,
];
