import os

lines = []
def L(s=""):
    lines.append(s)

L("'use client'")
L("import { useState } from 'react'")
L("import { Activity, Bell, User, Users, Bed, Heart, Monitor, Wind, Droplets, Thermometer, Weight, AlertTriangle, Clock, Calendar, Pill, Syringe, FileText, BookOpen, CheckCircle, XCircle, ArrowRight, Plus, Search, Menu, ChevronRight, MessageSquare, Shield, Stethoscope, Ambulance, TrendingUp, Eye, Brain, Bone, Kidney, HeartPulse, Lung, type LucideIcon, Zap, Home, Globe, Baby, Apple, Target, BarChart3, Sliders, LineChart } from 'lucide-react'")
L("")
L("const C = {")
L("  sky: '#2F80ED', skySoft: '#56CCF2', skyLight: '#E8F4FD', white: '#FFFFFF',")
L("  panel: '#F7FBFF', border: '#E3EEF9', navy: '#163C74', text: '#5B6B82',")
L("  textLight: '#8FA4BC', green: '#10B981', amber: '#F59E0B', red: '#EF4444', purple: '#8B5CF6',")
L("}")
L("")
L("const S = {")
L("  page: { minHeight: '100vh', background: C.panel, fontFamily: \"'Inter', system-ui, sans-serif\", color: C.text, display: 'flex', flexDirection: 'column' as const },")
L("  topBar: { height: 64, background: C.white, borderBottom: `1px solid ${C.border}`, display: 'flex', alignItems: 'center', padding: '0 24px', gap: 12, flexShrink: 0 },")
L("  logoText: { fontSize: 14, fontWeight: 700, color: C.navy },")
L("  body: { flex: 1, display: 'flex', overflow: 'hidden' },")
L("  leftNav: { width: 220, background: C.white, borderRight: `1px solid ${C.border}`, display: 'flex', flexDirection: 'column' as const, padding: '12px 8px', gap: 1, flexShrink: 0, overflow: 'auto' },")
L("  navItem: (a: boolean) => ({ padding: '8px 12px', borderRadius: 8, display: 'flex', alignItems: 'center', gap: 10, fontSize: 12, fontWeight: a ? 600 : 400, color: a ? C.sky : C.text, background: a ? C.skyLight : 'transparent', border: 'none', cursor: 'pointer', width: '100%', textAlign: 'left' as const }),")
L("  main: { flex: 1, overflow: 'auto', padding: 20 },")
L("  card: { background: C.white, border: `1px solid ${C.border}`, borderRadius: 12, padding: 20 },")
L("  cardH: { background: C.white, border: `1px solid ${C.border}`, borderRadius: 12, padding: 20, cursor: 'pointer', transition: 'all 0.1s' },")
L("  grid2: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 },")
L("  grid3: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 12 },")
L("  grid4: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 12 },")
L("  label: { fontSize: 11, fontWeight: 500, color: C.text, marginBottom: 4, display: 'block' },")
L("  input: { width: '100%', padding: '8px 12px', borderRadius: 8, border: `1px solid ${C.border}`, fontSize: 13, background: C.panel, outline: 'none', fontFamily: \"'Inter', sans-serif\" } as any,")
L("  sel: { width: '100%', padding: '8px 12px', borderRadius: 8, border: `1px solid ${C.border}`, fontSize: 13, background: C.panel, outline: 'none', fontFamily: \"'Inter', sans-serif\", cursor: 'pointer' },")
L("  btn: (c: string) => ({ padding: '8px 20px', borderRadius: 8, border: 'none', background: c, color: C.white, fontSize: 12, fontWeight: 600, cursor: 'pointer' }),")
L("  btnO: { padding: '8px 20px', borderRadius: 8, border: `1px solid ${C.border}`, background: C.white, color: C.text, fontSize: 12, fontWeight: 500, cursor: 'pointer' },")
L("  badge: (c: string) => ({ padding: '2px 8px', borderRadius: 4, fontSize: 10, fontWeight: 600, background: `${c}15`, color: c }),")
L("  pill: (c: string) => ({ display: 'inline-flex', alignItems: 'center', gap: 4, padding: '2px 8px', borderRadius: 100, fontSize: 10, fontWeight: 600, background: `${c}15`, color: c }),")
L("  secTitle: { fontSize: 16, fontWeight: 700, color: C.navy, marginBottom: 16 },")
L("  divider: { height: 1, background: C.border, margin: '16px 0' },")
L("  statCard: { textAlign: 'center', padding: 20, background: C.white, border: `1px solid ${C.border}`, borderRadius: 12 },")
L("  statValue: { fontSize: 28, fontWeight: 700, color: C.navy, marginTop: 8 },")
L("  statLabel: { fontSize: 11, color: C.textLight, marginTop: 4 },")
L("}")
L("")
L("const NAV_ITEMS: { id: string; label: string; icon: LucideIcon }[] = [")
L("  { id: 'dashboard', label: 'Renal Dashboard', icon: Activity },")
L("  { id: 'snapshot', label: 'Kidney Snapshot', icon: Kidney },")
L("  { id: 'timeline', label: 'Disease Timeline', icon: Clock },")
L("  { id: 'classification', label: 'CKD Classification', icon: Sliders },")
L("  { id: 'phenotype', label: 'Renal Phenotype', icon: Brain },")
L("  { id: 'function', label: 'Kidney Function Intelligence', icon: Monitor },")
L("  { id: 'egfr', label: 'eGFR Trend Engine', icon: TrendingUp },")
L("  { id: 'albuminuria', label: 'Albuminuria Intelligence', icon: Droplets },")
L("  { id: 'cause', label: 'Cause Intelligence', icon: Search },")
L("  { id: 'anemia', label: 'CKD Anemia Center', icon: HeartPulse },")
L("  { id: 'bone', label: 'Mineral Bone Disease', icon: Bone },")
L("  { id: 'electrolytes', label: 'Electrolyte Disorders', icon: Activity },")
L("  { id: 'bp', label: 'Blood Pressure Intelligence', icon: Heart },")
L("  { id: 'medications', label: 'Medication Intelligence', icon: Pill },")
L("  { id: 'dialysis-plan', label: 'Dialysis Planning', icon: Calendar },")
L("  { id: 'hemodialysis', label: 'Hemodialysis', icon: Wind },")
L("  { id: 'access', label: 'Access Intelligence', icon: Shield },")
L("  { id: 'peritoneal', label: 'Peritoneal Dialysis', icon: Droplets },")
L("  { id: 'transplant', label: 'Transplant Center', icon: Heart },")
L("  { id: 'fluids', label: 'Fluid Intelligence', icon: Weight },")
L("  { id: 'nutrition', label: 'Nutrition Intelligence', icon: Apple },")
L("  { id: 'lab', label: 'Laboratory Intelligence', icon: FileText },")
L("  { id: 'home', label: 'Home Monitoring', icon: Home },")
L("  { id: 'pregnancy', label: 'Pregnancy Pathway', icon: Baby },")
L("  { id: 'team', label: 'MDT', icon: Users },")
L("  { id: 'registry', label: 'Registry', icon: BookOpen },")
L("  { id: 'quality', label: 'Quality Indicators', icon: BarChart3 },")
L("  { id: 'portal', label: 'Patient Portal', icon: Globe },")
L("]")
L("")
L("const WORKSPACE_LINKS = [")
L("  { label: 'Patient Movement', href: '/pme' },")
L("  { label: 'Nurse Workspace', href: '/nurse' },")
L("  { label: 'Doctor Workspace', href: '/doctor' },")
L("  { label: 'Lab Workspace', href: '/laboratory' },")
L("  { label: 'Pharmacy', href: '/pharmacy' },")
L("  { label: 'Radiology', href: '/radiology' },")
L("  { label: 'Theatre', href: '/theatre' },")
L("  { label: 'ICU', href: '/icu' },")
L("  { label: 'Emergency', href: '/emergency' },")
L("  { label: 'Diabetes', href: '/diabetes' },")
L("  { label: 'Hypertension', href: '/hypertension' },")
L("  { label: 'HF', href: '/hf' },")
L("  { label: 'Respiratory', href: '/respiratory' },")
L("  { label: 'Sickle Cell', href: '/sickle-cell' },")
L("  { label: 'HIV', href: '/hiv' },")
L("  { label: 'Oncology', href: '/oncology' },")
L("  { label: 'Neurology', href: '/neurology' },")
L("]")
L("")

content = "\n".join(lines)
with open("C:\\Users\\Administrator\\Desktop\\client\\app\\ckd\\page.tsx", "w", encoding="utf-8") as f:
    f.write(content)

print(f"Written {len(lines)} lines, {len(content)} chars")
