import datetime
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT

class PDFExporter:
    def __init__(self, filename="clinical_note.pdf"):
        self.filename = filename
        self.styles = getSampleStyleSheet()
        self.styles.add(ParagraphStyle(
            name='Justify',
            parent=self.styles['Normal'],
            alignment=TA_JUSTIFY,
            fontSize=10,
            leading=12,
            spaceAfter=6
        ))
        self.styles.add(ParagraphStyle(
            name='DocTitle',
            parent=self.styles['Title'],
            alignment=TA_LEFT,
            fontSize=14,
            spaceAfter=10,
            spaceBefore=6
        ))
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=11,
            spaceBefore=8,
            spaceAfter=4
        ))

    def export_text(self, text: str, title: str = "Clinical Note"):
        doc = SimpleDocTemplate(
            self.filename,
            pagesize=A4,
            rightMargin=2*cm,
            leftMargin=2*cm,
            topMargin=2*cm,
            bottomMargin=2*cm
        )
        story = []

        story.append(Paragraph(self._escape(title), self.styles['DocTitle']))
        story.append(Spacer(1, 0.5*cm))

        lines = text.split('\n')
        for line in lines:
            stripped = line.strip()
            if not stripped:
                story.append(Spacer(1, 0.2*cm))
            elif stripped.startswith('==='):
                story.append(Paragraph(self._escape(stripped), self.styles['SectionHeader']))
            elif stripped.startswith('---'):
                story.append(Spacer(1, 0.3*cm))
            else:
                story.append(Paragraph(self._escape(stripped), self.styles['Justify']))

        story.append(Spacer(1, 1*cm))
        footer = f"Generated by AMEXAN Clinical OS on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}"
        story.append(Paragraph(footer, self.styles['Normal']))

        doc.build(story)
        return self.filename

    def _escape(self, text: str) -> str:
        return text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
