// Test script for the clerking note generator
// This is a standalone JS simulation of what generateClerkingNote produces

function generateClerkingNote(input) {
  const { patientName, patientId, unitSlug, consultant, encounterType, registration, presentingComplaint, hpi, exam, ddx, treatment } = input;
  const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });

  const sections = [
    `# CLERKING NOTE — SURGERY`,
    ``,
    `**Patient:** ${patientName} (MRN: ${patientId})`,
    `**Date:** ${date}`,
    `**Unit:** ${unitSlug.replace(/-/g, ' ')} | **Consultant:** ${consultant}`,
    `**Encounter Type:** ${encounterType.replace(/_/g, ' ')}`,
    `**Ward:** ${registration.ward} | **Bed:** ${registration.bed}`,
    ``,
    `---`,
    ``,
    `## Presenting Complaint`,
    `${presentingComplaint.complaint} x ${presentingComplaint.duration}, severity ${presentingComplaint.severity}/10`,
    ``,
  ];

  if (registration.surgicalRisk) {
    const r = registration.surgicalRisk;
    sections.push(`## Surgical Risk Assessment`);
    if (r.bloodGroup) sections.push(`- **Blood Group:** ${r.bloodGroup}`);
    if (r.allergies?.length) sections.push(`- **Allergies:** ${r.allergies.join(', ')}`);
    if (r.anticoagulants?.length) sections.push(`- **Anticoagulants:** ${r.anticoagulants.join(', ')}`);
    if (r.previousSurgery !== undefined) sections.push(`- **Previous Surgery:** ${r.previousSurgery ? 'Yes' : 'No'}`);
    sections.push(``);
  }

  if (hpi.length > 0) {
    sections.push(`## History of Presenting Illness`);
    for (const h of hpi) {
      sections.push(`- ${h.question}: ${typeof h.answer === 'boolean' ? (h.answer ? 'Yes' : 'No') : h.answer}`);
    }
    sections.push(``);
  }

  if (exam.length > 0) {
    sections.push(`## Examination Findings`);
    for (const e of exam) {
      const status = e.present === true ? 'Present' : e.present === false ? 'Absent' : 'Not examined';
      const val = e.value ? ` (${e.value})` : '';
      const comment = e.comment ? ` — ${e.comment}` : '';
      sections.push(`- ${e.findingText}: ${status}${val}${comment}`);
    }
    sections.push(``);
  }

  if (ddx.length > 0) {
    sections.push(`## Differential Diagnosis`);
    for (const d of ddx) {
      sections.push(`- ${d.diseaseName}: ${d.probability}%`);
    }
    sections.push(``);
  }

  if (treatment && treatment.length > 0 && treatment[0].items.length > 0) {
    sections.push(`## Initial Plan`);
    for (const item of treatment[0].items) {
      sections.push(`- ${item}`);
    }
    sections.push(``);
  }

  sections.push(`---`);
  sections.push(`*Generated by AMEXAN Clinical Reasoning System*`);

  return sections.join('\n');
}

// === SIGMOID VOLVULUS TEST CASE ===

const mockNote = generateClerkingNote({
  patientName: 'John Kamau',
  patientId: 'P002',
  unitSlug: 'acute-care-surgery',
  consultant: 'Dr. Okonkwo',
  encounterType: 'emergency',
  registration: {
    ward: 'Surgical Ward A',
    bed: '8',
    surgicalRisk: {
      bloodGroup: 'O+',
      allergies: ['penicillin'],
      anticoagulants: [],
      previousSurgery: true,
    },
  },
  presentingComplaint: {
    complaint: 'Abdominal distension and constipation for 3 days',
    duration: '3 days',
    severity: 8,
  },
  hpi: [
    { question: 'Severe colicky abdominal pain?', answer: 'Yes, sudden onset, severe, cramping in nature' },
    { question: 'Abdominal distension?', answer: 'Yes, progressive over 3 days — cannot button his trousers. Massive distension' },
    { question: 'Constipation / obstipation?', answer: 'No bowel movement for 3 days. No flatus for past 24 hours' },
    { question: 'Nausea / vomiting?', answer: 'Vomited twice today — bilious. Late-onset vomiting' },
    { question: 'Previous similar episodes?', answer: 'Yes — two episodes in the past 5 years, both resolved spontaneously with bed rest' },
    { question: 'Chronic constipation?', answer: 'Yes — long-standing, uses lactulose occasionally. Lives alone' },
    { question: 'Dietary history?', answer: 'High-fibre diet — traditional Kenyan diet of ugali, sukuma wiki, and beans' },
    { question: 'Past medical history?', answer: 'Hypertension on amlodipine. No diabetes. No previous abdominal surgery' },
    { question: 'Medications?', answer: 'Amlodipine 5 mg daily. Lactulose PRN. No anticoagulants' },
  ],
  exam: [
    { findingText: 'General appearance', present: true, comment: 'Elderly gentleman in obvious discomfort, lying still' },
    { findingText: 'Abdominal inspection', present: true, comment: 'Massively distended, tense, symmetrical. Visible peristalsis absent' },
    { findingText: 'Percussion', present: true, comment: 'Tympanic throughout — drum-like' },
    { findingText: 'Bowel sounds', present: true, comment: 'Initially high-pitched tinkling, now absent after 24 hours' },
    { findingText: 'Palpation', present: true, comment: 'Distended sigmoid loop palpable in left lower quadrant. No guarding. No rebound' },
    { findingText: 'Rectal exam', present: true, comment: 'Empty rectum. No masses. No blood' },
    { findingText: 'Heart Rate', present: true, value: 102 },
    { findingText: 'Blood Pressure', present: true, value: '100/65' },
    { findingText: 'Temperature', present: true, value: 37.2 },
    { findingText: 'Respiratory Rate', present: true, value: 22 },
    { findingText: 'SpO2', present: true, value: 97 },
  ],
  ddx: [
    { diseaseName: 'Sigmoid Volvulus', probability: 85 },
    { diseaseName: 'Large Bowel Obstruction (malignancy)', probability: 10 },
    { diseaseName: 'Acute Pancreatitis', probability: 3 },
    { diseaseName: 'Cecal Volvulus', probability: 2 },
  ],
  treatment: [
    {
      items: [
        'NBM (nil by mouth)',
        'IV fluids resuscitation — Hartmann\'s solution 1 L stat, then 125 mL/hr',
        'NG tube insertion — free drainage',
        'IV antibiotics — Ceftriaxone 2 g IV + Metronidazole 500 mg IV',
        'Analgesia — IV morphine titrated',
        'Emergency surgical consult — colorectal team',
        'Plan: urgent flexible sigmoidoscopy + rectal tube decompression',
        'If successful — elective sigmoid resection in same admission',
        'If ischemia/peritonitis — emergency laparotomy + Hartmann procedure',
        'ICU bed on standby',
      ],
    },
  ],
});

console.log(mockNote);
