import os

filepath = r"C:\Users\Administrator\Desktop\client\components\clinical-dashboards\AsthmaDashboard.tsx"
# Remove existing file if present
if os.path.exists(filepath):
    os.remove(filepath)

lines = []

def L(s):
    lines.append(s)

L('"use client";')
L('')
L('import {')
L('  useState, useEffect, useCallback, useMemo, useRef, memo')
L('} from "react";')
L('import {')
L('  collection, query, where, orderBy, getDocs, addDoc, updateDoc,')
L('  deleteDoc, doc, getDoc, setDoc, Timestamp, serverTimestamp,')
L('  onSnapshot, limit, writeBatch,')
L('} from "firebase/firestore";')
L('import { db } from "@/lib/firebase";')
L('')
L('interface PharmaEntry {')
L('  drugClass: string; mechanism: string; minDose: number; maxDose: number;')
L('  unit: string; commonDoses: string[]; frequencies: string[]; routes: string[];')
L('  indications: string[]; contraindications: string[]; warnings: string[];')
L('  sideEffects: string[]; patientInstructions: string; monitoring: string[];')
L('  interactions: string[]; pregnancyCategory: string; renalDose?: string;')
L('  hepaticDose?: string; color: string; tlColor: string;')
L('}')
L('')

# Now write the file in sections using a different approach
with open(filepath, 'w', encoding='utf-8') as f:
    f.write('"use client";\n\n')
    f.write('import {\n')
    f.write('  useState, useEffect, useCallback, useMemo, useRef, memo\n')
    f.write('} from "react";\n')
    f.write('import {\n')
    f.write('  collection, query, where, orderBy, getDocs, addDoc, updateDoc,\n')
    f.write('  deleteDoc, doc, getDoc, setDoc, Timestamp, serverTimestamp,\n')
    f.write('  onSnapshot, limit, writeBatch,\n')
    f.write('} from "firebase/firestore";\n')
    f.write('import { db } from "@/lib/firebase";\n\n')
    f.write('interface PharmaEntry {\n')
    f.write('  drugClass: string; mechanism: string; minDose: number; maxDose: number;\n')
    f.write('  unit: string; commonDoses: string[]; frequencies: string[]; routes: string[];\n')
    f.write('  indications: string[]; contraindications: string[]; warnings: string[];\n')
    f.write('  sideEffects: string[]; patientInstructions: string; monitoring: string[];\n')
    f.write('  interactions: string[]; pregnancyCategory: string; renalDose?: string;\n')
    f.write('  hepaticDose?: string; color: string; tlColor: string;\n')
    f.write('}\n\n')

print("Base imports written")

# Now write PHARMA_DB
with open(filepath, 'a', encoding='utf-8') as f:
    f.write('export const PHARMA_DB: Record<string, PharmaEntry> = {\n')
    f.write('  "Salbutamol (Albuterol)": {\n')
    f.write('    drugClass: "Short-Acting Beta-Agonist (SABA)",\n')
    f.write('    mechanism: "Selective beta2-adrenoceptor agonist, bronchodilation via smooth muscle relaxation. Onset 5-15 min, duration 4-6h.",\n')
    f.write('    minDose: 100, maxDose: 200, unit: "mcg",\n')
    f.write('    commonDoses: ["100","200"], frequencies: ["PRN"], routes: ["Inhaled (pMDI)","Nebulized"],\n')
    f.write('    indications: ["Relief of acute asthma symptoms","Exercise-induced bronchoconstriction","Acute exacerbation management"],\n')
    f.write('    contraindications: ["Hypersensitivity to salbutamol","Tachyarrhythmias","Hypertrophic obstructive cardiomyopathy"],\n')
    f.write('    warnings: ["Excessive use indicates poor asthma control, escalate therapy","May cause hypokalemia at high doses","Tremor and tachycardia common at high doses","Not for monotherapy in persistent asthma (needs ICS)"],\n')
    f.write('    sideEffects: ["Tremor","Tachycardia","Palpitations","Headache","Muscle cramps","Hypokalemia","Nervousness"],\n')
    f.write('    patientInstructions: "Use ONLY as needed for symptom relief. If needing more than 2 times per week, see your doctor. Shake inhaler well before each use. Use spacer for best delivery. Rinse mouth after use.",\n')
    f.write('    monitoring: ["Symptom frequency (SABA use/week)","Peak flow readings","Inhaler technique review at every visit"],\n')
    f.write('    interactions: ["Beta-blockers antagonize bronchodilation","Diuretics cause additive hypokalemia","MAOIs risk of hypertensive crisis"],\n')
    f.write('    pregnancyCategory: "A, safe in all trimesters, preferred for symptom relief",\n')
    f.write('    color: "#0891b2", tlColor: "#06b6d4",\n')
    f.write('  },\n')
    f.write('  "Beclomethasone": {\n')
    f.write('    drugClass: "Inhaled Corticosteroid (ICS)",\n')
    f.write('    mechanism: "Binds glucocorticoid receptor, decreases airway inflammation, eosinophils, mast cells, cytokines.",\n')
    f.write('    minDose: 50, maxDose: 400, unit: "mcg",\n')
    f.write('    commonDoses: ["50","100","200","400"], frequencies: ["OD","BD"], routes: ["Inhaled (pMDI)"],\n')
    f.write('    indications: ["Persistent asthma step 2 GINA","Step-up therapy for uncontrolled asthma"],\n')
    f.write('    contraindications: ["Untreated respiratory infection","Hypersensitivity"],\n')
    f.write('    warnings: ["Rinse mouth after each use to prevent oral thrush","Higher doses may cause adrenal suppression","Regular use essential, not for acute relief","May cause hoarseness"],\n')
    f.write('    sideEffects: ["Oral thrush","Dysphonia","Sore throat","Cough","Adrenal suppression high dose long term"],\n')
    f.write('    patientInstructions: "Use REGULARLY, not for quick relief. Rinse mouth with water after each use. Takes 1-4 weeks to reach full effect. Do not stop suddenly.",\n')
    f.write('    monitoring: ["Asthma control ACT score","Peak flow","Inhaler technique","Oral exam for thrush"],\n')
    f.write('    interactions: ["CYP3A4 inhibitors increase systemic ICS levels","Systemic corticosteroids additive adrenal suppression"],\n')
    f.write('    pregnancyCategory: "A, safe, equivalent to budesonide",\n')
    f.write('    color: "#059669", tlColor: "#10b981",\n')
    f.write('  },\n')
    f.write('  "Budesonide": {\n')
    f.write('    drugClass: "Inhaled Corticosteroid (ICS)",\n')
    f.write('    mechanism: "High-affinity glucocorticoid receptor agonist, decreases airway inflammation. Higher first-pass metabolism, better safety profile.",\n')
    f.write('    minDose: 200, maxDose: 1600, unit: "mcg",\n')
    f.write('    commonDoses: ["200","400","800","1600"], frequencies: ["OD","BD"], routes: ["Inhaled (pMDI/DPI)"],\n')
    f.write('    indications: ["Persistent asthma","Maintenance therapy in adults and children","Step-down therapy once controlled"],\n')
    f.write('    contraindications: ["Hypersensitivity","Untreated respiratory infection"],\n')
    f.write('    warnings: ["Rinse mouth after use to prevent oral thrush","Monitor growth velocity in children","Adrenal suppression at high doses"],\n')
    f.write('    sideEffects: ["Oral candidiasis","Dysphonia","Cough","Sore throat","Adrenal suppression high dose"],\n')
    f.write('    patientInstructions: "Use EVERY DAY as prescribed even when feeling well. Takes 2-4 weeks to reach full benefit. Rinse mouth and spit after use. Not for sudden attacks.",\n')
    f.write('    monitoring: ["ACT score","Peak flow diary","Inhaler technique","Growth in children","Bone density long-term high dose"],\n')
    f.write('    interactions: ["CYP3A4 inhibitors increase budesonide levels","Ketoconazole increases systemic exposure"],\n')
    f.write('    pregnancyCategory: "A, extensive safety data, preferred ICS in pregnancy",\n')
    f.write('    color: "#059669", tlColor: "#34d399",\n')
    f.write('  },\n')
    f.write('  "Fluticasone propionate": {\n')
    f.write('    drugClass: "Inhaled Corticosteroid (ICS)",\n')
    f.write('    mechanism: "Potent glucocorticoid agonist, decreases airway inflammation and hyperresponsiveness. Higher receptor affinity than beclomethasone.",\n')
    f.write('    minDose: 100, maxDose: 1000, unit: "mcg",\n')
    f.write('    commonDoses: ["100","250","500","1000"], frequencies: ["BD"], routes: ["Inhaled (pMDI/DPI)"],\n')
    f.write('    indications: ["Persistent asthma step 2-5 GINA","Step-up therapy"],\n')
    f.write('    contraindications: ["Hypersensitivity","Status asthmaticus not for acute","Untreated severe infections"],\n')
    f.write('    warnings: ["Rinse mouth after use","Higher doses cause adrenal suppression, consider steroid card","Growth monitoring in children"],\n')
    f.write('    sideEffects: ["Oral thrush","Dysphonia","Cough","Sore throat","Adrenal suppression","Bone density loss long-term high dose"],\n')
    f.write('    patientInstructions: "Use REGULARLY twice daily. Rinse mouth with water after each use. Takes 1-2 weeks for improvement. Never use for acute attacks.",\n')
    f.write('    monitoring: ["ACT score","Peak flow","Inhaler technique","Adrenal function high dose","Growth in children"],\n')
    f.write('    interactions: ["Ritonavir greatly increases fluticasone levels Cushing syndrome reported","Ketoconazole increases systemic levels"],\n')
    f.write('    pregnancyCategory: "B, limited data, budesonide preferred",\n')
    f.write('    color: "#059669", tlColor: "#22c55e",\n')
    f.write('  },\n')
    f.write('  "Budesonide/Formoterol (Symbicort)": {\n')
    f.write('    drugClass: "ICS/LABA Combination SMART Therapy",\n')
    f.write('    mechanism: "Budesonide ICS plus formoterol rapid-acting LABA. Formoterol fast onset 1-3 min allows PRN use as reliever. SMART Single Maintenance And Reliever Therapy.",\n')
    f.write('    minDose: 160, maxDose: 4.5, unit: "mcg",\n')
    f.write('    commonDoses: ["80/4.5","160/4.5","320/9"], frequencies: ["OD/BD maintenance + PRN"], routes: ["Inhaled (DPI)"],\n')
    f.write('    indications: ["GINA step 3-5 asthma","SMART/MART therapy preferred GINA approach","Maintenance and reliever in one inhaler"],\n')
    f.write('    contraindications: ["Need for rapid relief without formoterol experience","Hypersensitivity to components"],\n')
    f.write('    warnings: ["Do NOT use with additional LABA","Overuse may indicate poor asthma control","Max 8 inhalations per day including maintenance"],\n')
    f.write('    sideEffects: ["Oral thrush","Headache","Tremor","Palpitations","Mild tachycardia","Cough"],\n')
    f.write('    patientInstructions: "Use ONE inhaler for both maintenance AND symptom relief. Morning dose 1-2 inhalations. Relief 1 inhalation as needed. Max 8 inhalations total per day. Rinse mouth after use.",\n')
    f.write('    monitoring: ["Daily symptom diary","SABA use frequency","ACT score every visit","Exacerbation frequency","Inhaler technique"],\n')
    f.write('    interactions: ["Beta-blockers antagonize formoterol","Diuretics cause hypokalemia","CYP3A4 inhibitors increase budesonide"],\n')
    f.write('    pregnancyCategory: "B, limited data, budesonide component has good safety profile",\n')
    f.write('    color: "#7c3aed", tlColor: "#8b5cf6",\n')
    f.write('  },\n')
    f.write('  "Fluticasone/Salmeterol (Seretide/Advair)": {\n')
    f.write('    drugClass: "ICS/LABA Combination",\n')
    f.write('    mechanism: "Fluticasone ICS plus salmeterol long-acting beta2-agonist onset 30-60 min. Fixed-dose combination for maintenance only, NOT for reliever.",\n')
    f.write('    minDose: 100, maxDose: 50, unit: "mcg",\n')
    f.write('    commonDoses: ["100/50","250/50","500/50"], frequencies: ["BD"], routes: ["Inhaled (pMDI/DPI)"],\n')
    f.write('    indications: ["Persistent asthma step 3-4 GINA","Maintenance only not for SMART/MART"],\n')
    f.write('    contraindications: ["Acute bronchospasm not a reliever","Hypersensitivity"],\n')
    f.write('    warnings: ["NOT for acute symptom relief, salmeterol slow onset","Do not exceed 2 inhalations BD","Paradoxical bronchospasm reported"],\n')
    f.write('    sideEffects: ["Oral thrush","Dysphonia","Headache","Tremor","Palpitations","Nausea","Cough"],\n')
    f.write('    patientInstructions: "Use TWICE DAILY morning and evening as maintenance ONLY. This is NOT a rescue inhaler. For quick relief use your blue SABA inhaler. Rinse mouth after each use.",\n')
    f.write('    monitoring: ["ACT score","Peak flow","Inhaler technique","SABA use frequency","Exacerbation rate"],\n')
    f.write('    interactions: ["Beta-blockers cause bronchoconstriction","Ritonavir increases fluticasone levels","CYP3A4 inhibitors increase steroid levels"],\n')
    f.write('    pregnancyCategory: "C, limited data, use if benefit outweighs risk",\n')
    f.write('    color: "#2563eb", tlColor: "#3b82f6",\n')
    f.write('  },\n')
    f.write('  "Fluticasone furoate/Vilanterol (Relvar/Breo)": {\n')
    f.write('    drugClass: "ICS/LABA Combination Once Daily",\n')
    f.write('    mechanism: "Fluticasone furoate ICS high affinity long receptor binding plus vilanterol once-daily LABA rapid onset. Once-daily dosing improves adherence.",\n')
    f.write('    minDose: 92, maxDose: 22, unit: "mcg",\n')
    f.write('    commonDoses: ["92/22","184/22","100/25","200/25"], frequencies: ["OD"], routes: ["Inhaled (DPI)"],\n')
    f.write('    indications: ["Persistent asthma step 3-4 GINA","Once-daily simplification for adherence"],\n')
    f.write('    contraindications: ["Hypersensitivity","Status asthmaticus","Not for acute relief"],\n')
    f.write('    warnings: ["Once daily ONLY not for BD dosing","Not a reliever prescribe separate SABA","Paradoxical bronchospasm risk"],\n')
    f.write('    sideEffects: ["Oral thrush","Dysphonia","Headache","Nasopharyngitis","Cough"],\n')
    f.write('    patientInstructions: "Take ONCE DAILY at the same time each day. This is a preventer not a reliever. Rinse mouth after use. You still need your blue rescue inhaler for quick relief.",\n')
    f.write('    monitoring: ["ACT score","Peak flow","Adherence","Exacerbation rate"],\n')
    f.write('    interactions: ["Ritonavir increases fluticasone exposure","Ketoconazole increases levels","Beta-blockers antagonize vilanterol"],\n')
    f.write('    pregnancyCategory: "C, limited data",\n')
    f.write('    color: "#7c3aed", tlColor: "#a855f7",\n')
    f.write('  },\n')
    f.write('  "Salmeterol": {\n')
    f.write('    drugClass: "Long-Acting Beta-Agonist (LABA)",\n')
    f.write('    mechanism: "Selective beta2-adrenoceptor agonist, sustained bronchodilation 12h+. Onset 30-60 min, NOT a reliever. Must never be used without ICS.",\n')
    f.write('    minDose: 50, maxDose: 100, unit: "mcg",\n')
    f.write('    commonDoses: ["50","100"], frequencies: ["BD"], routes: ["Inhaled (pMDI/DPI)"],\n')
    f.write('    indications: ["Add-on to ICS in persistent asthma step 3-5 GINA","Maintenance bronchodilation"],\n')
    f.write('    contraindications: ["Asthma monotherapy must be combined with ICS","Acute bronchospasm slow onset","Hypersensitivity"],\n')
    f.write('    warnings: ["NEVER use as monotherapy in asthma increased mortality SMART study","NEVER use as rescue inhaler","CV effects QT prolongation tachycardia"],\n')
    f.write('    sideEffects: ["Headache","Tremor","Tachycardia","Palpitations","Muscle cramps","Nervousness","QT prolongation"],\n')
    f.write('    patientInstructions: "Take EXACTLY as prescribed always with your brown/preventer inhaler ICS. Do NOT use for sudden symptoms, use your blue inhaler instead.",\n')
    f.write('    monitoring: ["ACT score","Peak flow","CV monitoring HR ECG if high dose","Exacerbation frequency"],\n')
    f.write('    interactions: ["Beta-blockers cause bronchoconstriction","Diuretics cause hypokalemia","MAOIs cause hypertensive crisis","Antiarrhythmics additive QT prolongation"],\n')
    f.write('    pregnancyCategory: "C, limited data, use with ICS if needed",\n')
    f.write('    color: "#d97706", tlColor: "#f59e0b",\n')
    f.write('  },\n')
    f.write('  "Formoterol": {\n')
    f.write('    drugClass: "Long-Acting Beta-Agonist (LABA) Fast Onset",\n')
    f.write('    mechanism: "Selective beta2-agonist with rapid onset 1-3 min and long duration 12h. Unique among LABAs can be used both for maintenance and symptom relief SMART/MART.",\n')
    f.write('    minDose: 6, maxDose: 12, unit: "mcg",\n')
    f.write('    commonDoses: ["6","12"], frequencies: ["BD","PRN"], routes: ["Inhaled (DPI/pMDI)"],\n')
    f.write('    indications: ["Maintenance asthma therapy with ICS","SMART/MART therapy as reliever","Exercise-induced bronchoconstriction"],\n')
    f.write('    contraindications: ["Monotherapy in asthma must combine with ICS","Hypersensitivity"],\n')
    f.write('    warnings: ["Can be used as reliever ONLY when combined with ICS in a single inhaler","Formoterol as reliever without ICS increases exacerbation risk","Paradoxical bronchospasm","CV effects"],\n')
    f.write('    sideEffects: ["Tremor","Headache","Tachycardia","Palpitations","Cough","Nervousness"],\n')
    f.write('    patientInstructions: "When used in SMART regimen use same inhaler for maintenance and relief. As maintenance 1-2 puffs BD. As relief 1 puff PRN. Max 8 puffs per day includes maintenance doses.",\n')
    f.write('    monitoring: ["Asthma control","Exacerbation rate","Peak flow","Inhaler technique"],\n')
    f.write('    interactions: ["Beta-blockers antagonize","Diuretics cause hypokalemia","MAOIs cause hypertensive crisis"],\n')
    f.write('    pregnancyCategory: "C, limited data",\n')
    f.write('    color: "#d97706", tlColor: "#fbbf24",\n')
    f.write('  },\n')

print("First half of PHARMA_DB written")
