'use client';
import React, { useRef, useState, useMemo } from 'react';

interface MedicalDocumentProps {
  title: string;
  patientName: string;
  patientId: string;
  unit: string;
  date: string;
  noteText: string;
  filename?: string;
}

function parseNote(text: string): { type: string; content: string; level?: number }[] {
  const lines = text.split('\n');
  const blocks: { type: string; content: string; level?: number }[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      blocks.push({ type: 'spacer', content: '' });
      continue;
    }
    if (trimmed.startsWith('# ') || trimmed.startsWith('## ')) {
      const level = trimmed.startsWith('## ') ? 2 : 1;
      blocks.push({ type: 'heading', content: trimmed.replace(/^#+ /, ''), level });
      continue;
    }
    if (trimmed.startsWith('---')) {
      blocks.push({ type: 'divider', content: '' });
      continue;
    }
    if (trimmed.startsWith('- ')) {
      blocks.push({ type: 'list', content: trimmed.slice(2) });
      continue;
    }
    if (trimmed.startsWith('|')) {
      blocks.push({ type: 'table', content: trimmed });
      continue;
    }
    blocks.push({ type: 'text', content: trimmed });
  }
  return blocks;
}

function renderInline(text: string): React.ReactNode {
  const parts: React.ReactNode[] = [];
  const regex = /\*\*(.*?)\*\*/g;
  let lastIdx = 0;
  let match: RegExpExecArray | null;

  while ((match = regex.exec(text)) !== null) {
    if (match.index > lastIdx) {
      parts.push(text.slice(lastIdx, match.index));
    }
    parts.push(<strong key={match.index}>{match[1]}</strong>);
    lastIdx = match.index + match[0].length;
  }
  if (lastIdx < text.length) {
    parts.push(text.slice(lastIdx));
  }
  return parts.length > 0 ? parts : text;
}

export function MedicalDocument({
  title,
  patientName,
  patientId,
  unit,
  date,
  noteText,
  filename = 'clinical-note.pdf',
}: MedicalDocumentProps) {
  const docRef = useRef<HTMLDivElement>(null);
  const [pdfGenerating, setPdfGenerating] = useState(false);

  const blocks = useMemo(() => parseNote(noteText), [noteText]);

  const handlePrint = () => {
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>${title}</title>
        <style>
          @page { margin: 20mm 15mm; size: A4; }
          * { box-sizing: border-box; margin: 0; padding: 0; }
          body { font-family: 'Segoe UI', -apple-system, sans-serif; color: #1a1a1a; line-height: 1.6; padding: 20px; }
          .letterhead { border-bottom: 3px solid #1e3a5f; padding-bottom: 12px; margin-bottom: 16px; }
          .letterhead h1 { font-size: 18px; color: #1e3a5f; margin: 0; }
          .letterhead .sub { font-size: 11px; color: #64748b; margin-top: 2px; display: flex; justify-content: space-between; }
          .patient-header { display: flex; gap: 20px; font-size: 11px; color: #475569; margin-bottom: 16px; padding: 8px 12px; background: #f8fafc; border-radius: 4px; }
          .patient-header span { font-weight: 600; color: #1e3a5f; }
          h2 { font-size: 14px; color: #1e3a5f; margin: 16px 0 8px; padding-bottom: 4px; border-bottom: 1px solid #e2e8f0; }
          p { font-size: 12px; margin: 4px 0; }
          ul { padding-left: 20px; list-style: disc; }
          li { font-size: 12px; margin: 2px 0; }
          hr { border: none; border-top: 1px solid #e2e8f0; margin: 12px 0; }
          .footer { margin-top: 24px; padding-top: 12px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #94a3b8; text-align: center; }
          pre { font-family: 'Cascadia Code', 'Fira Code', monospace; font-size: 11px; background: #f8fafc; padding: 12px; border-radius: 4px; white-space: pre-wrap; }
          table { width: 100%; border-collapse: collapse; font-size: 11px; margin: 8px 0; }
          td, th { border: 1px solid #e2e8f0; padding: 6px 8px; text-align: left; }
          th { background: #f1f5f9; font-weight: 600; }
    </style>
  </head>
  <body>
    <div class="letterhead">
      <h1>AMEXAN Medical Centre</h1>
      <div class="sub">
        <span>${title}</span>
        <span>${date}</span>
      </div>
    </div>
    <div class="patient-header">
      <div><span>Patient:</span> ${patientName}</div>
      <div><span>MRN:</span> ${patientId}</div>
      <div><span>Unit:</span> ${unit}</div>
    </div>
    <pre>${noteText}</pre>
    <div class="footer">Generated by AMEXAN Clinical Reasoning System</div>
  </body>
  </html>
`);
win.document.close();
win.focus();
setTimeout(() => win.print(), 300);
};

const handleDownloadPDF = async () => {
if (!docRef.current || pdfGenerating) return;
setPdfGenerating(true);
try {
const { default: html2canvas } = await import('html2canvas');
const { default: jsPDF } = await import('jspdf');

const canvas = await html2canvas(docRef.current, {
scale: 2,
useCORS: true,
logging: false,
backgroundColor: '#ffffff',
});
const imgData = canvas.toDataURL('image/png');
const doc = new jsPDF('p', 'mm', 'a4');
const pageWidth = doc.internal.pageSize.getWidth();
const pageHeight = doc.internal.pageSize.getHeight();
const margin = 15;
const usableWidth = pageWidth - margin * 2;
const imgHeight = (canvas.height * usableWidth) / canvas.width;

let heightLeft = imgHeight;
let position = margin;

doc.addImage(imgData, 'PNG', margin, position, usableWidth, imgHeight);
heightLeft -= pageHeight - margin * 2;

while (heightLeft > 0) {
position = -(imgHeight - heightLeft) + margin;
doc.addPage();
doc.addImage(imgData, 'PNG', margin, position, usableWidth, imgHeight);
heightLeft -= pageHeight - margin * 2;
}

doc.save(filename);
} catch (err) {
console.error('PDF generation failed:', err);
} finally {
setPdfGenerating(false);
}
};

return (
<div className="border rounded-xl bg-white shadow-sm overflow-hidden">
<div className="flex items-center justify-between px-5 py-3 bg-gray-50 border-b print:hidden">
<div className="flex items-center gap-3">
<h3 className="text-sm font-bold text-gray-800">{title}</h3>
<span className="text-xs text-gray-400">{date}</span>
</div>
<div className="flex gap-2">
<button
onClick={handleDownloadPDF}
disabled={pdfGenerating}
className="px-3 py-1.5 text-xs font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 disabled:opacity-50 transition-colors flex items-center gap-1.5"
>
{pdfGenerating ? (
<><span className="animate-spin">⟳</span> Generating...</>
) : (
<><svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg> PDF</>
)}
</button>
<button
onClick={handlePrint}
className="px-3 py-1.5 text-xs font-medium text-gray-600 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors flex items-center gap-1.5"
>
<svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" /></svg>
Print
</button>
</div>
</div>

<div ref={docRef} className="bg-white" style={{ fontFamily: "'Segoe UI', -apple-system, sans-serif" }}>
<div className="px-8 pt-8 pb-4 border-b-2" style={{ borderColor: '#1e3a5f' }}>
<div className="flex items-center justify-between">
<div>
<h1 className="text-lg font-bold" style={{ color: '#1e3a5f', margin: 0 }}>AMEXAN Medical Centre</h1>
<p className="text-xs" style={{ color: '#64748b', marginTop: 2 }}>Teaching & Referral Hospital · Surgery Department</p>
</div>
<div className="text-right">
<p className="text-xs font-semibold" style={{ color: '#1e3a5f' }}>{title}</p>
<p className="text-xs" style={{ color: '#64748b' }}>{date}</p>
</div>
</div>
</div>

<div className="px-8 py-3" style={{ background: '#f8fafc', borderBottom: '1px solid #e2e8f0', display: 'flex', gap: 24, fontSize: 11, color: '#475569' }}>
<div><span style={{ fontWeight: 600, color: '#1e3a5f' }}>Patient:</span> {patientName}</div>
<div><span style={{ fontWeight: 600, color: '#1e3a5f' }}>MRN:</span> {patientId}</div>
<div><span style={{ fontWeight: 600, color: '#1e3a5f' }}>Unit:</span> {unit.replace(/-/g, ' ')}</div>
</div>

<div className="px-8 py-6 text-sm leading-relaxed" style={{ color: '#1a1a1a', minHeight: 400 }}>
{blocks.map((block, i) => {
switch (block.type) {
case 'heading':
return block.level === 1 ? (
<h1 key={i} className="text-base font-bold" style={{ color: '#1e3a5f', margin: '0 0 4px', paddingBottom: 4, borderBottom: '1px solid #e2e8f0' }}>{block.content}</h1>
) : (
<h2 key={i} className="text-sm font-semibold" style={{ color: '#1e3a5f', margin: '14px 0 6px', paddingBottom: 3, borderBottom: '1px solid #e2e8f0' }}>{block.content}</h2>
);
case 'text':
return <p key={i} className="text-sm" style={{ margin: '3px 0' }}>{renderInline(block.content)}</p>;
case 'list':
return <li key={i} className="text-sm" style={{ margin: '1px 0', marginLeft: 16 }}>{renderInline(block.content)}</li>;
case 'divider':
return <hr key={i} style={{ border: 'none', borderTop: '1px solid #e2e8f0', margin: '10px 0' }} />;
case 'spacer':
return <div key={i} style={{ height: 6 }} />;
case 'table':
return <p key={i} className="text-xs font-mono" style={{ margin: '2px 0', color: '#475569' }}>{block.content}</p>;
default:
return null;
}
})}
</div>

<div className="px-8 py-4 border-t text-center text-xs" style={{ color: '#94a3b8', borderColor: '#e2e8f0' }}>
Generated by AMEXAN Clinical Reasoning System · All data stored as structured clinical facts
</div>
</div>
</div>
);
}
