package crl

import (
	"time"
	"github.com/amexan/backend/crl/core"
)

// CardiologyRules returns all cardiology rules
func CardiologyRules() []*core.Rule {
	now := time.Now()
	return []*core.Rule{
		// CARD-0001: Chest pain comprehensive assessment
		{
			Code:        "CARD-0001",
			Name:        "Chest Pain Comprehensive History",
			Description: "Full chest pain history including cardiac, respiratory, and musculoskeletal causes",
			Category:    core.CategoryHistory,
			Priority:    core.PriorityCritical,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "chief_complaint", Operator: core.OpContains, Value: "chest pain", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "chest discomfort", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "chest tightness"},
			},
			Actions: []core.Action{
				{Type: core.ActionRecommendQuestion, Target: "When did the chest pain start?"},
				{Type: core.ActionRecommendQuestion, Target: "Was onset sudden or gradual?"},
				{Type: core.ActionRecommendQuestion, Target: "Describe the pain (sharp, dull, burning, pressure, tearing)?"},
				{Type: core.ActionRecommendQuestion, Target: "Rate severity 0-10"},
				{Type: core.ActionRecommendQuestion, Target: "Does the pain radiate? (left arm, jaw, back, shoulder)"},
				{Type: core.ActionRecommendQuestion, Target: "What makes it better or worse?"},
				{Type: core.ActionRecommendQuestion, Target: "Is it related to exertion or emotion?"},
				{Type: core.ActionRecommendQuestion, Target: "Is it pleuritic (worse with breathing/coughing)?"},
				{Type: core.ActionRecommendQuestion, Target: "Any associated shortness of breath?"},
				{Type: core.ActionRecommendQuestion, Target: "Any associated sweating (diaphoresis)?"},
				{Type: core.ActionRecommendQuestion, Target: "Any associated nausea or vomiting?"},
				{Type: core.ActionRecommendQuestion, Target: "Any palpitations or dizziness?"},
				{Type: core.ActionRecommendQuestion, Target: "Any previous similar episodes?"},
				{Type: core.ActionRecommendQuestion, Target: "Any known heart disease, hypertension, diabetes?"},
				{Type: core.ActionRecommendQuestion, Target: "Smoking history? Cholesterol levels?"},
				{Type: core.ActionRequireField, Target: "ecg_done"},
				{Type: core.ActionRequireField, Target: "cardiac_risk_factors"},
				{Type: core.ActionRequireField, Target: "red_flag_acs"},
				{Type: core.ActionAddDifferential, Target: "acute_coronary_syndrome"},
				{Type: core.ActionAddDifferential, Target: "pulmonary_embolism"},
				{Type: core.ActionAddDifferential, Target: "aortic_dissection"},
				{Type: core.ActionAddDifferential, Target: "pericarditis"},
				{Type: core.ActionAddDifferential, Target: "pneumothorax"},
				{Type: core.ActionAddDifferential, Target: "pneumonia"},
				{Type: core.ActionAddDifferential, Target: "gastroesophageal_reflux"},
				{Type: core.ActionAddDifferential, Target: "musculoskeletal_chest_pain"},
				{Type: core.ActionAddDifferential, Target: "anxiety_panic_attack"},
			},
			Evidence: "ESC Guidelines for management of acute coronary syndromes; Hutchison's: Chest pain evaluation",
			CreatedAt: now,
			UpdatedAt: now,
		},

		// CARD-0002: ACS red flag (crushing chest pain + radiation + sweating)
		{
			Code:        "CARD-0002",
			Name:        "Acute Coronary Syndrome Red Flag",
			Description: "Crushing/retrosternal chest pain with radiation and autonomic features = STEMI until proven",
			Category:    core.CategoryDiagnosis,
			Priority:    core.PriorityCritical,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "chest_pain_crushing", Operator: core.OpEquals, Value: true, Join: core.JoinAnd},
				{Field: "radiation_left_arm_jaw", Operator: core.OpEquals, Value: true, Join: core.JoinAnd},
				{Field: "diaphoresis", Operator: core.OpEquals, Value: true},
			},
			Actions: []core.Action{
				{Type: core.ActionTriggerAlert, Target: "SUSPECTED ACUTE CORONARY SYNDROME — STAT ECG, aspirin, cardiac monitoring"},
				{Type: core.ActionRecommendInvestigation, Target: "ecg_stat"},
				{Type: core.ActionRecommendInvestigation, Target: "high_sensitivity_troponin"},
				{Type: core.ActionRecommendInvestigation, Target: "cxr"},
				{Type: core.ActionRequireField, Target: "ecg_findings"},
				{Type: core.ActionRequireField, Target: "st_segment_analysis"},
				{Type: core.ActionUpdateProbability, Target: "acute_coronary_syndrome", Parameters: map[string]interface{}{"delta": 4.0}},
			},
			Evidence: "ESC NSTEMI/STEMI Guidelines: Time is muscle. Door-to-balloon <90 min for STEMI",
			CreatedAt: now,
			UpdatedAt: now,
		},

		// CARD-0003: Heart failure assessment
		{
			Code:        "CARD-0003",
			Name:        "Heart Failure History and Assessment",
			Description: "Comprehensive heart failure evaluation including NYHA classification and signs of congestion",
			Category:    core.CategoryHistory,
			Priority:    core.PriorityHigh,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "chief_complaint", Operator: core.OpContains, Value: "shortness of breath", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "breathless", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "dyspnoea", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "leg swelling", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "oedema"},
			},
			Actions: []core.Action{
				{Type: core.ActionRecommendQuestion, Target: "When did the breathlessness start?"},
				{Type: core.ActionRecommendQuestion, Target: "What activity level brings on the breathlessness?"},
				{Type: core.ActionRecommendQuestion, Target: "Can you lie flat at night (orthopnoea)?"},
				{Type: core.ActionRecommendQuestion, Target: "Do you wake up gasping for breath (PND)?"},
				{Type: core.ActionRecommendQuestion, Target: "Any swelling in your legs or ankles?"},
				{Type: core.ActionRecommendQuestion, Target: "Any cough, especially at night?"},
				{Type: core.ActionRecommendQuestion, Target: "Any chest pain or palpitations?"},
				{Type: core.ActionRecommendQuestion, Target: "Any known heart disease, hypertension, or diabetes?"},
				{Type: core.ActionRecommendQuestion, Target: "How many pillows do you sleep on?"},
				{Type: core.ActionRequireField, Target: "nyha_class"},
				{Type: core.ActionRequireField, Target: "peripheral_oedema"},
				{Type: core.ActionRequireField, Target: "jvp_assessment"},
				{Type: core.ActionRequireField, Target: "lung_auscultation_crepitations"},
				{Type: core.ActionRecommendInvestigation, Target: "bnt_pro_bnp"},
				{Type: core.ActionRecommendInvestigation, Target: "echo_cardiography"},
				{Type: core.ActionRecommendInvestigation, Target: "ecg"},
				{Type: core.ActionRecommendInvestigation, Target: "cxr_heart_size"},
				{Type: core.ActionAddDifferential, Target: "heart_failure_rfref"},
				{Type: core.ActionAddDifferential, Target: "heart_failure_hfpef"},
			},
			Evidence: "ESC Heart Failure Guidelines; NYHA Functional Classification",
			CreatedAt: now,
			UpdatedAt: now,
		},

		// CARD-0004: Palpitations / Arrhythmia assessment
		{
			Code:        "CARD-0004",
			Name:        "Palpitations and Arrhythmia History",
			Description: "Structured palpitation history for arrhythmia evaluation",
			Category:    core.CategoryHistory,
			Priority:    core.PriorityNormal,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "chief_complaint", Operator: core.OpContains, Value: "palpitation", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "irregular heartbeat", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "racing heart"},
			},
			Actions: []core.Action{
				{Type: core.ActionRecommendQuestion, Target: "When did the palpitations start?"},
				{Type: core.ActionRecommendQuestion, Target: "Can you describe the sensation (racing, fluttering, skipping, pounding)?"},
				{Type: core.ActionRecommendQuestion, Target: "Do they start and stop suddenly or gradually?"},
				{Type: core.ActionRecommendQuestion, Target: "How long do episodes last?"},
				{Type: core.ActionRecommendQuestion, Target: "Any triggers (caffeine, alcohol, stress, exertion)?"},
				{Type: core.ActionRecommendQuestion, Target: "Any associated chest pain, dizziness, or fainting?"},
				{Type: core.ActionRecommendQuestion, Target: "Any shortness of breath during episodes?"},
				{Type: core.ActionRecommendQuestion, Target: "Have you ever passed out during an episode?"},
				{Type: core.ActionRecommendQuestion, Target: "Any known heart or thyroid disease?"},
				{Type: core.ActionRequireField, Target: "ecg_rhythm_strip"},
				{Type: core.ActionRequireField, Target: "pulse_character"},
				{Type: core.ActionRecommendInvestigation, Target: "ecg_12_lead"},
				{Type: core.ActionRecommendInvestigation, Target: "holter_monitor"},
				{Type: core.ActionRecommendInvestigation, Target: "echo"},
				{Type: core.ActionRecommendInvestigation, Target: "thyroid_function"},
				{Type: core.ActionAddDifferential, Target: "atrial_fibrillation"},
				{Type: core.ActionAddDifferential, Target: "supraventricular_tachycardia"},
				{Type: core.ActionAddDifferential, Target: "ventricular_ectopics"},
				{Type: core.ActionAddDifferential, Target: "panic_attack"},
			},
			CreatedAt: now,
			UpdatedAt: now,
		},

		// CARD-0005: Aortic dissection red flag
		{
			Code:        "CARD-0005",
			Name:        "Aortic Dissection Red Flag",
			Description: "Sudden severe tearing chest pain radiating to back, with pulse deficit or BP differential",
			Category:    core.CategoryDiagnosis,
			Priority:    core.PriorityCritical,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "chest_pain_tearing", Operator: core.OpEquals, Value: true, Join: core.JoinAnd},
				{Field: "pain_radiation_to_back", Operator: core.OpEquals, Value: true, Join: core.JoinAnd},
				{Field: "sudden_onset", Operator: core.OpEquals, Value: true},
			},
			Actions: []core.Action{
				{Type: core.ActionTriggerAlert, Target: "SUSPECTED AORTIC DISSECTION — Emergency CT aortogram, BP control, cardiothoracic referral"},
				{Type: core.ActionRequireField, Target: "bp_both_arms"},
				{Type: core.ActionRequireField, Target: "pulse_deficit"},
				{Type: core.ActionRecommendInvestigation, Target: "ct_aortogram_emergency"},
				{Type: core.ActionRecommendInvestigation, Target: "chest_xray_wide_mediastinum"},
				{Type: core.ActionRecommendReferral, Target: "cardiothoracic_surgery"},
				{Type: core.ActionUpdateProbability, Target: "aortic_dissection", Parameters: map[string]interface{}{"delta": 4.5}},
			},
			Evidence: "Aortic dissection is a surgical emergency. Mortality increases 1-2% per hour without treatment.",
			CreatedAt: now,
			UpdatedAt: now,
		},

		// CARD-0006: Cardiovascular examination modules
		{
			Code:        "CARD-0006",
			Name:        "Cardiovascular Examination Modules",
			Description: "Activates CV exam techniques: inspection, palpation, auscultation, JVP, peripheral signs",
			Category:    core.CategoryExamination,
			Priority:    core.PriorityHigh,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "chief_complaint", Operator: core.OpContains, Value: "chest", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "breathless", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "palpitation", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "leg swelling"},
			},
			Actions: []core.Action{
				{Type: core.ActionRecommendExam, Target: "general_inspection"},
				{Type: core.ActionRecommendExam, Target: "hand_examination"},
				{Type: core.ActionRecommendExam, Target: "pulse_character_rate_rhythm"},
				{Type: core.ActionRecommendExam, Target: "blood_pressure_both_arms"},
				{Type: core.ActionRecommendExam, Target: "jvp_assessment"},
				{Type: core.ActionRecommendExam, Target: "precordium_inspection_palpation"},
				{Type: core.ActionRecommendExam, Target: "cardiac_auscultation"},
				{Type: core.ActionRecommendExam, Target: "lung_auscultation"},
				{Type: core.ActionRecommendExam, Target: "peripheral_oedema"},
				{Type: core.ActionRecommendExam, Target: "peripheral_pulses"},
			},
			CreatedAt: now,
			UpdatedAt: now,
		},
	}
}
