package crl

import (
	"time"
	"github.com/amexan/backend/crl/core"
)

// RespiratoryRules returns all respiratory / pulmonology rules
func RespiratoryRules() []*core.Rule {
	now := time.Now()
	return []*core.Rule{
		// RESP-0001: Cough comprehensive assessment
		{
			Code:        "RESP-0001",
			Name:        "Cough Comprehensive History",
			Description: "Full cough history including acute vs chronic, dry vs productive",
			Category:    core.CategoryHistory,
			Priority:    core.PriorityHigh,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "chief_complaint", Operator: core.OpContains, Value: "cough", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "coughing"},
			},
			Actions: []core.Action{
				{Type: core.ActionRecommendQuestion, Target: "How long have you had the cough?"},
				{Type: core.ActionRecommendQuestion, Target: "Is the cough dry or productive?"},
				{Type: core.ActionRecommendQuestion, Target: "If productive: what color, amount, and consistency of sputum?"},
				{Type: core.ActionRecommendQuestion, Target: "Is there any blood in the sputum (hemoptysis)?"},
				{Type: core.ActionRecommendQuestion, Target: "Any associated shortness of breath?"},
				{Type: core.ActionRecommendQuestion, Target: "Any fever or night sweats?"},
				{Type: core.ActionRecommendQuestion, Target: "Any chest pain?"},
				{Type: core.ActionRecommendQuestion, Target: "Any wheezing?"},
				{Type: core.ActionRecommendQuestion, Target: "Any weight loss?"},
				{Type: core.ActionRecommendQuestion, Target: "Any smoking history?"},
				{Type: core.ActionRecommendQuestion, Target: "Any known asthma, COPD, or TB?"},
				{Type: core.ActionRecommendQuestion, Target: "Any recent travel or sick contacts?"},
				{Type: core.ActionRequireField, Target: "cough_duration_days"},
				{Type: core.ActionRequireField, Target: "sputum_characteristics"},
				{Type: core.ActionRequireField, Target: "hemoptysis"},
				{Type: core.ActionRequireField, Target: "oxygen_saturation"},
				{Type: core.ActionAddDifferential, Target: "acute_bronchitis"},
				{Type: core.ActionAddDifferential, Target: "community_acquired_pneumonia"},
				{Type: core.ActionAddDifferential, Target: "copd_exacerbation"},
				{Type: core.ActionAddDifferential, Target: "asthma"},
				{Type: core.ActionAddDifferential, Target: "tuberculosis"},
				{Type: core.ActionAddDifferential, Target: "pulmonary_embolism"},
				{Type: core.ActionAddDifferential, Target: "lung_cancer"},
				{Type: core.ActionAddDifferential, Target: "bronchiectasis"},
				{Type: core.ActionAddDifferential, Target: "post_nasal_drip"},
			},
			Evidence: "NICE Cough guidelines: Acute cough <3 weeks, chronic >8 weeks",
			CreatedAt: now,
			UpdatedAt: now,
		},

		// RESP-0002: Hemoptysis red flag
		{
			Code:        "RESP-0002",
			Name:        "Hemoptysis Red Flag Assessment",
			Description: "Coughing up blood requires urgent investigation for TB, malignancy, bronchiectasis, PE",
			Category:    core.CategoryDiagnosis,
			Priority:    core.PriorityHigh,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "hemoptysis", Operator: core.OpEquals, Value: true, Join: core.JoinOr},
				{Field: "blood_streaked_sputum", Operator: core.OpEquals, Value: true},
			},
			Actions: []core.Action{
				{Type: core.ActionRecommendQuestion, Target: "How much blood? (streaks, teaspoon, cupful)"},
				{Type: core.ActionRecommendQuestion, Target: "Is this the first time or recurrent?"},
				{Type: core.ActionRecommendQuestion, Target: "Any weight loss, night sweats, or fever?"},
				{Type: core.ActionRecommendQuestion, Target: "Any smoking history? How many pack-years?"},
				{Type: core.ActionRecommendQuestion, Target: "Any history of TB exposure?"},
				{Type: core.ActionRequireField, Target: "cxr_result"},
				{Type: core.ActionRequireField, Target: "sputum_afb_culture"},
				{Type: core.ActionRecommendInvestigation, Target: "chest_xray"},
				{Type: core.ActionRecommendInvestigation, Target: "ct_chest"},
				{Type: core.ActionRecommendInvestigation, Target: "sputum_mcs_afb"},
				{Type: core.ActionRecommendInvestigation, Target: "bronchoscopy"},
				{Type: core.ActionAddDifferential, Target: "tuberculosis"},
				{Type: core.ActionAddDifferential, Target: "bronchogenic_carcinoma"},
				{Type: core.ActionAddDifferential, Target: "bronchiectasis"},
				{Type: core.ActionAddDifferential, Target: "pulmonary_embolism_infarction"},
				{Type: core.ActionAddDifferential, Target: "pneumonia"},
				{Type: core.ActionTriggerAlert, Target: "Hemoptysis requires urgent CXR and TB workup"},
			},
			CreatedAt: now,
			UpdatedAt: now,
		},

		// RESP-0003: Shortness of breath / dyspnoea assessment
		{
			Code:        "RESP-0003",
			Name:        "Shortness of Breath / Dyspnoea Assessment",
			Description: "Structured breathlessness assessment with MRC dyspnoea scale",
			Category:    core.CategoryHistory,
			Priority:    core.PriorityHigh,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "chief_complaint", Operator: core.OpContains, Value: "shortness of breath", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "dyspnoea", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "breathless", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "difficulty breathing"},
			},
			Actions: []core.Action{
				{Type: core.ActionRecommendQuestion, Target: "When did the breathlessness start?"},
				{Type: core.ActionRecommendQuestion, Target: "Was onset sudden or gradual?"},
				{Type: core.ActionRecommendQuestion, Target: "What activity level brings on breathlessness? (MRC scale)"},
				{Type: core.ActionRecommendQuestion, Target: "Can you lie flat? How many pillows?"},
				{Type: core.ActionRecommendQuestion, Target: "Do you wake up gasping for air (PND)?"},
				{Type: core.ActionRecommendQuestion, Target: "Any associated cough or wheeze?"},
				{Type: core.ActionRecommendQuestion, Target: "Any associated chest pain or palpitations?"},
				{Type: core.ActionRecommendQuestion, Target: "Any leg swelling?"},
				{Type: core.ActionRecommendQuestion, Target: "Any fever or cough with sputum?"},
				{Type: core.ActionRequireField, Target: "mrc_dyspnoea_scale"},
				{Type: core.ActionRequireField, Target: "oxygen_saturation_rest"},
				{Type: core.ActionRequireField, Target: "respiratory_rate"},
				{Type: core.ActionRequireField, Target: "use_of_accessory_muscles"},
				{Type: core.ActionAddDifferential, Target: "pneumonia"},
				{Type: core.ActionAddDifferential, Target: "copd_exacerbation"},
				{Type: core.ActionAddDifferential, Target: "asthma_exacerbation"},
				{Type: core.ActionAddDifferential, Target: "pulmonary_embolism"},
				{Type: core.ActionAddDifferential, Target: "pneumothorax"},
				{Type: core.ActionAddDifferential, Target: "heart_failure"},
				{Type: core.ActionAddDifferential, Target: "pulmonary_fibrosis"},
				{Type: core.ActionAddDifferential, Target: "anxiety_hyperventilation"},
			},
			CreatedAt: now,
			UpdatedAt: now,
		},

		// RESP-0004: Respiratory examination modules
		{
			Code:        "RESP-0004",
			Name:        "Respiratory Examination Modules",
			Description: "Activates respiratory exam: inspection, palpation, percussion, auscultation",
			Category:    core.CategoryExamination,
			Priority:    core.PriorityHigh,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "chief_complaint", Operator: core.OpContains, Value: "cough", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "breathless", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "dyspnoea", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "wheeze"},
			},
			Actions: []core.Action{
				{Type: core.ActionRecommendExam, Target: "general_inspection_respiratory"},
				{Type: core.ActionRecommendExam, Target: "chest_inspection"},
				{Type: core.ActionRecommendExam, Target: "chest_palpation"},
				{Type: core.ActionRecommendExam, Target: "chest_percussion"},
				{Type: core.ActionRecommendExam, Target: "chest_auscultation"},
				{Type: core.ActionRecommendExam, Target: "vocal_resonance"},
				{Type: core.ActionRecommendExam, Target: "peak_flow_measurement"},
				{Type: core.ActionRecommendExam, Target: "oxygen_saturation"},
			},
			CreatedAt: now,
			UpdatedAt: now,
		},

		// RESP-0005: Asthma/COPD exacerbation management
		{
			Code:        "RESP-0005",
			Name:        "Asthma and COPD Exacerbation Management",
			Description: "Protocol for acute asthma/COPD exacerbation: bronchodilators, steroids, oxygen",
			Category:    core.CategoryManagement,
			Priority:    core.PriorityHigh,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "wheezing", Operator: core.OpEquals, Value: true, Join: core.JoinAnd},
				{Field: "oxygen_saturation_below_94", Operator: core.OpEquals, Value: true, Join: core.JoinOr},
				{Field: "asthma_diagnosis", Operator: core.OpEquals, Value: true, Join: core.JoinOr},
				{Field: "copd_diagnosis", Operator: core.OpEquals, Value: true},
			},
			Actions: []core.Action{
				{Type: core.ActionRequireField, Target: "peak_expiratory_flow"},
				{Type: core.ActionRequireField, Target: "oxygen_saturation"},
				{Type: core.ActionRecommendInvestigation, Target: "abg_if_severe"},
				{Type: core.ActionRecommendInvestigation, Target: "cxr"},
				{Type: core.ActionActivatePathway, Target: "asthma_copd_exacerbation"},
			},
			Evidence: "BTS/SIGN Asthma Guidelines; GOLD COPD Guidelines",
			CreatedAt: now,
			UpdatedAt: now,
		},

		// RESP-0006: Pulmonary embolism red flag
		{
			Code:        "RESP-0006",
			Name:        "Pulmonary Embolism Red Flag",
			Description: "Sudden dyspnoea + pleuritic chest pain + hemoptysis + risk factors = PE until proven",
			Category:    core.CategoryDiagnosis,
			Priority:    core.PriorityCritical,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "dyspnoea_sudden_onset", Operator: core.OpEquals, Value: true, Join: core.JoinAnd},
				{Field: "pleuritic_chest_pain", Operator: core.OpEquals, Value: true, Join: core.JoinAnd},
				{Field: "pe_risk_factors", Operator: core.OpEquals, Value: true},
			},
			Actions: []core.Action{
				{Type: core.ActionTriggerAlert, Target: "SUSPECTED PULMONARY EMBOLISM — Wells score, D-dimer, CTPA if high probability"},
				{Type: core.ActionRequireField, Target: "wells_score_pe"},
				{Type: core.ActionRequireField, Target: "d_dimer_result"},
				{Type: core.ActionRecommendInvestigation, Target: "d_dimer"},
				{Type: core.ActionRecommendInvestigation, Target: "ctpa"},
				{Type: core.ActionRecommendInvestigation, Target: "ecg_s1q3t3"},
				{Type: core.ActionAddDifferential, Target: "pulmonary_embolism"},
				{Type: core.ActionUpdateProbability, Target: "pulmonary_embolism", Parameters: map[string]interface{}{"delta": 3.0}},
			},
			Evidence: "NICE Guideline NG158: Venous thromboembolic diseases; Wells score for PE",
			CreatedAt: now,
			UpdatedAt: now,
		},

		// RESP-0007: Pneumothorax red flag
		{
			Code:        "RESP-0007",
			Name:        "Pneumothorax Red Flag",
			Description: "Sudden unilateral pleuritic chest pain + dyspnoea + decreased breath sounds = pneumothorax",
			Category:    core.CategoryDiagnosis,
			Priority:    core.PriorityCritical,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "chest_pain_sudden", Operator: core.OpEquals, Value: true, Join: core.JoinAnd},
				{Field: "dyspnoea", Operator: core.OpEquals, Value: true, Join: core.JoinAnd},
				{Field: "decreased_breath_sounds_unilateral", Operator: core.OpEquals, Value: true},
			},
			Actions: []core.Action{
				{Type: core.ActionTriggerAlert, Target: "SUSPECTED PNEUMOTHORAX — Urgent CXR, chest drain if tension or large"},
				{Type: core.ActionRequireField, Target: "tracheal_deviation"},
				{Type: core.ActionRequireField, Target: "tension_pneumothorax_signs"},
				{Type: core.ActionRecommendInvestigation, Target: "chest_xray_emergency"},
				{Type: core.ActionAddDifferential, Target: "pneumothorax"},
				{Type: core.ActionAddDifferential, Target: "tension_pneumothorax"},
			},
			CreatedAt: now,
			UpdatedAt: now,
		},
	}
}
