package crl

import (
	"time"
	"github.com/amexan/backend/crl/core"
)

// NeurologyRules returns all neurology and neurosurgery rules
func NeurologyRules() []*core.Rule {
	now := time.Now()
	return []*core.Rule{
		// NEUR-0001: Headache comprehensive assessment
		{
			Code:        "NEUR-0001",
			Name:        "Headache Comprehensive History",
			Description: "Full headache history with red flag screening for secondary causes",
			Category:    core.CategoryHistory,
			Priority:    core.PriorityHigh,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "chief_complaint", Operator: core.OpContains, Value: "headache", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "head pain"},
			},
			Actions: []core.Action{
				{Type: core.ActionRecommendQuestion, Target: "When did the headache start?"},
				{Type: core.ActionRecommendQuestion, Target: "Was the onset sudden (thunderclap) or gradual?"},
				{Type: core.ActionRecommendQuestion, Target: "Where is the pain located (frontal, temporal, occipital, unilateral, diffuse)?"},
				{Type: core.ActionRecommendQuestion, Target: "Describe the pain (throbbing, pressure, stabbing, band-like)?"},
				{Type: core.ActionRecommendQuestion, Target: "Rate severity 0-10"},
				{Type: core.ActionRecommendQuestion, Target: "Any visual changes (aura, blurring, double vision)?"},
				{Type: core.ActionRecommendQuestion, Target: "Any nausea or vomiting?"},
				{Type: core.ActionRecommendQuestion, Target: "Any photophobia or phonophobia?"},
				{Type: core.ActionRecommendQuestion, Target: "Any neck stiffness or fever?"},
				{Type: core.ActionRecommendQuestion, Target: "Any neurological symptoms (weakness, numbness, speech changes)?"},
				{Type: core.ActionRecommendQuestion, Target: "Any known triggers?"},
				{Type: core.ActionRecommendQuestion, Target: "Any previous similar headaches? Pattern?"},
				{Type: core.ActionRecommendQuestion, Target: "Any head trauma recently?"},
				{Type: core.ActionRequireField, Target: "red_flag_thunderclap"},
				{Type: core.ActionRequireField, Target: "red_flag_meningitis"},
				{Type: core.ActionRequireField, Target: "red_flag_neurological_deficit"},
				{Type: core.ActionAddDifferential, Target: "tension_headache"},
				{Type: core.ActionAddDifferential, Target: "migraine_without_aura"},
				{Type: core.ActionAddDifferential, Target: "migraine_with_aura"},
				{Type: core.ActionAddDifferential, Target: "cluster_headache"},
				{Type: core.ActionAddDifferential, Target: "subarachnoid_haemorrhage"},
				{Type: core.ActionAddDifferential, Target: "meningitis_encephalitis"},
				{Type: core.ActionAddDifferential, Target: "temporal_arteritis"},
				{Type: core.ActionAddDifferential, Target: "intracranial_mass"},
				{Type: core.ActionAddDifferential, Target: "medication_overuse_headache"},
			},
			Evidence: "International Classification of Headache Disorders (ICHD-3); Hutchison's: Headache assessment",
			CreatedAt: now,
			UpdatedAt: now,
		},

		// NEUR-0002: Subarachnoid hemorrhage red flag
		{
			Code:        "NEUR-0002",
			Name:        "Subarachnoid Hemorrhage Red Flag",
			Description: "Thunderclap headache (worst headache of life) requires emergency CT and LP",
			Category:    core.CategoryDiagnosis,
			Priority:    core.PriorityCritical,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "headache_thunderclap", Operator: core.OpEquals, Value: true, Join: core.JoinAnd},
				{Field: "headache_sudden_onset", Operator: core.OpEquals, Value: true},
			},
			Actions: []core.Action{
				{Type: core.ActionTriggerAlert, Target: "SUSPECTED SUBARACHNOID HEMORRHAGE — Emergency CT head, if negative → LP"},
				{Type: core.ActionRecommendInvestigation, Target: "ct_head_emergency"},
				{Type: core.ActionRecommendInvestigation, Target: "lumbar_puncture_xanthochromia"},
				{Type: core.ActionRequireField, Target: "gcs_score"},
				{Type: core.ActionRequireField, Target: "neck_stiffness"},
				{Type: core.ActionRecommendReferral, Target: "neurosurgery_emergency"},
				{Type: core.ActionUpdateProbability, Target: "subarachnoid_haemorrhage", Parameters: map[string]interface{}{"delta": 4.5}},
			},
			Evidence: "NICE Headache guidelines: Sudden-onset thunderclap headache requires same-day CT and LP",
			CreatedAt: now,
			UpdatedAt: now,
		},

		// NEUR-0003: Stroke / TIA assessment
		{
			Code:        "NEUR-0003",
			Name:        "Stroke and Transient Ischaemic Attack Assessment",
			Description: "Rapid stroke assessment using FAST + ROSIER, activates stroke pathway",
			Category:    core.CategoryDiagnosis,
			Priority:    core.PriorityCritical,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "chief_complaint", Operator: core.OpContains, Value: "weakness", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "numb", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "slurred speech", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "facial droop", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "difficulty speaking"},
			},
			Actions: []core.Action{
				{Type: core.ActionRequireField, Target: "fast_assessment"},
				{Type: core.ActionRequireField, Target: "face_droop"},
				{Type: core.ActionRequireField, Target: "arm_weakness"},
				{Type: core.ActionRequireField, Target: "speech_abnormality"},
				{Type: core.ActionRequireField, Target: "time_of_onset_last_known_well"},
				{Type: core.ActionRequireField, Target: "roisier_score"},
				{Type: core.ActionRecommendQuestion, Target: "When was the patient last known to be well?"},
				{Type: core.ActionRecommendQuestion, Target: "Any sudden onset of weakness on one side?"},
				{Type: core.ActionRecommendQuestion, Target: "Any speech difficulty or confusion?"},
				{Type: core.ActionRecommendQuestion, Target: "Any previous strokes or TIAs?"},
				{Type: core.ActionRecommendQuestion, Target: "Any atrial fibrillation or heart disease?"},
				{Type: core.ActionRecommendQuestion, Target: "Any hypertension, diabetes, or smoking?"},
				{Type: core.ActionRecommendInvestigation, Target: "ct_head_emergency"},
				{Type: core.ActionRecommendInvestigation, Target: "ecg"},
				{Type: core.ActionRecommendInvestigation, Target: "blood_glucose"},
				{Type: core.ActionActivatePathway, Target: "stroke_care"},
				{Type: core.ActionAddDifferential, Target: "ischaemic_stroke"},
				{Type: core.ActionAddDifferential, Target: "haemorrhagic_stroke"},
				{Type: core.ActionAddDifferential, Target: "transient_ischaemic_attack"},
				{Type: core.ActionAddDifferential, Target: "stroke_mimic"},
			},
			Evidence: "NICE Stroke Guidelines (NG128): FAST assessment, door-to-needle <60 min for thrombolysis",
			CreatedAt: now,
			UpdatedAt: now,
		},

		// NEUR-0004: Seizure / epilepsy assessment
		{
			Code:        "NEUR-0004",
			Name:        "Seizure and Epilepsy History",
			Description: "Comprehensive seizure history including semiology, triggers, and risk factors",
			Category:    core.CategoryHistory,
			Priority:    core.PriorityHigh,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "chief_complaint", Operator: core.OpContains, Value: "seizure", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "fit", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "convulsion", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "passing out", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "unconscious"},
			},
			Actions: []core.Action{
				{Type: core.ActionRecommendQuestion, Target: "Can you describe what happened before, during, and after the episode?"},
				{Type: core.ActionRecommendQuestion, Target: "Was there an aura or warning before the event?"},
				{Type: core.ActionRecommendQuestion, Target: "Did the patient lose consciousness?"},
				{Type: core.ActionRecommendQuestion, Target: "Were there any jerking movements? Which body parts?"},
				{Type: core.ActionRecommendQuestion, Target: "Was there tongue biting, urinary incontinence, or frothing?"},
				{Type: core.ActionRecommendQuestion, Target: "How long did the episode last?"},
				{Type: core.ActionRecommendQuestion, Target: "Was the patient confused or sleepy afterward (post-ictal)?"},
				{Type: core.ActionRecommendQuestion, Target: "Any previous seizures or epilepsy diagnosis?"},
				{Type: core.ActionRecommendQuestion, Target: "Any history of head trauma, meningitis, or stroke?"},
				{Type: core.ActionRecommendQuestion, Target: "Any medication or alcohol use?"},
				{Type: core.ActionRecommendQuestion, Target: "Any fever or illness before the seizure?"},
				{Type: core.ActionRequireField, Target: "seizure_duration"},
				{Type: core.ActionRequireField, Target: "post_ictal_state"},
				{Type: core.ActionRequireField, Target: "eyewitness_account"},
				{Type: core.ActionRecommendInvestigation, Target: "eeg"},
				{Type: core.ActionRecommendInvestigation, Target: "ct_or_mri_brain"},
				{Type: core.ActionAddDifferential, Target: "generalized_tonic_clonic_seizure"},
				{Type: core.ActionAddDifferential, Target: "focal_seizure"},
				{Type: core.ActionAddDifferential, Target: "absence_seizure"},
				{Type: core.ActionAddDifferential, Target: "febrile_seizure"},
				{Type: core.ActionAddDifferential, Target: "syncope"},
				{Type: core.ActionAddDifferential, Target: "pseudoseizure"},
				{Type: core.ActionAddDifferential, Target: "status_epilepticus"},
			},
			CreatedAt: now,
			UpdatedAt: now,
		},

		// NEUR-0005: Neurological examination modules
		{
			Code:        "NEUR-0005",
			Name:        "Neurological Examination Modules",
			Description: "Activates neurological exam based on presenting symptoms",
			Category:    core.CategoryExamination,
			Priority:    core.PriorityNormal,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "chief_complaint", Operator: core.OpContains, Value: "headache", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "dizzy", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "weakness", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "numb", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "seizure", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "faint"},
			},
			Actions: []core.Action{
				{Type: core.ActionRecommendExam, Target: "mental_state_examination"},
				{Type: core.ActionRecommendExam, Target: "cranial_nerve_examination"},
				{Type: core.ActionRecommendExam, Target: "motor_system_examination"},
				{Type: core.ActionRecommendExam, Target: "sensory_examination"},
				{Type: core.ActionRecommendExam, Target: "cerebellar_examination"},
				{Type: core.ActionRecommendExam, Target: "gait_assessment"},
				{Type: core.ActionRecommendExam, Target: "reflexes"},
				{Type: core.ActionRecommendExam, Target: "fundoscopy"},
				{Type: core.ActionRecommendExam, Target: "meningism_signs"},
			},
			CreatedAt: now,
			UpdatedAt: now,
		},

		// NEUR-0006: Meningitis red flag
		{
			Code:        "NEUR-0006",
			Name:        "Meningitis Red Flag",
			Description: "Headache + fever + neck stiffness + altered consciousness = meningitis until proven",
			Category:    core.CategoryDiagnosis,
			Priority:    core.PriorityCritical,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "headache", Operator: core.OpEquals, Value: true, Join: core.JoinAnd},
				{Field: "fever", Operator: core.OpEquals, Value: true, Join: core.JoinAnd},
				{Field: "neck_stiffness", Operator: core.OpEquals, Value: true, Join: core.JoinAnd},
				{Field: "altered_consciousness", Operator: core.OpEquals, Value: true},
			},
			Actions: []core.Action{
				{Type: core.ActionTriggerAlert, Target: "SUSPECTED MENINGITIS — Urgent LP, IV antibiotics, and antivirals"},
				{Type: core.ActionRecommendInvestigation, Target: "lumbar_puncture"},
				{Type: core.ActionRecommendInvestigation, Target: "blood_cultures"},
				{Type: core.ActionRecommendInvestigation, Target: "ct_head"},
				{Type: core.ActionRecommendInvestigation, Target: "crp_procalcitonin"},
				{Type: core.ActionRequireField, Target: "rash_non_blanching"},
				{Type: core.ActionRequireField, Target: "kernig_sign"},
				{Type: core.ActionRequireField, Target: "brudzinski_sign"},
				{Type: core.ActionUpdateProbability, Target: "meningitis", Parameters: map[string]interface{}{"delta": 3.5}},
				{Type: core.ActionUpdateProbability, Target: "meningococcal_sepsis", Parameters: map[string]interface{}{"delta": 2.5}},
			},
			Evidence: "Meningitis is a medical emergency. IV antibiotics should not be delayed for LP or CT.",
			CreatedAt: now,
			UpdatedAt: now,
		},

		// NEUR-0007: Parkinsonism assessment
		{
			Code:        "NEUR-0007",
			Name:        "Parkinsonism and Movement Disorder Assessment",
			Description: "History and examination for suspected Parkinson's or movement disorder",
			Category:    core.CategoryHistory,
			Priority:    core.PriorityNormal,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "chief_complaint", Operator: core.OpContains, Value: "tremor", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "shaking", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "stiff", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "slow movement", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "balance"},
			},
			Actions: []core.Action{
				{Type: core.ActionRecommendQuestion, Target: "When did the tremor or movement problem start?"},
				{Type: core.ActionRecommendQuestion, Target: "Is the tremor at rest or with action?"},
				{Type: core.ActionRecommendQuestion, Target: "Which body parts are affected?"},
				{Type: core.ActionRecommendQuestion, Target: "Are movements becoming slower?"},
				{Type: core.ActionRecommendQuestion, Target: "Any stiffness in the arms, legs, or neck?"},
				{Type: core.ActionRecommendQuestion, Target: "Any problems with balance or falls?"},
				{Type: core.ActionRecommendQuestion, Target: "Any change in handwriting (micrographia)?"},
				{Type: core.ActionRecommendQuestion, Target: "Any change in voice (soft, hoarse)?"},
				{Type: core.ActionRecommendQuestion, Target: "Any difficulty with walking or shuffling gait?"},
				{Type: core.ActionRecommendQuestion, Target: "Any history of antipsychotic medication?"},
				{Type: core.ActionRequireField, Target: "tremor_characteristics"},
				{Type: core.ActionRequireField, Target: "rigidity_type"},
				{Type: core.ActionRequireField, Target: "gait_pattern"},
				{Type: core.ActionAddDifferential, Target: "parkinson_disease"},
				{Type: core.ActionAddDifferential, Target: "drug_induced_parkinsonism"},
				{Type: core.ActionAddDifferential, Target: "essential_tremor"},
				{Type: core.ActionAddDifferential, Target: "multiple_system_atrophy"},
				{Type: core.ActionAddDifferential, Target: "progressive_supranuclear_palsy"},
			},
			CreatedAt: now,
			UpdatedAt: now,
		},
	}
}
