package crl

import (
	"time"
	"github.com/amexan/backend/crl/core"
)

// EndocrinologyRules returns all endocrinology and diabetes rules
func EndocrinologyRules() []*core.Rule {
	now := time.Now()
	return []*core.Rule{
		// ENDO-0001: Diabetes history activation
		{
			Code:        "ENDO-0001",
			Name:        "Diabetes History Assessment",
			Description: "When known diabetes or diabetic symptoms, activate comprehensive diabetes assessment",
			Category:    core.CategoryHistory,
			Priority:    core.PriorityHigh,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "pmh.diabetes", Operator: core.OpEquals, Value: true, Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "diabetes", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "blood sugar", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "foot ulcer"},
			},
			Actions: []core.Action{
				{Type: core.ActionInsertSection, Target: "diabetes_history"},
				{Type: core.ActionInsertSection, Target: "glycemic_control"},
				{Type: core.ActionInsertSection, Target: "diabetes_complications"},
				{Type: core.ActionRecommendQuestion, Target: "When were you diagnosed with diabetes?"},
				{Type: core.ActionRecommendQuestion, Target: "Type 1 or Type 2?"},
				{Type: core.ActionRecommendQuestion, Target: "What medications are you taking for diabetes?"},
				{Type: core.ActionRecommendQuestion, Target: "What was your most recent HbA1c?"},
				{Type: core.ActionRecommendQuestion, Target: "Do you check your blood sugar at home? How often?"},
				{Type: core.ActionRecommendQuestion, Target: "Any hypoglycemic episodes?"},
				{Type: core.ActionRequireField, Target: "diabetes_type"},
				{Type: core.ActionRequireField, Target: "current_diabetes_medications"},
				{Type: core.ActionRequireField, Target: "most_recent_hba1c"},
				{Type: core.ActionRequireField, Target: "diabetes_complication_screening"},
				{Type: core.ActionActivatePathway, Target: "diabetes_management"},
			},
			CreatedAt: now,
			UpdatedAt: now,
		},

		// ENDO-0002: Diabetic foot ulcer assessment
		{
			Code:        "ENDO-0002",
			Name:        "Diabetic Foot Ulcer Comprehensive Assessment",
			Description: "Full diabetic foot assessment: neuropathic, ischemic, or mixed; Wagner classification",
			Category:    core.CategoryHistory,
			Priority:    core.PriorityHigh,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "chief_complaint", Operator: core.OpContains, Value: "foot ulcer", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "foot wound", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "diabetic foot"},
			},
			Actions: []core.Action{
				{Type: core.ActionRecommendQuestion, Target: "When did the foot ulcer start?"},
				{Type: core.ActionRecommendQuestion, Target: "How did it start? (trauma, pressure, spontaneous)"},
				{Type: core.ActionRecommendQuestion, Target: "Is there any pain in the foot?"},
				{Type: core.ActionRecommendQuestion, Target: "Any numbness or tingling in the feet?"},
				{Type: core.ActionRecommendQuestion, Target: "Any discoloration or temperature change?"},
				{Type: core.ActionRecommendQuestion, Target: "Any discharge, pus, or foul odor?"},
				{Type: core.ActionRecommendQuestion, Target: "Any fever or chills?"},
				{Type: core.ActionRecommendQuestion, Target: "Any previous foot ulcers or amputations?"},
				{Type: core.ActionRecommendQuestion, Target: "Do you have proper footwear?"},
				{Type: core.ActionRequireField, Target: "wagner_grade"},
				{Type: core.ActionRequireField, Target: "foot_ulcer_size_depth"},
				{Type: core.ActionRequireField, Target: "peripheral_pulses_assessment"},
				{Type: core.ActionRequireField, Target: "monofilament_test"},
				{Type: core.ActionRequireField, Target: "infection_signs"},
				{Type: core.ActionRecommendExam, Target: "foot_inspection"},
				{Type: core.ActionRecommendExam, Target: "peripheral_vascular_exam"},
				{Type: core.ActionRecommendExam, Target: "neurological_foot_exam"},
				{Type: core.ActionRecommendExam, Target: "monofilament_test"},
				{Type: core.ActionRecommendInvestigation, Target: "foot_xray"},
				{Type: core.ActionRecommendInvestigation, Target: "doppler_ultrasound_abi"},
				{Type: core.ActionRecommendInvestigation, Target: "wound_swab_mcs"},
				{Type: core.ActionAddDifferential, Target: "neuropathic_ulcer"},
				{Type: core.ActionAddDifferential, Target: "ischemic_ulcer"},
				{Type: core.ActionAddDifferential, Target: "mixed_neuroischemic_ulcer"},
				{Type: core.ActionAddDifferential, Target: "infected_diabetic_foot"},
				{Type: core.ActionAddDifferential, Target: "charcot_neuroarthropathy"},
				{Type: core.ActionActivatePathway, Target: "diabetic_foot_care"},
				{Type: core.ActionShowSection, Target: "multidisciplinary_foot_team"},
			},
			Evidence: "IWGDF Guidelines on prevention and management of diabetic foot disease; Wagner classification",
			CreatedAt: now,
			UpdatedAt: now,
		},

		// ENDO-0003: Diabetic ketoacidosis (DKA) red flag
		{
			Code:        "ENDO-0003",
			Name:        "Diabetic Ketoacidosis Red Flag",
			Description: "Hyperglycemia + ketosis + acidosis in known diabetes requires emergency management",
			Category:    core.CategoryDiagnosis,
			Priority:    core.PriorityCritical,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "known_diabetes", Operator: core.OpEquals, Value: true, Join: core.JoinAnd},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "vomit", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "abdominal pain", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "confusion", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "rapid breathing"},
			},
			Actions: []core.Action{
				{Type: core.ActionRecommendQuestion, Target: "Have you missed any insulin doses?"},
				{Type: core.ActionRecommendQuestion, Target: "Any infection or illness recently?"},
				{Type: core.ActionRecommendQuestion, Target: "Any nausea, vomiting, or abdominal pain?"},
				{Type: core.ActionRecommendQuestion, Target: "Any excessive thirst or frequent urination?"},
				{Type: core.ActionRecommendQuestion, Target: "Any rapid deep breathing (Kussmaul)?"},
				{Type: core.ActionRequireField, Target: "blood_glucose_stat"},
				{Type: core.ActionRequireField, Target: "capillary_ketones"},
				{Type: core.ActionRequireField, Target: "venous_blood_gas"},
				{Type: core.ActionRequireField, Target: "dka_assessment"},
				{Type: core.ActionRecommendInvestigation, Target: "stat_blood_glucose"},
				{Type: core.ActionRecommendInvestigation, Target: "capillary_ketones"},
				{Type: core.ActionRecommendInvestigation, Target: "venous_blood_gas_ph"},
				{Type: core.ActionRecommendInvestigation, Target: "septic_screen"},
				{Type: core.ActionTriggerAlert, Target: "SUSPECTED DKA — Fluid resuscitation, insulin infusion, monitor K+ and glucose hourly"},
				{Type: core.ActionAddDifferential, Target: "diabetic_ketoacidosis"},
				{Type: core.ActionAddDifferential, Target: "hyperosmolar_hyperglycemic_state"},
			},
			Evidence: "Joint British Diabetes Societies (JBDS) Guidelines for DKA management",
			CreatedAt: now,
			UpdatedAt: now,
		},

		// ENDO-0004: Thyroid disease assessment
		{
			Code:        "ENDO-0004",
			Name:        "Thyroid Disease History",
			Description: "Assessment for hyperthyroidism or hypothyroidism",
			Category:    core.CategoryHistory,
			Priority:    core.PriorityNormal,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "chief_complaint", Operator: core.OpContains, Value: "thyroid", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "goitre", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "neck swelling", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "weight loss", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "weight gain"},
			},
			Actions: []core.Action{
				{Type: core.ActionRecommendQuestion, Target: "Any swelling or lump in the neck?"},
				{Type: core.ActionRecommendQuestion, Target: "Any heat intolerance or excessive sweating?"},
				{Type: core.ActionRecommendQuestion, Target: "Any palpitations or racing heart?"},
				{Type: core.ActionRecommendQuestion, Target: "Any tremors or nervousness?"},
				{Type: core.ActionRecommendQuestion, Target: "Any fatigue or lethargy?"},
				{Type: core.ActionRecommendQuestion, Target: "Any change in weight?"},
				{Type: core.ActionRecommendQuestion, Target: "Any change in bowel habits?"},
				{Type: core.ActionRecommendQuestion, Target: "Any change in skin or hair?"},
				{Type: core.ActionRecommendQuestion, Target: "Any eye symptoms (bulging, irritation, double vision)?"},
				{Type: core.ActionRequireField, Target: "thyroid_function_tests"},
				{Type: core.ActionRequireField, Target: "thyroid_ultrasound"},
				{Type: core.ActionAddDifferential, Target: "hyperthyroidism_grave_disease"},
				{Type: core.ActionAddDifferential, Target: "hypothyroidism_hashimoto"},
				{Type: core.ActionAddDifferential, Target: "thyroid_nodule"},
				{Type: core.ActionAddDifferential, Target: "thyroid_cancer"},
				{Type: core.ActionAddDifferential, Target: "subacute_thyroiditis"},
			},
			CreatedAt: now,
			UpdatedAt: now,
		},
	}
}
