package crl

import (
	"time"
	"github.com/amexan/backend/crl/core"
)

// GastroenterologyRules returns all gastroenterology rules
func GastroenterologyRules() []*core.Rule {
	now := time.Now()
	return []*core.Rule{
		// GI-0001: Abdominal pain comprehensive assessment
		{
			Code:        "GI-0001",
			Name:        "Abdominal Pain Comprehensive History",
			Description: "Full abdominal pain history with surgical and medical differentials",
			Category:    core.CategoryHistory,
			Priority:    core.PriorityCritical,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "chief_complaint", Operator: core.OpContains, Value: "abdominal pain", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "stomach pain", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "belly pain"},
			},
			Actions: []core.Action{
				{Type: core.ActionRecommendQuestion, Target: "When did the pain start?"},
				{Type: core.ActionRecommendQuestion, Target: "Was onset sudden or gradual?"},
				{Type: core.ActionRecommendQuestion, Target: "Where exactly is the pain (point with one finger)?"},
				{Type: core.ActionRecommendQuestion, Target: "Has the pain moved from its original position?"},
				{Type: core.ActionRecommendQuestion, Target: "Describe the pain (sharp, colicky, burning, dull, cramping)?"},
				{Type: core.ActionRecommendQuestion, Target: "Rate severity 0-10"},
				{Type: core.ActionRecommendQuestion, Target: "What makes the pain better or worse?"},
				{Type: core.ActionRecommendQuestion, Target: "Any relationship to meals?"},
				{Type: core.ActionRecommendQuestion, Target: "Any nausea or vomiting?"},
				{Type: core.ActionRecommendQuestion, Target: "Any change in bowel habits (constipation, diarrhea)?"},
				{Type: core.ActionRecommendQuestion, Target: "Any blood in stool or vomit?"},
				{Type: core.ActionRecommendQuestion, Target: "Any fever or chills?"},
				{Type: core.ActionRecommendQuestion, Target: "Any urinary symptoms?"},
				{Type: core.ActionRecommendQuestion, Target: "For women: any gynecological symptoms? Pregnancy?"},
				{Type: core.ActionRequireField, Target: "pain_location_quadrant"},
				{Type: core.ActionRequireField, Target: "peritoneal_signs"},
				{Type: core.ActionRequireField, Target: "bowel_sounds"},
				{Type: core.ActionAddDifferential, Target: "acute_appendicitis"},
				{Type: core.ActionAddDifferential, Target: "cholecystitis"},
				{Type: core.ActionAddDifferential, Target: "pancreatitis"},
				{Type: core.ActionAddDifferential, Target: "perforated_viscus"},
				{Type: core.ActionAddDifferential, Target: "intestinal_obstruction"},
				{Type: core.ActionAddDifferential, Target: "gastroenteritis"},
				{Type: core.ActionAddDifferential, Target: "peptic_ulcer_disease"},
				{Type: core.ActionAddDifferential, Target: "renal_colic"},
				{Type: core.ActionAddDifferential, Target: "ectopic_pregnancy"},
				{Type: core.ActionAddDifferential, Target: "diverticulitis"},
			},
			Evidence: "Hutchison's Clinical Methods: Abdominal examination; NICE guidelines for abdominal pain",
			CreatedAt: now,
			UpdatedAt: now,
		},

		// GI-0002: Upper GI bleeding red flag
		{
			Code:        "GI-0002",
			Name:        "Upper GI Bleeding Red Flag Assessment",
			Description: "Haematemesis, melaena, or haematochezia with hemodynamic instability = emergency endoscopy",
			Category:    core.CategoryDiagnosis,
			Priority:    core.PriorityCritical,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "haematemesis", Operator: core.OpEquals, Value: true, Join: core.JoinOr},
				{Field: "melaena", Operator: core.OpEquals, Value: true, Join: core.JoinOr},
				{Field: "haematochezia", Operator: core.OpEquals, Value: true},
			},
			Actions: []core.Action{
				{Type: core.ActionTriggerAlert, Target: "UPPER GI BLEED — Urgent OGD, resuscitation, cross-match, PPI"},
				{Type: core.ActionRequireField, Target: "hemodynamic_status"},
				{Type: core.ActionRequireField, Target: "blatchford_score"},
				{Type: core.ActionRequireField, Target: "rockall_score"},
				{Type: core.ActionRequireField, Target: "gcs_bleeding_risk"},
				{Type: core.ActionRecommendInvestigation, Target: "emergency_ogd"},
				{Type: core.ActionRecommendInvestigation, Target: "fbc_coagulation"},
				{Type: core.ActionRecommendInvestigation, Target: "cross_match"},
				{Type: core.ActionRecommendQuestion, Target: "Are you vomiting blood? How much?"},
				{Type: core.ActionRecommendQuestion, Target: "Any black/tarry stools?"},
				{Type: core.ActionRecommendQuestion, Target: "Any history of ulcers or NSAID use?"},
				{Type: core.ActionRecommendQuestion, Target: "Any liver disease or alcohol use?"},
				{Type: core.ActionRecommendQuestion, Target: "Any dizziness, lightheadedness, or fainting?"},
				{Type: core.ActionAddDifferential, Target: "peptic_ulcer_bleeding"},
				{Type: core.ActionAddDifferential, Target: "oesophageal_varices"},
				{Type: core.ActionAddDifferential, Target: "mallory_weiss_tear"},
				{Type: core.ActionAddDifferential, Target: "gastritis_erosive"},
				{Type: core.ActionUpdateProbability, Target: "upper_gi_bleed", Parameters: map[string]interface{}{"delta": 3.0}},
			},
			Evidence: "NICE Guideline NG141: Acute upper GI bleeding; Glasgow-Blatchford score for pre-endoscopy risk",
			CreatedAt: now,
			UpdatedAt: now,
		},

		// GI-0003: Vomiting and diarrhea assessment
		{
			Code:        "GI-0003",
			Name:        "Vomiting and Diarrhea Assessment",
			Description: "Structured assessment for gastroenteritis, food poisoning, and dehydration status",
			Category:    core.CategoryHistory,
			Priority:    core.PriorityNormal,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "chief_complaint", Operator: core.OpContains, Value: "vomit", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "diarrhoea", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "nausea"},
			},
			Actions: []core.Action{
				{Type: core.ActionRecommendQuestion, Target: "How many episodes of vomiting/diarrhea?"},
				{Type: core.ActionRecommendQuestion, Target: "What color/character of vomit? (food, bile, blood, coffee ground)"},
				{Type: core.ActionRecommendQuestion, Target: "What character of stool? (watery, bloody, mucous)"},
				{Type: core.ActionRecommendQuestion, Target: "Any fever or chills?"},
				{Type: core.ActionRecommendQuestion, Target: "Any abdominal pain or cramping?"},
				{Type: core.ActionRecommendQuestion, Target: "Any recent travel or food exposure?"},
				{Type: core.ActionRecommendQuestion, Target: "Any similar illness in family or contacts?"},
				{Type: core.ActionRequireField, Target: "dehydration_assessment"},
				{Type: core.ActionRequireField, Target: "oral_intake_tolerance"},
				{Type: core.ActionRequireField, Target: "urine_output"},
				{Type: core.ActionAddDifferential, Target: "acute_gastroenteritis"},
				{Type: core.ActionAddDifferential, Target: "food_poisoning"},
				{Type: core.ActionAddDifferential, Target: "appendicitis"},
				{Type: core.ActionAddDifferential, Target: "pancreatitis"},
			},
			CreatedAt: now,
			UpdatedAt: now,
		},

		// GI-0004: Jaundice assessment
		{
			Code:        "GI-0004",
			Name:        "Jaundice Assessment",
			Description: "Jaundice history with pre-hepatic, hepatic, and post-hepatic differentiation",
			Category:    core.CategoryHistory,
			Priority:    core.PriorityNormal,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "chief_complaint", Operator: core.OpContains, Value: "jaundice", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "yellow", Join: core.JoinOr},
				{Field: "observation.sclera_icterus", Operator: core.OpEquals, Value: true},
			},
			Actions: []core.Action{
				{Type: core.ActionRecommendQuestion, Target: "When did the yellow discoloration start?"},
				{Type: core.ActionRecommendQuestion, Target: "Is it getting worse, better, or the same?"},
				{Type: core.ActionRecommendQuestion, Target: "Is there any itching (pruritus)?"},
				{Type: core.ActionRecommendQuestion, Target: "Any abdominal pain? Where?"},
				{Type: core.ActionRecommendQuestion, Target: "Any fever or chills?"},
				{Type: core.ActionRecommendQuestion, Target: "Have you noticed dark urine or pale stool?"},
				{Type: core.ActionRecommendQuestion, Target: "Any history of liver disease or hepatitis?"},
				{Type: core.ActionRecommendQuestion, Target: "Any alcohol use? How much?"},
				{Type: core.ActionRecommendQuestion, Target: "Any new medications or herbal remedies?"},
				{Type: core.ActionRecommendQuestion, Target: "Any recent blood transfusion or tattoos?"},
				{Type: core.ActionRecommendQuestion, Target: "Any weight loss?"},
				{Type: core.ActionRequireField, Target: "liver_function_tests"},
				{Type: core.ActionRequireField, Target: "bilirubin_fractionation"},
				{Type: core.ActionRequireField, Target: "abdominal_ultrasound"},
				{Type: core.ActionAddDifferential, Target: "pre_hepatic_jaundice_haemolysis"},
				{Type: core.ActionAddDifferential, Target: "hepatic_jaundice_hepatitis"},
				{Type: core.ActionAddDifferential, Target: "post_hepatic_jaundice_obstruction"},
				{Type: core.ActionAddDifferential, Target: "alcoholic_liver_disease"},
				{Type: core.ActionAddDifferential, Target: "pancreatic_cancer"},
				{Type: core.ActionAddDifferential, Target: "drug_induced_liver_injury"},
			},
			CreatedAt: now,
			UpdatedAt: now,
		},

		// GI-0005: Abdominal examination modules
		{
			Code:        "GI-0005",
			Name:        "Abdominal Examination Modules",
			Description: "Activates abdominal exam techniques: inspection, palpation, percussion, auscultation",
			Category:    core.CategoryExamination,
			Priority:    core.PriorityHigh,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "chief_complaint", Operator: core.OpContains, Value: "abdominal", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "stomach", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "belly", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "vomit", Join: core.JoinOr},
				{Field: "chief_complaint", Operator: core.OpContains, Value: "jaundice"},
			},
			Actions: []core.Action{
				{Type: core.ActionRecommendExam, Target: "abdominal_inspection"},
				{Type: core.ActionRecommendExam, Target: "abdominal_auscultation"},
				{Type: core.ActionRecommendExam, Target: "abdominal_palpation_superficial"},
				{Type: core.ActionRecommendExam, Target: "abdominal_palpation_deep"},
				{Type: core.ActionRecommendExam, Target: "liver_palpation_percussion"},
				{Type: core.ActionRecommendExam, Target: "spleen_palpation"},
				{Type: core.ActionRecommendExam, Target: "renal_palpation"},
				{Type: core.ActionRecommendExam, Target: "shifting_dullness_ascites"},
				{Type: core.ActionRecommendExam, Target: "hernial_orifices"},
				{Type: core.ActionRecommendExam, Target: "rectal_examination"},
				{Type: core.ActionRecommendExam, Target: "inguinal_lymph_nodes"},
			},
			CreatedAt: now,
			UpdatedAt: now,
		},

		// GI-0006: Peritonitis red flag
		{
			Code:        "GI-0006",
			Name:        "Peritonitis / Acute Abdomen Red Flag",
			Description: "Board-like rigidity, rebound tenderness, absent bowel sounds = surgical emergency",
			Category:    core.CategoryDiagnosis,
			Priority:    core.PriorityCritical,
			Status:      core.RuleActive,
			Version:     "1.0.0",
			Conditions: []core.Condition{
				{Field: "abdominal_rigidity", Operator: core.OpEquals, Value: true, Join: core.JoinAnd},
				{Field: "rebound_tenderness", Operator: core.OpEquals, Value: true, Join: core.JoinAnd},
				{Field: "absent_bowel_sounds", Operator: core.OpEquals, Value: true},
			},
			Actions: []core.Action{
				{Type: core.ActionTriggerAlert, Target: "ACUTE ABDOMEN / PERITONITIS — Emergency surgical review, NBM, IV fluids, IV antibiotics"},
				{Type: core.ActionRequireField, Target: "last_meal"},
				{Type: core.ActionRequireField, Target: "pregnancy_test_if_applicable"},
				{Type: core.ActionRecommendInvestigation, Target: "erect_chest_xray_free_air"},
				{Type: core.ActionRecommendInvestigation, Target: "abdominal_xray"},
				{Type: core.ActionRecommendInvestigation, Target: "ct_abdomen_pelvis"},
				{Type: core.ActionRecommendInvestigation, Target: "fbc_ucr_lft_amylase"},
				{Type: core.ActionRecommendReferral, Target: "general_surgery_emergency"},
				{Type: core.ActionUpdateProbability, Target: "perforated_viscus", Parameters: map[string]interface{}{"delta": 4.0}},
				{Type: core.ActionUpdateProbability, Target: "peritonitis", Parameters: map[string]interface{}{"delta": 3.5}},
			},
			Evidence: "Peritonitis requires urgent surgical exploration. Erect CXR can detect free air under diaphragm.",
			CreatedAt: now,
			UpdatedAt: now,
		},
	}
}
