export type {
  EncounterPhase,
  RegistrationData,
  PresentingComplaintData,
  HPIEntry,
  ExamEntry,
  BedsideScoreEntry,
  DDXEntry,
  InvestigationEntry,
  ImagingEntry,
  TreatmentEntry,
  OperativeNoteData,
  WardRoundEntry,
  ComplicationEntry,
  DispositionData,
  EncounterState,
  SubcollectionName,
} from '@/src/types/encounter';
