const fs = require('fs');
const p = 'C:\\Users\\Administrator\\Desktop\\client\\lib\\amexan\\departments\\neuro.ts';
const l = [];

const add = s => l.push(s);
const addl = a => a.forEach(x => l.push(x));

// HEADER
addl([
  '// ═══════════════════════════════════════════════════════════════════════════════',
  '// lib/amexan/departments/neuro.ts',
  '// AMEXAN Neurology Disease Intelligence Library',
  '// 3 subspecialties — each disease is a complete DiseaseIntelligence JSON',
  '// ═══════════════════════════════════════════════════════════════════════════════',
  '',
  "import type { DiseaseIntelligence } from '../core';",
  '',
  'export const NEURO_DISEASES: DiseaseIntelligence[] = [',
  '  // ─── Stroke Unit: Acute Ischaemic Stroke ───────────────────────────────────',
  '  {',
  "    id: 'acute-ischaemic-stroke',",
  "    name: 'Acute Ischaemic Stroke',",
  "    specialtyId: 'NEURO', subspecialtyId: 'stroke', icd10: 'I63.9',",
  '    epidemiology: {',
  "      incidence: '13.7 million new strokes/year globally; ischaemic accounts for 62-87% of all strokes; age-standardised incidence in Sub-Saharan Africa: 316 per 100,000',",
  "      prevalence: '80 million stroke survivors worldwide; leading cause of adult disability in Kenya; prevalence ~1-2% in adults >45 years',",
  "      ageDistribution: 'Mean age 65-70 years in high-resource settings; younger in Africa (mean 55-60 years); increasing with age; 25% occur in people <65 years',",
  "      genderPredilection: 'Male > Female (1.3:1) overall; lifetime risk higher in women due to longer life expectancy',",
  "      geographicDistribution: 'Global; highest in East Asia, Eastern Europe, and Sub-Saharan Africa; in Kenya: increasing burden due to hypertension and lifestyle changes, urban > rural',",
  "      seasonality: 'Higher incidence in winter months (cold, infections); no significant seasonal variation in tropical regions'",
  '    },',
  '    symptomWeights: [',
  "      { symptom: 'sudden unilateral limb weakness (hemiparesis)', weight: 10, prevalence: 85, category: 'red_flag' },",
  "      { symptom: 'sudden facial droop (unilateral)', weight: 9, prevalence: 75, category: 'red_flag' },",
  "      { symptom: 'sudden speech difficulty (aphasia/dysarthria)', weight: 9, prevalence: 65, category: 'red_flag' },",
  "      { symptom: 'sudden unilateral sensory loss', weight: 7, prevalence: 55, category: 'major' },",
  "      { symptom: 'sudden visual disturbance (monocular/binocular blindness, hemianopia)', weight: 8, prevalence: 20, category: 'red_flag' },",
  "      { symptom: 'sudden ataxia / gait imbalance', weight: 7, prevalence: 25, category: 'major' },",
  "      { symptom: 'sudden severe headache (especially with vomiting)', weight: 5, prevalence: 25, category: 'major' },",
  "      { symptom: 'vertigo / dizziness (with brainstem signs)', weight: 6, prevalence: 15, category: 'major' },",
  "      { symptom: 'sudden confusion / decreased consciousness', weight: 8, prevalence: 20, category: 'red_flag' },",
  "      { symptom: 'dysphagia (difficulty swallowing)', weight: 6, prevalence: 40, category: 'major' },",
  "      { symptom: 'neglect / inattention to one side', weight: 7, prevalence: 20, category: 'major' },",
  "      { symptom: 'seizure at onset', weight: 4, prevalence: 5, category: 'minor' },",
  "      { symptom: 'nausea / vomiting (posterior circulation)', weight: 5, prevalence: 15, category: 'minor' },",
  '    ],',
  '    riskFactors: [',
  "      { factor: 'Hypertension (uncontrolled)', weight: 4.0, prevalence: 45 },",
  "      { factor: 'Atrial Fibrillation', weight: 5.0, prevalence: 10 },",
  "      { factor: 'Diabetes Mellitus', weight: 3.0, prevalence: 20 },",
  "      { factor: 'Smoking', weight: 3.5, prevalence: 25 },",
  "      { factor: 'Dyslipidaemia', weight: 2.5, prevalence: 30 },",
  "      { factor: 'Obesity (BMI >30)', weight: 2.0, prevalence: 25 },",
  "      { factor: 'Physical inactivity', weight: 2.0, prevalence: 35 },",
  "      { factor: 'Age >65 years', weight: 3.0, prevalence: 30 },",
  "      { factor: 'Prior stroke or TIA', weight: 4.5, prevalence: 15 },",
  "      { factor: 'Cardiac disease (valvular, HF, PFO, endocarditis)', weight: 3.5, prevalence: 12 },",
  "      { factor: 'Carotid artery stenosis (>70%)', weight: 4.0, prevalence: 5 },",
  "      { factor: 'Oral contraceptive pill / Hormonal therapy', weight: 2.5, prevalence: 8 },",
  "      { factor: 'Sickle cell disease (in African populations)', weight: 3.0, prevalence: 5 },",
  "      { factor: 'HIV infection', weight: 2.5, prevalence: 10 },",
  "      { factor: 'Heavy alcohol consumption', weight: 2.0, prevalence: 15 },",
  '    ],',
  '    differentials: [',
  "      { disease: 'Acute Ischaemic Stroke', likelihood: 50, distinguishingFeatures: ['Sudden onset focal deficit', 'FAST positive', 'CT: no haemorrhage', 'Deficits match vascular territory', 'Onset usually minutes to hours'] },",
  "      { disease: 'Intracerebral Haemorrhage (Haemorrhagic Stroke)', likelihood: 15, distinguishingFeatures: ['More severe headache', 'Vomiting common', 'Rapid progression', 'CT: hyperdensity (blood)', 'Often hypertensive'] },",
  "      { disease: 'Subarachnoid Haemorrhage', likelihood: 5, distinguishingFeatures: ['Thunderclap headache', 'Neck stiffness', 'Photophobia', 'CT: blood in subarachnoid space', 'Usually aneurysmal'] },",
  "      { disease: 'Migraine with Aura (Hemiplegic/Complicated)', likelihood: 5, distinguishingFeatures: ['History of migraine', 'Positive aura (visual, sensory spreading)', 'Gradual progression of symptoms', 'Headache preceding/with deficit', 'Reversible <24-72h', 'Young patients'] },",
  "      { disease: 'Seizure with Post-ictal (Todd Paresis)', likelihood: 4, distinguishingFeatures: ['History of seizure activity', 'Post-ictal weakness (resolves 24-48h)', 'Tongue biting', 'Incontinence', 'Confusion post-event'] },",
  "      { disease: 'Hypoglycaemia', likelihood: 4, distinguishingFeatures: ['History of diabetes', 'Consciousness more affected than focal signs', 'BGL <3.0 mmol/L', 'Rapid resolution with dextrose', 'May mimic any stroke'] },",
  "      { disease: 'Functional Neurological Disorder (Conversion)', likelihood: 3, distinguishingFeatures: ['Inconsistent signs', 'Variability with distraction', 'La belle indifference', 'Non-anatomical pattern', 'Previous functional symptoms', 'No vascular risk factors'] },",
  "      { disease: 'Brain Tumour (with acute bleed or seizure)', likelihood: 3, distinguishingFeatures: ['Gradual onset (unless haemorrhage)', 'Headache worse in morning', 'Seizure', 'Papilloedema', 'CT/MRI shows mass'] },",
  "      { disease: 'Cerebral Venous Sinus Thrombosis', likelihood: 2, distinguishingFeatures: ['Headache prominent', 'Seizures common', 'Often postpartum/dehydrated', 'CT venogram: empty delta sign', 'Venous infarct pattern'] },",
  "      { disease: 'Encephalitis/Meningitis', likelihood: 2, distinguishingFeatures: ['Fever', 'Altered consciousness', 'Headache', 'Meningism', 'CSF changes', 'Often bilateral or diffuse'] },",
  '    ],',
]);

fs.writeFileSync(p, l.join('\n') + '\n', 'utf8');
console.log('Header + D1 part A written. Size:', fs.statSync(p).size);
