const fs = require('fs');
const p = 'C:\\Users\\Administrator\\Desktop\\client\\lib\\amexan\\departments\\neuro.ts';
const l = [];
const addl = a => a.forEach(x => l.push(x));

// D3: imaging, severityCriteria, diagnosticCriteria
addl([
  '    imaging: [',
  "      { modality: 'MRI Brain (Epilepsy Protocol 3T)', indication: 'All patients with new-onset epilepsy (except genetic generalised epilepsy with typical EEG). Essential for surgical evaluation in drug-resistant epilepsy. High-resolution thin-slice T1 (MPRAGE), T2, FLAIR, GRE, DWI sequences.', findings: 'Hippocampal sclerosis: T2/FLAIR hyperintensity + atrophy of hippocampus (most common surgical lesion in temporal lobe epilepsy). Focal cortical dysplasia (FCD): transmantle sign, blurring of grey-white junction, cortical thickening/thinning. Tumour: low-grade glioma (DNET, ganglioglioma, oligodendroglioma), meningioma. Cavernoma: popcorn lesion with haemosiderin rim (GRE blooming). Encephalomalacia/glosis: post-traumatic, post-infectious, post-stroke. Neurocysticercosis: cyst with scolex, calcified granulomas (especially at grey-white junction). Mesial temporal sclerosis (MTS): atrophy + T2 hyperintensity of hippocampus. Malformations of cortical development: polymicrogyria, lissencephaly, heterotopia, schizencephaly.', sensitivity: 85, specificity: 95, preparation: 'Screen for MRI contraindications' },",
  "      { modality: 'CT Brain', indication: 'Emergency imaging for first seizure (rule out acute lesion). Used when MRI unavailable or contraindicated. NCC screening: calcified granulomas (tropical settings).', findings: 'Acute haemorrhage, mass lesion, oedema, midline shift, hydrocephalus. Calcified neurocysticercosis granulomas (punctate calcifications at grey-white junction). Old infarcts, encephalomalacia.', sensitivity: 60, specificity: 95, preparation: 'None (emergency)' },",
  "      { modality: 'FDG-PET (Interictal)', indication: 'Localise epileptogenic zone in MRI-negative epilepsy. Shows hypometabolism in epileptic focus interictally.', findings: 'Temporal lobe: regional hypometabolism (temporal pole, hippocampus) ipsilateral to seizure onset. Extratemporal: focal cortical hypometabolism. Sensitivity superior to MRI for localising FCD.', sensitivity: 85, specificity: 80, preparation: 'Patient must be seizure-free for 24h (interictal) and fasting for 6h' },",
  "      { modality: 'Magnetoencephalography (MEG)', indication: 'Localise epileptic source (dipole modelling) in MRI-negative epilepsy or for pre-surgical planning (complementary to EEG).', findings: 'Cluster of equivalent current dipoles (ECD) colocalising to epileptogenic zone. Helps differentiate mesial vs neocortical temporal onset.', sensitivity: 80, specificity: 85, preparation: 'Metal-free' },",
  '    ],',
  '    severityCriteria: [',
  "      { criterion: 'Seizure Frequency (per month)', mild: 'Seizure-free (no seizures in >=12 months)', moderate: '<1 per month (infrequent seizures)', severe: '1-4 per month (frequent seizures)', critical: '>4 per month or clusters (high-frequency)' },",
  "      { criterion: 'ILAE Classification of Drug Resistance', mild: 'Seizure-free on first/first-line AED', moderate: 'Seizure-free on second-line or combination therapy', severe: 'Failed >=2 appropriate AED trials (drug-resistant epilepsy)', critical: 'Failed >=4 AED trials + ongoing seizures (refractory)' },",
  "      { criterion: 'Seizure Type Severity (impact on safety)', mild: 'Simple focal (no impairment of consciousness)', moderate: 'Focal with impaired awareness (not dangerous)', severe: 'GTCS (generalised tonic-clonic) - risk of injury, aspiration, SUDEP', critical: 'Status epilepticus (>5 min GTCS or >=2 seizures without recovery)' },",
  "      { criterion: 'SUDEP Risk (Sudden Unexpected Death in Epilepsy)', mild: 'No risk factors (seizure-free, no GTCS, supervised)', moderate: 'Occasional GTCS, non-adherence', severe: 'Frequent GTCS, nocturnal seizures, alcohol use, living alone', critical: 'Frequent GTCS nocturnally, poor adherence, drug-resistant, living alone, no nocturnal monitoring' },",
  "      { criterion: 'Psychosocial Impact / Quality of Life', mild: 'Normal life, driving allowed, employed', moderate: 'Driving restricted, some work limitations', severe: 'Unable to work, significant social restrictions', critical: 'Housebound, dependent for ADLs, severe depression/social isolation' },",
  '    ],',
  '    diagnosticCriteria: [',
  "      { name: 'ILAE 2017 Clinical Definition of Epilepsy', type: 'required', description: 'Epilepsy is defined as any of: 1) >=2 unprovoked seizures occurring >24h apart; 2) One unprovoked seizure and a probability of further seizures >=60% over the next 10 years; 3) Diagnosis of an epilepsy syndrome.' },",
  "      { name: 'ILAE 2017 Seizure Classification', type: 'required', description: 'Focal onset: aware or impaired awareness; motor onset (automatisms, atonic, clonic, epileptic spasms, hyperkinetic, myoclonic, tonic) or non-motor onset (autonomic, behaviour arrest, cognitive, emotional, sensory). Generalised onset: motor (tonic-clonic, clonic, tonic, myoclonic, myoclonic-tonic-clonic, myoclonic-atonic, atonic, epileptic spasms) or non-motor (absence - typical, atypical, myoclonic, eyelid myoclonia). Unknown onset: motor (tonic-clonic, epileptic spasms) or non-motor (behaviour arrest).' },",
  "      { name: 'ILAE 2017 Epilepsy Syndrome Classification', type: 'minor', description: 'Neonatal/infantile: Self-limited neonatal (BFNE, BFIS), Infantile epileptic spasms syndrome (West), Dravet syndrome, Self-limited infantile epilepsy (SeLIE). Childhood: Self-limited focal epilepsies (Rolandic/SeLECTS, Panayiotopoulos, SeLIMS/CSWS), Childhood absence epilepsy (CAE), Juvenile absence epilepsy (JAE), Juvenile myoclonic epilepsy (JME), Genetic generalised epilepsy (GGE). Adolescent/adult: JME, JAE, GGE, Temporal lobe epilepsy (mesial TLE), Sleep-related hypermotor epilepsy (SHE).' },",
  '    ],',
]);

fs.appendFileSync(p, l.join('\n') + '\n', 'utf8');
console.log('D3 part B written. Size:', fs.statSync(p).size);
