const fs = require('fs');
const p = 'C:\\Users\\Administrator\\Desktop\\client\\lib\\amexan\\departments\\neuro.ts';
const l = [];
const addl = a => a.forEach(x => l.push(x));

// D3: treatmentGuidelines (first half - firstLine, stepProtocol steps 1-3)
addl([
  '    treatmentGuidelines: [',
  '      {',
  "        name: 'WHO/ILAE/NICE Epilepsy Treatment Guidelines 2024 (MOH Kenya Adapted)', source: 'NICE Guideline NG217, WHO Epilepsy Guidelines, ILAE Treatment Guidelines, MOH Kenya Essential Medicines List', year: 2024,",
  '        firstLine: [',
  "          { drug: 'Carbamazepine (Focal seizures first-line)', dose: 'Start 100-200 mg nightly, titrate by 200 mg every 1-2 weeks to maintenance 400-600 mg BD (max 2 g/day)', route: 'PO', frequency: 'Twice daily (BD)', duration: 'Lifelong (unless seizure-free 2-5 years and weaning considered)', maxDose: '2 g/day', evidenceLevel: 'A', pregnancyCategory: 'D', renalAdjustment: 'None', hepaticAdjustment: 'Reduce dose in hepatic impairment' },",
  "          { drug: 'Sodium Valproate (Generalised seizures first-line)', dose: 'Start 200-500 mg BD, titrate by 200-500 mg weekly to maintenance 500 mg-1.5 g BD (max 2.5 g/day)', route: 'PO', frequency: 'Twice daily (BD)', duration: 'Lifelong (unless weaning considered)', maxDose: '2.5 g/day', evidenceLevel: 'A', pregnancyCategory: 'D (FOETOTOXIC - avoid in women of childbearing potential)', renalAdjustment: 'Reduce dose if CrCl <30', hepaticAdjustment: 'Avoid in liver disease' },",
  "          { drug: 'Levetiracetam (Broad-spectrum, focal + generalised)', dose: 'Start 250 mg BD, increase by 250-500 mg per week to maintenance 500 mg-1.5 g BD (max 3 g/day)', route: 'PO/IV', frequency: 'Twice daily (BD)', duration: 'Lifelong', maxDose: '3 g/day', evidenceLevel: 'A', pregnancyCategory: 'C', renalAdjustment: 'Reduce dose if CrCl <50' },",
  "          { drug: 'Lamotrigine (Broad-spectrum, good tolerability)', dose: 'Start 25 mg nightly x 2 weeks, then 50 mg nightly x 2 weeks, then 50 mg BD, titrate by 50-100 mg q2 weeks to maintenance 100-200 mg BD (max 500 mg/day). If on valproate: start 25 mg alternate days x 2 weeks.', route: 'PO', frequency: 'Twice daily (BD)', duration: 'Lifelong', maxDose: '500 mg/day', evidenceLevel: 'A', pregnancyCategory: 'C' },",
  "          { drug: 'Phenytoin (Standard choice in resource-limited settings)', dose: 'Start 300 mg daily (or 5 mg/kg/day) in divided doses; titrate based on levels (target 10-20 mcg/mL); loading 15-20 mg/kg', route: 'PO/IV', frequency: 'Once daily (sustained release) or BD', duration: 'Lifelong', maxDose: '600 mg/day', evidenceLevel: 'A', pregnancyCategory: 'D' },",
  '        ],',
  '        stepProtocol: [',
  "          { step: 1, therapy: 'Diagnosis confirmation and seizure classification', details: 'Detailed history (eyewitness account essential). Classify seizure type: focal vs generalised vs unknown onset. Identify epilepsy syndrome if possible. Perform routine EEG (awake + sleep-deprived if needed). MRI brain (epilepsy protocol) to exclude structural cause. ECG to exclude arrhythmia. Baseline bloods (CBC, LFT, U&E, Cr, Ca, Mg). Tailor AED to seizure type: Focal onset: CBZ, LTG, LEV (first-line). Generalised onset: VPA (caution in women of childbearing age), LTG, LEV, clobazam. Unclassified: LEV or LTG (broad-spectrum). Avoid CBZ, PHT, oxcarbazepine, gabapentin, pregabalin in genetic generalised epilepsy.', duration: 'Diagnostic work-up 1-4 weeks', monitoring: ['Serum AED levels at baseline (if phenytoin/carbamazepine/valproate)', 'CBC, LFT, Cr at baseline', 'Drug-drug interaction check (ART, OCP, statins, warfarin)', 'Pregnancy test (women of childbearing age)'], alternatives: [] },",
  "          { step: 2, therapy: 'Initiation of first AED (monotherapy)', details: 'Start at low dose, titrate slowly to minimse side effects. Target lowest effective dose. Allow adequate trial: minimum 4-8 weeks at therapeutic dose. Titration schedule: Carbamazepine: 100 mg nocte -> increase by 200 mg q1-2 weeks to 200-600 mg BD. Valproate: 200 mg BD -> increase by 200-500 mg q1 week to 500 mg-1.5 g BD (avoid in WOCBP). Levetiracetam: 250 mg BD -> increase by 500 mg q1 week to 500 mg-1.5 g BD (max 3 g). Lamotrigine: very slow titration to avoid rash. Phenytoin: 300 mg/d. Phenobarbital: 60-90 mg nocte (first-line in resource-limited settings, MOH Kenya). Counsel: regular adherence (pill box, phone alarms, caregiver involvement). Side effects: dizziness, sedation, ataxia, rash, nystagmus. Seizure diary.', duration: 'Titration 4-12 weeks; trial period 4-12 weeks at therapeutic dose', monitoring: ['Seizure frequency and severity (seizure diary)', 'Side effects (dizziness, sedation, rash, cognitive slowing, weight gain)', 'AED levels (if PHT, CBZ, VPA: after steady state, 2-4 weeks post-baseline)', 'LFT, CBC at 4-6 weeks', 'Mood monitoring', 'Driving counselling'], alternatives: [] },",
  "          { step: 3, therapy: 'If first AED fails — second monotherapy or combination', details: 'If seizure-free on first AED but side effects: try alternative first-line AED (switch slowly, cross-titration). If no response to first AED despite adequate dose and compliance: switch to alternative first-line agent with different mechanism. If partial response but not seizure-free: consider combination therapy (add second AED with complementary mechanism). Rational polytherapy: Focal: CBZ + LTG, CBZ + LEV, LTG + LEV. Generalised: VPA + LTG, VPA + clobazam, LTG + LEV. Broad-spectrum combos: LEV + LTG, VPA + LEV, VPA + LTG. Avoid: CBZ + phenytoin (enzyme inducers), CBZ + oxcarbazepine (same mechanism).', duration: 'Switch 4-8 weeks titration; combination assessment 8-12 weeks', monitoring: ['Seizure diary continued', 'AED levels if on combination with potential interactions', 'Side effects profile (especially cognitive, sedation)', 'Drug-drug interactions (especially enzyme inducers + OCP, warfarin, ARVs)'], alternatives: ['Clobazam 10-20 mg nocte (add-on for short-term or rescue therapy)', 'Zonisamide 50-400 mg daily (add-on for refractory focal)'] },",
  "          { step: 4, therapy: 'Drug-resistant epilepsy — epilepsy surgery evaluation', details: 'ILAE definition: failure of >=2 appropriate AEDs to achieve sustained seizure freedom. Refer to epilepsy surgery centre. Pre-surgical evaluation: Phase I: video-EEG monitoring, high-resolution 3T MRI epilepsy protocol, neuropsychology, fMRI (language/memory lateralisation if temporal). Phase II: intracranial EEG (SEEG/subdural grids) if MRI-negative or extratemporal. Surgical options: Temporal lobe epilepsy (TLE): anterior temporal lobectomy (ATL) or selective amygdalohippocampectomy (SAH) — seizure-free rate 70-80% with MTS. Extratemporal: lesionectomy if structural lesion — 60-80% seizure-free. Hemispherectomy: for hemimegalencephaly, Sturge-Weber, Rasmusssen encephalitis — 70-80% seizure-free. Vagus Nerve Stimulation (VNS): palliative for non-surgical candidates — 50% responder rate. Deep Brain Stimulation (DBS): anterior nucleus of thalamus (ANT-DBS) for refractory focal. Ketogenic Diet: especially for children with Dravet, GLUT1 deficiency, Lennox-Gastaut Syndrome.', duration: 'Surgical evaluation: 3-12 months; post-surgical follow-up 2-5 years', monitoring: ['Video-EEG monitoring duration variable (days to weeks)', 'Neuropsychology baseline and post-operatively', 'Seizure diary (Engel/ILAE classification of outcomes)', 'MRI post-operatively (if surgery)', 'AED continuation/de-escalation (usually continued for 1-2 years post-surgery)'], alternatives: [] },",
  "          { step: 5, therapy: 'Long-term management, transition, and AED withdrawal', details: 'Seizure-free for >=2-5 years: consider AED withdrawal (shared decision-making). Withdrawal protocol: reduce slowly over 3-6 months (one drug at a time, reduce by 25% every 4-8 weeks). Warn: withdrawal seizure risk is 20-30%; if recurrence backfires. Long-term monitoring: annual review (seizure diary, side effects, drug levels if on PHT/CBZ/VPA, adherence check, mood, bone health). Drug interactions with ART, OCP, warfarin. Transition planning (paediatric to adult epilepsy services). SUDEP counselling: adherence reduces risk; nocturnal monitoring. Status epilepticus emergency/rescue plan for all patients: buccal midazolam 5-10 mg or rectal diazepam. Driving restrictions per NTSA Kenya: 6-12 months seizure-free before driving. Employment: reasonable adjustments under Kenyan disability law.', duration: 'Lifelong AED (most patients); rehabilitation post-surgery 3-12 months', monitoring: ['Annual review in epilepsy clinic', 'Seizure diary', 'AED levels (if PHT/CBZ/VPA) annually', 'Bone health: Ca, Vit D, DEXA (if VPA/PHT/CBZ long-term)', 'Mood screening (PHQ-9, GAD-7) annually', 'CBC, LFT, Cr annually', 'Folic acid 5 mg daily for women of childbearing potential on AEDs'], alternatives: ['Referral to epilepsy nurse specialist', 'Community health worker support for adherence in rural settings'] },",
  '        ],',
  '        secondLine: [',
  "          { drug: 'Clobazam (Add-on/rescue)', dose: 'Add-on: 10-20 mg nocte (start 5 mg, titrate). Rescue/cluster: 20-30 mg single dose PRN', route: 'PO', frequency: 'Once daily (or PRN for rescue)', duration: 'Add-on limited (tolerance develops). Rescue: as needed', maxDose: '40 mg/day', evidenceLevel: 'B', pregnancyCategory: 'C' },",
  "          { drug: 'Buccal Midazolam (Status Epilepticus / Cluster Seizures Rescue)', dose: 'Buccal 5-10 mg (0.2-0.3 mg/kg in children). Max 10 mg.', route: 'Buccal', frequency: 'Single dose (may repeat once after 10 min if ongoing)', duration: 'Single dose (rescue)', maxDose: '10 mg', evidenceLevel: 'A', pregnancyCategory: 'D' },",
  "          { drug: 'Phenytoin IV (Status Epilepticus)', dose: 'Loading 20 mg/kg IV (max 1,500 mg) at 50 mg/min. Maintenance 100 mg IV q8h (adjust per levels target 10-20 mcg/mL)', route: 'IV', frequency: 'Loading then TDS', duration: 'Until oral therapy established', maxDose: '1,500 mg load; 600 mg/day maintenance', evidenceLevel: 'A', pregnancyCategory: 'D' },",
  "          { drug: 'Topiramate (Add-on refractory)', dose: 'Start 25 mg nocte, titrate by 25-50 mg q1-2 weeks to 50-200 mg BD', route: 'PO', frequency: 'Twice daily', duration: 'Lifelong', maxDose: '400 mg/day', evidenceLevel: 'B', pregnancyCategory: 'D', renalAdjustment: 'Reduce dose if CrCl <50' },",
  '        ],',
  "        duration: 'AED therapy: lifelong for most patients (may attempt withdrawal after 2-5 years seizure-free in selected patients)',",
  "        monitoring: ['Seizure diary (frequency, duration, type, triggers, post-ictal)', 'AED serum levels (PHT, CBZ, VPA, PB: therapeutic range every 6-12 months or when dose changed)', 'CBC, LFT, Cr (annually; more frequently for VPA: LFT q3-6 months first year)', 'Mood screening annually (PHQ-9, GAD-7)', 'Bone health (Ca, Vit D, DEXA for VPA/PHT/CBZ long-term)', 'Folic acid 5 mg daily for WOCBP on enzyme-inducing AEDs', 'Annual review: drug interactions, adherence, side effects, driving, employment, QOL'],",
  '      },',
  '    ],',
]);

fs.appendFileSync(p, l.join('\n') + '\n', 'utf8');
console.log('D3 part C written. Size:', fs.statSync(p).size);
