const fs = require('fs');
const p = 'C:\\Users\\Administrator\\Desktop\\client\\lib\\amexan\\departments\\neuro.ts';
const l = [];

const add = s => l.push(s);
const addl = a => a.forEach(x => l.push(x));

// D1 continued: investigations
addl([
  '    investigations: [',
  "      { test: 'Non-contrast CT Brain (NCCT)', purpose: 'Exclude haemorrhage; identify early ischaemic signs; assess ASPECTS score', timing: 'emergency', sensitivity: 55, specificity: 98, positiveResult: 'Loss of grey-white differentiation, sulcal effacement, hyperdense artery sign (thrombus), ASPECTS <10 indicates early ischaemia', negativeResult: 'Normal NCCT does not exclude acute ischaemic stroke (up to 50% normal in first 3-6h)' },",
  "      { test: 'CT Angiography (CTA) Head and Neck', purpose: 'Detect large vessel occlusion (LVO); assess carotid/vertebral stenosis; guide thrombectomy decision', timing: 'emergency', sensitivity: 95, specificity: 98, positiveResult: 'Occlusion of ICA, MCA-M1/M2, ACA, basilar, PCA; or significant carotid stenosis >70%; or dissection', negativeResult: 'No LVO; may still be lacunar or distal vessel stroke' },",
  "      { test: 'CT Perfusion (CTP)', purpose: 'Identify salvageable penumbra vs infarct core; extended time window (6-24h) selection', timing: 'emergency', sensitivity: 90, specificity: 85, positiveResult: 'Large penumbra (Tmax >6 sec volume) relative to core (CBF <30% volume) indicates salvageable tissue', negativeResult: 'Small or no penumbra/low mismatch ratio suggests limited benefit from reperfusion' },",
  "      { test: 'MRI Brain (DWI + ADC + GRE/SWI + FLAIR)', purpose: 'Gold standard for acute ischaemic stroke detection; differentiate acute vs chronic; DWI positive within minutes', timing: 'urgent', sensitivity: 95, specificity: 98, positiveResult: 'DWI hyperintense with ADC hypointense = acute ischaemic core; GRE/SWI may show haemorrhage or microbleeds', negativeResult: 'No DWI restriction argues strongly against acute ischaemic stroke' },",
  "      { test: 'ECG (12-lead)', purpose: 'Detect atrial fibrillation, acute MI, arrhythmias; determine stroke aetiology', timing: 'emergency', sensitivity: 85, specificity: 95, positiveResult: 'AF (paroxysmal or persistent), LVH, acute ischaemic changes, prolonged QT', negativeResult: 'Normal ECG -> ambulatory monitoring for paroxysmal AF' },",
  "      { test: 'Echocardiogram (TTE +/- TOE)', purpose: 'Detect cardioembolic source (LV thrombus, PFO, valvular vegetations, myxoma)', timing: 'routine', sensitivity: 75, specificity: 90, positiveResult: 'LV thrombus, left atrial appendage thrombus, PFO with shunt, valvular vegetations, atrial myxoma', negativeResult: 'No cardioembolic source; consider TOE if high suspicion (cryptogenic stroke)' },",
  "      { test: 'CBC with Platelets', purpose: 'Baseline before thrombolysis; detect polycythaemia, thrombophilia, infection', timing: 'emergency', positiveResult: 'Thrombocytopenia (<100) contraindicates thrombolysis; polycythaemia suggests hyperviscosity; leukocytosis may indicate infection', negativeResult: 'Normal CBC' },",
  "      { test: 'Coagulation Profile (PT, aPTT, INR)', purpose: 'Assess bleeding risk before thrombolysis; exclude coagulopathy', timing: 'emergency', positiveResult: 'INR >1.7 contraindicates thrombolysis; elevated aPTT suggests anticoagulation effect', negativeResult: 'Normal coagulation' },",
  "      { test: 'Random Blood Glucose', purpose: 'Exclude hypoglycaemia mimicking stroke; hyperglycaemia worsens outcome', timing: 'emergency', sensitivity: 99, specificity: 99, positiveResult: 'BGL <3.0 mmol/L (hypoglycaemia mimic) or >10 mmol/L (worse outcome)', negativeResult: 'Normoglycaemia' },",
  "      { test: 'Full Lipid Profile', purpose: 'Assess vascular risk; guide secondary prevention (statin intensity)', timing: 'routine', positiveResult: 'LDL >2.6 mmol/L (moderate risk) or >1.8 mmol/L (high risk); low HDL', negativeResult: 'Normal lipids' },",
  "      { test: 'HbA1c', purpose: 'Screen for undiagnosed diabetes; assess glycaemic control', timing: 'routine', positiveResult: '>6.5% (diabetes) or >5.7% (pre-diabetes)', negativeResult: '<5.7%' },",
  "      { test: 'HIV Serology', purpose: 'High prevalence in Kenya; HIV increases stroke risk (vasculopathy, opportunistic infections)', timing: 'routine', positiveResult: 'HIV positive -> need to differentiate HIV vasculopathy from opportunistic infection', negativeResult: 'HIV negative' },",
  '    ],',
  '    imaging: [',
  "      { modality: 'Non-Contrast CT Brain (NCCT)', indication: 'First-line imaging in all suspected acute stroke patients within 20 min of arrival. Differentiates ischaemic from haemorrhagic stroke before thrombolysis.', findings: 'Early ischaemic signs: loss of grey-white matter differentiation (especially insular ribbon/lentiform nucleus), sulcal effacement, hyperdense MCA/ICA sign (thrombus). ASPECTS score: 1 point subtracted for each region involved (M1-6, caudate, lentiform, IC, insula). ASPECTS >=6 = favourable for thrombolysis/thrombectomy. Haemorrhage: hyperdense lesion (60-80 HU). Mass effect, midline shift.', sensitivity: 55, specificity: 98, preparation: 'Rapid acquisition; no contrast needed' },",
  "      { modality: 'CT Angiography (CTA) Head and Neck', indication: 'Assess for LVO (thrombectomy candidate), carotid/vertebral dissection, stenosis assessment. Perform simultaneously with NCCT.', findings: 'Vascular occlusion: absence of contrast opacification in vessel. LVO sites: ICA terminus (T occlusion), MCA-M1/M2, ACA, basilar artery, PCA. Carotid stenosis: NASCET criteria grading. Dissection: tapered narrowing, string sign, intimal flap, pseudoaneurysm. Collateral assessment.', sensitivity: 95, specificity: 98, preparation: 'IV contrast (50-100 mL), rapid injection; assess renal function' },",
  "      { modality: 'MRI Brain (DWI/ADC/GRE/FLAIR/MRA)', indication: 'Gold standard confirmation of acute ischaemic stroke. Used when CT inconclusive, for posterior circulation stroke, or to determine stroke age. DWI positive in minutes.', findings: 'DWI: bright signal (acute ischaemic core). ADC: dark (restricted diffusion) - persists 7-10 days. GRE/SWI: haemorrhage (blooming artefact), microbleeds, thrombus susceptibility effect. FLAIR: hyperintensity in subacute stage (extracellular oedema). DWI-FLAIR mismatch identifies patients within 4.5h window. MRA TOF: demonstrates large vessel patency/stenosis.', sensitivity: 95, specificity: 98, preparation: 'Screen for MRI contraindications (pacemaker, metallic implants, claustrophobia)' },",
  "      { modality: 'Carotid Doppler Ultrasound', indication: 'Detect carotid stenosis; useful for follow-up after revascularisation; alternative if CTA/MRA contraindicated', findings: 'PSV >230 cm/s suggests >70% stenosis (NASCET). Spectral broadening, post-stenotic turbulence. Plaque morphology (calcified, ulcerated, echolucent).', sensitivity: 85, specificity: 90, preparation: 'No special preparation' },",
  '    ],',
  '    severityCriteria: [',
  "      { criterion: 'NIHSS Score (National Institutes of Health Stroke Scale)', mild: '0-4 (minor stroke)', moderate: '5-15 (moderate stroke)', severe: '16-20 (moderate-severe)', critical: '21-42 (severe stroke)' },",
  "      { criterion: 'ASPECTS Score (CT-based)', mild: '8-10 (minimal early ischaemic change)', moderate: '6-7 (moderate change)', severe: '4-5 (extensive change)', critical: '0-3 (large core, poor outcome)' },",
  "      { criterion: 'Level of Consciousness (NIHSS Ia)', mild: '0 (Alert)', moderate: '1 (Not alert, arousable)', severe: '2 (Not alert, obtunded)', critical: '3 (Unresponsive/coma)' },",
  "      { criterion: 'Systolic BP', mild: '<140 mmHg', moderate: '140-180 mmHg', severe: '180-220 mmHg', critical: '>220 mmHg (risk of haemorrhagic transformation)' },",
  "      { criterion: 'Blood Glucose Level', mild: '4-8 mmol/L', moderate: '8-12 mmol/L', severe: '12-20 mmol/L', critical: '>20 or <3 mmol/L' },",
  "      { criterion: 'Large Vessel Occlusion (LVO) on CTA', mild: 'No LVO (lacunar/perforator stroke)', moderate: 'Distal MCA (M2/M3) or ACA', severe: 'Proximal MCA (M1), ICA terminus, basilar', critical: 'Basilar occlusion + coma (locked-in syndrome); massive MCA (T occlusion)' },",
  "      { criterion: 'Haemorrhagic Transformation Risk', mild: 'ASPECTS >=8, no HTN crisis, no anticoagulation', moderate: 'ASPECTS 6-7, BP 180-200, single antiplatelet', severe: 'ASPECTS <6, uncontrolled HTN, dual antiplatelet', critical: 'ASPECTS <4, INR >1.7, thrombocytopenia, known bleeding diathesis' },",
  '    ],',
  '    diagnosticCriteria: [',
  "      { name: 'WHO Definition of Stroke', type: 'required', description: 'Rapidly developing clinical signs of focal (or global) disturbance of cerebral function, lasting >24 hours or leading to death, with no apparent cause other than vascular origin.' },",
  "      { name: 'TOAST Classification (Aetiological Subtype)', type: 'required', description: '1. Large-artery atherosclerosis (LAA): >50% stenosis or occlusion of a major cerebral artery. 2. Cardioembolism (CE): cardiac source confirmed (AF, LV thrombus, prosthetic valve, PFO, endocarditis). 3. Small-vessel occlusion (SVO): lacunar infarct <1.5 cm on imaging. 4. Stroke of other determined aetiology (SOD): dissection, vasculitis, hypercoagulable, sickle cell, vasculopathy. 5. Stroke of undetermined aetiology (SUD): no cause found despite complete work-up (cryptogenic).' },",
  "      { name: 'Clinical Diagnosis by Vascular Territory', type: 'minor', description: 'Anterior circulation (MCA/ACA): hemiparesis, hemisensory loss, aphasia (dominant), neglect (non-dominant), homonymous hemianopia, gaze preference. Posterior circulation (Vertebrobasilar/PCA): vertigo/nystagmus, ataxia, diplopia, dysphagia, crossed signs, quadriparesis, hemianopia, decreased consciousness. Lacunar: pure motor, pure sensory, ataxic hemiparesis, clumsy hand-dysarthria.' },",
  '    ],',
]);

fs.appendFileSync(p, l.join('\n') + '\n', 'utf8');
console.log('D1 part B written. Size:', fs.statSync(p).size);
