const fs = require('fs');
const p = 'C:\\Users\\Administrator\\Desktop\\client\\lib\\amexan\\departments\\neuro.ts';
const l = [];
const add = s => l.push(s);
const addl = a => a.forEach(x => l.push(x));

// D1: treatmentGuidelines (biggest section)
addl([
  '    treatmentGuidelines: [',
  '      {',
  "        name: 'AHA/ASA Acute Ischaemic Stroke Guidelines 2024 (Kenya/MOH Adapted)', source: 'AHA/ASA Guidelines 2024, WHO, MOH Kenya Stroke Guidelines', year: 2024,",
  '        firstLine: [',
  "          { drug: 'Alteplase (tPA) IV thrombolysis', dose: '0.9 mg/kg IV (max 90 mg); 10% as bolus over 1 min, remaining 90% over 60 min', route: 'IV', frequency: 'Single dose (one-time)', duration: 'Bolus + 60-min infusion', maxDose: '90 mg total', evidenceLevel: 'A', pregnancyCategory: 'C' },",
  "          { drug: 'Aspirin (Acute phase after exclusion of haemorrhage)', dose: '300 mg PO (loading) then 75-100 mg daily', route: 'PO (or NG if dysphagic)', frequency: 'Once daily', duration: 'Lifelong', evidenceLevel: 'A', pregnancyCategory: 'C' },",
  "          { drug: 'Atorvastatin (High-intensity statin)', dose: '40-80 mg PO nightly', route: 'PO', frequency: 'Once daily (nightly)', duration: 'Lifelong', maxDose: '80 mg', evidenceLevel: 'A', pregnancyCategory: 'X' },",
  '        ],',
  '        stepProtocol: [',
  "          { step: 1, therapy: 'Pre-hospital and ED: Recognition, triage, and stabilisation', details: 'FAST or BE-FAST assessment. Time zero = last known well (LKW) time. Target door-to-CT <20 min, door-to-needle (DTN) <60 min. Stabilise: monitor airway/breathing/circulation. O2 if SpO2 <94%. Treat hypoglycaemia. Nil by mouth (dysphagia screen). 12-lead ECG. Start NCCT brain within 20 min of arrival. All non-contrast CTs to be reported immediately (teleradiology if needed). If LKW >4.5h or uncertain: proceed to CTA + CTP/MRI for extended window assessment.', duration: 'First 60 min (door-to-needle target)', monitoring: ['NIHSS q15min during tPA', 'BP q15min x 2h then q30min x 6h then q1h x 16h', 'Airway/breathing for declining consciousness', 'Dysphagia screen before any oral intake'], alternatives: ['Tenecteplase (TNK) 0.25 mg/kg IV bolus (max 25 mg) - increasingly used as alternative to alteplase due to easier administration'] },",
  "          { step: 2, therapy: 'Thrombolysis (IV alteplase) - if eligible', details: 'Eligible: LKW within 4.5h, age >=18, NIHSS >=4 (or disabling deficit even if NIHSS <4), BP <185/110 before tPA. Contraindications: ICH on CT, INR >1.7, platelets <100, heparin in last 48h with elevated aPTT, major surgery/trauma/ICH within 3 months, GI/GU bleed within 21 days, SBP >185 or DBP >110 refractory to treatment, rapidly improving symptoms, seizure at onset with residual deficit, glucose <2.8 or >22 mmol/L. Administer per protocol. Post-tPA: monitor in stroke unit/HDU. No antiplatelet or anticoagulation for 24h (confirm haemorrhage excluded on 24h CT). Control BP <180/105.', duration: 'Bolus + 60-min infusion; 24h post-tPA monitoring', monitoring: ['NIHSS q15min during infusion, q30min x 6h, q1h x 24h', 'BP q15min x 2h, q30min x 6h, q1h x 16h', 'CT brain at 24h (or earlier if neurological deterioration)', 'Bleeding assessment: gums, skin, urine, stool, mental status'], alternatives: ['Tenecteplase (TNK) 0.25 mg/kg IV bolus over 5-10 sec - non-inferior, easier administration, preferred by some centres'] },",
  "          { step: 3, therapy: 'Mechanical thrombectomy (endovascular therapy)', details: 'Indications: LVO (ICA terminus, MCA-M1/M2, basilar artery), within 6h of LKW (DAWN/DEFUSE-3 criteria up to 24h with perfusion imaging), pre-stroke mRS 0-1, ASPECTS >=6 (or CT perfusion with favourable mismatch). Penumbra > core by 1.2x mismatch, core <21 mL if >6h from LKW, core <31 mL if >12h from LKW (basilar). Transfer to comprehensive stroke centre if needed. Procedure: femoral/radial access, guide catheter to target vessel, stent retriever or aspiration catheter, recanalisation target TICI 2b-3 (good reperfusion). Post-procedural care: ICU/HDU for 24h, BP target <140/90 (strict), NIHSS q1h, neurological checks, access site monitoring.', duration: 'Procedure duration typically 30-90 min; post-procedure ICU/HDU for 24-48h', monitoring: ['NIHSS q1h x 24h', 'BP q15min x 2h then q1h (target <140/90)', 'Groin/access site q1h for haematoma/pseudoaneurysm', 'Neuro checks for deterioration', 'CT brain at 24h post-procedure'], alternatives: ['TNK bridging before thrombectomy if not already thrombolysed', 'Direct thrombectomy (skip thrombolysis) if LVO + contraindication to tPA'] },",
  "          { step: 4, therapy: 'Acute medical management and secondary prevention', details: 'Aspirin 300 mg PO (loading) after ruling out haemorrhage on 24h CT (or immediately if no tPA given). If post-thrombolysis: start aspirin after 24h CT confirms no haemorrhage. Dual antiplatelet therapy (DAPT) for 24-48h if TIA/minor stroke (NIHSS <=3) and no cardioembolic source: aspirin 300 mg + clopidogrel 300 mg loading then aspirin 75 mg + clopidogrel 75 mg daily x 21 days then single. Atorvastatin 40-80 mg PO nightly (high-intensity regardless of baseline LDL). BP management: if tPA given, maintain <180/105 for 24h then start/continue antihypertensives. If no tPA, hold antihypertensives for first 24h unless SBP >220 or DBP >120 (permissive hypertension maintains penumbral perfusion). Thereafter: target BP <130/80 long-term. DVT prophylaxis: LMWH or compression stockings (if immobile).', duration: 'Lifelong secondary prevention', monitoring: ['BP daily (target long-term <130/80)', 'Lipid panel at 4-6 weeks post-statin', 'HbA1c q3-6 months (if diabetic)', 'Medication adherence', 'Carotid Doppler at 3-6 months (if stenosis)'], alternatives: ['Ticagrelor 90 mg BD alternative to clopidogrel for DAPT', 'Clopidogrel monotherapy if aspirin intolerant', 'DAPT (aspirin + clopidogrel) longer if symptomatic large artery stenosis'] },",
  "          { step: 5, therapy: 'Stroke unit care and rehabilitation', details: 'Admit to stroke unit/ward with multidisciplinary team (neurologist, nursing, physiotherapy, occupational therapy, speech therapy, nutritionist, social worker). Daily neurological assessment (NIHSS). Dysphagia assessment by SLT before oral intake (water swallow test, then formal assessment). NG tube if dysphagic. Early mobilisation: start 24-48h after stroke when haemodynamically stable. Daily physio: motor retraining, balance, gait, transfers, spasticity management. OT: ADL training, upper limb function, cognitive assessment, visual/perceptual deficits. SLT: aphasia therapy, communication aids, dysphagia management. Psychosocial: mood assessment (post-stroke depression common), family counselling, caregiver support. Discharge planning: home assessment, equipment needs, community therapy referral, follow-up at neurology or medical clinic.', duration: 'Acute stay 5-14 days; rehabilitation weeks to months', monitoring: ['Daily NIHSS', 'Modified Rankin Scale (mRS) pre-discharge', 'Mood screening (PHQ-9)', 'Dysphagia reassessment', 'Fall risk assessment', 'Carer needs assessment'], alternatives: ['Referral to regional rehabilitation centre if prolonged needs', 'Community-based rehabilitation in rural areas'] },",
  '        ],',
  '        secondLine: [',
  "          { drug: 'Clopidogrel (for DAPT or monotherapy)', dose: '300 mg loading then 75 mg daily', route: 'PO', frequency: 'Once daily', duration: '21 days DAPT then lifelong monotherapy (or lifelong monotherapy alone)', evidenceLevel: 'A', pregnancyCategory: 'B' },",
  "          { drug: 'Ticagrelor', dose: '180 mg loading then 90 mg twice daily', route: 'PO', frequency: 'Twice daily', duration: '21 days DAPT (with aspirin) then monotherapy lifelong', evidenceLevel: 'B', pregnancyCategory: 'C' },",
  "          { drug: 'Tenecteplase (TNK)', dose: '0.25 mg/kg IV bolus (max 25 mg)', route: 'IV (bolus)', frequency: 'Single bolus', duration: 'One-time bolus', maxDose: '25 mg', evidenceLevel: 'B', pregnancyCategory: 'C' },",
  "          { drug: 'Enoxaparin (DVT prophylaxis)', dose: '40 mg SC daily', route: 'SC', frequency: 'Once daily', duration: 'During immobility/ward stay', evidenceLevel: 'A', renalAdjustment: 'Reduce dose if CrCl <30' },",
  '        ],',
  "        duration: 'Acute: first 24-72h critical for thrombolysis/thrombectomy; inpatient stay 5-14 days; secondary prevention lifelong',",
  "        monitoring: ['NIHSS daily during admission', 'BP monitoring: q1h acute phase, then daily', 'Dysphagia screen before oral intake', 'Aspiration precautions', 'DVT prophylaxis compliance', 'Fever control (pyrexia worsens outcome)', 'Pain assessment', 'Bowels/bladder function', 'Mood screening (PHQ-9)', 'Modified Rankin Scale (mRS)'],",
  '      },',
  '    ],',
  '    admissionCriteria: [',
  '      { indications: [\'Acute stroke with symptom onset <24h\', \'LKW within 24h (thrombolysis/thrombectomy evaluation)\', \'New focal neurological deficit (FAST positive)\', \'NIHSS >=4 (or disabling deficit even if NIHSS <4)\', \'Transient ischaemic attack (TIA) with ABCD2 >=4 or crescendo TIAs\', \'Suspected stroke with symptom onset uncertain (for investigation)\'], level: \'ward\', parameters: [{ param: \'Onset time\', threshold: \'<24h from LKW\' }, { param: \'NIHSS\', threshold: \'>=4\' }, { param: \'CT Brain\', threshold: \'No haemorrhage (ischaemic confirmed)\' }] },',
  '      { indications: [\'Post-thrombolysis (alteplase/TNK) for 24h monitoring\', \'Post-thrombectomy for 24-48h monitoring\', \'Large stroke with decreased consciousness (NIHSS >15)\', \'Stroke with significant haemorrhagic transformation\', \'Posterior circulation stroke with unstable airway/breathing\', \'Malignant MCA syndrome (large MCA infarct with mass effect)\', \'BP requiring IV antihypertensives\', \'Cardiorespiratory instability (AF with RVR, acute HF, MI)\'], level: \'HDU\', parameters: [{ param: \'NIHSS\', threshold: \'>15 or post-thrombolysis/thrombectomy\' }, { param: \'BP\', threshold: \'Requiring IV therapy\' }, { param: \'Consciousness\', threshold: \'GCS <=12 or declining\' }] },',
  '      { indications: [\'Malignant MCA syndrome with impending herniation (decompressive hemicraniectomy candidate)\', \'Basilar artery occlusion with coma/thrombectomy\', \'Massive haemorrhagic transformation with herniation\', \'Status epilepticus as complication\', \'Need for mechanical ventilation (airway compromise, aspiration)\'], level: \'ICU\', parameters: [{ param: \'GCS\', threshold: \'<=8\' }, { param: \'CT\', threshold: \'Midline shift >=5mm or herniation\' }, { param: \'Airway\', threshold: \'Unable to protect airway\' }] },',
  '    ],',
  '    dischargeCriteria: {',
  '      clinical: [\'Neurologically stable (NIHSS unchanged or improving x 48h)\', \'Haemodynamically stable (BP controlled on oral therapy)\', \'No fever or infection\', \'Dysphagia assessed and safe swallow established (or NG/PEG in place with plan)\', \'Able to mobilise safely with or without assistance\', \'Pain controlled\', \'No evidence of DVT or PE\', \'Mood stable (no severe depression/psychosis)\'],',
  '      lab: [\'BP within target range (on oral therapy)\', \'Lipid panel completed (statin dose optimised)\', \'Glucose controlled (if diabetic)\', \'CBC/coagulation stable (post-thrombolysis, no bleeding)\'],',
  '      social: [\'Carer available/support system in place\', \'Home environment assessed (OT home visit if needed)\', \'Equipment (wheelchair, walking aid, commode) arranged\', \'Community physio/OT/SLT referral made\', \'Follow-up appointment confirmed (neurology/medical clinic)\', \'Medication reconciliation and adherence counselling done\', \'Stroke education: risk factors, warning signs, medication, emergency plan\', \'Family/carer education on care needs\'],',
  '    },',
]);

fs.appendFileSync(p, l.join('\n') + '\n', 'utf8');
console.log('D1 part C written. Size:', fs.statSync(p).size);
