const fs = require('fs');
const p = 'C:\\Users\\Administrator\\Desktop\\client\\lib\\amexan\\departments\\neuro.ts';
const l = [];

const addl = a => a.forEach(x => l.push(x));

// D1: complications, followUp, prognosis, emergencyFlags, pediatricAdjustments, pregnancyAdjustments, aiReasoning, clinicalNoteTemplate, closing
addl([
  '    complications: [',
  "      { name: 'Haemorrhagic Transformation (Symptomatic ICH)', incidence: 5, timeCourse: 'First 24-48h post-stroke, especially after thrombolysis (2-7%) or thrombectomy', management: 'Stop antiplatelet/anticoagulation. Urgent NCCT. Reverse anticoagulation if appropriate (vitamin K, FFP, PCC if warfarin; idarucizumab if dabigatran; andexanet if factor Xa). Neurosurgical consult (decompression, haematoma evacuation). BP control (target <160/90). Supportive care.', redFlags: ['Worsening neurological deficit (NIHSS increase >=4)', 'New severe headache', 'Decreased consciousness', 'Vomiting', 'Hypertension'] },",
  "      { name: 'Malignant MCA Syndrome (Massive Oedema/Herniation)', incidence: 10, timeCourse: '24h-5 days post-stroke (peak 72h)', management: 'Medical: elevate head 30 degrees, mannitol 1-1.5 g/kg IV q6h, hyperventilation (pCO2 30-35 mmHg) transiently. Surgical: decompressive hemicraniectomy + duroplasty if <60 years, NIHSS >15, ASPECTS <=5, MCA infarct >50% of territory within 48h of symptom onset. DHC reduces mortality from 70% to 20% but survivors have significant disability (mRS 3-4).', redFlags: ['Decreased consciousness (GCS falling)', 'Ipsilateral pupillary dilatation', 'Hemiparesis worsening', 'Cushing reflex (bradycardia + hypertension)', 'CT: midline shift >5mm'] },",
  "      { name: 'Post-stroke Dysphagia / Aspiration Pneumonia', incidence: 40, timeCourse: 'Acute: first 48h. Persistent: 15% at 3 months.', management: 'Nil by mouth until formal SLT assessment. Water swallow test at bedside. NG tube for hydration/nutrition. Modified diet (thickened fluids, pureed). PEG if dysphagia persists >4-6 weeks. Antibiotics for aspiration pneumonia. Oral care protocol.', redFlags: ['Coughing/choking with feeds', 'Wet/gurgly voice after swallowing', 'Recurrent chest infections', 'Weight loss', 'Dehydration'] },",
  "      { name: 'Post-stroke Seizures', incidence: 10, timeCourse: 'Early (within 7 days): 3-5%. Late (>7 days): 5-10%. Highest in haemorrhagic and large cortical strokes.', management: 'Acute seizure: IV lorazepam 0.1 mg/kg or midazolam 5-10 mg. Status epilepticus: per seizure protocol. AED prophylaxis: not routine; start levetiracetam 500 mg-1 g BD if >1 acute seizure or high risk (large haemorrhagic).', redFlags: ['Recurrent/prolonged seizures', 'Status epilepticus', 'Post-ictal deficit persisting >24h'] },",
  '    ],',
  "    followUp: { interval: '2 weeks post-discharge, then 1 month, 3 months, 6 months, then annually', duration: 'Lifelong', tests: ['BP at every visit (target <130/80)', 'Lipid panel at 6 weeks and annually', 'HbA1c at 3 months and annually (if diabetic)', 'Carotid Doppler at 3-6 months if stenosis known', 'ECG at each visit (detect AF)', 'Holter/event monitor if cryptogenic stroke (paroxysmal AF detection)', 'Modified Rankin Scale (mRS) at 3 months', 'Mood screening (PHQ-9) at each visit'], specialistReview: true, specialistTiming: 'Neurology follow-up at 2 weeks and 3 months; at 6 months if functional limitation persists; annually for secondary prevention' },",
  "    prognosis: 'Good functional outcome (mRS 0-2) at 3 months: 55-65% with thrombolysis, 70-80% with thrombectomy if LVO. Mortality: 12-20% at 30 days, 25-35% at 1 year. Poor prognostic factors: higher age, high NIHSS at presentation, large infarct core (ASPECTS <5), hyperglycaemia, atrial fibrillation, delayed treatment. Recurrence risk: 10-15% at 1 year, 25-40% at 5 years without optimal secondary prevention. With optimal secondary prevention (antiplatelet, statin, BP control, lifestyle): 50% relative risk reduction. Return to work: 40% at 1 year. Quality of life: 60% report good QOL at 1 year despite disability. In Kenya: mortality higher due to delayed presentation, limited thrombectomy access, and high post-stroke infection rates. Rehabilitation access limited - community-based programmes essential.',",
  '    emergencyFlags: [',
  "      { condition: 'Neurological deterioration (NIHSS increase >=4 from baseline)', action: 'Urgent review: check BP, glucose, O2 sats. STAT NCCT brain (exclude haemorrhagic transformation, oedema, herniation). If post-thrombolysis: stop any antiplatelet/anticoagulant, reverse if indicated, neurosurgery consult', timeCritical: '<15 minutes' },",
  "      { condition: 'Sudden decreased consciousness / GCS falling >2 points', action: 'ABC assessment. Protect airway (intubate if GCS <8). CT brain stat. Neurosurgery consult. Manage ICP (mannitol, hyperventilation). Evaluate for herniation', timeCritical: '<10 minutes' },",
  "      { condition: 'Suspected malignant MCA syndrome (large MCA infarct + declining consciousness + ipsilateral pupil change)', action: 'Immediate CT brain. Neurosurgery consult for decompressive hemicraniectomy. Mannitol 1 g/kg IV. Elevate head 30 degrees. Hyperventilate if herniating. Transfer to ICU', timeCritical: '<30 minutes' },",
  "      { condition: 'Seizure at onset or within 24h of stroke', action: 'IV lorazepam 4 mg or IV midazolam 5-10 mg. Check glucose. If status: per status epilepticus protocol. CT brain to exclude haemorrhagic transformation', timeCritical: '<5 minutes' },",
  "      { condition: 'Anaphylaxis / angioedema from alteplase (during/after tPA infusion)', action: 'STOP tPA infusion. Chlorphenamine 10 mg IV, hydrocortisone 200 mg IV. Maintain airway (angioedema may require intubation). ICU review', timeCritical: '<5 minutes' },",
  '    ],',
  '    pediatricAdjustments: [',
  "      { parameter: 'Stroke assessment scales', adjustment: 'Use Paediatric NIHSS (PedNIHSS) or modified adult NIHSS for children. To detect subtle deficits in younger children, use developmentally appropriate items.', ageRange: '<18 years' },",
  "      { parameter: 'Thrombolysis dosing', adjustment: 'Alteplase 0.9 mg/kg (max 90 mg) same as adult; 10% bolus over 1 min, 90% over 60 min. Limited paediatric evidence (case series). Same contraindications. Paediatric thrombectomy increasingly performed in experienced centres for LVO.', ageRange: '<18 years' },",
  "      { parameter: 'Aetiological work-up', adjustment: 'Broader aetiology: sickle cell disease (30% of paediatric stroke in Kenya), congenital heart disease, moyamoya, vasculitis, infection (TB, HIV, meningitis), metabolic disorders, dissection (trauma). MRI preferred over CT (better sensitivity). TCD screening for sickle cell children >2 years.', ageRange: '<18 years' },",
  '    ],',
  '    pregnancyAdjustments: [',
  "      { trimester: 'all', adjustment: 'Pregnancy increases stroke risk (especially 3rd trimester and postpartum). Thrombolysis (alteplase) is category C; use if benefit > risk (no absolute contraindication). CT brain safe (shield uterus). CTA with iodinated contrast: risk of fetal hypothyroidism (minimal with single dose). Thrombectomy safe (X-ray exposure minimal with proper shielding). Aspirin safe in pregnancy (low dose). Statins contraindicated (pregnancy category X) - hold during pregnancy. BP target <140/90 in pregnancy.', safety: 'caution', alternative: 'Aspirin 75 mg daily if antiplatelet needed; LMWH for VTE prophylaxis; nifedipine/labetalol for BP control (pregnancy-safe)' },",
  "      { trimester: 'third', adjustment: 'Highest risk period (peripartum and early postpartum). CT brain safe (shield uterus). Thrombolysis: use if clear benefit. If simultaneously at term/Labour: coordinate with obstetrics. Acute stroke management should not be delayed by pregnancy. Mode of delivery: vaginal delivery may be safe for mild deficits; caesarean for severe deficits (inability to push, increased ICP risk).', safety: 'caution' },",
  "      { trimester: 'postpartum', adjustment: '12-fold increased stroke risk in first 6 weeks postpartum (especially pre-eclampsia/eclampsia, CVT, postpartum angiopathy). BP monitoring essential. Antiplatelet: aspirin safe with breastfeeding. Statins: limited safety data (avoid, especially if breastfeeding). Breastfeeding: safe after stroke. Counselling on stroke risk for future pregnancies.', safety: 'caution', alternative: 'LMWH instead of antiplatelet for VTE/hypercoagulable states' },",
  '    ],',
  '    aiReasoning: {',
  "      presentationPattern: ['Sudden onset unilateral weakness + facial droop + speech difficulty = stroke until proven otherwise (FAST positive)', 'Any sudden onset focal neurological deficit in a patient with vascular risk factors = stroke until proven otherwise', 'Posterior circulation: vertigo + ataxia + diplopia + dysarthria = stroke mimic posterior circulation may be missed; examine for gaze palsy, nystagmus, crossed signs, Horner', 'Stroke symptoms + atrial fibrillation on ECG = cardioembolic stroke until proven otherwise; consider anticoagulation for secondary prevention', 'Young patient with stroke (<45) = look for dissection, PFO, thrombophilia, sickle cell, vasculitis, HIV, illicit drug use (cocaine, amphetamines)'],",
  "      keyFeatures: ['FAST positive (Face, Arm, Speech, Time)', 'Sudden onset (minutes to hours)', 'Focal deficit matching a vascular territory', 'NIHSS score quantifies severity', 'CT brain: exclude haemorrhage', 'CTA: identify LVO/thrombectomy candidate', 'Symptom onset time (LKW) critical for treatment decision'],",
  "      discriminatingQuestions: ['When was the patient last known well (LKW)?', 'What is the exact time of symptom onset?', 'Is the patient on any anticoagulation (warfarin, DOAC)?', 'Is there any recent history of bleeding, surgery, or trauma?', 'Does the patient have atrial fibrillation?', 'Is there any history of prior stroke or TIA?', 'Does the patient have diabetes, hypertension, smoking history?', 'Is the patient on antiplatelet therapy?', 'Any history of seizures at onset?'],",
  "      diagnosticAlgorithm: ['1. FAST assessment at point of first contact (pre-hospital/ED triage)', '2. Time zero / last known well. Activate stroke protocol/team.', '3. ABC stabilisation. O2 if SpO2 <94%. Check BGL (exclude hypoglycaemia).', '4. NIHSS assessment (quantify severity)', '5. STAT NCCT brain (within 20 min of arrival) -> rule out haemorrhage', '6. CT: if haemorrhage -> manage per haemorrhagic stroke protocol', '7. CT: if no haemorrhage + LKW <4.5h -> assess thrombolysis eligibility', '8. Check tPA contraindications: INR, platelets, BP, recent surgery/bleed, anticoagulation', '9. If LKW 4.5-24h or unclear -> CTA + CTP/MRI DWI for thrombectomy/extension window', '10. If LVO on CTA + eligible -> mechanical thrombectomy (up to 24h with perfusion)', '11. Admit to stroke unit/ward or HDU (post-tPA)/ICU (post-thrombectomy or large stroke)', '12. Start aspirin 300 mg post-24h CT if no haemorrhage (or immediately if no tPA)', '13. Start atorvastatin 40-80 mg (high-intensity statin)', '14. DVT prophylaxis if immobile', '15. Dysphagia screen before oral intake', '16. Secondary prevention: BP control, antiplatelet, statin, lifestyle modification, anticoagulation if AF', '17. Multidisciplinary rehabilitation: PT, OT, SLT, psychology, social work', '18. Discharge planning: mRS, home assessment, community therapy, follow-up arranged'],",
  '    },',
  '    clinicalNoteTemplate: {',
  "      sections: ['Patient demographics and presenting complaint', 'LKW (Last Known Well) time and symptom onset time', 'Stroke code activation time and arrival time', 'FAST assessment and pre-hospital findings', 'Vascular risk factors (HTN, DM, AF, smoking, dyslipidaemia, prior stroke)', 'Current medications (especially anticoagulation, antiplatelet, antihypertensives)', 'Examination: NIHSS score (total and each component), vital signs (BP, HR, RR, SpO2, BGL)', 'CT Brain: ASPECTS score, presence/absence of early ischaemic signs, exclusion of haemorrhage', 'CTA findings: LVO status, stenosis, dissection, collaterals', 'CT Perfusion/MRI findings (if performed): core volume, penumbra volume, mismatch ratio', 'Thrombolysis: given? time? dose? complications?', 'Thrombectomy: performed? time? TICI grade? complications?', 'Diagnosis: Ischaemic stroke, TOAST classification (LAA/CE/SVO/SOD/SUD), vascular territory', 'Admission plan: level of care (ward/HDU/ICU), monitoring frequency, nil by mouth/dysphagia status', 'Secondary prevention plan: antiplatelet, statin, antihypertensives, long-term anticoagulation if indicated', 'Rehabilitation plan: PT/OT/SLT referral, early mobilisation', 'Discharge planning: home assessment, equipment, follow-up'],",
  "      consultantWording: 'This [age]-year-old [gender] with [vascular risk factors] presented with [symptom] [duration] after LKW. NIHSS was [score] on arrival. NCCT brain showed [ASPECTS score, findings] with no haemorrhage. CTA revealed [LVO/stenosis/dissection/normal]. [Thrombolysis with alteplase/TNK was given at [time] post-LKW / No thrombolysis due to [reason].] [Thrombectomy was performed at [time] achieving TICI [grade] recanalisation / No thrombectomy due to [reason].] Diagnosis: Acute ischaemic stroke in [territory] due to [TOAST aetiology]. Plan: Admit to [ward/HDU/ICU]. [Aspirin/anticoagulation]. Atorvastatin [dose]. BP goal [target]. Dysphagia status: [safe/NG tube pending]. Rehabilitation: [PT/OT/SLT referrals].',",
  "      exampleNote: 'A 62-year-old male with hypertension and type 2 diabetes presented at 14:30 with LKW at 12:00 (onset 2.5h ago). FAST positive: left facial droop, left arm drift, slurred speech. NIHSS 12 (1a:1, 1b:1, 1c:1, 6:2, 7:2, 8:2, 9:2, 10:1). BP 165/95, BGL 8.2 mmol/L. NCCT brain: ASPECTS 9 (loss of insular ribbon). CTA: right MCA-M1 occlusion. Patient within 4.5h window, no contraindications to tPA. Alteplase 0.9 mg/kg (total 72 mg: 7.2 mg bolus, 64.8 mg infusion) started at 15:00 (door-to-needle 40 min). Transferred for thrombectomy: right MCA-M1 stent retriever, TICI 2b recanalisation at 17:00. Door-to-puncture: 2h. Post-procedure CT: no haemorrhage. Admitted to HDU for 24h monitoring. BP controlled. Diagnosis: Acute right MCA ischaemic stroke (LAA: right MCA-M1 occlusion). Plan: Aspirin 300 mg after 24h CT (confirm no haemorrhage). Atorvastatin 80 mg nocte. BP target <140/90 acute then <130/80. Dysphagia: failed water swallow test, keep NBM, SLT review. PT/OT daily. Review for long-term anticoagulation (prolonged Holter for paroxysmal AF).',",
  '    },',
  '  },',
]);

fs.appendFileSync(p, l.join('\n') + '\n', 'utf8');
console.log('D1 complete. Size:', fs.statSync(p).size);
