const fs = require('fs');
const p = 'C:\\Users\\Administrator\\Desktop\\client\\lib\\amexan\\departments\\neuro.ts';
const l = [];
const addl = a => a.forEach(x => l.push(x));

// Disease 2: Haemorrhagic Stroke (part A - epidemiology, symptomWeights, riskFactors, differentials, investigations)
addl([
  '  // ─── Stroke Unit: Haemorrhagic Stroke (Intracerebral Haemorrhage) ──────────',
  '  {',
  "    id: 'haemorrhagic-stroke',",
  "    name: 'Haemorrhagic Stroke',",
  "    specialtyId: 'NEURO', subspecialtyId: 'stroke', icd10: 'I61.9',",
  '    epidemiology: {',
  "      incidence: '3-5 million cases/year globally; 10-20% of all strokes; incidence 50-80 per 100,000 in high-resource settings, 100-150 per 100,000 in Sub-Saharan Africa',",
  "      prevalence: 'Accounts for 10-20% of all strokes worldwide; higher proportion in Africa (20-30% of all strokes due to untreated hypertension); leading cause of stroke mortality (40-50% 30-day mortality)',",
  "      ageDistribution: 'Mean age 60-65 years; occurs at younger age in Africa (mean 50-55 years) due to higher uncontrolled hypertension; rare <35 years (consider AVM, aneurysms, cavernoma)',",
  "      genderPredilection: 'Male > Female (1.4:1)',",
  "      geographicDistribution: 'Higher in Asia and Africa (20-30% of all strokes vs 10-15% in West); in Kenya, high burden from untreated hypertension, alcohol use, and limited acute care access',",
  "      seasonality: 'Slight increase in winter (hypertension exacerbation); related to alcohol binge-drinking patterns around holidays'",
  '    },',
  '    symptomWeights: [',
  "      { symptom: 'sudden severe headache (worst of life, thunderclap)', weight: 9, prevalence: 80, category: 'red_flag' },",
  "      { symptom: 'vomiting (often projectile)', weight: 8, prevalence: 60, category: 'red_flag' },",
  "      { symptom: 'decreased consciousness / coma', weight: 9, prevalence: 50, category: 'red_flag' },",
  "      { symptom: 'sudden focal neurological deficit (hemiparesis)', weight: 8, prevalence: 70, category: 'red_flag' },",
  "      { symptom: 'seizure at onset', weight: 6, prevalence: 15, category: 'major' },",
  "      { symptom: 'speech difficulty (aphasia/dysarthria)', weight: 7, prevalence: 45, category: 'major' },",
  "      { symptom: 'hypertension (BP >180/100 at presentation)', weight: 7, prevalence: 75, category: 'major' },",
  "      { symptom: 'neck stiffness / meningism', weight: 5, prevalence: 20, category: 'major' },",
  "      { symptom: 'focal sensory loss', weight: 5, prevalence: 30, category: 'minor' },",
  "      { symptom: 'visual disturbance (hemianopia, diplopia)', weight: 6, prevalence: 15, category: 'major' },",
  "      { symptom: 'ataxia / gait imbalance (cerebellar bleed)', weight: 8, prevalence: 10, category: 'major' },",
  "      { symptom: 'photophobia', weight: 4, prevalence: 15, category: 'minor' },",
  "      { symptom: 'fixed dilated pupil (ipsilateral to bleed — transtentorial herniation)', weight: 10, prevalence: 10, category: 'red_flag' },",
  '    ],',
  '    riskFactors: [',
  "      { factor: 'Hypertension (untreated or poorly controlled)', weight: 6.0, prevalence: 60 },",
  "      { factor: 'Age >55 years', weight: 3.0, prevalence: 50 },",
  "      { factor: 'Heavy alcohol consumption', weight: 4.0, prevalence: 20 },",
  "      { factor: 'Anticoagulation (warfarin, DOACs)', weight: 5.0, prevalence: 8 },",
  "      { factor: 'Cerebral Amyloid Angiopathy', weight: 3.5, prevalence: 15 },",
  "      { factor: 'Smoking', weight: 2.5, prevalence: 25 },",
  "      { factor: 'Male gender', weight: 1.5, prevalence: 55 },",
  "      { factor: 'Chronic liver disease (coagulopathy)', weight: 3.0, prevalence: 5 },",
  "      { factor: 'Low cholesterol', weight: 2.0, prevalence: 15 },",
  "      { factor: 'Illicit drug use (cocaine, amphetamines)', weight: 4.0, prevalence: 3 },",
  "      { factor: 'Arteriovenous Malformation (AVM)', weight: 2.0, prevalence: 1 },",
  "      { factor: 'Intracranial aneurysm', weight: 2.5, prevalence: 2 },",
  "      { factor: 'Haematological disorders (thrombocytopenia, haemophilia)', weight: 3.0, prevalence: 2 },",
  "      { factor: 'HIV (vasculopathy and HIV-associated hypertension)', weight: 2.5, prevalence: 10 },",
  '    ],',
  '    differentials: [',
  "      { disease: 'Intracerebral Haemorrhage (Haemorrhagic Stroke)', likelihood: 50, distinguishingFeatures: ['Sudden headache + vomiting + neurological deficit', 'CT: hyperdense intraparenchymal haematoma', 'Hypertensive at presentation', 'Rapid progression over minutes to hours'] },",
  "      { disease: 'Acute Ischaemic Stroke (with haemorrhagic transformation)', likelihood: 15, distinguishingFeatures: ['More gradual onset', 'CT: hypodense core with possible hyperdense areas', 'Less severe headache', 'Often cardioembolic', 'Onset over hours'] },",
  "      { disease: 'Subarachnoid Haemorrhage (SAH)', likelihood: 10, distinguishingFeatures: ['Thunderclap headache (instant, worst ever)', 'Meningism', 'CT: blood in basal cisterns/sulci', 'Aneurysm on CTA/DSA', 'Can present with minimal focal signs'] },",
  "      { disease: 'Cerebral Venous Sinus Thrombosis (CVT)', likelihood: 5, distinguishingFeatures: ['Headache (gradual or acute)', 'Seizures common', 'Often postpartum, dehydrated, or hypercoagulable', 'CT venogram: empty delta sign, thrombosed sinus', 'Venous infarction pattern (bilateral, haemorrhagic)'] },",
  "      { disease: 'Brain Tumour (with acute haemorrhage)', likelihood: 5, distinguishingFeatures: ['Pre-existing symptoms (headache weeks-months)', 'Seizure', 'Papilloedema', 'CT/MRI: mass lesion with mixed density/signal', 'Peripheral oedema disproportionate'] },",
  "      { disease: 'Hypertensive Encephalopathy (PRES)', likelihood: 4, distinguishingFeatures: ['Severe hypertension', 'Headache, visual disturbance, seizures', 'MRI: bilateral posterior white matter oedema', 'Reversible with BP control', 'No haematoma on CT'] },",
  "      { disease: 'Seizure with Post-ictal (Todd Paresis)', likelihood: 3, distinguishingFeatures: ['Seizure activity witnessed', 'Post-ictal weakness', 'Tongue biting, incontinence', 'CT: no haemorrhage', 'EEG: epileptiform activity'] },",
  '    ],',
  '    investigations: [',
  "      { test: 'Non-Contrast CT Brain (NCCT)', purpose: 'Diagnose ICH: detect haematoma, localisation, volume, intraventricular extension, hydrocephalus, mass effect', timing: 'emergency', sensitivity: 95, specificity: 100, positiveResult: 'Hyperdense intraparenchymal lesion (60-80 HU). Location: basal ganglia (40%), lobar (30%), thalamus (15%), pons/cerebellum (10%), brainstem (5%). Haematoma volume (ABC/2 formula). Intraventricular extension. Hydrocephalus. Midline shift. Subarachnoid extension.', negativeResult: 'No hyperdensity: if clinical suspicion high, consider CT venogram (CVT) or MRI (cerebral amyloid angiopathy with microbleeds)' },",
  "      { test: 'CT Angiography (CTA) Head', purpose: 'Detect underlying vascular lesion (AVM, aneurysm, dural fistula); spot sign predicts haematoma expansion', timing: 'emergency', sensitivity: 95, specificity: 98, positiveResult: 'Spot sign (intense contrast pooling within haematoma): predicts expansion. AVM: nidus, feeding arteries, draining veins. Aneurysm: saccular outpouching. Vasculitis: vessel irregularity.', negativeResult: 'No vascular lesion: indicates primary hypertensive ICH (if basal ganglia/thalamic) or amyloid (if lobar)' },",
  "      { test: 'CT Venogram (CTV)', purpose: 'Exclude CVT if atypical location (parasagittal, bilateral) or high suspicion (young, postpartum, hypercoagulable)', timing: 'urgent', sensitivity: 97, specificity: 99, positiveResult: 'Empty delta sign (superior sagittal sinus), filling defect in sinus, venous infarct with haemorrhagic component', negativeResult: 'Normal venous sinus filling' },",
  "      { test: 'MRI Brain (GRE/SWI, T1/T2, DWI)', purpose: 'Characterise haematoma age (hyperacute to chronic); detect underlying lesion; CAA diagnosis', timing: 'urgent', sensitivity: 95, specificity: 98, positiveResult: 'GRE/SWI: blooming artefact (acute blood). T1: isointense (hyperacute) -> hyperintense (early subacute). T2: hypointense (acute) -> hyperintense (chronic). DWI: central restriction may be present. CAA: multiple cortical/subcortical microbleeds (Boston criteria).', negativeResult: 'No haemorrhage or lesion on SWI suggests non-haemorrhagic diagnosis' },",
  "      { test: 'Coagulation Profile (PT, aPTT, INR, Fibrinogen)', purpose: 'Assess for coagulopathy as cause; guide reversal therapy', timing: 'emergency', positiveResult: 'INR >1.4 (warfarin), elevated aPTT (heparin, DOACs), low fibrinogen (DIC), prolonged PT (liver disease)', negativeResult: 'Normal coagulation - likely hypertensive ICH' },",
  "      { test: 'CBC with Platelets', purpose: 'Rule out thrombocytopenia; detect infection/inflammation', timing: 'emergency', positiveResult: 'Platelets <100 (risk of expansion); <50 (severe risk); leukocytosis suggests infection', negativeResult: 'Normal platelets' },",
  "      { test: 'ECG (12-lead)', purpose: 'Detect atrial fibrillation, LVH (hypertensive heart disease), QT prolongation (ICH-associated ECG changes)', timing: 'emergency', positiveResult: 'LVH (chronic hypertension), AF (possible cardioembolic), cerebral T-wave inversions, QT prolongation', negativeResult: 'Normal ECG' },",
  "      { test: 'Serum Creatinine/Urea', purpose: 'Assess renal function (hypertensive nephropathy; IV contrast risk if CTA needed)', timing: 'emergency', positiveResult: 'Elevated Cr suggests chronic hypertensive nephropathy or acute kidney injury', negativeResult: 'Normal' },",
  "      { test: 'LFTs (Liver Function Tests)', purpose: 'Screen for liver disease -> coagulopathy -> ICH', timing: 'routine', positiveResult: 'Elevated transaminases, low albumin, prolonged PT suggests chronic liver disease', negativeResult: 'Normal LFTs' },",
  "      { test: 'Toxicology Screen (urine)', purpose: 'Detect cocaine, amphetamine, methamphetamine (vasospasm/HTN induced)', timing: 'routine', positiveResult: 'Positive for stimulant drugs (cocaine, amphetamines)', negativeResult: 'Negative' },",
  '    ],',
]);

fs.appendFileSync(p, l.join('\n') + '\n', 'utf8');
console.log('D2 part A written. Size:', fs.statSync(p).size);
