const fs = require('fs');
const p = 'C:\\Users\\Administrator\\Desktop\\client\\lib\\amexan\\departments\\neuro.ts';
const l = [];
const addl = a => a.forEach(x => l.push(x));

// D2: aiReasoning, clinicalNoteTemplate, closing
addl([
  '    aiReasoning: {',
  "      presentationPattern: ['Sudden severe headache + vomiting + decreased consciousness = ICH until proven otherwise (CT needed emergently)', 'Acute focal deficit + severe hypertension + basal ganglia haematoma on CT = hypertensive ICH (most common)', 'Sudden headache + seizure + young patient = consider AVM or other structural lesion', 'ICH in patient on anticoagulation = expansion risk high; immediate reversal indicated', 'Lobar haemorrhage in elderly patient with history of hypertension = consider CAA (multiple microbleeds suggestive)', 'Cerebellar haemorrhage: headache + vomiting + ataxia + vertigo -> surgical emergency if >3 cm or hydrocephalus'],",
  "      keyFeatures: ['NCCT: hyperdense intraparenchymal haematoma', 'Hypertension (SBP >180 common)', 'Decreased consciousness (GCS <=13 in 50%)', 'Rapid progression over minutes', 'Headache + vomiting (ICP-related)', 'ICH Score for risk stratification', 'Spot sign on CTA predicts expansion'],",
  "      discriminatingQuestions: ['What is the exact GCS?', 'What is the BP at presentation?', 'Is the patient on any anticoagulation or antiplatelet?', 'Is there a history of bleeding disorder?', 'Is there a history of hypertension?', 'Is there a history of drug use (cocaine, amphetamines)?', 'Is the patient known to have an AVM or aneurysm?', 'Is there a family history of ICH or aneurysms?', 'What was the onset pattern? (sudden thunderclap vs gradual)'],",
  "      diagnosticAlgorithm: ['1. ABC assessment, protect airway if GCS <8 or deteriorating', '2. IV access x 2, bloods: CBC, Coag (INR/aPTT), platelets, Cr, LFT, group and screen', '3. STAT NCCT brain (within 20 min of arrival)', '4. If ICH confirmed: calculate ABC/2 volume, assess IVH, midline shift, hydrocephalus', '5. Calculate ICH Score (GCS, age >80, infratentorial, volume >30 mL, IVH)', '6. Acute BP management: start IV nicardipine/labetalol within 1h (target SBP <140)', '7. Reverse anticoagulation urgently (PCC/vitamin K/idarucizumab/andexanet)', '8. Consider CTA (spot sign assessment, rule out vascular lesion)', '9. Neurosurgery consult: EVD if IVH + hydrocephalus; evacuation if cerebellar >3 cm; decompression if herniation', '10. Seizure observation (no routine AED unless seizure)', '11. DVT prophylaxis: SCD then LMWH after 24-72h', '12. NG feeding by 48h if unable to swallow', '13. Repeat CT if deterioration (any GCS drop >=2)', '14. Transition to oral BP control (target <130/80 long-term)', '15. DSA/MRI at 6-12 weeks to re-evaluate for underlying structural lesion', '16. Rehabilitation: PT, OT, SLT, social work'],",
  '    },',
  '    clinicalNoteTemplate: {',
  "      sections: ['Patient demographics and presenting complaint', 'Onset: sudden vs progressive? headache severity?', 'Vascular risk factors: hypertension (duration, control), anticoagulation, alcohol, smoking, drugs', 'Current medications (especially anticoagulants, antiplatelets, antihypertensives)', 'Presentation GCS, NIHSS, vital signs (especially BP)', 'CT brain: haematoma location, volume (ABC/2), IVH, midline shift, hydrocephalus, spot sign on CTA', 'ICH Score components and total', 'Aetiology: SMASH-U classification', 'Acute management: BP therapy and targets, reversal given, neurosurgical intervention (EVD, craniotomy, decompression)', 'Serial neurological exam (GCS, pupils, motor)', 'Diagnosis: Spontaneous ICH, [location], [aetiology], ICH Score [value]', 'Admission plan: level of care (ward/HDU/ICU), monitoring frequency, investigations pending', 'Secondary prevention plan: BP control, address aetiology', 'Rehabilitation plan and discharge planning'],",
  "      consultantWording: 'This [age]-year-old [gender] with [risk factors] presented with [headache/vomiting/focal deficit] of sudden onset. GCS on arrival: [score]. BP: [value] mmHg. NCCT brain shows [location] intraparenchymal haemorrhage volume [value] mL (by ABC/2) with [IVH presence/extent / hydrocephalus / midline shift]. CTA shows [spot sign present/absent / no underlying AVM/aneurysm]. ICH Score: [value] (GCS component + age + infratentorial + volume + IVH). Diagnosis: Spontaneous ICH, [location], likely [hypertensive/amyloid/structural/anticoagulant-related]. Plan: [IV nicardipine/labetalol to target SBP <140], [reversal given], [neurosurgical intervention if needed]. Admit to [ICU/HDU/ward] for [monitoring].',",
  "      exampleNote: 'A 54-year-old male with untreated hypertension (known 3 years, not on medication) presents with sudden severe headache, vomiting x5, and right-sided weakness. LKW 2h ago. On arrival: GCS 10 (E3 V3 M4), BP 220/130, NIHSS 18. NCCT brain: left basal ganglia hyperdense haematoma, volume 45 mL (ABC/2 = 5 x 4.5 x 4 / 2). Intraventricular extension: trace in occipital horn. Midline shift 7 mm. No hydrocephalus. CTA: spot sign positive. No AVM/aneurysm. ICH Score: 3 (GCS 10-12: 1; age <80: 0; infratentorial: 0; volume >30: 1; IVH: 1). Diagnosis: Spontaneous left basal ganglia ICH (hypertensive), ICH Score 3. Acute management: Nicardipine IV started at 5 mg/h, titrated to 12 mg/h to achieve SBP <140. Mannitol 1 g/kg IV given. Vitamin K 10 mg IV + FFP empirically (INR 1.5). Neurosurgery consulted. TXA 1 g IV for spot sign. Admitted to HDU for q1h neuro-checks.',",
  '    },',
  '  },',
]);

fs.appendFileSync(p, l.join('\n') + '\n', 'utf8');
console.log('D2 complete. Size:', fs.statSync(p).size);
