const fs = require('fs');
const p = 'C:\\Users\\Administrator\\Desktop\\client\\lib\\amexan\\departments\\neuro.ts';
const l = [];
const addl = a => a.forEach(x => l.push(x));

// D3: Epilepsy (part A - through investigations)
addl([
  '  // ─── Epilepsy Unit: Epilepsy ──────────────────────────────────────────────',
  '  {',
  "    id: 'epilepsy',",
  "    name: 'Epilepsy',",
  "    specialtyId: 'NEURO', subspecialtyId: 'epilepsy', icd10: 'G40.9',",
  '    epidemiology: {',
  "      incidence: '50-70 per 100,000 persons/year globally; 5 million new diagnoses/year; higher in low- and middle-income countries (80-100 per 100,000)',",
  "      prevalence: 'Active epilepsy prevalence 0.5-1% of the population (5-10 per 1,000); 50 million people worldwide; 80% of global burden in low- and middle-income countries',",
  "      ageDistribution: 'Bimodal: higher in children <1 year and elderly >65 years; peak in early childhood (congenital, genetic, febrile-related) and late adulthood (stroke, dementia, tumour-related)',",
  "      genderPredilection: 'Male > Female (1.1:1) marginally',",
  "      geographicDistribution: 'Global; higher prevalence in Sub-Saharan Africa (7-10 per 1,000) due to endemic infections (neurocysticercosis, meningitis, malaria), perinatal complications, and traumatic brain injury',",
  "      seasonality: 'Seizure exacerbations can be seasonal: fevers in rainy season (infections), sleep deprivation in cultural events, alcohol binging during festive seasons'",
  '    },',
  '    symptomWeights: [',
  "      { symptom: 'generalised tonic-clonic seizures (GTCS)', weight: 10, prevalence: 60, category: 'red_flag' },",
  "      { symptom: 'focal (partial) seizures with impaired awareness (temporal lobe)', weight: 9, prevalence: 35, category: 'major' },",
  "      { symptom: 'focal motor seizures (Jacksonian march)', weight: 8, prevalence: 15, category: 'major' },",
  "      { symptom: 'absence seizures (brief staring spells)', weight: 8, prevalence: 10, category: 'major' },",
  "      { symptom: 'myoclonic jerks (especially early morning)', weight: 7, prevalence: 10, category: 'major' },",
  "      { symptom: 'auras (epigastric rising, deja vu, olfactory, psychic)', weight: 7, prevalence: 25, category: 'minor' },",
  "      { symptom: 'loss of consciousness / unresponsiveness', weight: 9, prevalence: 70, category: 'red_flag' },",
  "      { symptom: 'tongue biting (lateral)', weight: 6, prevalence: 30, category: 'major' },",
  "      { symptom: 'urinary incontinence during seizure', weight: 5, prevalence: 25, category: 'minor' },",
  "      { symptom: 'post-ictal confusion / lethargy', weight: 6, prevalence: 70, category: 'major' },",
  "      { symptom: 'post-ictal headache', weight: 5, prevalence: 40, category: 'minor' },",
  "      { symptom: 'Todd paresis (post-ictal focal weakness)', weight: 6, prevalence: 10, category: 'major' },",
  "      { symptom: 'nocturnal seizures (awakening from sleep)', weight: 7, prevalence: 20, category: 'major' },",
  '    ],',
  '    riskFactors: [',
  "      { factor: 'Family history of epilepsy (first-degree relative)', weight: 3.0, prevalence: 15 },",
  "      { factor: 'History of febrile seizures (complex)', weight: 3.5, prevalence: 5 },",
  "      { factor: 'Traumatic Brain Injury (moderate-severe)', weight: 5.0, prevalence: 8 },",
  "      { factor: 'Stroke (especially haemorrhagic)', weight: 4.0, prevalence: 10 },",
  "      { factor: 'CNS infection (meningitis, encephalitis, neurocysticercosis)', weight: 4.5, prevalence: 10 },",
  "      { factor: 'Perinatal complications (birth asphyxia, prematurity, neonatal seizures)', weight: 4.0, prevalence: 5 },",
  "      { factor: 'Cerebral palsy', weight: 5.0, prevalence: 2 },",
  "      { factor: 'Brain tumour (primary or metastatic)', weight: 4.0, prevalence: 5 },",
  "      { factor: 'Alzheimer disease / dementia (elderly)', weight: 3.5, prevalence: 5 },",
  "      { factor: 'Alcohol dependence (withdrawal seizures)', weight: 3.0, prevalence: 10 },",
  "      { factor: 'Sleep deprivation', weight: 2.5, prevalence: 25 },",
  "      { factor: 'Drug abuse (cocaine, amphetamines, tramadol)', weight: 3.0, prevalence: 5 },",
  "      { factor: 'Cerebral malaria in childhood', weight: 3.5, prevalence: 8 },",
  "      { factor: 'HIV encephalopathy / opportunistic infections', weight: 3.0, prevalence: 8 },",
  "      { factor: 'Malnutrition (thiamine, pyridoxine deficiency)', weight: 2.0, prevalence: 10 },",
  '    ],',
  '    differentials: [',
  "      { disease: 'Epilepsy (recurrent unprovoked seizures)', likelihood: 45, distinguishingFeatures: ['>=2 unprovoked seizures >24h apart', 'EEG: epileptiform discharges (spikes, sharp waves)', 'Stereotyped seizure semiology', 'Aura (may be present)', 'Post-ictal state'] },",
  "      { disease: 'Psychogenic Non-epileptic Seizures (PNES)', likelihood: 10, distinguishingFeatures: ['Non-stereotyped', 'Prolonged >5 min without cyanosis', 'Ictal crying/talking', 'Pelvic thrusting', 'Side-to-side head movement', 'Closed eyes during seizure', 'Normal EEG during event'] },",
  "      { disease: 'Syncope (Cardiac / Vasovagal)', likelihood: 12, distinguishingFeatures: ['Provoked by standing, pain, micturition, defecation', 'Prodrome: lightheadedness, visual grey-out', 'Brief loss of consciousness (seconds)', 'Rapid recovery without confusion', 'Normal EEG'] },",
  "      { disease: 'Migraine with Aura (Basilar, Hemiplegic)', likelihood: 5, distinguishingFeatures: ['Throbbing headache preceding or following symptoms', 'Aura: visual (scintillations, fortification spectra)', 'Duration: 5-60 min', 'No loss of consciousness', 'No post-ictal confusion'] },",
  "      { disease: 'Transient Ischaemic Attack (TIA)', likelihood: 5, distinguishingFeatures: ['Sudden onset focal deficit (negative symptoms)', 'No rhythmic jerking', 'No loss of consciousness (unless brainstem)', 'Duration: minutes to <1h', 'Complete recovery'] },",
  "      { disease: 'Sleep Disorders (Narcolepsy, Parasomnia, REM Behaviour Disorder)', likelihood: 3, distinguishingFeatures: ['Cataplexy (narcolepsy)', 'Hallucinations (hypnagogic/hypnopompic)', 'Polysomnography diagnostic'] },",
  "      { disease: 'Movement Disorders (Myoclonus, Tics, Dystonia)', likelihood: 3, distinguishingFeatures: ['No impairment of consciousness', 'Suppressible (tics)', 'Worsened by relaxation (myoclonus)', 'EEG: no epileptiform activity'] },",
  "      { disease: 'Acute Symptomatic Seizures (Provoked)', likelihood: 12, distinguishingFeatures: ['Seizure within 7 days of acute insult', 'Provoked by: hyponatraemia, hypoglycaemia, uraemia, hypocalcaemia, drug toxicity', 'Treat underlying cause: no need for long-term AED', 'EEG may show slowing but not epileptiform'] },",
  '    ],',
  '    investigations: [',
  "      { test: 'EEG (Routine 30 min, awake + sleep)', purpose: 'Detect epileptiform discharges to support diagnosis; classify seizure type and epilepsy syndrome', timing: 'routine', sensitivity: 50, specificity: 90, positiveResult: 'Spikes, sharp waves, spike-wave complexes, polyspike-wave, focal slowing, generalised discharges. Photoparoxysmal response. Sleep activation of discharges.', negativeResult: 'Normal EEG in 50% of epilepsy patients (single routine EEG does not exclude epilepsy). Repeat sleep-deprived EEG increases yield to 80%.' },",
  "      { test: 'Sleep-Deprived EEG', purpose: 'Increase diagnostic yield of epileptiform discharges (sleep deprivation activates discharges)', timing: 'routine', sensitivity: 80, specificity: 90, positiveResult: 'Interictal epileptiform discharges (IEDs) captured during sleep or after sleep deprivation', negativeResult: 'Persistently normal despite sleep deprivation reduces probability of epilepsy' },",
  "      { test: 'Long-term Video-EEG Monitoring (VEM)', purpose: 'Captures habitual events for definitive diagnosis; differentiate epilepsy vs PNES; localise seizure onset for surgical evaluation', timing: 'routine', sensitivity: 95, specificity: 98, positiveResult: 'Ictal EEG correlates with clinical seizure semiology; localises epileptogenic zone', negativeResult: 'No events captured during monitoring period (inconclusive)' },",
  "      { test: 'MRI Brain (Epilepsy Protocol: 3T, high-resolution, thin-slice, FLAIR, T1, T2, GRE)', purpose: 'Detect structural abnormalities underlying epilepsy (hippocampal sclerosis, cortical dysplasia, tumour, cavernoma, trauma)', timing: 'routine', sensitivity: 85, specificity: 95, positiveResult: 'Hippocampal sclerosis (T2/FLAIR hyperintensity, atrophy), focal cortical dysplasia (FCD), malformations of cortical development, tumour (low-grade glioma, ganglioglioma), cavernoma, post-traumatic gliosis, mesial temporal sclerosis (MTS)', negativeResult: 'MRI-negative epilepsy (normal MRI) - may still be surgical candidate with PET/MEG/SEEG' },",
  "      { test: 'CT Brain (Non-contrast)', purpose: 'Emergency setting: exclude acute pathology (haemorrhage, mass, trauma, hydrocephalus) in first seizure/status epilepticus', timing: 'emergency', sensitivity: 60, specificity: 95, positiveResult: 'Tumour, haemorrhage, calcification (neurocysticercosis), stroke, hydrocephalus, trauma', negativeResult: 'Normal CT does not exclude structural lesion - MRI superior' },",
  "      { test: 'CBC, U&E, Creatinine, Glucose, Calcium, Magnesium, LFTs', purpose: 'Exclude metabolic provocation of seizures (hyponatraemia, hypoglycaemia, hypocalcaemia, hypomagnesaemia, uraemia, hepatic encephalopathy)', timing: 'emergency', positiveResult: 'Hyponatraemia (<125), hypoglycaemia (<3.0), hypocalcaemia (<1.9), hypomagnesaemia (<0.6), elevated Cr/LFT', negativeResult: 'Normal metabolic panel suggests no metabolic trigger' },",
  "      { test: 'ECG (12-lead)', purpose: 'Rule out cardiac arrhythmia (prolonged QT, Brugada, arrhythmia) as cause of seizure-like episodes', timing: 'emergency', sensitivity: 90, specificity: 90, positiveResult: 'Prolonged QTc (>450 ms), Brugada pattern, long QT syndrome, WPW, arrhythmia', negativeResult: 'Normal ECG' },",
  "      { test: 'Neurocysticercosis Serology (Serum + CSF anti-cysticercal antibodies)', purpose: 'Screen for neurocysticercosis (NCC) - leading cause of acquired epilepsy in Sub-Saharan Africa, Latin America, Asia', timing: 'routine', sensitivity: 80, specificity: 95, positiveResult: 'Positive serum EITB (enzyme-linked immunoelectrotransfer blot) for cysticidal antibodies', negativeResult: 'Negative serology does not exclude NCC (particularly if single degenerating cyst)' },",
  "      { test: 'HIV Serology', purpose: 'High prevalence in Kenya; HIV associated with increased epilepsy risk (HIV encephalopathy, opportunistic infections, medication interactions)', timing: 'routine', positiveResult: 'HIV positive: start ART, avoid enzyme-inducing AEDs (interaction with ARVs). Consider CNS toxoplasmosis, TB, cryptococcoma, PML, lymphoma as epilepsy cause.', negativeResult: 'HIV negative' },",
  "      { test: 'Serum Antiepileptic Drug Levels', purpose: 'Monitor therapeutic levels; assess compliance; detect toxicity', timing: 'routine', positiveResult: 'Subtherapeutic (non-adherence, underdosing) or supratherapeutic (toxicity - carbamazepine, phenytoin, valproate)', negativeResult: 'Within therapeutic range' },",
  '    ],',
]);

fs.appendFileSync(p, l.join('\n') + '\n', 'utf8');
console.log('D3 part A written. Size:', fs.statSync(p).size);
