import type { DiseaseIntelligence } from '../core';

export const SURG_DISEASES: DiseaseIntelligence[] = [
  // ─── Large Bowel Obstruction (LBO) — Complete Clinical Module ───────────────
  {
    id: 'large-bowel-obstruction',
    name: 'Large Bowel Obstruction (LBO)',
    specialtyId: 'SURG',
    subspecialtyId: 'general-surgery',
    icd10: 'K56.6',
    epidemiology: {
      incidence: '~15-20% of all intestinal obstructions; 4.8/100,000 in East Africa; accounts for 60% of all colon emergencies',
      prevalence: 'Sigmoid volvulus is the most common cause in Kenya, Ethiopia, and Uganda; incidence increases with age',
      ageDistribution: 'Peak 60-80 years for cancer; 40-60 years for volvulus in Africa; higher in males',
      genderPredilection: 'Male > Female (2:1 for volvulus; 1.2:1 for cancer)',
      geographicDistribution: 'Sigmoid volvulus: East Africa, "volvulus belt" (Kenya, Uganda, Ethiopia, Nigeria). Colorectal cancer: higher in developed nations but rising in LMICs.',
      seasonality: 'No clear seasonality; some studies show increased volvulus during dry seasons (high-fibre harvest)'
    },
    symptomWeights: [
      { symptom: 'abdominal distension', weight: 10, prevalence: 90, category: 'major' },
      { symptom: 'absolute constipation (no stool or flatus)', weight: 10, prevalence: 85, category: 'major' },
      { symptom: 'colicky abdominal pain', weight: 8, prevalence: 80, category: 'major' },
      { symptom: 'vomiting (bilious/faeculent)', weight: 7, prevalence: 60, category: 'major' },
      { symptom: 'failure to pass flatus', weight: 9, prevalence: 85, category: 'major' },
      { symptom: 'abdominal tenderness', weight: 6, prevalence: 65, category: 'minor' },
      { symptom: 'tachycardia', weight: 7, prevalence: 50, category: 'major' },
      { symptom: 'fever', weight: 6, prevalence: 30, category: 'red_flag' },
      { symptom: 'weight loss', weight: 5, prevalence: 25, category: 'minor' },
      { symptom: 'rectal bleeding', weight: 6, prevalence: 15, category: 'red_flag' },
      { symptom: 'previous similar episodes', weight: 7, prevalence: 35, category: 'major' },
      { symptom: 'change in bowel habit', weight: 5, prevalence: 40, category: 'minor' },
      { symptom: 'tenesmus', weight: 4, prevalence: 20, category: 'minor' },
      { symptom: 'dehydration (dry mucosa, reduced turgor)', weight: 6, prevalence: 55, category: 'major' },
      { symptom: 'hypotension', weight: 8, prevalence: 20, category: 'red_flag' },
      { symptom: 'peritonism (guarding/rigidity)', weight: 9, prevalence: 15, category: 'red_flag' },
    ],
    riskFactors: [
      { factor: 'Age >60 years', weight: 3.0, prevalence: 60 },
      { factor: 'Chronic constipation', weight: 2.5, prevalence: 45 },
      { factor: 'High-fibre diet (East African staple)', weight: 2.0, prevalence: 50 },
      { factor: 'Previous episode of volvulus', weight: 4.0, prevalence: 20 },
      { factor: 'Redundant sigmoid colon (anatomical)', weight: 3.5, prevalence: 30 },
      { factor: 'Colorectal cancer history', weight: 3.0, prevalence: 10 },
      { factor: 'Family history of colorectal cancer', weight: 2.5, prevalence: 8 },
      { factor: 'Parkinson disease', weight: 2.0, prevalence: 5 },
      { factor: 'Anticholinergic medications', weight: 1.8, prevalence: 10 },
      { factor: 'Inflammatory bowel disease', weight: 2.2, prevalence: 3 },
      { factor: 'Previous abdominal surgery', weight: 2.0, prevalence: 25 },
      { factor: 'Diverticular disease', weight: 1.8, prevalence: 12 },
      { factor: 'Low socioeconomic status', weight: 1.5, prevalence: 40 },
      { factor: 'Male sex', weight: 1.5, prevalence: 65 },
    ],
    differentials: [
      { disease: 'Sigmoid Volvulus', likelihood: 45, distinguishingFeatures: ['Massive distension out of proportion to pain', 'Coffee bean sign on AXR', 'Previous similar episodes', 'Elderly + chronic constipation', 'High-fibre diet context', 'Empty rectum on DRE'] },
      { disease: 'Colorectal Cancer (obstructing)', likelihood: 25, distinguishingFeatures: ['Gradual onset over weeks', 'Weight loss', 'Rectal bleeding', 'Change in bowel habit', 'Family history of CRC', 'Older age'] },
      { disease: 'Pseudo-obstruction (Ogilvie\'s)', likelihood: 10, distinguishingFeatures: ['No mechanical cause', 'Recent surgery/trauma', 'Bedridden patient', 'Electrolyte imbalance', 'Painless distension', 'No colicky pain'] },
      { disease: 'Caecal Volvulus', likelihood: 8, distinguishingFeatures: ['Right-sided distension', 'Caecal dilation on AXR', 'Coffee bean in RUQ', 'Associated with malrotation'] },
      { disease: 'Diverticulitis', likelihood: 5, distinguishingFeatures: ['Left iliac fossa pain', 'Fever prominent', 'Localised tenderness', 'Abscess may cause partial obstruction'] },
      { disease: 'Acute Pancreatitis', likelihood: 4, distinguishingFeatures: ['Epigastric pain radiating to back', 'Distension is secondary', 'Elevated amylase/lipase', 'Vomiting precedes distension'] },
      { disease: 'Intussusception (adult)', likelihood: 2, distinguishingFeatures: ['Intermittent colicky pain', 'Redcurrant jelly stool', 'Palpable sausage-shaped mass', 'Target lesion on USS'] },
      { disease: 'Hernia (obstructed/strangulated)', likelihood: 3, distinguishingFeatures: ['Visible bulge on examination', 'Previous hernia known', 'Localised pain at hernia site', 'Irreducible + tender'] },
      { disease: 'Adhesive SBO (small bowel)', likelihood: 5, distinguishingFeatures: ['Previous abdominal surgery', 'Central distension', 'Central colicky pain', 'More prominent vomiting', 'Multiple air-fluid levels'] },
    ],
    investigations: [
      { test: 'Abdominal X-ray (erect + supine)', purpose: 'Diagnose bowel obstruction, differentiate large vs small bowel, detect perforation (free air)', timing: 'emergency', sensitivity: 85, specificity: 90, positiveResult: 'Coffee bean sign, bent inner tube sign, colonic dilation >10cm, air-fluid levels, haustra seen', negativeResult: 'Does not exclude early obstruction; CT is more sensitive' },
      { test: 'CT Abdomen + Pelvis with IV contrast', purpose: 'Confirm diagnosis, determine cause, assess for ischemia, guide surgical planning', timing: 'emergency', sensitivity: 95, specificity: 97, positiveResult: 'Transition point, mesenteric swirl sign, bird beak sign, colonic wall thickening, pneumatosis', negativeResult: 'Excludes mechanical obstruction with high confidence' },
      { test: 'Full Blood Count', purpose: 'Assess for leukocytosis, anaemia', timing: 'emergency', positiveResult: 'Elevated WBC suggests infection/ischemia; low Hb may suggest underlying cancer with bleeding', negativeResult: 'Normal WBC does not exclude ischemia' },
      { test: 'Serum Lactate', purpose: 'Detect bowel ischemia and tissue hypoperfusion', timing: 'emergency', positiveResult: '>2 mmol/L suggests early ischemia; >4 mmol/L strongly suggests gangrene', negativeResult: '<2 mmol/L: low likelihood of ischemia but does not exclude' },
      { test: 'Urea and Electrolytes', purpose: 'Assess hydration, renal function, and electrolyte disturbance from vomiting/third-spacing', timing: 'emergency', positiveResult: 'Elevated urea/creatinine (prerenal AKI), hyponatraemia from vomiting', negativeResult: 'Normal values acceptable but do not exclude dehydration' },
      { test: 'CRP', purpose: 'Assess systemic inflammation', timing: 'urgent', positiveResult: 'Elevated >50 suggests significant inflammation; >200 suggests complication', negativeResult: 'Low CRP does not exclude simple obstruction' },
      { test: 'Blood Cultures (2 sets)', purpose: 'Identify bacteraemia if sepsis suspected', timing: 'emergency', sensitivity: 50, specificity: 95, positiveResult: 'Growth guides antibiotic therapy', negativeResult: 'Blood cultures negative in ~50% of bacteraemia' },
      { test: 'Arterial Blood Gas', purpose: 'Assess acid-base status, lactate, and respiratory compromise', timing: 'emergency', positiveResult: 'Metabolic acidosis suggests ischemia; elevated lactate', negativeResult: 'Normal ABG in early stages' },
      { test: 'Crossmatch (Group and Save)', purpose: 'Prepare for potential emergency surgery', timing: 'emergency', positiveResult: 'Identifies blood group for transfusion', negativeResult: 'Normal' },
      { test: 'Coagulation Profile', purpose: 'Pre-operative assessment before surgical intervention', timing: 'urgent', positiveResult: 'Abnormal coagulation may influence operative approach and need for reversal', negativeResult: 'Normal' },
    ],
    imaging: [
      { modality: 'Abdominal X-ray (AXR) — erect and supine', indication: 'First-line imaging for suspected large bowel obstruction', findings: 'Coffee bean sign (sigmoid volvulus), colonic dilation >10cm, air-fluid levels, haustra pattern distinguishing large vs small bowel, absent free air', sensitivity: 85, specificity: 90 },
      { modality: 'CT Abdomen + Pelvis with IV contrast', indication: 'Gold standard — confirm obstruction, identify cause, assess for complications', findings: 'Transition point identifying level of obstruction, mesenteric swirl sign (volvulus), bird beak sign at rectosigmoid junction, colonic wall thickening, pneumatosis intestinalis, free fluid, target lesion (intussusception)', sensitivity: 95, specificity: 97, preparation: 'IV contrast unless contraindicated (eGFR <30)' },
      { modality: 'CT Abdomen without contrast', indication: 'If contraindication to IV contrast or renal failure', findings: 'Transition point, faecal loading pattern, free air, can still identify volvulus signs', sensitivity: 85, specificity: 90, preparation: 'NBM 4 hours' },
      { modality: 'Abdominal Ultrasound', indication: 'Limited role; may help if pregnant or paediatric', findings: 'Dilated colon, thickened walls, free fluid, target sign for intussusception', sensitivity: 50, specificity: 85 },
      { modality: 'Gastrografin Enema', indication: 'If CT unavailable and diagnosis uncertain; also therapeutic for sigmoid volvulus', findings: 'Bird beak sign at obstructed segment; may be therapeutic in volvulus', sensitivity: 90, specificity: 95 },
    ],
    severityCriteria: [
      { criterion: 'Lactate', mild: '<2 mmol/L', moderate: '2-4 mmol/L', severe: '4-6 mmol/L', critical: '>6 mmol/L' },
      { criterion: 'Abdominal Pain', mild: 'Mild colicky, intermittent', moderate: 'Moderate colicky, frequent', severe: 'Severe constant pain (suggests ischemia)', critical: 'Generalised peritonitis' },
      { criterion: 'Distension', mild: 'Mild, patient comfortable', moderate: 'Moderate, uncomfortable', severe: 'Severe, tense, respiratory compromise', critical: 'Tense with diaphragmatic splinting' },
      { criterion: 'Systemic Signs', mild: 'Normal vitals', moderate: 'Tachycardia, dehydration', severe: 'Tachycardia + hypotension, oliguria', critical: 'Septic shock, multi-organ failure' },
      { criterion: 'WBC', mild: '<12', moderate: '12-15', severe: '15-20', critical: '>20 or <4' },
      { criterion: 'Peritoneal Signs', mild: 'None', moderate: 'Mild tenderness', severe: 'Guarding/rebound', critical: 'Rigidity, generalised peritonitis' },
      { criterion: 'Imaging', mild: 'Dilated colon, no air-fluid levels', moderate: 'Air-fluid levels, transition point', severe: 'Pneumatosis intestinalis', critical: 'Free air, portal venous gas' },
    ],
    diagnosticCriteria: [
      { name: 'Clinical Triad', type: 'major', description: 'Abdominal distension + absolute constipation + colicky abdominal pain' },
      { name: 'AXR Signs', type: 'major', description: 'Coffee bean sign or colonic dilation >10cm on abdominal X-ray' },
      { name: 'CT Confirmation', type: 'required', description: 'Transition point with dilated proximal colon and collapsed distal colon on CT abdomen' },
      { name: 'Lactate Elevation', type: 'minor', description: 'Elevated serum lactate suggests ischemia and increases urgency' },
    ],
    treatmentGuidelines: [
      {
        name: 'WSES Guidelines for Large Bowel Obstruction 2024', source: 'World Society of Emergency Surgery', year: 2024,
        firstLine: [
          { drug: 'Crystalloid (Normal Saline or Ringer\'s Lactate)', dose: '30 mL/kg IV bolus, then 125 mL/hr maintenance', route: 'IV', frequency: 'Bolus then continuous', duration: 'Until resuscitation complete', evidenceLevel: 'A' },
          { drug: 'Ceftriaxone', dose: '2 g IV', route: 'IV', frequency: '12-hourly', duration: '3-5 days (peri-operative)', evidenceLevel: 'A' },
          { drug: 'Metronidazole', dose: '500 mg IV', route: 'IV', frequency: '8-hourly', duration: '3-5 days (peri-operative)', evidenceLevel: 'A' },
          { drug: 'Enoxaparin', dose: '40 mg SC', route: 'SC', frequency: 'Daily', duration: '7 days (or until fully mobile)', evidenceLevel: 'A', renalAdjustment: 'Reduce to 20 mg if CrCl <30' },
          { drug: 'Paracetamol', dose: '1 g IV/PO', route: 'IV/PO', frequency: '6-8 hourly PRN', duration: 'As needed', evidenceLevel: 'C', maxDose: '4 g/day' },
          { drug: 'Morphine', dose: '2.5-5 mg IV bolus', route: 'IV', frequency: 'PRN (titrated)', duration: 'Acute pain', evidenceLevel: 'C', maxDose: '20 mg/4h' },
        ],
        stepProtocol: [
          { step: 1, therapy: 'Resuscitation (first 1 hour)', details: 'NBM, large-bore IV access x2, IV crystalloid 30 mL/kg, NG tube on free drainage, urinary catheter, bloods (FBC, U&E, CRP, Lactate, ABG, crossmatch, cultures), analgesia, broad-spectrum IV antibiotics. Call surgical team immediately.', duration: 'Within 1 hour of presentation', monitoring: ['Vitals q15min', 'Urine output hourly', 'Fluid balance chart'], alternatives: ['Warmed fluids if hypothermic'] },
          { step: 2, therapy: 'Diagnostic (within 2 hours)', details: 'Erect + supine AXR. CT abdomen/pelvis with IV contrast (gold standard). If no ischemia/perforation: consider endoscopic decompression for volvulus.', duration: 'Within 2 hours of presentation', monitoring: ['Lactate', 'Pain severity', 'Abdominal girth measurement'] },
          { step: 3, therapy: 'Definitive Management (ischaemic or perforated)', details: 'Emergency laparotomy. Sigmoid colectomy with Hartmann\'s procedure (end colostomy) if gangrenous. Sigmoid resection with primary anastomosis if viable. Abdominal lavage. Pelvic drain.', duration: 'Urgent <6 hours from decision', monitoring: ['Vitals continuous', 'Lactate clearance', 'Urine output'], alternatives: ['Laparoscopic approach if stable and expertise available'] },
          { step: 4, therapy: 'Definitive Management (non-ischaemic volvulus)', details: 'Flexible sigmoidoscopy + detorsion. Insert flatus/rectal tube for 48 hours. Serial AXX to confirm decompression. Bowel preparation over 2 days. Elective sigmoid resection with primary anastomosis in same admission (recurrence rate >50%).', duration: 'Within 12-24 hours', monitoring: ['AXR post-detorsion', 'Vitals', 'Pain'], alternatives: ['Gastrografin enema (diagnostic + therapeutic)'] },
          { step: 5, therapy: 'Pseudo-obstruction (Ogilvie\'s)', details: 'Conservative: NBM, NG tube, correct electrolytes, mobilise. Neostigmine 2 mg IV over 3-5 minutes if no improvement in 24 hours (monitor for bradycardia). Colonoscopic decompression if neostigmine fails.', duration: '24-72 hours', monitoring: ['Serial abdominal girth', 'AXR daily', 'Cardiac monitoring with neostigmine'], alternatives: ['PEG colonoscopic decompression', 'CT-guided percutaneous caecostomy'] },
        ],
        secondLine: [
          { drug: 'Neostigmine', dose: '2 mg IV over 3-5 minutes', route: 'IV', frequency: 'Single dose (may repeat once)', duration: 'For pseudo-obstruction', evidenceLevel: 'B' },
          { drug: 'Noradrenaline', dose: '0.05-0.5 mcg/kg/min IV', route: 'IV', frequency: 'Continuous infusion', duration: 'Until haemodynamic stability', evidenceLevel: 'A', maxDose: '3 mcg/kg/min' },
          { drug: 'Gentamicin', dose: '5-7 mg/kg IV', route: 'IV', frequency: '24-hourly', duration: '3-5 days', evidenceLevel: 'B', renalAdjustment: 'Adjust per level and protocol' },
        ],
        duration: 'Variable: 5-10 days (conservative); 5-7 days (post-op)',
        monitoring: ['Vitals q1h initially', 'Lactate q4-6h', 'Urine output hourly', 'Abdominal girth', 'Pain scores', 'Fluid balance', 'Stoma output (if created)', 'Wound assessment daily'],
      },
    ],
    admissionCriteria: [
      { indications: ['Confirmed large bowel obstruction on imaging', 'Clinical triad of distension + constipation + colicky pain', 'Lactate >2 mmol/L', 'Dehydration requiring IV fluids', 'Inability to tolerate oral intake', 'Significant abdominal pain requiring analgesia', 'Any red flag (fever, tachycardia, hypotension, peritonism)'], level: 'ward', parameters: [{ param: 'Lactate', threshold: '>2 mmol/L' }, { param: 'Distension', threshold: 'Moderate to severe' }, { param: 'Pain', threshold: 'Requiring parenteral analgesia' }] },
      { indications: ['Lactate >4 mmol/L', 'Peritonitis or guarding/rigidity', 'Septic shock (SBP <90 + HR >100)', 'Respiratory compromise from distension', 'Acute kidney injury (creatinine >200)', 'Need for ICU-level monitoring'], level: 'ICU', parameters: [{ param: 'Lactate', threshold: '>4 mmol/L' }, { param: 'SBP', threshold: '<90 mmHg' }, { param: 'Creatinine', threshold: '>200 μmol/L' }] },
    ],
    dischargeCriteria: {
      clinical: ['Tolerating oral diet', 'Pain controlled on oral analgesia', 'Afebrile for 24 hours', 'Stoma functioning (if applicable)', 'Wound healing without signs of infection', 'Passing flatus/stool', 'Independent mobilisation'],
      lab: ['WBC trending down or normal', 'Lactate normalised', 'CRP trending down', 'Creatinine normalised (if AKI)'],
      social: ['Able to care for stoma (or carer available)', 'Able to manage at home', 'Follow-up appointment arranged', 'Stoma supplies provided'],
    },
    complications: [
      { name: 'Bowel Ischaemia/Gangrene', incidence: 15, timeCourse: '6-24 hours from onset', management: 'Emergency laparotomy, resection of non-viable bowel, Hartmann\'s procedure if gangrenous', redFlags: ['Constant pain replacing colicky pattern', 'Lactate rising', 'Acidosis', 'Fever', 'Tachycardia', 'Peritonism'] },
      { name: 'Bowel Perforation', incidence: 5, timeCourse: '12-48 hours from onset', management: 'Emergency laparotomy, peritoneal lavage, resection +/- stoma', redFlags: ['Sudden severe pain', 'Generalised peritonitis', 'Free air on imaging', 'Sepsis', 'Haemodynamic instability'] },
      { name: 'Anastomotic Leak (post-op)', incidence: 5, timeCourse: '3-7 days post-operatively', management: 'Re-operation: peritoneal lavage, takedown of anastomosis, end colostomy (Hartmann\'s)', redFlags: ['Fever day 3-7 post-op', 'Tachycardia', 'Abdominal pain', 'Drain fluid feculent', 'Wound infection', 'Ileus'] },
      { name: 'Wound Infection', incidence: 15, timeCourse: '3-7 days post-op', management: 'Wound opening, packing, culture-directed antibiotics, negative pressure therapy if large', redFlags: ['Wound erythema', 'Purulent discharge', 'Wound pain', 'Fever', 'Wound dehiscence'] },
      { name: 'Stoma Complications', incidence: 20, timeCourse: 'Early (<30 days) and late', management: 'Stoma therapist review, local wound care, surgical revision if necrosis/retraction/stricture', redFlags: ['Stoma becoming dark/purple/black', 'Stoma retraction', 'Parastomal bulge', 'Bleeding from stoma', 'Obstruction at stoma site'] },
      { name: 'Deep Vein Thrombosis / PE', incidence: 3, timeCourse: 'Post-operative; 3-10 days', management: 'Therapeutic anticoagulation, IVC filter if contraindicated', redFlags: ['Unilateral leg swelling', 'Sudden dyspnoea', 'Chest pain', 'Hypoxia'] },
      { name: 'Ileus (prolonged)', incidence: 10, timeCourse: '>5 days post-op', management: 'Continue NG drainage, correct electrolytes, mobilise, prokinetics (metoclopramide), TPN if prolonged >7 days', redFlags: ['Persistent NG output >500 mL/day', 'Absent bowel sounds', 'Abdominal distension', 'Nausea/vomiting'] },
      { name: 'AKI (prerenal)', incidence: 25, timeCourse: 'On admission, resolves with resuscitation', management: 'IV fluids, stop nephrotoxics, monitor urine output and creatinine', redFlags: ['Oliguria <0.5 mL/kg/h', 'Rising creatinine', 'Hyperkalaemia', 'Fluid overload'] },
    ],
    followUp: {
      interval: '1 week (wound check + histology), then 6 weeks (stoma reversal assessment)',
      duration: '3 months to 1 year depending on aetiology',
      tests: ['Histology review (if cancer resected)', 'Colonoscopy (if obstructing cancer, after recovery)', 'Stoma review by therapist', 'Surveillance imaging if cancer (CT at 6, 12, 24 months)'],
      specialistReview: true,
      specialistTiming: 'Surgical clinic at 1 week, 6 weeks; cancer pathway requires MDT discussion',
    },
    prognosis: 'For sigmoid volvulus: excellent if treated before ischemia (mortality <5%). With gangrene: mortality 10-20%. For obstructive cancer: stage-dependent, 5-year survival Stage I 90%, Stage IV <10%. Recurrence rate of volvulus without resection: >50%. AKI resolves in >95% with adequate resuscitation.',
    emergencyFlags: [
      { condition: 'Lactate >4 mmol/L', action: 'Emergency laparotomy within 2 hours', timeCritical: '2 hours' },
      { condition: 'Peritonitis (generalised)', action: 'Emergency laparotomy within 1 hour', timeCritical: '1 hour' },
      { condition: 'Free air on imaging', action: 'Emergency laparotomy within 1 hour', timeCritical: '1 hour' },
      { condition: 'Pneumatosis intestinalis on CT', action: 'Emergency laparotomy within 2 hours', timeCritical: '2 hours' },
      { condition: 'Septic shock', action: 'Resuscitation + emergency laparotomy', timeCritical: '1 hour' },
      { condition: 'Stoma duskiness', action: 'Immediate surgical review — may need revision', timeCritical: '4 hours' },
    ],
    pediatricAdjustments: [
      { parameter: 'Incidence', adjustment: 'LBO is rare in children; consider Hirschsprung disease, intussusception, or congenital bands', ageRange: '0-12' },
      { parameter: 'Management', adjustment: 'Paediatric surgical referral mandatory; fluid resuscitation weight-based', ageRange: '0-12' },
    ],
    pregnancyAdjustments: [
      { trimester: 'first', adjustment: 'CT with contrast is relatively contraindicated; MRI or USS first-line. Surgical approach same but risks to foetus discussed.', safety: 'caution' },
      { trimester: 'second', adjustment: 'Gravid uterus may alter anatomy; CT with contrast after careful risk-benefit; surgical approach same', safety: 'caution' },
      { trimester: 'third', adjustment: 'Gravid uterus displaces colon; high clinical suspicion needed; imaging limited. MDT with obstetrics.', safety: 'caution' },
    ],
    aiReasoning: {
      presentationPattern: ['Elderly patient with sudden massive abdominal distension + absolute constipation + colicky abdominal pain + dehydration'],
      keyFeatures: ['Distension out of proportion to pain (pathognomonic)', 'Empty rectum on DRE', 'Previous similar episodes', 'Coffee bean sign on AXR', 'High-fibre East African diet'],
      discriminatingQuestions: ['Did the distension start suddenly or gradually?', 'Have you passed stool or flatus in the past 3 days?', 'Have you had this before?', 'Have you had any rectal bleeding?', 'Have you lost weight unintentionally?', 'Have you had previous abdominal surgery?', 'Do you have a known hernia?'],
      diagnosticAlgorithm: ['Step 1: Clinical diagnosis (triad)', 'Step 2: Erect + supine AXR (coffee bean sign?)', 'Step 3: CT Abdomen + IV contrast (gold standard — confirm cause)', 'Step 4: Lactate (stratify ischemia risk)', 'Step 5: If ischemic or perforated → emergency laparotomy', 'Step 6: If non-ischemic volvulus → endoscopic detorsion + elective resection', 'Step 7: If pseudo-obstruction → conservative or neostigmine'],
    },
    clinicalNoteTemplate: {
      sections: ['Presenting Complaint', 'History of Presenting Illness', 'Past Medical History', 'Past Surgical History', 'Drug History', 'Allergies', 'Social History', 'Family History', 'Examination (General + Abdominal + DRE)', 'Differential Diagnosis', 'Investigations', 'Imaging', 'Diagnosis', 'Management Plan', 'Operative Note', 'Post-operative Plan', 'Discharge Summary'],
      consultantWording: 'Sir/Madam, RE: [Patient Name] — Large Bowel Obstruction. This [age]-year-old [male/female] presents with a [duration] history of [describe]. Examination reveals [findings]. Investigations show [results]. Based on [CT/AXR findings + lactate], the diagnosis is [specific cause: e.g., sigmoid volvulus, obstructing cancer]. Recommended management: [surgery vs endoscopic vs conservative]. The patient [has/does not have] signs of ischemia and requires [urgency].',
      exampleNote: 'The patient presents with a 3-day history of sudden abdominal distension, absolute constipation, and colicky abdominal pain. Examination: grossly distended, tympanic abdomen, empty rectum. AXR shows coffee bean sign. CT confirms sigmoid volvulus with transition point at rectosigmoid junction. Lactate 2.1. No pneumatosis. Diagnosis: non-ischemic sigmoid volvulus. Plan: flexible sigmoidoscopy + detorsion, flatus tube, then elective sigmoid resection in same admission.',
    },
  },
];
