// ═══════════════════════════════════════════════════════════════════════════════
// AMEXAN ENGINE REGISTRATION — Book XXIV
// Registers every engine in the system into the Engine Registry.
// No imports from engine implementations — only constitutional metadata.
// ═══════════════════════════════════════════════════════════════════════════════

import { engineRegistry } from './engine-registry';
import { ruleRegistry } from './rule-registry';
import { knowledgeRegistry } from './knowledge-registry';
import { workflowRegistry } from './workflow-registry';

export function registerAllEngines(): void {
  engineRegistry.registerBatch([
    // ── Clinical Reasoning ──────────────────────────────────────────────────────
    { engineId: 'encounter_orchestrator', engineName: 'Encounter Orchestrator', category: 'orchestrator', version: '2.0.0', description: '8-State Clinical Interview OS — manages encounter lifecycle from registration through discharge', inputs: ['EncounterState', 'Answer'], outputs: ['AmexanSession', 'NextQuestion', 'HpiNarrative'], dependencies: ['question_engine', 'bayesian_engine', 'narrative_engine'], constitutionalLaws: [1, 2, 3, 4], status: 'active' },
    { engineId: 'bayesian_engine', engineName: 'Bayesian Reasoning Engine', category: 'clinical_reasoning', version: '1.0.0', description: 'Computes differential probability updates from clinical findings using naive Bayes', inputs: ['AnswerPolarity', 'FeatureId'], outputs: ['DdxUpdateResult', 'CandidateDiseaseState'], dependencies: ['knowledge_graph'], constitutionalLaws: [1, 2, 3], status: 'active' },
    { engineId: 'question_engine', engineName: 'Question Engine', category: 'question', version: '1.0.0', description: 'Selects next clinical question based on information gain, safety priority, and clinical round', inputs: ['EncounterState', 'DdxUpdateResult'], outputs: ['NextQuestion'], dependencies: ['bayesian_engine', 'clinical_reasoning_engine'], constitutionalLaws: [1, 2, 3, 4], status: 'active' },
    { engineId: 'clinical_reasoning_engine', engineName: 'Clinical Reasoning Engine', category: 'clinical_reasoning', version: '1.0.0', description: 'Filters differentials by biodata, detects symptom constellations, provides reasoning path', inputs: ['EncounterState', 'DdxUpdateResult'], outputs: ['ClinicalReasoningPath', 'FilteredDifferential', 'SymptomCluster'], dependencies: ['knowledge_graph', 'geographic_priors'], constitutionalLaws: [1, 2, 3], status: 'active' },
    { engineId: 'narrative_engine', engineName: 'Narrative Engine', category: 'clinical_documentation', version: '1.0.0', description: 'Generates HPI narrative from structured clinical data using constitutional templates', inputs: ['EncounterState', 'Answer[]'], outputs: ['HpiNarrative'], dependencies: [], constitutionalLaws: [1, 3, 4], status: 'active' },
    { engineId: 'contradiction_engine', engineName: 'Contradiction Engine', category: 'contradiction', version: '1.0.0', description: 'Detects temporal, anatomical, logical, and severity contradictions in clinical data', inputs: ['EncounterState'], outputs: ['Contradiction[]'], dependencies: [], constitutionalLaws: [1, 2, 3], status: 'active' },
    { engineId: 'clinical_scoring_engine', engineName: 'Clinical Scoring Engine', category: 'clinical_scoring', version: '1.0.0', description: 'Computes clinical scores (CURB-65, Wells, PERC, etc.) from available data', inputs: ['EncounterState', 'FeatureId'], outputs: ['ScoreComputationResult'], dependencies: [], constitutionalLaws: [1, 3], status: 'active' },
    { engineId: 'completeness_engine', engineName: 'Completeness Engine', category: 'completeness', version: '1.0.0', description: 'Measures history completeness across 14 clinical domains', inputs: ['EncounterState'], outputs: ['DomainCompleteness'], dependencies: [], constitutionalLaws: [1, 3], status: 'active' },
    { engineId: 'danger_scoring_engine', engineName: 'Danger Scoring Engine', category: 'danger_scoring', version: '1.0.0', description: 'Ranks differentials by danger level and identifies must-not-miss diagnoses', inputs: ['EncounterState', 'DdxUpdateResult'], outputs: ['DangerRankedDisease[]'], dependencies: ['bayesian_engine', 'knowledge_graph'], constitutionalLaws: [1, 2, 3], status: 'active' },
    { engineId: 'examination_engine', engineName: 'Examination Engine', category: 'examination', version: '1.0.0', description: 'Builds examination plans based on differentials — region-based and systemic signs', inputs: ['FilteredDifferential[]'], outputs: ['ExaminationPlan', 'ExamSign'], dependencies: ['clinical_reasoning_engine', 'knowledge_graph'], constitutionalLaws: [1, 3, 4], status: 'active' },
    { engineId: 'investigation_engine', engineName: 'Investigation Engine', category: 'investigation', version: '1.0.0', description: 'Suggests investigations based on differentials with facility tier awareness', inputs: ['FilteredDifferential[]', 'FacilityTier'], outputs: ['InvestigationPlan', 'SuggestedInvestigation'], dependencies: ['clinical_reasoning_engine', 'knowledge_graph'], constitutionalLaws: [1, 3, 4], status: 'active' },
    { engineId: 'geographic_priors', engineName: 'Geographic Priors Engine', category: 'geographic_prior', version: '1.0.0', description: 'Adjusts disease priors based on geographic region and endemicity', inputs: ['Region', 'DiseaseId'], outputs: ['number'], dependencies: [], constitutionalLaws: [1, 3], status: 'active' },
    { engineId: 'priority_scorer', engineName: 'Priority Scorer', category: 'clinical_scoring', version: '1.0.0', description: 'Computes composite priority scores for questions: diagnostic + safety + documentation value', inputs: ['FeatureId', 'EncounterState'], outputs: ['PriorityScore'], dependencies: [], constitutionalLaws: [1, 3], status: 'active' },

    // ── Presentation ────────────────────────────────────────────────────────────
    { engineId: 'presentation_engine', engineName: 'Presentation Engine', category: 'presentation', version: '1.0.0', description: 'Converts EngineState into declarative PresentationScreen with sections, cards, navigation, warnings', inputs: ['EngineState'], outputs: ['PresentationOutput', 'PresentationScreen'], dependencies: ['experience_engine'], constitutionalLaws: [1, 4], status: 'active' },
    { engineId: 'experience_engine', engineName: 'Experience Engine', category: 'experience', version: '1.0.0', description: 'Per-actor journey routing — same reasoning, different experience per role', inputs: ['ExperienceRequest'], outputs: ['ExperienceOutput', 'RoutingDecision'], dependencies: ['constitution_book_ii'], constitutionalLaws: [1, 4], status: 'active' },
    { engineId: 'theme_engine', engineName: 'Theme Engine', category: 'theme', version: '1.0.0', description: 'Role-specific color themes, branding, CSS variable generation', inputs: ['BrandConfig', 'ActorId'], outputs: ['ThemeContext'], dependencies: [], constitutionalLaws: [4], status: 'active' },

    // ── Knowledge ───────────────────────────────────────────────────────────────
    { engineId: 'knowledge_yaml_parser', engineName: 'Knowledge YAML Parser', category: 'knowledge_compiler', version: '1.0.0', description: 'Parses YAML medical knowledge packages into typed KnowledgePackage objects', inputs: ['string (YAML)'], outputs: ['KnowledgePackage'], dependencies: [], constitutionalLaws: [3, 4], status: 'active' },
    { engineId: 'knowledge_package_registry', engineName: 'Knowledge Package Registry', category: 'knowledge_compiler', version: '1.0.0', description: 'Multi-index registry for searching knowledge by ID, disease, symptom, object type, free text', inputs: ['KnowledgePackage'], outputs: ['CompilationResult'], dependencies: ['knowledge_yaml_parser'], constitutionalLaws: [3, 4], status: 'active' },
    { engineId: 'knowledge_graph', engineName: 'Knowledge Graph', category: 'knowledge_graph', version: '1.0.0', description: 'Queryable graph with 3-path traversal for differentials, investigations, treatments, complications', inputs: ['KnowledgePackage[]'], outputs: ['GraphNode[]', 'KnowledgePath'], dependencies: ['knowledge_package_registry'], constitutionalLaws: [3, 4], status: 'active' },
    { engineId: 'knowledge_integration', engineName: 'Knowledge Integration', category: 'knowledge_integration', version: '1.0.0', description: 'Returns full clinical context: differentials, red flags, investigations, treatments, teaching from symptoms+diagnoses', inputs: ['string[] (symptoms)', 'string[] (diagnoses)'], outputs: ['FullContext'], dependencies: ['knowledge_graph'], constitutionalLaws: [3, 4], status: 'active' },

    // ── Enterprise ──────────────────────────────────────────────────────────────
    { engineId: 'business_constitution', engineName: 'Business Constitution', category: 'business_constitution', version: '1.0.0', description: 'Business Constitution — customers, products, plans, pricing, regions, taxes, discounts', inputs: ['PlanId', 'ProductId[]', 'RegionCode'], outputs: ['PriceQuote'], dependencies: [], constitutionalLaws: [4], status: 'active' },
    { engineId: 'licensing_engine', engineName: 'Licensing Engine', category: 'enterprise_licensing', version: '1.0.0', description: 'License generation, validation, module access control, API metering', inputs: ['Subscription'], outputs: ['License', 'LicenseValidation'], dependencies: ['business_constitution'], constitutionalLaws: [4], status: 'active' },
    { engineId: 'billing_engine', engineName: 'Billing Engine', category: 'enterprise_billing', version: '1.0.0', description: 'Invoice creation, subscription lifecycle, MRR/ARR estimation', inputs: ['Subscription', 'Date'], outputs: ['Invoice', 'Subscription'], dependencies: ['business_constitution'], constitutionalLaws: [4], status: 'active' },
    { engineId: 'marketplace_engine', engineName: 'Marketplace Engine', category: 'enterprise_marketplace', version: '1.0.0', description: 'Extension registry, search, install/uninstall/config/usage tracking, catalog stats', inputs: ['MarketplaceExtension'], outputs: ['InstalledExtension'], dependencies: [], constitutionalLaws: [4], status: 'active' },
    { engineId: 'customer_success_engine', engineName: 'Customer Success Engine', category: 'enterprise_customer_success', version: '1.0.0', description: 'Health scores, feature adoption, deployment progress, churn prediction', inputs: ['Organization', 'Subscription'], outputs: ['CustomerHealthScore', 'FeatureAdoption[]', 'DeploymentProgress'], dependencies: ['business_constitution'], constitutionalLaws: [4], status: 'active' },
    { engineId: 'admin_dashboard_engine', engineName: 'Admin Dashboard Engine', category: 'enterprise_admin', version: '1.0.0', description: 'Sales, financial, infrastructure, growth dashboards, at-risk customer identification', inputs: ['Subscription[]', 'Organization[]'], outputs: ['SalesDashboard', 'FinancialDashboard', 'InfrastructureDashboard', 'GrowthMetrics'], dependencies: [], constitutionalLaws: [4], status: 'active' },
    { engineId: 'white_label_engine', engineName: 'White Label Engine', category: 'enterprise_white_label', version: '1.0.0', description: 'Tenant branding, CSS variables, domain config, language packs, locale formatting', inputs: ['TenantSettings'], outputs: ['BrandingPackage', 'Record<string,string>'], dependencies: [], constitutionalLaws: [4], status: 'active' },
    { engineId: 'security_engine', engineName: 'Security & Compliance Engine', category: 'enterprise_security', version: '1.0.0', description: 'Audit logging, enterprise RBAC, compliance frameworks (HIPAA/GDPR/Kenya), security policies', inputs: ['AuditLogEntry'], outputs: ['AuditLogEntry', 'ComplianceReport'], dependencies: ['business_constitution'], constitutionalLaws: [4], status: 'active' },
    { engineId: 'multi_tenant_engine', engineName: 'Multi-Tenant Engine', category: 'enterprise_multi_tenant', version: '1.0.0', description: 'Tenant provisioning, domain routing, isolation models, resource quotas', inputs: ['Organization', 'RegionCode'], outputs: ['Tenant', 'TenantResourceQuota'], dependencies: ['business_constitution'], constitutionalLaws: [4], status: 'active' },
    { engineId: 'support_engine', engineName: 'Support Engine', category: 'enterprise_support', version: '1.0.0', description: 'Ticket system, SLA definitions, knowledge base, escalation management', inputs: ['SupportTicket'], outputs: ['SupportTicket', 'SLADefinition'], dependencies: ['business_constitution'], constitutionalLaws: [4], status: 'active' },
    { engineId: 'growth_engine', engineName: 'Growth & Partner Engine', category: 'enterprise_growth', version: '1.0.0', description: 'Partner tiers, commissions, referral pipeline, partner metrics dashboard', inputs: ['Partner'], outputs: ['Partner', 'PartnerMetrics'], dependencies: [], constitutionalLaws: [4], status: 'active' },
    { engineId: 'plugin_engine', engineName: 'Plugin Engine', category: 'enterprise_plugin', version: '1.0.0', description: 'Developer registration, plugin manifest management, versioning, marketplace stats', inputs: ['PluginManifest'], outputs: ['PluginManifest', 'DeveloperRegistration'], dependencies: [], constitutionalLaws: [4], status: 'active' },
    { engineId: 'deployment_engine', engineName: 'Deployment Engine', category: 'enterprise_deployment', version: '1.0.0', description: 'Implementation project workflow: 8 phases with tasks, blockers, milestones, health tracking', inputs: ['Organization', 'Facility[]'], outputs: ['ImplementationProject'], dependencies: ['business_constitution'], constitutionalLaws: [4], status: 'active' },
    { engineId: 'analytics_engine', engineName: 'Analytics Engine', category: 'enterprise_analytics', version: '1.0.0', description: 'Cross-customer medical analytics, disease trends, outbreak detection, benchmarking', inputs: ['DiseaseTrend', 'OutbreakAlert'], outputs: ['AnalyticsReport', 'OutbreakAlert[]'], dependencies: [], constitutionalLaws: [4], status: 'active' },

    // ── AGOC Infrastructure ────────────────────────────────────────────────────
    { engineId: 'telemetry_broker', engineName: 'Telemetry Broker', category: 'constitutional_validation', version: '1.0.0', description: 'Universal Engine Event bus — engines emit without knowing AGOC exists', inputs: ['UniversalEngineEvent'], outputs: ['UniversalEngineEvent'], dependencies: [], constitutionalLaws: [1, 2, 3, 4, 5], status: 'active' },
    { engineId: 'oi_database', engineName: 'Operating Intelligence Database', category: 'constitutional_validation', version: '1.0.0', description: 'Separate database for engine events, rule activations, performance, health — no patient data', inputs: ['UniversalEngineEvent'], outputs: ['OIStore'], dependencies: ['telemetry_broker'], constitutionalLaws: [1, 2, 4], status: 'active' },
    { engineId: 'engine_registry', engineName: 'Engine Registry', category: 'constitutional_validation', version: '1.0.0', description: 'Constitutional catalog of every engine: versions, inputs, outputs, dependencies', inputs: ['EngineRegistration'], outputs: ['EngineRegistration[]'], dependencies: [], constitutionalLaws: [3, 4], status: 'active' },
    { engineId: 'rule_registry', engineName: 'Rule Registry', category: 'constitutional_validation', version: '1.0.0', description: 'Central catalog of every rule: visibility, activation, priority, safety, contraindication', inputs: ['RuleRegistration'], outputs: ['RuleRegistration[]'], dependencies: [], constitutionalLaws: [3, 4], status: 'active' },
    { engineId: 'knowledge_registry_agoc', engineName: 'Knowledge Registry (AGOC)', category: 'constitutional_validation', version: '1.0.0', description: 'Versioned knowledge package tracking with approval gates and supersession', inputs: ['KnowledgePackageRecord'], outputs: ['KnowledgePackageRecord[]'], dependencies: ['knowledge_package_registry'], constitutionalLaws: [3, 4], status: 'active' },
    { engineId: 'workflow_registry', engineName: 'Workflow Registry', category: 'constitutional_validation', version: '1.0.0', description: 'Catalog of all workflows with expected phases, durations, analytics, bottleneck detection', inputs: ['WorkflowRegistration'], outputs: ['WorkflowAnalytics'], dependencies: [], constitutionalLaws: [3, 4], status: 'active' },
    { engineId: 'engine_health_registry', engineName: 'Engine Health Registry', category: 'constitutional_validation', version: '1.0.0', description: 'Health tracking: execution stats, error rates, latency, status monitoring, alerts', inputs: ['EngineExecution'], outputs: ['EngineHealthRecord', 'EngineHealthAlert'], dependencies: ['oi_database'], constitutionalLaws: [1, 2, 4], status: 'active' },

    // ── Workspace Resolution (Book XV) ────────────────────────────────────────
    { engineId: 'workspace_resolution_engine', engineName: 'Workspace Resolution Engine', category: 'workspace_resolution', version: '1.0.0', description: 'Constitutional completeness gate — decides whether an authenticated actor may reach a dashboard, and performs gap analysis to route incomplete workspaces to guided onboarding (CR-WS-001, WS-001..WS-010)', inputs: ['ResolvedWorkspace'], outputs: ['WorkspaceResolutionDecision'], dependencies: ['workspace_engine', 'rule_registry'], constitutionalLaws: [1, 4], status: 'active' },

    // ── Software Engineering Governance (Book XVI — SC-1) ──────────────────────
    { engineId: 'software_engineering_governance_engine', engineName: 'Software Engineering Governance Engine', category: 'software_engineering', version: '1.0.0', description: 'Constitutional governance of the codebase — layer isolation, bounded contribution, test gates, design tokens, observability, engineering permissions (CR-SC-001, SC-001..SC-015)', inputs: ['EngineeringAudit'], outputs: ['EngineeringGovernanceDecision'], dependencies: ['rule_registry'], constitutionalLaws: [3, 4], status: 'active' },

    // ── Knowledge Intelligence (Book XVII — KI-1) ──────────────────────────────
    { engineId: 'knowledge_intelligence_engine', engineName: 'Knowledge Intelligence Engine', category: 'knowledge_intelligence', version: '1.0.0', description: 'Constitutional intelligence pipeline — context-mandatory, explainable reasoning, evidence traceability, layered intelligence, reflection (CR-KI-001, KI-001..KI-011)', inputs: ['ReasoningRequest'], outputs: ['ReasoningResult'], dependencies: ['knowledge_graph', 'rule_registry'], constitutionalLaws: [1, 3], status: 'active' },

    // ── Knowledge Ecosystem (Book XVIII — KE-1) ────────────────────────────────
    { engineId: 'knowledge_ecosystem_engine', engineName: 'Knowledge Ecosystem Engine', category: 'knowledge_ecosystem', version: '1.0.0', description: 'Constitutional knowledge ecosystem — living knowledge base, guideline builder and layering, adaptive education, multi-output publishing, provenance preservation (CR-KE-001, KE-001..KE-012)', inputs: ['KnowledgeEcosystemRequest'], outputs: ['KnowledgeEcosystemResult'], dependencies: ['knowledge_graph', 'rule_registry'], constitutionalLaws: [3, 4], status: 'active' },

    // ── Healthcare Community (Book XIX — HC-1) ─────────────────────────────────
    { engineId: 'healthcare_community_engine', engineName: 'Healthcare Community Engine', category: 'healthcare_community', version: '1.0.0', description: 'Constitutional community — community objects, layered communities, verified identity, knowledge-driven feed, constitutional moderation; never optimizes for engagement (CR-HC-001, HC-001..HC-015)', inputs: ['CommunityInteraction'], outputs: ['CommunityDecision'], dependencies: ['rule_registry'], constitutionalLaws: [1, 4], status: 'active' },
  ]);
}

export function registerAllWorkflows(): void {
  workflowRegistry.registerBatch([
    {
      workflowId: 'clinical_care_default', workflowName: 'Clinical Care — Default', journeyId: 'clinical_care',
      expectedPhases: ['registration', 'triage', 'history', 'examination', 'investigation', 'diagnosis', 'management', 'discharge'],
      expectedDurationPerPhase: { registration: 120000, triage: 180000, history: 600000, examination: 300000, investigation: 300000, diagnosis: 120000, management: 240000, discharge: 180000 },
      expectedTotalDuration: 2040000, actorTypes: ['doctor', 'resident', 'consultant', 'nurse'], version: '1.0.0', status: 'active',
    },
    {
      workflowId: 'nursing_care_default', workflowName: 'Nursing Care — Default', journeyId: 'nursing_care',
      expectedPhases: ['shift_handover', 'patient_round', 'medication_admin', 'vital_signs', 'fluid_chart', 'care_plan', 'documentation', 'handover'],
      expectedDurationPerPhase: { shift_handover: 600000, patient_round: 1200000, medication_admin: 600000, vital_signs: 180000, fluid_chart: 120000, care_plan: 180000, documentation: 300000, handover: 600000 },
      expectedTotalDuration: 3780000, actorTypes: ['nurse', 'midwife', 'student'], version: '1.0.0', status: 'active',
    },
    {
      workflowId: 'patient_portal_default', workflowName: 'Patient Portal', journeyId: 'patient_portal',
      expectedPhases: ['dashboard', 'appointments', 'medications', 'results', 'billing', 'messages', 'education'],
      expectedDurationPerPhase: { dashboard: 60000, appointments: 120000, medications: 60000, results: 120000, billing: 120000, messages: 180000, education: 300000 },
      expectedTotalDuration: 960000, actorTypes: ['patient', 'family_member'], version: '1.0.0', status: 'active',
    },
    {
      workflowId: 'telemedicine_default', workflowName: 'Telemedicine Encounter', journeyId: 'telemedicine',
      expectedPhases: ['waiting_room', 'video_consult', 'history', 'examination', 'prescription', 'follow_up', 'documentation'],
      expectedDurationPerPhase: { waiting_room: 120000, video_consult: 900000, history: 300000, examination: 120000, prescription: 120000, follow_up: 60000, documentation: 240000 },
      expectedTotalDuration: 1860000, actorTypes: ['doctor', 'patient'], version: '1.0.0', status: 'active',
    },
    {
      workflowId: 'pharmacy_default', workflowName: 'Pharmacy Workflow', journeyId: 'pharmacy',
      expectedPhases: ['prescription_review', 'dispensing', 'counselling', 'documentation', 'inventory_check'],
      expectedDurationPerPhase: { prescription_review: 120000, dispensing: 180000, counselling: 300000, documentation: 120000, inventory_check: 60000 },
      expectedTotalDuration: 780000, actorTypes: ['pharmacist'], version: '1.0.0', status: 'active',
    },
    {
      workflowId: 'laboratory_default', workflowName: 'Laboratory Workflow', journeyId: 'laboratory',
      expectedPhases: ['order_receipt', 'sample_collection', 'sample_processing', 'analysis', 'validation', 'result_reporting'],
      expectedDurationPerPhase: { order_receipt: 60000, sample_collection: 300000, sample_processing: 600000, analysis: 1200000, validation: 120000, result_reporting: 60000 },
      expectedTotalDuration: 2340000, actorTypes: ['lab_technician'], version: '1.0.0', status: 'active',
    },
    {
      workflowId: 'radiology_default', workflowName: 'Radiology Workflow', journeyId: 'radiology',
      expectedPhases: ['order_review', 'scheduling', 'imaging', 'interpretation', 'reporting', 'consultation'],
      expectedDurationPerPhase: { order_review: 60000, scheduling: 120000, imaging: 600000, interpretation: 600000, reporting: 300000, consultation: 180000 },
      expectedTotalDuration: 1860000, actorTypes: ['radiologist'], version: '1.0.0', status: 'active',
    },
    {
      workflowId: 'learning_default', workflowName: 'Clinical Learning Workflow', journeyId: 'learning',
      expectedPhases: ['case_assignment', 'history_review', 'differential_formulation', 'reasoning_comparison', 'feedback', 'knowledge_review', 'quiz'],
      expectedDurationPerPhase: { case_assignment: 30000, history_review: 300000, differential_formulation: 300000, reasoning_comparison: 180000, feedback: 300000, knowledge_review: 600000, quiz: 300000 },
      expectedTotalDuration: 2010000, actorTypes: ['student', 'educator'], version: '1.0.0', status: 'active',
    },
  ]);
}

export function registerAllRules(): void {
  ruleRegistry.registerBatch([
    // Safety rules
    { ruleId: 'R_SAF_001', ruleName: 'Pregnancy ACE Inhibitor Contraindication', engineId: 'clinical_reasoning_engine', category: 'safety', description: 'Block ACE inhibitors in pregnant patients', conditions: 'patient.gender === female && patient.ageGroup === adult && encounter.pregnancy === true && featureId === ACE_INHIBITOR', effect: 'visibility = false; warning = "Contraindicated in pregnancy"', version: '1.0.0', status: 'active' },
    { ruleId: 'R_SAF_002', ruleName: 'Pediatric Aspirin Contraindication', engineId: 'clinical_reasoning_engine', category: 'safety', description: 'Block aspirin in pediatric patients due to Reye syndrome risk', conditions: 'patient.ageGroup === child && featureId === ASPIRIN', effect: 'visibility = false; warning = "Contraindicated in children (Reye syndrome risk)"', version: '1.0.0', status: 'active' },
    { ruleId: 'R_SAF_003', ruleName: 'Red Flag Critical Prioritization', engineId: 'question_engine', category: 'priority', description: 'Red flag questions always get priority 1 regardless of information gain', conditions: 'feature.tags includes "red_flag"', effect: 'priority = 1', version: '1.0.0', status: 'active' },
    { ruleId: 'R_SAF_004', ruleName: 'Danger Score Immediate Action', engineId: 'danger_scoring_engine', category: 'safety', description: 'Any disease with dangerScore > 90 triggers immediate action alert', conditions: 'candidate.dangerScore > 90', effect: 'alert = "immediate"; actionMessage = "URGENT: Immediate clinical evaluation required"', version: '1.0.0', status: 'active' },
    { ruleId: 'R_SAF_005', ruleName: 'Must-Not-Miss Never Hidden', engineId: 'presentation_engine', category: 'visibility', description: 'Must-not-miss diagnoses cannot be hidden from the differential list', conditions: 'card.type === differential_list && disease.tags includes "must_not_miss"', effect: 'visible = true; enabled = true', version: '1.0.0', status: 'active' },
    { ruleId: 'R_SAF_006', ruleName: 'Investigation Urgency Override', engineId: 'investigation_engine', category: 'priority', description: 'Immediate investigations always appear before routine ones', conditions: 'investigation.urgency === immediate', effect: 'priority = 1', version: '1.0.0', status: 'active' },
    
    // Visibility rules
    { ruleId: 'R_VIS_001', ruleName: 'Gender-Specific Examination Visibility', engineId: 'examination_engine', category: 'visibility', description: 'Show gender-specific exams only for matching patient gender', conditions: 'exam.genderRestricted && exam.genderRestricted !== patient.gender', effect: 'visible = false', version: '1.0.0', status: 'active' },
    { ruleId: 'R_VIS_002', ruleName: 'Pediatric Examination Modification', engineId: 'examination_engine', category: 'context', description: 'Modify examination plan for pediatric patients', conditions: 'patient.ageGroup === child || patient.ageGroup === infant', effect: 'include pediatric-specific signs; exclude invasive exams', version: '1.0.0', status: 'active' },
    { ruleId: 'R_VIS_003', ruleName: 'Facility Tier Investigation Filter', engineId: 'investigation_engine', category: 'context', description: 'Only show investigations available at the facility\'s tier', conditions: 'investigation.tier > facility.tier', effect: 'visible = false; note = "Refer to higher facility"', version: '1.0.0', status: 'active' },
    
    // Activation rules
    { ruleId: 'R_ACT_001', ruleName: 'Chest Pain Activates Cardiac Workflow', engineId: 'encounter_orchestrator', category: 'activation', description: 'Chest pain chief complaint activates cardiac reasoning highway', conditions: 'chiefComplaint includes "chest" && chiefComplaint includes "pain"', effect: 'activateHighway("cardiac"); setConvergencePhase("acs_rule_out")', version: '1.0.0', status: 'active' },
    { ruleId: 'R_ACT_002', ruleName: 'Fever Activates Infection Workflow', engineId: 'encounter_orchestrator', category: 'activation', description: 'Fever as presenting symptom activates infection highway', conditions: 'chiefComplaint includes "fever"', effect: 'activateHighway("infection")', version: '1.0.0', status: 'active' },
    { ruleId: 'R_ACT_003', ruleName: 'Trauma Activates Trauma Workflow', engineId: 'encounter_orchestrator', category: 'activation', description: 'Trauma chief complaint activates trauma highway with primary/secondary survey', conditions: 'chiefComplaint includes "trauma" || chiefComplaint includes "injury" || chiefComplaint includes "accident"', effect: 'activateHighway("trauma"); setPhase("primary_survey")', version: '1.0.0', status: 'active' },
    
    // Ordering rules
    { ruleId: 'R_ORD_001', ruleName: 'History Before Examination', engineId: 'encounter_orchestrator', category: 'ordering', description: 'History questions must precede examination in clinical sequence', conditions: 'currentPhase === examination && any(historyCompleteness.domains, d => d < 0.5)', effect: 'block = true; redirect = "Complete history first"', version: '1.0.0', status: 'active' },
    { ruleId: 'R_ORD_002', ruleName: 'Examination Before Investigation', engineId: 'encounter_orchestrator', category: 'ordering', description: 'Physical examination should precede investigations in non-emergency', conditions: 'currentPhase === investigation && encounter.isEmergency === false && examinationCompletion < 0.3', effect: 'warning = "Consider completing examination first"; softBlock = true', version: '1.0.0', status: 'active' },
    { ruleId: 'R_ORD_003', ruleName: 'Red Flags Before Routine Questions', engineId: 'question_engine', category: 'ordering', description: 'Red flag questions must be asked before routine clinical questions', conditions: 'hasOutstandingRedFlags() && current priority === 3', effect: 'override = true; inject red flag questions at priority 1', version: '1.0.0', status: 'active' },
    { ruleId: 'R_ORD_004', ruleName: 'Pediatric Fever Sepsis Screening', engineId: 'question_engine', category: 'ordering', description: 'In pediatric fever, sepsis red flags must be assessed first', conditions: 'patient.ageGroup === child && feature === FEVER && hasOutstandingRedFlags("sepsis")', effect: 'injectFeature("SEPSIS_RED_FLAGS", 0)', version: '1.0.0', status: 'active' },
    
    // Contraindication rules
    { ruleId: 'R_CTX_001', ruleName: 'Metformin Contrast Contraindication', engineId: 'clinical_reasoning_engine', category: 'contraindication', description: 'Check metformin use before ordering contrast imaging', conditions: 'investigation.type === imaging && investigation.contrast === true && medication.includes("metformin")', effect: 'warning = "Hold metformin 48h before contrast"; safetyCheck = true', version: '1.0.0', status: 'active' },
    { ruleId: 'R_CTX_002', ruleName: 'Pregnancy Imaging Radiation Caution', engineId: 'clinical_reasoning_engine', category: 'contraindication', description: 'Caution for radiation-based imaging in pregnancy', conditions: 'patient.gender === female && encounter.pregnancy === true && investigation.radiation === true', effect: 'warning = "Consider non-radiation alternative"; addCheck("beta_hcg")', version: '1.0.0', status: 'active' },

    // ── Workspace Resolution rules (Book XV — CR-WS-001, WS-001..WS-010) ─────
    { ruleId: 'CR-WS-001', ruleName: 'No Dashboard Before a Valid Workspace', engineId: 'workspace_resolution_engine', category: 'activation', description: 'No authenticated user shall ever land on a dashboard before a valid Workspace has been resolved. The dashboard only renders an already-resolved workspace.', conditions: 'authentication === authenticated && workspace === undefined', effect: 'block = true; route = "/register/constitution"; reason = "Workspace not resolved"', version: '1.0.0', status: 'active' },
    { ruleId: 'WS-001', ruleName: 'Dashboard Requires Resolved Workspace', engineId: 'workspace_resolution_engine', category: 'activation', description: 'The dashboard may only render when a valid Workspace has been resolved', conditions: 'target === dashboard', effect: 'require = "resolvedWorkspace"', version: '1.0.0', status: 'active' },
    { ruleId: 'WS-002', ruleName: 'Incomplete Workspace Launches Onboarding', engineId: 'workspace_resolution_engine', category: 'activation', description: 'Incomplete workspace launches guided onboarding instead of a dashboard fallback', conditions: 'workspace.isComplete === false', effect: 'route = "/register/constitution"; nextStep = resolveNextStep(missing)', version: '1.0.0', status: 'active' },
    { ruleId: 'WS-003', ruleName: 'Profession Precedes Role', engineId: 'workspace_resolution_engine', category: 'ordering', description: 'A professional identity must exist before any role is assigned', conditions: 'role !== undefined && professional === undefined', effect: 'require = "professional"; step = "professional"', version: '1.0.0', status: 'active' },
    { ruleId: 'WS-004', ruleName: 'Membership Precedes Employment', engineId: 'workspace_resolution_engine', category: 'ordering', description: 'An actor must belong to an organization before employment may be recorded', conditions: 'employment !== undefined && membership === undefined', effect: 'require = "membership"; step = "organization_choice"', version: '1.0.0', status: 'active' },
    { ruleId: 'WS-005', ruleName: 'Employment Precedes Assignment', engineId: 'workspace_resolution_engine', category: 'ordering', description: 'An active employment must exist before an assignment is created', conditions: 'assignment !== undefined && employment === undefined', effect: 'require = "employment"; step = "assignment"', version: '1.0.0', status: 'active' },
    { ruleId: 'WS-006', ruleName: 'Assignment Determines Dashboard', engineId: 'workspace_resolution_engine', category: 'ordering', description: 'The active assignment selects the dashboard layout', conditions: 'assignment !== undefined', effect: 'dashboard = resolveDashboard(assignment.type)', version: '1.0.0', status: 'active' },
    { ruleId: 'WS-007', ruleName: 'Dashboard Determines Navigation', engineId: 'workspace_resolution_engine', category: 'ordering', description: 'The resolved dashboard determines the navigation tree', conditions: 'dashboard !== undefined', effect: 'navigation = resolveNavigation(dashboard)', version: '1.0.0', status: 'active' },
    { ruleId: 'WS-008', ruleName: 'Navigation Determines Permissions', engineId: 'workspace_resolution_engine', category: 'ordering', description: 'The navigation tree constrains the permissions surface', conditions: 'navigation !== undefined', effect: 'permissions = derive(navigation)', version: '1.0.0', status: 'active' },
    { ruleId: 'WS-009', ruleName: 'Multiple Workspaces Per Actor', engineId: 'workspace_resolution_engine', category: 'visibility', description: 'An actor may own multiple workspaces; a switcher must be available', conditions: 'memberships.length > 1', effect: 'show = "workspaceSwitcher"', version: '1.0.0', status: 'active' },
    { ruleId: 'WS-010', ruleName: 'Workspace Switching Requires No Re-Authentication', engineId: 'workspace_resolution_engine', category: 'visibility', description: 'Switching workspaces never requires re-authentication', conditions: 'event === workspace_switch', effect: 'allow = true', version: '1.0.0', status: 'active' },

    // ── Software Engineering Governance rules (Book XVI — SC-1) ────────────────
    { ruleId: 'CR-SC-001', ruleName: 'Frontend Is an Untrusted Presentation Layer', engineId: 'software_engineering_governance_engine', category: 'security', description: 'The frontend is an untrusted presentation layer — render, collect, and display only. No sensitive logic (permissions, pricing, rules, clinical decisions, role decisions, tokens, secrets, business logic) may ever live in frontend code.', conditions: 'target === frontend && logic.type in [permission, pricing, rule, clinical_decision, role_decision, token, secret, business_logic]', effect: 'block = true; mandate = "backend only"', version: '1.0.0', status: 'active' },
    { ruleId: 'SC-001', ruleName: 'Bounded Contribution', engineId: 'software_engineering_governance_engine', category: 'architecture', description: 'Each feature shall contribute to a single bounded context; no hidden shared coupling between contexts', conditions: 'feature.crossesContexts > 1', effect: 'warn = true; require = "single context ownership"', version: '1.0.0', status: 'active' },
    { ruleId: 'SC-002', ruleName: 'Public Interface Only', engineId: 'software_engineering_governance_engine', category: 'architecture', description: 'Cross-boundary access happens only through explicit public interfaces', conditions: 'access.crossesBoundary && interface === undefined', effect: 'block = true; require = "public interface"', version: '1.0.0', status: 'active' },
    { ruleId: 'SC-003', ruleName: 'Contracts Only', engineId: 'software_engineering_governance_engine', category: 'architecture', description: 'Boundaries communicate only through typed contracts, never shared mutable state', conditions: 'boundary.communication && contract === undefined', effect: 'block = true; require = "typed contract"', version: '1.0.0', status: 'active' },
    { ruleId: 'SC-004', ruleName: 'No Private Imports', engineId: 'software_engineering_governance_engine', category: 'architecture', description: 'No module may import the private internals of another module — public API only', conditions: 'import.path includes "internal" || import.path includes "private"', effect: 'block = true', version: '1.0.0', status: 'active' },
    { ruleId: 'SC-005', ruleName: 'Independent Deployability', engineId: 'software_engineering_governance_engine', category: 'architecture', description: 'Each bounded context shall be independently deployable', conditions: 'deploy.couplesContexts === true', effect: 'warn = true', version: '1.0.0', status: 'active' },
    { ruleId: 'SC-006', ruleName: 'Layer Isolation', engineId: 'software_engineering_governance_engine', category: 'architecture', description: 'Presentation, application, domain, and infrastructure layers must not bypass one another', conditions: 'layer === presentation && accesses === domain/infrastructure directly', effect: 'block = true; route = "through application layer"', version: '1.0.0', status: 'active' },
    { ruleId: 'SC-007', ruleName: 'Feature-Based Architecture', engineId: 'software_engineering_governance_engine', category: 'architecture', description: 'Code is organized by feature, not by technical layer folders', conditions: 'structure === technical_layers', effect: 'warn = true; require = "feature folders"', version: '1.0.0', status: 'active' },
    { ruleId: 'SC-008', ruleName: 'Teams Own Domains', engineId: 'software_engineering_governance_engine', category: 'ownership', description: 'Every domain is owned by exactly one team', conditions: 'domain.owners.length > 1', effect: 'block = true; require = "single owner"', version: '1.0.0', status: 'active' },
    { ruleId: 'SC-009', ruleName: 'No Shared Chaos', engineId: 'software_engineering_governance_engine', category: 'ownership', description: 'No shared utility folders without explicit governance — shared code is a living interface with a defined owner', conditions: 'folder.name includes "shared" && folder.owner === undefined', effect: 'block = true; require = "owner + contract"', version: '1.0.0', status: 'active' },
    { ruleId: 'SC-010', ruleName: 'Code Ownership', engineId: 'software_engineering_governance_engine', category: 'ownership', description: 'Every file has a named code owner; CODEOWNERS is mandatory', conditions: 'file.codeowner === undefined', effect: 'block = true', version: '1.0.0', status: 'active' },
    { ruleId: 'SC-011', ruleName: 'Mandatory Test Gates', engineId: 'software_engineering_governance_engine', category: 'quality', description: 'No production code merges without passing tests', conditions: 'merge.production && tests.failed === true', effect: 'block = true', version: '1.0.0', status: 'active' },
    { ruleId: 'SC-012', ruleName: 'Design Tokens Single Source of Truth', engineId: 'software_engineering_governance_engine', category: 'ui', description: 'Design tokens are defined in one canonical place; no hardcoded styling values', conditions: 'style.hardcoded === true', effect: 'block = true; require = "design token"', version: '1.0.0', status: 'active' },
    { ruleId: 'SC-013', ruleName: 'Observability Mandatory', engineId: 'software_engineering_governance_engine', category: 'operations', description: 'Every service emits structured logs, metrics, and traces', conditions: 'service.observability === false', effect: 'block = true; require = "logs + metrics + traces"', version: '1.0.0', status: 'active' },
    { ruleId: 'SC-014', ruleName: 'Engineering Permissions', engineId: 'software_engineering_governance_engine', category: 'security', description: 'Engineers hold least-privilege access to infrastructure; actions are audited', conditions: 'engineer.privilege === highest && role !== release_manager', effect: 'warn = true; require = "least privilege"', version: '1.0.0', status: 'active' },
    { ruleId: 'SC-015', ruleName: 'Documentation Is Code', engineId: 'software_engineering_governance_engine', category: 'quality', description: 'Documentation lives in the repository next to the code it describes and is reviewed like code', conditions: 'documentation.location !== repository', effect: 'warn = true; require = "in-repo docs"', version: '1.0.0', status: 'active' },

    // ── Knowledge Intelligence rules (Book XVII — KI-1) ────────────────────────
    { ruleId: 'CR-KI-001', ruleName: 'AMEXAN Assists Reasoning, Never Replaces It', engineId: 'knowledge_intelligence_engine', category: 'safety', description: 'AMEXAN generates interpretations, visualizations, evidence links, protocol pathways, and explainable reasoning chains — but clinical responsibility remains with the licensed professional. Reasoning stays inspectable, challengeable, editable.', conditions: 'output.type in [interpretation, recommendation, reasoning_chain] && clinician.review !== true', effect: 'warn = true; require = "clinician review"', version: '1.0.0', status: 'active' },
    { ruleId: 'KI-001', ruleName: 'Nothing Remains Raw Forever', engineId: 'knowledge_intelligence_engine', category: 'data', description: 'Every new piece of information immediately enters the constitutional processing pipeline', conditions: 'observation exists', effect: 'task = "process through pipeline"', version: '1.0.0', status: 'active' },
    { ruleId: 'KI-002', ruleName: 'Every Object Is Alive Through Relationships', engineId: 'knowledge_intelligence_engine', category: 'data', description: 'Objects gain meaning through relationships — never static facts', conditions: 'object exists', effect: 'set = "link relationships"', version: '1.0.0', status: 'active' },
    { ruleId: 'KI-003', ruleName: 'Context Is Mandatory', engineId: 'knowledge_intelligence_engine', category: 'context', description: 'No reasoning without context: age, sex, pregnancy, geography, season, occupation, comorbidities', conditions: 'reasoning && context === undefined', effect: 'block = true; require = "context"', version: '1.0.0', status: 'active' },
    { ruleId: 'KI-004', ruleName: 'Knowledge Explains Itself', engineId: 'knowledge_intelligence_engine', category: 'visibility', description: 'Every conclusion answers why, based on what, and on which facts and relationships', conditions: 'conclusion && explanation === undefined', effect: 'require = "explanation"', version: '1.0.0', status: 'active' },
    { ruleId: 'KI-005', ruleName: 'Layered Intelligence', engineId: 'knowledge_intelligence_engine', category: 'architecture', description: 'Intelligence is layered — observation, context, reasoning, knowledge, documentation, learning; one responsibility each', conditions: 'engine.responsibilities > 1', effect: 'require = "single responsibility"', version: '1.0.0', status: 'active' },
    { ruleId: 'KI-006', ruleName: 'Documentation Is Computation', engineId: 'knowledge_intelligence_engine', category: 'data', description: 'Notes become structured knowledge feeding every engine', conditions: 'note && structure === undefined', effect: 'set = "structured knowledge"', version: '1.0.0', status: 'active' },
    { ruleId: 'KI-007', ruleName: 'Evidence Traceability', engineId: 'knowledge_intelligence_engine', category: 'safety', description: 'Every recommendation exposes source guideline, publication, version, local adaptation', conditions: 'recommendation && source === undefined', effect: 'require = "evidence source"', version: '1.0.0', status: 'active' },
    { ruleId: 'KI-008', ruleName: 'Personalized Protocol Layering', engineId: 'knowledge_intelligence_engine', category: 'data', description: 'Protocols exist in layers; customization never destroys the default', conditions: 'protocol.customization && canonical === undefined', effect: 'require = "inheritance"', version: '1.0.0', status: 'active' },
    { ruleId: 'KI-009', ruleName: 'Reflection Is Constitutional', engineId: 'knowledge_intelligence_engine', category: 'workflow', description: 'After every completed case the clinician may record lessons learned', conditions: 'event === case_completed', effect: 'task = "offer reflection"', version: '1.0.0', status: 'active' },
    { ruleId: 'KI-010', ruleName: 'Knowledge Is Multi-View', engineId: 'knowledge_intelligence_engine', category: 'visibility', description: 'One case, many views: clinical, teaching, research, administrative, patient explanation', conditions: 'case exists', effect: 'show = "multi-view"', version: '1.0.0', status: 'active' },
    { ruleId: 'KI-011', ruleName: 'Personal Knowledge Workspace', engineId: 'knowledge_intelligence_engine', category: 'visibility', description: 'Every clinician owns a personal knowledge workspace', conditions: 'person exists', effect: 'allow = "personal workspace"', version: '1.0.0', status: 'active' },

    // ── Knowledge Ecosystem rules (Book XVIII — KE-1) ──────────────────────────
    { ruleId: 'CR-KE-001', ruleName: 'Provenance Is Preserved in Every Knowledge Output', engineId: 'knowledge_ecosystem_engine', category: 'data', description: 'All guidelines, educational materials, summaries, posters, brochures, and visualizations preserve provenance — source, version, approving authority, review date, references. Customizations layer on the canonical source, never replace it.', conditions: 'output.type in [guideline, educational_material, summary, poster, brochure, visualization] && output.provenance === undefined', effect: 'block = true; require = "provenance"', version: '1.0.0', status: 'active' },
    { ruleId: 'KE-001', ruleName: 'Knowledge Is a Living Organizational Asset', engineId: 'knowledge_ecosystem_engine', category: 'data', description: 'Every encounter, guideline, protocol, publication, and reflection contributes to the knowledge ecosystem', conditions: 'knowledge exists', effect: 'task = "contribute to ecosystem"', version: '1.0.0', status: 'active' },
    { ruleId: 'KE-002', ruleName: 'Knowledge Must Become Usable', engineId: 'knowledge_ecosystem_engine', category: 'data', description: 'No isolated PDFs, Word documents, or folders — resources become structured, searchable, linked knowledge', conditions: 'resource.format in [pdf, docx, pptx, email, folder]', effect: 'set = "structured knowledge object"', version: '1.0.0', status: 'active' },
    { ruleId: 'KE-003', ruleName: 'Department Living Knowledge Base', engineId: 'knowledge_ecosystem_engine', category: 'workflow', description: 'Every department owns a living knowledge base', conditions: 'department && knowledgeBase === undefined', effect: 'require = "department knowledge base"', version: '1.0.0', status: 'active' },
    { ruleId: 'KE-004', ruleName: 'Guideline Builder Uses Modular Blocks', engineId: 'knowledge_ecosystem_engine', category: 'workflow', description: 'Guidelines built from modular building blocks, not static documents', conditions: 'guideline && blocks === undefined', effect: 'require = "modular blocks"', version: '1.0.0', status: 'active' },
    { ruleId: 'KE-005', ruleName: 'Guideline Layering Without Duplication', engineId: 'knowledge_ecosystem_engine', category: 'data', description: 'Guidelines layer: global, country, society, organization, department, personal — no duplication', conditions: 'guideline.layer === undefined', effect: 'require = "layer inheritance"', version: '1.0.0', status: 'active' },
    { ruleId: 'KE-006', ruleName: 'One Source, Many Outputs', engineId: 'knowledge_ecosystem_engine', category: 'visibility', description: 'One knowledge object publishes to every channel from a single source', conditions: 'knowledge exists', effect: 'show = "multi-output"', version: '1.0.0', status: 'active' },
    { ruleId: 'KE-007', ruleName: 'Adaptive Patient Education', engineId: 'knowledge_ecosystem_engine', category: 'context', description: 'Education adapts to diagnosis, age, language, pregnancy, culture, literacy', conditions: 'patient && education.static === true', effect: 'set = "adaptive education"', version: '1.0.0', status: 'active' },
    { ruleId: 'KE-008', ruleName: 'Chronic Disease Education Journeys', engineId: 'knowledge_ecosystem_engine', category: 'workflow', description: 'Chronic disease patients receive continuous, progressing education journeys', conditions: 'diagnosis in [diabetes, hypertension, asthma, copd, heart_failure, ckd, cancer, hiv, tuberculosis]', effect: 'task = "education journey"', version: '1.0.0', status: 'active' },
    { ruleId: 'KE-009', ruleName: 'Constitutional Knowledge Templates', engineId: 'knowledge_ecosystem_engine', category: 'visibility', description: 'Every educational resource uses a constitutional template — nothing starts blank', conditions: 'resource && template === undefined', effect: 'require = "template"', version: '1.0.0', status: 'active' },
    { ruleId: 'KE-010', ruleName: 'Journal Intelligence Ingests Only Permitted Sources', engineId: 'knowledge_ecosystem_engine', category: 'data', description: 'Literature ingested through licensed APIs or permitted feeds; original source always preserved and cited', conditions: 'publication && source.unlicensed === true', effect: 'block = true', version: '1.0.0', status: 'active' },
    { ruleId: 'KE-011', ruleName: 'Knowledge Comparison', engineId: 'knowledge_ecosystem_engine', category: 'visibility', description: 'Clinicians compare hospital vs WHO vs national vs personal guidelines transparently', conditions: 'guideline exists', effect: 'show = "comparison"', version: '1.0.0', status: 'active' },
    { ruleId: 'KE-012', ruleName: 'Knowledge Analytics', engineId: 'knowledge_ecosystem_engine', category: 'reporting', description: 'Measure most-used guidelines, ignored protocols, misunderstood concepts, adherence', conditions: 'knowledge exists', effect: 'notify = "knowledge metrics"', version: '1.0.0', status: 'active' },

    // ── Healthcare Community rules (Book XIX — HC-1) ───────────────────────────
    { ruleId: 'CR-HC-001', ruleName: 'Never Optimize for Engagement or Time Spent', engineId: 'healthcare_community_engine', category: 'governance', description: 'Never optimize for engagement, advertising, or time spent. No attention-baiting, no outrage feeds, no infinite scroll. Success is measured only by healthcare improvement.', conditions: 'metric in [engagement, time_spent, ad_views, impressions, dwell_time, scroll_depth, sessions_per_day]', effect: 'block = true; metric = "healthcare improvement only"', version: '1.0.0', status: 'active' },
    { ruleId: 'HC-001', ruleName: 'A Healthcare Community, Not a Social Network', engineId: 'healthcare_community_engine', category: 'governance', description: 'Every community feature serves a healthcare purpose', conditions: 'community && purpose === undefined', effect: 'require = "healthcare purpose"', version: '1.0.0', status: 'active' },
    { ruleId: 'HC-002', ruleName: 'Community Objects Replace Social Posts', engineId: 'healthcare_community_engine', category: 'workflow', description: 'No "posts" — content units are structured community objects (case, pearl, question, topic)', conditions: 'content.type === post', effect: 'require = "community object"', version: '1.0.0', status: 'active' },
    { ruleId: 'HC-003', ruleName: 'Layered Communities', engineId: 'healthcare_community_engine', category: 'workflow', description: 'Communities exist in layers — global, organizational, department, specialty, teaching', conditions: 'community.layer === undefined', effect: 'require = "layer"', version: '1.0.0', status: 'active' },
    { ruleId: 'HC-004', ruleName: 'Verified Professional Identity', engineId: 'healthcare_community_engine', category: 'security', description: 'Healthcare professionals verified through licensing or institutional verification; clinical voices never anonymous', conditions: 'person.professional && verified === false', effect: 'require = "verification"', version: '1.0.0', status: 'active' },
    { ruleId: 'HC-005', ruleName: 'Healthcare Social Graph', engineId: 'healthcare_community_engine', category: 'data', description: 'The social graph is professional and clinical — teacher–student, mentor–mentee, colleagues', conditions: 'relationship exists', effect: 'set = "professional graph"', version: '1.0.0', status: 'active' },
    { ruleId: 'HC-006', ruleName: 'Knowledge-Driven Feed', engineId: 'healthcare_community_engine', category: 'visibility', description: 'The feed shows objects relevant to specialty, interests, and learning — never engagement-driven', conditions: 'feed && sort === engagement', effect: 'show = "knowledge-driven feed"', version: '1.0.0', status: 'active' },
    { ruleId: 'HC-007', ruleName: 'Constitutional News Engine', engineId: 'healthcare_community_engine', category: 'data', description: 'News organized by specialty and region, sourced from labeled trustworthy channels', conditions: 'news && source === unlabeled', effect: 'require = "labeled source"', version: '1.0.0', status: 'active' },
    { ruleId: 'HC-008', ruleName: 'Safe Clinical Discussion Spaces', engineId: 'healthcare_community_engine', category: 'governance', description: 'Clinical discussions in safe, moderated spaces — no patient data, no blame', conditions: 'discussion && moderation === undefined', effect: 'require = "moderation"', version: '1.0.0', status: 'active' },
    { ruleId: 'HC-009', ruleName: 'Teaching Communities', engineId: 'healthcare_community_engine', category: 'workflow', description: 'Teaching communities have structure: cases, journals, images, protocols, Q&A, assessments', conditions: 'teaching && structure === undefined', effect: 'require = "teaching structure"', version: '1.0.0', status: 'active' },
    { ruleId: 'HC-010', ruleName: 'Protected Patient Communities', engineId: 'healthcare_community_engine', category: 'privacy', description: 'Patient communities are protected, private, moderated by healthcare professionals', conditions: 'patient_community && privacy === false', effect: 'require = "privacy + moderation"', version: '1.0.0', status: 'active' },
    { ruleId: 'HC-011', ruleName: 'Telemedicine Communities', engineId: 'healthcare_community_engine', category: 'context', description: 'Telemedicine connects patients and clinicians responsibly, respecting scope of practice', conditions: 'telemedicine && scope === undefined', effect: 'require = "scope of practice"', version: '1.0.0', status: 'active' },
    { ruleId: 'HC-012', ruleName: 'Humanitarian Collaboration', engineId: 'healthcare_community_engine', category: 'workflow', description: 'During emergencies, AMEXAN connects responders, researchers, and organizations for crisis collaboration', conditions: 'humanitarian && ethics === undefined', effect: 'require = "ethical standards"', version: '1.0.0', status: 'active' },
    { ruleId: 'HC-013', ruleName: 'Public Health Awareness Communities', engineId: 'healthcare_community_engine', category: 'reporting', description: 'Public health awareness through education, never sensationalism or marketing', conditions: 'public_health && tone === sensational', effect: 'block = true', version: '1.0.0', status: 'active' },
    { ruleId: 'HC-014', ruleName: 'Reputation Through Contribution', engineId: 'healthcare_community_engine', category: 'governance', description: 'Reputation earned through teaching, cases, answers, research, mentoring — never likes or followers', conditions: 'reputation.metric in [likes, followers]', effect: 'block = true; require = "contribution-based"', version: '1.0.0', status: 'active' },
    { ruleId: 'HC-015', ruleName: 'Constitutional Moderation', engineId: 'healthcare_community_engine', category: 'governance', description: 'Every community has a moderation hierarchy — automated, community, platform, constitutional', conditions: 'content.report === violation', effect: 'block = true; escalate = true', version: '1.0.0', status: 'active' },
  ]);
}

export function initializeAGOC(): void {
  registerAllEngines();
  registerAllWorkflows();
  registerAllRules();
}