import type { DiseaseEducation } from '../educationRegistry';
import { getDiseaseName, getDiseaseCategory } from '../diseaseProfile';

const CATEGORY_EDUCATION_TEMPLATES: Record<string, Partial<DiseaseEducation>> = {
  cardiology: {
    overview: '{DiseaseName} affects the cardiovascular system and requires prompt clinical evaluation. Management depends on the specific condition, severity, and patient comorbidities.',
    epidemiology: 'Cardiovascular diseases are the leading cause of death globally, accounting for approximately 18 million deaths annually. Prevalence increases with age and is higher in patients with diabetes, hypertension, and smoking history.',
    riskFactors: ['Hypertension', 'Diabetes mellitus', 'Dyslipidemia', 'Smoking', 'Family history of cardiovascular disease', 'Increasing age', 'Obesity', 'Sedentary lifestyle'],
    typicalPresentation: ['Cardiac chest pain or discomfort', 'Shortness of breath on exertion or at rest', 'Palpitations or irregular heartbeat', 'Fatigue and reduced exercise tolerance', 'Peripheral edema or fluid retention'],
    clinicalSigns: ['Cardiovascular examination findings vary based on the specific condition — may include murmurs, gallop rhythm, elevated JVP, peripheral edema, or lung crackles'],
    diagnosticCriteria: 'Diagnosis is based on clinical history, physical examination, ECG, cardiac biomarkers, and imaging studies (echocardiography, CT coronary angiography, or cardiac MRI) as clinically indicated.',
    firstLineTreatment: 'Management includes lifestyle modification, pharmacotherapy (antiplatelets, beta-blockers, ACE inhibitors, statins, diuretics), and revascularization procedures (PCI or CABG) where indicated.',
    complications: ['Acute coronary syndrome (STEMI/NSTEMI)', 'Heart failure', 'Arrhythmias (AF, VT, VF)', 'Cardiogenic shock', 'Sudden cardiac death', 'Peripheral thromboembolism'],
    prognosis: 'Prognosis varies widely with the specific condition, severity at presentation, and timeliness of intervention. Early diagnosis and guideline-directed medical therapy significantly improve outcomes.',
    prevention: ['Blood pressure control (<130/80 mmHg)', 'Glycemic control (HbA1c <7%)', 'Smoking cessation', 'Regular aerobic exercise (150 min/week)', 'Healthy diet (Mediterranean/DASH diet)', 'Weight management'],
    patientEducation: ['Take all medications exactly as prescribed — do not stop without medical advice', 'Recognize warning signs: chest pain, severe dyspnea, syncope', 'Maintain a heart-healthy lifestyle with diet and exercise', 'Attend all follow-up appointments and cardiac rehabilitation', 'Carry a list of current medications at all times'],
    references: ['ESC Guidelines for Cardiovascular Disease', 'AHA/ACC Clinical Practice Guidelines'],
  },
  respiratory: {
    overview: '{DiseaseName} is a respiratory condition that requires clinical evaluation. Presentation and severity vary based on underlying etiology and patient factors.',
    epidemiology: 'Respiratory diseases affect over 1 billion people worldwide and are a leading cause of morbidity and mortality. Prevalence varies significantly by region, socioeconomic status, and environmental exposures.',
    riskFactors: ['Smoking or tobacco use', 'Environmental pollution', 'Occupational exposures', 'Allergies', 'Family history of respiratory disease', 'Immunosuppression', 'Chronic lung disease'],
    typicalPresentation: ['Cough (acute or chronic) with or without sputum', 'Shortness of breath or dyspnea', 'Wheezing or chest tightness', 'Fever and constitutional symptoms', 'Chest pain, especially with breathing or coughing'],
    clinicalSigns: ['Respiratory examination findings vary — may include tachypnea, accessory muscle use, wheeze, crackles, reduced breath sounds, or bronchial breathing'],
    diagnosticCriteria: 'Diagnosis is based on clinical history, physical examination, chest imaging (X-ray or CT), pulmonary function tests, and relevant laboratory investigations as clinically indicated.',
    firstLineTreatment: 'Varies by condition: bronchodilators and inhaled corticosteroids for asthma/COPD, antibiotics for pneumonia, antitubercular therapy for TB, oxygen supplementation for hypoxemia.',
    complications: ['Respiratory failure', 'Pneumothorax', 'Empyema', 'Sepsis', 'Acute respiratory distress syndrome (ARDS)', 'Cor pulmonale'],
    prognosis: 'Prognosis depends on the specific diagnosis, disease severity at presentation, and patient factors such as age and comorbidities. Early treatment improves outcomes.',
    prevention: ['Smoking cessation', 'Vaccination (influenza, pneumococcal)', 'Avoidance of triggers and allergens', 'Pulmonary rehabilitation where indicated', 'Occupational safety measures'],
    patientEducation: ['Complete the full course of prescribed medications', 'Use inhalers with correct technique — demonstrate at each visit', 'Monitor symptoms and seek care if worsening', 'Avoid smoking and second-hand smoke exposure', 'Maintain up-to-date vaccinations'],
    references: ['GOLD Guidelines for COPD', 'GINA Guidelines for Asthma', 'BTS Clinical Guidelines'],
  },
  infectious: {
    overview: '{DiseaseName} is an infectious condition caused by a pathogen. Accurate diagnosis and timely treatment are essential to prevent complications and reduce transmission.',
    epidemiology: 'Infectious diseases remain a major cause of morbidity and mortality worldwide, particularly in low-resource settings. Incidence varies by region, season, and population immunity.',
    riskFactors: ['Immunosuppression (HIV, steroids, chemotherapy)', 'Malnutrition', 'Diabetes mellitus', 'Recent hospitalization or surgery', 'Contact with infected individuals', 'Travel to endemic areas', 'Crowded living conditions'],
    typicalPresentation: ['Fever with or without chills/rigors', 'Malaise and fatigue', 'Localizing symptoms based on infected organ/system', 'Lymphadenopathy', 'Rash or skin changes depending on etiology'],
    clinicalSigns: ['Signs vary by pathogen and site of infection — may include fever, tachycardia, tachypnea, focal tenderness, erythema, swelling, or purulent discharge'],
    diagnosticCriteria: 'Diagnosis is based on clinical presentation, laboratory investigations (CBC, CRP, cultures, serology, molecular testing), and imaging studies as clinically indicated.',
    firstLineTreatment: 'Appropriate antimicrobial therapy based on suspected or confirmed pathogen, source control where indicated, and supportive care including fluids, antipyretics, and oxygen if required.',
    complications: ['Sepsis and septic shock', 'Organ-specific complications (abscess, empyema, endocarditis)', 'Disseminated infection', 'Antimicrobial resistance', 'Multi-organ dysfunction syndrome (MODS)'],
    prognosis: 'Outcomes depend on the pathogen, host immune status, timeliness of treatment, and presence of complications. Early appropriate therapy significantly improves prognosis.',
    prevention: ['Hand hygiene and infection control measures', 'Vaccination where available', 'Safe food and water practices', 'Avoidance of unnecessary antibiotic use', 'Travel precautions and prophylaxis where indicated'],
    patientEducation: ['Complete the full course of prescribed antibiotics even if you feel better', 'Watch for signs of deterioration: worsening fever, confusion, difficulty breathing', 'Practice good hand hygiene and respiratory etiquette', 'Stay hydrated and rest', 'Keep follow-up appointments for monitoring'],
    references: ['WHO Infectious Disease Guidelines', 'CDC Treatment Guidelines', 'Local Antimicrobial Stewardship Guidelines'],
  },
  surgery: {
    overview: '{DiseaseName} is a surgical condition that may require operative intervention. Diagnosis is based on clinical examination and appropriate imaging studies.',
    epidemiology: 'Surgical conditions account for a significant proportion of hospital admissions and emergency department visits worldwide. Early recognition and timely referral improve outcomes.',
    riskFactors: ['Increasing age', 'Obesity', 'Diabetes mellitus', 'Smoking', 'Previous abdominal surgery', 'Immunosuppression', 'Poor nutritional status'],
    typicalPresentation: ['Pain (acute or chronic) localized to the affected area', 'Swelling or mass', 'Nausea and vomiting', 'Fever if inflammatory/infectious', 'Functional impairment'],
    clinicalSigns: ['Signs vary by condition — may include tenderness, guarding, rigidity, mass, or signs of peritonism on abdominal examination'],
    diagnosticCriteria: 'Diagnosis is based on clinical history, physical examination, laboratory investigations (CBC, CRP), and appropriate imaging studies (X-ray, ultrasound, CT scan).',
    firstLineTreatment: 'Initial management includes resuscitation, analgesia, IV fluids, and antibiotics if infection is present. Definitive management is surgical intervention as indicated.',
    complications: ['Wound infection or dehiscence', 'Intra-abdominal abscess', 'Anastomotic leak', 'Post-operative hemorrhage', 'Ileus or bowel obstruction', 'DVT/pulmonary embolism', 'Anesthesia-related complications'],
    prognosis: 'Prognosis is generally favorable with timely surgical intervention. Outcomes depend on the urgency of presentation, comorbidities, and post-operative care quality.',
    prevention: ['Optimize comorbidities before elective surgery', 'Smoking cessation and weight loss', 'Perioperative antibiotics as indicated', 'DVT prophylaxis', 'Early mobilization after surgery'],
    patientEducation: ['Understand the planned surgical procedure and its risks', 'Follow pre-operative instructions (fasting, medication adjustments)', 'Watch for signs of wound infection: redness, swelling, discharge, fever', 'Adhere to activity restrictions after surgery', 'Attend all post-operative follow-up appointments'],
    references: ['Surgical Recall', 'ACS Surgery: Principles and Practice', 'Local Surgical Guidelines'],
  },
  orthopaedics: {
    overview: '{DiseaseName} is a musculoskeletal condition affecting the bones, joints, or soft tissues. Management may be conservative or surgical depending on severity.',
    epidemiology: 'Musculoskeletal conditions are among the most common reasons for healthcare seeking globally, affecting people of all ages. Prevalence increases with age and varies by activity level.',
    riskFactors: ['Increasing age', 'Obesity', 'Occupational or sports-related overuse', 'Previous joint injury', 'Osteoporosis', 'Genetic predisposition', 'Poor biomechanics'],
    typicalPresentation: ['Localized pain worsened by movement or weight-bearing', 'Swelling or effusion', 'Stiffness and reduced range of motion', 'Instability or giving way', 'Deformity or malalignment'],
    clinicalSigns: ['Examination findings vary — may include tenderness, swelling, crepitus, reduced range of motion, ligamentous laxity, or deformity'],
    diagnosticCriteria: 'Diagnosis is based on clinical history, physical examination, and imaging studies (X-ray, MRI, CT, ultrasound) as clinically indicated.',
    firstLineTreatment: 'Initial management follows the RICE principle (Rest, Ice, Compression, Elevation) with appropriate analgesia. Physiotherapy and rehabilitation are key. Surgical intervention is reserved for specific indications.',
    complications: ['Chronic pain', 'Joint stiffness or contracture', 'Post-traumatic osteoarthritis', 'Non-union or malunion of fractures', 'Compartment syndrome', 'Avascular necrosis'],
    prognosis: 'Prognosis is generally good with appropriate management. Recovery time varies by injury severity, patient age, and adherence to rehabilitation protocols.',
    prevention: ['Proper warm-up and conditioning before physical activity', 'Use of appropriate protective equipment', 'Weight management to reduce joint stress', 'Fall prevention strategies in the elderly', 'Ergonomic workplace modifications'],
    patientEducation: ['Follow the RICE protocol for acute injuries', 'Adhere to the prescribed rehabilitation program', 'Use assistive devices as instructed (crutches, brace, sling)', 'Do not rush return to sports or heavy activity', 'Report any new or worsening symptoms promptly'],
    references: ['AAOS Clinical Practice Guidelines', 'AO Principles of Fracture Management', 'Bone and Joint Initiative'],
  },
  neurology: {
    overview: '{DiseaseName} involves the nervous system and requires thorough neurological evaluation. Early recognition and treatment are essential for optimal outcomes.',
    epidemiology: 'Neurological disorders are a leading cause of disability worldwide. The global burden includes stroke, dementia, headache disorders, epilepsy, and neurodegenerative diseases.',
    riskFactors: ['Increasing age', 'Hypertension', 'Diabetes mellitus', 'Smoking', 'Family history of neurological disease', 'Head trauma', 'Cardiovascular disease'],
    typicalPresentation: ['Headache (acute, chronic, or progressive)', 'Neurological deficit (weakness, numbness, visual changes)', 'Seizures or altered consciousness', 'Cognitive decline or memory impairment', 'Gait disturbance or coordination problems'],
    clinicalSigns: ['Neurological examination findings vary — may include focal deficits, altered mental status, cranial nerve abnormalities, or abnormal reflexes'],
    diagnosticCriteria: 'Diagnosis is based on clinical history, detailed neurological examination, and appropriate investigations (CT/MRI brain, EEG, nerve conduction studies, lumbar puncture) as indicated.',
    firstLineTreatment: 'Acute management is directed at the underlying cause (thrombolysis for ischemic stroke, anticonvulsants for seizures, etc.). Long-term management includes secondary prevention and rehabilitation.',
    complications: ['Permanent neurological deficit', 'Disability and loss of independence', 'Aspiration pneumonia', 'Venous thromboembolism', 'Pressure sores', 'Depression and anxiety'],
    prognosis: 'Prognosis varies widely depending on the specific condition and severity. Early intervention and comprehensive rehabilitation improve functional outcomes.',
    prevention: ['Blood pressure control', 'Glycemic management', 'Smoking cessation', 'Regular physical activity', 'Head injury prevention (helmets, fall prevention)', 'Cognitive stimulation'],
    patientEducation: ['Recognize stroke warning signs (FAST: Face, Arm, Speech, Time)', 'Take medications consistently for secondary prevention', 'Participate in rehabilitation therapies', 'Adapt home environment for safety', 'Join support groups for chronic neurological conditions'],
    references: ['NICE Guidelines for Neurological Conditions', 'AAN Clinical Practice Guidelines', 'WHO Neurological Disorders Guidelines'],
  },
  psychiatry: {
    overview: '{DiseaseName} is a mental health condition that requires comprehensive psychiatric assessment. Treatment involves a biopsychosocial approach tailored to the individual.',
    epidemiology: 'Mental health disorders affect approximately 1 in 8 people globally. Depression is a leading cause of disability worldwide, and psychiatric comorbidities are common in medical illness.',
    riskFactors: ['Genetic predisposition (family history)', 'Childhood adversity or trauma', 'Chronic medical illness', 'Substance use', 'Social isolation', 'Stressful life events', 'Personality factors'],
    typicalPresentation: ['Persistent low mood or loss of interest/pleasure', 'Anxiety, worry, or panic attacks', 'Changes in sleep, appetite, or energy', 'Cognitive difficulties (concentration, memory)', 'Psychotic symptoms (hallucinations, delusions)', 'Suicidal thoughts or self-harm'],
    clinicalSigns: ['Mental state examination findings vary — may include depressed or elevated mood, anxiety, thought disorder, perceptual abnormalities, or cognitive impairment'],
    diagnosticCriteria: 'Diagnosis is based on clinical interview, mental state examination, and DSM-5-TR or ICD-11 diagnostic criteria. Medical workup is essential to rule out organic causes.',
    firstLineTreatment: 'Management combines pharmacotherapy (antidepressants, mood stabilizers, antipsychotics) and evidence-based psychotherapy (CBT, DBT, IPT). Social support and lifestyle interventions are integral.',
    complications: ['Suicide and self-harm', 'Functional impairment and disability', 'Poor quality of life', 'Social isolation and relationship breakdown', 'Substance use comorbidity', 'Medical consequences of poor self-care'],
    prognosis: 'Prognosis varies by disorder. Most psychiatric conditions are treatable and many individuals achieve significant improvement or recovery with appropriate treatment and support.',
    prevention: ['Early recognition and intervention', 'Stress management and healthy coping strategies', 'Social connection and support networks', 'Regular physical activity', 'Avoidance of substance misuse', 'Routine screening in high-risk groups'],
    patientEducation: ['Mental health conditions are medical conditions — not a sign of weakness', 'Medication adherence is crucial — do not stop abruptly', 'Attend therapy sessions regularly', 'Develop a crisis plan with your mental health team', 'Engage with peer support groups', 'Reach out immediately if you have thoughts of self-harm'],
    references: ['DSM-5-TR Diagnostic Criteria', 'APA Practice Guidelines', 'NICE Mental Health Guidelines', 'WHO mhGAP Guidelines'],
  },
  general_medicine: {
    overview: '{DiseaseName} requires thorough clinical evaluation and management. Presentation and severity vary based on underlying etiology and patient factors.',
    epidemiology: 'This condition presents with variable epidemiology depending on the specific diagnosis. Clinical assessment and appropriate investigations guide management.',
    riskFactors: ['Increasing age', 'Comorbid medical conditions', 'Lifestyle factors (diet, exercise, smoking)', 'Family history', 'Environmental exposures'],
    typicalPresentation: ['Symptom onset, duration, and progression depend on underlying etiology', 'Associated features vary by organ system involved'],
    clinicalSigns: ['Physical examination findings correlate with the underlying pathology'],
    diagnosticCriteria: 'Diagnosis is based on clinical history, physical examination, and appropriate laboratory and imaging investigations as clinically indicated.',
    firstLineTreatment: 'Management is directed at the underlying cause and includes pharmacological and non-pharmacological interventions as appropriate. Supportive care is provided as needed.',
    complications: ['Progression of underlying disease', 'Secondary infection', 'Organ dysfunction', 'Reduced quality of life'],
    prognosis: 'Prognosis depends on the specific diagnosis, severity at presentation, and response to treatment. Early diagnosis and appropriate management improve outcomes.',
    prevention: ['Regular medical check-ups and screening', 'Healthy lifestyle (balanced diet, regular exercise)', 'Medication adherence for chronic conditions', 'Avoidance of harmful habits (smoking, excessive alcohol)', 'Vaccination as recommended'],
    patientEducation: ['Take all medications as prescribed — complete the full course', 'Return immediately if symptoms worsen', 'Attend all follow-up appointments as scheduled', 'Maintain a healthy lifestyle with balanced diet and regular exercise', 'Report any new or worsening symptoms to your healthcare provider promptly'],
    references: ['Clinical Medicine (Kumar & Clark)', 'Current Medical Diagnosis and Treatment'],
  },
};

export function getFallbackEducation(diseaseId: string): DiseaseEducation {
  const name = getDiseaseName(diseaseId);
  const cat = getDiseaseCategory(diseaseId);
  const template = CATEGORY_EDUCATION_TEMPLATES[cat] || CATEGORY_EDUCATION_TEMPLATES['general_medicine'];

  function fill(s: string) { return s.replace(/\{DiseaseName\}/g, name); }

  return {
    diseaseId,
    diseaseName: name,
    overview: fill(template.overview || ''),
    epidemiology: template.epidemiology || '',
    riskFactors: template.riskFactors || [],
    typicalPresentation: template.typicalPresentation || [],
    clinicalSigns: template.clinicalSigns || [],
    diagnosticCriteria: template.diagnosticCriteria || '',
    firstLineTreatment: template.firstLineTreatment || '',
    complications: template.complications || [],
    prognosis: template.prognosis || '',
    prevention: template.prevention || [],
    patientEducation: template.patientEducation || [],
    references: template.references || [],
  };
}
