CREATE CONSTRAINT IF NOT EXISTS FOR (s:Symptom) REQUIRE s.name IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (d:Disease) REQUIRE d.name IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (inv:Investigation) REQUIRE inv.name IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (drug:Drug) REQUIRE drug.name IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (bs:BodySystem) REQUIRE bs.name IS UNIQUE;

MERGE (fever:Symptom {name:'Fever'})
MERGE (cough:Symptom {name:'Cough'})
MERGE (dyspnoea:Symptom {name:'Dyspnoea'})
MERGE (chestPain:Symptom {name:'Chest Pain'})
MERGE (fatigue:Symptom {name:'Fatigue'})
MERGE (weightLoss:Symptom {name:'Weight Loss'})
MERGE (nightSweats:Symptom {name:'Night Sweats'})

MERGE (pneumonia:Disease {name:'Pneumonia'})
MERGE (tb:Disease {name:'Tuberculosis'})
MERGE (heartFailure:Disease {name:'Heart Failure'})
MERGE (copd:Disease {name:'COPD'})
MERGE (asthma:Disease {name:'Asthma'})
MERGE (pe:Disease {name:'Pulmonary Embolism'})
MERGE (lungCa:Disease {name:'Lung Cancer'})

MERGE (resp:BodySystem {name:'Respiratory'})
MERGE (cardio:BodySystem {name:'Cardiovascular'})

MERGE (cxr:Investigation {name:'Chest X-ray'})
MERGE (ctChest:Investigation {name:'CT Chest'})
MERGE (ecg:Investigation {name:'ECG'})
MERGE (echo:Investigation {name:'Echocardiogram'})
MERGE (sputumCulture:Investigation {name:'Sputum Culture'})
MERGE (bloodCulture:Investigation {name:'Blood Culture'})
MERGE (fbc:Investigation {name:'Full Blood Count'})
MERGE (crp:Investigation {name:'C-Reactive Protein'})
MERGE (bnp:Investigation {name:'BNP/NT-proBNP'})
MERGE (pfts:Investigation {name:'Pulmonary Function Tests'})
MERGE (ctpa:Investigation {name:'CT Pulmonary Angiogram'})
MERGE (bronchoscopy:Investigation {name:'Bronchoscopy'})

MERGE (amoxicillin:Drug {name:'Amoxicillin'})
MERGE (doxycycline:Drug {name:'Doxycycline'})
MERGE (rifampicin:Drug {name:'Rifampicin'})
MERGE (isoniazid:Drug {name:'Isoniazid'})
MERGE (furosemide:Drug {name:'Furosemide'})
MERGE (salbutamol:Drug {name:'Salbutamol'})
MERGE (prednisolone:Drug {name:'Prednisolone'})
MERGE (heparin:Drug {name:'Heparin'})

// Symptom -> Disease
MERGE (fever)-[:SUGGESTS]->(pneumonia)
MERGE (cough)-[:SUGGESTS]->(pneumonia)
MERGE (dyspnoea)-[:SUGGESTS]->(pneumonia)
MERGE (cough)-[:SUGGESTS]->(tb)
MERGE (fever)-[:SUGGESTS]->(tb)
MERGE (nightSweats)-[:SUGGESTS]->(tb)
MERGE (weightLoss)-[:SUGGESTS]->(tb)
MERGE (dyspnoea)-[:SUGGESTS]->(heartFailure)
MERGE (fatigue)-[:SUGGESTS]->(heartFailure)
MERGE (chestPain)-[:SUGGESTS]->(heartFailure)
MERGE (cough)-[:SUGGESTS]->(copd)
MERGE (dyspnoea)-[:SUGGESTS]->(copd)
MERGE (cough)-[:SUGGESTS]->(asthma)
MERGE (dyspnoea)-[:SUGGESTS]->(asthma)
MERGE (dyspnoea)-[:SUGGESTS]->(pe)
MERGE (chestPain)-[:SUGGESTS]->(pe)
MERGE (cough)-[:SUGGESTS]->(lungCa)
MERGE (dyspnoea)-[:SUGGESTS]->(lungCa)
MERGE (chestPain)-[:SUGGESTS]->(lungCa)
MERGE (weightLoss)-[:SUGGESTS]->(lungCa)

// Disease -> BodySystem
MERGE (pneumonia)-[:PART_OF]->(resp)
MERGE (tb)-[:PART_OF]->(resp)
MERGE (copd)-[:PART_OF]->(resp)
MERGE (asthma)-[:PART_OF]->(resp)
MERGE (lungCa)-[:PART_OF]->(resp)
MERGE (heartFailure)-[:PART_OF]->(cardio)

// Disease -> Investigation
MERGE (pneumonia)-[:INVESTIGATE_WITH]->(cxr)
MERGE (pneumonia)-[:INVESTIGATE_WITH]->(fbc)
MERGE (pneumonia)-[:INVESTIGATE_WITH]->(crp)
MERGE (pneumonia)-[:INVESTIGATE_WITH]->(bloodCulture)
MERGE (pneumonia)-[:INVESTIGATE_WITH]->(sputumCulture)
MERGE (tb)-[:INVESTIGATE_WITH]->(cxr)
MERGE (tb)-[:INVESTIGATE_WITH]->(sputumCulture)
MERGE (tb)-[:INVESTIGATE_WITH]->(ctChest)
MERGE (heartFailure)-[:INVESTIGATE_WITH]->(ecg)
MERGE (heartFailure)-[:INVESTIGATE_WITH]->(echo)
MERGE (heartFailure)-[:INVESTIGATE_WITH]->(bnp)
MERGE (heartFailure)-[:INVESTIGATE_WITH]->(cxr)
MERGE (copd)-[:INVESTIGATE_WITH]->(pfts)
MERGE (copd)-[:INVESTIGATE_WITH]->(cxr)
MERGE (asthma)-[:INVESTIGATE_WITH]->(pfts)
MERGE (pe)-[:INVESTIGATE_WITH]->(ctpa)
MERGE (pe)-[:INVESTIGATE_WITH]->(ecg)
MERGE (lungCa)-[:INVESTIGATE_WITH]->(cxr)
MERGE (lungCa)-[:INVESTIGATE_WITH]->(ctChest)
MERGE (lungCa)-[:INVESTIGATE_WITH]->(bronchoscopy)

// Disease -> Drug (Treatment)
MERGE (pneumonia)-[:TREATED_BY]->(amoxicillin)
MERGE (pneumonia)-[:TREATED_BY]->(doxycycline)
MERGE (tb)-[:TREATED_BY]->(rifampicin)
MERGE (tb)-[:TREATED_BY]->(isoniazid)
MERGE (heartFailure)-[:TREATED_BY]->(furosemide)
MERGE (copd)-[:TREATED_BY]->(salbutamol)
MERGE (copd)-[:TREATED_BY]->(prednisolone)
MERGE (asthma)-[:TREATED_BY]->(salbutamol)
MERGE (asthma)-[:TREATED_BY]->(prednisolone)
MERGE (pe)-[:TREATED_BY]->(heparin)

// Differential diagnoses (Disease mimics another)
MERGE (pneumonia)-[:MIMICS]->(tb)
MERGE (tb)-[:MIMICS]->(pneumonia)
MERGE (pneumonia)-[:MIMICS]->(heartFailure)
MERGE (heartFailure)-[:MIMICS]->(pneumonia)
MERGE (asthma)-[:MIMICS]->(copd)
MERGE (copd)-[:MIMICS]->(asthma)
MERGE (pneumonia)-[:MIMICS]->(lungCa)
MERGE (lungCa)-[:MIMICS]->(pneumonia)

RETURN 'Knowledge graph seeded' AS result;
