import type { DepartmentDefinition } from './index';

export const laboratoryMedicine: DepartmentDefinition = {
  id: 'LAB',
  name: 'Laboratory Medicine',
  shortName: 'LAB',
  description: 'Clinical pathology services including chemical pathology, haematology, microbiology, immunology and molecular diagnostics for disease diagnosis and monitoring.',
  icon: '🧪',
  color: '#0ea5e9',
  sections: [
    {
      id: 'chemical-pathology',
      name: 'Chemical Pathology / Clinical Biochemistry',
      description: 'Biochemical analysis of body fluids for diagnosis and monitoring',
      diseaseCategories: ['Clinical biochemistry profiling', 'Endocrine laboratory diagnostics', 'Toxicology and therapeutic drug monitoring', 'Tumour marker analysis', 'Lipid and cardiovascular risk profiling', 'Inherited metabolic disease screening'],
    },
    {
      id: 'haematology-lab',
      name: 'Haematology Laboratory',
      description: 'Blood cell analysis, coagulation and transfusion medicine',
      diseaseCategories: ['Full blood count and differential', 'Coagulation studies', 'Haemoglobinopathy diagnosis', 'Bone marrow reporting', 'Flow cytometry phenotyping', 'Transfusion compatibility testing'],
    },
    {
      id: 'microbiology',
      name: 'Microbiology & Virology',
      description: 'Identification of pathogenic microorganisms and antibiotic sensitivity',
      diseaseCategories: ['Bacterial culture and sensitivity', 'Mycobacterial culture (TB)', 'Fungal culture and identification', 'Blood culture and sepsis profiling', 'Viral PCR and serology', 'Molecular diagnostics (PCR/NAT)', 'Antimicrobial resistance surveillance'],
    },
    {
      id: 'immunology',
      name: 'Clinical Immunology',
      description: 'Assessment of immune function and autoimmune disease',
      diseaseCategories: ['Autoantibody profiling', 'Allergy and hypersensitivity testing', 'Immunoglobulin quantification', 'Complement studies', 'Lymphocyte subset analysis', 'Vaccine response monitoring'],
    },
    {
      id: 'molecular-genetics',
      name: 'Molecular Genetics',
      description: 'DNA/RNA analysis for inherited and acquired genetic disorders',
      diseaseCategories: ['Germline genetic testing', 'Somatic mutation profiling (oncology)', 'Pharmacogenomics', 'Prenatal genetic screening', 'Carrier screening', 'Inherited cancer predisposition testing'],
    },
    {
      id: 'point-of-care',
      name: 'Point-of-Care Testing (POCT)',
      description: 'Near-patient testing and quality assurance',
      diseaseCategories: ['Blood gas analysis', 'Glucose monitoring', 'INR monitoring', 'Cardiac markers (troponin/BNP)', 'Urine dipstick analysis', 'Pregnancy testing', 'Infectious disease rapid testing'],
    },
  ],
  commonSymptoms: [
    'abnormal_lab_result_needing_correlation',
    'unexplained_anaemia', 'unexplained_thrombocytopenia',
    'unexplained_coagulopathy', 'electrolyte_imbalance',
    'acid_base_disorder', 'abnormal_liver_function',
    'abnormal_renal_function', 'suspected_infection',
    'fever_of_unknown_origin', 'autoimmune_marker_detection',
    'tumour_marker_monitoring', 'therapeutic_drug_monitoring',
    'allergy_testing', 'genetic_risk_assessment',
    'preoperative_lab_screening', 'transfusion_compatibility',
    'blood_group_discrepancy', 'haemolysis_workup',
    'thyroid_function_abnormal', 'adrenal_function_testing',
  ],
  commonInvestigations: [
    'FBC with differential', 'Peripheral blood film',
    'PT/APTT/Fibrinogen', 'D-dimer', 'U&E', 'Creatinine/eGFR',
    'LFT (ALT, AST, ALP, GGT, bilirubin)', 'CRP', 'ESR',
    'Cardiac troponin', 'BNP/NT-proBNP', 'Lipid profile',
    'HbA1c', 'Blood glucose', 'TSH/FT4/FT3', 'Cortisol/ACTH',
    'Iron studies', 'Ferritin', 'Vitamin B12', 'Folate',
    'Vitamin D', 'Calcium/Phosphate/Magnesium',
    'Blood culture and sensitivity', 'Urine culture microscopy',
    'Stool culture', 'Throat swab culture',
    'Hepatitis B/C/HIV serology', 'Syphilis serology',
    'Autoimmune serology (ANA, RF, anti-CCP, ANCA)',
    'Serum protein electrophoresis', 'Free light chains',
    'Immunoglobulins G/A/M/E', 'Tumour markers (CEA, CA19-9, AFP, CA-125, PSA)',
    'Therapeutic drug monitoring (gentamicin, vancomycin, lithium)',
    'PCR for viral/Bacterial detection', 'Flow cytometry',
    'Cytogenetics/FISH', 'Next-generation sequencing panels',
  ],
};
