import type { DepartmentDefinition } from './index';

export const pediatrics: DepartmentDefinition = {
  id: 'PAED',
  name: 'Pediatrics',
  shortName: 'PAED',
  description: 'Medical care of infants, children and adolescents from birth to 18 years, including neonatal medicine and paediatric subspecialties.',
  icon: '👶',
  color: '#22d3ee',
  sections: [
    {
      id: 'neonatology',
      name: 'Neonatology',
      description: 'Care of newborn infants, particularly premature and critically ill neonates',
      diseaseCategories: ['Prematurity', 'Neonatal jaundice', 'Neonatal sepsis', 'Neonatal respiratory distress', 'Birth asphyxia', 'Neonatal hypoglycaemia', 'Congenital anomalies'],
    },
    {
      id: 'paediatric-resp',
      name: 'Paediatric Respiratory',
      description: 'Respiratory conditions in children',
      diseaseCategories: ['Bronchiolitis', 'Paediatric asthma', 'Pneumonia', 'Croup', 'Foreign body aspiration', 'Tuberculosis in children', 'Whooping cough'],
    },
    {
      id: 'paediatric-infectious',
      name: 'Paediatric Infectious Disease',
      description: 'Infections common in the paediatric population',
      diseaseCategories: ['Febrile child', 'Meningitis/encephalitis', 'Sepsis in children', 'UTI in children', 'Measles', 'Mumps', 'Rubella', 'Varicella', 'Kawasaki disease'],
    },
    {
      id: 'paediatric-gastro',
      name: 'Paediatric Gastroenterology',
      description: 'Gastrointestinal and nutritional disorders in children',
      diseaseCategories: ['Acute gastroenteritis', 'Dehydration', 'Chronic diarrhoea', 'Coeliac disease', 'Food allergy', 'Infant colic', 'Constipation', 'Malnutrition'],
    },
    {
      id: 'paediatric-neuro',
      name: 'Paediatric Neurology',
      description: 'Neurological disorders in children',
      diseaseCategories: ['Febrile seizures', 'Epilepsy in children', 'Cerebral palsy', 'Developmental delay', 'ADHD', 'Autism spectrum disorder'],
    },
    {
      id: 'paediatric-cardio',
      name: 'Paediatric Cardiology',
      description: 'Congenital and acquired heart disease in children',
      diseaseCategories: ['Congenital heart disease', 'Ventricular septal defect', 'Atrial septal defect', 'Tetralogy of Fallot', 'Kawasaki disease', 'Rheumatic heart disease', 'Myocarditis'],
    },
    {
      id: 'paediatric-emergency',
      name: 'Paediatric Emergency & Critical Care',
      description: 'Acute presentations, resuscitation and critical illness in children',
      diseaseCategories: ['Paediatric trauma', 'Poisoning', 'Status epilepticus', 'Severe dehydration', 'DKA in children', 'Child abuse', 'Acute severe asthma'],
    },
    {
      id: 'adolescent',
      name: 'Adolescent Medicine',
      description: 'Health issues specific to adolescence',
      diseaseCategories: ['Growth and puberty disorders', 'Eating disorders', 'Menstrual disorders in adolescents', 'Vaccination', 'Mental health in adolescence'],
    },
    {
      id: 'paediatric-endocrinology',
      name: 'Paediatric Endocrinology',
      description: 'Endocrine and metabolic disorders in children',
      diseaseCategories: ['Type 1 diabetes', 'Diabetic ketoacidosis', 'Congenital hypothyroidism', 'Growth disorders', 'Precocious puberty', 'Delayed puberty', 'Adrenal insufficiency'],
    },
    {
      id: 'paediatric-haematology',
      name: 'Paediatric Haematology',
      description: 'Blood disorders in children',
      diseaseCategories: ['Sickle cell disease', 'Thalassaemia', 'Anaemia', 'Haemophilia', 'Idiopathic thrombocytopenic purpura', 'Neutropenia'],
    },
    {
      id: 'paediatric-nephrology',
      name: 'Paediatric Nephrology',
      description: 'Kidney and urinary tract disorders in children',
      diseaseCategories: ['Acute glomerulonephritis', 'Nephrotic syndrome', 'Urinary tract infection', 'Acute kidney injury', 'Chronic kidney disease', 'Hypertension in children'],
    },
    {
      id: 'paediatric-oncology',
      name: 'Paediatric Oncology',
      description: 'Childhood cancers and tumours',
      diseaseCategories: ['Leukaemia', 'Lymphoma', 'Wilms tumour', 'Neuroblastoma', 'Brain tumours in children', 'Bone tumours'],
    },
    {
      id: 'picu-nicu',
      name: 'PICU/NICU',
      description: 'Neonatal and paediatric intensive care',
      diseaseCategories: ['Respiratory failure', 'Cardiac failure', 'Shock', 'Post-cardiac surgery care', 'Status epilepticus', 'Septic shock'],
    },
    {
      id: 'developmental-pediatrics',
      name: 'Developmental Pediatrics',
      description: 'Developmental and behavioural disorders in children',
      diseaseCategories: ['Autism spectrum disorder', 'ADHD', 'Learning disabilities', 'Global developmental delay', 'Speech and language delay', 'Motor delay'],
    },
  ],
  commonSymptoms: [
    'fever', 'cough', 'difficulty_breathing', 'wheeze', 'stridor',
    'vomiting', 'diarrhoea', 'reduced_feeding', 'lethargy',
    'irritability', 'seizures', 'rash', 'cyanosis', 'jaundice',
    'poor_weight_gain', 'abdominal_pain', 'headache', 'sore_throat',
    'ear_pain', 'runny_nose', 'constipation', 'dysuria',
    'swollen_joints', 'limp', 'bruising', 'petechiae',
    'developmental_regression', 'excessive_crying',
  ],
  commonInvestigations: [
    'FBC', 'CRP', 'Blood culture', 'Urinalysis', 'Urine culture',
    'Chest X-ray', 'Stool culture', 'Lumbar puncture', 'CSF analysis',
    'Blood glucose', 'Blood gas', 'Electrolytes', 'LFT',
    'Rapid antigen tests', 'PCR for respiratory viruses',
    'Malarial smear', 'Mantoux/TST', 'Growth charts',
    'Newborn screening', 'Pulse oximetry', 'Abdominal ultrasound',
    'Echocardiogram', 'EEG', 'Developmental screening tools',
  ],
};
