import type { DepartmentDefinition } from './index';

export const pharmacy: DepartmentDefinition = {
  id: 'PHARM',
  name: 'Pharmacy & Clinical Pharmacology',
  shortName: 'PHARM',
  description: 'Clinical pharmacy services, medication management, pharmacovigilance, therapeutic drug monitoring and pharmaceutical care across all departments.',
  icon: '💊',
  color: '#8b5cf6',
  sections: [
    {
      id: 'clinical-pharmacy',
      name: 'Clinical Pharmacy',
      description: 'Ward-based clinical pharmacy, medication review, pharmaceutical care planning',
      diseaseCategories: ['Medication reconciliation', 'Prescription review and validation', 'Clinical pharmacy on ward rounds', 'Discharge medication planning', 'Medication history taking', 'Pharmaceutical care plans'],
    },
    {
      id: 'therapeutic-monitoring',
      name: 'Therapeutic Drug Monitoring',
      description: 'Monitoring drug levels to ensure therapeutic efficacy and avoid toxicity',
      diseaseCategories: ['Antibiotic TDM (vancomycin, gentamicin)', 'Anti-epileptic TDM (phenytoin, valproate)', 'Immunosuppressant TDM (tacrolimus, cyclosporine)', 'Lithium monitoring', 'Digoxin monitoring', 'Methotrexate monitoring'],
    },
    {
      id: 'pharmacovigilance',
      name: 'Pharmacovigilance & Drug Safety',
      description: 'Monitoring and prevention of adverse drug reactions and medication errors',
      diseaseCategories: ['Adverse drug reaction reporting', 'Medication error prevention', 'High-alert medication management', 'Look-alike sound-alike drug safety', 'Vaccine safety monitoring', 'Contraindicated drug combinations'],
    },
    {
      id: 'dispensing',
      name: 'Dispensing & Pharmaceutical Compounding',
      description: 'Accurate dispensing, labelling, extemporaneous preparation and sterile compounding',
      diseaseCategories: ['Inpatient dispensing', 'Outpatient dispensing', 'Extemporaneous compounding', 'Aseptic preparation (cytotoxics)', 'Total parenteral nutrition compounding', 'Clinical trial medication management'],
    },
    {
      id: 'formulary',
      name: 'Formulary & Medicines Management',
      description: 'Medicines selection, procurement, stock management and cost optimisation',
      diseaseCategories: ['Hospital formulary management', 'Medicines procurement and supply chain', 'Expensive medicine approval', 'Antimicrobial formulary restriction', 'Medicines shortage management', 'Non-formulary medicine requests'],
    },
    {
      id: 'patient-counselling',
      name: 'Patient Counselling & Medicines Optimisation',
      description: 'Patient education on medication use, adherence optimisation',
      diseaseCategories: ['Medication adherence support', 'Polypharmacy review and simplification', 'Inhaler technique counselling', 'Anticoagulation counselling', 'Polypharmacy in elderly', 'Medication passport/care record'],
    },
  ],
  commonSymptoms: [
    'adverse_drug_reaction', 'drug_allergy_suspected',
    'therapeutic_failure', 'supratherapeutic_level',
    'subtherapeutic_level', 'drug_interaction_concern',
    'medication_error', 'polypharmacy_concern',
    'dosing_in_renal_impairment', 'dosing_in_hepatic_impairment',
    'pregnancy_medication_safety', 'lactation_medication_safety',
    'paediatric_dosing', 'elderly_dosing_optimisation',
    'chemotherapy_dosing', 'antibiotic_stewardship_review',
    'anticoagulation_management', 'pain_medication_optimisation',
    'inhaler_technique_assessment', 'medication_adherence_issue',
    'high_cost_drug_approval', 'clinical_trial_medication',
  ],
  commonInvestigations: [
    'Drug level monitoring (vancomycin, gentamicin, lithium, digoxin, phenytoin)',
    'Creatinine clearance / eGFR for drug dosing', 'LFT for hepatotoxic drugs',
    'FBC for myelosuppressive drugs', 'Coagulation screen for anticoagulants',
    'QTc monitoring for proarrhythmic drugs',
    'TDM for immunosuppressants (tacrolimus, cyclosporine, sirolimus)',
    'Allergy history documentation and verification',
    'Medication reconciliation against accurate drug history',
    'BNF/Martindale drug interaction screening',
    'Antimicrobial sensitivity report review',
    'Pregnancy test for teratogenic medications',
    'Therapeutic drug monitoring peak/trough levels',
    'Pharmacogenomic testing (HLA-B*5701, TPMT, CYP2C19)',
    'Drug-induced electrolyte monitoring (K+, Mg++)',
    'IV compatibility checking for Y-site administration',
  ],
};
