import type { DepartmentDefinition } from './index';

export const radiology: DepartmentDefinition = {
  id: 'RAD',
  name: 'Radiology',
  shortName: 'RAD',
  description: 'Medical imaging interpretation and image-guided interventions across all modalities including X-ray, ultrasound, CT, MRI, nuclear medicine and interventional radiology.',
  icon: '📡',
  color: '#7c3aed',
  sections: [
    {
      id: 'general-radiography',
      name: 'General Radiography',
      description: 'Plain film X-ray interpretation across all body regions',
      diseaseCategories: ['Chest X-ray interpretation', 'Abdominal X-ray', 'Extremity fracture assessment', 'Spine X-ray', 'Skeletal survey', 'Arthrography'],
    },
    {
      id: 'cross-sectional',
      name: 'Cross-Sectional Imaging',
      description: 'CT and MRI interpretation by body region',
      diseaseCategories: ['CT head interpretation', 'CT chest', 'CT abdomen/pelvis', 'CT angiography', 'MRI brain', 'MRI spine', 'MRI musculoskeletal', 'MRI body'],
    },
    {
      id: 'ultrasound',
      name: 'Ultrasound',
      description: 'Diagnostic ultrasound across all applications',
      diseaseCategories: ['Abdominal ultrasound', 'Pelvic ultrasound', 'Obstetric ultrasound', 'Vascular doppler', 'Musculoskeletal ultrasound', 'Echocardiography', 'Breast ultrasound'],
    },
    {
      id: 'nuclear-medicine',
      name: 'Nuclear Medicine',
      description: 'Functional imaging using radiopharmaceuticals',
      diseaseCategories: ['Bone scan', 'PET CT oncology', 'Myocardial perfusion scan', 'Thyroid scan', 'Renal DTPA/MAG3', 'V/Q scan', 'Gallium scan', 'SPECT'],
    },
    {
      id: 'interventional',
      name: 'Interventional Radiology',
      description: 'Minimally invasive image-guided procedures',
      diseaseCategories: ['Biopsy (CT/US-guided)', 'Abscess drainage', 'Nephrostomy insertion', 'Central line insertion', 'Angioplasty and stenting', 'Embolisation procedures', 'Vertebroplasty', 'TIPS'],
    },
    {
      id: 'mammography',
      name: 'Mammography & Breast Imaging',
      description: 'Breast cancer screening and diagnostic breast imaging',
      diseaseCategories: ['Screening mammography', 'Diagnostic mammography', 'Breast tomosynthesis', 'Breast MRI', 'Ductography', 'Stereotactic biopsy'],
    },
    {
      id: 'paediatric-radiology',
      name: 'Paediatric Radiology',
      description: 'Imaging considerations in children',
      diseaseCategories: ['Paediatric chest imaging', 'Neonatal imaging', 'Paediatric skeletal imaging', 'Paediatric neuroimaging', 'Paediatric abdominal imaging'],
    },
  ],
  commonSymptoms: [
    'pain_requiring_imaging', 'mass_detected_on_exam',
    'fracture_suspected', 'dislocation_suspected', 'foreign_body',
    'haemorrhage_evaluation', 'ischaemia_evaluation',
    'infection_localisation', 'abscess_suspected',
    'tumour_staging', 'treatment_response_assessment',
    'screening_abnormality', 'inflammatory_changes',
    'obstruction_evaluation', 'perforation_suspected',
    'vascular_occlusion', 'aneurysm_screening',
    'pre_operative_mapping', 'image_guided_biopsy_needed',
    'image_guided_drainage_needed',
  ],
  commonInvestigations: [
    'Chest X-ray (PA/lateral)', 'Abdominal X-ray (erect/supine)',
    'Limb X-ray (AP/lateral/oblique)', 'Spine X-ray series',
    'CT head non-contrast', 'CT head with contrast',
    'CT chest abdomen pelvis', 'CT angiography', 'CT urogram',
    'MRI brain with/without contrast', 'MRI spine',
    'MRI knee/shoulder/hip', 'MRI abdomen',
    'Abdominal ultrasound', 'Vascular doppler ultrasound',
    'Obstetric ultrasound', 'Echocardiogram',
    'PET CT (FDG)', 'Bone scan (Tc-99m MDP)',
    'Mammogram (screening/diagnostic)',
    'Fluoroscopic studies (barium swallow/enema)',
    'DEXA bone density scan',
  ],
};
