// ─── AMEXAN — Summary Engine ────────────────────────────────────────────────
import { ConsultationContext, DiseaseScore, SeverityResult, ClinicalNote } from '@/src/types';
import { generateHPI } from './hpiGenerator';
import { getInvestigationsForDDx } from '@/src/data/respiratory/investigations';
import { getTreatmentPlan } from '@/src/data/respiratory/treatments';

// ─── Main entry: build the full clinical note ────────────────────────────────
export function buildClinicalNote(
  ctx: ConsultationContext,
  differentials: DiseaseScore[],
  severity: SeverityResult
): ClinicalNote {
  const topDx = differentials.filter(d => d.score > 0).slice(0, 3);
  const primaryDx = topDx[0];

  const hpi = generateHPI(ctx, topDx);

  const topIds = topDx.map(d => d.diseaseId);
  const investigations = getInvestigationsForDDx(topIds, 3)
    .map(inv => `[${inv.priority.toUpperCase()}] ${inv.name} — ${inv.rationale}`);

  const management = primaryDx
    ? getTreatmentPlan(primaryDx.diseaseId, severity.level).map(
        t => t.condition
          ? `${t.name}: ${t.detail} (if ${t.condition})`
          : `${t.name}: ${t.detail}`
      )
    : ['Supportive care — reassess when more information available'];

  const summary = buildSummary(ctx, topDx, severity);

  return {
    hpi,
    differentials: topDx,
    severity,
    investigations,
    management,
    summary,
    timestamp: new Date(),
  };
}

// ─── Summary paragraph ───────────────────────────────────────────────────────
function buildSummary(
  ctx: ConsultationContext,
  topDx: DiseaseScore[],
  severity: SeverityResult
): string {
  const age = ctx.age
    ? ctx.age < 24
      ? `${ctx.age}-month-old`
      : `${Math.floor(ctx.age / 12)}-year-old`
    : 'paediatric patient';

  const sex = ctx.sex ?? 'child';
  const primaryDx = topDx[0];
  const ddx2 = topDx[1];
  const ddx3 = topDx[2];

  const sxList = ctx.symptoms
    .map(s => s.replace(/_/g, ' '))
    .join(', ');

  const severityLabel = severity.level.toUpperCase();
  const flagText =
    severity.redFlags.length > 0
      ? ` Red flags present: ${severity.redFlags.join('; ')}.`
      : ' No immediate red flags identified.';

  const ddxText = [ddx2, ddx3]
    .filter(Boolean)
    .map(d => d!.name)
    .join(' and ');

  return [
    `${age.charAt(0).toUpperCase() + age.slice(1)} ${sex} presenting with ${sxList}.`,
    primaryDx
      ? `Working diagnosis: ${primaryDx.name} (${primaryDx.confidence} confidence).`
      : '',
    ddxText ? `Differentials include ${ddxText}.` : '',
    `Severity assessment: ${severityLabel}.${flagText}`,
    severity.action,
  ]
    .filter(Boolean)
    .join(' ');
}

// ─── SOAP note formatter ─────────────────────────────────────────────────────
export function formatSOAP(note: ClinicalNote, patientName?: string): string {
  const line = '─'.repeat(60);
  const ts = note.timestamp.toLocaleString();
  const header = patientName
    ? `AMEXAN Clinical Note — ${patientName} — ${ts}`
    : `AMEXAN Clinical Note — ${ts}`;

  const ddxLines = note.differentials
    .map((d, i) => `  ${i + 1}. ${d.name} [${d.confidence.toUpperCase()} — score: ${d.score}]`)
    .join('\n');

  const invLines = note.investigations
    .map(i => `  • ${i}`)
    .join('\n');

  const mgtLines = note.management
    .map(m => `  • ${m}`)
    .join('\n');

  const flagLines =
    note.severity.redFlags.length > 0
      ? note.severity.redFlags.map(f => `  ⚠ ${f}`).join('\n')
      : '  None identified';

  return `
${header}
${line}

SUBJECTIVE (HPI)
${note.hpi}

OBJECTIVE / SEVERITY
  Level: ${note.severity.level.toUpperCase()}
  Action: ${note.severity.action}
  Red flags:
${flagLines}

ASSESSMENT (Differential Diagnoses)
${ddxLines}

PLAN — Investigations
${invLines}

PLAN — Management
${mgtLines}

SUMMARY
${note.summary}

${line}
Generated by AMEXAN Reasoning Engine
`.trim();
}