interface ClerkingInput {
  patientName: string;
  patientId: string;
  unitSlug: string;
  consultant: string;
  encounterType: string;
  registration: {
    ward: string;
    bed: string;
    surgicalRisk?: { bloodGroup?: string; allergies?: string[]; anticoagulants?: string[]; previousSurgery?: boolean };
  };
  presentingComplaint: { complaint: string; duration: string; severity: number };
  hpi: { question: string; answer: string | boolean }[];
  exam: { findingText: string; present?: boolean; value?: number; comment?: string }[];
  ddx: { diseaseName: string; probability: number }[];
  treatment?: { items: string[] }[];
}

export function generateClerkingNote(input: ClerkingInput): string {
  const { patientName, patientId, unitSlug, consultant, encounterType, registration, presentingComplaint, hpi, exam, ddx, treatment } = input;
  const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });

  const sections: string[] = [
    `# CLERKING NOTE — SURGERY`,
    ``,
    `**Patient:** ${patientName} (MRN: ${patientId})`,
    `**Date:** ${date}`,
    `**Unit:** ${unitSlug.replace(/-/g, ' ')} | **Consultant:** ${consultant}`,
    `**Encounter Type:** ${encounterType.replace(/_/g, ' ')}`,
    `**Ward:** ${registration.ward} | **Bed:** ${registration.bed}`,
    ``,
    `---`,
    ``,
    `## Presenting Complaint`,
    `${presentingComplaint.complaint} x ${presentingComplaint.duration}, severity ${presentingComplaint.severity}/10`,
    ``,
  ];

  if (registration.surgicalRisk) {
    const r = registration.surgicalRisk;
    sections.push(`## Surgical Risk Assessment`);
    if (r.bloodGroup) sections.push(`- **Blood Group:** ${r.bloodGroup}`);
    if (r.allergies?.length) sections.push(`- **Allergies:** ${r.allergies.join(', ')}`);
    if (r.anticoagulants?.length) sections.push(`- **Anticoagulants:** ${r.anticoagulants.join(', ')}`);
    if (r.previousSurgery !== undefined) sections.push(`- **Previous Surgery:** ${r.previousSurgery ? 'Yes' : 'No'}`);
    sections.push(``);
  }

  if (hpi.length > 0) {
    sections.push(`## History of Presenting Illness`);
    for (const h of hpi) {
      sections.push(`- ${h.question}: ${typeof h.answer === 'boolean' ? (h.answer ? 'Yes' : 'No') : h.answer}`);
    }
    sections.push(``);
  }

  if (exam.length > 0) {
    sections.push(`## Examination Findings`);
    for (const e of exam) {
      const status = e.present === true ? 'Present' : e.present === false ? 'Absent' : 'Not examined';
      const val = e.value ? ` (${e.value})` : '';
      const comment = e.comment ? ` — ${e.comment}` : '';
      sections.push(`- ${e.findingText}: ${status}${val}${comment}`);
    }
    sections.push(``);
  }

  if (ddx.length > 0) {
    sections.push(`## Differential Diagnosis`);
    for (const d of ddx) {
      sections.push(`- ${d.diseaseName}: ${d.probability}%`);
    }
    sections.push(``);
  }

  if (treatment && treatment.length > 0 && treatment[0].items.length > 0) {
    sections.push(`## Initial Plan`);
    for (const item of treatment[0].items) {
      sections.push(`- ${item}`);
    }
    sections.push(``);
  }

  sections.push(`---`);
  sections.push(`*Generated by AMEXAN Clinical Reasoning System*`);

  return sections.join('\n');
}
