interface ConsentInput {
  patientName: string;
  patientId: string;
  dateOfBirth?: string;
  procedure: string;
  diagnosis: string;
  surgeon: string;
  hospital: string;
  anaesthesia: string;
  benefits: string[];
  risks: string[];
  alternatives: string[];
  specificRisks?: string[];
  templateSteps?: string[];
  interpreter?: string;
  witnessName?: string;
}

export function generateConsentForm(input: ConsentInput): string {
  const date = new Date().toLocaleDateString('en-GB', {
    day: 'numeric', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });

  const sections: string[] = [
    `# CONSENT FORM — SURGERY`,
    ``,
    `**Hospital:** ${input.hospital}`,
    `**Date:** ${date}`,
    ``,
    `---`,
    ``,
    `## Section 1: Patient Details`,
    ``,
    `**Name:** ${input.patientName}`,
    `**MRN:** ${input.patientId}`,
    input.dateOfBirth ? `**Date of Birth:** ${input.dateOfBirth}` : '',
    ``,
    `## Section 2: Diagnosis & Procedure`,
    ``,
    `**Diagnosis:** ${input.diagnosis}`,
    ``,
    `**Proposed Procedure:** ${input.procedure}`,
    ``,
    `**Anaesthesia:** ${input.anaesthesia}`,
    ``,
    `**Surgeon:** ${input.surgeon}`,
    ``,
    `## Section 3: Explanation of Procedure`,
    ``,
    `The nature and purpose of the procedure have been explained to the patient.`,
    ``,
    input.templateSteps && input.templateSteps.length > 0
      ? [`The procedure involves:`, ...input.templateSteps.map((s, i) => `  ${i + 1}. ${s}`), ``].join('\n')
      : '',
    `## Section 4: Intended Benefits`,
    ``,
    ...input.benefits.map((b) => `- ${b}`),
    ``,
    `## Section 5: Risks and Complications`,
    ``,
    `The following risks have been explained to the patient:`,
    ``,
    ...input.risks.map((r) => `- ${r}`),
    ``,
    input.specificRisks && input.specificRisks.length > 0
      ? [`**Procedure-specific risks:**`, ...input.specificRisks.map((r) => `- ${r}`), ``].join('\n')
      : '',
    `## Section 6: Alternative Options`,
    ``,
    `The following alternatives have been discussed:`,
    ``,
    ...input.alternatives.map((a) => `- ${a}`),
    ``,
    `## Section 7: Patient Confirmation`,
    ``,
    [
      `I, **${input.patientName}**, confirm that:`,
      `- I have been given time to read this consent form`,
      `- I have had the opportunity to ask questions`,
      `- I understand the procedure, its benefits, risks, and alternatives`,
      `- I understand that I may withdraw consent at any time`,
      `- I consent to the procedure described above`,
    ].join('\n'),
    ``,
    ``,
    `**Patient Signature:** _________________________  **Date:** _______________`,
    ``,
    `## Section 8: Healthcare Professional Confirmation`,
    ``,
    [
      `I have explained the procedure, risks, benefits, and alternatives to the patient.`,
      `I believe the patient understands and has given informed consent.`,
    ].join('\n'),
    ``,
    ``,
    `**Doctor Name:** ${input.surgeon}`,
    `**Signature:** _________________________  **Date:** _______________`,
    ``,
    input.interpreter
      ? [
          `## Section 9: Interpreter Declaration`,
          ``,
          `I, **${input.interpreter}**, interpreted the above information to the patient in a language they understand.`,
          ``,
          `**Interpreter Signature:** _________________________  **Date:** _______________`,
        ].join('\n')
      : '',
    input.witnessName
      ? [
          ``,
          `## Witness Statement`,
          ``,
          `I, **${input.witnessName}**, witnessed the consent discussion and confirm the patient voluntarily consented.`,
          ``,
          `**Witness Signature:** _________________________  **Date:** _______________`,
        ].join('\n')
      : '',
    ``,
    `---`,
    `*Generated by AMEXAN Clinical Reasoning System*`,
  ];

  return sections.filter(Boolean).join('\n');
}

export function generateConsentFromTemplate(
  diseaseName: string,
  procedure: string,
  patientName: string,
  patientId: string,
  surgeon: string,
  hospital: string,
): ConsentInput {
  const commonRisks = [
    'Bleeding (haemorrhage) requiring transfusion',
    'Infection (wound infection, deep infection)',
    'Reaction to anaesthesia',
    'Blood clots (DVT/PE)',
    'Scarring and adhesions',
    'Damage to surrounding structures',
  ];

  return {
    patientName,
    patientId,
    procedure,
    diagnosis: diseaseName,
    surgeon,
    hospital,
    anaesthesia: 'General anaesthesia',
    benefits: [
      `Treatment of ${diseaseName}`,
      'Relief of symptoms',
      'Prevention of disease progression',
    ],
    risks: commonRisks,
    alternatives: [
      'Conservative (non-surgical) management',
      'Medical therapy',
      'Observation with monitoring',
      'Alternative surgical approach',
    ],
  };
}
