interface DischargeInput {
  patientName: string;
  patientId: string;
  unitSlug: string;
  primaryDiagnosis: string;
  secondaryDiagnoses: string[];
  admissionDate: string;
  dischargeDate: string;
  proceduresPerformed: string[];
  hospitalCourse: string;
  dischargeMedications: string[];
  dischargeInstructions: string[];
  followUp: string;
  warningSigns: string[];
}

export function generateDischargeSummary(input: DischargeInput): string {
  return [
    `# DISCHARGE SUMMARY`,
    ``,
    `**Patient:** ${input.patientName} (MRN: ${input.patientId})`,
    `**Unit:** ${input.unitSlug.replace(/-/g, ' ')}`,
    `**Admission:** ${input.admissionDate}`,
    `**Discharge:** ${input.dischargeDate}`,
    ``,
    `---`,
    ``,
    `## Diagnoses`,
    `**Primary:** ${input.primaryDiagnosis}`,
    input.secondaryDiagnoses.length > 0
      ? `**Secondary:** ${input.secondaryDiagnoses.map((d) => `\n- ${d}`).join('')}`
      : '',
    ``,
    `## Procedures Performed`,
    input.proceduresPerformed.length > 0
      ? input.proceduresPerformed.map((p) => `- ${p}`).join('\n')
      : 'None',
    ``,
    `## Hospital Course`,
    input.hospitalCourse || 'See clinical notes for full details.',
    ``,
    `## Discharge Medications`,
    input.dischargeMedications.length > 0
      ? input.dischargeMedications.map((m) => `- ${m}`).join('\n')
      : 'None',
    ``,
    `## Discharge Instructions`,
    input.dischargeInstructions.length > 0
      ? input.dischargeInstructions.map((i) => `- ${i}`).join('\n')
      : 'Routine post-operative care as discussed.',
    ``,
    `## Follow-up`,
    input.followUp || 'To be reviewed in surgical outpatients in 2 weeks.',
    ``,
    `## Warning Signs (return to ED if)`,
    input.warningSigns.length > 0
      ? input.warningSigns.map((w) => `- ${w}`).join('\n')
      : '- Worsening pain\n- Fever >38°C\n- Wound discharge or bleeding\n- Inability to tolerate oral intake',
    ``,
    `---`,
    `*Generated by AMEXAN Clinical Reasoning System*`,
  ].filter(Boolean).join('\n');
}
