interface OperativeInput {
  preOpDiagnosis: string;
  postOpDiagnosis: string;
  procedure: string;
  surgeon: string;
  assistant: string;
  anaesthesia: string;
  findings: string;
  procedureDetails: string;
  bloodLoss: string;
  specimens: string[];
  complications: string[];
  disposition: string;
  templateDisease?: string;
}

export function generateOperativeNote(input: OperativeInput): string {
  const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });

  return [
    `# OPERATIVE NOTE`,
    ``,
    `**Date:** ${date}`,
    ``,
    `---`,
    ``,
    `**Pre-operative Diagnosis:** ${input.preOpDiagnosis}`,
    ``,
    `**Post-operative Diagnosis:** ${input.postOpDiagnosis}`,
    ``,
    `**Procedure:** ${input.procedure}`,
    ``,
    `**Surgeon:** ${input.surgeon}`,
    ``,
    `**Assistant:** ${input.assistant}`,
    ``,
    `**Anaesthesia:** ${input.anaesthesia}`,
    ``,
    `---`,
    ``,
    `## Findings`,
    input.findings,
    ``,
    `## Procedure Details`,
    input.procedureDetails,
    ``,
    `## Blood Loss`,
    input.bloodLoss,
    ``,
    `## Specimens`,
    input.specimens.length > 0 ? input.specimens.map((s) => `- ${s}`).join('\n') : 'None',
    ``,
    `## Complications`,
    input.complications.length > 0 ? input.complications.map((c) => `- ${c}`).join('\n') : 'None',
    ``,
    `## Disposition`,
    input.disposition,
    ``,
    `---`,
    `*Generated by AMEXAN Clinical Reasoning System*`,
  ].join('\n');
}

export function generateOperativeNoteFromTemplate(
  diseaseName: string,
  templateSteps: string[],
  surgeon: string,
): OperativeInput {
  return {
    preOpDiagnosis: diseaseName,
    postOpDiagnosis: diseaseName,
    procedure: `Surgery for ${diseaseName}`,
    surgeon,
    assistant: '',
    anaesthesia: 'General anaesthesia',
    findings: `Intra-operative findings consistent with ${diseaseName}`,
    procedureDetails: templateSteps.join('\n'),
    bloodLoss: 'Minimal (<100 mL)',
    specimens: [],
    complications: [],
    disposition: 'To ward for post-operative recovery',
    templateDisease: diseaseName,
  };
}
