interface ReferralInput {
  patientName: string;
  patientId: string;
  referringDoctor: string;
  referredTo: string;
  specialty: string;
  reason: string;
  urgency: 'routine' | 'urgent' | 'emergency';
  clinicalSummary: string;
  relevantHistory: string;
  relevantExams: string;
  investigations: string;
  medications: string;
  suggestedPlan: string;
}

export function generateReferralNote(input: ReferralInput): string {
  return [
    `# REFERRAL NOTE`,
    ``,
    `**Patient:** ${input.patientName} (MRN: ${input.patientId})`,
    `**Referring Doctor:** ${input.referringDoctor}`,
    `**Referred To:** ${input.referredTo} (${input.specialty})`,
    `**Urgency:** ${input.urgency.toUpperCase()}`,
    ``,
    `---`,
    ``,
    `## Reason for Referral`,
    input.reason,
    ``,
    `## Clinical Summary`,
    input.clinicalSummary,
    ``,
    `## Relevant History`,
    input.relevantHistory || 'See clinical notes.',
    ``,
    `## Relevant Examination Findings`,
    input.relevantExams || 'See clinical notes.',
    ``,
    `## Investigations`,
    input.investigations || 'Pending.',
    ``,
    `## Current Medications`,
    input.medications || 'None.',
    ``,
    `## Suggested Plan`,
    input.suggestedPlan || 'Awaiting specialist review.',
    ``,
    `---`,
    `*Generated by AMEXAN Clinical Reasoning System*`,
  ].join('\n');
}
