interface WardRoundInput {
  patientName: string;
  patientId: string;
  unitSlug: string;
  date: string;
  subjective: string;
  objective: string;
  assessment: string;
  plan: string;
  author: string;
  version: number;
  vitals?: { bp: string; hr: number; rr: number; temp: number; spo2: number };
}

export function generateWardRoundNote(input: WardRoundInput): string {
  const sections: string[] = [
    `# WARD ROUND NOTE — v${input.version}`,
    ``,
    `**Patient:** ${input.patientName} (MRN: ${input.patientId})`,
    `**Unit:** ${input.unitSlug.replace(/-/g, ' ')}`,
    `**Date:** ${input.date}`,
    `**Clinician:** ${input.author}`,
    ``,
    `---`,
    ``,
  ];

  if (input.vitals) {
    sections.push(`## Vital Signs`);
    sections.push(`- BP: ${input.vitals.bp}`);
    sections.push(`- HR: ${input.vitals.hr} bpm`);
    sections.push(`- RR: ${input.vitals.rr} /min`);
    sections.push(`- Temp: ${input.vitals.temp}°C`);
    sections.push(`- SpO2: ${input.vitals.spo2}%`);
    sections.push(``);
  }

  sections.push(`## Subjective`);
  sections.push(input.subjective || 'Patient reports...');
  sections.push(``);
  sections.push(`## Objective`);
  sections.push(input.objective || 'Examination findings...');
  sections.push(``);
  sections.push(`## Assessment`);
  sections.push(input.assessment || 'Clinical impression...');
  sections.push(``);
  sections.push(`## Plan`);
  sections.push(input.plan || 'Plan...');
  sections.push(``);
  sections.push(`---`);
  sections.push(`*Generated by AMEXAN Clinical Reasoning System*`);

  return sections.join('\n');
}
