// ═══════════════════════════════════════════════════════════════
// AMEXAN UCOS — COUGH DISEASE CONTEXT PROFILES (PART 1)
// TB, CAP, Asthma, COPD, Bronchiectasis, Lung Cancer, HF
// ═══════════════════════════════════════════════════════════════

import type { ContextAwareDiseaseProfile, ContextOverride } from './cough-context-architecture';

const PREGNANCY_CXR_SAFE: Partial<ContextOverride> = {
  investigationAdditions: ['chest_xray_shielded'],
  investigationRemovals: ['ct_chest', 'ctpa'],
  cxrInterpretationModifiers: ['pregnancy_physiological_changes_may_mimic_disease'],
  contraindications: ['doxycycline', 'fluoroquinolones', 'streptomycin'],
};

const HIV_CONTEXT_SHARED: Partial<ContextOverride> = {
  questionAdditions: ['cd4_count_most_recent', 'art_regimen', 'art_adherence', 'oi_prophylaxis'],
  examAdditions: ['oral_cavity_inspection', 'full_lymph_node_survey', 'skin_exam_for_ks'],
  mechanismWeightDeltas: { alveolar_inflammation: 0.2, neoplastic_infiltration: 0.15 },
  activationThresholdDelta: -0.1,
  monitoringAdditions: ['cd4_monthly', 'viral_load', 'art_adherence_check'],
};

const ICU_SHARED: Partial<ContextOverride> = {
  questionRemovals: ['cough_severity', 'cough_timing', 'cough_feeding_difficulty'],
  examAdditions: ['ventilator_assessment', 'hemodynamic_monitoring', 'sedation_assessment'],
  investigationAdditions: ['bal', 'eta', 'abg', 'procalcitonin'],
  dispositionChanges: { icuRequired: true },
  monitoringAdditions: ['ventilator_settings', 'hemodynamics_continuous', 'abg_6hourly'],
  hideRules: ['self_reported_symptoms_unreliable_icu'],
};

const RENAL_ADJUSTMENTS: Partial<ContextOverride> = {
  contraindications: ['aminoglycosides', 'nsaids'],
  monitoringAdditions: ['renal_function_daily', 'fluid_balance', 'electrolytes_daily'],
  dispositionChanges: { specialtyReferral: 'nephrology' },
};

const DIABETES_ADJUSTMENTS: Partial<ContextOverride> = {
  investigationAdditions: ['hba1c', 'blood_glucose_monitoring'],
  monitoringAdditions: ['blood_glucose_4hourly'],
};

// ═══════════════════════════════════════════════════════════════
// PROFILE 1: TUBERCULOSIS
// ═══════════════════════════════════════════════════════════════

export const TB_CONTEXT_PROFILE: ContextAwareDiseaseProfile = {
  diseaseId: 'tb',
  diseaseName: 'Pulmonary Tuberculosis',
  master: {
    organism: 'Mycobacterium tuberculosis complex',
    transmission: 'Airborne droplet nuclei',
    corePathophysiology: 'Type IV hypersensitivity, granuloma formation, caseous necrosis',
    naturalHistory: 'Primary infection → latent TB → reactivation (5-10%). Higher risk with HIV, malnutrition, diabetes.',
    universalComplications: ['Hemoptysis', 'Bronchiectasis', 'Empyema', 'Miliary dissemination', 'TB meningitis', 'IRIS'],
    universalMechanisms: ['alveolar_inflammation', 'neoplastic_infiltration'],
    universalPhenotypes: ['cough_chronic', 'cough_hemoptysis', 'cough_constitutional'],
  },
  baseline: {
    epidemiology: 'Leading infectious killer. 10M cases/year.',
    symptomOnset: 'Insidious over weeks to months',
    typicalPresentation: 'Chronic cough >2 weeks, night sweats, weight loss, fever, hemoptysis',
    discriminatingFeatures: ['cough_>2weeks', 'night_sweats', 'weight_loss', 'hemoptysis', 'tb_contact'],
    basePrevalence: 0.08,
    agePrevalenceModifiers: { adult: 0.10, older_adult: 0.08, adolescent: 0.05 },
    typicalPhenotypes: ['cough_chronic', 'cough_hemoptysis'],
    commonMechanisms: ['alveolar_inflammation', 'neoplastic_infiltration'],
    requiredQuestions: ['cough_duration', 'cough_sputum', 'cough_night_sweats', 'cough_weight_loss', 'cough_tb_contact', 'cough_hiv_status', 'cough_fever'],
    requiredExams: ['chest_auscultation', 'lymph_nodes', 'clubbing', 'weight_assessment', 'temperature'],
    initialInvestigations: ['chest_xray', 'genexpert'],
    confirmatoryInvestigations: ['tb_culture', 'ct_chest'],
    treatmentLines: [
      { line: 1, regimen: 'RHZE 2mo / RH 4mo', medications: ['rifampicin', 'isoniazid', 'pyrazinamide', 'ethambutol'], duration: '6mo' },
      { line: 2, regimen: 'MDR-TB per WHO', medications: ['mdr_drugs'], duration: '9-12mo' },
    ],
    supportiveCare: ['pyridoxine', 'nutritional_support', 'dot'],
    disposition: { admissionRequired: false, icuRequired: false, specialty: 'tb_clinic', followUp: 'Monthly 6mo' },
    monitoring: [
      { parameter: 'Sputum AFB', frequency: 'Monthly', target: 'Conversion by 2mo' },
      { parameter: 'Weight', frequency: 'Monthly', target: 'Stable/gaining' },
      { parameter: 'LFT', frequency: 'Monthly', target: 'Normal' },
    ],
    urgency: 'yellow',
    activationThreshold: 0.25,
    guidelines: ['who_tb_2024'],
    hmisEvents: ['tb_suspected', 'tb_confirmed'],
  },
  ageGroupToContext: {
    neonate: 'pediatric_infant', infant: 'pediatric_infant', toddler: 'pediatric_toddler',
    preschool: 'pediatric_preschool', school_age: 'pediatric_school', adolescent: 'pediatric_adolescent',
    adult: 'adult_immunocompetent', older_adult: 'elderly_>65',
  },
  relevantContexts: [],
  excludedContexts: [],
  contextOverrides: [
    {
      context: 'pediatric_infant', applicabilityWeight: 1.0,
      questionRemovals: ['cough_smoking', 'cough_occupational_exposure', 'cough_hemoptysis_detail'],
      questionAdditions: ['bcg_scar', 'tb_contact_duration', 'playmates_coughing', 'failure_to_thrive', 'poor_feeding'],
      questionPriorityOverrides: { cough_night_sweats: 'critical', cough_weight_loss: 'critical' },
      examAdditions: ['growth_chart_review', 'nutrition_assessment', 'lymph_node_palpation', 'bcg_scar_check'],
      phenotypeActivations: ['cough_with_failure_to_thrive', 'cough_with_lymphadenopathy', 'cough_miliary'],
      mechanismWeightDeltas: { alveolar_inflammation: 0.2, neoplastic_infiltration: -0.1 },
      investigationAdditions: ['gastric_aspirate_genexpert', 'tst', 'igra'],
      investigationRemovals: ['sputum_afb'],
      cxrInterpretationModifiers: ['pediatric_lymphadenopathy_common_80%', 'ghon_complex', 'miliary_more_common'],
      treatmentDoseChanges: { all: 'weight_band_dosing_per_who' },
      monitoringAdditions: ['weight_weekly_first_2mo', 'nutrition_assessment_weekly'],
      dispositionChanges: { specialtyReferral: 'pediatric_tb_clinic' },
      activationThresholdDelta: -0.05,
      differentialAdditions: [{ diseaseId: 'ntm_lymphadenitis', weight: 0.3 }, { diseaseId: 'hiv_lymphoid_interstitial_pneumonitis', weight: 0.2 }, { diseaseId: 'malnutrition_cough', weight: 0.3 }],
      differentialRemovals: ['lung_cancer', 'copd_exacerbation'],
      clinicalNotes: 'Pediatric TB: 50% have no cough. TB score system. Miliary more common. CXR lymphadenopathy 80%. Gastric aspirate preferred.',
    },
    {
      context: 'pediatric_toddler', applicabilityWeight: 1.0,
      questionRemovals: ['cough_smoking', 'cough_occupational_exposure'],
      questionAdditions: ['bcg_scar', 'tb_contact_duration', 'failure_to_thrive'],
      examAdditions: ['growth_chart', 'nutrition_assessment', 'lymph_node_exam'],
      phenotypeActivations: ['cough_with_failure_to_thrive', 'cough_with_lymphadenopathy'],
      investigationAdditions: ['gastric_aspirate_genexpert', 'tst'],
      investigationRemovals: ['sputum_afb'],
      treatmentDoseChanges: { all: 'weight_band_dosing' },
      differentialAdditions: [{ diseaseId: 'ntm_lymphadenitis', weight: 0.25 }],
      differentialRemovals: ['lung_cancer'],
    },
    {
      context: 'pediatric_school', applicabilityWeight: 1.0,
      questionAdditions: ['school_attendance', 'contact_screening', 'bcg_scar'],
      examAdditions: ['growth_assessment', 'lymph_node_exam'],
      investigationAdditions: ['tst', 'igra'],
      treatmentDoseChanges: { all: 'weight_band_dosing' },
    },
    {
      context: 'pregnancy', applicabilityWeight: 1.0,
      questionAdditions: ['gestational_age', 'fetal_movements', 'vaginal_bleeding', 'preeclampsia_symptoms'],
      questionPriorityOverrides: { cough_dyspnea: 'critical' },
      examAdditions: ['fetal_heart_rate', 'obstetric_referral', 'oxygen_saturation'],
      mechanismWeightDeltas: { alveolar_inflammation: 0.15 },
      investigationAdditions: ['chest_xray_shielded'],
      cxrInterpretationModifiers: ['pregnancy_physiological_changes_may_mimic_disease'],
      contraindications: ['streptomycin'],
      monitoringAdditions: ['fetal_ultrasound_3rd_trimester', 'nutritional_supplementation'],
      dispositionChanges: { specialtyReferral: 'obstetrics_and_tb' },
      urgencyOverride: 'orange',
      activationThresholdDelta: -0.05,
      differentialAdditions: [{ diseaseId: 'pe', weight: 0.4 }, { diseaseId: 'peripartum_cardiomyopathy', weight: 0.3 }],
      clinicalNotes: 'Pregnancy TB: RHZE all safe. CXR with shielding. Streptomycin contraindicated. Higher risk of miliary.',
    },
    {
      context: 'postpartum', applicabilityWeight: 0.7,
      questionAdditions: ['breastfeeding', 'postpartum_depression_screening', 'infant_health'],
      examAdditions: ['fundal_height', 'breast_exam'],
      monitoringAdditions: ['postpartum_depression_screening', 'infant_tb_screening'],
      activationThresholdDelta: -0.05,
    },
    {
      context: 'hiv_cd4_very_low', applicabilityWeight: 1.0,
      ...HIV_CONTEXT_SHARED,
      activationThresholdDelta: -0.15,
      phenotypeActivations: ['cough_hiv_disseminated', 'cough_miliary', 'cough_iris'],
      investigationAdditions: ['cd4_count', 'viral_load', 'pcp_prophylaxis_check'],
      cxrInterpretationModifiers: ['cxr_may_be_normal_in_hiv_tb_20%', 'atypical_lower_lobe'],
      treatmentAdditions: [{ drugId: 'prednisolone_for_iris', line: 2, notes: 'IRIS: 1.5mg/kg 2wk then taper' }],
      interactions: ['rifampicin_reduces_dolutegravir', 'boosted_pi_dose_adjustment'],
      monitoringAdditions: ['weekly_review_first_2mo', 'iris_monitoring', 'art_adherence'],
      differentialAdditions: [{ diseaseId: 'pcp', weight: 0.6 }, { diseaseId: 'cmv_pneumonitis', weight: 0.3 }, { diseaseId: 'fungal_pneumonia', weight: 0.3 }, { diseaseId: 'bacterial_pneumonia', weight: 0.4 }],
      clinicalNotes: 'HIV-TB: CXR normal in 20%. Miliary common. IRIS common. Drug interactions with ART.',
    },
    {
      context: 'hiv_cd4_low', applicabilityWeight: 1.0,
      ...HIV_CONTEXT_SHARED,
      activationThresholdDelta: -0.1,
      phenotypeActivations: ['cough_hiv_disseminated'],
      differentialAdditions: [{ diseaseId: 'pcp', weight: 0.4 }, { diseaseId: 'bacterial_pneumonia', weight: 0.3 }],
    },
    {
      context: 'hiv_iris_risk', applicabilityWeight: 1.0,
      questionAdditions: ['art_start_date', 'symptom_worsening_since_art'],
      phenotypeActivations: ['cough_iris'],
      treatmentAdditions: [{ drugId: 'prednisolone', line: 2, notes: 'IRIS: 1.5mg/kg 2wk then taper' }],
      monitoringAdditions: ['iris_symptom_diary', 'weekly_review'],
    },
    {
      context: 'elderly_>65', applicabilityWeight: 0.8,
      questionAdditions: ['functional_status', 'caregiver_support', 'aspiration_risk', 'medication_list'],
      examAdditions: ['swallow_assessment', 'cognitive_assessment'],
      monitoringAdditions: ['functional_status_daily'],
      activationThresholdDelta: -0.05,
      differentialAdditions: [{ diseaseId: 'aspiration_pneumonia', weight: 0.4 }, { diseaseId: 'lung_cancer', weight: 0.3 }],
      clinicalNotes: 'Elderly TB: Atypical — no fever in 30%. Weight loss only sign. Hepatotoxicity more common.',
    },
    {
      context: 'icu_ventilated', applicabilityWeight: 0.8,
      ...ICU_SHARED,
      questionAdditions: ['tb_risk_factors_from_chart', 'hiv_status_from_chart'],
      investigationAdditions: ['bal_genexpert', 'bal_tb_culture', 'ct_chest_portable'],
      phenotypeActivations: ['cough_icu_ards', 'cough_icu_miliary_with_ards'],
      treatmentAdditions: [{ drugId: 'iv_rhze', line: 1, notes: 'IV if unable PO' }],
      dispositionChanges: { icuRequired: true },
      urgencyOverride: 'red',
    },
    {
      context: 'renal_failure', applicabilityWeight: 0.7,
      ...RENAL_ADJUSTMENTS,
      treatmentDoseChanges: { isoniazid: 'reduce_gfr_<10', pyrazinamide: 'reduce_gfr_<30', ethambutol: 'reduce_gfr_<50', rifampicin: 'no_adjustment' },
      clinicalNotes: 'Renal TB: Ethambutol accumulates — monitor vision. RHZ adjusted for GFR.',
    },
    {
      context: 'liver_disease', applicabilityWeight: 0.7,
      contraindications: ['isoniazid', 'pyrazinamide', 'rifampicin'],
      treatmentAdditions: [
        { drugId: 'streptomycin', line: 1, notes: 'Hepatotoxic-sparing' },
        { drugId: 'levofloxacin', line: 1, notes: 'Part of hepatotoxic-sparing regimen' },
      ],
      monitoringAdditions: ['lft_weekly', 'inr_daily', 'encephalopathy_assessment'],
      clinicalNotes: 'Liver disease TB: Hepatotoxic-sparing regimen. Rifampicin safest first-line but monitor LFT.',
    },
    {
      context: 'diabetes', applicabilityWeight: 0.7,
      ...DIABETES_ADJUSTMENTS,
      activationThresholdDelta: -0.05,
      clinicalNotes: 'Diabetes-TB: Triple risk. Rifampicin reduces sulfonylurea effectiveness.',
    },
    {
      context: 'malnutrition', applicabilityWeight: 0.8,
      questionAdditions: ['muac', 'edema_assessment', 'dietary_intake'],
      examAdditions: ['muac_measurement', 'edema_assessment', 'anthropometry'],
      investigationAdditions: ['albumin', 'prealbumin'],
      treatmentAdditions: [{ drugId: 'nutritional_rehabilitation', line: 1, notes: 'Concurrent nutritional support critical' }],
      monitoringAdditions: ['weight_weekly', 'muac_weekly'],
      activationThresholdDelta: -0.1,
    },
    {
      context: 'transplant', applicabilityWeight: 0.9,
      questionAdditions: ['transplant_type', 'immunosuppression_regimen', 'donor_tb_status'],
      interactions: ['rifampicin_reduces_calcineurin_inhibitors_dramatically'],
      monitoringAdditions: ['immunosuppression_levels_weekly', 'graft_function_weekly'],
      dispositionChanges: { specialtyReferral: 'transplant_id' },
      activationThresholdDelta: -0.1,
      clinicalNotes: 'Transplant TB: Rifampicin dramatically reduces tacrolimus/cyclosporine. Triple interaction.',
    },
    {
      context: 'oncology_chemo', applicabilityWeight: 0.7,
      questionAdditions: ['chemo_regimen', 'neutropenic_status', 'radiation_history'],
      investigationAdditions: ['neutrophil_count', 'ct_chest', 'bronchoscopy_bal'],
      differentialAdditions: [
        { diseaseId: 'chemo_induced_pneumonitis', weight: 0.5 },
        { diseaseId: 'radiation_pneumonitis', weight: 0.4 },
        { diseaseId: 'fungal_pneumonia', weight: 0.4 },
      ],
    },
    {
      context: 'healthcare_worker', applicabilityWeight: 0.6,
      questionAdditions: ['occupational_exposure_duration', 'previous_tst_conversion', 'mask_usage'],
      investigationAdditions: ['tst', 'igra', 'occupational_health_referral'],
      hmisEventAdditions: ['occupational_exposure_reporting'],
    },
    {
      context: 'endemic_tb_high', applicabilityWeight: 0.8,
      activationThresholdDelta: -0.1,
      clinicalNotes: 'Endemic TB: Every chronic cough is TB until proven otherwise.',
    },
    {
      context: 'tb_contact_household', applicabilityWeight: 1.0,
      questionAdditions: ['index_case_treatment_status', 'index_case_drug_resistance', 'shared_bedroom'],
      investigationAdditions: ['tst', 'igra', 'chest_xray', 'contact_screening'],
      activationThresholdDelta: -0.2,
      urgencyOverride: 'orange',
      treatmentAdditions: [{ drugId: 'isoniazid_preventative_therapy', line: 0, notes: 'All household contacts <5: IPT after excluding active TB' }],
      hmisEventAdditions: ['household_contact_tracing'],
    },
    {
      context: 'resource_low', applicabilityWeight: 0.7,
      investigationRemovals: ['genexpert', 'tb_culture', 'ct_chest', 'igra'],
      investigationAdditions: ['sputum_afb_smear', 'chest_xray', 'clinical_scoring_system'],
      clinicalNotes: 'Resource-limited: GeneXpert preferred but often unavailable. AFB smear. Clinical diagnosis.',
    },
  ],
};

// ═══════════════════════════════════════════════════════════════
// PROFILE 2: COMMUNITY-ACQUIRED PNEUMONIA
// ═══════════════════════════════════════════════════════════════

export const CAP_CONTEXT_PROFILE: ContextAwareDiseaseProfile = {
  diseaseId: 'cap',
  diseaseName: 'Community-acquired Pneumonia',
  master: {
    organism: 'S. pneumoniae, H. influenzae, M. pneumoniae, viruses',
    transmission: 'Droplet / aspiration / inhalation',
    corePathophysiology: 'Alveolar inflammation → exudate → consolidation → V/Q mismatch → hypoxemia',
    naturalHistory: 'Acute 1-3 days. Treated: resolves 1-3wk. Untreated: progressive respiratory failure, sepsis.',
    universalComplications: ['Parapneumonic effusion', 'Empyema', 'Respiratory failure', 'Sepsis', 'Septic shock', 'Lung abscess'],
    universalMechanisms: ['alveolar_inflammation', 'infectious'],
    universalPhenotypes: ['cough_acute_productive', 'cough_febrile'],
  },
  baseline: {
    epidemiology: 'Leading infectious death. 450M cases/year.',
    symptomOnset: 'Acute 1-3 days',
    typicalPresentation: 'Acute fever, productive cough purulent sputum, dyspnea, pleuritic pain, crackles',
    discriminatingFeatures: ['fever', 'crackles', 'sputum_purulence', 'dyspnea', 'cxr_consolidation'],
    basePrevalence: 0.15,
    agePrevalenceModifiers: { infant: 0.20, child: 0.10, adult: 0.12, older_adult: 0.25 },
    typicalPhenotypes: ['cough_acute_productive', 'cough_febrile'],
    commonMechanisms: ['alveolar_inflammation', 'infectious'],
    requiredQuestions: ['cough_duration', 'cough_sputum', 'cough_sputum_color', 'cough_fever', 'cough_dyspnea', 'cough_chest_pain'],
    requiredExams: ['chest_auscultation', 'temperature', 'oxygen_saturation', 'respiratory_rate'],
    initialInvestigations: ['chest_xray', 'cbc', 'crp'],
    confirmatoryInvestigations: ['blood_culture', 'ct_chest', 'sputum_culture'],
    treatmentLines: [
      { line: 1, regimen: 'Amoxicillin 500mg TDS or Doxycycline 100mg BD', medications: ['amoxicillin', 'doxycycline'], duration: '5-7d' },
      { line: 2, regimen: 'Ceftriaxone 1g IV + Azithromycin 500mg', medications: ['ceftriaxone', 'azithromycin'], duration: '7-10d' },
      { line: 3, regimen: 'IV antibiotics + ICU', medications: ['ceftriaxone', 'vancomycin', 'piperacillin_tazobactam'], duration: '10-14d' },
    ],
    supportiveCare: ['oxygen_if_spo2_<92', 'iv_fluids_if_septic', 'antipyretics'],
    disposition: { admissionRequired: false, icuRequired: false, specialty: 'internal_medicine', followUp: '1wk' },
    monitoring: [
      { parameter: 'Temperature', frequency: '4-6hrly', target: '<37.5C' },
      { parameter: 'O2 sat', frequency: '4hrly', target: '>=92%' },
      { parameter: 'RR', frequency: '4hrly', target: '12-20' },
    ],
    urgency: 'orange',
    activationThreshold: 0.3,
    guidelines: ['who_cap_2024'],
    hmisEvents: ['pneumonia_diagnosis', 'admission_required'],
  },
  ageGroupToContext: {
    neonate: 'pediatric_infant', infant: 'pediatric_infant', toddler: 'pediatric_toddler',
    preschool: 'pediatric_preschool', school_age: 'pediatric_school', adolescent: 'pediatric_adolescent',
    adult: 'adult_immunocompetent', older_adult: 'elderly_>65',
  },
  relevantContexts: [],
  excludedContexts: [],
  contextOverrides: [
    {
      context: 'pediatric_infant', applicabilityWeight: 1.0,
      questionRemovals: ['cough_sputum_color', 'cough_smoking', 'cough_occupational_exposure'],
      questionAdditions: ['feeding_difficulty', 'irritability', 'lethargy', 'immunization_status', 'rsv_season'],
      questionPriorityOverrides: { cough_feeding_difficulty: 'critical', cough_dyspnea: 'critical' },
      examAdditions: ['chest_indrawing', 'nasal_flaring', 'head_bobbing', 'grunting', 'capillary_refill'],
      phenotypeActivations: ['cough_with_sepsis_signs', 'cough_with_dehydration'],
      investigationAdditions: ['blood_culture', 'rsv_test', 'blood_glucose'],
      investigationRemovals: ['sputum_culture'],
      treatmentRemovals: ['doxycycline'],
      treatmentDoseChanges: { all: 'weight_based_dosing_per_who_etat' },
      monitoringAdditions: ['rr_2hrly', 'o2_continuous', 'feeding_intake_daily'],
      dispositionChanges: { admissionRequired: true },
      urgencyOverride: 'orange',
      differentialAdditions: [{ diseaseId: 'bronchiolitis', weight: 0.5 }, { diseaseId: 'sepsis', weight: 0.3 }],
      clinicalNotes: 'Infant CAP: WHO IMCI. Tachypnea + chest indrawing = severe. Hypoxia = very severe.',
    },
    {
      context: 'pediatric_preschool', applicabilityWeight: 0.9,
      questionAdditions: ['immunization_status', 'school_contact'],
      examAdditions: ['chest_indrawing', 'oxygen_saturation'],
      treatmentRemovals: ['doxycycline'],
      treatmentDoseChanges: { all: 'weight_based_dosing' },
    },
    {
      context: 'pregnancy', applicabilityWeight: 1.0,
      ...PREGNANCY_CXR_SAFE,
      questionAdditions: ['gestational_age', 'fetal_movements', 'contractions'],
      examAdditions: ['fetal_heart_rate', 'obstetric_referral'],
      treatmentRemovals: ['doxycycline'],
      treatmentAdditions: [{ drugId: 'ceftriaxone', line: 1, notes: 'Preferred over doxycycline in pregnancy' }],
      monitoringAdditions: ['fetal_hr_monitoring'],
      urgencyOverride: 'orange',
      differentialAdditions: [{ diseaseId: 'pe', weight: 0.4 }],
    },
    {
      context: 'hiv_cd4_very_low', applicabilityWeight: 1.0,
      ...HIV_CONTEXT_SHARED,
      investigationAdditions: ['blood_culture', 'procalcitonin'],
      treatmentAdditions: [{ drugId: 'ceftriaxone', line: 1, notes: 'Broad coverage' }, { drugId: 'cotrimoxazole', line: 1, notes: 'PCP prophylaxis if CD4<200' }],
      differentialAdditions: [{ diseaseId: 'pcp', weight: 0.6 }, { diseaseId: 'tb', weight: 0.5 }],
    },
    {
      context: 'elderly_>65', applicabilityWeight: 0.9,
      questionAdditions: ['functional_baseline', 'delirium_screening', 'aspiration_risk', 'vaccination_history'],
      examAdditions: ['cognitive_assessment', 'swallow_assessment'],
      treatmentLines: [{ line: 1, regimen: 'Ceftriaxone 1g IV + Azithromycin 500mg', medications: ['ceftriaxone', 'azithromycin'], duration: '7-10d' }],
      monitoringAdditions: ['delirium_screening_bd', 'functional_status_daily'],
      dispositionChanges: { admissionRequired: true, specialtyReferral: 'geriatrics' },
      differentialAdditions: [{ diseaseId: 'aspiration_pneumonia', weight: 0.4 }, { diseaseId: 'heart_failure', weight: 0.3 }],
      clinicalNotes: 'Elderly CAP: Atypical — no fever (30%), delirium may be only sign. Higher CURB-65 mortality.',
    },
    {
      context: 'icu_ventilated', applicabilityWeight: 1.0,
      ...ICU_SHARED,
      investigationAdditions: ['bal', 'blood_culture', 'procalcitonin', 'legionella_ua', 'pneumococcal_ua', 'covid_pcr'],
      treatmentLines: [{ line: 1, regimen: 'Pip-tazo 4.5g IV QDS + Azithromycin 500mg IV', medications: ['piperacillin_tazobactam', 'azithromycin'], duration: '7-14d' }],
      urgencyOverride: 'red',
    },
    {
      context: 'copd_known', applicabilityWeight: 0.8,
      questionAdditions: ['baseline_function', 'home_o2', 'previous_exacerbations'],
      examAdditions: ['accessory_muscle_use', 'pursed_lip_breathing'],
      investigationAdditions: ['abg'],
      treatmentAdditions: [{ drugId: 'ceftriaxone', line: 1, notes: 'Broader coverage for COPD' }],
      differentialAdditions: [{ diseaseId: 'copd_exacerbation', weight: 0.6 }],
    },
    {
      context: 'cerebrovascular_disease', applicabilityWeight: 0.7,
      questionAdditions: ['swallowing_difficulty', 'choking_episodes'],
      examAdditions: ['swallow_assessment', 'cranial_nerve_exam'],
      treatmentAdditions: [{ drugId: 'clindamycin', line: 1, notes: 'Anaerobic coverage if aspiration suspected' }],
      differentialAdditions: [{ diseaseId: 'aspiration_pneumonia', weight: 0.6 }],
    },
    {
      context: 'resource_low', applicabilityWeight: 0.7,
      investigationRemovals: ['chest_xray', 'cbc', 'crp', 'blood_culture', 'sputum_culture', 'ct_chest'],
      investigationAdditions: ['clinical_imci_criteria', 'crp_poc'],
      treatmentLines: [{ line: 1, regimen: 'Amoxicillin 500mg TDS 5-7d (WHO IMCI)', medications: ['amoxicillin'], duration: '5-7d' }],
      clinicalNotes: 'Resource-limited CAP: WHO IMCI criteria. Clinical diagnosis. Refer if severe (chest indrawing, stridor, hypoxia).',
    },
  ],
};

// ═══════════════════════════════════════════════════════════════
// PROFILE 3: ASTHMA
// ═══════════════════════════════════════════════════════════════

export const ASTHMA_CONTEXT_PROFILE: ContextAwareDiseaseProfile = {
  diseaseId: 'asthma',
  diseaseName: 'Asthma',
  master: {
    organism: 'N/A — chronic inflammatory airway disease',
    transmission: 'N/A',
    corePathophysiology: 'Eosinophilic inflammation → bronchial hyperresponsiveness → reversible obstruction → remodeling',
    naturalHistory: 'Onset often childhood. Episodic exacerbations. Progressive if untreated.',
    universalComplications: ['Status asthmaticus', 'Respiratory failure', 'Pneumothorax', 'Growth impairment', 'Steroid side effects'],
    universalMechanisms: ['bronchospasm', 'allergic'],
    universalPhenotypes: ['cough_wheezy', 'cough_nocturnal', 'cough_exercise_induced'],
  },
  baseline: {
    epidemiology: '300M worldwide. 10% children, 5% adults.',
    symptomOnset: 'Episodic / exacerbation pattern',
    typicalPresentation: 'Episodic wheeze, cough (nocturnal/early morning), dyspnea, reversible with bronchodilators',
    discriminatingFeatures: ['wheeze', 'nocturnal_symptoms', 'reversibility', 'family_history', 'atopy', 'exercise_triggered'],
    basePrevalence: 0.12,
    agePrevalenceModifiers: { child: 0.20, adolescent: 0.15, adult: 0.10, older_adult: 0.08 },
    typicalPhenotypes: ['cough_wheezy', 'cough_nocturnal', 'cough_exercise_induced'],
    commonMechanisms: ['bronchospasm', 'allergic'],
    requiredQuestions: ['cough_timing', 'cough_dyspnea', 'cough_sputum', 'nocturnal_symptoms', 'exercise_triggers', 'seasonal_pattern', 'family_asthma_history', 'atopy_history'],
    requiredExams: ['chest_auscultation', 'peak_flow', 'oxygen_saturation', 'accessory_muscle_use'],
    initialInvestigations: ['spirometry'],
    confirmatoryInvestigations: ['exercise_challenge', 'allergy_test', 'feno'],
    treatmentLines: [
      { line: 1, regimen: 'SABA as needed', medications: ['salbutamol_inhaler'], duration: 'As needed' },
      { line: 2, regimen: 'Low-dose ICS (budesonide 200mcg) + SABA', medications: ['budesonide_inhaler', 'salbutamol_inhaler'], duration: 'Daily controller' },
      { line: 3, regimen: 'ICS/LABA SMART', medications: ['budesonide_formoterol'], duration: 'Daily' },
    ],
    supportiveCare: ['inhaler_technique_education', 'asthma_action_plan', 'trigger_avoidance'],
    disposition: { admissionRequired: false, icuRequired: false, specialty: 'pulmonology', followUp: '1-3mo' },
    monitoring: [
      { parameter: 'Peak flow', frequency: 'Daily', target: '>=80% personal best' },
      { parameter: 'ACT score', frequency: 'Monthly', target: '>=20' },
      { parameter: 'Inhaler technique', frequency: 'Each visit', target: 'Correct' },
    ],
    urgency: 'yellow',
    activationThreshold: 0.3,
    guidelines: ['gina'],
    hmisEvents: ['asthma_diagnosis'],
  },
  ageGroupToContext: {
    neonate: 'pediatric_infant', infant: 'pediatric_infant', toddler: 'pediatric_toddler',
    preschool: 'pediatric_preschool', school_age: 'pediatric_school', adolescent: 'pediatric_adolescent',
    adult: 'adult_immunocompetent', older_adult: 'elderly_>65',
  },
  relevantContexts: [],
  excludedContexts: [],
  contextOverrides: [
    {
      context: 'pediatric_infant', applicabilityWeight: 0.8,
      questionAdditions: ['viral_associated_wheezing', 'family_atopy_history', 'eczema_history'],
      examAdditions: ['skin_exam_for_eczema', 'growth_assessment'],
      phenotypeActivations: ['cough_viral_associated_wheeze'],
      investigationAdditions: ['allergy_testing'],
      treatmentDoseChanges: { all: 'weight_based' },
      monitoringAdditions: ['growth_monitoring'],
      differentialAdditions: [{ diseaseId: 'bronchiolitis', weight: 0.6 }],
      clinicalNotes: 'Infant asthma: Diagnosis difficult <2yr. Viral-associated wheeze. Trial of bronchodilator.',
    },
    {
      context: 'pediatric_school', applicabilityWeight: 0.9,
      questionAdditions: ['sport_participation', 'school_absences', 'exercise_triggers_detail', 'pet_exposure'],
      examAdditions: ['ent_exam', 'skin_exam'],
      investigationAdditions: ['exercise_challenge', 'spirometry', 'feno'],
      monitoringAdditions: ['peak_flow_diary', 'act_score_monthly'],
    },
    {
      context: 'pregnancy', applicabilityWeight: 0.9,
      questionAdditions: ['asthma_control_during_pregnancy', 'gestational_age'],
      examAdditions: ['fetal_heart_rate', 'oxygen_saturation'],
      treatmentAdditions: [{ drugId: 'budesonide', line: 1, notes: 'Preferred ICS in pregnancy' }],
      monitoringAdditions: ['fetal_growth_monitoring', 'asthma_control_monthly'],
      urgencyOverride: 'orange',
      clinicalNotes: 'Pregnancy asthma: 1/3 improve, 1/3 worsen. Uncontrolled asthma worse than drugs.',
    },
    {
      context: 'elderly_>65', applicabilityWeight: 0.7,
      questionAdditions: ['medication_list', 'comorbidities_cardiac', 'inhaler_technique_check', 'functional_status'],
      examAdditions: ['cardiac_exam', 'cognitive_assessment'],
      investigationAdditions: ['ecg', 'echo', 'spirometry', 'bnp'],
      treatmentAdditions: [{ drugId: 'spacer_device', line: 1, notes: 'Better deposition in elderly' }],
      differentialAdditions: [{ diseaseId: 'heart_failure', weight: 0.4 }, { diseaseId: 'copd', weight: 0.4 }],
    },
    {
      context: 'copd_known', applicabilityWeight: 0.7,
      questionAdditions: ['smoking_detail', 'baseline_function'],
      examAdditions: ['barrel_chest', 'pursed_lip_breathing'],
      investigationAdditions: ['spirometry', 'ct_chest'],
      differentialAdditions: [{ diseaseId: 'copd_exacerbation', weight: 0.5 }],
      clinicalNotes: 'Asthma-COPD overlap (ACO): Both components need treatment.',
    },
    {
      context: 'resource_low', applicabilityWeight: 0.7,
      investigationRemovals: ['spirometry', 'exercise_challenge', 'allergy_test', 'feno'],
      investigationAdditions: ['peak_flow_meter', 'clinical_bd_trial'],
      clinicalNotes: 'Resource-limited: Diagnosis clinical. Response to bronchodilator trial.',
    },
  ],
};

// ═══════════════════════════════════════════════════════════════
// PROFILE 4: COPD EXACERBATION
// ═══════════════════════════════════════════════════════════════

export const COPD_CONTEXT_PROFILE: ContextAwareDiseaseProfile = {
  diseaseId: 'copd_exacerbation',
  diseaseName: 'COPD Exacerbation',
  master: {
    organism: 'Triggered by infection (bacterial/viral) or environmental',
    transmission: 'N/A — acute-on-chronic',
    corePathophysiology: 'Airway inflammation → mucus hypersecretion → air trapping → loss of elastic recoil → acute exacerbation',
    naturalHistory: 'Progressive irreversible. Exacerbations accelerate decline.',
    universalComplications: ['Respiratory failure', 'Pneumothorax', 'Cor pulmonale', 'Secondary polycythemia'],
    universalMechanisms: ['obstructive', 'mucus_hypersecretion'],
    universalPhenotypes: ['cough_productive_morning', 'cough_wheezy', 'cough_chronic'],
  },
  baseline: {
    epidemiology: '3rd leading cause of death. 300M cases. 90% smoking.',
    symptomOnset: 'Acute worsening over days',
    typicalPresentation: 'Smoker with chronic cough, sputum, dyspnea. Exacerbation: increased sputum purulence/volume, worsening dyspnea.',
    discriminatingFeatures: ['smoker', 'chronic_cough', 'sputum_change', 'dyspnea_worsening', 'barrel_chest', 'pursed_lip_breathing'],
    basePrevalence: 0.08,
    agePrevalenceModifiers: { adult: 0.05, older_adult: 0.20 },
    typicalPhenotypes: ['cough_productive_morning', 'cough_wheezy', 'cough_chronic'],
    commonMechanisms: ['obstructive', 'mucus_hypersecretion'],
    requiredQuestions: ['cough_sputum', 'cough_sputum_color', 'cough_dyspnea', 'cough_smoking', 'pack_years', 'dyspnea_worsening', 'sputum_change', 'previous_exacerbations', 'home_o2'],
    requiredExams: ['chest_auscultation', 'oxygen_saturation', 'accessory_muscle_use', 'pursed_lip_breathing', 'barrel_chest', 'pedal_edema'],
    initialInvestigations: ['chest_xray', 'abg'],
    confirmatoryInvestigations: ['ct_chest', 'spirometry', 'ecg'],
    treatmentLines: [
      { line: 1, regimen: 'SABA + SAMA nebulized', medications: ['salbutamol_neb', 'ipratropium_neb'], duration: 'Acute' },
      { line: 2, regimen: 'Prednisolone 30-40mg 5-7d + abx if purulent', medications: ['prednisolone_oral', 'amoxicillin'], duration: '5-7d' },
      { line: 3, regimen: 'NIV (BiPAP) if hypercapnic', medications: [], duration: 'As needed' },
    ],
    supportiveCare: ['O2_target_88-92%', 'smoking_cessation', 'pulmonary_rehab'],
    disposition: { admissionRequired: true, icuRequired: false, specialty: 'pulmonology', followUp: '2-4wk' },
    monitoring: [
      { parameter: 'O2 sat', frequency: 'Continuous acute, 4hrly stable', target: '88-92%' },
      { parameter: 'ABG', frequency: 'If hypercapnic 1-4hrly', target: 'pH>7.35' },
    ],
    urgency: 'orange',
    activationThreshold: 0.3,
    guidelines: ['gold_copd_2024'],
    hmisEvents: ['admission_required', 'icu_required'],
  },
  ageGroupToContext: { adult: 'adult_immunocompetent', older_adult: 'elderly_>65' },
  relevantContexts: ['adult_immunocompetent', 'elderly_>65', 'icu_ventilated', 'pregnancy', 'heart_failure_known', 'diabetes', 'resource_low'],
  excludedContexts: ['pediatric_infant', 'pediatric_toddler', 'pediatric_preschool', 'pediatric_school', 'pediatric_adolescent'],
  contextOverrides: [
    {
      context: 'elderly_>65', applicabilityWeight: 1.0,
      questionAdditions: ['delirium_screening', 'falls_history', 'caregiver_support', 'advance_directives'],
      monitoringAdditions: ['delirium_screening_bd', 'falls_prevention'],
      urgencyOverride: 'orange',
    },
    {
      context: 'icu_ventilated', applicabilityWeight: 1.0,
      ...ICU_SHARED,
      treatmentLines: [
        { line: 1, regimen: 'SABA+SAMA continuous neb', medications: ['salbutamol_neb', 'ipratropium_neb'], duration: 'Acute' },
        { line: 2, regimen: 'IV methylprednisolone 60-125mg 6-8hrly', medications: ['methylprednisolone_iv'], duration: '3-5d then taper' },
      ],
      urgencyOverride: 'red',
    },
    {
      context: 'heart_failure_known', applicabilityWeight: 0.8,
      questionAdditions: ['orthopnea', 'pnd', 'pedal_edema'],
      examAdditions: ['jvp', 'pedal_edema', 'gallop'],
      investigationAdditions: ['bnp', 'echo'],
      differentialAdditions: [{ diseaseId: 'heart_failure', weight: 0.5 }],
    },
    {
      context: 'resource_low', applicabilityWeight: 0.7,
      investigationRemovals: ['abg', 'ct_chest', 'spirometry', 'ecg'],
      treatmentLines: [
        { line: 1, regimen: 'SABA inhaler if available', medications: ['salbutamol_inhaler'], duration: 'Acute' },
        { line: 2, regimen: 'Prednisolone 30-40mg + amoxicillin', medications: ['prednisolone_oral', 'amoxicillin'], duration: '5-7d' },
      ],
      clinicalNotes: 'Resource-limited: O2 target 88-92%. ABG often unavailable.',
    },
  ],
};

// ═══════════════════════════════════════════════════════════════
// PROFILE 5: BRONCHIECTASIS
// ═══════════════════════════════════════════════════════════════

export const BRONCHIECTASIS_CONTEXT_PROFILE: ContextAwareDiseaseProfile = {
  diseaseId: 'bronchiectasis',
  diseaseName: 'Bronchiectasis',
  master: {
    organism: 'Structural lung disease. Pseudomonas, H. influenza, NTM common.',
    transmission: 'N/A',
    corePathophysiology: 'Initial insult → impaired clearance → chronic colonization → airway destruction → vicious cycle',
    naturalHistory: 'Progressive. Exacerbations cause irreversible decline.',
    universalComplications: ['Hemoptysis (massive)', 'Respiratory failure', 'Cor pulmonale', 'NTM co-infection'],
    universalMechanisms: ['mucus_hypersecretion', 'infectious'],
    universalPhenotypes: ['cough_chronic', 'cough_productive_copious', 'cough_hemoptysis'],
  },
  baseline: {
    epidemiology: '1:1000 adults. Underdiagnosed.',
    symptomOnset: 'Chronic years, acute exacerbations',
    typicalPresentation: 'Chronic daily productive cough copious sputum, recurrent infections, clubbing, hemoptysis',
    discriminatingFeatures: ['chronic_sputum_daily', 'recurrent_infections', 'clubbing', 'hemoptysis', 'copious_sputum_>30ml/day'],
    basePrevalence: 0.03,
    agePrevalenceModifiers: { adult: 0.03, older_adult: 0.05 },
    typicalPhenotypes: ['cough_chronic', 'cough_productive_copious', 'cough_hemoptysis'],
    commonMechanisms: ['mucus_hypersecretion', 'infectious'],
    requiredQuestions: ['cough_duration', 'cough_sputum', 'cough_sputum_volume', 'cough_sputum_color', 'cough_hemoptysis_detail', 'recurrent_infections', 'previous_tb'],
    requiredExams: ['chest_auscultation', 'clubbing_assessment', 'oxygen_saturation', 'sputum_inspection'],
    initialInvestigations: ['chest_xray', 'ct_chest'],
    confirmatoryInvestigations: ['sputum_culture', 'bronchoscopy', 'immunoglobulin_levels'],
    treatmentLines: [
      { line: 1, regimen: 'Airway clearance (physiotherapy, PEP device)', medications: [], duration: 'Daily lifelong' },
      { line: 2, regimen: 'Antibiotics for exacerbations per culture', medications: ['amoxicillin', 'ciprofloxacin'], duration: '7-14d' },
      { line: 3, regimen: 'Chronic macrolide if frequent exacerbations', medications: ['azithromycin'], duration: 'Long-term' },
    ],
    supportiveCare: ['pulmonary_physiotherapy', 'vaccination', 'nutritional_support'],
    disposition: { admissionRequired: false, icuRequired: false, specialty: 'pulmonology', followUp: '3-6mo' },
    monitoring: [
      { parameter: 'Sputum culture', frequency: 'Exacerbation + annual', target: 'Identify organism' },
      { parameter: 'PFT', frequency: 'Annual', target: 'Stable' },
    ],
    urgency: 'yellow',
    activationThreshold: 0.3,
    guidelines: ['ers_bronchiectasis_2024'],
    hmisEvents: [],
  },
  ageGroupToContext: {
    child: 'pediatric_school', adolescent: 'pediatric_adolescent',
    adult: 'adult_immunocompetent', older_adult: 'elderly_>65',
  },
  relevantContexts: [],
  excludedContexts: ['pediatric_infant', 'pediatric_toddler'],
  contextOverrides: [
    {
      context: 'pediatric_school', applicabilityWeight: 0.8,
      questionAdditions: ['recurrent_pneumonia_history', 'immunodeficiency_screening'],
      examAdditions: ['growth_assessment', 'clubbing_assessment'],
      investigationAdditions: ['immunoglobulin_levels', 'cftr_genetic_testing', 'sweat_chloride'],
      differentialAdditions: [{ diseaseId: 'cystic_fibrosis', weight: 0.5 }],
      clinicalNotes: 'Pediatric bronchiectasis: Exclude CF and immunodeficiency.',
    },
    {
      context: 'hiv_cd4_low', applicabilityWeight: 0.6,
      ...HIV_CONTEXT_SHARED,
      differentialAdditions: [{ diseaseId: 'tb', weight: 0.6 }, { diseaseId: 'ntm', weight: 0.5 }],
    },
    {
      context: 'resource_low', applicabilityWeight: 0.6,
      investigationRemovals: ['ct_chest', 'bronchoscopy', 'immunoglobulin_levels'],
      clinicalNotes: 'Resource-limited: Clinical diagnosis — chronic cough + clubbing + recurrent infections.',
    },
  ],
};

// ═══════════════════════════════════════════════════════════════
// PROFILE 6: LUNG CANCER
// ═══════════════════════════════════════════════════════════════

export const LUNG_CANCER_CONTEXT_PROFILE: ContextAwareDiseaseProfile = {
  diseaseId: 'lung_cancer',
  diseaseName: 'Lung Cancer',
  master: {
    organism: 'Malignant neoplasm (NSCLC >80%, SCLC ~15%)',
    transmission: 'N/A — acquired mutations from carcinogen exposure',
    corePathophysiology: 'Carcinogen exposure → genetic mutations → uncontrolled proliferation → invasion → metastasis',
    naturalHistory: 'Insidious onset. Often advanced at diagnosis. 5-yr survival 15-20%.',
    universalComplications: ['Hemoptysis', 'SVC syndrome', 'Pleural effusion', 'Metastasis', 'Airway obstruction', 'Hypercalcemia'],
    universalMechanisms: ['neoplastic_infiltration'],
    universalPhenotypes: ['cough_chronic', 'cough_hemoptysis'],
  },
  baseline: {
    epidemiology: 'Most common cancer death. 2.2M cases/year.',
    symptomOnset: 'Insidious wks-mo',
    typicalPresentation: 'Chronic cough in smoker >40py, hemoptysis, weight loss, chest pain, clubbing',
    discriminatingFeatures: ['smoker_>40py', 'hemoptysis', 'weight_loss', 'clubbing', 'age_>50', 'family_history'],
    basePrevalence: 0.02,
    agePrevalenceModifiers: { adult: 0.01, older_adult: 0.06 },
    typicalPhenotypes: ['cough_chronic', 'cough_hemoptysis'],
    commonMechanisms: ['neoplastic_infiltration'],
    requiredQuestions: ['cough_duration', 'cough_sputum', 'cough_smoking', 'pack_years', 'cough_hemoptysis_detail', 'cough_weight_loss', 'cough_chest_pain', 'cough_dyspnea', 'family_history_cancer'],
    requiredExams: ['chest_auscultation', 'clubbing', 'lymph_nodes', 'weight_assessment', 'svc_check'],
    initialInvestigations: ['chest_xray', 'ct_chest'],
    confirmatoryInvestigations: ['bronchoscopy', 'biopsy', 'pet_ct'],
    treatmentLines: [
      { line: 1, regimen: 'Surgical resection (I-II) or SBRT', medications: [], duration: 'Curative' },
      { line: 2, regimen: 'Chemo+IO (III-IV): platinum doublet + IO', medications: ['platinum_doublet', 'immunotherapy'], duration: '4-6 cycles + maintenance' },
      { line: 3, regimen: 'Targeted if driver mutation (EGFR, ALK, etc)', medications: ['osimertinib', 'alectinib'], duration: 'Until progression' },
    ],
    supportiveCare: ['smoking_cessation', 'palliative_care', 'nutritional_support', 'pain_management'],
    disposition: { admissionRequired: false, icuRequired: false, specialty: 'oncology', followUp: '3mo' },
    monitoring: [{ parameter: 'CT chest', frequency: '3-6mo', target: 'Stable' }],
    urgency: 'orange',
    activationThreshold: 0.4,
    guidelines: ['nccn_lung'],
    hmisEvents: [],
  },
  ageGroupToContext: { adult: 'adult_immunocompetent', older_adult: 'elderly_>65' },
  relevantContexts: ['adult_immunocompetent', 'elderly_>65', 'copd_known', 'resource_low'],
  excludedContexts: ['pediatric_infant', 'pediatric_toddler', 'pediatric_preschool', 'pediatric_school', 'pregnancy'],
  contextOverrides: [
    {
      context: 'elderly_>65', applicabilityWeight: 1.0,
      questionAdditions: ['advance_directives', 'functional_status', 'caregiver_support'],
      treatmentDoseChanges: { chemo: 'reduced_doses_often_needed_cga' },
      clinicalNotes: 'Elderly: CGA before treatment. SBRT good for early stage.',
    },
    {
      context: 'copd_known', applicabilityWeight: 0.7,
      clinicalNotes: 'COPD-cancer: Shared smoking risk. COPD limits surgical options. PFTs essential before resection.',
    },
    {
      context: 'resource_low', applicabilityWeight: 0.6,
      investigationRemovals: ['ct_chest', 'bronchoscopy', 'biopsy', 'pet_ct', 'molecular_testing'],
      clinicalNotes: 'Resource-limited: Most present late. Palliative care often only option.',
    },
  ],
};

// ═══════════════════════════════════════════════════════════════
// PROFILE 7: HEART FAILURE
// ═══════════════════════════════════════════════════════════════

export const HEART_FAILURE_CONTEXT_PROFILE: ContextAwareDiseaseProfile = {
  diseaseId: 'heart_failure',
  diseaseName: 'Heart Failure / Pulmonary Edema',
  master: {
    organism: 'N/A — cardiac pump failure',
    transmission: 'N/A — from ischemic, hypertensive, valvular, cardiomyopathy',
    corePathophysiology: 'Reduced CO → elevated LAP → pulmonary venous HTN → interstitial edema → alveolar edema → cough & dyspnea',
    naturalHistory: 'Chronic progressive. Acute decompenations. 5-yr mortality ~50%.',
    universalComplications: ['Cardiogenic shock', 'Respiratory failure', 'Cardiorenal syndrome', 'Arrhythmias', 'Hepatic congestion'],
    universalMechanisms: ['cardiac', 'pulmonary_edema'],
    universalPhenotypes: ['cough_nocturnal', 'cough_positional', 'cough_productive_pink'],
  },
  baseline: {
    epidemiology: '64M cases worldwide. Leading hospitalization cause >65.',
    symptomOnset: 'Gradual or acute decompensation',
    typicalPresentation: 'Nocturnal cough, orthopnea, PND, dyspnea on exertion, pedal edema, crackles, elevated JVP',
    discriminatingFeatures: ['orthopnea', 'pnd', 'pedal_edema', 'basal_crackles', 'elevated_jvp', 'gallop', 'bnp_elevated'],
    basePrevalence: 0.05,
    agePrevalenceModifiers: { older_adult: 0.15 },
    typicalPhenotypes: ['cough_nocturnal', 'cough_positional', 'cough_productive_pink'],
    commonMechanisms: ['cardiac', 'pulmonary_edema'],
    requiredQuestions: ['cough_duration', 'cough_timing', 'cough_dyspnea', 'orthopnea', 'pnd', 'pedal_edema', 'exercise_tolerance', 'medication_list', 'chest_pain', 'palpitations'],
    requiredExams: ['chest_auscultation', 'jvp', 'pedal_edema', 'hepatomegaly', 'gallop', 'oxygen_saturation'],
    initialInvestigations: ['chest_xray', 'echo', 'bnp'],
    confirmatoryInvestigations: ['cardiac_mri', 'ecg'],
    treatmentLines: [
      { line: 1, regimen: 'Furosemide 40mg + ACEI (lisinopril 5mg)', medications: ['furosemide', 'lisinopril'], duration: 'Long-term' },
      { line: 2, regimen: 'Add beta-blocker (bisoprolol) + spironolactone 25mg', medications: ['bisoprolol', 'spironolactone'], duration: 'Long-term' },
      { line: 3, regimen: 'Add SGLT2i (dapagliflozin 10mg)', medications: ['dapagliflozin'], duration: 'Long-term' },
    ],
    supportiveCare: ['oxygen', 'salt_restriction', 'daily_weights', 'fluid_restriction', 'sleep_upright'],
    disposition: { admissionRequired: true, icuRequired: false, specialty: 'cardiology', followUp: '1-2wk' },
    monitoring: [
      { parameter: 'Daily weight', frequency: 'Daily', target: '+/- 1kg' },
      { parameter: 'O2 sat', frequency: '4hrly', target: '>=92%' },
      { parameter: 'BNP', frequency: 'Decompensation', target: 'Trending down' },
    ],
    urgency: 'orange',
    activationThreshold: 0.3,
    guidelines: ['esc_hf_2024', 'acc_aha_hf'],
    hmisEvents: ['admission_required'],
  },
  ageGroupToContext: { adult: 'adult_immunocompetent', older_adult: 'elderly_>65' },
  relevantContexts: ['adult_immunocompetent', 'elderly_>65', 'pregnancy', 'renal_failure', 'copd_known', 'icu_ventilated', 'diabetes', 'resource_low'],
  excludedContexts: ['pediatric_infant', 'pediatric_toddler', 'pediatric_preschool', 'pediatric_school'],
  contextOverrides: [
    {
      context: 'elderly_>65', applicabilityWeight: 1.0,
      questionAdditions: ['falls_history', 'postural_hypotension', 'medication_adherence', 'cognitive_status'],
      treatmentDoseChanges: { lisinopril: 'start_2.5mg', bisoprolol: 'start_1.25mg' },
      monitoringAdditions: ['orthostatic_bp_daily', 'renal_function_weekly'],
      clinicalNotes: 'Elderly HF: Start low, go slow. Falls risk with diuretics.',
    },
    {
      context: 'pregnancy', applicabilityWeight: 0.9,
      questionAdditions: ['gestational_age', 'preeclampsia_symptoms', 'vaginal_bleeding'],
      examAdditions: ['fetal_heart_rate', 'obstetric_referral'],
      contraindications: ['ace_inhibitors', 'spironolactone'],
      treatmentAdditions: [
        { drugId: 'hydralazine', line: 1, notes: 'ACEI alternative in pregnancy' },
        { drugId: 'nifedipine', line: 1, notes: 'Alternative antihypertensive' },
      ],
      differentialAdditions: [{ diseaseId: 'peripartum_cardiomyopathy', weight: 0.5 }, { diseaseId: 'pe', weight: 0.4 }],
      urgencyOverride: 'orange',
      clinicalNotes: 'Pregnancy HF: Peripartum CM. ACEI contraindicated. Hydralazine + nitrates.',
    },
    {
      context: 'renal_failure', applicabilityWeight: 0.8,
      ...RENAL_ADJUSTMENTS,
      contraindications: ['spironolactone_if_gfr_<30'],
      clinicalNotes: 'Cardiorenal: HF and renal failure worsen each other. Diuretic resistance common.',
    },
    {
      context: 'copd_known', applicabilityWeight: 0.7,
      investigationAdditions: ['bnp', 'echo'],
      differentialAdditions: [{ diseaseId: 'copd_exacerbation', weight: 0.5 }],
      clinicalNotes: 'HF-COPD: BNP key to differentiate. Cardioselective beta-blockers safe in COPD.',
    },
    {
      context: 'resource_low', applicabilityWeight: 0.6,
      investigationRemovals: ['echo', 'bnp', 'cardiac_mri'],
      investigationAdditions: ['clinical_volume_assessment', 'chest_xray'],
      clinicalNotes: 'Resource-limited: Clinical diagnosis (JVP, edema, crackles, gallop). Furosemide + ACEI.',
    },
  ],
};

export const ALL_PART1_PROFILES: ContextAwareDiseaseProfile[] = [
  TB_CONTEXT_PROFILE, CAP_CONTEXT_PROFILE, ASTHMA_CONTEXT_PROFILE,
  COPD_CONTEXT_PROFILE, BRONCHIECTASIS_CONTEXT_PROFILE,
  LUNG_CANCER_CONTEXT_PROFILE, HEART_FAILURE_CONTEXT_PROFILE,
];
