export const PAIN_TEMPLATE = {
  symptomCategory: 'pain' as const,
  name: 'Pain Exploration',
  coreFields: [
    { id: 'pain_location', label: 'Exact location', type: 'text' as const, mandatory: true, purpose: 'Anchors the pain to a specific region', ddRelevance: ['all_abdominal', 'all_chest', 'all_musculoskeletal'] },
    { id: 'pain_onset', label: 'Onset (sudden/gradual)', type: 'select' as const, options: ['sudden', 'gradual', 'acute_on_chronic'], mandatory: true, purpose: 'Sudden onset = vascular/perforation, gradual = inflammation', ddRelevance: ['volvulus', 'perforation', 'appendicitis', 'MI'] },
    { id: 'pain_duration', label: 'Duration', type: 'text' as const, mandatory: true, purpose: 'Establishes timeline and acuity', ddRelevance: ['all'] },
    { id: 'pain_course', label: 'Course since onset', type: 'select' as const, options: ['improving', 'worsening', 'unchanged', 'fluctuating'], mandatory: true, purpose: 'Worsening = progression/ischaemia', ddRelevance: ['ischaemia', 'perforation', 'progressive_disease'] },
    { id: 'pain_severity', label: 'Severity (0-10)', type: 'number' as const, mandatory: true, purpose: 'Baseline and tracks response', safetyRelevance: ['severe_pain_red_flag'] },
    { id: 'pain_character', label: 'Character/quality', type: 'text' as const, mandatory: true, purpose: 'Colicky = obstruction, burning = ulcer, stabbing = perforation', ddRelevance: ['obstruction', 'ulcer', 'pancreatitis', 'renal_colic'] },
    { id: 'pain_radiation', label: 'Radiation/spread', type: 'text' as const, mandatory: false, purpose: 'Referred pain patterns guide diagnosis', ddRelevance: ['biliary', 'pancreatitis', 'MI', 'renal_colic'] },
    { id: 'pain_timing', label: 'Timing (constant/intermittent)', type: 'select' as const, options: ['constant', 'intermittent', 'colicky', 'continuous_with_exacerbations'], mandatory: true, purpose: 'Constant = ischaemia/perforation, intermittent = obstruction', ddRelevance: ['ischaemia', 'obstruction', 'colic'] },
    { id: 'pain_aggravating', label: 'Aggravating factors', type: 'text' as const, mandatory: false, purpose: 'Eating, movement, breathing, coughing', ddRelevance: ['pancreatitis', 'peritonism', 'pleuritic'] },
    { id: 'pain_relieving', label: 'Relieving factors', type: 'text' as const, mandatory: false, purpose: 'Position, medications, food', ddRelevance: ['ulcer', 'reflux', 'MSK'] },
    { id: 'pain_previous_similar', label: 'Previous similar episodes', type: 'boolean' as const, mandatory: false, purpose: 'Recurrent pattern = chronic/recurrent condition', ddRelevance: ['volvulus', 'ulcer', 'IBS', 'renal_colic'] },
    { id: 'pain_24h_trend', label: 'Trend in last 24 hours', type: 'select' as const, options: ['better', 'worse', 'same', 'fluctuating'], mandatory: true, purpose: 'Acute deterioration = emergency', safetyRelevance: ['acute_deterioration'] },
  ],
  associatedSymptomPrompt: 'Have you also noticed any of the following with the pain?',
  associatedSymptomOptions: [
    { category: 'vomiting', label: 'Vomiting' },
    { category: 'fever', label: 'Fever' },
    { category: 'distension', label: 'Abdominal distension' },
    { category: 'constipation', label: 'Constipation' },
    { category: 'diarrhea', label: 'Diarrhea' },
    { category: 'bleeding', label: 'Bleeding (any site)' },
    { category: 'urinary', label: 'Urinary symptoms' },
    { category: 'dyspnea', label: 'Shortness of breath' },
    { category: 'cardiac', label: 'Palpitations/chest tightness' },
    { category: 'neurological', label: 'Neurological symptoms' },
    { category: 'constitutional', label: 'Weight loss' },
    { category: 'constitutional', label: 'Loss of appetite' },
  ],
  completionCriteria: [
    'Location recorded',
    'Onset recorded',
    'Duration recorded',
    'Course recorded',
    'Severity recorded',
    'Character recorded',
    'Timing (constant/intermittent) recorded',
    '24h trend recorded',
    'At least associated symptoms screened',
  ],
};

export const VOMITING_TEMPLATE = {
  symptomCategory: 'vomiting' as const,
  name: 'Vomiting Exploration',
  coreFields: [
    { id: 'vomiting_onset', label: 'When did vomiting start?', type: 'text' as const, mandatory: true, purpose: 'Timeline relative to other symptoms', ddRelevance: ['obstruction', 'gastroenteritis', 'raised_ICP'] },
    { id: 'vomiting_frequency', label: 'Frequency (times per day)', type: 'number' as const, mandatory: true, purpose: 'Assesses severity and dehydration risk' },
    { id: 'vomiting_content', label: 'Content/character', type: 'select' as const, options: ['undigested_food', 'bilious', 'faeculent', 'blood', 'coffee_ground', 'watery', 'mucoid', 'undigested_plus_bilious'], mandatory: true, purpose: 'Bilious = proximal obstruction, faeculent = distal obstruction, blood = UGIB', ddRelevance: ['obstruction', 'UGIB', 'ileus', 'raised_ICP'] },
    { id: 'vomiting_projectile', label: 'Projectile?', type: 'boolean' as const, mandatory: false, purpose: 'Projectile = raised ICP / pyloric stenosis', ddRelevance: ['raised_ICP', 'pyloric_stenosis'] },
    { id: 'vomiting_relation_to_food', label: 'Relation to meals', type: 'select' as const, options: ['before_eating', 'immediately_after', '30min_after', 'hours_after', 'not_related'], mandatory: true, purpose: 'Timing helps differentiate causes', ddRelevance: ['gastroparesis', 'ulcer', 'obstruction'] },
    { id: 'vomiting_alleviated_by', label: 'What relieves the vomiting?', type: 'text' as const, mandatory: false, purpose: 'NG tube, medications, nothing' },
    { id: 'vomiting_nausea_precedes', label: 'Nausea before vomiting?', type: 'boolean' as const, mandatory: true, purpose: 'Absent nausea = raised ICP / vestibular', ddRelevance: ['raised_ICP', 'vestibular'] },
    { id: 'vomiting_hematemesis', label: 'Any blood in vomit?', type: 'boolean' as const, mandatory: true, purpose: 'UGIB requires immediate action', safetyRelevance: ['UGIB'], ddRelevance: ['ulcer', 'varices', 'Mallory_Weiss'] },
    { id: 'vomiting_bilious', label: 'Green/bilious?', type: 'boolean' as const, mandatory: true, purpose: 'Bilious vomiting = obstruction until proven otherwise in surgical patient', ddRelevance: ['obstruction', 'ileus'] },
    { id: 'vomiting_faeculent', label: 'Foul-smelling/faeculent?', type: 'boolean' as const, mandatory: true, purpose: 'Faeculent = distal obstruction / feculent peritonitis', ddRelevance: ['distal_obstruction', 'peritonitis'] },
    { id: 'vomiting_ability_to_tolerate', label: 'Able to keep anything down?', type: 'boolean' as const, mandatory: true, purpose: 'Assesses dehydration risk and need for IV fluids' },
  ],
  associatedSymptomPrompt: 'Along with the vomiting, have you noticed?',
  associatedSymptomOptions: [
    { category: 'pain', label: 'Abdominal pain' },
    { category: 'fever', label: 'Fever' },
    { category: 'diarrhea', label: 'Diarrhea' },
    { category: 'constipation', label: 'Constipation' },
    { category: 'distension', label: 'Abdominal distension' },
    { category: 'neurological', label: 'Headache/vision changes' },
    { category: 'constitutional', label: 'Decreased urination' },
  ],
  completionCriteria: [
    'Onset recorded',
    'Frequency recorded',
    'Content recorded',
    'Relation to food recorded',
    'Nausea preceding recorded',
    'Hematemesis screened',
    'Bilious vomiting screened',
    'Able to tolerate oral intake recorded',
  ],
};

export const FEVER_TEMPLATE = {
  symptomCategory: 'fever' as const,
  name: 'Fever Exploration',
  coreFields: [
    { id: 'fever_onset', label: 'When did fever start?', type: 'text' as const, mandatory: true, purpose: 'Timeline relative to other symptoms', ddRelevance: ['infection', 'inflammation', 'malignancy'] },
    { id: 'fever_duration', label: 'Duration of fever', type: 'text' as const, mandatory: true, purpose: 'Acute vs chronic = different causes', ddRelevance: ['acute_infection', 'chronic_infection', 'PUO'] },
    { id: 'fever_documented_temp', label: 'Highest documented temperature', type: 'number' as const, mandatory: false, purpose: 'Hyperpyrexia = emergency', safetyRelevance: ['hyperpyrexia'] },
    { id: 'fever_pattern', label: 'Pattern of fever', type: 'select' as const, options: ['continuous', 'intermittent', 'remittent', 'relapsing', 'undulant', 'not_monitored'], mandatory: true, purpose: 'Pattern narrows differential', ddRelevance: ['malaria', 'typhoid', 'abscess', 'lymphoma', 'TB'] },
    { id: 'fever_chills', label: 'Chills/rigors?', type: 'boolean' as const, mandatory: true, purpose: 'Rigors = bacteraemia/severe infection', ddRelevance: ['bacteraemia', 'malaria', 'abscess', 'sepsis'] },
    { id: 'fever_sweats', label: 'Night sweats?', type: 'boolean' as const, mandatory: false, purpose: 'B symptoms = TB/lymphoma', ddRelevance: ['TB', 'lymphoma', 'HIV'] },
    { id: 'fever_response_to_antipyretics', label: 'Response to antipyretics?', type: 'boolean' as const, mandatory: false, purpose: 'Poor response = serious infection' },
    { id: 'fever_temporal_relation', label: 'Relation to other symptoms', type: 'text' as const, mandatory: false, purpose: 'Fever before pain = medical, pain before fever = surgical', ddRelevance: ['surgical_abdomen', 'medical_fever'] },
    { id: 'fever_source_hint', label: 'Any localizing symptoms?', type: 'multi_select' as const, options: ['cough', 'dysuria', 'diarrhea', 'wound', 'sore_throat', 'headache', 'joint_pain', 'none', 'other'], mandatory: true, purpose: 'Identifies source of infection' },
    { id: 'fever_hiv_risk', label: 'HIV risk factors / known status?', type: 'boolean' as const, mandatory: false, purpose: 'Immunocompromised = broader differential', ddRelevance: ['HIV', 'opportunistic_infection'] },
  ],
  associatedSymptomPrompt: 'Along with the fever, have you noticed?',
  associatedSymptomOptions: [
    { category: 'pain', label: 'Pain (any site)' },
    { category: 'vomiting', label: 'Vomiting' },
    { category: 'cough', label: 'Cough' },
    { category: 'dyspnea', label: 'Shortness of breath' },
    { category: 'diarrhea', label: 'Diarrhea' },
    { category: 'urinary', label: 'Urinary symptoms' },
    { category: 'neurological', label: 'Headache/stiff neck' },
    { category: 'skin', label: 'Rash' },
    { category: 'constitutional', label: 'Weight loss' },
    { category: 'constitutional', label: 'Loss of appetite' },
  ],
  completionCriteria: [
    'Onset recorded',
    'Duration recorded',
    'Pattern recorded',
    'Chills/rigors screened',
    'Localizing symptoms screened',
    'Systemic features screened',
  ],
};

export const DISTENSION_TEMPLATE = {
  symptomCategory: 'distension' as const,
  name: 'Abdominal Distension Exploration',
  coreFields: [
    { id: 'distension_onset', label: 'When did distension start?', type: 'text' as const, mandatory: true, purpose: 'Timeline relative to pain/obstruction', ddRelevance: ['obstruction', 'ascites', 'ileus'] },
    { id: 'distension_course', label: 'Course since onset', type: 'select' as const, options: ['rapidly_progressive', 'slowly_progressive', 'stable', 'fluctuating', 'intermittent'], mandatory: true, purpose: 'Rapid = acute obstruction, slow = ascites/malignancy', ddRelevance: ['obstruction', 'ascites', 'mass'] },
    { id: 'distension_rate', label: 'Rate of progression', type: 'select' as const, options: ['hours', 'days', 'weeks', 'months'], mandatory: true, purpose: 'Acute = surgical, chronic = medical', ddRelevance: ['surgical_abdomen', 'medical_distension'] },
    { id: 'distension_girth_change', label: 'Change in abdominal girth?', type: 'text' as const, mandatory: false, purpose: 'Objective measure of progression' },
    { id: 'distension_positional', label: 'Positional variation?', type: 'boolean' as const, mandatory: false, purpose: 'Ascites shifts, gas does not', ddRelevance: ['ascites', 'obstruction'] },
    { id: 'distension_visible_peristalsis', label: 'Visible peristalsis?', type: 'boolean' as const, mandatory: true, purpose: 'Visible peristalsis = obstruction', ddRelevance: ['obstruction'] },
    { id: 'distension_pain_relation', label: 'Relation to pain', type: 'select' as const, options: ['pain_before_distension', 'distension_before_pain', 'same_time', 'no_pain'], mandatory: true, purpose: 'Pain before distension = surgical, distension without pain = medical', ddRelevance: ['surgical_abdomen', 'medical_distension'] },
    { id: 'distension_flatus', label: 'Passing flatus?', type: 'boolean' as const, mandatory: true, purpose: 'No flatus = complete obstruction', ddRelevance: ['obstruction'] },
    { id: 'distension_bowel_movement', label: 'Last bowel movement?', type: 'text' as const, mandatory: true, purpose: 'Constipation days since last BM = key data', ddRelevance: ['obstruction'] },
    { id: 'distension_previous_similar', label: 'Previous similar episodes?', type: 'boolean' as const, mandatory: true, purpose: 'Recurrent = volvulus/IBS/chronic constipation', ddRelevance: ['volvulus', 'IBS', 'chronic_constipation'] },
    { id: 'distension_worsened_by', label: 'Aggravated by eating?', type: 'boolean' as const, mandatory: false, purpose: 'Post-prandial distension = obstruction/IBS' },
  ],
  associatedSymptomPrompt: 'Along with the distension, have you noticed?',
  associatedSymptomOptions: [
    { category: 'pain', label: 'Abdominal pain' },
    { category: 'vomiting', label: 'Vomiting' },
    { category: 'constipation', label: 'Constipation' },
    { category: 'fever', label: 'Fever' },
    { category: 'dyspnea', label: 'Shortness of breath' },
    { category: 'urinary', label: 'Urinary symptoms' },
    { category: 'constitutional', label: 'Weight loss' },
    { category: 'constitutional', label: 'Loss of appetite' },
  ],
  completionCriteria: [
    'Onset recorded',
    'Course recorded',
    'Rate of progression recorded',
    'Flatus status recorded',
    'Last bowel movement recorded',
    'Previous similar episodes screened',
    'Visible peristalsis screened',
    'Pain relation to distension recorded',
  ],
};

export const CONSTIPATION_TEMPLATE = {
  symptomCategory: 'constipation' as const,
  name: 'Constipation Exploration',
  coreFields: [
    { id: 'constipation_duration', label: 'Duration of constipation?', type: 'text' as const, mandatory: true, purpose: 'Acute vs chronic = different causes', ddRelevance: ['obstruction', 'chronic_constipation', 'IBS'] },
    { id: 'constipation_last_bm', label: 'Date of last bowel movement?', type: 'text' as const, mandatory: true, purpose: 'Core data point for obstruction' },
    { id: 'constipation_completeness', label: 'Complete or partial?', type: 'select' as const, options: ['complete_no_stool', 'complete_no_flatus', 'partial_some_flatus', 'partial_small_stool'], mandatory: true, purpose: 'Complete = obstruction', ddRelevance: ['obstruction'] },
    { id: 'constipation_prior_habit', label: 'Prior bowel habit', type: 'select' as const, options: ['daily', 'alternate_days', 'twice_daily', 'irregular', 'chronic_constipation', 'laxative_dependent'], mandatory: true, purpose: 'Change from baseline = significant', ddRelevance: ['obstruction', 'IBS', 'cancer'] },
    { id: 'constipation_stool_caliber', label: 'Change in stool caliber?', type: 'select' as const, options: ['normal', 'narrow_pencil', 'broader', 'ribbon_like', 'not_applicable'], mandatory: false, purpose: 'Narrow caliber = rectal mass', ddRelevance: ['rectal_cancer', 'stricture'] },
    { id: 'constipation_blood', label: 'Rectal bleeding?', type: 'boolean' as const, mandatory: true, purpose: 'Bleeding = cancer / fissure / haemorrhoids', ddRelevance: ['CRC', 'fissure', 'haemorrhoids'] },
    { id: 'constipation_mucus', label: 'Mucus with stool?', type: 'boolean' as const, mandatory: false, purpose: 'Mucus = IBS / colitis', ddRelevance: ['IBS', 'colitis'] },
    { id: 'constipation_straining', label: 'Straining to pass?', type: 'boolean' as const, mandatory: false, purpose: 'Dyssynergic defecation / pelvic floor' },
    { id: 'constipation_laxative_use', label: 'Laxative use?', type: 'text' as const, mandatory: false, purpose: 'Chronic laxative use = dependency' },
    { id: 'constipation_previous_similar', label: 'Previous similar episodes?', type: 'boolean' as const, mandatory: false, purpose: 'Recurrent = chronic constipation / volvulus / IBS', ddRelevance: ['volvulus', 'IBS'] },
    { id: 'constipation_tenesmus', label: 'Sensation of incomplete evacuation?', type: 'boolean' as const, mandatory: false, purpose: 'Tenesmus = rectal mass / proctitis', ddRelevance: ['rectal_cancer', 'proctitis'] },
  ],
  associatedSymptomPrompt: 'Along with the constipation, have you noticed?',
  associatedSymptomOptions: [
    { category: 'pain', label: 'Abdominal pain' },
    { category: 'distension', label: 'Abdominal distension' },
    { category: 'vomiting', label: 'Vomiting' },
    { category: 'bleeding', label: 'Rectal bleeding' },
    { category: 'fever', label: 'Fever' },
    { category: 'constitutional', label: 'Weight loss' },
    { category: 'constitutional', label: 'Loss of appetite' },
  ],
  completionCriteria: [
    'Duration recorded',
    'Last bowel movement recorded',
    'Complete vs partial recorded',
    'Prior bowel habit recorded',
    'Rectal bleeding screened',
    'Previous similar episodes screened',
  ],
};

export const COUGH_TEMPLATE = {
  symptomCategory: 'cough' as const,
  name: 'Cough Exploration',
  coreFields: [
    { id: 'cough_onset', label: 'When did cough start?', type: 'text' as const, mandatory: true, purpose: 'Acute vs chronic', ddRelevance: ['pneumonia', 'bronchitis', 'TB', 'asthma'] },
    { id: 'cough_duration', label: 'Duration', type: 'text' as const, mandatory: true, purpose: '<3 weeks = acute, >8 weeks = chronic', ddRelevance: ['acute_respiratory', 'chronic_respiratory', 'TB', 'malignancy'] },
    { id: 'cough_type', label: 'Dry or productive?', type: 'select' as const, options: ['dry', 'productive', 'mixed'], mandatory: true, purpose: 'Dry = viral/asthma/insterstitial, productive = infection/ suppurative', ddRelevance: ['pneumonia', 'bronchitis', 'asthma', 'TB', 'bronchiectasis'] },
    { id: 'cough_sputum_character', label: 'Sputum character (if productive)', type: 'multi_select' as const, options: ['clear', 'white', 'yellow', 'green', 'rusty', 'blood_tinged', 'frothy', 'foul_smelling', 'not_applicable'], mandatory: true, purpose: 'Colour = infection type, blood = TB/cancer/embolism', ddRelevance: ['pneumonia', 'bronchiectasis', 'TB', 'cancer', 'abscess'] },
    { id: 'cough_sputum_volume', label: 'Sputum volume per day', type: 'select' as const, options: ['scanty', 'moderate', 'copious', 'not_applicable'], mandatory: false, purpose: 'Copious = bronchiectasis / abscess', ddRelevance: ['bronchiectasis', 'abscess'] },
    { id: 'cough_timing', label: 'Timing (time of day)', type: 'select' as const, options: ['morning', 'evening', 'night', 'all_day', 'positional', 'after_meals'], mandatory: true, purpose: 'Night = asthma/GORD, morning = bronchitis, after meals = aspiration', ddRelevance: ['asthma', 'bronchitis', 'GORD', 'aspiration'] },
    { id: 'cough_triggers', label: 'Triggers', type: 'multi_select' as const, options: ['cold_air', 'exercise', 'dust', 'smoke', 'lying_flat', 'eating', 'talking', 'none', 'other'], mandatory: false, purpose: 'Identifies aetiology', ddRelevance: ['asthma', 'GORD', 'allergy'] },
    { id: 'cough_hemoptysis', label: 'Coughing up blood?', type: 'boolean' as const, mandatory: true, purpose: 'Red flag — TB / cancer / PE / bronchiectasis', safetyRelevance: ['hemoptysis'], ddRelevance: ['TB', 'cancer', 'PE', 'bronchiectasis'] },
    { id: 'cough_breathlessness', label: 'Shortness of breath with cough?', type: 'boolean' as const, mandatory: true, purpose: 'Assesses severity and respiratory compromise', safetyRelevance: ['respiratory_distress'], ddRelevance: ['pneumonia', 'asthma_exacerbation', 'COPD_exacerbation'] },
    { id: 'cough_chest_pain', label: 'Chest pain with cough?', type: 'boolean' as const, mandatory: false, purpose: 'Pleuritic pain = pneumonia / PE', ddRelevance: ['pneumonia', 'PE', 'pleurisy'] },
    { id: 'cough_fever', label: 'Fever with cough?', type: 'boolean' as const, mandatory: true, purpose: 'Fever + cough = pneumonia / bronchitis', ddRelevance: ['pneumonia', 'bronchitis', 'COVID'] },
    { id: 'cough_exposure', label: 'TB exposure history?', type: 'boolean' as const, mandatory: false, purpose: 'TB contact = active TB screening', ddRelevance: ['TB'] },
  ],
  associatedSymptomPrompt: 'Along with the cough, have you noticed?',
  associatedSymptomOptions: [
    { category: 'fever', label: 'Fever' },
    { category: 'dyspnea', label: 'Shortness of breath' },
    { category: 'cardiac', label: 'Chest pain/tightness' },
    { category: 'bleeding', label: 'Coughing blood' },
    { category: 'constitutional', label: 'Weight loss' },
    { category: 'constitutional', label: 'Night sweats' },
    { category: 'constitutional', label: 'Loss of appetite' },
  ],
  completionCriteria: [
    'Onset recorded',
    'Duration recorded',
    'Dry vs productive recorded',
    'Sputum character recorded (if productive)',
    'Hemoptysis screened',
    'Breathlessness screened',
    'Fever screened',
    'Timing recorded',
  ],
};

export const BLEEDING_TEMPLATE = {
  symptomCategory: 'bleeding' as const,
  name: 'Bleeding Exploration',
  coreFields: [
    { id: 'bleeding_site', label: 'Bleeding site', type: 'select' as const, options: ['rectal', 'hematemesis', 'epistaxis', 'vaginal', 'hematuria', 'wound', 'gums', 'skin_bruising', 'multiple_sites', 'other'], mandatory: true, purpose: 'Site guides investigation and urgency' },
    { id: 'bleeding_onset', label: 'When did bleeding start?', type: 'text' as const, mandatory: true, purpose: 'Acute vs chronic blood loss' },
    { id: 'bleeding_duration', label: 'Duration of bleeding', type: 'text' as const, mandatory: true, purpose: 'Acute ongoing = emergency' },
    { id: 'bleeding_volume', label: 'Estimated volume', type: 'select' as const, options: ['spots', 'streaks', 'tea_spoon', 'table_spoon', 'cup', 'multiple_cups', 'unable_to_estimate'], mandatory: true, purpose: 'Quantifies blood loss severity', safetyRelevance: ['massive_hemorrhage'] },
    { id: 'bleeding_color', label: 'Color of blood', type: 'select' as const, options: ['bright_red', 'dark_red', 'maroon', 'black_tarry', 'coffee_ground', 'mixed_with_stool', 'on_surface'], mandatory: true, purpose: 'Bright red = distal, dark/melena = proximal', ddRelevance: ['UGIB', 'LGIB', 'rectal_bleeding'] },
    { id: 'bleeding_associated_pain', label: 'Pain with bleeding?', type: 'boolean' as const, mandatory: false, purpose: 'Painless = cancer/diverticulosis, painful = fissure/colitis', ddRelevance: ['CRC', 'fissure', 'colitis', 'diverticulitis'] },
    { id: 'bleeding_clots', label: 'Clots present?', type: 'boolean' as const, mandatory: false, purpose: 'Clots = significant bleeding' },
    { id: 'bleeding_symptoms_anaemia', label: 'Symptoms of anaemia?', type: 'multi_select' as const, options: ['dizziness', 'fatigue', 'pallor', 'palpitations', 'breathlessness', 'chest_pain', 'none'], mandatory: true, purpose: 'Assesses haemodynamic impact', safetyRelevance: ['anaemia_symptoms'] },
    { id: 'bleeding_anticoagulants', label: 'On anticoagulants/antiplatelets?', type: 'boolean' as const, mandatory: true, purpose: 'Warfarin/DOAP/aspirin — reversal may be needed', safetyRelevance: ['anticoagulation'] },
    { id: 'bleeding_previous_episodes', label: 'Previous bleeding episodes?', type: 'boolean' as const, mandatory: false, purpose: 'Recurrent = chronic condition', ddRelevance: ['diverticulosis', 'AVM', 'haemorrhoids', 'ulcer'] },
    { id: 'bleeding_associated_symptoms', label: 'Associated GI symptoms', type: 'multi_select' as const, options: ['abdominal_pain', 'nausea', 'vomiting', 'diarrhea', 'constipation', 'tenesmus', 'weight_loss', 'none'], mandatory: false, purpose: 'Context for GI bleeding' },
  ],
  associatedSymptomPrompt: 'Along with the bleeding, have you noticed?',
  associatedSymptomOptions: [
    { category: 'pain', label: 'Abdominal pain' },
    { category: 'vomiting', label: 'Vomiting blood' },
    { category: 'constipation', label: 'Constipation' },
    { category: 'diarrhea', label: 'Diarrhea' },
    { category: 'constitutional', label: 'Weight loss' },
    { category: 'constitutional', label: 'Fatigue/dizziness' },
    { category: 'fever', label: 'Fever' },
  ],
  completionCriteria: [
    'Site recorded',
    'Onset recorded',
    'Duration recorded',
    'Volume estimated',
    'Color recorded',
    'Anticoagulant use screened',
    'Anaemia symptoms screened',
  ],
};

export const DYSPNEA_TEMPLATE = {
  symptomCategory: 'dyspnea' as const,
  name: 'Breathlessness Exploration',
  coreFields: [
    { id: 'dyspnea_onset', label: 'When did breathlessness start?', type: 'text' as const, mandatory: true, purpose: 'Acute vs chronic', ddRelevance: ['asthma', 'PE', 'pneumonia', 'COPD', 'heart_failure'] },
    { id: 'dyspnea_duration', label: 'Duration', type: 'text' as const, mandatory: true, purpose: 'Minutes = PE/asthma, hours = pneumonia, days-weeks = effusion/ heart failure' },
    { id: 'dyspnea_course', label: 'Course since onset', type: 'select' as const, options: ['rapidly_worsening', 'slowly_worsening', 'stable', 'improving', 'episodic'], mandatory: true, purpose: 'Rapid deterioration = emergency', safetyRelevance: ['respiratory_failure'] },
    { id: 'dyspnea_mrc_grade', label: 'MRC breathlessness grade', type: 'select' as const, options: ['1_strenuous', '2_hurrying', '3_walking_peers', '4_stops_100m', '5_homebound'], mandatory: true, purpose: 'Objective severity measure' },
    { id: 'dyspnea_orthopnea', label: 'Orthopnoea?', type: 'boolean' as const, mandatory: true, purpose: 'Heart failure / COPD', ddRelevance: ['heart_failure', 'COPD'] },
    { id: 'dyspnea_pnd', label: 'Paroxysmal nocturnal dyspnoea?', type: 'boolean' as const, mandatory: false, purpose: 'Classic for heart failure', ddRelevance: ['heart_failure'] },
    { id: 'dyspnea_positional', label: 'Worse lying flat?', type: 'boolean' as const, mandatory: true, purpose: 'Orthopnoea = cardiac / diaphragmatic splinting', ddRelevance: ['heart_failure', 'ascites', 'obstruction'] },
    { id: 'dyspnea_exertional', label: 'Worse on exertion?', type: 'boolean' as const, mandatory: true, purpose: 'Exertional = cardiac/respiratory limitation' },
    { id: 'dyspnea_cough', label: 'Associated cough?', type: 'boolean' as const, mandatory: true, purpose: 'Cough + dyspnea = respiratory infection / asthma / COPD' },
    { id: 'dyspnea_chest_pain', label: 'Chest pain?', type: 'boolean' as const, mandatory: true, purpose: 'Pleuritic = PE/pneumonia, central = MI', safetyRelevance: ['chest_pain'], ddRelevance: ['PE', 'MI', 'pneumonia'] },
    { id: 'dyspnea_ankle_swelling', label: 'Ankle swelling?', type: 'boolean' as const, mandatory: false, purpose: 'Peripheral oedema = heart failure', ddRelevance: ['heart_failure'] },
    { id: 'dyspnea_wheeze', label: 'Wheezing?', type: 'boolean' as const, mandatory: true, purpose: 'Wheeze = asthma/COPD/anaphylaxis', ddRelevance: ['asthma', 'COPD', 'anaphylaxis'] },
    { id: 'dyspnea_sputum', label: 'Sputum production?', type: 'boolean' as const, mandatory: false, purpose: 'Sputum = infection/bronchiectasis' },
  ],
  associatedSymptomPrompt: 'Along with the breathlessness, have you noticed?',
  associatedSymptomOptions: [
    { category: 'cough', label: 'Cough' },
    { category: 'fever', label: 'Fever' },
    { category: 'cardiac', label: 'Chest pain/tightness' },
    { category: 'cardiac', label: 'Palpitations' },
    { category: 'constitutional', label: 'Ankle swelling' },
    { category: 'bleeding', label: 'Coughing blood' },
  ],
  completionCriteria: [
    'Onset recorded',
    'Duration recorded',
    'Course recorded',
    'MRC grade recorded',
    'Orthopnoea screened',
    'Chest pain screened',
    'Wheeze screened',
    'Cough screened',
    'Positional variation recorded',
  ],
};

export const DIARRHEA_TEMPLATE = {
  symptomCategory: 'diarrhea' as const,
  name: 'Diarrhea Exploration',
  coreFields: [
    { id: 'diarrhea_onset', label: 'When did diarrhea start?', type: 'text' as const, mandatory: true, purpose: 'Acute vs chronic', ddRelevance: ['gastroenteritis', 'IBD', 'IBS', 'infection'] },
    { id: 'diarrhea_duration', label: 'Duration', type: 'text' as const, mandatory: true, purpose: '<2 weeks = acute, >4 weeks = chronic' },
    { id: 'diarrhea_frequency', label: 'Frequency per day', type: 'number' as const, mandatory: true, purpose: 'Assesses severity and dehydration risk' },
    { id: 'diarrhea_consistency', label: 'Consistency', type: 'select' as const, options: ['watery', 'loose', 'semi_formed', 'mucoid', 'bloody', 'rice_water'], mandatory: true, purpose: 'Helps differentiate aetiology', ddRelevance: ['gastroenteritis', 'IBD', 'cholera', 'dysentery'] },
    { id: 'diarrhea_blood', label: 'Blood in stool?', type: 'boolean' as const, mandatory: true, purpose: 'Dysentery / IBD / ischaemic colitis', safetyRelevance: ['dysentery'], ddRelevance: ['IBD', 'dysentery', 'ischaemic_colitis'] },
    { id: 'diarrhea_mucus', label: 'Mucus in stool?', type: 'boolean' as const, mandatory: false, purpose: 'Mucus = IBD / IBS / infection', ddRelevance: ['IBD', 'IBS'] },
    { id: 'diarrhea_urgency', label: 'Urgency/tenesmus?', type: 'boolean' as const, mandatory: false, purpose: 'Rectal inflammation = IBD / infection', ddRelevance: ['IBD', 'proctitis'] },
    { id: 'diarrhea_night_waking', label: 'Wakes from sleep?', type: 'boolean' as const, mandatory: true, purpose: 'Organic = wakes from sleep, functional = does not', ddRelevance: ['IBD', 'IBS'] },
    { id: 'diarrhea_abdominal_pain', label: 'Abdominal pain with diarrhea?', type: 'boolean' as const, mandatory: true, purpose: 'Pain pattern helps differentiate', ddRelevance: ['IBD', 'IBS', 'gastroenteritis'] },
    { id: 'diarrhea_vomiting', label: 'Vomiting with diarrhea?', type: 'boolean' as const, mandatory: true, purpose: 'Gastroenteritis / food poisoning', ddRelevance: ['gastroenteritis', 'food_poisoning'] },
    { id: 'diarrhea_fever', label: 'Fever with diarrhea?', type: 'boolean' as const, mandatory: true, purpose: 'Invasive infection / IBD flare', ddRelevance: ['dysentery', 'IBD_flare', 'infection'] },
    { id: 'diarrhea_travel', label: 'Recent travel?', type: 'boolean' as const, mandatory: false, purpose: 'Traveler\'s diarrhea / parasitic infection', ddRelevance: ['traveler_diarrhea', 'parasitic'] },
    { id: 'diarrhea_antibiotics', label: 'Recent antibiotics?', type: 'boolean' as const, mandatory: false, purpose: 'C. diff risk', ddRelevance: ['C_diff', 'antibiotic_associated'] },
    { id: 'diarrhea_contacts', label: 'Similar illness in contacts?', type: 'boolean' as const, mandatory: false, purpose: 'Infectious outbreak' },
  ],
  associatedSymptomPrompt: 'Along with the diarrhea, have you noticed?',
  associatedSymptomOptions: [
    { category: 'vomiting', label: 'Vomiting' },
    { category: 'fever', label: 'Fever' },
    { category: 'pain', label: 'Abdominal pain' },
    { category: 'bleeding', label: 'Blood in stool' },
    { category: 'constitutional', label: 'Weight loss' },
    { category: 'constitutional', label: 'Loss of appetite' },
  ],
  completionCriteria: [
    'Onset recorded',
    'Duration recorded',
    'Frequency recorded',
    'Consistency recorded',
    'Blood in stool screened',
    'Fever screened',
    'Vomiting screened',
    'Night waking screened',
  ],
};

export const NEUROLOGICAL_TEMPLATE = {
  symptomCategory: 'neurological' as const,
  name: 'Neurological Symptom Exploration',
  coreFields: [
    { id: 'neuro_type', label: 'Type of neurological symptom', type: 'select' as const, options: ['headache', 'seizure', 'weakness', 'numbness', 'dizziness', 'visual_change', 'speech_change', 'hearing_loss', 'tremor', 'memory_loss', 'gait_disturbance', 'loss_of_consciousness', 'other'], mandatory: true, purpose: 'Type determines further exploration' },
    { id: 'neuro_onset', label: 'When did it start?', type: 'text' as const, mandatory: true, purpose: 'Sudden vs gradual = different causes', ddRelevance: ['stroke', 'TIA', 'migraine', 'tumour'] },
    { id: 'neuro_onset_speed', label: 'Speed of onset', type: 'select' as const, options: ['sudden_seconds', 'sudden_minutes', 'gradual_hours', 'gradual_days', 'gradual_weeks', 'gradual_months'], mandatory: true, purpose: 'Sudden = vascular, gradual = degenerative/ mass', ddRelevance: ['stroke', 'TIA', 'tumour', 'neuropathy'] },
    { id: 'neuro_duration', label: 'Duration of symptom', type: 'text' as const, mandatory: true, purpose: 'Transient vs persistent', ddRelevance: ['TIA', 'seizure', 'migraine'] },
    { id: 'neuro_course', label: 'Course since onset', type: 'select' as const, options: ['improving', 'worsening', 'unchanged', 'fluctuating', 'episodic'], mandatory: true, purpose: 'Progressive = mass/degenerative' },
    { id: 'neuro_laterality', label: 'Laterality', type: 'select' as const, options: ['unilateral', 'bilateral', 'central', 'migrating', 'alternating', 'not_applicable'], mandatory: true, purpose: 'Unilateral = vascular/focal, bilateral = global/metabolic', ddRelevance: ['stroke', 'TIA', 'migraine'] },
    { id: 'neuro_associated_headache', label: 'Headache?', type: 'boolean' as const, mandatory: true, purpose: 'Headache + neuro = migraine / SAH / mass / meningitis', safetyRelevance: ['SAH', 'meningitis'] },
    { id: 'neuro_associated_fever', label: 'Fever?', type: 'boolean' as const, mandatory: true, purpose: 'Fever + neuro = meningitis/encephalitis', safetyRelevance: ['CNS_infection'] },
    { id: 'neuro_associated_vomiting', label: 'Vomiting?', type: 'boolean' as const, mandatory: false, purpose: 'Vomiting + headache = raised ICP', ddRelevance: ['raised_ICP', 'migraine'] },
    { id: 'neuro_neck_stiffness', label: 'Neck stiffness?', type: 'boolean' as const, mandatory: false, purpose: 'Meningism = meningitis/SAH', safetyRelevance: ['meningitis', 'SAH'] },
    { id: 'neuro_visual_changes', label: 'Visual changes?', type: 'multi_select' as const, options: ['blurring', 'double_vision', 'vision_loss', 'flashing_lights', 'floaters', 'photophobia', 'none'], mandatory: false, purpose: 'Localizes lesion', ddRelevance: ['migraine', 'stroke', 'raised_ICP', 'MS'] },
    { id: 'neuro_speech', label: 'Speech changes?', type: 'select' as const, options: ['slurred', 'aphasia', 'dysarthria', 'none', 'not_applicable'], mandatory: false, purpose: 'Stroke / TIA / mass', ddRelevance: ['stroke', 'TIA', 'mass'] },
    { id: 'neuro_weakness_distribution', label: 'Weakness distribution', type: 'select' as const, options: ['hemiparesis', 'monoparesis', 'paraparesis', 'quadriparesis', 'facial', 'not_applicable'], mandatory: false, purpose: 'Localizes lesion', ddRelevance: ['stroke', 'cord_compression', 'neuropathy'] },
    { id: 'neuro_loss_of_consciousness', label: 'Loss of consciousness?', type: 'boolean' as const, mandatory: true, purpose: 'Syncope / seizure / arrhythmia / stroke', safetyRelevance: ['LOC'], ddRelevance: ['seizure', 'syncope', 'arrhythmia'] },
    { id: 'neuro_seizure_type', label: 'Seizure description (if applicable)', type: 'multi_select' as const, options: ['generalized_tonic_clonic', 'absence', 'focal', 'secondary_generalized', 'not_applicable'], mandatory: false, purpose: 'Type determines aetiology and management' },
  ],
  associatedSymptomPrompt: 'Along with the neurological symptoms, have you noticed?',
  associatedSymptomOptions: [
    { category: 'fever', label: 'Fever' },
    { category: 'vomiting', label: 'Vomiting' },
    { category: 'pain', label: 'Headache' },
    { category: 'neurological', label: 'Any other neurological symptom' },
    { category: 'cardiac', label: 'Palpitations/chest pain' },
    { category: 'trauma', label: 'Head injury' },
    { category: 'constitutional', label: 'Weight loss' },
  ],
  completionCriteria: [
    'Type of symptom recorded',
    'Onset recorded',
    'Speed of onset recorded',
    'Duration recorded',
    'Course recorded',
    'Laterality recorded',
    'Loss of consciousness screened',
    'Fever screened',
    'Headache screened',
  ],
};

export const CONSTITUTIONAL_TEMPLATE = {
  symptomCategory: 'constitutional' as const,
  name: 'Constitutional Symptom Exploration',
  coreFields: [
    { id: 'constitutional_type', label: 'Type of constitutional symptom', type: 'multi_select' as const, options: ['weight_loss', 'loss_of_appetite', 'fatigue', 'night_sweats', 'fever', 'generalized_weakness', 'decreased_urination', 'thirst', 'insomnia'], mandatory: true, purpose: 'Systemic impact assessment' },
    { id: 'constitutional_weight_loss', label: 'Weight loss amount (if applicable)', type: 'text' as const, mandatory: false, purpose: 'Significant = malignancy / chronic infection / malabsorption', ddRelevance: ['malignancy', 'TB', 'HIV', 'malabsorption'] },
    { id: 'constitutional_weight_period', label: 'Period over which weight lost', type: 'text' as const, mandatory: false, purpose: 'Rate of weight loss = urgency' },
    { id: 'constitutional_appetite_change', label: 'Appetite change', type: 'select' as const, options: ['normal', 'reduced', 'increased', 'aversion_to_food', 'early_satiety'], mandatory: true, purpose: 'Anorexia = systemic illness / malignancy / GI pathology' },
    { id: 'constitutional_fatigue', label: 'Fatigue severity', type: 'select' as const, options: ['mild', 'moderate', 'severe', 'bed_bound'], mandatory: false, purpose: 'Functional impact assessment' },
    { id: 'constitutional_night_sweats', label: 'Night sweats?', type: 'boolean' as const, mandatory: false, purpose: 'B symptom = TB / lymphoma / HIV', ddRelevance: ['TB', 'lymphoma', 'HIV'] },
    { id: 'constitutional_fever_sensation', label: 'Feeling feverish?', type: 'boolean' as const, mandatory: true, purpose: 'Systemic infection / inflammation' },
    { id: 'constitutional_decreased_urine', label: 'Decreased urination?', type: 'boolean' as const, mandatory: true, purpose: 'Dehydration / AKI / obstruction', safetyRelevance: ['AKI'] },
    { id: 'constitutional_functional_status', label: 'Current functional status', type: 'select' as const, options: ['independent', 'needs_assistance', 'bed_bound', 'confined_to_home'], mandatory: true, purpose: 'Overall severity assessment' },
    { id: 'constitutional_duration', label: 'Duration of constitutional symptoms', type: 'text' as const, mandatory: true, purpose: 'Acute vs chronic systemic illness' },
  ],
  associatedSymptomPrompt: 'Along with these general symptoms, have you noticed?',
  associatedSymptomOptions: [
    { category: 'fever', label: 'Documented fever' },
    { category: 'pain', label: 'Pain (any site)' },
    { category: 'cough', label: 'Cough' },
    { category: 'diarrhea', label: 'Diarrhea' },
    { category: 'bleeding', label: 'Bleeding' },
    { category: 'skin', label: 'Rash' },
    { category: 'neurological', label: 'Neurological symptoms' },
  ],
  completionCriteria: [
    'Type of constitutional symptom recorded',
    'Appetite change recorded',
    'Fever sensation screened',
    'Decreased urination screened',
    'Functional status recorded',
    'Duration recorded',
  ],
};

export const URINARY_TEMPLATE = {
  symptomCategory: 'urinary' as const,
  name: 'Urinary Symptom Exploration',
  coreFields: [
    { id: 'urinary_type', label: 'Type of urinary symptom', type: 'multi_select' as const, options: ['dysuria', 'frequency', 'urgency', 'nocturia', 'hematuria', 'retention', 'incontinence', 'oliguria', 'polyuria', 'difficulty_starting', 'weak_stream'], mandatory: true, purpose: 'Type determines cause' },
    { id: 'urinary_onset', label: 'When did symptoms start?', type: 'text' as const, mandatory: true, purpose: 'Acute vs chronic' },
    { id: 'urinary_duration', label: 'Duration', type: 'text' as const, mandatory: true, purpose: 'Helps differentiate infection vs obstruction vs BPH vs diabetes' },
    { id: 'urinary_dysuria', label: 'Pain/burning on urination?', type: 'boolean' as const, mandatory: true, purpose: 'UTI / STI / stone', ddRelevance: ['UTI', 'STI', 'stone'] },
    { id: 'urinary_frequency', label: 'Frequency (times per day)', type: 'number' as const, mandatory: false, purpose: 'Frequency = UTI / BPH / diabetes / OAB' },
    { id: 'urinary_hematuria', label: 'Blood in urine?', type: 'boolean' as const, mandatory: true, purpose: 'UTI / stone / cancer / GN', safetyRelevance: ['hematuria'], ddRelevance: ['UTI', 'stone', 'cancer', 'GN'] },
    { id: 'urinary_retention', label: 'Unable to pass urine?', type: 'boolean' as const, mandatory: true, purpose: 'Acute retention = emergency — catheterization needed', safetyRelevance: ['retention'], ddRelevance: ['BPH', 'obstruction', 'neurogenic'] },
    { id: 'urinary_oliguria', label: 'Decreased urine output?', type: 'boolean' as const, mandatory: true, purpose: 'AKI / dehydration / obstruction', safetyRelevance: ['AKI'] },
    { id: 'urinary_flank_pain', label: 'Flank/loin pain?', type: 'boolean' as const, mandatory: false, purpose: 'Pyelonephritis / stone', ddRelevance: ['pyelonephritis', 'stone'] },
    { id: 'urinary_fever', label: 'Fever with urinary symptoms?', type: 'boolean' as const, mandatory: true, purpose: 'Upper UTI / pyelonephritis / prostatitis', ddRelevance: ['pyelonephritis', 'prostatitis'] },
    { id: 'urinary_vaginal_discharge', label: 'Vaginal/urethral discharge?', type: 'boolean' as const, mandatory: false, purpose: 'STI / vaginitis', ddRelevance: ['STI'] },
  ],
  associatedSymptomPrompt: 'Along with the urinary symptoms, have you noticed?',
  associatedSymptomOptions: [
    { category: 'fever', label: 'Fever' },
    { category: 'pain', label: 'Flank/loin pain' },
    { category: 'bleeding', label: 'Blood in urine' },
    { category: 'vomiting', label: 'Vomiting' },
    { category: 'distension', label: 'Abdominal distension (retention)' },
    { category: 'constitutional', label: 'Increased thirst/weight loss' },
  ],
  completionCriteria: [
    'Type of symptom recorded',
    'Onset recorded',
    'Duration recorded',
    'Dysuria screened',
    'Hematuria screened',
    'Retention screened',
    'Oliguria screened',
    'Fever screened',
  ],
};

export const WEAKNESS_TEMPLATE = {
  symptomCategory: 'weakness' as const,
  name: 'Generalized Weakness Exploration',
  coreFields: [
    { id: 'weakness_onset', label: 'When did weakness start?', type: 'text' as const, mandatory: true, purpose: 'Acute vs chronic', ddRelevance: ['anaemia', 'infection', 'endocrine', 'malignancy', 'neuromuscular'] },
    { id: 'weakness_duration', label: 'Duration', type: 'text' as const, mandatory: true, purpose: 'Acute hours = infection/metabolic, chronic weeks = anaemia/malignancy' },
    { id: 'weakness_course', label: 'Course since onset', type: 'select' as const, options: ['worsening', 'stable', 'improving', 'fluctuating'], mandatory: true, purpose: 'Progressive = neuromuscular/malignancy' },
    { id: 'weakness_distribution', label: 'Distribution', type: 'select' as const, options: ['generalized', 'proximal_muscles', 'distal_muscles', 'unilateral', 'lower_limbs', 'upper_limbs', 'focal'], mandatory: true, purpose: 'Generalized = systemic, proximal = myopathy, distal = neuropathy' },
    { id: 'weakness_functional_impact', label: 'Functional impact', type: 'multi_select' as const, options: ['walking', 'standing', 'lifting', 'grooming', 'eating', 'working', 'none'], mandatory: true, purpose: 'Severity assessment' },
    { id: 'weakness_fatigue_vs_weakness', label: 'Fatigue vs true weakness?', type: 'select' as const, options: ['true_motor_weakness', 'fatigue_tiredness', 'both'], mandatory: true, purpose: 'True weakness = neurological/muscular, fatigue = systemic' },
    { id: 'weakness_associated_symptoms', label: 'Associated symptoms', type: 'multi_select' as const, options: ['weight_loss', 'fever', 'night_sweats', 'pallor', 'breathlessness', 'palpitations', 'loss_of_appetite', 'joint_pain', 'rash', 'none'], mandatory: true, purpose: 'Identifies underlying cause' },
  ],
  associatedSymptomPrompt: 'Along with the weakness, have you noticed?',
  associatedSymptomOptions: [
    { category: 'constitutional', label: 'Weight loss/loss of appetite' },
    { category: 'fever', label: 'Fever/night sweats' },
    { category: 'dyspnea', label: 'Breathlessness' },
    { category: 'cardiac', label: 'Palpitations' },
    { category: 'bleeding', label: 'Bleeding/bruising' },
    { category: 'pain', label: 'Joint/muscle pain' },
    { category: 'skin', label: 'Rash' },
    { category: 'neurological', label: 'Neurological symptoms' },
    { category: 'urinary', label: 'Increased urination/thirst' },
  ],
  completionCriteria: [
    'Onset recorded',
    'Duration recorded',
    'Course recorded',
    'Distribution recorded',
    'Functional impact recorded',
    'Fatigue vs true weakness determined',
    'Associated systemic symptoms screened',
  ],
};

export const SKIN_TEMPLATE = {
  symptomCategory: 'skin' as const,
  name: 'Skin Symptom Exploration',
  coreFields: [
    { id: 'skin_type', label: 'Type of skin problem', type: 'select' as const, options: ['rash', 'swelling', 'ulcer', 'itching', 'color_change', 'blister', 'nodule', 'wound', 'other'], mandatory: true, purpose: 'Type determines further exploration' },
    { id: 'skin_onset', label: 'When did it start?', type: 'text' as const, mandatory: true, purpose: 'Acute vs chronic' },
    { id: 'skin_duration', label: 'Duration', type: 'text' as const, mandatory: true, purpose: 'Acute = infection/allergy, chronic = eczema/psoriasis' },
    { id: 'skin_location', label: 'Location on body', type: 'text' as const, mandatory: true, purpose: 'Distribution helps diagnosis' },
    { id: 'skin_spread', label: 'Spread/progression', type: 'select' as const, options: ['spreading', 'stable', 'regressing', 'migrating'], mandatory: true, purpose: 'Spreading = infection/progression' },
    { id: 'skin_itching', label: 'Itching?', type: 'boolean' as const, mandatory: true, purpose: 'Atopy / allergy / liver disease / scabies' },
    { id: 'skin_pain', label: 'Pain?', type: 'boolean' as const, mandatory: false, purpose: 'Shingles / cellulitis / abscess / ischaemia' },
    { id: 'skin_fever', label: 'Fever with skin symptoms?', type: 'boolean' as const, mandatory: true, purpose: 'Systemic infection / hypersensitivity', safetyRelevance: ['sepsis'], ddRelevance: ['cellulitis', 'SJS', 'infection'] },
    { id: 'skin_exposure', label: 'Any trigger/exposure?', type: 'multi_select' as const, options: ['new_medication', 'new_food', 'insect_bite', 'new_soap', 'new_clothing', 'sun_exposure', 'contact_person_with_rash', 'none', 'other'], mandatory: false, purpose: 'Identifies aetiology' },
  ],
  associatedSymptomPrompt: 'Along with the skin symptoms, have you noticed?',
  associatedSymptomOptions: [
    { category: 'fever', label: 'Fever' },
    { category: 'pain', label: 'Pain' },
    { category: 'constitutional', label: 'Joint pain' },
    { category: 'constitutional', label: 'Weight loss' },
    { category: 'neurological', label: 'Neurological symptoms' },
  ],
  completionCriteria: [
    'Type recorded',
    'Onset recorded',
    'Duration recorded',
    'Location recorded',
    'Itching screened',
    'Fever screened',
    'Spread recorded',
  ],
};

export const CARDIOVASCULAR_TEMPLATE = {
  symptomCategory: 'cardiac' as const,
  name: 'Cardiovascular Symptom Exploration',
  coreFields: [
    { id: 'cardiac_type', label: 'Type of symptom', type: 'multi_select' as const, options: ['chest_pain', 'palpitations', 'chest_tightness', 'dizziness_on_standing', 'syncope', 'ankle_swelling', 'exertional_chest_discomfort'], mandatory: true, purpose: 'Type determines urgency and aetiology' },
    { id: 'cardiac_onset', label: 'When did it start?', type: 'text' as const, mandatory: true, purpose: 'Acute = ACS/arrhythmia, chronic = heart failure' },
    { id: 'cardiac_duration', label: 'Duration', type: 'text' as const, mandatory: true, purpose: 'Minutes = angina, seconds = palpitation, hours = heart failure' },
    { id: 'cardiac_chest_pain_character', label: 'Chest pain character (if present)', type: 'select' as const, options: ['not_applicable', 'crushing', 'tightness', 'stabbing', 'burning', 'sharp', 'aching'], mandatory: false, purpose: 'Crushing/tightness = cardiac, stabbing = MSK/pleuritic', ddRelevance: ['ACS', 'MSK', 'pleuritic', 'GORD'] },
    { id: 'cardiac_chest_pain_radiation', label: 'Radiation (if chest pain)', type: 'multi_select' as const, options: ['left_arm', 'right_arm', 'jaw', 'back', 'shoulder', 'epigastric', 'none', 'not_applicable'], mandatory: false, purpose: 'Classic cardiac radiation' },
    { id: 'cardiac_exertional', label: 'Related to exertion?', type: 'boolean' as const, mandatory: true, purpose: 'Exertional = angina / heart failure limitation' },
    { id: 'cardiac_relieved_by_rest', label: 'Relieved by rest?', type: 'boolean' as const, mandatory: false, purpose: 'Angina = relieved, non-cardiac = not' },
    { id: 'cardiac_palpitations', label: 'Palpitations — regular or irregular?', type: 'select' as const, options: ['regular', 'irregular', 'skipped_beats', 'racing', 'not_applicable'], mandatory: false, purpose: 'Irregular = AF, regular = SVT/VT' },
    { id: 'cardiac_syncope', label: 'Fainted/lost consciousness?', type: 'boolean' as const, mandatory: true, purpose: 'Cardiac syncope = dangerous', safetyRelevance: ['cardiac_syncope'] },
    { id: 'cardiac_dizziness', label: 'Dizziness on standing?', type: 'boolean' as const, mandatory: false, purpose: 'Postural hypotension / dehydration / autonomic' },
    { id: 'cardiac_ankle_swelling', label: 'Ankle swelling?', type: 'boolean' as const, mandatory: true, purpose: 'Heart failure / venous insufficiency / renal', ddRelevance: ['heart_failure', 'venous_insufficiency'] },
    { id: 'cardiac_orthopnea', label: 'Woken by breathlessness?', type: 'boolean' as const, mandatory: false, purpose: 'PND = heart failure', ddRelevance: ['heart_failure'] },
    { id: 'cardiac_risk_factors', label: 'Cardiac risk factors', type: 'multi_select' as const, options: ['smoking', 'diabetes', 'hypertension', 'high_cholesterol', 'family_history', 'obesity', 'sedentary', 'none'], mandatory: true, purpose: 'Risk stratification', ddRelevance: ['ACS', 'arrhythmia', 'heart_failure'] },
  ],
  associatedSymptomPrompt: 'Along with the cardiovascular symptoms, have you noticed?',
  associatedSymptomOptions: [
    { category: 'dyspnea', label: 'Shortness of breath' },
    { category: 'constitutional', label: 'Dizziness/fainting' },
    { category: 'constitutional', label: 'Fatigue' },
    { category: 'pain', label: 'Chest pain' },
    { category: 'vomiting', label: 'Nausea/vomiting' },
    { category: 'constitutional', label: 'Ankle swelling' },
  ],
  completionCriteria: [
    'Type recorded',
    'Onset recorded',
    'Duration recorded',
    'Exertional relationship recorded',
    'Syncope screened',
    'Ankle swelling screened',
    'Cardiac risk factors recorded',
  ],
};

export const PSYCHOLOGICAL_TEMPLATE = {
  symptomCategory: 'psychological' as const,
  name: 'Psychological Symptom Exploration',
  coreFields: [
    { id: 'psych_type', label: 'Type of symptom', type: 'multi_select' as const, options: ['low_mood', 'anxiety', 'hallucinations', 'delusions', 'memory_loss', 'confusion', 'agitation', 'withdrawal', 'suicidal_thoughts', 'self_harm', 'sleep_disturbance', 'appetite_change'], mandatory: true, purpose: 'Type determines urgency and pathway' },
    { id: 'psych_onset', label: 'When did it start?', type: 'text' as const, mandatory: true, purpose: 'Acute vs chronic — acute confusion = organic cause' },
    { id: 'psych_duration', label: 'Duration', type: 'text' as const, mandatory: true, purpose: 'Days = acute, weeks-months = chronic' },
    { id: 'psych_course', label: 'Course since onset', type: 'select' as const, options: ['worsening', 'stable', 'improving', 'fluctuating'], mandatory: true, purpose: 'Deterioration = need for urgent intervention' },
    { id: 'psych_precipitant', label: 'Any precipitant?', type: 'multi_select' as const, options: ['stress', 'loss', 'illness', 'medication_change', 'substance_use', 'trauma', 'none_identified', 'other'], mandatory: false, purpose: 'Context for symptoms' },
    { id: 'psych_suicidal', label: 'Suicidal thoughts?', type: 'boolean' as const, mandatory: true, purpose: 'Safety critical — immediate assessment needed', safetyRelevance: ['suicidality'] },
    { id: 'psych_self_harm', label: 'Self-harm?', type: 'boolean' as const, mandatory: true, purpose: 'Safety critical', safetyRelevance: ['self_harm'] },
    { id: 'psych_harm_to_others', label: 'Thoughts of harming others?', type: 'boolean' as const, mandatory: true, purpose: 'Safety critical', safetyRelevance: ['harm_to_others'] },
    { id: 'psych_sleep', label: 'Sleep disturbance?', type: 'select' as const, options: ['initial_insomnia', 'mid_waking', 'early_morning_waking', 'hypersomnia', 'nightmares', 'none'], mandatory: true, purpose: 'Sleep pattern is key diagnostic feature' },
    { id: 'psych_appetite', label: 'Appetite change?', type: 'select' as const, options: ['increased', 'decreased', 'normal'], mandatory: false, purpose: 'Appetite change = mood disorder' },
    { id: 'psych_energy', label: 'Energy levels', type: 'select' as const, options: ['normal', 'reduced', 'very_low', 'increased'], mandatory: false, purpose: 'Low = depression, high = mania' },
    { id: 'psych_substance_use', label: 'Alcohol/substance use?', type: 'boolean' as const, mandatory: true, purpose: 'Substance-induced mood/psychosis', ddRelevance: ['substance_induced'] },
    { id: 'psych_previous_episodes', label: 'Previous similar episodes?', type: 'boolean' as const, mandatory: false, purpose: 'Recurrent = chronic condition' },
    { id: 'psych_family_history', label: 'Family history of psychiatric illness?', type: 'boolean' as const, mandatory: false, purpose: 'Genetic predisposition' },
    { id: 'psych_organic_features', label: 'Features suggesting organic cause?', type: 'multi_select' as const, options: ['acute_onset', 'fluctuating_level', 'hallucinations', 'fever', 'headache', 'medication_change', 'known_dementia', 'none'], mandatory: true, purpose: 'Delirium vs functional psychosis', ddRelevance: ['delirium', 'dementia', 'functional'] },
  ],
  associatedSymptomPrompt: 'Along with these symptoms, have you noticed?',
  associatedSymptomOptions: [
    { category: 'constitutional', label: 'Sleep/appetite changes' },
    { category: 'neurological', label: 'Headache/confusion' },
    { category: 'fever', label: 'Fever' },
    { category: 'constitutional', label: 'Weight loss' },
    { category: 'constitutional', label: 'Fatigue' },
    { category: 'pain', label: 'Pain' },
  ],
  completionCriteria: [
    'Type recorded',
    'Onset recorded',
    'Duration recorded',
    'Course recorded',
    'Suicidal thoughts screened',
    'Self-harm screened',
    'Harm to others screened',
    'Sleep disturbance recorded',
    'Organic features screened',
    'Substance use screened',
  ],
};
