import type { SystemExamFieldDef } from '../systemExaminationTypes';

export const CARDIOVASCULAR_FIELDS: readonly SystemExamFieldDef[] = [
  // ── INSPECTION ─────────────────────────────────────────────────────────
  { id: 'cvs_insp_hands', label: 'Hands examination', shortLabel: 'Hands', phase: 'inspection', type: 'multiselect', options: ['normal', 'clubbing', 'splinter_haemorrhages', 'janeway', 'osler_nodes', 'palmar_erythema', 'xanthomata'], mandatory: true, clinicalGuide: 'Inspect nails, palms, and digits; clubbing, splinter haemorrhages, Janeway lesions suggest endocarditis', observation: 'Peripheral stigmata of cardiovascular disease', description: 'Document nail changes, palmar changes, lesions', interpretation: 'Clubbing = cyanotic heart disease/IE; splinter haem = endocarditis; xanthomata = hyperlipidaemia', activatesFields: ['cvs_insp_face'] },
  { id: 'cvs_insp_face', label: 'Face examination', shortLabel: 'Face', phase: 'inspection', type: 'multiselect', options: ['normal', 'mitral_facies', 'malar_flush', 'xanthelasma', 'arcus_senilis', 'central_cyanosis', 'pallor'], mandatory: true, clinicalGuide: 'Inspect face for malar flush (mitral stenosis), xanthelasma (hyperlipidaemia), central cyanosis', observation: 'Facial signs of cardiovascular disease', description: 'Document facial stigmata', interpretation: 'Mitral facies = pulmonary hypertension; xanthelasma/arcus = hyperlipidaemia; cyanosis = shunt/R→L' },
  { id: 'cvs_insp_jvp', label: 'Jugular venous pressure', shortLabel: 'JVP', phase: 'inspection', type: 'select', options: ['normal', 'elevated', 'giant_v_waves', 'cannon_waves', 'kussmaul_sign'], mandatory: true, clinicalGuide: 'Patient reclining at 45°, head turned left; observe for IJPV pulsation above clavicle', observation: 'Height and waveform of internal jugular venous pulsation', description: 'Measure vertical height above sternal angle in cm', measurement: true, unit: 'cm above sternal angle', interpretation: 'Elevated >4 cm = right heart failure, PE, tamponade, SVC obstruction; Kussmaul = constrictive pericarditis', activatesFields: ['cvs_insp_jvp_waveform'] },
  { id: 'cvs_insp_jvp_waveform', label: 'JVP waveform', shortLabel: 'JVP wave', phase: 'inspection', type: 'select', options: ['normal', 'giant_a_waves', 'absent_a_waves', 'giant_v_waves', 'cannon_waves'], mandatory: false, clinicalGuide: 'Observe for dominant waves relative to carotid pulsation', observation: 'Waveform morphology of JVP', description: 'a, c, v wave analysis', interpretation: 'Giant a = TR/pulm HTN; cannon = complete heart block; giant v = TR', isAbnormalOnly: true },
  { id: 'cvs_insp_apex_beat', label: 'Apex beat inspection', shortLabel: 'Apex beat', phase: 'inspection', type: 'select', options: ['visible', 'not_visible', 'displaced'], mandatory: false, clinicalGuide: 'Observe for visible pulsation in 5th intercostal space, midclavicular line', observation: 'Visible cardiac apex beat', description: 'Location of visible apex', interpretation: 'Visible apex beat suggests LVH/hyperdynamic circulation', isAbnormalOnly: true },
  { id: 'cvs_insp_scars', label: 'Chest scars (CVS)', shortLabel: 'Scars', phase: 'inspection', type: 'multiselect', options: ['sternotomy', 'thoracotomy', 'pacemaker_pocket', 'icd_pocket', 'cabg_scar', 'other'], mandatory: false, clinicalGuide: 'Inspect for surgical scars indicating previous cardiac surgery', observation: 'Surgical scars over chest and neck', description: 'Document type and location', interpretation: 'Prior cardiac surgery relevant to current presentation', isAbnormalOnly: true },
  { id: 'cvs_insp_oedema', label: 'Peripheral oedema', shortLabel: 'Oedema', phase: 'inspection', type: 'select', options: ['absent', 'mild_ankle', 'moderate_leg', 'severe_sacral', 'anasarca'], mandatory: true, clinicalGuide: 'Inspect ankles, shins, sacrum for pitting oedema', observation: 'Swelling due to interstitial fluid accumulation', description: 'Grade pitting (1-4) and extent (ankle/leg/sacral)', measurement: true, unit: 'grade (1-4)', interpretation: 'Bilateral = right heart failure/venous insufficiency; unilateral = DVT/lymphoedema' },
  // ── PALPATION ──────────────────────────────────────────────────────────
  { id: 'cvs_palp_apex', label: 'Apex beat palpation', shortLabel: 'Apex beat', phase: 'palpation', type: 'select', options: ['normal', 'displaced', 'thrusting', 'tapping', 'heaving', 'diffuse'], mandatory: true, clinicalGuide: 'Use fingertips; locate in 5th ICS MCL; note character', observation: 'Character and location of the apex beat', description: 'Describe character (tapping = MS, heaving = AS, thrusting = MR/AR)', interpretation: 'Character helps identify underlying valve lesion and ventricular strain' },
  { id: 'cvs_palp_parasternal_heave', label: 'Parasternal heave', shortLabel: 'Parasternal', phase: 'palpation', type: 'boolean', mandatory: true, clinicalGuide: 'Place palm of hand on left parasternal area; feel for lifting movement', observation: 'Lifting sensation felt over left parasternal region during systole', description: 'Present / Absent', interpretation: 'Indicates right ventricular hypertrophy — pulm HTN, PS, or TV disease' },
  { id: 'cvs_palp_thrills', label: 'Thrills', shortLabel: 'Thrills', phase: 'palpation', type: 'multiselect', options: ['absent', 'aortic', 'pulmonic', 'tricuspid', 'mitral'], mandatory: false, clinicalGuide: 'Palpate over valve areas with palm; thrill = palpable murmur', observation: 'Palpable vibration over valve areas', description: 'Locate the thrill (base/apex/left sternal edge)', interpretation: 'Indicates turbulent flow across a valve — usually severe lesion', isAbnormalOnly: true },
  { id: 'cvs_palp_pulses', label: 'Peripheral pulses (all sites)', shortLabel: 'Pulses', phase: 'palpation', type: 'select', options: ['normal', 'weak', 'bounding', 'absent', 'radiofemoral_delay'], mandatory: true, clinicalGuide: 'Palpate radial, brachial, carotid, femoral, popliteal, DP, PT; assess volume, symmetry', observation: 'Pulse volume, symmetry, character at all peripheral sites', description: 'Document all palpable sites and pulse volume (0-3+)', interpretation: 'Absent = PVD/embolism; radiofemoral delay = coarctation; collapsing = AR' },
  { id: 'cvs_palp_radial_character', label: 'Radial pulse character', shortLabel: 'Radial char.', phase: 'palpation', type: 'select', options: ['normal', 'collapsing_waterhammer', 'slow_rising', 'bisferiens', 'dicrotic', 'alternans', 'paradoxus'], mandatory: false, clinicalGuide: 'Feel radial pulse with index and middle finger; assess character', observation: 'Quality and character of the radial pulse', description: 'Describe the waveform character', interpretation: 'Collapsing = AR/PDA; slow rising = AS; bisferiens = AS+AR/HOCM; paradoxus = tamponade/COPD', isAbnormalOnly: true },
  { id: 'cvs_palp_carotid', label: 'Carotid pulse', shortLabel: 'Carotid', phase: 'palpation', type: 'select', options: ['normal', 'slow_rising', 'double_wave', 'waterhammer', 'reduced_volume'], mandatory: false, clinicalGuide: 'Palpate carotid gently; never both at once; assess volume and character', observation: 'Carotid upstroke and volume', description: 'Characterize the upstroke and volume', interpretation: 'Slow rising = AS; waterhammer = AR; double = HOCM; reduced = low CO', isAbnormalOnly: true },
  { id: 'cvs_palp_bp', label: 'Blood pressure', shortLabel: 'BP', phase: 'palpation', type: 'number', mandatory: true, clinicalGuide: 'Measured in both arms; use appropriate cuff size', observation: 'Systolic and diastolic BP', measurement: true, unit: 'mmHg', interpretation: 'Compare with age-specific norms (vitalsEngine); discrepancy suggests coarctation/subclavian stenosis' },
  // ── AUSCULTATION ────────────────────────────────────────────────────────
  { id: 'cvs_ausc_heart_sounds', label: 'Heart sounds — S1, S2', shortLabel: 'S1, S2', phase: 'auscultation', type: 'select', options: ['normal', 'reduced', 'accentuated', 'wide_split', 'fixed_split', 'paradoxical_split', 'single_s2'], mandatory: true, clinicalGuide: 'Use diaphragm at apex (S1) and base (S2); note intensity and splitting', observation: 'Intensity and splitting of first and second heart sounds', description: 'Describe S1 intensity, S2 intensity, and S2 splitting', interpretation: 'Loud S1 = MS; soft S1 = MR/AI; loud S2 = pulm HTN; wide split = RBBB; fixed = ASD; paradoxical = LBBB/AS' },
  { id: 'cvs_ausc_murmurs', label: 'Murmurs', shortLabel: 'Murmurs', phase: 'auscultation', type: 'multiselect', options: ['absent', 'systolic', 'diastolic', 'continuous', 'sisystolic', 'presystolic'], mandatory: true, clinicalGuide: 'Listen over all valve areas with diaphragm and bell; use patient positions', observation: 'Audible turbulent blood flow', description: 'Grade 1-6, timing, location, radiation, character, pitch', interpretation: 'Requires full murmur characterization', activatesFields: ['cvs_ausc_murmur_details', 'cvs_ausc_murmur_grade'] },
  { id: 'cvs_ausc_murmur_details', label: 'Murmur — location & radiation', shortLabel: 'Murmur site', phase: 'auscultation', type: 'select', options: ['aortic_area', 'pulmonic_area', 'tricuspid_area', 'mitral_area', 'left_sternal_edge', 'apex', 'carotids', 'back', 'axilla'], mandatory: false, clinicalGuide: 'Identify point of maximum intensity and radiation pattern', observation: 'Where the murmur is loudest and where it radiates', description: 'PMI and radiation', interpretation: 'AS radiates to carotids; MR radiates to axilla; AR radiates to left sternal edge', isAbnormalOnly: true },
  { id: 'cvs_ausc_murmur_grade', label: 'Murmur — grade', shortLabel: 'Grade', phase: 'auscultation', type: 'select', options: ['grade_1', 'grade_2', 'grade_3', 'grade_4', 'grade_5', 'grade_6'], mandatory: false, clinicalGuide: 'Grade 1 = barely audible; 2 = faint; 3 = moderately loud; 4 = loud with thrill; 5 = heard with stethoscope edge; 6 = heard without stethoscope', observation: 'Loudness of the murmur on Levine scale', measurement: true, unit: '/6', interpretation: 'Higher grades = more turbulent flow; thrill = ≥4/6', isAbnormalOnly: true },
  { id: 'cvs_ausc_systolic_murmur', label: 'Systolic murmur — character', shortLabel: 'Systolic char', phase: 'auscultation', type: 'select', options: ['pansystolic', 'mid_systolic_ejection', 'late_systolic', 'early_systolic'], mandatory: false, clinicalGuide: 'Pansystolic = MR/VSD; mid-systolic = AS/PS', observation: 'Timing and shape within systole', description: 'Pan-, mid-ejection, or late systolic', interpretation: 'Pansystolic = holosystolic MR/VSD; mid-ejection = AS/PS; late = MVP', isAbnormalOnly: true },
  { id: 'cvs_ausc_diastolic_murmur', label: 'Diastolic murmur — character', shortLabel: 'Diastolic char', phase: 'auscultation', type: 'select', options: ['early_diastolic_decrescendo', 'mid_diastolic', 'presystolic'], mandatory: false, clinicalGuide: 'Early = AR/PR; mid = MS/TS; presystolic = MS', observation: 'Timing within diastole', description: 'Early-, mid-, or pre-systolic', interpretation: 'Early decrescendo = AR; mid diastolic = MS', isAbnormalOnly: true },
  { id: 'cvs_ausc_additional_sounds', label: 'Additional sounds', shortLabel: 'Added sounds', phase: 'auscultation', type: 'multiselect', options: ['s3_gallop', 's4_gallop', 'ejection_click', 'opening_snap', 'pericardial_rub', 'prosthetic_valve_click', 'none'], mandatory: false, clinicalGuide: 'Listen for S3 (ventricular gallop), S4 (atrial gallop), clicks, snaps, and rubs', observation: 'Extra sounds beyond S1 and S2', description: 'Identify the sound and its timing', interpretation: 'S3 = LV failure/volume overload; S4 = stiff LV/HTN/AS; opening snap = MS; click = MVP/AS/PS; rub = pericarditis', isAbnormalOnly: true },
  { id: 'cvs_ausc_bruits', label: 'Bruits (carotid/abdominal/femoral)', shortLabel: 'Bruits', phase: 'auscultation', type: 'multiselect', options: ['absent', 'carotid_left', 'carotid_right', 'abdominal_aortic', 'renal', 'femoral_left', 'femoral_right'], mandatory: false, clinicalGuide: 'Listen over carotid arteries, abdominal aorta, and femoral arteries', observation: 'Audible bruit indicating stenosis', description: 'Location and character of bruit', interpretation: 'Carotid bruit = ICA stenosis; abdominal = AAA/renovascular; femoral = PAD', isAbnormalOnly: true },
  // ── SPECIAL TESTS ──────────────────────────────────────────────────────
  { id: 'cvs_spec_ecg', label: 'ECG (12-lead)', shortLabel: 'ECG', phase: 'special_tests', type: 'select', options: ['normal', 'sinus_tachycardia', 'sinus_bradycardia', 'afib', 'aflutter', 'lvh', 'rvh', 'st_depression', 'st_elevation', 't_inversion', 'pathological_q', 'bbb_left', 'bbb_right', 'other'], mandatory: false, clinicalGuide: 'Standard 12-lead ECG; rate, rhythm, axis, intervals, ischaemia, hypertrophy', observation: '12-lead ECG findings', measurement: true, unit: '', interpretation: 'Essential baseline for all cardiac presentations' },
  { id: 'cvs_spec_postural_bp', label: 'Postural blood pressure', shortLabel: 'Postural BP', phase: 'special_tests', type: 'number', mandatory: false, clinicalGuide: 'Measure lying, then after 1 and 3 minutes standing', observation: 'BP change from lying to standing', measurement: true, unit: 'mmHg drop', interpretation: 'Drop ≥20 systolic or ≥10 diastolic = postural hypotension; suggests dehydration, neuropathy, bleeding' },
  { id: 'cvs_spec_ankle_brachial', label: 'Ankle-Brachial Pressure Index', shortLabel: 'ABPI', phase: 'special_tests', type: 'number', mandatory: false, clinicalGuide: 'Measure ankle and brachial systolic pressures with Doppler; ABPI = ankle/brachial', observation: 'ABPI ratio', measurement: true, unit: '', interpretation: '>1.4 = non-compressible (calcified); 1.0-1.4 = normal; 0.5-0.9 = claudication; <0.5 = critical ischaemia' },
];

export const CVS_INSPECTION = CARDIOVASCULAR_FIELDS.filter(f => f.phase === 'inspection');
export const CVS_PALPATION = CARDIOVASCULAR_FIELDS.filter(f => f.phase === 'palpation');
export const CVS_AUSCULTATION = CARDIOVASCULAR_FIELDS.filter(f => f.phase === 'auscultation');
export const CVS_SPECIAL_TESTS = CARDIOVASCULAR_FIELDS.filter(f => f.phase === 'special_tests');
