import type { SystemExamFieldDef } from '../systemExaminationTypes';

export const GASTROINTESTINAL_FIELDS: readonly SystemExamFieldDef[] = [
  // ── INSPECTION ─────────────────────────────────────────────────────────
  { id: 'gi_insp_hands', label: 'Hands (GI stigmata)', shortLabel: 'GI hands', phase: 'inspection', type: 'multiselect', options: ['normal', 'clubbing', 'leuconychia', 'koilonychia', 'palmar_erythema', 'dupuy_tracture'], mandatory: true, clinicalGuide: 'Inspect for liver disease stigmata: clubbing, leuconychia, palmar erythema, Dupuytren', observation: 'Peripheral stigmata of gastrointestinal and liver disease', description: 'Document nail changes, palmar changes', interpretation: 'Clubbing = IBD/cirrhosis/coeliac; leuconychia = chronic liver disease; palmar erythema = cirrhosis' },
  { id: 'gi_insp_face', label: 'Face/oral cavity', shortLabel: 'GI face', phase: 'inspection', type: 'multiselect', options: ['normal', 'angular_stomatitis', 'glossitis', 'oral_ulcers', 'foetor_hepaticus'], mandatory: false, clinicalGuide: 'Inspect oral mucosa, tongue, teeth, and breath', observation: 'Oral and facial signs of GI disease', description: 'Document lesions, ulceration, and breath odour', interpretation: 'Angular stomatitis/glossitis = B12/iron deficiency; foetor hepaticus = liver failure' },
  { id: 'gi_insp_abdomen', label: 'Abdominal contour', shortLabel: 'Contour', phase: 'inspection', type: 'select', options: ['flat', 'scaphoid', 'distended', 'symmetrical', 'asymmetrical'], mandatory: true, clinicalGuide: 'Observe from foot of bed; note contour and symmetry', observation: 'Shape and symmetry of the abdomen', description: 'Flat, scaphoid, distended; note if distension is generalized or localized', interpretation: 'Scaphoid = malnutrition; distended = ascites/obstruction/mass; asymmetry = organomegaly/tumour' },
  { id: 'gi_insp_umbilicus', label: 'Umbilicus', shortLabel: 'Umbilicus', phase: 'inspection', type: 'select', options: ['normal', 'everted', 'hernia', 'cullen_sign'], mandatory: true, clinicalGuide: 'Inspect umbilicus for eversion (ascites), herniation, or discolouration', observation: 'Umbilical position, contour, and colour', description: 'Describe any abnormalities', interpretation: 'Everted = ascites; Cullen sign (periumbilical bruising) = haemorrhagic pancreatitis' },
  { id: 'gi_insp_hernia', label: 'Abdominal wall hernia', shortLabel: 'Hernia', phase: 'inspection', type: 'select', options: ['none', 'umbilical', 'epigastric', 'incisional', 'spigelian'], mandatory: false, clinicalGuide: 'Ask patient to lift head (increase intra-abdominal pressure) to reveal hernia', observation: 'Visible or reducible abdominal wall hernia', description: 'Location and reducibility', interpretation: 'May cause complications if strangulated', isAbnormalOnly: true },
  { id: 'gi_insp_skin', label: 'Abdominal skin changes', shortLabel: 'Skin changes', phase: 'inspection', type: 'multiselect', options: ['normal', 'striae', 'collateral_vessels', 'caput_medusae', 'scar_abdomen', 'rash'], mandatory: false, clinicalGuide: 'Inspect for striae (Cushing/cirrhosis), caput medusae (portal HTN), scars', observation: 'Skin changes on the abdominal wall', description: 'Describe any skin findings', interpretation: 'Caput medusae = portal HTN; striae = ascites/Cushing; upper abdominal scars = GI surgery', isAbnormalOnly: true },
  { id: 'gi_insp_inguinal', label: 'Inguinal/groin inspection', shortLabel: 'Groin', phase: 'inspection', type: 'select', options: ['normal', 'inguinal_hernia', 'femoral_hernia', 'enlarged_nodes', 'scrotal_swelling'], mandatory: false, clinicalGuide: 'Inspect groin for hernia, lymphadenopathy, or scrotal involvement', observation: 'Inguinal region for hernia or adenopathy', description: 'Document side and characteristics', interpretation: 'Inguinal = indirect (young) vs direct (old); femoral = below inguinal ligament, high risk of strangulation' },
  // ── PALPATION ──────────────────────────────────────────────────────────
  { id: 'gi_palp_superficial', label: 'Superficial palpation', shortLabel: 'Superficial', phase: 'palpation', type: 'select', options: ['soft', 'guarding', 'rigidity', 'tenderness', 'distended'], mandatory: true, clinicalGuide: 'Start away from pain; use flat hand, gentle pressure; note tenderness, guarding, rigidity', observation: 'Abdominal wall tension and tenderness on light palpation', description: 'Document any tenderness, guarding, or rigidity with location', interpretation: 'Guarding = peritoneal irritation; rigidity = peritonitis; generalized tenderness = perforation' },
  { id: 'gi_palp_deep', label: 'Deep palpation', shortLabel: 'Deep', phase: 'palpation', type: 'select', options: ['benign', 'palpable_mass', 'rebound_tenderness', 'aortic_pulsation'], mandatory: true, clinicalGuide: 'Deep palpation in all 9 quadrants; note masses, tenderness, aortic width', observation: 'Deep abdominal contents and tenderness', description: 'Document any masses (location, size, consistency) and deep tenderness', interpretation: 'Mass = tumour/abscess/organomegaly; rebound = peritonitis', activatesFields: ['gi_palp_mass_details'] },
  { id: 'gi_palp_mass_details', label: 'Palpable mass — details', shortLabel: 'Mass details', phase: 'palpation', type: 'text', mandatory: false, clinicalGuide: 'Describe: location (quadrant), size (cm), consistency (hard/soft/cystic), mobility, tenderness', observation: 'Characteristics of a palpable abdominal mass', description: 'Size, consistency, mobility, tenderness, surface, edge', interpretation: 'Helps distinguish organomegaly from tumour, abscess, or cyst', isAbnormalOnly: true },
  { id: 'gi_palp_liver', label: 'Liver palpation', shortLabel: 'Liver', phase: 'palpation', type: 'select', options: ['not_palpable', 'palpable', 'enlarged', 'pulsatile', 'tender'], mandatory: true, clinicalGuide: 'Start in RLQ, move upwards with inspiration; assess span, consistency', observation: 'Palpable liver below costal margin', description: 'Size below costal margin (cm), consistency (firm/hard/nodular), tenderness', measurement: true, unit: 'cm below costal margin', interpretation: 'Enlarged (hepatomegaly) = cirrhosis/CHF/hepatitis/tumour; pulsatile = TR; nodular = cirrhosis/metastases' },
  { id: 'gi_palp_spleen', label: 'Spleen palpation', shortLabel: 'Spleen', phase: 'palpation', type: 'select', options: ['not_palpable', 'palpable', 'massive_splenomegaly'], mandatory: true, clinicalGuide: 'Start in RLQ; move left hand to support LUQ; right hand palpates with inspiration', observation: 'Palpable spleen below costal margin', description: 'Size (cm below costal margin); note if spleen tip is felt', measurement: true, unit: 'cm below costal margin', interpretation: 'Splenomegaly = portal HTN/leukaemia/lymphoma/EBV/MAI; massive = myelofibrosis/CML/malaria' },
  { id: 'gi_palp_kidneys', label: 'Kidney palpation', shortLabel: 'Kidneys', phase: 'palpation', type: 'select', options: ['not_palpable', 'palpable_left', 'palpable_right', 'bimanually_palpable'], mandatory: false, clinicalGuide: 'Bimanual palpation; ballot the kidney from behind while palpating anteriorly', observation: 'Palpable ballotable kidney', description: 'Side and size', interpretation: 'Enlarged kidney = PKD/hydronephrosis/tumour; ballotable = large renal mass' },
  { id: 'gi_palp_ascites', label: 'Ascites (shifting dullness / fluid thrill)', shortLabel: 'Ascites', phase: 'palpation', type: 'select', options: ['absent', 'shifting_dullness', 'fluid_thrill'], mandatory: true, clinicalGuide: 'Percuss from midline to flanks for dullness; shift patient for shifting dullness; fluid thrill test', observation: 'Signs of intra-abdominal fluid', description: 'Shifting dullness (present/absent) and/or fluid thrill (present/absent)', interpretation: 'Shifting dullness = moderate ascites (≥1.5L); fluid thrill = tense ascites' },
  { id: 'gi_palp_aorta', label: 'Abdominal aorta', shortLabel: 'Aorta', phase: 'palpation', type: 'select', options: ['normal', 'wide_>3cm', 'tender', 'pulsatile_mass'], mandatory: false, clinicalGuide: 'Palpate for aortic width (normal ~2.5cm) in epigastrium; >3cm = AAA', observation: 'Width and tenderness of the abdominal aorta', description: 'Estimated width in cm', measurement: true, unit: 'cm', interpretation: '>3 cm suggests AAA; tender/pulsatile = symptomatic AAA requiring urgent imaging', isAbnormalOnly: true },
  // ── PERCUSSION ─────────────────────────────────────────────────────────
  { id: 'gi_perc_liver_span', label: 'Liver span (percussion)', shortLabel: 'Liver span', phase: 'percussion', type: 'number', mandatory: true, clinicalGuide: 'Percuss from lung resonance to liver dullness (upper), then to tympany (lower)', observation: 'Vertical span of liver dullness in MCL', measurement: true, unit: 'cm', interpretation: 'Normal 6-12 cm in MCL; reduced = cirrhosis; increased = congestion/hepatitis/tumour' },
  { id: 'gi_perc_spleen', label: 'Spleen percussion (Traube space)', shortLabel: 'Spleen perc.', phase: 'percussion', type: 'select', options: ['resonant', 'dull'], mandatory: false, clinicalGuide: 'Percuss Traube space (6th-9th ribs, anterior axillary line); dullness suggests splenomegaly', observation: 'Percussion note over Traube space', description: 'Resonant (normal) or dull (splenomegaly)', interpretation: 'Dullness in Traube space = splenomegaly >92% sensitive' },
  { id: 'gi_perc_ascites', label: 'Shifting dullness (percussion)', shortLabel: 'Shift dull.', phase: 'percussion', type: 'select', options: ['absent', 'present'], mandatory: true, clinicalGuide: 'Percuss from midline to flank in supine; turn patient to lateral and percuss again', observation: 'Change in percussion note with position change', description: 'Dull flank → resonant anterior = shifting dullness', interpretation: 'Present = ≥1.5L ascitic fluid' },
  // ── AUSCULTATION ───────────────────────────────────────────────────────
  { id: 'gi_ausc_bowel_sounds', label: 'Bowel sounds', shortLabel: 'Bowel sounds', phase: 'auscultation', type: 'select', options: ['normal', 'increased', 'reduced', 'absent', 'tinkling', 'rushing'], mandatory: true, clinicalGuide: 'Listen for 30-60s in RLQ before concluding absent; normal = 5-35/min', observation: 'Audible bowel peristalsis', description: 'Characterize frequency and character', measurement: true, unit: '/min', interpretation: 'Absent = ileus/peritonitis; increased/tinkling = early obstruction; high-pitched = mechanical obstruction' },
  { id: 'gi_ausc_bruits', label: 'Abdominal bruits', shortLabel: 'Bruits', phase: 'auscultation', type: 'multiselect', options: ['absent', 'aortic', 'renal_left', 'renal_right', 'iliac'], mandatory: false, clinicalGuide: 'Listen over aorta, renal arteries, and iliac arteries for bruits', observation: 'Bruits over abdominal vessels', description: 'Location of bruit', interpretation: 'Renal bruit = RAS/hypertension; aortic = AAA/stenosis', isAbnormalOnly: true },
  { id: 'gi_ausc_venous_hum', label: 'Venous hum / Cruveilhier-Baumgarten', shortLabel: 'Venous hum', phase: 'auscultation', type: 'boolean', mandatory: false, clinicalGuide: 'Listen around umbilicus for venous murmur of portal hypertension', observation: 'Continuous venous murmur over periumbilical veins', description: 'Present / Absent', interpretation: 'Indicates portal hypertension with collateral circulation (caput medusae + hum = Cruveilhier-Baumgarten)', isAbnormalOnly: true },
  // ── SPECIAL TESTS ──────────────────────────────────────────────────────
  { id: 'gi_spec_rectal', label: 'Digital rectal examination', shortLabel: 'DRE', phase: 'special_tests', type: 'select', options: ['not_performed', 'normal', 'haemorrhoids', 'prostate_enlarged', 'prostate_nodular', 'rectal_mass', 'faecal_impaction', 'blood_on_stool', 'tenderness'], mandatory: false, clinicalGuide: 'Left lateral position; inspect perianum first; gentle insertion; assess tone, mass, prostate, stool', observation: 'Digital rectal examination findings', description: 'Sphincter tone, prostate (size/nodules), rectal mucosa, stool colour, blood', interpretation: 'Essential for lower GI and prostate assessment; mass = carcinoma; blood = bleeding source' },
  { id: 'gi_spec_hernia_reducibility', label: 'Hernia — reducibility & cough impulse', shortLabel: 'Hernia test', phase: 'special_tests', type: 'select', options: ['reducible', 'irreducible', 'strangulated', 'cough_impulse_present'], mandatory: false, clinicalGuide: 'Attempt reduction; assess for cough impulse; check for tenderness and overlying skin changes', observation: 'Hernia reduction and cough impulse', description: 'Reducible, irreducible, strangulated (red, tender, non-reducible)', interpretation: 'Irreducible + tender + overlying erythema = strangulation — surgical emergency' },
  { id: 'gi_spec_ascitic_tap', label: 'Ascitic tap / paracentesis', shortLabel: 'Paracentesis', phase: 'special_tests', type: 'select', options: ['not_performed', 'clear', 'bloody', 'cloudy', 'chylous'], mandatory: false, clinicalGuide: 'LLQ or midline approach under ultrasound guidance; send for gram stain, culture, cytology', observation: 'Ascitic fluid appearance', description: 'Fluid colour, clarity, cell count, SAAG', interpretation: 'Cloudy = SBP; bloody = haemorrhage/tumour; chylous = lymphatic obstruction' },
  { id: 'gi_spec_faecal_occult', label: 'Faecal occult blood test', shortLabel: 'FOB', phase: 'special_tests', type: 'select', options: ['not_done', 'negative', 'positive'], mandatory: false, clinicalGuide: 'FIT (faecal immunochemical test) preferred over guaiac-based tests', observation: 'Presence of blood in stool', interpretation: 'Positive = GI bleeding; requires endoscopic evaluation' },
];

export const GI_INSPECTION = GASTROINTESTINAL_FIELDS.filter(f => f.phase === 'inspection');
export const GI_PALPATION = GASTROINTESTINAL_FIELDS.filter(f => f.phase === 'palpation');
export const GI_PERCUSSION = GASTROINTESTINAL_FIELDS.filter(f => f.phase === 'percussion');
export const GI_AUSCULTATION = GASTROINTESTINAL_FIELDS.filter(f => f.phase === 'auscultation');
export const GI_SPECIAL_TESTS = GASTROINTESTINAL_FIELDS.filter(f => f.phase === 'special_tests');
