import type { SystemExamFieldDef } from '../systemExaminationTypes';

export const MUSCULOSKELETAL_FIELDS: readonly SystemExamFieldDef[] = [
  // ── INSPECTION ─────────────────────────────────────────────────────────
  { id: 'msk_insp_gait', label: 'Gait and posture', shortLabel: 'Gait/posture', phase: 'inspection', type: 'select', options: ['normal', 'antalgic', 'trendelenburg', 'waddling', 'stiff_leg', 'short_leg', 'flexed_knee'], mandatory: true, clinicalGuide: 'Observe walking, standing, and sitting posture; note any asymmetry or compensation', observation: 'Postural alignment and gait pattern', description: 'Describe gait and postural deviation', interpretation: 'Antalgic = pain avoidance; Trendelenburg = hip abductor weakness; waddling = bilateral hip disease' },
  { id: 'msk_insp_spine', label: 'Spine alignment (anterior/posterior/lateral)', shortLabel: 'Spine', phase: 'inspection', type: 'select', options: ['normal', 'kyphosis', 'lordosis', 'scoliosis_C', 'scoliosis_S', 'flat_back', 'rigid'], mandatory: true, clinicalGuide: 'Observe from behind, front, and side; note natural curves, asymmetry, shoulder/hip height', observation: 'Spinal alignment in coronal and sagittal planes', description: 'Describe curve type, apex, and rigidity (flexible/fixed)', interpretation: 'Scoliosis = rotatory curve; kyphosis = Scheuermann/osteoporosis; rigid = inflammatory (AS)' },
  { id: 'msk_insp_upper_limbs', label: 'Upper limbs — inspection', shortLabel: 'UL inspect', phase: 'inspection', type: 'multiselect', options: ['normal', 'swelling', 'deformity', 'muscle_wasting', 'skin_changes', 'nail_changes'], mandatory: true, clinicalGuide: 'Inspect shoulders, elbows, wrists, hands (MCP/PIP/DIP); note alignment, swelling, deformity', observation: 'Upper limb posture, alignment, and visible pathology', description: 'Describe any swelling, deformity, wasting, or skin/nail changes per joint', interpretation: 'Swan neck/Boutonniere = RA; Heberden/Bouchard = OA; wasting = nerve root/plexus' },
  { id: 'msk_insp_lower_limbs', label: 'Lower limbs — inspection', shortLabel: 'LL inspect', phase: 'inspection', type: 'multiselect', options: ['normal', 'swelling', 'deformity', 'muscle_wasting', 'skin_changes', 'varicose_veins', 'nail_changes'], mandatory: true, clinicalGuide: 'Inspect hips, knees, ankles, feet (MTP/IP); note alignment varus/valgus, swelling', observation: 'Lower limb posture, alignment, and visible pathology', description: 'Describe joint alignment (varus/valgus), swelling distribution, and skin changes', interpretation: 'Genu varum/valgum = OA/trauma; hallux valgus = OA; pes planus = flat foot; swelling = effusion/synovitis' },
  { id: 'msk_insp_skin', label: 'Skin over joints', shortLabel: 'Jt skin', phase: 'inspection', type: 'select', options: ['normal', 'erythema', 'psoriasis', 'calcinosis', 'sclerodactyly', 'rash'], mandatory: false, clinicalGuide: 'Inspect skin overlying affected joints for erythema, scaling, thickening', observation: 'Skin changes over joints suggesting inflammatory arthritis', description: 'Describe distribution and type of skin change', interpretation: 'Psoriasis = psoriatic arthritis; erythema = acute inflammation (gout/septic); sclerodactyly = scleroderma' },
  // ── PALPATION ──────────────────────────────────────────────────────────
  { id: 'msk_palp_tenderness', label: 'Joint line tenderness', shortLabel: 'Joint tenderness', phase: 'palpation', type: 'select', options: ['absent', 'mild', 'moderate', 'severe'], mandatory: true, clinicalGuide: 'Palpate along joint lines; note location of maximal tenderness', observation: 'Pain elicited by palpation over joint lines', description: 'Which joints and which aspect', interpretation: 'Localized tenderness = local pathology (meniscus, ligament, synovitis)' },
  { id: 'msk_palp_effusion', label: 'Joint effusion / swelling', shortLabel: 'Effusion', phase: 'palpation', type: 'select', options: ['absent', 'mild', 'moderate', 'large'], mandatory: false, clinicalGuide: 'Palpate for fluctuance, ballotable patella (knee), bulge sign; note warmth', observation: 'Palpable fluid within joint capsule', description: 'Size and warmth of effusion', interpretation: 'Effusion = inflammation/trauma/sepsis; warm = acute inflammation (gout/septic/RA flare)' },
  { id: 'msk_palp_warmth', label: 'Joint warmth', shortLabel: 'Warmth', phase: 'palpation', type: 'boolean', mandatory: false, clinicalGuide: 'Compare temperature with contralateral joint using dorsum of hand', observation: 'Increased temperature over joint', description: 'Compare with opposite side', interpretation: 'Warm joint = active inflammation (septic arthritis until proven otherwise — emergency)', isAbnormalOnly: true },
  { id: 'msk_palp_crepitus', label: 'Crepitus on movement', shortLabel: 'Crepitus', phase: 'palpation', type: 'select', options: ['absent', 'fine', 'coarse'], mandatory: false, clinicalGuide: 'Palpate joint during active/passive movement; feel for grinding', observation: 'Palpable or audible grating sensation', description: 'Fine (OA) vs coarse (degenerative) crepitus', interpretation: 'Crepitus = degeneration/loose bodies; fine = OA; coarse = advanced OA/meniscal' },
  { id: 'msk_palp_muscle_tenderness', label: 'Muscle tenderness', shortLabel: 'Muscle tend.', phase: 'palpation', type: 'select', options: ['absent', 'fibromyalgia_tender_points', 'myositis'], mandatory: false, clinicalGuide: 'Palpate muscle bellies for tenderness; fibromyalgia = 18 tender points', observation: 'Pain on muscle palpation', description: 'Diffuse vs localized; per specific muscles or tender points', interpretation: 'Fibromyalgia = widespread tender points; myositis = proximal muscle tenderness' },
  // ── SPECIAL TESTS (joint-specific provocative tests) ───────────────────
  // Shoulder
  { id: 'msk_spec_shoulder_rom', label: 'Shoulder range of motion', shortLabel: 'Shoulder ROM', phase: 'special_tests', type: 'select', options: ['full', 'limited_abduction', 'limited_ER', 'limited_IR', 'frozen_shoulder', 'painful_arc'], mandatory: false, clinicalGuide: 'Test active then passive: abduction (0-180), forward flexion (0-180), ER (0-90), IR (reach behind back)', observation: 'Active and passive shoulder range of motion', measurement: true, unit: 'degrees', interpretation: 'Painful arc (60-120°) = subacromial pathology; frozen = adhesive capsulitis; limited ER = frozen shoulder' },
  { id: 'msk_spec_shoulder_impingement', label: 'Shoulder impingement tests', shortLabel: 'Impingement', phase: 'special_tests', type: 'multiselect', options: ['negative', 'neer', 'hawkins_kennedy', 'empty_can', 'drop_arm'], mandatory: false, clinicalGuide: 'Neer = passive forward flexion; Hawkins = flex elbow 90° + internal rotation; Empty can = resisted supraspinatus', observation: 'Pain reproduction with impingement manoeuvres', description: 'Which test(s) positive', interpretation: 'Neer/Hawkins = subacromial impingement; empty can positive = supraspinatus tear; drop arm = full-thickness tear' },
  // Knee
  { id: 'msk_spec_knee_rom', label: 'Knee range of motion', shortLabel: 'Knee ROM', phase: 'special_tests', type: 'select', options: ['full', 'limited_extension', 'limited_flexion', 'locked'], mandatory: false, clinicalGuide: 'Measure with goniometer; normal 0° extension to 135° flexion', observation: 'Active and passive knee ROM', measurement: true, unit: 'degrees', interpretation: 'Limited ext = meniscal tear/effusion/arthritis; locked = bucket-handle meniscal tear; limited flex = OA' },
  { id: 'msk_spec_knee_ligaments', label: 'Knee ligament tests', shortLabel: 'Ligaments', phase: 'special_tests', type: 'multiselect', options: ['stable', 'acl_lachman', 'acl_ad_drawer', 'pcl_pd_drawer', 'mcl_valgus', 'lcl_varus', 'combined_instability'], mandatory: false, clinicalGuide: 'Lachman = 30° flexion, stabilize femur, pull tibia; Anterior drawer = 90°; Posterior drawer = 90°; Collateral = varus/valgus stress at 30°', observation: 'Knee stability on stress testing', description: 'Grade 1 (0-5mm), 2 (5-10mm), 3 (>10mm) laxity', interpretation: 'Lachman + = ACL tear; posterior sag + drawer = PCL tear; valgus/varus = MCL/LCL injury' },
  { id: 'msk_spec_knee_meniscus', label: 'Meniscal tests', shortLabel: 'Meniscus', phase: 'special_tests', type: 'multiselect', options: ['negative', 'mcmurray', 'thessaly', 'ayer_compression'], mandatory: false, clinicalGuide: 'McMurray = flex knee + rotation + extension; Thessaly = weight-bearing rotation at 5° and 20°', observation: 'Meniscal provocation tests', description: 'Which test reproduced pain/click', interpretation: 'Positive McMurray = meniscal tear; medial rotation = lateral meniscus, lateral rotation = medial meniscus' },
  // Hip
  { id: 'msk_spec_hip_rom', label: 'Hip range of motion', shortLabel: 'Hip ROM', phase: 'special_tests', type: 'select', options: ['full', 'limited_flexion', 'limited_IR', 'limited_ER', 'limited_abduction', 'painful'], mandatory: false, clinicalGuide: 'Flexion (0-120), IR (0-45 in flexed), ER (0-45 in flexed), abduction (0-45), adduction (0-30)', observation: 'Active and passive hip ROM', measurement: true, unit: 'degrees', interpretation: 'Limited IR + flexion = OA (earliest sign); limited ER = irritable hip; painful all directions = septic/AVN' },
  { id: 'msk_spec_hip_provocative', label: 'Hip provocative tests', shortLabel: 'Hip prov.', phase: 'special_tests', type: 'multiselect', options: ['negative', 'fabere_patrick', 'scour_test', 'log_roll', 'trendelenburg'], mandatory: false, clinicalGuide: 'FABERE (Flexion ABduction External Rotation = Patrick) tests SIJ/hip; scour = flex + adduct + axial load; Trendelenburg = stand on one leg', observation: 'Pain reproduction with specific hip tests', description: 'Which tests positive (pain or instability)', interpretation: 'FABERE pain = hip/SIJ pathology; positive Trendelenburg = abductor weakness/hip instability' },
  // Spine
  { id: 'msk_spec_spine_cervical_rom', label: 'Cervical spine ROM', shortLabel: 'C-spine ROM', phase: 'special_tests', type: 'select', options: ['full', 'limited_flexion', 'limited_extension', 'limited_rotation', 'limited_lateral_bending', 'painful'], mandatory: false, clinicalGuide: 'Flexion (chin to chest), extension, rotation (chin to shoulder), lateral bending (ear to shoulder)', observation: 'Active cervical spine ROM', measurement: true, unit: 'degrees', interpretation: 'Pain/limited = cervical spondylosis/whiplash/myofascial; rotational + pain = facet joint' },
  { id: 'msk_spec_spine_lumbar_rom', label: 'Lumbar spine ROM', shortLabel: 'L-spine ROM', phase: 'special_tests', type: 'select', options: ['full', 'limited_flexion', 'limited_extension', 'limited_lateral_flexion', 'schobers_reduced'], mandatory: false, clinicalGuide: 'Flexion (Schober test: marks 5cm below and 10cm above sacrum, should expand >5cm), extension, lateral', observation: 'Active lumbar spine ROM and Schober test', measurement: true, unit: 'cm (Schober)', interpretation: 'Reduced Schober = axial spondyloarthritis; painful flexion = discogenic/Mech LBP; limited extension = spinal stenosis' },
  { id: 'msk_spec_spine_special', label: 'Spine special tests', shortLabel: 'Spine tests', phase: 'special_tests', type: 'multiselect', options: ['negative', 'sciatic_stretch_test', 'straight_leg_raise', 'crossed_slr', 'femoral_stretch', 'valsalva', 'slump_test'], mandatory: false, clinicalGuide: 'SLR = 30-70° reproduces radicular pain; crossed SLR = high specificity for disc herniation; femoral stretch = L2-4 radiculopathy', observation: 'Nerve root tension signs', description: 'Positive if reproduces radicular pain (not back pain)', interpretation: 'SLR + = L4-S1 root irritation; crossed SLR = high specificity; femoral stretch = L2-4; Valsalva + = raised ICP/mass lesion' },
  // Elbow, Wrist, Hand
  { id: 'msk_spec_elbow_rom', label: 'Elbow range of motion', shortLabel: 'Elbow ROM', phase: 'special_tests', type: 'select', options: ['full', 'limited_extension', 'limited_flexion', 'locked'], mandatory: false, clinicalGuide: 'Extension (0°), flexion (150°), pronation (80°), supination (80°)', observation: 'Elbow ROM including pronation/supination', measurement: true, unit: 'degrees', interpretation: 'Extension block = OA/effusion; flexion block = swelling; loss of pronation/supination = radial head/DRUJ' },
  { id: 'msk_spec_epicondylitis', label: 'Epicondylitis tests', shortLabel: 'Epicondylitis', phase: 'special_tests', type: 'select', options: ['negative', 'cozens_lateral', 'millers_medial'], mandatory: false, clinicalGuide: 'Cozens (resisted wrist extension) = lateral epicondylitis (tennis elbow); Millers (resisted wrist flexion) = medial (golfer\'s elbow)', observation: 'Pain on resisted wrist movement', description: 'Lateral (Cozens) or medial (Millers)', interpretation: 'Cozens + = lateral epicondylitis; Millers + = medial epicondylitis' },
  { id: 'msk_spec_wrist_rom', label: 'Wrist range of motion', shortLabel: 'Wrist ROM', phase: 'special_tests', type: 'select', options: ['full', 'limited_flexion', 'limited_extension', 'limited_radial', 'limited_ulnar'], mandatory: false, clinicalGuide: 'Flexion (0-80°), extension (0-70°), radial (0-20°), ulnar (0-30°) deviation', observation: 'Active wrist ROM', measurement: true, unit: 'degrees', interpretation: 'Limited = OA/RA/fracture malunion/tenosynovitis' },
  { id: 'msk_spec_carpal_tunnel', label: 'Carpal tunnel syndrome tests', shortLabel: 'CT signs', phase: 'special_tests', type: 'multiselect', options: ['negative', 'phalen', 'tinel', 'carpal_compression'], mandatory: false, clinicalGuide: 'Phalen = 60s wrist flexion; Tinel = tap over carpal tunnel; compression = 30s direct pressure', observation: 'Provocative tests for median nerve compression', description: 'Which tests reproduced symptoms (tingling/numbness in median distribution)', interpretation: 'Phalen most sensitive; Tinel most specific; compression = highest PPV' },
  // Ankle and Foot
  { id: 'msk_spec_ankle_rom', label: 'Ankle range of motion', shortLabel: 'Ankle ROM', phase: 'special_tests', type: 'select', options: ['full', 'limited_DF', 'limited_PF', 'painful'], mandatory: false, clinicalGuide: 'Dorsiflexion (0-20°), plantarflexion (0-50°), inversion, eversion', observation: 'Ankle and subtalar ROM', measurement: true, unit: 'degrees', interpretation: 'Limited DF = tight Achilles/missed fracture (Maisonneuve); limited PF = OA/post-traumatic' },
  { id: 'msk_spec_ankle_ligaments', label: 'Ankle ligament tests', shortLabel: 'Ankle lig.', phase: 'special_tests', type: 'multiselect', options: ['stable', 'anterior_drawer', 'talar_tilt'], mandatory: false, clinicalGuide: 'Anterior drawer = stabilize tibia, pull foot forward; talar tilt = invert ankle in slight PF', observation: 'Ankle stability on stress testing', description: 'Grade 1-3 laxity', interpretation: 'Anterior drawer + = ATFL injury; talar tilt + = calcaneofibular ligament' },
];

export const MSK_INSPECTION = MUSCULOSKELETAL_FIELDS.filter(f => f.phase === 'inspection');
export const MSK_PALPATION = MUSCULOSKELETAL_FIELDS.filter(f => f.phase === 'palpation');
export const MSK_SPECIAL_TESTS = MUSCULOSKELETAL_FIELDS.filter(f => f.phase === 'special_tests');
