import type { SystemExamFieldDef } from '../systemExaminationTypes';

export const NEUROLOGICAL_FIELDS: readonly SystemExamFieldDef[] = [
  // ═════════════════════════════════════════════════════════════════════════
  // INSPECTION
  // ═════════════════════════════════════════════════════════════════════════
  { id: 'neuro_insp_gait', label: 'Gait observation', shortLabel: 'Gait', phase: 'inspection', type: 'select', options: ['normal', 'hemiplegic', 'parkinsonian', 'ataxic', 'waddling', 'steppage', 'scissoring', 'antalgic', 'trendelenburg', 'festinating', 'apraxic'], mandatory: true, clinicalGuide: 'Observe patient walking: initiation, stride, arm swing, turns, tandem walk', observation: 'Pattern of ambulation', description: 'Describe gait pattern in detail', interpretation: 'Hemiplegic = stroke; ataxic = cerebellar; steppage = foot drop (peroneal/L5); festinating = Parkinson; waddling = myopathy' },
  { id: 'neuro_insp_posture', label: 'Posture and involuntary movements', shortLabel: 'Posture/move', phase: 'inspection', type: 'multiselect', options: ['normal', 'tremor_rest', 'tremor_action', 'tremor_intention', 'chorea', 'athetosis', 'dystonia', 'myoclonus', 'tic', 'hemiballismus', 'akathisia'], mandatory: true, clinicalGuide: 'Observe at rest, with arms extended, and during movement', observation: 'Body posture and presence of involuntary movements', description: 'Classify movement type, location, aggravating/relieving factors', interpretation: 'Rest tremor = Parkinson; intention tremor = cerebellar; chorea = Huntington/Sydenham; dystonia = basal ganglia' },
  { id: 'neuro_insp_speech', label: 'Speech assessment', shortLabel: 'Speech', phase: 'inspection', type: 'select', options: ['normal', 'dysarthria', 'expressive_aphasia', 'receptive_aphasia', 'global_aphasia', 'hypophonia', 'pressured', 'scanning'], mandatory: true, clinicalGuide: 'Assess fluency, comprehension, repetition, naming, reading, writing', observation: 'Spontaneous speech, articulation, language content', description: 'Characterize speech type and severity', interpretation: 'Dysarthria = motor (brainstem/CN/cerebellum); aphasia = cortical (dominant hemisphere); scanning = cerebellar' },
  { id: 'neuro_insp_face_asymmetry', label: 'Facial symmetry', shortLabel: 'Face sym.', phase: 'inspection', type: 'select', options: ['symmetrical', 'upper_face_weak', 'lower_face_weak', 'bilateral_weak'], mandatory: true, clinicalGuide: 'Observe at rest, with smile, eye closure, and forehead wrinkling', observation: 'Symmetry of facial muscles at rest and on movement', description: 'Identify which divisions of facial nerve are affected', interpretation: 'Upper + lower facial weakness = UMN (spares forehead); only lower = LMN (CN VII lesion)' },
  { id: 'neuro_insp_eyes', label: 'Eye gaze and pupils', shortLabel: 'Eyes/gaze', phase: 'inspection', type: 'select', options: ['normal', 'ptosis', 'strabismus', 'nystagmus', 'dilated_pupil', 'pinpoint', 'anisocoria', 'conjugate_deviation'], mandatory: true, clinicalGuide: 'Observe eye position, gaze, nystagmus, pupillary size and symmetry', observation: 'Eye position, alignment, pupil size, and gaze at rest', description: 'Ptosis, squint, nystagmus direction, pupillary size', interpretation: 'Ptosis + miosis = Horner; dilated fixed = CN III palsy/stroke; nystagmus = cerebellar/vestibular' },
  // ── PALPATION — limited in neuro; mainly tone assessment ───────────────
  { id: 'neuro_palp_muscle_tone', label: 'Muscle tone (upper limbs)', shortLabel: 'Tone (UL)', phase: 'palpation', type: 'select', options: ['normal', 'increased_spastic', 'increased_rigid', 'decreased_hypotonic', 'paratonia', 'clasp_knife', 'cogwheel'], mandatory: true, clinicalGuide: 'Passively move elbow, wrist, shoulder; note resistance; test for cogwheeling at wrist', observation: 'Resistance to passive movement in upper limbs', description: 'Classify tone change and severity', interpretation: 'Spastic = UMN (stroke/MS); rigid = extrapyramidal (Parkinson); hypotonic = LMN/cerebellar' },
  { id: 'neuro_palp_muscle_tone_ll', label: 'Muscle tone (lower limbs)', shortLabel: 'Tone (LL)', phase: 'palpation', type: 'select', options: ['normal', 'increased_spastic', 'decreased_hypotonic', 'clonus'], mandatory: false, clinicalGuide: 'Roll leg on bed; flex/extend knee and ankle; test for clonus at ankle', observation: 'Resistance to passive movement in lower limbs', description: 'Classify tone change; sustained clonus ≥3 beats', interpretation: 'Spastic = UMN; clonus = UMN (≥3 beats = pathological); hypotonic = LMN/cerebellar' },
  // ── SPECIAL TESTS (most of neurological exam is "special tests") ──────
  // Cranial nerves
  { id: 'neuro_spec_cn_olfactory', label: 'CN I — Olfactory', shortLabel: 'CN I', phase: 'special_tests', type: 'select', options: ['normal', 'hyposmia', 'anosmia', 'parosmia'], mandatory: false, clinicalGuide: 'Test each nostril separately with non-irritating odour (coffee, soap)', observation: 'Sense of smell', description: 'Test with familiar odours', interpretation: 'Anosmia = head trauma/meningioma/COVID; bilateral = Parkinson/Alzheimer' },
  { id: 'neuro_spec_cn_visual', label: 'CN II — Visual acuity & fields', shortLabel: 'CN II', phase: 'special_tests', type: 'select', options: ['normal', 'reduced_acuity', 'field_defect_homon', 'field_defect_bito', 'field_defect_mono', 'blindness'], mandatory: true, clinicalGuide: 'Test acuity (Snellen chart), colour (Ishihara), fields (confrontation), fundoscopy', observation: 'Visual acuity, colour vision, and visual fields', description: 'Acuity, field deficit pattern', interpretation: 'Homon = optic tract/radiation; bitemporal = chiasm (pituitary); monocular = optic nerve/sensory' },
  { id: 'neuro_spec_cn_pupils', label: 'CN II/III — Pupillary reflexes', shortLabel: 'Pupils', phase: 'special_tests', type: 'select', options: ['normal', 'afferent_defect', 'efferent_defect', 'fixed_dilated', 'argyll_robertson', 'horners'], mandatory: true, clinicalGuide: 'Test direct/consensual light reflex and accommodation; RAPD (swinging light test)', observation: 'Light reflex, accommodation, relative afferent pupillary defect', description: 'Pupil size, symmetry, reactivity, RAPD', interpretation: 'RAPD = optic nerve lesion; fixed dilated = CN III; Argyll Robertson = neurosyphilis; Horner = sympathetic lesion' },
  { id: 'neuro_spec_cn_eye_movement', label: 'CN III, IV, VI — Extraocular movements', shortLabel: 'EOM', phase: 'special_tests', type: 'select', options: ['normal', 'cn_iii_palsy', 'cn_iv_palsy', 'cn_vi_palsy', 'internuclear_ophthalmoplegia', 'conjugate_gaze_palsy'], mandatory: true, clinicalGuide: 'H-gaze test; observe for limited movement, diplopia, nystagmus', observation: 'Fullness of extraocular movements, diplopia, nystagmus', description: 'Identify which direction is limited and any diplopia', interpretation: 'CN III = down+out; IV = impaired down-gaze (adducted eye); VI = impaired abduction; INO = MLF (MS)' },
  { id: 'neuro_spec_cn_trigeminal', label: 'CN V — Trigeminal', shortLabel: 'CN V', phase: 'special_tests', type: 'select', options: ['normal', 'sensory_loss', 'motor_weakness', 'cornear_reflex_reduced'], mandatory: true, clinicalGuide: 'Test facial sensation (V1/V2/V3) and jaw movement (temporalis/masseter strength)', observation: 'Facial sensation and jaw muscle strength', description: 'Which division(s) affected; corneal reflex', interpretation: 'Sensory loss = trigeminal lesion/MS; motor = pontine lesion; corneal reflex reduced = CN V or VII' },
  { id: 'neuro_spec_cn_facial', label: 'CN VII — Facial', shortLabel: 'CN VII', phase: 'special_tests', type: 'select', options: ['normal', 'upper_motor_neuron', 'lower_motor_neuron'], mandatory: true, clinicalGuide: 'Raise eyebrows, close eyes tightly, puff cheeks, smile, show teeth', observation: 'Facial movement — upper and lower face', description: 'LMN vs UMN differentiation (forehead spared in UMN)', interpretation: 'LMN = Bell palsy/Ramsay Hunt; UMN = stroke/tumour' },
  { id: 'neuro_spec_cn_auditory', label: 'CN VIII — Vestibulocochlear', shortLabel: 'CN VIII', phase: 'special_tests', type: 'select', options: ['normal', 'hearing_loss', 'tinnitus', 'vertigo_nystagmus'], mandatory: false, clinicalGuide: 'Rinne (air > bone = normal; bone > air = conductive) and Weber (lateralizes = sensorineural) tests', observation: 'Hearing and vestibular function', description: 'Rinne and Weber test; note nystagmus/vertigo', interpretation: 'Sensorineural = acoustic neuroma/Menière; conductive = otitis media/otosclerosis' },
  { id: 'neuro_spec_cn_glossopharyngeal', label: 'CN IX/X — Glossopharyngeal & Vagus', shortLabel: 'CN IX/X', phase: 'special_tests', type: 'select', options: ['normal', 'palatal_weakness', 'gag_reflex_absent', 'dysphagia', 'hoarseness'], mandatory: true, clinicalGuide: 'Observe palate elevation ("ahhh"), assess gag reflex, voice quality, swallowing', observation: 'Palatal movement, gag reflex, voice, swallowing', description: 'Palatal elevation, gag reflex (present/reduced/absent)', interpretation: 'CN IX = gag/gustatory; CN X = palatal/voice; bilateral = pseudobulbar palsy; unilateral = medullary lesion' },
  { id: 'neuro_spec_cn_spinal_accessory', label: 'CN XI — Spinal accessory', shortLabel: 'CN XI', phase: 'special_tests', type: 'select', options: ['normal', 'weakness_trapezius', 'weakness_scm'], mandatory: false, clinicalGuide: 'Shrug shoulders against resistance (trapezius); turn head against hand (SCM)', observation: 'Strength of trapezius and SCM', measurement: true, unit: 'MRC grade', interpretation: 'CN XI lesion = shoulder droop, weak head rotation; MRC <4 = pathological' },
  { id: 'neuro_spec_cn_hypoglossal', label: 'CN XII — Hypoglossal', shortLabel: 'CN XII', phase: 'special_tests', type: 'select', options: ['normal', 'deviation', 'fasciculation', 'weakness'], mandatory: false, clinicalGuide: 'Inspect tongue at rest (fasciculations), then protrude (deviation), then test strength (press against cheek)', observation: 'Tongue bulk, fasciculations, protrusion, and strength', description: 'Fasciculations, deviation (tongue points to lesion side)', interpretation: 'UMN = mild weakness; LMN = fasciculations + atrophy, deviates towards lesion side' },
  // Motor system
  { id: 'neuro_spec_motor_bulk', label: 'Muscle bulk (all limbs)', shortLabel: 'Bulk', phase: 'special_tests', type: 'select', options: ['normal', 'wasting', 'hypertrophy', 'pseudohypertrophy'], mandatory: true, clinicalGuide: 'Inspect and palpate deltoid, biceps, triceps, thenar/hypothenar, quads, calf', observation: 'Muscle mass and contour in all limbs', description: 'Identify atrophic muscles and distribution (proximal/distal/asymmetrical)', interpretation: 'Distal wasting = neuropathy/MND; proximal = myopathy; fasciculations + wasting = LMN/MND' },
  { id: 'neuro_spec_motor_strength', label: 'MRC power (upper limbs)', shortLabel: 'Power (UL)', phase: 'special_tests', type: 'select', options: ['grade_5', 'grade_4minus', 'grade_4', 'grade_4plus', 'grade_3', 'grade_2', 'grade_1', 'grade_0'], mandatory: true, clinicalGuide: 'MRC scale 0-5; test shoulder abductors, elbow flex/ext, wrist ext, finger abd, thumb abd', observation: 'Muscle strength in upper limbs (MRC scale)', measurement: true, unit: 'MRC grade', interpretation: '<5/5 = weakness; pattern helps localize (proximal = myopathy; distal = neuropathy; hemiparesis = UMN)' },
  { id: 'neuro_spec_motor_strength_ll', label: 'MRC power (lower limbs)', shortLabel: 'Power (LL)', phase: 'special_tests', type: 'select', options: ['grade_5', 'grade_4minus', 'grade_4', 'grade_4plus', 'grade_3', 'grade_2', 'grade_1', 'grade_0'], mandatory: true, clinicalGuide: 'MRC scale; hip flex, knee ext/flex, ankle DF/PF, great toe ext', observation: 'Muscle strength in lower limbs (MRC scale)', measurement: true, unit: 'MRC grade', interpretation: 'Pattern of weakness helps localize lesion; unilateral = UMN/LMN; bilateral = myelopathy/neuropathy' },
  // Reflexes
  { id: 'neuro_spec_reflexes_ul', label: 'Upper limb reflexes', shortLabel: 'Reflexes (UL)', phase: 'special_tests', type: 'multiselect', options: ['normal', 'hyperreflexia', 'hyporeflexia', 'absent', 'inverted_supinator'], mandatory: true, clinicalGuide: 'Biceps (C5/6), supinator/brachioradialis (C6), triceps (C7); compare sides', observation: 'Deep tendon reflexes in upper limbs', description: 'Grade (0-4+) for biceps, supinator, triceps', measurement: true, unit: 'grade (0-4+)', interpretation: 'Hyperreflexia = UMN; hyporeflexia/absent = LMN, root lesion; inverted supinator = C5/6 lesion with cord compression' },
  { id: 'neuro_spec_reflexes_ll', label: 'Lower limb reflexes', shortLabel: 'Reflexes (LL)', phase: 'special_tests', type: 'multiselect', options: ['normal', 'hyperreflexia', 'hyporeflexia', 'absent', 'sustained_clonus'], mandatory: true, clinicalGuide: 'Knee jerk (L3/4), ankle jerk (S1); test for patellar/ankle clonus', observation: 'Deep tendon reflexes in lower limbs', description: 'Grade (0-4+) for patellar, Achilles', measurement: true, unit: 'grade (0-4+)', interpretation: 'Hyperreflexia + clonus = UMN; hyporeflexia = LMN; absent ankle jerk = S1 radiculopathy/neuropathy' },
  { id: 'neuro_spec_reflexes_plantar', label: 'Plantar response (Babinski)', shortLabel: 'Plantar', phase: 'special_tests', type: 'select', options: ['flexor', 'extensor', 'equivocal', 'no_response'], mandatory: true, clinicalGuide: 'Stimulate lateral sole from heel to ball; normal = toe flexion; extensor = UMN sign', observation: 'Toe movement in response to plantar stimulation', description: 'Flexor (normal) or extensor (Babinski present)', interpretation: 'Extensor (Babinski sign) = UMN lesion (corticospinal tract); bilateral in infants = normal' },
  { id: 'neuro_spec_reflexes_primitive', label: 'Primitive reflexes', shortLabel: 'Primitive', phase: 'special_tests', type: 'multiselect', options: ['absent', 'grasp', 'palmomental', 'snout', 'suck'], mandatory: false, clinicalGuide: 'Test grasp (stroke palm), palmomental (stroke thenar eminence), snout (tap upper lip)', observation: 'Elicited primitive reflexes indicating frontal release signs', description: 'Which reflexes are present', interpretation: 'Frontal lobe release signs = dementia, frontal lesion, normal ageing >70' },
  // Sensory
  { id: 'neuro_spec_sensory_light_touch', label: 'Light touch sensation', shortLabel: 'Light touch', phase: 'special_tests', type: 'select', options: ['normal', 'reduced', 'absent', 'hyperaesthesia'], mandatory: true, clinicalGuide: 'Use cotton wool; test in each dermatome; compare side to side', observation: 'Perception of light touch throughout all dermatomes', description: 'Map any dermatomal or peripheral nerve pattern', interpretation: 'Dermatomal loss = root lesion; glove-stocking = polyneuropathy; hemisensory = contralateral thalamus/cortex' },
  { id: 'neuro_spec_sensory_pinprick', label: 'Pinprick (pain) sensation', shortLabel: 'Pinprick', phase: 'special_tests', type: 'select', options: ['normal', 'reduced', 'absent', 'hyperalgesia'], mandatory: true, clinicalGuide: 'Use neurological pin (disposable); test dermatomes; note distribution', observation: 'Pain sensation throughout all dermatomes', description: 'Map sensory loss pattern (dermatomal/nerve/glove-stocking)', interpretation: 'Spinothalamic tract = loss contralateral below lesion; syringomyelia = caped distribution' },
  { id: 'neuro_spec_sensory_vibration', label: 'Vibration sense', shortLabel: 'Vibration', phase: 'special_tests', type: 'select', options: ['normal', 'reduced', 'absent'], mandatory: true, clinicalGuide: 'Use 128Hz tuning fork; test over bony prominences (MCP, wrist, elbow, shoulder, hallux, ankle, knee, ASIS)', observation: 'Perception of vibration at bony prominences', description: 'Level at which vibration is no longer felt (ascending from toes)', interpretation: 'Distal-to-proximal loss = peripheral neuropathy; unilateral loss = dorsal column (posterior cord)' },
  { id: 'neuro_spec_sensory_proprioception', label: 'Joint position sense (proprioception)', shortLabel: 'Joint pos.', phase: 'special_tests', type: 'select', options: ['normal', 'reduced', 'absent'], mandatory: true, clinicalGuide: 'Hold distal phalanx laterally; ask patient (eyes closed) direction of movement', observation: 'Perception of passive joint movement direction', description: 'Level at which proprioception is impaired (ascending from great toe)', interpretation: 'Dorsal column loss = tabes/MS/B12 deficiency; impaired = dorsal root ganglionopathy' },
  { id: 'neuro_spec_sensory_temperature', label: 'Temperature sensation', shortLabel: 'Temp sense', phase: 'special_tests', type: 'select', options: ['normal', 'reduced', 'absent'], mandatory: false, clinicalGuide: 'Use tuning fork with cold water or metal handle; test in suspected deficit area', observation: 'Ability to distinguish warm vs cold', description: 'Map area of impairment', interpretation: 'Spinothalamic tract (lateral); usually affected with pain sensation' },
  // Coordination
  { id: 'neuro_spec_coordination_fnf', label: 'Finger-nose-finger test', shortLabel: 'FNF', phase: 'special_tests', type: 'select', options: ['normal', 'dysmetria', 'intention_tremor', 'past_pointing'], mandatory: false, clinicalGuide: 'Patient touches examiner\'s finger then own nose repeatedly; assess accuracy', observation: 'Accuracy and smoothness of finger-to-nose movement', description: 'Dysmetria (overshoot), intention tremor (worsens near target)', interpretation: 'Cerebellar hemisphere lesion = ipsilateral dysmetria/tremor; worse with eyes closed = proprioceptive loss' },
  { id: 'neuro_spec_coordination_hss', label: 'Heel-shin-slide test', shortLabel: 'Heel-shin', phase: 'special_tests', type: 'select', options: ['normal', 'ataxic', 'decomposition'], mandatory: false, clinicalGuide: 'Patient slides heal down opposite shin from knee to ankle', observation: 'Smoothness of heel-to-shin movement', description: 'Ataxic, decomposed, or normal', interpretation: 'Cerebellar vermis/hemisphere = ipsilateral ataxia; inaccurate = proprioceptive problem' },
  { id: 'neuro_spec_coordination_rapid_alt', label: 'Rapid alternating movements', shortLabel: 'RAM', phase: 'special_tests', type: 'select', options: ['normal', 'dysdiadochokinesia', 'slow'], mandatory: false, clinicalGuide: 'Pronate-supinate hands rapidly; tap foot rapidly; pat-pat test', observation: 'Speed and rhythm of alternating movements', description: 'Dysdiadochokinesia = irregular/abnormal rhythm', interpretation: 'Dysdiadochokinesia = cerebellar hemisphere lesion; slow = extrapyramidal/pyramidal' },
  { id: 'neuro_spec_coordination_romberg', label: 'Romberg test', shortLabel: 'Romberg', phase: 'special_tests', type: 'select', options: ['normal', 'positive', 'fall_eyes_open'], mandatory: true, clinicalGuide: 'Stand feet together, eyes open first then closed for 30s; observe sway', observation: 'Balance with eyes open and closed', description: 'Positive Romberg = increased sway/falling with eyes closed', interpretation: 'Positive = proprioceptive/vestibular deficit (not cerebellar); falls eyes open = cerebellar' },
  // Meningeal signs
  { id: 'neuro_spec_meningeal', label: 'Meningeal signs', shortLabel: 'Meningeal', phase: 'special_tests', type: 'multiselect', options: ['absent', 'neck_stiffness', 'kernig', 'brudzinski'], mandatory: false, clinicalGuide: 'Neck stiffness = passive neck flexion; Kernig = flex hip then extend knee; Brudzinski = neck flexion → hip/knee flexion', observation: 'Signs of meningeal irritation', description: 'Which signs are present', interpretation: 'Meningitis, subarachnoid haemorrhage, meningism', isAbnormalOnly: true },
  // Autonomic
  { id: 'neuro_spec_autonomic', label: 'Autonomic function screen', shortLabel: 'Autonomic', phase: 'special_tests', type: 'select', options: ['normal', 'impaired_sweating', 'postural_hypotension', 'urinary_retention', 'erectile_dysfunction'], mandatory: false, clinicalGuide: 'Assess BP lying/standing, sweating, bladder function, bowel function, sexual function', observation: 'Autonomic nervous system function', description: 'BP variation, sweating pattern, bladder/bowel/sexual function', interpretation: 'Dysautonomia = MSA/Parkinson/diabetic autonomic neuropathy/spinal cord injury' },
];

export const NEURO_INSPECTION = NEUROLOGICAL_FIELDS.filter(f => f.phase === 'inspection');
export const NEURO_PALPATION = NEUROLOGICAL_FIELDS.filter(f => f.phase === 'palpation');
export const NEURO_SPECIAL_TESTS = NEUROLOGICAL_FIELDS.filter(f => f.phase === 'special_tests');
