import type { SystemExamFieldDef } from '../systemExaminationTypes';

// ═══════════════════════════════════════════════════════════════════════════════
// RENAL / GENITOURINARY SYSTEM
// ═══════════════════════════════════════════════════════════════════════════════

export const RENAL_FIELDS: readonly SystemExamFieldDef[] = [
  { id: 'renal_insp_hands', label: 'Nail changes (renal)', shortLabel: 'Renal nails', phase: 'inspection', type: 'multiselect', options: ['normal', 'half_and_half', 'white_nails'], mandatory: false, clinicalGuide: 'Half-and-half nails = chronic renal failure', observation: 'Nail bed colouration', description: 'Half-and-half (Lindsay nails) = proximal white, distal pink/brown', interpretation: 'Half-and-half nails = uraemia; white nails = hypoalbuminaemia' },
  { id: 'renal_insp_skin', label: 'Skin (renal)', shortLabel: 'Renal skin', phase: 'inspection', type: 'multiselect', options: ['normal', 'pallor', 'pigmentation', 'excoriations', 'uraemic_frost'], mandatory: false, clinicalGuide: 'Uraemic frost = crystallized urea on skin; excoriations = severe pruritus', observation: 'Skin changes associated with renal failure', description: 'Pallor (anaemia), pigmentation, excoriations, frost', interpretation: 'Pallor = anaemia of CKD; excoriations = hyperphosphataemia/pruritus; frost = end-stage uraemia' },
  { id: 'renal_insp_precordium', label: 'AV fistula site inspection', shortLabel: 'AVF', phase: 'inspection', type: 'select', options: ['not_applicable', 'functional', 'thrill_present', 'signs_infection', 'aneurysm', 'stenosis'], mandatory: false, clinicalGuide: 'Inspect forearm for AV fistula; look for infection, aneurysm, stenosis, or loss of thrill', observation: 'AV fistula site on inspection', description: 'Fistula location, patency signs (thrill/bruit), and any complications', interpretation: 'Loss of thrill = thrombosis; erythema/swelling = infection; aneurysmal dilation = outflow stenosis' },
  { id: 'renal_insp_flank', label: 'Flank inspection', shortLabel: 'Flank', phase: 'inspection', type: 'select', options: ['normal', 'fullness', 'cva_tenderness'], mandatory: false, clinicalGuide: 'Inspect flanks for fullness (hydronephrosis/PKD) or visible mass', observation: 'Flank symmetry and contour', description: 'Noticeable flank fullness or bulging', interpretation: 'Fullness = hydronephrosis/PKD/renal tumour; bilateral fullness = PKD' },
  { id: 'renal_insp_oedema', label: 'Oedema (renal)', shortLabel: 'Renal oedema', phase: 'inspection', type: 'select', options: ['absent', 'periorbital', 'ankle', 'sacral', 'anasarca'], mandatory: true, clinicalGuide: 'Periorbital oedema = nephrotic syndrome; sacral = fluid overload', observation: 'Oedema distribution suggesting renal disease', description: 'Periorbital (nephrotic) vs dependent (nephritic/fluid overload)', interpretation: 'Periorbital oedema = nephrotic syndrome; dependent oedema + HTN = nephritic' },
  { id: 'renal_palp_kidneys', label: 'Kidney palpation (renal)', shortLabel: 'Kidneys', phase: 'palpation', type: 'select', options: ['not_palpable', 'palpable_right', 'palpable_left', 'bilateral', 'ballotable', 'tender'], mandatory: true, clinicalGuide: 'Bimanual palpation; ballot each kidney; PKD = bilaterally enlarged, irregular', observation: 'Palpable ballotable kidneys', description: 'Size, consistency, tenderness', interpretation: 'Bilateral enlargement = PKD; unilateral = hydronephrosis/tumour; ballotable = large renal cyst' },
  { id: 'renal_palp_suprapubic', label: 'Suprapubic / bladder', shortLabel: 'Bladder', phase: 'palpation', type: 'select', options: ['normal', 'palpable_bladder', 'tender_bladder', 'ballotable'], mandatory: false, clinicalGuide: 'Percuss and palpate suprapubic area for distended bladder', observation: 'Palpable or percussible bladder above pubis', description: 'Size above pubis (cm) and tenderness', interpretation: 'Palpable after voiding = urinary retention; tender = cystitis' },
  { id: 'renal_spec_genital', label: 'External genitalia', shortLabel: 'Genitalia', phase: 'special_tests', type: 'select', options: ['not_examined', 'normal', 'ulcer', 'discharge', 'swelling', 'phimosis', 'foreskin_abnormalities'], mandatory: false, clinicalGuide: 'Inspect for ulcers, discharge, masses; male: phimosis, paraphimosis, testicular exam', observation: 'External genitalia examination', description: 'Document any abnormalities', interpretation: 'Ulcer = STI/trauma; discharge = urethritis; testicular mass = tumour/epididymitis' },
  { id: 'renal_spec_prostate', label: 'Prostate examination (DRE)', shortLabel: 'Prostate', phase: 'special_tests', type: 'select', options: ['normal', 'enlarged_benign', 'nodular', 'tender', 'stony_hard', 'not_performed'], mandatory: false, clinicalGuide: 'DRE: assess prostate size, consistency, median sulcus, tenderness, nodules', observation: 'Prostate gland on DRE', description: 'Size (1-3+), consistency (firm/hard/nodular), tenderness', interpretation: 'Enlarged smooth = BPH; nodular/hard = carcinoma; tender = prostatitis' },
  { id: 'renal_spec_dipstick', label: 'Urine dipstick', shortLabel: 'Dipstick', phase: 'special_tests', type: 'select', options: ['not_done', 'normal', 'blood', 'protein', 'glucose', 'leucocytes', 'nitrites', 'ketones'], mandatory: false, clinicalGuide: 'Mid-stream urine; dipstick for blood, protein, glucose, leucocytes, nitrites, pH, specific gravity', observation: 'Urine dipstick analysis results', description: 'Document all abnormal dipstick parameters', interpretation: 'Blood = stones/tumour/infection/glomerular; protein = nephrotic/nephritic; nitrites+leucocytes = UTI' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// ENDOCRINE SYSTEM
// ═══════════════════════════════════════════════════════════════════════════════

export const ENDOCRINE_FIELDS: readonly SystemExamFieldDef[] = [
  { id: 'endo_insp_hands', label: 'Hands (endocrine)', shortLabel: 'Endo hands', phase: 'inspection', type: 'multiselect', options: ['normal', 'tremor', 'palmar_erythema', 'acromegaly_enlarged', 'thyroid_acropachy', 'pigmentation_knuckles'], mandatory: true, clinicalGuide: 'Hand tremor = hyperthyroidism; enlarged hands = acromegaly; thyroid acropachy = Graves', observation: 'Hand signs of endocrine disease', description: 'Tremor (fine/coarse), temperature, moisture, size, pigmentation', interpretation: 'Fine tremor + warm moist = hyperthyroid; large spade-like = acromegaly; pigmented knuckles = Addison' },
  { id: 'endo_insp_face', label: 'Face (endocrine)', shortLabel: 'Endo face', phase: 'inspection', type: 'multiselect', options: ['normal', 'moon_face', 'acromegaly_features', 'exophthalmos', 'myxoedema', 'butterfly_rash', 'hirsutism'], mandatory: true, clinicalGuide: 'Moon face = Cushing; exophthalmos = Graves; coarsening = acromegaly; myxoedema = hypothyroid', observation: 'Facial features suggesting endocrine disorder', description: 'Periorbital, facial structure, hair distribution, complexion', interpretation: 'Moon + buffalo hump = Cushing; exophthalmos + lid lag = Graves; coarse features = acromegaly; puffy = hypothyroid' },
  { id: 'endo_insp_neck', label: 'Neck inspection (thyroid)', shortLabel: 'Neck/thyroid', phase: 'inspection', type: 'select', options: ['normal', 'diffuse_goitre', 'nodular_goitre', 'thyroidectomy_scar', 'cervical_lymphadenopathy'], mandatory: true, clinicalGuide: 'Inspect neck from front and side; look for thyroid swelling, scars, visible lymph nodes', observation: 'Visible thyroid gland and neck contour', description: 'Diffuse vs nodular, size, visible on swallowing', interpretation: 'Diffuse = Graves/Hashimoto; nodular = MNG/adenoma; visible only on swallowing = retrosternal' },
  { id: 'endo_palp_thyroid', label: 'Thyroid palpation', shortLabel: 'Palp thyroid', phase: 'palpation', type: 'select', options: ['normal', 'diffuse_enlargement', 'nodule_single', 'multinodular', 'firm_hard', 'tender'], mandatory: true, clinicalGuide: 'Approach from behind; ask patient to swallow; assess size, consistency, nodules, tenderness', observation: 'Thyroid gland on palpation', description: 'Size (grade 1-3), consistency (soft/firm/hard/nodular), tenderness, mobility', interpretation: 'Tender = De Quervain (viral); firm + symmetrical = Hashimoto; hard + fixed = thyroid carcinoma' },
  { id: 'endo_palp_thyroid_ausc', label: 'Thyroid auscultation (bruit)', shortLabel: 'Thyroid bruit', phase: 'palpation', type: 'boolean', mandatory: false, clinicalGuide: 'Listen over thyroid gland with bell of stethoscope for systolic bruit', observation: 'Audible bruit over thyroid', description: 'Present / Absent', interpretation: 'Bruit = hyperthyroidism (Graves) — increased vascularity; suggests active disease' },
  { id: 'endo_palp_skin', label: 'Skin (endocrine)', shortLabel: 'Endo skin', phase: 'palpation', type: 'select', options: ['normal', 'thin_easy_bruise', 'thick_dry', 'acanthosis_nigricans', 'striae', 'vitiligo', 'hyperpigmentation'], mandatory: true, clinicalGuide: 'Thin skin + bruising = Cushing; thick dry = hypothyroid; acanthosis = insulin resistance; hyperpigmentation = Addison', observation: 'Skin texture, thickness, pigmentation, and lesions', description: 'Texture, pigmentation, striae, bruising, acanthosis', interpretation: 'Acanthosis nigricans = T2DM/IR; vitiligo = autoimmune endocrinopathy; hyperpigmentation = Addison/ACTH-dependent' },
  { id: 'endo_spec_acanthosis', label: 'Acanthosis nigricans grading', shortLabel: 'Acanthosis', phase: 'special_tests', type: 'select', options: ['absent', 'mild', 'moderate', 'severe'], mandatory: false, clinicalGuide: 'Velvety hyperpigmented skin in flexures (neck, axillae, groin); grade by extent and texture', observation: 'Velvety hyperpigmented plaques in flexural areas', description: 'Grade (mild = present on neck only; severe = extends beyond flexures)', interpretation: 'Marker of insulin resistance — strongly associated with T2DM, PCOS, metabolic syndrome' },
  { id: 'endo_spec_thyroid_antibodies', label: 'Thyroid autoantibodies (clinical indication)', shortLabel: 'Thyroid Abs', phase: 'special_tests', type: 'select', options: ['not_indicated', 'TPO_positive', 'TG_positive', 'TRAb_positive'], mandatory: false, clinicalGuide: 'TPO = Hashimoto; TRAb = Graves; TG = thyroiditis', observation: 'Clinical indication for antibody testing', description: 'Which antibodies elevated', interpretation: 'TPO+ = autoimmune thyroiditis; TRAb+ = Graves disease' },
  { id: 'endo_spec_neuropathy_screen', label: 'Peripheral neuropathy screen (diabetic)', shortLabel: 'Neuropathy', phase: 'special_tests', type: 'select', options: ['normal', 'reduced_light_touch', 'reduced_monofilament', 'reduced_vibration', 'absent_reflexes'], mandatory: false, clinicalGuide: '10g monofilament at plantar foot (4 sites); vibration 128Hz at hallux; ankle jerks', observation: 'Screening for diabetic peripheral neuropathy', description: 'Monofilament (sites felt), vibration, ankle reflexes, light touch', interpretation: '>1 site insensate = peripheral neuropathy; monofilament loss = high risk of foot ulcer' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// BREAST EXAMINATION
// ═══════════════════════════════════════════════════════════════════════════════

export const BREAST_FIELDS: readonly SystemExamFieldDef[] = [
  { id: 'breast_insp_sitting', label: 'Breast inspection (sitting)', shortLabel: 'Inspect sitting', phase: 'inspection', type: 'select', options: ['normal', 'asymmetry', 'skin_dimpling', 'peau_dorange', 'nipple_retraction', 'nipple_discharge', 'erythema', 'masses_visible'], mandatory: true, clinicalGuide: 'Inspect with arms by side, then arms above head, then hands on hips; look for asymmetry, dimpling, peau d\'orange', observation: 'Breast symmetry, skin, nipple, and contour', description: 'Location of any visible abnormality (quadrant/clock face)', interpretation: 'Peau d\'orange = inflammatory carcinoma; dimpling = suspensory ligament invasion; nipple retraction = ductal carcinoma' },
  { id: 'breast_insp_lying', label: 'Breast inspection (lying)', shortLabel: 'Inspect lying', phase: 'inspection', type: 'select', options: ['normal', 'flattening', 'tethering'], mandatory: false, clinicalGuide: 'Patient lying flat, arms above head; note any flattening or tethering', observation: 'Change in breast contour when lying', description: 'Any flattening or skin tethering', interpretation: 'Flattening = underlying mass; tethering = Cooper ligament invasion' },
  { id: 'breast_palp_breast', label: 'Breast palpation', shortLabel: 'Palp breast', phase: 'palpation', type: 'select', options: ['normal', 'lump', 'modularity', 'thickening', 'tenderness'], mandatory: true, clinicalGuide: 'Systematic palpation of all 4 quadrants + tail of Spence; use flat of fingers in concentric circles', observation: 'Breast tissue on palpation', description: 'Lump: location (quadrant/clock), size (cm), consistency, tenderness, mobility, skin tethering', measurement: true, unit: 'cm', interpretation: 'Hard irregular immobile = carcinoma; smooth mobile tender = fibroadenoma/cyst; bilateral nodular = fibrocystic', activatesFields: ['breast_palp_lump_details'] },
  { id: 'breast_palp_lump_details', label: 'Breast lump — details', shortLabel: 'Lump details', phase: 'palpation', type: 'text', mandatory: false, clinicalGuide: 'Describe: quadrant/clock, size (cm), shape, consistency (hard/cystic/firm), border, mobility, tethering', observation: 'Detailed characterization of a palpable breast lump', description: 'Full lump characterization', interpretation: 'Suspicious features: hard, irregular, fixed, >2cm, skin involvement, node positivity', isAbnormalOnly: true },
  { id: 'breast_palp_axilla', label: 'Axillary lymph nodes', shortLabel: 'Axillary nodes', phase: 'palpation', type: 'select', options: ['not_palpable', 'palpable_benign', 'suspicious', 'fixed'], mandatory: true, clinicalGuide: 'Palpate axillary nodes (central, pectoral, subscapular, lateral) with patient seated, arm relaxed', observation: 'Palpable axillary lymphadenopathy', description: 'Number, size (cm), consistency, mobility', interpretation: 'Firm/fixed >1cm = suspicious for metastasis; tender + mobile = reactive; matted = advanced disease' },
  { id: 'breast_palp_supraclavicular', label: 'Supraclavicular nodes', shortLabel: 'SC nodes', phase: 'palpation', type: 'select', options: ['not_palpable', 'palpable'], mandatory: true, clinicalGuide: 'Palpate supraclavicular fossae from behind', observation: 'Palpable supraclavicular nodes', description: 'Side, size, consistency', interpretation: 'Palpable = advanced disease (N3) — poor prognosis' },
  { id: 'breast_spec_nipple_discharge', label: 'Nipple discharge assessment', shortLabel: 'Nipple disc.', phase: 'special_tests', type: 'select', options: ['none', 'milky', 'bloody', 'serous', 'purulent', 'green'], mandatory: false, clinicalGuide: 'Gentle radial expression; note colour, consistency, spontaneous vs expressible, single/multiple ducts', observation: 'Character of nipple discharge', description: 'Spontaneous or expressible, colour, consistency, single or multiple duct', interpretation: 'Bloody (intraductal papilloma/carcinoma); milky (galactorrhoea); purulent (mastitis)' },
  { id: 'breast_spec_skin_biopsy', label: 'Skin punch biopsy (clinical indication)', shortLabel: 'Biopsy', phase: 'special_tests', type: 'boolean', mandatory: false, clinicalGuide: 'Indicated for suspected Paget disease (eczematous nipple changes), inflammatory carcinoma', observation: 'Skin biopsy for suspected malignant skin changes', description: 'Biopsy site and result', interpretation: 'Paget cells = Paget disease; dermal lymphatic invasion = inflammatory carcinoma' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// ENT EXAMINATION
// ═══════════════════════════════════════════════════════════════════════════════

export const ENT_FIELDS: readonly SystemExamFieldDef[] = [
  { id: 'ent_insp_ear', label: 'Ear inspection (pinna + canal)', shortLabel: 'Ear', phase: 'inspection', type: 'select', options: ['normal', 'deformity', 'discharge', 'erythema', 'postauricular_swelling', 'preauricular_sinus'], mandatory: true, clinicalGuide: 'Inspect pinna, canal opening, and post-auricular area', observation: 'External ear morphology and condition', description: 'Any deformity, discharge, swelling, or sinus', interpretation: 'Discharge = otitis externa/media; postauricular swelling = mastoiditis; preauricular sinus = congenital' },
  { id: 'ent_insp_nose', label: 'Nose inspection', shortLabel: 'Nose', phase: 'inspection', type: 'select', options: ['normal', 'deviation', 'swelling', 'discharge', 'perforation', 'saddle_nose'], mandatory: true, clinicalGuide: 'Inspect external nose and anterior nares with otoscope or speculum', observation: 'External nose and nasal cavity', description: 'Nasal septum, turbinates, discharge character', interpretation: 'Saddle nose = granulomatosis (GPA)/trauma; septal perforation = cocaine/GPA; discharge = sinusitis/CSF leak' },
  { id: 'ent_insp_mouth', label: 'Oral cavity / oropharynx', shortLabel: 'Oral cavity', phase: 'inspection', type: 'select', options: ['normal', 'ulcer', 'leukoplakia', 'erythroplakia', 'tonsillar_enlargement', 'palatal_swelling', 'trismus'], mandatory: true, clinicalGuide: 'Use tongue depressor and light; inspect buccal mucosa, tongue, floor of mouth, palate, tonsils', observation: 'Oral cavity and oropharyngeal structures', description: 'Mucosa, tongue, floor of mouth, palate, tonsils, dentition', interpretation: 'Leuko/erythroplakia = premalignant; non-healing ulcer >3wk = SCC; asymmetric tonsil = lymphoma/tonsillar abscess' },
  { id: 'ent_insp_neck', label: 'Neck inspection (ENT)', shortLabel: 'ENT neck', phase: 'inspection', type: 'select', options: ['normal', 'mass', 'tender', 'sinus_tract', 'surgical_scar'], mandatory: true, clinicalGuide: 'Inspect neck from front and side; note masses, scars, sinuses, or asymmetry', observation: 'Neck contour and any visible pathology', description: 'Site, swelling, overlying skin changes', interpretation: 'Midline = thyroglossal/thyroid; lateral = branchial cyst/LN/SCC; supraclavicular = Virchow (GI/thoracic)' },
  { id: 'ent_palp_neck', label: 'Neck palpation / cervical nodes', shortLabel: 'Cervical nodes', phase: 'palpation', type: 'select', options: ['normal', 'reactive', 'suspicious', 'matted', 'abscess'], mandatory: true, clinicalGuide: 'Systematic palpation of all cervical node levels (IA-VB, VI, VII), thyroid, and salivary glands', observation: 'Cervical lymphadenopathy and neck masses', description: 'Level, size, consistency, mobility, tenderness', interpretation: '>1.5cm fixed non-tender = malignancy; tender + abscess = suppurative; matted = TB/lymphoma' },
  { id: 'ent_spec_hearing', label: 'Hearing assessment (Rinne/Weber)', shortLabel: 'Hearing', phase: 'special_tests', type: 'select', options: ['normal', 'conductive_loss', 'sensorineural_loss', 'mixed_loss'], mandatory: false, clinicalGuide: '512Hz tuning fork: Rinne (air vs bone); Weber (which ear louder)', observation: 'Tuning fork tests for hearing', description: 'Rinne: air>bone (normal) or bone>air (conductive); Weber: lateralizes (SNHL away, CHL towards)', interpretation: 'Conductive = otitis media/otosclerosis/perforation; SNHL = presbycusis/acoustic neuroma/noise' },
  { id: 'ent_spec_whisper', label: 'Whispered voice test', shortLabel: 'Whisper', phase: 'special_tests', type: 'select', options: ['normal', 'reduced', 'unable'], mandatory: false, clinicalGuide: 'Stand at arm\'s length behind patient; whisper a number with full expiration; mask opposite ear', observation: 'Ability to hear whispered speech', description: 'Pass / Fail per ear', interpretation: 'Failed whisper test suggests hearing impairment requiring formal audiometry' },
  { id: 'ent_spec_anterior_rhinoscopy', label: 'Anterior rhinoscopy', shortLabel: 'Rhinoscopy', phase: 'special_tests', type: 'select', options: ['normal', 'deviated_septum', 'inferior_turbinate_hypertrophy', 'polyp', 'blood', 'crusting'], mandatory: false, clinicalGuide: 'Use otoscope with largest speculum or nasal speculum; inspect septum, turbinates, mucosa', observation: 'Nasal cavity under direct inspection', description: 'Septum, turbinates, mucosa, polyps, discharge', interpretation: 'Polyp = CRSwNP/allergic; bleeding = epistaxis/tumour; crusting = atrophic rhinitis/GPA' },
  { id: 'ent_spec_flexible_nasendoscopy', label: 'Flexible nasendoscopy', shortLabel: 'FNE', phase: 'special_tests', type: 'select', options: ['not_performed', 'normal', 'abnormal'], mandatory: false, clinicalGuide: 'Topical anaesthetic + decongestant; pass scope along floor of nose to nasopharynx', observation: 'Nasal cavity, nasopharynx, larynx, and hypopharynx via flexible endoscopy', description: 'Full endoscopic findings from nasal cavity to larynx', interpretation: 'Essential for suspected laryngeal/pharyngeal pathology, obstructive sleep apnoea, globus' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// EYE EXAMINATION
// ═══════════════════════════════════════════════════════════════════════════════

export const EYE_FIELDS: readonly SystemExamFieldDef[] = [
  { id: 'eye_insp_visual_acuity', label: 'Visual acuity', shortLabel: 'VA', phase: 'inspection', type: 'select', options: ['normal', 'reduced_6_9', 'reduced_6_12', 'reduced_6_18', 'reduced_6_36', 'reduced_6_60', 'CF', 'HM', 'PL', 'NPL'], mandatory: true, clinicalGuide: 'Snellen chart at 6m; pinhole corrects refractive error; document best corrected acuity', observation: 'Distance visual acuity', measurement: true, unit: 'Snellen', interpretation: '<6/12 = driving standard; 6/60 = severe impairment; HM/PL/NPL = legal blindness; pinhole improvement = refractive' },
  { id: 'eye_insp_eyelids', label: 'Eyelids / adnexa', shortLabel: 'Eyelids', phase: 'inspection', type: 'select', options: ['normal', 'ptosis', 'ectropion', 'entropion', 'lagophthalmos', 'chalazion', 'stye', 'blepharitis', 'basal_cell_carcinoma'], mandatory: true, clinicalGuide: 'Inspect lid position, closure, margin, lashes, and lesions', observation: 'Eyelid position, movement, and lesions', description: 'Describe any ptosis, lesion, or closure abnormality', interpretation: 'Ptosis = CN III/Horner/myasthenia; ectropion = ageing; BCC = most common lid malignancy; lagophthalmos = CN VII' },
  { id: 'eye_insp_conjunctiva', label: 'Conjunctiva and sclera', shortLabel: 'Conjunctiva', phase: 'inspection', type: 'select', options: ['normal', 'injection', 'chemosis', 'subconjunctival_haem', 'pterygium', 'pinguecula', 'jaundice'], mandatory: true, clinicalGuide: 'Inspect bulbar and palpebral conjunctiva by everting lower lid', observation: 'Conjunctival colour, clarity, and lesions', description: 'Injection (ciliary vs conjunctival), chemosis, haemorrhage, growth', interpretation: 'Ciliary injection = iritis (red eye); conjunctival = conjunctivitis; chemosis = allergy/trauma; pterygium = UV-related' },
  { id: 'eye_insp_cornea', label: 'Cornea', shortLabel: 'Cornea', phase: 'inspection', type: 'select', options: ['normal', 'ulcer', 'opacity', 'arcus_senilis', 'keratic_precipitates', 'band_keratopathy'], mandatory: true, clinicalGuide: 'Use slit lamp or pen torch; inspect clarity, curvature, and surface', observation: 'Corneal clarity, curvature, and surface integrity', description: 'Any opacity, ulcer, arcus, or deposits', interpretation: 'Ulcer = infection (bacterial = emergency); arcus = hyperlipidaemia; KP = uveitis; band = hypercalcaemia/RA' },
  { id: 'eye_insp_pupils', label: 'Pupils and iris', shortLabel: 'Pupils', phase: 'inspection', type: 'select', options: ['normal', 'anisocoria', 'irregular', 'rubeosis_iridis', 'iris_coloboma'], mandatory: true, clinicalGuide: 'Note size, shape, symmetry, and colour of iris', observation: 'Pupil shape, size, and iris morphology', description: 'Diameter (mm), shape (round/irregular), symmetry', interpretation: 'Rubeosis = diabetes/CRVO; coloboma = congenital; irregular = synechiae (previous iritis)' },
  { id: 'eye_insp_lens', label: 'Lens (cataract assessment)', shortLabel: 'Lens', phase: 'inspection', type: 'select', options: ['clear', 'nuclear_sclerosis', 'cortical_opacity', 'posterior_subcapsular', 'mature_cataract', 'pseudophakia'], mandatory: true, clinicalGuide: 'Red reflex test with ophthalmoscope; slit lamp for detailed lens assessment', observation: 'Lens clarity and position', description: 'Type: nuclear, cortical, PSC; grade (1-4); pseudophakia (IOL)', interpretation: 'PSC = steroids/diabetes/trauma (most symptomatic); nuclear = age-related; mature = white lens' },
  { id: 'eye_insp_fundus', label: 'Fundus (optic disc, macula, vessels)', shortLabel: 'Fundus', phase: 'inspection', type: 'select', options: ['normal', 'disc_swelling', 'disc_pallor', 'cupping', 'haemorrhage', 'exudates', 'cotton_wool', 'hypertensive_changes', 'diabetic_retinopathy', 'macular_degeneration'], mandatory: true, clinicalGuide: 'Ophthalmoscopy in dim light; assess disc (margins, colour, cup), vessels (AV ratio, crossing), macula, periphery', observation: 'Retinal examination findings', description: 'Disc margins, colour, cup:disc ratio; vascular changes; macular changes', interpretation: 'Swollen disc = papilloedema/optic neuritis; cupping = glaucoma; haemorrhages + exudates = DR/HTN; cotton wool = ischaemia' },
  { id: 'eye_spec_visual_fields', label: 'Visual fields by confrontation', shortLabel: 'VF', phase: 'special_tests', type: 'select', options: ['normal', 'homon_hemianopia', 'bitemporal', 'quadrantanopia', 'central_scotoma', 'enlarged_blind_spot'], mandatory: false, clinicalGuide: 'Test all 4 quadrants each eye by confrontation; use red pin for central fields', observation: 'Visual field defect pattern on confrontation testing', description: 'Map the field defect (which quadrant, monocular/binocular)', interpretation: 'Homon = optic tract/radiation; bitemporal = chiasm; central scotoma = optic nerve; enlarged blind spot = papilloedema' },
  { id: 'eye_spec_eye_movement', label: 'Extraocular movements / squint', shortLabel: 'EOM', phase: 'special_tests', type: 'select', options: ['full', 'limited_unilateral', 'limited_bilateral', 'nystagmus', 'strabismus', 'diplopia'], mandatory: false, clinicalGuide: 'H-gaze: 9 positions; note full range, limitation, nystagmus, or diplopia', observation: 'Fullness of EOM, any nystagmus, or strabismus', description: 'Direction of limitation, nystagmus type, diplopia direction', interpretation: 'CN VI = lateral rectus; CN IV = superior oblique; CN III = remaining; INO = MS; nystagmus = cerebellar/vestibular' },
  { id: 'eye_spec_tonometry', label: 'Tonometry (intraocular pressure)', shortLabel: 'IOP', phase: 'special_tests', type: 'number', mandatory: false, clinicalGuide: 'Goldmann applanation tonometry (gold standard) or Tonopen/iCare for screening; normal 10-21 mmHg', observation: 'Intraocular pressure', measurement: true, unit: 'mmHg', interpretation: '>21 = ocular hypertension/glaucoma; <6 = hypotony (post-op/uveitis/trauma)' },
  { id: 'eye_spec_slit_lamp', label: 'Slit lamp examination', shortLabel: 'Slit lamp', phase: 'special_tests', type: 'select', options: ['normal', 'anterior_uveitis', 'keratitis', 'corneal_abrasion', 'hyphema', 'hypopyon', 'cataract_details'], mandatory: false, clinicalGuide: 'Slit lamp with fluorescein and cobalt blue filter', observation: 'Anterior segment under slit lamp', description: 'Conjunctiva, cornea, AC (cells/flare), iris, lens details', interpretation: 'Cells + flare = anterior uveitis; fluorescein uptake = corneal abrasion; hyphema = trauma; hypopyon = infection' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// SKIN EXAMINATION
// ═══════════════════════════════════════════════════════════════════════════════

export const SKIN_FIELDS: readonly SystemExamFieldDef[] = [
  { id: 'skin_insp_primary_lesion', label: 'Primary lesion type', shortLabel: 'Primary lesion', phase: 'inspection', type: 'select', options: ['normal', 'macule', 'papule', 'plaque', 'nodule', 'vesicle', 'bulla', 'pustule', 'wheal', 'cyst'], mandatory: true, clinicalGuide: 'Classify the primary lesion: flat ≤1cm (macule), raised ≤1cm (papule), raised >1cm (plaque/nodule), fluid-filled (vesicle/bulla/pustule)', observation: 'Morphology of the primary skin lesion', description: 'Lesion type, size, colour, shape, border, arrangement', measurement: true, unit: 'cm', interpretation: 'Macule/papule = most common; vesicle/bulla = inflammation/separation; pustule = infection/pustular psoriasis' },
  { id: 'skin_insp_distribution', label: 'Lesion distribution', shortLabel: 'Distribution', phase: 'inspection', type: 'multiselect', options: ['localized', 'generalized', 'flexural', 'extensor', 'sun_exposed', 'dermatomal', 'acral', 'intertriginous', 'bilaterally_symmetrical'], mandatory: true, clinicalGuide: 'Note anatomical distribution: flexural = eczema; extensor = psoriasis; dermatomal = HZ; sun-exposed = photodermatitis', observation: 'Distribution and symmetry of the lesions', description: 'Pattern of involvement — flexural, extensor, dermatomal, symmetrical, etc', interpretation: 'Flexural = atopic dermatitis; extensor = psoriasis; dermatomal = HZ; sun-exposed = SLE/photosensitivity' },
  { id: 'skin_insp_secondary_change', label: 'Secondary changes', shortLabel: 'Secondary', phase: 'inspection', type: 'multiselect', options: ['none', 'scale', 'crust', 'erosion', 'ulcer', 'fissure', 'lichenification', 'excoriation', 'scar', 'atrophy'], mandatory: false, clinicalGuide: 'Scale = psoriasis/eczema; crust = dried exudate; lichenification = chronic scratching; erosion = superficial epidermal loss', observation: 'Secondary changes from evolution or scratching', description: 'Scale, crust, erosion, ulcer, fissure, lichenification, excoriation, scar, atrophy', interpretation: 'Lichenification = chronic eczema; scale = psoriasis; crust = impetigo/herpes; fissure = xerosis/eczema' },
  { id: 'skin_insp_nails', label: 'Nail changes', shortLabel: 'Nails', phase: 'inspection', type: 'multiselect', options: ['normal', 'pitting', 'onycholysis', 'subungual_hyperkeratosis', 'oil_drop', 'beau_lines', 'mees_lines', 'splinter_haem', 'paronychia'], mandatory: false, clinicalGuide: 'Pitting and oil drop = psoriasis; onycholysis = psoriasis/trauma; Beau = severe illness; Mees = arsenic/chemotherapy', observation: 'Nail plate and nail bed changes', description: 'Pitting, onycholysis, subungual debris, colour changes', interpretation: 'Pitting + oil drop = nail psoriasis; onycholysis = psoriasis/trauma/hyperthyroid; Beau = acute illness/trauma' },
  { id: 'skin_insp_mucous_membranes', label: 'Mucous membrane involvement', shortLabel: 'Mucosa', phase: 'inspection', type: 'multiselect', options: ['normal', 'oral_ulcers', 'genital_ulcers', 'conjunctival', 'nasal_perforation'], mandatory: false, clinicalGuide: 'Inspect oral, genital, and conjunctival mucosae for ulcers, erosions, or lesions', observation: 'Mucosal involvement of the skin condition', description: 'Site and appearance of mucosal lesions', interpretation: 'Oral + genital ulcers = Behçet/HSV; Lacy white = oral lichen planus; bullae = MMP/SJS/TEN' },
  { id: 'skin_insp_hair', label: 'Hair and scalp', shortLabel: 'Hair/scalp', phase: 'inspection', type: 'select', options: ['normal', 'alopecia_areata', 'scalp_psoriasis', 'scarring_alopecia', 'hirsutism', 'hair_loss_diffuse'], mandatory: false, clinicalGuide: 'Inspect scalp for psoriasis, alopecia areata, or scarring alopecia', observation: 'Hair distribution, density, and scalp condition', description: 'Pattern of hair loss, scalp lesions, hair texture', interpretation: 'Patchy = alopecia areata; diffuse = telogen effluvium/thyroid/iron; scarring = LE/LP; scalp psoriasis = thick scale' },
  { id: 'skin_spec_dermoscopy', label: 'Dermoscopy', shortLabel: 'Dermoscopy', phase: 'special_tests', type: 'select', options: ['not_performed', 'benign', 'suspicious', 'malignant', 'melanocytic', 'non_melanocytic'], mandatory: false, clinicalGuide: '10x magnification with polarized or non-polarized dermoscope; use pattern analysis', observation: 'Dermoscopic features of skin lesion', description: 'Pigment network, dots/globules, streaks, regression structures', interpretation: 'Asymmetry + irregular network + atypical dots = melanoma; arborizing vessels = BCC; starburst = Spitz nevi' },
  { id: 'skin_spec_biopsy', label: 'Skin biopsy (indication)', shortLabel: 'Biopsy', phase: 'special_tests', type: 'select', options: ['not_indicated', 'shave_biopsy', 'punch_biopsy', 'excision_biopsy'], mandatory: false, clinicalGuide: 'Shave = raised superficial; punch = deep dermal process; excision = suspected melanoma', observation: 'Biopsy type indicated for histological diagnosis', description: 'Site, size, technique, and indication', interpretation: 'Gold standard for definitive diagnosis; excisional biopsy for suspicious pigmented lesions' },
  { id: 'skin_spec_wood_lamp', label: 'Wood lamp examination', shortLabel: 'Wood lamp', phase: 'special_tests', type: 'select', options: ['not_performed', 'normal', 'positive_fluorescence'], mandatory: false, clinicalGuide: 'Wood lamp (360nm UV) in dark room; fluorescing lesions = fungal (tinea capitis), erythrasma, vitiligo, P acnes', observation: 'Fluorescence of skin lesions under Wood lamp', description: 'Fluorescence colour and distribution', interpretation: 'Blue-green = tinea capitis; coral-red = erythrasma; bright white = vitiligo; orange = P acnes' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// OBSTETRIC EXAMINATION (antenatal)
// ═══════════════════════════════════════════════════════════════════════════════

export const OBSTETRIC_FIELDS: readonly SystemExamFieldDef[] = [
  { id: 'obs_insp_abdomen', label: 'Abdominal contour (gravid)', shortLabel: 'Preg abdomen', phase: 'inspection', type: 'select', options: ['normal_pregnant', 'excessive_fundal_height', 'small_for_dates', 'polyhydramnios', 'multiple_gestation_suspected'], mandatory: true, clinicalGuide: 'Observe contour and size; note linea nigra, striae gravidarum, and old scars', observation: 'Gravid abdomen shape and size for gestational age', description: 'Fundal height, contour, striae, linea nigra, scars', interpretation: 'Large for dates = polyhydramnios/multiple/macrosomia; small = IUGR/oligohydramnios/dates wrong' },
  { id: 'obs_palp_fundal_height', label: 'Fundal height / symphysis-fundal height', shortLabel: 'SFH', phase: 'palpation', type: 'number', mandatory: true, clinicalGuide: 'SFH in cm = weeks gestation after 20w; measure with tape from pubic symphysis to fundus', observation: 'Symphysis-to-fundus distance', measurement: true, unit: 'cm', interpretation: 'SFH <3cm of gestation = appropriate; >3cm = further assessment (multiple/poly/macrosomia); <3cm = IUGR/oligo' },
  { id: 'obs_palp_lie', label: 'Fetal lie / presentation', shortLabel: 'Lie', phase: 'palpation', type: 'select', options: ['longitudinal', 'transverse', 'oblique', 'unstable'], mandatory: true, clinicalGuide: 'Leopold first manoeuvre: palpate fundus — what is there?', observation: 'Fetal lie defined by relationship of fetal spine to maternal spine', description: 'Longitudinal (cephalic/breech), transverse, oblique, unstable', interpretation: 'Longitudinal = normal; transverse = C-section likely; oblique = unstable' },
  { id: 'obs_palp_pole', label: 'Fetal pole (Leopold I)', shortLabel: 'Pole', phase: 'palpation', type: 'select', options: ['cephalic', 'breech', 'unclear'], mandatory: true, clinicalGuide: 'Leopold I: both hands cupping fundus; breech = soft irregular; head = firm round ballotable', observation: 'What is in the uterine fundus?', description: 'Breech (soft, irregular) or cephalic (firm, round, ballotable)', interpretation: 'Breech presentation = consider external cephalic version at term; determines delivery mode' },
  { id: 'obs_palp_back', label: 'Fetal back (Leopold II)', shortLabel: 'Back', phase: 'palpation', type: 'select', options: ['left_anterior', 'left_posterior', 'right_anterior', 'right_posterior', 'not_identified'], mandatory: true, clinicalGuide: 'Leopold II: flat hands on either side of abdomen; back = smooth resistant; limbs = knobbly', observation: 'Fetal back position relative to maternal abdomen', description: 'Left/right + anterior/posterior; also note limb position', interpretation: 'Determines optimal auscultation site for fetal heart; anterior = easier auscultation; posterior = back-to-back labour' },
  { id: 'obs_palp_lower_pole', label: 'Lower pole (Leopold III)', shortLabel: 'Lower pole', phase: 'palpation', type: 'select', options: ['engaged', 'not_engaged', 'engaged_breech', 'unclear'], mandatory: true, clinicalGuide: 'Leopold III: thumb and fingers of right hand grasp lower pole above pubis', observation: 'Engagement of the presenting part into pelvis', description: 'Engaged (fixed, <0/5 palpable) vs not engaged (mobile, 3-5/5 palpable)', interpretation: 'Non-engaged in primigravida at term = CPD/malpresentation; multigravida = may engage in labour' },
  { id: 'obs_ausc_fetal_heart', label: 'Fetal heart auscultation', shortLabel: 'FHR', phase: 'auscultation', type: 'number', mandatory: true, clinicalGuide: 'Pinard stethoscope or Doppler; count for 60s; normal 110-160 bpm', observation: 'Fetal heart rate', measurement: true, unit: 'bpm', interpretation: '110-160 = normal; >160 = tachycardia (infection/fever/drugs); <110 = bradycardia (distress/hypoxia/block)' },
  { id: 'obs_spec_contractions', label: 'Contractions / uterine activity', shortLabel: 'Contractions', phase: 'special_tests', type: 'select', options: ['absent', 'palpable_contraction', 'regular_contractions', 'tender_uterus'], mandatory: true, clinicalGuide: 'Place hand on fundus for 30 min or assess contraction frequency over 10 min', observation: 'Uterine activity — frequency, duration, strength', description: 'Frequency (per 10 min), duration (s), strength (mild/moderate/strong)', interpretation: 'Regular + progressive = labour; tender = abruption/chorioamnionitis; hyperstimulation >5/10 min = tocolytics' },
  { id: 'obs_spec_bishop', label: 'Bishop score / cervical assessment', shortLabel: 'Bishop', phase: 'special_tests', type: 'select', options: ['not_assessed', 'unfavourable_0_3', 'intermediate_4_6', 'favourable_7_10'], mandatory: false, clinicalGuide: 'Vaginal exam: cervical dilation, effacement, consistency, position, station', observation: 'Bishop score components estimated', description: 'Dilation, effacement (%), consistency, position, station', interpretation: '≥7 = favourable for induction; <4 = unfavourable; <6 in nullip = higher C-section risk' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// NEONATAL EXAMINATION
// ═══════════════════════════════════════════════════════════════════════════════

export const NEONATAL_FIELDS: readonly SystemExamFieldDef[] = [
  { id: 'neo_insp_general', label: 'General appearance / colour', shortLabel: 'General', phase: 'inspection', type: 'select', options: ['pink_alert', 'acrocyanosis', 'central_cyanosis', 'jaundice', 'pallor', 'plethora', 'mottled'], mandatory: true, clinicalGuide: 'Observe overall appearance, colour, tone, activity, and cry', observation: 'General condition, colour, tone, and activity of the neonate', description: 'Pink, cyanosed, jaundiced, pale, plethoric; tone (flexed/floppy); activity', interpretation: 'Central cyanosis = CHD/sepsis/resp; jaundice day <1 = pathological; floppy = sepsis/HIE/metabolic; plethoric = polycythaemia' },
  { id: 'neo_insp_skin', label: 'Neonatal skin', shortLabel: 'Neo skin', phase: 'inspection', type: 'multiselect', options: ['normal', 'vernix', 'lanugo', 'milia', 'erythema_toxicum', 'stork_bites', 'mongolian_spot', 'birthmark'], mandatory: true, clinicalGuide: 'Inspect entire skin; record any rashes, marks, or lesions', observation: 'Neonatal skin findings', description: 'Vernix (preterm), lanugo (preterm), any rashes or birthmarks', interpretation: 'Erythema toxicum = benign (eosinophilic pustules); Mongolian spot = benign (lumbosacral); haemangioma = monitor' },
  { id: 'neo_insp_face', label: 'Facial / dysmorphic features', shortLabel: 'Facial', phase: 'inspection', type: 'select', options: ['normal', 'dysmorphic_features', 'asymmetric_crying_face'], mandatory: true, clinicalGuide: 'Observe for dysmorphic features: hypertelorism, low-set ears, micrognathia, cleft lip/palate', observation: 'Facial structure and symmetry', description: 'Any dysmorphic features (hypertelorism, ear position, micrognathia, cleft)', interpretation: 'Dysmorphic = genetic syndrome (T21, T18, 22q11); asymmetric cry = CN VII palsy (birth trauma)' },
  { id: 'neo_insp_chest', label: 'Chest / respiratory effort', shortLabel: 'Neo chest', phase: 'inspection', type: 'select', options: ['normal', 'grunting', 'nasal_flaring', 'intercostal_recession', 'tachypnoea', 'see_saw_respirations'], mandatory: true, clinicalGuide: 'Observe respiratory rate, effort, and pattern for 60s', observation: 'Respiratory effort and signs of respiratory distress', description: 'Rate, grunting, flaring, recession, see-saw, gasping', interpretation: 'Grunting = RDS/pneumonia/sepsis; recession = lung disease; see-saw = airway obstruction/RDS; tachypnoea = TTN/RDS' },
  { id: 'neo_insp_abdomen', label: 'Abdominal inspection (neonatal)', shortLabel: 'Neo abdomen', phase: 'inspection', type: 'select', options: ['normal', 'distended', 'scaphoid', 'visible_bowel_loops'], mandatory: true, clinicalGuide: 'Observe abdominal shape and contour; scaphoid = diaphragmatic hernia', observation: 'Abdominal contour and distension', description: 'Distended, scaphoid, visible bowel loops, omphalocele', interpretation: 'Scaphoid = congenital diaphragmatic hernia; distended = obstruction/necrotizing enterocolitis/ascites; omphalocele = abdominal wall defect' },
  { id: 'neo_palp_femoral_pulses', label: 'Femoral pulses', shortLabel: 'Femoral', phase: 'palpation', type: 'select', options: ['normal', 'weak', 'absent'], mandatory: true, clinicalGuide: 'Palpate both femoral pulses simultaneously; weak/absent = coarctation until proven otherwise', observation: 'Femoral pulse volume compared to brachial', description: 'Equal, weak, or absent compared to brachial', interpretation: 'Absent/weak = coarctation of aorta (duct-dependent) — urgent cardiology/Prostaglandin' },
  { id: 'neo_palp_abdomen', label: 'Abdominal palpation (neonatal)', shortLabel: 'Neo palp', phase: 'palpation', type: 'select', options: ['soft_benign', 'tender', 'palpable_mass', 'hepatomegaly', 'splenomegaly'], mandatory: true, clinicalGuide: 'Gentle palpation of all quadrants; note any mass, organomegaly, or tenderness', observation: 'Abdominal contents on palpation', description: 'Any palpable masses, organ enlargement, tenderness', interpretation: 'Palpable kidney = hydronephrosis/PKD/multicystic; mass = neuroblastoma/Wilms; hepatomegaly = sepsis/CHF/storage' },
  { id: 'neo_palp_hips', label: 'Hip examination (Ortolani + Barlow)', shortLabel: 'Hips', phase: 'palpation', type: 'select', options: ['normal', 'unstable_ortolani', 'unstable_barlow', 'dislocated'], mandatory: true, clinicalGuide: 'Ortolani: flex hips 90°, abduct with lift — clunk = reduction; Barlow: flexed, adduct with posterior pressure — clunk = dislocation', observation: 'Hip stability using Ortolani and Barlow manoeuvres', description: 'Ortolani (reduction) and Barlow (dislocation) tests', interpretation: 'Positive = DDH (developmental dysplasia of hip) — needs ultrasound referral' },
  { id: 'neo_spec_red_reflex', label: 'Red reflex test', shortLabel: 'Red reflex', phase: 'special_tests', type: 'select', options: ['normal', 'absent', 'white_cataract', 'asymmetric'], mandatory: true, clinicalGuide: 'Ophthalmoscope at arm\'s length; both eyes simultaneously; normal = symmetrical bright red reflex', observation: 'Retinal red reflex', description: 'Symmetry, colour, and clarity of red reflex', interpretation: 'White reflex (leukocoria) = cataract/retinoblastoma/Coats — urgent ophthalmology referral' },
  { id: 'neo_spec_moro_reflex', label: 'Moro (startle) reflex', shortLabel: 'Moro', phase: 'special_tests', type: 'select', options: ['normal', 'absent', 'asymmetric'], mandatory: false, clinicalGuide: 'Support head in semi-sitting position; allow head to drop slightly; normal = extension + abduction + then adduction + cry', observation: 'Moro reflex response', description: 'Present (symmetrical), absent, or asymmetric', interpretation: 'Absent = HIE/sepsis/CNS depression; asymmetric = brachial plexus injury (Erb-Duchenne)/clavicle fracture' },
  { id: 'neo_spec_suck_reflex', label: 'Suck / rooting reflex', shortLabel: 'Suck/root', phase: 'special_tests', type: 'select', options: ['normal', 'weak', 'absent'], mandatory: false, clinicalGuide: 'Stroke cheek/angle of mouth — infant turns toward stimulus (rooting); insert gloved finger — sucking', observation: 'Rooting and sucking reflexes', description: 'Rooting (present/absent) and suck (normal, weak, absent)', interpretation: 'Absent = prematurity/CNS depression/HIE/sepsis; weak = poor feeding risk' },
  { id: 'neo_spec_primitive_reflexes', label: 'Other primitive reflexes', shortLabel: 'Primitive rfx', phase: 'special_tests', type: 'multiselect', options: ['palmar_grasp', 'plantar_grasp', 'stepping', 'asymmetric_tonic_neck', 'babinski'], mandatory: false, clinicalGuide: 'Palmar grasp = press finger into palm; stepping = hold upright, soles on surface; ATNR = rotate head, observe fencing', observation: 'Presence and symmetry of primitive reflexes', description: 'Palmar grasp, plantar grasp, stepping, ATNR, Babinski', interpretation: 'Grasp = present term; ATNR = present birth-6mo; Babinski extensor = normal <1yr; absent stepping = hypotonia/prematurity' },
];
