// AMEXAN Universal Component Library - Registry
// Constitutional Principle: Every component is registered, versioned, and contract-checked.
// Registers every component in the universal library against the ComponentRegistry.

import { ComponentRegistry } from '@/lib/design/component-registry';
import type { ComponentContract } from '@/lib/design/component-registry';

const VERSION = { major: 1, minor: 0, patch: 0 };

const contracts: ComponentContract[] = [
  {
    id: 'button',
    variants: ['primary', 'secondary', 'outline', 'ghost', 'danger', 'success'],
    sizes: ['xs', 'sm', 'md', 'lg', 'xl'],
    states: ['default', 'hover', 'focus', 'pressed', 'disabled', 'loading', 'error', 'success', 'offline'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true },
    animation: true,
    themeable: true,
    telemetry: { enabled: true, events: ['click', 'focus', 'blur'] },
    version: VERSION,
    minHeight: 48,
  },
  {
    id: 'badge',
    variants: ['primary', 'secondary', 'success', 'warning', 'danger', 'info', 'neutral'],
    sizes: ['xs', 'sm', 'md', 'lg'],
    states: ['default', 'disabled'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: false },
    animation: false,
    themeable: true,
    telemetry: { enabled: false, events: [] },
    version: VERSION,
  },
  {
    id: 'card',
    variants: ['default', 'elevated', 'outlined', 'filled'],
    sizes: ['sm', 'md', 'lg'],
    states: ['default', 'hover', 'focus', 'disabled', 'loading', 'error', 'offline'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true },
    animation: true,
    themeable: true,
    telemetry: { enabled: true, events: ['click', 'open', 'close'] },
    version: VERSION,
  },
  {
    id: 'input',
    variants: ['default', 'filled', 'danger', 'success'],
    sizes: ['sm', 'md', 'lg'],
    states: ['default', 'hover', 'focus', 'disabled', 'loading', 'error', 'success', 'offline'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true },
    animation: true,
    themeable: true,
    telemetry: { enabled: true, events: ['change', 'blur', 'focus'] },
    version: VERSION,
    minHeight: 48,
  },
  {
    id: 'textarea',
    variants: ['default', 'filled', 'danger'],
    sizes: ['sm', 'md', 'lg'],
    states: ['default', 'hover', 'focus', 'disabled', 'loading', 'error', 'offline'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true },
    animation: true,
    themeable: true,
    telemetry: { enabled: true, events: ['change', 'blur'] },
    version: VERSION,
    minHeight: 96,
  },
  {
    id: 'select',
    variants: ['default', 'filled', 'danger'],
    sizes: ['sm', 'md', 'lg'],
    states: ['default', 'hover', 'focus', 'disabled', 'loading', 'error', 'offline'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true },
    animation: true,
    themeable: true,
    telemetry: { enabled: true, events: ['change'] },
    version: VERSION,
    minHeight: 48,
  },
  {
    id: 'checkbox',
    variants: ['primary', 'success', 'danger'],
    sizes: ['md'],
    states: ['default', 'hover', 'focus', 'disabled', 'loading', 'error'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true, ariaLive: 'polite' },
    animation: true,
    themeable: true,
    telemetry: { enabled: true, events: ['change'] },
    version: VERSION,
    minHeight: 48,
  },
  {
    id: 'radio',
    variants: ['primary', 'success', 'danger'],
    sizes: ['md'],
    states: ['default', 'hover', 'focus', 'disabled', 'loading'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true },
    animation: true,
    themeable: true,
    telemetry: { enabled: true, events: ['change'] },
    version: VERSION,
    minHeight: 48,
  },
  {
    id: 'switch',
    variants: ['primary', 'success', 'warning'],
    sizes: ['md'],
    states: ['default', 'hover', 'focus', 'disabled', 'loading'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true, ariaLive: 'polite' },
    animation: true,
    themeable: true,
    telemetry: { enabled: true, events: ['change'] },
    version: VERSION,
    minHeight: 48,
  },
  {
    id: 'skeleton',
    variants: ['default'],
    sizes: ['sm', 'md', 'lg'],
    states: ['default'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: false },
    animation: true,
    themeable: true,
    telemetry: { enabled: false, events: [] },
    version: VERSION,
  },
  {
    id: 'loader',
    variants: ['circular', 'linear'],
    sizes: ['sm', 'md', 'lg'],
    states: ['default', 'error'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: false, ariaLive: 'polite' },
    animation: true,
    themeable: true,
    telemetry: { enabled: false, events: [] },
    version: VERSION,
  },
  {
    id: 'empty-state',
    variants: ['default'],
    sizes: ['md'],
    states: ['default'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: false },
    animation: false,
    themeable: true,
    telemetry: { enabled: true, events: ['action'] },
    version: VERSION,
  },
  {
    id: 'error-state',
    variants: ['error', 'warning', 'critical'],
    sizes: ['md'],
    states: ['default', 'error'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true, ariaLive: 'assertive' },
    animation: false,
    themeable: true,
    telemetry: { enabled: true, events: ['retry', 'support'] },
    version: VERSION,
  },
  {
    id: 'notification',
    variants: ['info', 'success', 'warning', 'danger'],
    sizes: ['md'],
    states: ['default', 'success', 'error'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true, ariaLive: 'polite' },
    animation: true,
    themeable: true,
    telemetry: { enabled: true, events: ['dismiss', 'action'] },
    version: VERSION,
  },
  {
    id: 'tooltip',
    variants: ['default'],
    sizes: ['sm', 'md'],
    states: ['default', 'focus', 'hover'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true },
    animation: true,
    themeable: true,
    telemetry: { enabled: false, events: [] },
    version: VERSION,
  },
  {
    id: 'avatar',
    variants: ['default'],
    sizes: ['xs', 'sm', 'md', 'lg', 'xl'],
    states: ['default', 'disabled'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: false },
    animation: false,
    themeable: true,
    telemetry: { enabled: false, events: [] },
    version: VERSION,
  },
  {
    id: 'breadcrumb',
    variants: ['default'],
    sizes: ['sm', 'md'],
    states: ['default', 'focus', 'disabled'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true },
    animation: false,
    themeable: true,
    telemetry: { enabled: true, events: ['click'] },
    version: VERSION,
  },
  {
    id: 'pagination',
    variants: ['default'],
    sizes: ['sm', 'md'],
    states: ['default', 'focus', 'disabled'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true },
    animation: true,
    themeable: true,
    telemetry: { enabled: true, events: ['navigate'] },
    version: VERSION,
    minHeight: 48,
  },
  {
    id: 'modal',
    variants: ['default'],
    sizes: ['sm', 'md', 'lg', 'xl'],
    states: ['default', 'loading', 'error', 'success', 'offline'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true, ariaLive: 'polite' },
    animation: true,
    themeable: true,
    telemetry: { enabled: true, events: ['open', 'close', 'dismiss'] },
    version: VERSION,
  },
  {
    id: 'drawer',
    variants: ['default'],
    sizes: ['sm', 'md', 'lg'],
    states: ['default', 'loading', 'error', 'offline'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true, ariaLive: 'polite' },
    animation: true,
    themeable: true,
    telemetry: { enabled: true, events: ['open', 'close'] },
    version: VERSION,
  },
  {
    id: 'tabs',
    variants: ['default'],
    sizes: ['sm', 'md', 'lg'],
    states: ['default', 'focus', 'disabled'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true },
    animation: true,
    themeable: true,
    telemetry: { enabled: true, events: ['select'] },
    version: VERSION,
    minHeight: 48,
  },
  {
    id: 'accordion',
    variants: ['default'],
    sizes: ['sm', 'md'],
    states: ['default', 'focus', 'disabled', 'hover'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true },
    animation: true,
    themeable: true,
    telemetry: { enabled: true, events: ['toggle'] },
    version: VERSION,
    minHeight: 48,
  },
  {
    id: 'table',
    variants: ['default'],
    sizes: ['sm', 'md', 'lg'],
    states: ['default', 'hover', 'focus', 'disabled', 'loading', 'offline'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true },
    animation: false,
    themeable: true,
    telemetry: { enabled: true, events: ['row-click', 'sort'] },
    version: VERSION,
  },
  {
    id: 'datagrid',
    variants: ['default'],
    sizes: ['sm', 'md', 'lg'],
    states: ['default', 'hover', 'focus', 'disabled', 'loading', 'offline'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true },
    animation: false,
    themeable: true,
    telemetry: { enabled: true, events: ['sort', 'select', 'page'] },
    version: VERSION,
  },
  {
    id: 'timeline',
    variants: ['default'],
    sizes: ['sm', 'md', 'lg'],
    states: ['default', 'hover', 'focus'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true },
    animation: false,
    themeable: true,
    telemetry: { enabled: true, events: ['event-click'] },
    version: VERSION,
  },
  {
    id: 'calendar',
    variants: ['default'],
    sizes: ['sm', 'md', 'lg'],
    states: ['default', 'hover', 'focus', 'disabled'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true },
    animation: true,
    themeable: true,
    telemetry: { enabled: true, events: ['select', 'navigate'] },
    version: VERSION,
    minHeight: 44,
  },
  {
    id: 'navbar',
    variants: ['default'],
    sizes: ['md'],
    states: ['default', 'focus', 'disabled'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true },
    animation: false,
    themeable: true,
    telemetry: { enabled: true, events: ['item-click', 'menu-open'] },
    version: VERSION,
    minHeight: 44,
  },
  {
    id: 'sidebar',
    variants: ['default'],
    sizes: ['sm', 'md', 'lg'],
    states: ['default', 'focus', 'disabled', 'hover'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true },
    animation: true,
    themeable: true,
    telemetry: { enabled: true, events: ['item-click', 'toggle'] },
    version: VERSION,
    minHeight: 44,
  },
  {
    id: 'command',
    variants: ['default'],
    sizes: ['md', 'lg'],
    states: ['default', 'focus', 'loading', 'error'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true, ariaLive: 'polite' },
    animation: true,
    themeable: true,
    telemetry: { enabled: true, events: ['open', 'execute', 'close'] },
    version: VERSION,
    minHeight: 44,
  },
  {
    id: 'form',
    variants: ['default'],
    sizes: ['md', 'lg'],
    states: ['default', 'focus', 'loading', 'error', 'success', 'offline'],
    accessibility: { label: true, keyboardOperable: true, focusVisible: true },
    animation: false,
    themeable: true,
    telemetry: { enabled: true, events: ['submit', 'cancel', 'autosave'] },
    version: VERSION,
  },
];

export function registerUiComponents(): string[] {
  const registry = ComponentRegistry.getInstance();
  for (const contract of contracts) {
    if (!registry.has(contract.id)) {
      registry.register(contract);
    }
  }
  return contracts.map((c) => c.id);
}

export const uiComponentIds = contracts.map((c) => c.id);

export default registerUiComponents;

