// Disease catalogue organized by department -> section -> disease
// Based on clinical protocols from clinicalProtocols.ts

export interface DiseaseEntry {
  id: string;
  name: string;
  departmentKey: string;
  section: string;
  prevalence: 'very_common' | 'common' | 'uncommon' | 'rare';
  emergency: boolean;
  mustNotMiss: boolean;
}

export const DISEASE_CATALOGUE: Record<string, DiseaseEntry[]> = {
  'paediatric-respiratory': [
    { id: 'pneumonia', name: 'Paediatric Pneumonia', departmentKey: 'PAED', section: 'paediatric-respiratory', prevalence: 'very_common', emergency: true, mustNotMiss: true },
    { id: 'bronchiolitis', name: 'Bronchiolitis', departmentKey: 'PAED', section: 'paediatric-respiratory', prevalence: 'very_common', emergency: true, mustNotMiss: false },
    { id: 'asthma', name: 'Paediatric Asthma', departmentKey: 'PAED', section: 'paediatric-respiratory', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'tuberculosis', name: 'Paediatric Tuberculosis', departmentKey: 'PAED', section: 'paediatric-respiratory', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'foreign-body-aspiration', name: 'Foreign Body Aspiration', departmentKey: 'PAED', section: 'paediatric-respiratory', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'croup', name: 'Paediatric Croup', departmentKey: 'PAED', section: 'paediatric-respiratory', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'epiglottitis', name: 'Paediatric Epiglottitis', departmentKey: 'PAED', section: 'paediatric-respiratory', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
  ],
  'paediatric-cardiology': [
    { id: 'congenital_heart_disease', name: 'Congenital Heart Disease', departmentKey: 'PAED', section: 'paediatric-cardiology', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'rheumatic_heart', name: 'Rheumatic Heart Disease', departmentKey: 'PAED', section: 'paediatric-cardiology', prevalence: 'common', emergency: false, mustNotMiss: true },
  ],
  'neonatology': [
    { id: 'neonatal_jaundice', name: 'Neonatal Jaundice', departmentKey: 'PAED', section: 'neonatology', prevalence: 'very_common', emergency: false, mustNotMiss: false },
    { id: 'neonatal_sepsis', name: 'Neonatal Sepsis', departmentKey: 'PAED', section: 'neonatology', prevalence: 'common', emergency: true, mustNotMiss: true },
    { id: 'prematurity', name: 'Prematurity / RDS', departmentKey: 'PAED', section: 'neonatology', prevalence: 'common', emergency: true, mustNotMiss: false },
  ],
  'paediatric-emergency': [
    { id: 'sepsis_emergency', name: 'Sepsis', departmentKey: 'PAED', section: 'paediatric-emergency', prevalence: 'common', emergency: true, mustNotMiss: true },
    { id: 'anaphylaxis', name: 'Anaphylaxis', departmentKey: 'PAED', section: 'paediatric-emergency', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'status_epilepticus', name: 'Status Epilepticus', departmentKey: 'PAED', section: 'paediatric-emergency', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'major_trauma', name: 'Major Trauma', departmentKey: 'PAED', section: 'paediatric-emergency', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
  ],
  'paediatric-infectious': [
    { id: 'meningitis', name: 'Meningitis', departmentKey: 'PAED', section: 'paediatric-infectious', prevalence: 'common', emergency: true, mustNotMiss: true },
    { id: 'malaria', name: 'Severe Malaria', departmentKey: 'PAED', section: 'paediatric-infectious', prevalence: 'very_common', emergency: true, mustNotMiss: true },
  ],
  'general-medicine': [
    { id: 'hypertension', name: 'Essential Hypertension', departmentKey: 'IM', section: 'general-medicine', prevalence: 'very_common', emergency: false, mustNotMiss: false },
    { id: 'heart-failure', name: 'Heart Failure', departmentKey: 'IM', section: 'general-medicine', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'pneumonia', name: 'Community-Acquired Pneumonia', departmentKey: 'IM', section: 'general-medicine', prevalence: 'very_common', emergency: false, mustNotMiss: true },
    { id: 'copd', name: 'COPD', departmentKey: 'IM', section: 'general-medicine', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'diabetes_t2', name: 'Type 2 Diabetes', departmentKey: 'IM', section: 'general-medicine', prevalence: 'very_common', emergency: false, mustNotMiss: false },
    { id: 'diabetes-type-1', name: 'Type 1 Diabetes', departmentKey: 'IM', section: 'general-medicine', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'thyroid-disorders', name: 'Thyroid Disorders', departmentKey: 'IM', section: 'general-medicine', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'dyslipidemia', name: 'Dyslipidemia', departmentKey: 'IM', section: 'general-medicine', prevalence: 'very_common', emergency: false, mustNotMiss: false },
    { id: 'ckd', name: 'Chronic Kidney Disease', departmentKey: 'IM', section: 'general-medicine', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'af', name: 'Atrial Fibrillation', departmentKey: 'IM', section: 'general-medicine', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'depression', name: 'Major Depressive Disorder', departmentKey: 'IM', section: 'general-medicine', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'peptic_ulcer', name: 'Peptic Ulcer Disease', departmentKey: 'IM', section: 'general-medicine', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'delirium', name: 'Delirium', departmentKey: 'IM', section: 'general-medicine', prevalence: 'common', emergency: true, mustNotMiss: true },
    { id: 'dementia', name: 'Dementia', departmentKey: 'IM', section: 'general-medicine', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'falls', name: 'Falls', departmentKey: 'IM', section: 'general-medicine', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'fatigue', name: 'Fatigue', departmentKey: 'IM', section: 'general-medicine', prevalence: 'very_common', emergency: false, mustNotMiss: false },
    { id: 'fever-of-unknown-origin', name: 'FUO', departmentKey: 'IM', section: 'general-medicine', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'frailty-syndrome', name: 'Frailty', departmentKey: 'IM', section: 'general-medicine', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'polypharmacy', name: 'Polypharmacy', departmentKey: 'IM', section: 'general-medicine', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'preoperative-assessment', name: 'Preoperative Assessment', departmentKey: 'IM', section: 'general-medicine', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'weight-loss', name: 'Weight Loss (Unintentional)', departmentKey: 'IM', section: 'general-medicine', prevalence: 'common', emergency: false, mustNotMiss: false },
  ],
  'infectious-disease': [
    { id: 'hiv', name: 'HIV / AIDS', departmentKey: 'IM', section: 'infectious-disease', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'tb', name: 'Tuberculosis', departmentKey: 'IM', section: 'infectious-disease', prevalence: 'very_common', emergency: false, mustNotMiss: true },
  ],
  'rheumatology': [
    { id: 'rheumatoid_arthritis', name: 'Rheumatoid Arthritis', departmentKey: 'IM', section: 'rheumatology', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'lupus', name: 'Systemic Lupus Erythematosus', departmentKey: 'IM', section: 'rheumatology', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'gout', name: 'Gout', departmentKey: 'IM', section: 'rheumatology', prevalence: 'common', emergency: false, mustNotMiss: false },
  ],
  'general-cardiology': [
    { id: 'chest_pain', name: 'Chest Pain / ACS', departmentKey: 'CARD', section: 'general-cardiology', prevalence: 'very_common', emergency: true, mustNotMiss: true },
    { id: 'hypertension_card', name: 'Hypertension', departmentKey: 'CARD', section: 'general-cardiology', prevalence: 'very_common', emergency: false, mustNotMiss: false },
  ],
  'heart-failure': [
    { id: 'heart_failure_card', name: 'Heart Failure (HFrEF)', departmentKey: 'CARD', section: 'heart-failure', prevalence: 'common', emergency: false, mustNotMiss: true },
  ],
  'cardiac-ep': [
    { id: 'af_ep', name: 'Atrial Fibrillation', departmentKey: 'CARD', section: 'cardiac-ep', prevalence: 'common', emergency: false, mustNotMiss: true },
  ],
  'diabetes': [
    { id: 'diabetes_t1', name: 'Type 1 Diabetes', departmentKey: 'ENDO', section: 'diabetes', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'diabetes_t2_endo', name: 'Type 2 Diabetes', departmentKey: 'ENDO', section: 'diabetes', prevalence: 'very_common', emergency: false, mustNotMiss: false },
    { id: 'dka', name: 'Diabetic Ketoacidosis', departmentKey: 'ENDO', section: 'diabetes', prevalence: 'common', emergency: true, mustNotMiss: true },
  ],
  'thyroid': [
    { id: 'hypothyroidism', name: 'Hypothyroidism', departmentKey: 'ENDO', section: 'thyroid', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'hyperthyroidism', name: 'Hyperthyroidism', departmentKey: 'ENDO', section: 'thyroid', prevalence: 'common', emergency: false, mustNotMiss: false },
  ],
  'pulmonology': [
    { id: 'copd_pulm', name: 'COPD', departmentKey: 'RESP', section: 'pulmonology', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'asthma_pulm', name: 'Asthma', departmentKey: 'RESP', section: 'pulmonology', prevalence: 'very_common', emergency: false, mustNotMiss: true },
    { id: 'pneumonia_pulm', name: 'Pneumonia', departmentKey: 'RESP', section: 'pulmonology', prevalence: 'very_common', emergency: false, mustNotMiss: true },
    { id: 'tb_pulm', name: 'Pulmonary Tuberculosis', departmentKey: 'RESP', section: 'pulmonology', prevalence: 'very_common', emergency: false, mustNotMiss: true },
    { id: 'bronchiectasis', name: 'Bronchiectasis', departmentKey: 'RESP', section: 'pulmonology', prevalence: 'uncommon', emergency: false, mustNotMiss: false },
    { id: 'interstitial-lung-disease', name: 'Interstitial Lung Disease', departmentKey: 'RESP', section: 'pulmonology', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'lung-abscess', name: 'Lung Abscess', departmentKey: 'RESP', section: 'pulmonology', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'pulmonary-embolism', name: 'Pulmonary Embolism', departmentKey: 'RESP', section: 'pulmonology', prevalence: 'common', emergency: true, mustNotMiss: true },
    { id: 'pulmonary-hypertension', name: 'Pulmonary Hypertension', departmentKey: 'RESP', section: 'pulmonology', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'respiratory-failure', name: 'Respiratory Failure', departmentKey: 'RESP', section: 'pulmonology', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'pleural_effusion', name: 'Pleural Effusion', departmentKey: 'RESP', section: 'pulmonology', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'empyema', name: 'Empyema', departmentKey: 'RESP', section: 'pulmonology', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'pneumothorax', name: 'Pneumothorax', departmentKey: 'RESP', section: 'pulmonology', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'bronchiolitis', name: 'Bronchiolitis (Adult)', departmentKey: 'RESP', section: 'pulmonology', prevalence: 'uncommon', emergency: false, mustNotMiss: false },
    { id: 'croup', name: 'Croup (Adult)', departmentKey: 'RESP', section: 'pulmonology', prevalence: 'rare', emergency: false, mustNotMiss: false },
    { id: 'epiglottitis', name: 'Epiglottitis (Adult)', departmentKey: 'RESP', section: 'pulmonology', prevalence: 'rare', emergency: true, mustNotMiss: true },
    { id: 'foreign_body_aspiration', name: 'Foreign Body Aspiration (Adult)', departmentKey: 'RESP', section: 'pulmonology', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
  ],
  'sleep-medicine': [
    { id: 'osa', name: 'Obstructive Sleep Apnoea', departmentKey: 'RESP', section: 'sleep-medicine', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'obstructive-sleep-apnea', name: 'Obstructive Sleep Apnea', departmentKey: 'RESP', section: 'sleep-medicine', prevalence: 'common', emergency: false, mustNotMiss: false },
  ],
  'general-nephrology': [
    { id: 'ckd_neph', name: 'Chronic Kidney Disease', departmentKey: 'RENAL', section: 'general-nephrology', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'aki', name: 'Acute Kidney Injury', departmentKey: 'RENAL', section: 'general-nephrology', prevalence: 'common', emergency: true, mustNotMiss: true },
    { id: 'acute-glomerulonephritis', name: 'Acute Glomerulonephritis', departmentKey: 'RENAL', section: 'general-nephrology', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'drug-induced-nephropathy', name: 'Drug-Induced Nephropathy', departmentKey: 'RENAL', section: 'general-nephrology', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'nephrotic-syndrome', name: 'Nephrotic Syndrome', departmentKey: 'RENAL', section: 'general-nephrology', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'nephritic-syndrome', name: 'Nephritic Syndrome', departmentKey: 'RENAL', section: 'general-nephrology', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'lupus-nephritis', name: 'Lupus Nephritis', departmentKey: 'RENAL', section: 'general-nephrology', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'iga-nephropathy', name: 'IgA Nephropathy', departmentKey: 'RENAL', section: 'general-nephrology', prevalence: 'uncommon', emergency: false, mustNotMiss: false },
    { id: 'prerenal-aki', name: 'Prerenal AKI', departmentKey: 'RENAL', section: 'general-nephrology', prevalence: 'common', emergency: true, mustNotMiss: true },
    { id: 'intrinsic-aki', name: 'Intrinsic AKI', departmentKey: 'RENAL', section: 'general-nephrology', prevalence: 'common', emergency: true, mustNotMiss: true },
    { id: 'postrenal-aki', name: 'Postrenal AKI', departmentKey: 'RENAL', section: 'general-nephrology', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'renal-artery-stenosis', name: 'Renal Artery Stenosis', departmentKey: 'RENAL', section: 'general-nephrology', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'renovascular-hypertension', name: 'Renovascular Hypertension', departmentKey: 'RENAL', section: 'general-nephrology', prevalence: 'uncommon', emergency: false, mustNotMiss: false },
    { id: 'hyperkalemia', name: 'Hyperkalemia', departmentKey: 'RENAL', section: 'general-nephrology', prevalence: 'common', emergency: true, mustNotMiss: true },
    { id: 'hyponatremia', name: 'Hyponatremia', departmentKey: 'RENAL', section: 'general-nephrology', prevalence: 'common', emergency: true, mustNotMiss: true },
    { id: 'acid-base-disorders', name: 'Acid-Base Disorders', departmentKey: 'RENAL', section: 'general-nephrology', prevalence: 'common', emergency: true, mustNotMiss: true },
    { id: 'immunosuppression', name: 'Immunosuppression (Renal)', departmentKey: 'RENAL', section: 'general-nephrology', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'renal-biopsy-complications', name: 'Renal Biopsy Complications', departmentKey: 'RENAL', section: 'general-nephrology', prevalence: 'rare', emergency: true, mustNotMiss: false },
  ],
  'dialysis': [
    { id: 'esrd', name: 'End-Stage Renal Disease', departmentKey: 'RENAL', section: 'dialysis', prevalence: 'uncommon', emergency: false, mustNotMiss: false },
    { id: 'ckd-stages', name: 'CKD Staging', departmentKey: 'RENAL', section: 'dialysis', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'dialysis-indications', name: 'Dialysis Indications', departmentKey: 'RENAL', section: 'dialysis', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'hemodialysis-access', name: 'Hemodialysis Access', departmentKey: 'RENAL', section: 'dialysis', prevalence: 'uncommon', emergency: false, mustNotMiss: false },
    { id: 'dialysis-disequilibrium', name: 'Dialysis Disequilibrium', departmentKey: 'RENAL', section: 'dialysis', prevalence: 'uncommon', emergency: true, mustNotMiss: false },
    { id: 'peritoneal-dialysis-peritonitis', name: 'PD Peritonitis', departmentKey: 'RENAL', section: 'dialysis', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'kidney-transplant-rejection', name: 'Kidney Transplant Rejection', departmentKey: 'RENAL', section: 'dialysis', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
  ],
  'general-neurology': [
    { id: 'alzheimer-disease', name: 'Alzheimer Disease', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'parkinsons', name: 'Parkinson Disease', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'uncommon', emergency: false, mustNotMiss: false },
    { id: 'trigeminal-neuralgia', name: 'Trigeminal Neuralgia', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'uncommon', emergency: false, mustNotMiss: false },
    { id: 'bell-palsy', name: 'Bell Palsy', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'restless-legs-syndrome', name: 'Restless Legs Syndrome', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'multiple-sclerosis', name: 'Multiple Sclerosis', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'myasthenia-gravis', name: 'Myasthenia Gravis', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'guillain-barre', name: 'Guillain-Barre Syndrome', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'chronic-inflammatory-demyelinating-polyneuropathy', name: 'CIDP', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'rare', emergency: false, mustNotMiss: true },
    { id: 'migraine', name: 'Migraine', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'very_common', emergency: false, mustNotMiss: false },
    { id: 'cluster-headache', name: 'Cluster Headache', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'uncommon', emergency: false, mustNotMiss: false },
    { id: 'tension-headache', name: 'Tension Headache', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'very_common', emergency: false, mustNotMiss: false },
    { id: 'idiopathic-intracranial-hypertension', name: 'Idiopathic Intracranial Hypertension', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'als', name: 'ALS', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'rare', emergency: false, mustNotMiss: true },
    { id: 'muscular-dystrophy', name: 'Muscular Dystrophy', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'rare', emergency: false, mustNotMiss: false },
    { id: 'neuromyelitis-optica', name: 'Neuromyelitis Optica', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'rare', emergency: true, mustNotMiss: true },
    { id: 'essential-tremor', name: 'Essential Tremor', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'dystonia', name: 'Dystonia', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'uncommon', emergency: false, mustNotMiss: false },
    { id: 'encephalitis', name: 'Encephalitis', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'brain-abscess', name: 'Brain Abscess', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'rare', emergency: true, mustNotMiss: true },
    { id: 'meningitis', name: 'Meningitis (Neuro)', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'peripheral-neuropathy', name: 'Peripheral Neuropathy', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'myopathy', name: 'Myopathy', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'uncommon', emergency: false, mustNotMiss: false },
    { id: 'huntington-disease', name: 'Huntington Disease', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'rare', emergency: false, mustNotMiss: false },
    { id: 'glioma', name: 'Glioma', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'meningioma', name: 'Meningioma', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'uncommon', emergency: false, mustNotMiss: false },
    { id: 'febrile-seizures', name: 'Febrile Seizures', departmentKey: 'NEURO', section: 'general-neurology', prevalence: 'common', emergency: true, mustNotMiss: false },
  ],
  'stroke': [
    { id: 'ischaemic_stroke', name: 'Acute Ischaemic Stroke', departmentKey: 'NEURO', section: 'stroke', prevalence: 'common', emergency: true, mustNotMiss: true },
    { id: 'haemorrhagic_stroke', name: 'Haemorrhagic Stroke', departmentKey: 'NEURO', section: 'stroke', prevalence: 'common', emergency: true, mustNotMiss: true },
    { id: 'tia', name: 'Transient Ischaemic Attack', departmentKey: 'NEURO', section: 'stroke', prevalence: 'common', emergency: true, mustNotMiss: true },
    { id: 'subarachnoid-hemorrhage', name: 'Subarachnoid Hemorrhage', departmentKey: 'NEURO', section: 'stroke', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'cerebral-venous-thrombosis', name: 'Cerebral Venous Thrombosis', departmentKey: 'NEURO', section: 'stroke', prevalence: 'rare', emergency: true, mustNotMiss: true },
  ],
  'epilepsy': [
    { id: 'epilepsy_monitor', name: 'Epilepsy', departmentKey: 'NEURO', section: 'epilepsy', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'focal-epilepsy', name: 'Focal Epilepsy', departmentKey: 'NEURO', section: 'epilepsy', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'generalized-epilepsy', name: 'Generalized Epilepsy', departmentKey: 'NEURO', section: 'epilepsy', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'status-epilepticus', name: 'Status Epilepticus', departmentKey: 'NEURO', section: 'epilepsy', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
  ],
  'general-gi': [
    { id: 'gerd', name: 'GERD', departmentKey: 'GI', section: 'general-gi', prevalence: 'very_common', emergency: false, mustNotMiss: false },
    { id: 'peptic_ulcer_gi', name: 'Peptic Ulcer Disease', departmentKey: 'GI', section: 'general-gi', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'ibd', name: 'Inflammatory Bowel Disease', departmentKey: 'GI', section: 'general-gi', prevalence: 'uncommon', emergency: false, mustNotMiss: false },
    { id: 'gastroenteritis', name: 'Acute Gastroenteritis', departmentKey: 'GI', section: 'general-gi', prevalence: 'very_common', emergency: false, mustNotMiss: false },
  ],
  'hepatology': [
    { id: 'cirrhosis', name: 'Liver Cirrhosis', departmentKey: 'GI', section: 'hepatology', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'hepatitis-b', name: 'Hepatitis B', departmentKey: 'GI', section: 'hepatology', prevalence: 'very_common', emergency: false, mustNotMiss: true },
    { id: 'hepatitis-c', name: 'Hepatitis C', departmentKey: 'GI', section: 'hepatology', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'alcoholic-hepatitis', name: 'Alcoholic Hepatitis', departmentKey: 'GI', section: 'hepatology', prevalence: 'common', emergency: true, mustNotMiss: true },
    { id: 'non-alcoholic-fatty-liver-disease', name: 'NAFLD/NASH', departmentKey: 'GI', section: 'hepatology', prevalence: 'very_common', emergency: false, mustNotMiss: false },
    { id: 'autoimmune-hepatitis', name: 'Autoimmune Hepatitis', departmentKey: 'GI', section: 'hepatology', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'hepatocellular-carcinoma', name: 'Hepatocellular Carcinoma', departmentKey: 'GI', section: 'hepatology', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'primary-biliary-cholangitis', name: 'Primary Biliary Cholangitis', departmentKey: 'GI', section: 'hepatology', prevalence: 'uncommon', emergency: false, mustNotMiss: false },
    { id: 'primary-sclerosing-cholangitis', name: 'Primary Sclerosing Cholangitis', departmentKey: 'GI', section: 'hepatology', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'hemochromatosis', name: 'Hereditary Hemochromatosis', departmentKey: 'GI', section: 'hepatology', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'wilson-disease', name: 'Wilson Disease', departmentKey: 'GI', section: 'hepatology', prevalence: 'rare', emergency: false, mustNotMiss: true },
    { id: 'alpha-1-antitrypsin-deficiency', name: 'Alpha-1 Antitrypsin Deficiency', departmentKey: 'GI', section: 'hepatology', prevalence: 'rare', emergency: false, mustNotMiss: false },
    { id: 'budd-chiari-syndrome', name: 'Budd-Chiari Syndrome', departmentKey: 'GI', section: 'hepatology', prevalence: 'rare', emergency: true, mustNotMiss: true },
    { id: 'liver-abscess', name: 'Liver Abscess', departmentKey: 'GI', section: 'hepatology', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
  ],
  'antenatal': [
    { id: 'preeclampsia', name: 'Pre-eclampsia', departmentKey: 'OB', section: 'antenatal', prevalence: 'common', emergency: true, mustNotMiss: true },
    { id: 'gestational_dm', name: 'Gestational Diabetes', departmentKey: 'OB', section: 'antenatal', prevalence: 'common', emergency: false, mustNotMiss: false },
  ],
  'high-risk': [
    { id: 'eclampsia', name: 'Eclampsia', departmentKey: 'OB', section: 'high-risk', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'pph', name: 'Postpartum Haemorrhage', departmentKey: 'OB', section: 'high-risk', prevalence: 'common', emergency: true, mustNotMiss: true },
  ],
  'general-psychiatry': [
    { id: 'major-depressive-disorder', name: 'Major Depressive Disorder', departmentKey: 'PSYCH', section: 'general-psychiatry', prevalence: 'very_common', emergency: false, mustNotMiss: false },
    { id: 'bipolar-disorder', name: 'Bipolar Disorder', departmentKey: 'PSYCH', section: 'general-psychiatry', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'schizophrenia', name: 'Schizophrenia', departmentKey: 'PSYCH', section: 'general-psychiatry', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'schizoaffective-disorder', name: 'Schizoaffective Disorder', departmentKey: 'PSYCH', section: 'general-psychiatry', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'generalized-anxiety', name: 'Generalised Anxiety Disorder', departmentKey: 'PSYCH', section: 'general-psychiatry', prevalence: 'very_common', emergency: false, mustNotMiss: false },
    { id: 'panic-disorder', name: 'Panic Disorder', departmentKey: 'PSYCH', section: 'general-psychiatry', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'social-anxiety', name: 'Social Anxiety Disorder', departmentKey: 'PSYCH', section: 'general-psychiatry', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'specific-phobia', name: 'Specific Phobia', departmentKey: 'PSYCH', section: 'general-psychiatry', prevalence: 'very_common', emergency: false, mustNotMiss: false },
    { id: 'ocd', name: 'OCD', departmentKey: 'PSYCH', section: 'general-psychiatry', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'ptsd', name: 'PTSD', departmentKey: 'PSYCH', section: 'general-psychiatry', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'acute-stress-disorder', name: 'Acute Stress Disorder', departmentKey: 'PSYCH', section: 'general-psychiatry', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'anorexia-nervosa', name: 'Anorexia Nervosa', departmentKey: 'PSYCH', section: 'general-psychiatry', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'bulimia-nervosa', name: 'Bulimia Nervosa', departmentKey: 'PSYCH', section: 'general-psychiatry', prevalence: 'uncommon', emergency: false, mustNotMiss: false },
    { id: 'persistent-depressive-disorder', name: 'Persistent Depressive Disorder', departmentKey: 'PSYCH', section: 'general-psychiatry', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'insomnia', name: 'Insomnia Disorder', departmentKey: 'PSYCH', section: 'general-psychiatry', prevalence: 'very_common', emergency: false, mustNotMiss: false },
    { id: 'somatic-symptom-disorder', name: 'Somatic Symptom Disorder', departmentKey: 'PSYCH', section: 'general-psychiatry', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'late-life-depression', name: 'Late-Life Depression', departmentKey: 'PSYCH', section: 'general-psychiatry', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'delirium-in-medical-setting', name: 'Delirium in Medical Setting', departmentKey: 'PSYCH', section: 'general-psychiatry', prevalence: 'common', emergency: true, mustNotMiss: true },
  ],
  'child-adolescent': [
    { id: 'adhd', name: 'ADHD', departmentKey: 'PSYCH', section: 'child-adolescent', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'autism-spectrum', name: 'Autism Spectrum Disorder', departmentKey: 'PSYCH', section: 'child-adolescent', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'conduct-disorder', name: 'Conduct Disorder', departmentKey: 'PSYCH', section: 'child-adolescent', prevalence: 'uncommon', emergency: false, mustNotMiss: false },
    { id: 'tic-disorders', name: 'Tic Disorders', departmentKey: 'PSYCH', section: 'child-adolescent', prevalence: 'uncommon', emergency: false, mustNotMiss: false },
    { id: 'separation-anxiety', name: 'Separation Anxiety Disorder', departmentKey: 'PSYCH', section: 'child-adolescent', prevalence: 'common', emergency: false, mustNotMiss: false },
  ],
  'addiction': [
    { id: 'alcohol-use-disorder', name: 'Alcohol Use Disorder', departmentKey: 'PSYCH', section: 'addiction', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'substance_use', name: 'Substance Use Disorder', departmentKey: 'PSYCH', section: 'addiction', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'cannabis-use-disorder', name: 'Cannabis Use Disorder', departmentKey: 'PSYCH', section: 'addiction', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'opioid-use-disorder', name: 'Opioid Use Disorder', departmentKey: 'PSYCH', section: 'addiction', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'catatonia', name: 'Catatonia', departmentKey: 'PSYCH', section: 'addiction', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
  ],
  'general-surgery': [
    { id: 'acute_abdomen', name: 'Acute Abdomen', departmentKey: 'SURG', section: 'general-surgery', prevalence: 'very_common', emergency: true, mustNotMiss: true },
    { id: 'appendicitis', name: 'Appendicitis', departmentKey: 'SURG', section: 'general-surgery', prevalence: 'very_common', emergency: true, mustNotMiss: true },
    { id: 'cholecystitis', name: 'Cholecystitis', departmentKey: 'SURG', section: 'general-surgery', prevalence: 'common', emergency: true, mustNotMiss: true },
    { id: 'bowel_obstruction', name: 'Bowel Obstruction', departmentKey: 'SURG', section: 'general-surgery', prevalence: 'common', emergency: true, mustNotMiss: true },
    { id: 'hernia', name: 'Hernia', departmentKey: 'SURG', section: 'general-surgery', prevalence: 'very_common', emergency: false, mustNotMiss: false },
  ],
  'lbo-intelligence': [
    { id: 'large_bowel_obstruction', name: 'Large Bowel Obstruction (LBO)', departmentKey: 'SURG', section: 'lbo-intelligence', prevalence: 'common', emergency: true, mustNotMiss: true },
  ],
  'trauma': [
    { id: 'polytrauma', name: 'Polytrauma', departmentKey: 'SURG', section: 'trauma', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
  ],
  'surgical-hdu': [
    { id: 'post_op_monitoring', name: 'Post-Operative Monitoring', departmentKey: 'SURG', section: 'surgical-hdu', prevalence: 'common', emergency: true, mustNotMiss: true },
    { id: 'hdu_sepsis', name: 'HDU Sepsis Management', departmentKey: 'SURG', section: 'surgical-hdu', prevalence: 'common', emergency: true, mustNotMiss: true },
    { id: 'hdu_fluid_resuscitation', name: 'HDU Fluid & Haemodynamic Mgmt', departmentKey: 'SURG', section: 'surgical-hdu', prevalence: 'common', emergency: true, mustNotMiss: true },
  ],
  'radiation-oncology': [
    { id: 'external_beam_rt', name: 'External Beam Radiotherapy', departmentKey: 'ONCO', section: 'radiation-oncology', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'brachytherapy', name: 'Brachytherapy', departmentKey: 'ONCO', section: 'radiation-oncology', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'radiation_side_effects', name: 'Radiation Side Effects Management', departmentKey: 'ONCO', section: 'radiation-oncology', prevalence: 'common', emergency: true, mustNotMiss: false },
  ],
  'gynae-surgery': [
    { id: 'laparoscopic_gynae', name: 'Laparoscopic Gynaecological Surgery', departmentKey: 'GYN', section: 'gynae-surgery', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'open_gynae_surgery', name: 'Open Gynaecological Surgery', departmentKey: 'GYN', section: 'gynae-surgery', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'gynae_post_op', name: 'Gynaecological Post-Operative Care', departmentKey: 'GYN', section: 'gynae-surgery', prevalence: 'common', emergency: false, mustNotMiss: true },
  ],
  'icu-cardiac': [
    { id: 'post_cardiac_icu', name: 'Post-Cardiac Surgery ICU', departmentKey: 'ICU', section: 'icu-cardiac', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'cardiogenic_shock_icu', name: 'Cardiogenic Shock Management', departmentKey: 'ICU', section: 'icu-cardiac', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
    { id: 'icd_ccu', name: 'ICD / CCU Monitoring', departmentKey: 'ICU', section: 'icu-cardiac', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
  ],
  'uro-stone': [
    { id: 'eswl', name: 'Extracorporeal Shock Wave Lithotripsy', departmentKey: 'URO', section: 'uro-stone', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'ureteroscopy_ston', name: 'Ureteroscopy & Stone Retrieval', departmentKey: 'URO', section: 'uro-stone', prevalence: 'common', emergency: false, mustNotMiss: false },
    { id: 'pcnl', name: 'Percutaneous Nephrolithotomy (PCNL)', departmentKey: 'URO', section: 'uro-stone', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'metabolic_stone', name: 'Metabolic Stone Workup & Prevention', departmentKey: 'URO', section: 'uro-stone', prevalence: 'common', emergency: false, mustNotMiss: false },
  ],
  'id-stewardship': [
    { id: 'antibiotic_review', name: 'Antibiotic Review & Streamlining', departmentKey: 'ID', section: 'id-stewardship', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'opat', name: 'Outpatient Parenteral Antibiotic Therapy (OPAT)', departmentKey: 'ID', section: 'id-stewardship', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'amr_management', name: 'Antimicrobial Resistance Management', departmentKey: 'ID', section: 'id-stewardship', prevalence: 'common', emergency: true, mustNotMiss: true },
  ],
  'rheum-infusion': [
    { id: 'rituximab_infusion', name: 'Rituximab Infusion Therapy', departmentKey: 'RHEUM', section: 'rheum-infusion', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'infliximab_infusion', name: 'Infliximab Infusion Therapy', departmentKey: 'RHEUM', section: 'rheum-infusion', prevalence: 'uncommon', emergency: false, mustNotMiss: true },
    { id: 'biologic_infusion_monitoring', name: 'Biologic Infusion Monitoring & Safety', departmentKey: 'RHEUM', section: 'rheum-infusion', prevalence: 'uncommon', emergency: true, mustNotMiss: true },
  ],
  'pharmacy-general': [
    { id: 'vancomycin-dosing', name: 'Vancomycin Dosing & Monitoring', departmentKey: 'PHARM', section: 'pharmacy-general', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'aminoglycoside-dosing', name: 'Aminoglycoside Dosing', departmentKey: 'PHARM', section: 'pharmacy-general', prevalence: 'common', emergency: false, mustNotMiss: true },
    { id: 'drug-interactions', name: 'Drug-Drug Interactions', departmentKey: 'PHARM', section: 'pharmacy-general', prevalence: 'common', emergency: true, mustNotMiss: false },
  ],
};

export function getDiseasesForSection(sectionSlug: string): DiseaseEntry[] {
  return DISEASE_CATALOGUE[sectionSlug] || [];
}

export function getDiseaseById(sectionSlug: string, diseaseId: string): DiseaseEntry | undefined {
  return (DISEASE_CATALOGUE[sectionSlug] || []).find(d => d.id === diseaseId);
}
