import { DEPARTMENTS } from './clinicalProtocols';
import { CLINICAL_PATHWAYS, type EncounterType, ENCOUNTER_LABELS } from './encounterTypes';

export interface EncounterTypeInfo {
  type: EncounterType;
  label: string;
  icon: string;
  color: string;
  activeCases?: number;
}

export interface UnitInfo {
  id: string;
  label: string;
  description: string;
  icon: string;
  encounterTypes: EncounterTypeInfo[];
  activeCases: number;
  pathways: string[];
}

export interface DepartmentInfo {
  key: string;
  label: string;
  color: string;
  icon: string;
  description: string;
  units: UnitInfo[];
  activeCases: number;
  todayEncounters: number;
  avgWaitMinutes: number;
}

const ALL_ENCOUNTERS: EncounterType[] = ['outpatient','emergency','inpatient','ward_round','follow_up','procedure','operative_note','icu_review','telemedicine','antenatal','post_op','discharge_summary','referral','mdt_review'];

const FULL_HISTORY_TYPE: EncounterTypeInfo = { type: 'full_history' as any, label: 'Full History', icon: '📋', color: '#6366f1', activeCases: 0 };

function pickEncounters(ids: EncounterType[]): EncounterTypeInfo[] {
  return ids.map(type => ({ type, ...ENCOUNTER_LABELS[type], activeCases: 0 }));
}

function withFullHistory(arr: EncounterTypeInfo[]): EncounterTypeInfo[] {
  return [...arr, FULL_HISTORY_TYPE];
}

export const WORKSPACE_DATA: DepartmentInfo[] = [
  {
    key: 'PAED', ...DEPARTMENTS.PAED,
    description: 'Comprehensive paediatric care from neonate to adolescent with sub-specialty units.',
    activeCases: 24, todayEncounters: 47, avgWaitMinutes: 18,
    units: [
      { id: 'paediatric-respiratory', label: 'Paediatric Respiratory Unit', description: 'Cough, wheeze, respiratory distress, TB, asthma, bronchiolitis', icon: '🫁', activeCases: 8, pathways: ['severe-pneumonia'],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','emergency','inpatient','ward_round','follow_up'])) },
      { id: 'paediatric-cardiology', label: 'Paediatric Cardiology', description: 'Congenital heart disease, murmurs, heart failure', icon: '❤️', activeCases: 5, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','ward_round','follow_up'])) },
      { id: 'neonatology', label: 'Neonatology Unit', description: 'Newborn care, prematurity, NICU, neonatal jaundice', icon: '👶', activeCases: 12, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['inpatient','ward_round','icu_review','discharge_summary'])) },
      { id: 'paediatric-emergency', label: 'Paediatric Emergency', description: 'Acute presentations, trauma, poisoning, resuscitation', icon: '🚨', activeCases: 7, pathways: ['severe-pneumonia'],
        encounterTypes: withFullHistory(pickEncounters(['emergency','procedure','referral'])) },
      { id: 'paediatric-infectious', label: 'Paediatric Infectious Disease', description: 'Febrile illness, sepsis, meningitis, tropical infections', icon: '🦠', activeCases: 4, pathways: ['sepsis'],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','ward_round','mdt_review'])) },
      { id: 'paediatric-gastroenterology', label: 'Paediatric Gastroenterology', description: 'GI disorders, feeding problems, IBD, malnutrition', icon: '🩺', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','procedure','follow_up'])) },
      { id: 'paediatric-neurology', label: 'Paediatric Neurology', description: 'Epilepsy, developmental delay, headache, cerebral palsy', icon: '🧠', activeCases: 4, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','follow_up'])) },
      { id: 'paediatric-nephrology', label: 'Paediatric Nephrology', description: 'CKD, nephrotic syndrome, UTIs, glomerulonephritis', icon: '💧', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','follow_up'])) },
      { id: 'paediatric-hematology', label: 'Paediatric Haematology', description: 'Sickle cell, thalassaemia, anaemia, bleeding disorders', icon: '🩸', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','follow_up'])) },
      { id: 'paediatric-oncology', label: 'Paediatric Oncology', description: 'Childhood cancers, leukaemia, lymphoma, solid tumours', icon: '⚕️', activeCases: 5, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','ward_round','mdt_review'])) },
      { id: 'paediatric-endocrinology', label: 'Paediatric Endocrinology', description: 'Growth, puberty, diabetes, thyroid, DKA', icon: '🔬', activeCases: 3, pathways: ['dka'],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
      { id: 'picu-nicu', label: 'PICU/NICU', description: 'Neonatal & paediatric intensive care, respiratory failure, shock', icon: '💓', activeCases: 4, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['inpatient','icu_review','ward_round'])) },
      { id: 'developmental-pediatrics', label: 'Developmental Pediatrics', description: 'Autism, ADHD, learning disabilities, developmental delay', icon: '🌟', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
    ],
  },
  {
    key: 'SURG', ...DEPARTMENTS.SURG,
    description: 'Surgery: acute care, elective surgery, trauma, and post-operative management.',
    activeCases: 18, todayEncounters: 35, avgWaitMinutes: 25,
    units: [
      { id: 'acute-care-surgery', label: 'Acute Care Surgery', description: 'Acute abdomen, appendicitis, cholecystitis, perforation', icon: '🚑', activeCases: 4, pathways: ['acute-abdomen'],
        encounterTypes: withFullHistory(pickEncounters(['emergency','inpatient','ward_round','operative_note'])) },
      { id: 'upper-gi-surgery', label: 'Upper GI Surgery', description: 'Gastric cancer, oesophageal reflux surgery', icon: '🫁', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','operative_note','post_op','mdt_review'])) },
      { id: 'colorectal-surgery', label: 'Colorectal Surgery', description: 'Colon/rectal cancer, IBD surgery, stoma care', icon: '🩺', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','operative_note','post_op','mdt_review'])) },
      { id: 'hepatobiliary-surgery', label: 'Hepatobiliary Surgery', description: 'Pancreatic cancer, liver metastasis, bile duct surgery', icon: '🔬', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','operative_note','mdt_review'])) },
      { id: 'hernia-surgery', label: 'Hernia Surgery', description: 'Inguinal, femoral, incisional hernia repair', icon: '🔧', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','operative_note','post_op'])) },
      { id: 'breast-surgery', label: 'Breast Surgery', description: 'Breast cancer, mastectomy, lumpectomy', icon: '⚕️', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','operative_note','post_op','mdt_review'])) },
      { id: 'endocrine-surgery', label: 'Endocrine Surgery', description: 'Thyroidectomy, parathyroidectomy', icon: '🔬', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','operative_note','post_op'])) },
      { id: 'trauma-surgery', label: 'Trauma Surgery', description: 'Penetrating injury, blunt trauma, haemorrhage control', icon: '🚨', activeCases: 1, pathways: ['polytrauma'],
        encounterTypes: withFullHistory(pickEncounters(['emergency','inpatient','operative_note','ward_round'])) },
      { id: 'vascular-surgery', label: 'Vascular Surgery', description: 'Peripheral arterial disease, AAA repair', icon: '🩸', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','operative_note','post_op'])) },
      { id: 'surgical-infection', label: 'Surgical Infection Unit', description: 'Necrotising fasciitis, infected wounds', icon: '🦠', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['inpatient','ward_round','procedure'])) },
      { id: 'surgical-hdu', label: 'Surgical High Dependency Unit', description: 'Post-operative monitoring, step-down care', icon: '💓', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['inpatient','ward_round','icu_review'])) },
      { id: 'lbo-intelligence', label: 'Large Bowel Obstruction (LBO) Unit', description: 'LBO clinical reasoning, scoring, management, and operative decision support', icon: '🔪', activeCases: 0, pathways: ['acute-abdomen'],
        encounterTypes: withFullHistory(pickEncounters(['emergency','inpatient','operative_note','ward_round','discharge_summary','mdt_review'])) },
    ],
  },
  {
    key: 'CARD', ...DEPARTMENTS.CARD,
    description: 'Cardiology: coronary artery disease, heart failure, arrhythmias, hypertension.',
    activeCases: 22, todayEncounters: 40, avgWaitMinutes: 20,
    units: [
      { id: 'cardiology-general', label: 'General Cardiology', description: 'Chest pain, palpitations, dyspnoea, murmur', icon: '❤️', activeCases: 4, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','ward_round','follow_up'])) },
      { id: 'cad-ischaemia', label: 'Coronary Artery Disease', description: 'ACS, angina, post-MI care, revascularisation', icon: '🫀', activeCases: 5, pathways: ['acute-coronary-syndrome'],
        encounterTypes: withFullHistory(pickEncounters(['emergency','inpatient','ward_round','operative_note','follow_up'])) },
      { id: 'heart-failure', label: 'Heart Failure Service', description: 'HFrEF, HFpEF, pulmonary oedema, LVAD', icon: '💓', activeCases: 4, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','ward_round','follow_up'])) },
      { id: 'ep-arrhythmia', label: 'Electrophysiology & Arrhythmia', description: 'AF, SVT, ventricular tachycardia, pacemaker', icon: '⚡', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','procedure','follow_up'])) },
      { id: 'valvular-heart-disease', label: 'Valvular Heart Disease', description: 'Aortic stenosis, mitral regurgitation, endocarditis', icon: '🔬', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','operative_note','post_op'])) },
      { id: 'cardiomyopathy', label: 'Cardiomyopathy Service', description: 'Dilated, hypertrophic, restrictive cardiomyopathy', icon: '💪', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','ward_round'])) },
      { id: 'hypertension-clinic', label: 'Hypertension Clinic', description: 'Primary/secondary hypertension, resistant hypertension', icon: '📊', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','telemedicine','follow_up'])) },
      { id: 'pericardial-vascular', label: 'Pericardial & Vascular', description: 'Pericarditis, pericardial effusion, aortic dissection', icon: '🫁', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['emergency','inpatient','ward_round'])) },
    ],
  },
  {
    key: 'RESP', ...DEPARTMENTS.RESP,
    description: 'Respiratory medicine: airways disease, respiratory infections, pleural disease.',
    activeCases: 15, todayEncounters: 30, avgWaitMinutes: 16,
    units: [
      { id: 'pulmonology', label: 'Pulmonology', description: 'COPD, asthma, bronchiectasis, ILD', icon: '🫁', activeCases: 5, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','ward_round','follow_up'])) },
      { id: 'respiratory-infections', label: 'Respiratory Infections', description: 'Pneumonia, TB, empyema, COVID-19', icon: '🦠', activeCases: 4, pathways: ['severe-pneumonia'],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','emergency','inpatient','ward_round'])) },
      { id: 'pleural-disease', label: 'Pleural Disease', description: 'Pleural effusion, pneumothorax, mesothelioma', icon: '🔬', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','procedure','follow_up'])) },
      { id: 'respiratory-failure', label: 'Respiratory Failure Unit', description: 'Type 1 & 2 respiratory failure, NIV, weaning', icon: '💓', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['inpatient','ward_round','icu_review'])) },
      { id: 'sleep-resp', label: 'Sleep & Ventilation', description: 'Sleep apnoea, CPAP, home ventilation', icon: '🌙', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','telemedicine','follow_up'])) },
    ],
  },
  {
    key: 'RENAL', ...DEPARTMENTS.RENAL,
    description: 'Nephrology: CKD, dialysis, glomerular disease, electrolyte disorders.',
    activeCases: 12, todayEncounters: 22, avgWaitMinutes: 14,
    units: [
      { id: 'renal-general', label: 'General Nephrology', description: 'CKD, AKI, hypertension, urinalysis', icon: '💧', activeCases: 4, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','ward_round','follow_up'])) },
      { id: 'glomerular-disease', label: 'Glomerular Disease', description: 'Nephrotic syndrome, glomerulonephritis, vasculitis', icon: '🔬', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','follow_up','mdt_review'])) },
      { id: 'dialysis', label: 'Dialysis Service', description: 'Haemodialysis, peritoneal dialysis, access', icon: '🔄', activeCases: 4, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','ward_round'])) },
      { id: 'electrolytes-transplant', label: 'Electrolytes & Transplant', description: 'Hyponatraemia, hyperkalaemia, renal transplant', icon: '🩸', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','ward_round','telemedicine'])) },
    ],
  },
  {
    key: 'ENDO', ...DEPARTMENTS.ENDO,
    description: 'Endocrinology: diabetes, thyroid, adrenal, pituitary, bone metabolism.',
    activeCases: 10, todayEncounters: 18, avgWaitMinutes: 12,
    units: [
      { id: 'diabetes', label: 'Diabetes Service', description: 'DKA, HHS, type 1 & 2 diabetes, insulin pump', icon: '🩸', activeCases: 4, pathways: ['dka'],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','ward_round','follow_up','telemedicine'])) },
      { id: 'thyroid-clinic', label: 'Thyroid Clinic', description: 'Hyperthyroidism, hypothyroidism, nodules, cancer', icon: '🔬', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
      { id: 'adrenal-pituitary', label: 'Adrenal & Pituitary', description: 'Adrenal insufficiency, Cushing, pituitary tumours', icon: '🧠', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','follow_up'])) },
      { id: 'bone-calcium', label: 'Bone & Calcium Metabolism', description: 'Osteoporosis, hypocalcaemia, hypercalcaemia, Paget', icon: '🦴', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','telemedicine','follow_up'])) },
    ],
  },
  {
    key: 'NEURO', ...DEPARTMENTS.NEURO,
    description: 'Neurology: stroke, epilepsy, headache, movement disorders, neuromuscular.',
    activeCases: 14, todayEncounters: 28, avgWaitMinutes: 22,
    units: [
      { id: 'stroke', label: 'Stroke Service', description: 'Acute stroke, TIA, thrombolysis, rehabilitation', icon: '🧠', activeCases: 4, pathways: ['stroke'],
        encounterTypes: withFullHistory(pickEncounters(['emergency','inpatient','ward_round','follow_up','mdt_review'])) },
      { id: 'epilepsy', label: 'Epilepsy Service', description: 'Seizure disorders, EEG, status epilepticus', icon: '⚡', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','follow_up','telemedicine'])) },
      { id: 'headache', label: 'Headache Clinic', description: 'Migraine, tension headache, cluster headache', icon: '🤕', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','telemedicine','follow_up'])) },
      { id: 'neurodegenerative', label: 'Neurodegenerative Disorders', description: 'Parkinson, Alzheimer, MND, MS', icon: '🔬', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','ward_round','follow_up'])) },
      { id: 'neuroimmunology', label: 'Neuroimmunology', description: 'Multiple sclerosis, neuromyelitis optica', icon: '🔬', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','follow_up'])) },
      { id: 'cns-infections', label: 'CNS Infections', description: 'Meningitis, encephalitis, cerebral abscess', icon: '🦠', activeCases: 1, pathways: ['sepsis'],
        encounterTypes: withFullHistory(pickEncounters(['emergency','inpatient','ward_round'])) },
      { id: 'neuromuscular', label: 'Neuromuscular Disorders', description: 'GBS, myasthenia gravis, muscular dystrophy', icon: '💪', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','follow_up'])) },
      { id: 'movement-disorders', label: 'Movement Disorders', description: 'Deep brain stimulation, dystonia, tremor', icon: '🔄', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
      { id: 'neuro-oncology', label: 'Neuro-Oncology', description: 'Brain tumours, spinal cord tumours', icon: '⚕️', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','mdt_review'])) },
      { id: 'general-neurology', label: 'General Neurology', description: 'Dizziness, neuropathy, general neurology consults', icon: '🧠', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up'])) },
    ],
  },
  {
    key: 'GI', ...DEPARTMENTS.GI,
    description: 'Gastroenterology: luminal GI, hepatology, pancreatic-biliary disorders.',
    activeCases: 11, todayEncounters: 20, avgWaitMinutes: 15,
    units: [
      { id: 'gi-general', label: 'General Gastroenterology', description: 'GERD, dyspepsia, IBS, dysphagia', icon: '🩺', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
      { id: 'hepatology', label: 'Hepatology', description: 'Hepatitis B/C, cirrhosis, liver failure, ascites', icon: '🔬', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','ward_round','follow_up'])) },
      { id: 'oesophageal-gastric', label: 'Oesophageal & Gastric', description: 'Bleeding ulcer, variceal bleed, gastric cancer', icon: '🚨', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['emergency','inpatient','procedure','follow_up'])) },
      { id: 'pancreatic-biliary', label: 'Pancreatic & Biliary', description: 'Pancreatitis, bile duct stones, pancreatic cancer', icon: '💧', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['emergency','inpatient','procedure','follow_up'])) },
    ],
  },
  {
    key: 'OB', ...DEPARTMENTS.OB,
    description: 'Obstetrics: antenatal, high-risk pregnancy, labour, postnatal care.',
    activeCases: 20, todayEncounters: 38, avgWaitMinutes: 10,
    units: [
      { id: 'antenatal', label: 'Antenatal Clinic', description: 'Routine antenatal care, screening, ultrasound', icon: '👶', activeCases: 8, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','antenatal','telemedicine'])) },
      { id: 'high-risk-pregnancy', label: 'High-Risk Pregnancy', description: 'PET, GDM, IUGR, previa, multiple pregnancy', icon: '🔬', activeCases: 4, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','antenatal','inpatient','ward_round'])) },
      { id: 'labour-delivery', label: 'Labour & Delivery', description: 'Normal & assisted delivery, induction, C-section', icon: '🚑', activeCases: 4, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['emergency','inpatient','operative_note','post_op'])) },
      { id: 'postnatal', label: 'Postnatal Ward', description: 'Mother-baby care, breastfeeding, postpartum complications', icon: '🤱', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['inpatient','ward_round','follow_up'])) },
      { id: 'fetal-medicine', label: 'Fetal Medicine', description: 'Fetal anomalies, invasive testing, fetal therapy', icon: '🔬', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','procedure','mdt_review'])) },
      { id: 'obstetric-surgery', label: 'Obstetric Surgery', description: 'C-section complications, postpartum haemorrhage', icon: '🔪', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['emergency','inpatient','operative_note','post_op'])) },
    ],
  },
  {
    key: 'GYN', ...DEPARTMENTS.GYN,
    description: 'Gynaecology: general gynaecology, oncology, fertility, urogynaecology.',
    activeCases: 12, todayEncounters: 22, avgWaitMinutes: 14,
    units: [
      { id: 'general-gyn', label: 'General Gynaecology', description: 'Menstrual disorders, pelvic pain, screening', icon: '🌸', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
      { id: 'gyn-infections', label: 'Gynaecology Infections', description: 'STIs, PID, vaginal discharge, Bartholin', icon: '🦠', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','procedure','follow_up'])) },
      { id: 'gyn-oncology', label: 'Gynaecological Oncology', description: 'Ovarian, cervical, endometrial cancer', icon: '⚕️', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','operative_note','mdt_review'])) },
      { id: 'gyn-surgery', label: 'Gynaecological Surgery', description: 'Hysterectomy, myomectomy, laparoscopy', icon: '🔪', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','operative_note','post_op'])) },
      { id: 'fertility', label: 'Fertility Service', description: 'Subfertility, IVF, ovulation induction', icon: '🌟', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
      { id: 'menopause-urogyn', label: 'Menopause & Urogynaecology', description: 'Menopause, prolapse, incontinence', icon: '🔄', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
    ],
  },
  {
    key: 'RHEUM', ...DEPARTMENTS.RHEUM,
    description: 'Rheumatology: inflammatory arthritis, connective tissue disease, vasculitis.',
    activeCases: 8, todayEncounters: 16, avgWaitMinutes: 20,
    units: [
      { id: 'inflammatory-arthritis', label: 'Inflammatory Arthritis', description: 'RA, AS, psoriatic arthritis, gout', icon: '🦴', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','follow_up'])) },
      { id: 'connective-tissue', label: 'Connective Tissue Disease', description: 'SLE, scleroderma, Sjögren, mixed CTD', icon: '🔬', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','ward_round','follow_up'])) },
      { id: 'vasculitis', label: 'Vasculitis Service', description: 'ANCA vasculitis, giant cell arteritis', icon: '🩸', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','follow_up'])) },
      { id: 'rheum-infusion', label: 'Rheumatology Infusion Unit', description: 'Biologics, rituximab, tocilizumab', icon: '💉', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','procedure'])) },
      { id: 'degenerative-rheum', label: 'Degenerative & Soft Tissue', description: 'Osteoarthritis, tendinopathy, fibromyalgia', icon: '💪', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','telemedicine','follow_up'])) },
    ],
  },
  {
    key: 'HAEM', ...DEPARTMENTS.HAEM,
    description: 'Haematology: blood disorders, haem-onc, coagulation, transfusion.',
    activeCases: 9, todayEncounters: 18, avgWaitMinutes: 18,
    units: [
      { id: 'haem-general', label: 'General Haematology', description: 'Anaemia, polycythaemia, thrombocytopenia, cytopenia', icon: '🩸', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
      { id: 'haem-onc', label: 'Haematological Oncology', description: 'Leukaemia, lymphoma, myeloma, transplant', icon: '⚕️', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','ward_round','mdt_review'])) },
      { id: 'coagulation', label: 'Coagulation & Thrombosis', description: 'VTE, DIC, haemophilia, anticoagulation', icon: '🩸', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','follow_up'])) },
      { id: 'transfusion', label: 'Transfusion Medicine', description: 'Blood component therapy, transfusion reactions', icon: '💉', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','telemedicine'])) },
    ],
  },
  {
    key: 'ONCO', ...DEPARTMENTS.ONCO,
    description: 'Oncology: medical oncology, solid tumours, radiation, emergencies.',
    activeCases: 14, todayEncounters: 28, avgWaitMinutes: 30,
    units: [
      { id: 'medical-oncology', label: 'Medical Oncology', description: 'Chemotherapy, targeted therapy, immunotherapy', icon: '⚕️', activeCases: 4, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','ward_round','mdt_review'])) },
      { id: 'solid-tumour', label: 'Solid Tumour Clinic', description: 'Breast, lung, colon, prostate cancer', icon: '🔬', activeCases: 4, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','mdt_review'])) },
      { id: 'haem-onc-onco', label: 'Haematology-Oncology', description: 'Leukaemia, lymphoma, stem cell transplant', icon: '🩸', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','ward_round','mdt_review'])) },
      { id: 'radiation-oncology', label: 'Radiation Oncology', description: 'Radiotherapy planning, brachytherapy', icon: '📡', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','procedure','follow_up'])) },
      { id: 'oncology-emergencies', label: 'Oncology Emergencies', description: 'Febrile neutropenia, SVC syndrome, cord compression', icon: '🚨', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['emergency','inpatient','ward_round'])) },
    ],
  },
  {
    key: 'GERI', ...DEPARTMENTS.GERI,
    description: 'Geriatric medicine: acute geriatrics, dementia, falls, frailty, rehabilitation.',
    activeCases: 16, todayEncounters: 30, avgWaitMinutes: 20,
    units: [
      { id: 'geri-acute', label: 'Acute Geriatrics Ward', description: 'Acute illness in older adults, delirium, falls, syncope', icon: '👴', activeCases: 5, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['emergency','inpatient','ward_round','discharge_summary'])) },
      { id: 'cognition-dementia', label: 'Cognition & Dementia Service', description: 'Dementia, mild cognitive impairment, delirium assessment', icon: '🧠', activeCases: 4, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','mdt_review','follow_up'])) },
      { id: 'falls-mobility', label: 'Falls & Mobility Clinic', description: 'Recurrent falls, gait disorders, hip fracture, sarcopenia', icon: '🏃', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','follow_up'])) },
      { id: 'frailty-complex-care', label: 'Frailty & Complex Care', description: 'Frailty syndrome, polypharmacy, malnutrition, pressure ulcers', icon: '🔄', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','mdt_review','follow_up'])) },
      { id: 'geri-rehab', label: 'Geriatric Rehabilitation', description: 'Post-fracture rehab, deconditioning, comprehensive geriatric assessment', icon: '💪', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['inpatient','ward_round','follow_up','mdt_review'])) },
    ],
  },
  {
    key: 'EM', ...DEPARTMENTS.EM,
    description: 'Emergency medicine: resuscitation, trauma, medical & surgical emergencies.',
    activeCases: 28, todayEncounters: 55, avgWaitMinutes: 5,
    units: [
      { id: 'resus', label: 'Resuscitation Room', description: 'Cardiac arrest, anaphylaxis, shock, airway emergencies', icon: '🚨', activeCases: 5, pathways: ['sepsis','acute-coronary-syndrome'],
        encounterTypes: withFullHistory(pickEncounters(['emergency','procedure'])) },
      { id: 'majors', label: 'Majors', description: 'Medical emergencies, SOB, chest pain, sepsis', icon: '🏥', activeCases: 8, pathways: ['sepsis','acute-coronary-syndrome'],
        encounterTypes: withFullHistory(pickEncounters(['emergency','referral'])) },
      { id: 'trauma-resus', label: 'Trauma Resuscitation', description: 'Polytrauma, head injury, haemorrhage control', icon: '🚑', activeCases: 3, pathways: ['polytrauma'],
        encounterTypes: withFullHistory(pickEncounters(['emergency','procedure'])) },
      { id: 'toxicology', label: 'Toxicology & OD', description: 'Poisoning, overdose, substance abuse emergencies', icon: '☠️', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['emergency','inpatient','referral'])) },
      { id: 'respiratory-emerg', label: 'Respiratory Emergencies', description: 'Acute asthma, COPD exacerbation, PE, airway', icon: '🫁', activeCases: 4, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['emergency','referral'])) },
      { id: 'neuro-emerg', label: 'Neurological Emergencies', description: 'Stroke, seizure, reduced GCS, status epilepticus', icon: '🧠', activeCases: 3, pathways: ['stroke'],
        encounterTypes: withFullHistory(pickEncounters(['emergency','referral'])) },
      { id: 'minors', label: 'Minors / Fast Track', description: 'Minor injuries, lacerations, abscess, URTI', icon: '🩹', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['emergency','procedure'])) },
    ],
  },
  {
    key: 'IM', ...DEPARTMENTS.IM,
    description: 'Adult internal medicine covering general medicine, ID, rheumatology.',
    activeCases: 31, todayEncounters: 58, avgWaitMinutes: 22,
    units: [
      { id: 'general-internal', label: 'General Internal Medicine', description: 'Complex multisystem disease, acute medical take', icon: '🏥', activeCases: 8, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['emergency','inpatient','ward_round','follow_up'])) },
      { id: 'hypertension-im', label: 'Hypertension Service', description: 'Resistant hypertension, secondary HTN workup', icon: '📊', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','telemedicine','follow_up'])) },
      { id: 'infectious-disease-im', label: 'Infectious Disease', description: 'Complex infections, sepsis, HIV, TB, OPAT', icon: '🦠', activeCases: 2, pathways: ['sepsis'],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','ward_round'])) },
      { id: 'allergy-immunology', label: 'Allergy & Immunology', description: 'Anaphylaxis, drug allergy, urticaria, immunodeficiency', icon: '🔬', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
      { id: 'vaccination-travel', label: 'Vaccination & Travel', description: 'Travel advice, routine vaccinations, post-exposure', icon: '💉', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','telemedicine'])) },
    ],
  },
  {
    key: 'PSYCH', ...DEPARTMENTS.PSYCH,
    description: 'Psychiatry: mood disorders, anxiety, psychosis, child, addiction, emergency.',
    activeCases: 18, todayEncounters: 34, avgWaitMinutes: 25,
    units: [
      { id: 'mood-disorders', label: 'Mood Disorders Clinic', description: 'Major depressive disorder, bipolar disorder, persistent depressive disorder', icon: '💬', activeCases: 4, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
      { id: 'anxiety-disorders', label: 'Anxiety & Stress Disorders', description: 'Generalised anxiety, panic disorder, social anxiety, OCD, PTSD', icon: '😰', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
      { id: 'psychotic-disorders', label: 'Psychotic Disorders Service', description: 'Schizophrenia, schizoaffective disorder, brief psychotic disorder', icon: '🧠', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','follow_up'])) },
      { id: 'child-adolescent', label: 'Child & Adolescent Service', description: 'ADHD, autism, conduct disorder, behavioural disorders', icon: '👦', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
      { id: 'addiction', label: 'Addiction Services', description: 'Alcohol, opioid, cannabis use disorders, detox, rehabilitation', icon: '🔄', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','follow_up'])) },
      { id: 'personality-disorders', label: 'Personality Disorders Service', description: 'Borderline personality, antisocial personality disorder', icon: '🔬', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
      { id: 'eating-disorders', label: 'Eating Disorders Service', description: 'Anorexia nervosa, bulimia nervosa', icon: '⚖️', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','follow_up'])) },
      { id: 'emergency-psychiatry', label: 'Emergency Psychiatry', description: 'Suicide risk, acute psychosis, agitation, crisis intervention', icon: '🚨', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['emergency','inpatient','referral'])) },
      { id: 'sleep-disorders-psych', label: 'Sleep Disorders Clinic', description: 'Insomnia, narcolepsy, parasomnias', icon: '🌙', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','telemedicine','follow_up'])) },
      { id: 'general-psychiatry', label: 'General Psychiatry Outpatient', description: 'General psychiatric assessments and follow-up', icon: '💬', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
    ],
  },
  {
    key: 'ORTHO', ...DEPARTMENTS.ORTHO,
    description: 'Orthopaedics: trauma, sports, degenerative, spine, infections, tumours.',
    activeCases: 14, todayEncounters: 28, avgWaitMinutes: 20,
    units: [
      { id: 'trauma-ortho', label: 'Orthopaedic Trauma', description: 'Fractures of limbs, hip, spine, pelvis; polytrauma orthopaedic management', icon: '🦴', activeCases: 4, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['emergency','inpatient','operative_note','post_op','ward_round'])) },
      { id: 'sports-medicine', label: 'Sports Medicine & Arthroscopy', description: 'ACL tear, meniscal tear, rotator cuff tear, ankle sprain', icon: '⚽', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','operative_note','post_op','follow_up'])) },
      { id: 'degenerative-ortho', label: 'Degenerative Joint Disease', description: 'Osteoarthritis knee/hip, joint replacement, spondylosis', icon: '🦴', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','operative_note','post_op','follow_up'])) },
      { id: 'spine-surgery', label: 'Spine Surgery', description: 'Disc herniation, spinal stenosis, scoliosis, cauda equina syndrome', icon: '🔬', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','operative_note','ward_round'])) },
      { id: 'ortho-infections', label: 'Orthopaedic Infections', description: 'Septic arthritis, osteomyelitis, prosthetic joint infection', icon: '🦠', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['emergency','inpatient','operative_note'])) },
      { id: 'ortho-tumors', label: 'Orthopaedic Oncology', description: 'Osteosarcoma, Ewing sarcoma, bone tumours', icon: '⚕️', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','operative_note','mdt_review'])) },
      { id: 'pediatric-ortho', label: 'Paediatric Orthopaedics', description: 'Clubfoot, DDH, Legg-Calve-Perthes, paediatric fractures', icon: '👶', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','operative_note','follow_up'])) },
      { id: 'post-op-ortho', label: 'Orthopaedic Post-Operative Care', description: 'Periprosthetic fracture, wound complications, rehabilitation', icon: '💪', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['inpatient','ward_round','post_op','follow_up'])) },
      { id: 'general-ortho', label: 'General Orthopaedics Clinic', description: 'General orthopaedic assessments, fracture follow-up', icon: '🦴', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
    ],
  },
  {
    key: 'DERM', ...DEPARTMENTS.DERM,
    description: 'Dermatology: inflammatory, infections, skin cancer, autoimmune, wound care.',
    activeCases: 10, todayEncounters: 20, avgWaitMinutes: 25,
    units: [
      { id: 'inflammatory-derm', label: 'Inflammatory Dermatology', description: 'Eczema, psoriasis, lichen planus, seborrhoeic dermatitis', icon: '🩹', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
      { id: 'derm-infections', label: 'Skin Infections', description: 'Cellulitis, impetigo, fungal infections, herpes zoster, scabies', icon: '🦠', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','procedure','follow_up'])) },
      { id: 'skin-cancers', label: 'Skin Cancer & Mohs Surgery', description: 'Melanoma, BCC, SCC, Kaposi sarcoma, surgical excision', icon: '🔬', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','procedure','post_op'])) },
      { id: 'autoimmune-derm', label: 'Autoimmune Skin Disease', description: 'Pemphigus, bullous pemphigoid, vitiligo', icon: '🔬', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','follow_up'])) },
      { id: 'drug-reactions', label: 'Cutaneous Drug Reactions', description: 'Stevens-Johnson syndrome, TEN, drug rash', icon: '🚨', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['emergency','inpatient','ward_round'])) },
      { id: 'acne-rosacea', label: 'Acne & Rosacea Clinic', description: 'Acne vulgaris, rosacea', icon: '🩹', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
      { id: 'wound-care', label: 'Wound Care & Ulcer Management', description: 'Pressure ulcers, skin abscess, chronic wounds', icon: '🏥', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','procedure'])) },
      { id: 'general-derm', label: 'General Dermatology', description: 'General dermatology assessments and follow-up', icon: '🩹', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
    ],
  },
  {
    key: 'ENT', ...DEPARTMENTS.ENT,
    description: 'Ear, Nose & Throat: otology, rhinology, laryngology, head & neck.',
    activeCases: 8, todayEncounters: 16, avgWaitMinutes: 18,
    units: [
      { id: 'otology', label: 'Otology & Hearing', description: 'Acute otitis media, CSOM, cholesteatoma, hearing loss, mastoiditis', icon: '👂', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','operative_note','follow_up'])) },
      { id: 'rhinology', label: 'Rhinology & Sinus', description: 'Allergic rhinitis, sinusitis, nasal polyps', icon: '👃', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','procedure','follow_up'])) },
      { id: 'laryngology', label: 'Laryngology & Voice', description: 'Acute tonsillitis, peritonsillar abscess, vocal cord nodules, laryngeal cancer', icon: '🔬', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','operative_note','follow_up'])) },
      { id: 'head-neck', label: 'Head & Neck Surgery', description: 'Thyroid nodules, salivary gland tumours, neck abscess', icon: '🔪', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','operative_note','post_op'])) },
      { id: 'sleep-ent', label: 'ENT Sleep Medicine', description: 'Obstructive sleep apnoea, snoring surgery', icon: '🌙', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','telemedicine','follow_up'])) },
      { id: 'ent-emergencies', label: 'ENT Emergencies', description: 'Epistaxis, airway obstruction, foreign body nose/ear', icon: '🚨', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['emergency','procedure','inpatient'])) },
      { id: 'ent-clinic', label: 'General ENT Clinic', description: 'General ENT assessments and follow-up', icon: '👂', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
    ],
  },
  {
    key: 'OPHTH', ...DEPARTMENTS.OPHTH,
    description: 'Ophthalmology: cataract, anterior segment, glaucoma, retina, neuro-ophth.',
    activeCases: 12, todayEncounters: 24, avgWaitMinutes: 22,
    units: [
      { id: 'cataract-clinic', label: 'Cataract & Lens Service', description: 'Age-related cataract, congenital cataract', icon: '👁️', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','operative_note','post_op','follow_up'])) },
      { id: 'anterior-segment', label: 'Anterior Segment & Cornea', description: 'Conjunctivitis, keratitis, corneal ulcer, uveitis', icon: '🔬', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','procedure','follow_up'])) },
      { id: 'glaucoma', label: 'Glaucoma Service', description: 'Primary open-angle glaucoma, acute angle-closure glaucoma', icon: '🔬', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','procedure','follow_up'])) },
      { id: 'retina-vitreous', label: 'Retina & Vitreous Service', description: 'Diabetic retinopathy, retinal detachment, macular degeneration', icon: '👁️', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','operative_note','follow_up'])) },
      { id: 'neuro-ophthalmology', label: 'Neuro-Ophthalmology', description: 'Optic neuritis, papilledema, cranial nerve palsies', icon: '🧠', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','follow_up'])) },
      { id: 'ophth-trauma', label: 'Ocular Trauma', description: 'Corneal abrasion, globe injury, chemical burn', icon: '🚨', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['emergency','operative_note','follow_up'])) },
      { id: 'pediatric-ophth', label: 'Paediatric Ophthalmology', description: 'Strabismus, amblyopia, congenital cataract', icon: '👶', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','operative_note','follow_up'])) },
      { id: 'ophth-emergency', label: 'Eye Casualty', description: 'Red eye, acute vision loss, ocular trauma triage', icon: '🚨', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['emergency','referral','follow_up'])) },
    ],
  },
  {
    key: 'URO', ...DEPARTMENTS.URO,
    description: 'Urology: stone disease, prostate, bladder, renal, male reproductive, emergencies.',
    activeCases: 10, todayEncounters: 20, avgWaitMinutes: 18,
    units: [
      { id: 'stone-disease', label: 'Stone Disease Unit', description: 'Renal stones, ureteric stones, bladder stones, ESWL, PCNL', icon: '💎', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','procedure','inpatient','follow_up'])) },
      { id: 'prostate-clinic', label: 'Prostate Clinic', description: 'BPH, prostatitis, prostate cancer diagnosis and management', icon: '🔬', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','operative_note','follow_up'])) },
      { id: 'bladder-urothelial', label: 'Bladder & Urothelial Service', description: 'UTI, cystitis, bladder cancer, overactive bladder', icon: '🚽', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','procedure','follow_up'])) },
      { id: 'renal-urology', label: 'Renal & Upper Tract Urology', description: 'Renal cell carcinoma, renal cyst, hydronephrosis', icon: '💧', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','operative_note','follow_up'])) },
      { id: 'male-reproductive', label: 'Male Reproductive Health', description: 'Erectile dysfunction, testicular torsion, epididymitis, testicular cancer', icon: '🔬', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','emergency','operative_note','follow_up'])) },
      { id: 'incontinence-urogyn', label: 'Incontinence & Functional Urology', description: 'Stress incontinence, urge incontinence, neuropathic bladder', icon: '🔄', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
      { id: 'uro-emergencies', label: 'Urological Emergencies', description: 'Acute urinary retention, priapism, Fournier gangrene', icon: '🚨', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['emergency','inpatient','operative_note'])) },
      { id: 'uro-clinic', label: 'General Urology Clinic', description: 'General urology assessments and follow-up', icon: '🚽', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','follow_up','telemedicine'])) },
    ],
  },
  {
    key: 'ICU', ...DEPARTMENTS.ICU,
    description: 'Critical care: respiratory, cardiovascular, neuro, sepsis, trauma, surgical ICU.',
    activeCases: 20, todayEncounters: 40, avgWaitMinutes: 5,
    units: [
      { id: 'icu-respiratory', label: 'Respiratory ICU', description: 'ARDS, status asthmaticus, ventilator-associated pneumonia, respiratory weaning', icon: '🫁', activeCases: 4, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['icu_review','ward_round','inpatient'])) },
      { id: 'icu-cardiovascular', label: 'Cardiovascular ICU', description: 'Cardiogenic shock, septic shock, haemorrhagic shock, post-cardiac surgery', icon: '❤️', activeCases: 4, pathways: ['sepsis'],
        encounterTypes: withFullHistory(pickEncounters(['icu_review','ward_round','inpatient'])) },
      { id: 'icu-neuro', label: 'Neuro ICU', description: 'Raised ICP, myasthenic crisis, brain death, post-neurosurgery', icon: '🧠', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['icu_review','ward_round'])) },
      { id: 'icu-sepsis', label: 'Sepsis & Multi-Organ Failure ICU', description: 'Sepsis bundle, multiorgan dysfunction, haemodynamic monitoring', icon: '🦠', activeCases: 3, pathways: ['sepsis'],
        encounterTypes: withFullHistory(pickEncounters(['icu_review','ward_round','inpatient'])) },
      { id: 'icu-trauma', label: 'Trauma ICU', description: 'Damage control resuscitation, massive transfusion, polytrauma', icon: '🚑', activeCases: 2, pathways: ['polytrauma'],
        encounterTypes: withFullHistory(pickEncounters(['icu_review','ward_round','post_op'])) },
      { id: 'icu-surgical', label: 'Surgical ICU', description: 'Post-abdominal surgery, post-operative complications', icon: '🔪', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['icu_review','ward_round','post_op'])) },
      { id: 'icu-renal', label: 'Renal ICU', description: 'Acute kidney injury in ICU, electrolyte emergencies, CRRT', icon: '💧', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['icu_review','ward_round'])) },
      { id: 'icu-procedures', label: 'ICU Procedures & Lines', description: 'Central line, arterial line, bronchoscopy, tracheostomy care', icon: '💉', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['icu_review','procedure'])) },
      { id: 'icu-medical', label: 'General Medical ICU', description: 'General medical critical care', icon: '💓', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['icu_review','ward_round','inpatient'])) },
    ],
  },
  {
    key: 'ID', ...DEPARTMENTS.ID,
    description: 'Infectious disease: bacterial, viral, mycobacterial, parasitic, travel, stewardship.',
    activeCases: 12, todayEncounters: 22, avgWaitMinutes: 20,
    units: [
      { id: 'bacterial-id', label: 'Bacterial Infections', description: 'Sepsis, meningitis, typhoid, brucellosis, leptospirosis', icon: '🦠', activeCases: 3, pathways: ['sepsis'],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','ward_round','mdt_review'])) },
      { id: 'viral-id', label: 'Viral Infections', description: 'HIV/AIDS, hepatitis B/C, COVID-19, influenza, ebola', icon: '🦠', activeCases: 3, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','ward_round','follow_up'])) },
      { id: 'mycobacterial-id', label: 'Mycobacterial & Fungal Infections', description: 'Pulmonary/extrapulmonary TB, leprosy, candidemia, cryptococcal meningitis', icon: '🔬', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','ward_round'])) },
      { id: 'parasitic-id', label: 'Parasitic & Tropical Infections', description: 'Malaria, leishmaniasis, amebiasis, dengue', icon: '🌍', activeCases: 2, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','follow_up'])) },
      { id: 'id-travel', label: 'Travel & Tropical Medicine', description: 'Travel advice, vaccine-preventable diseases, travellers diarrhoea', icon: '🌍', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','telemedicine','follow_up'])) },
      { id: 'id-stewardship', label: 'Antimicrobial Stewardship', description: 'Antibiotic review, OPAT, resistance management, C. difficile', icon: '💊', activeCases: 1, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','telemedicine','mdt_review'])) },
      { id: 'id-general', label: 'General Infectious Diseases', description: 'Complex infections, fever of unknown origin, general ID consults', icon: '🦠', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','ward_round'])) },
    ],
  },
  {
    key: 'RAD', ...DEPARTMENTS.RAD,
    description: 'Radiology: diagnostic imaging, interventional radiology, radiation safety.',
    activeCases: 0, todayEncounters: 0, avgWaitMinutes: 0,
    units: [
      { id: 'neuro-imaging', label: 'Neuroimaging', description: 'Stroke imaging, brain tumour imaging, head trauma', icon: '🧠', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','emergency','telemedicine'])) },
      { id: 'chest-imaging', label: 'Chest Imaging', description: 'Pneumonia radiology, PE imaging, lung cancer screening', icon: '🫁', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','emergency','telemedicine'])) },
      { id: 'abdominal-imaging', label: 'Abdominal Imaging', description: 'Acute abdomen imaging, liver mass, renal mass', icon: '🏥', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','emergency','telemedicine'])) },
      { id: 'msk-imaging', label: 'MSK Imaging', description: 'Fracture characterisation, bone tumour radiology', icon: '🦴', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','emergency','telemedicine'])) },
      { id: 'interventional-rad', label: 'Interventional Radiology', description: 'Biopsy guidance, drainage procedures, angiography', icon: '🔬', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','procedure'])) },
      { id: 'critical-findings', label: 'Critical Findings Reporting', description: 'Free air, tension pneumothorax, urgent findings', icon: '🚨', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['emergency','telemedicine'])) },
    ],
  },
  {
    key: 'LAB', ...DEPARTMENTS.LAB,
    description: 'Laboratory Medicine: clinical chemistry, haematology, microbiology, transfusion.',
    activeCases: 0, todayEncounters: 0, avgWaitMinutes: 0,
    units: [
      { id: 'lab-haematology', label: 'Haematology Lab', description: 'Anaemia workup, leukaemia diagnostics, coagulation screening', icon: '🩸', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','telemedicine'])) },
      { id: 'lab-chemistry', label: 'Clinical Chemistry', description: 'Renal function, liver function, cardiac markers, electrolyte analysis', icon: '🧪', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','telemedicine'])) },
      { id: 'lab-microbiology', label: 'Microbiology', description: 'Blood culture interpretation, urine culture, gram stain guide', icon: '🦠', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','telemedicine'])) },
      { id: 'transfusion-lab', label: 'Transfusion Medicine', description: 'Blood grouping, cross-matching, transfusion reaction workup', icon: '💉', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['inpatient','emergency','telemedicine'])) },
      { id: 'point-of-care', label: 'Point-of-Care Testing', description: 'ABG interpretation, glucose monitoring, rapid diagnostics', icon: '📊', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['emergency','inpatient','telemedicine'])) },
    ],
  },
  {
    key: 'PHARM', ...DEPARTMENTS.PHARM,
    description: 'Pharmacy: medication management, TDM, antimicrobial stewardship, drug safety.',
    activeCases: 0, todayEncounters: 0, avgWaitMinutes: 0,
    units: [
      { id: 'drug-interactions', label: 'Drug Interactions', description: 'Warfarin interactions, antiretroviral interactions, antibiotic interactions', icon: '💊', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['outpatient','inpatient','telemedicine'])) },
      { id: 'therapeutic-drug-monitoring', label: 'Therapeutic Drug Monitoring', description: 'Vancomycin dosing, aminoglycoside dosing, phenytoin monitoring', icon: '📊', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['inpatient','telemedicine'])) },
      { id: 'adverse-drug-reactions', label: 'Adverse Drug Reactions', description: 'Stevens-Johnson syndrome, drug-induced liver injury, allergy assessment', icon: '🚨', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['inpatient','emergency','telemedicine'])) },
      { id: 'antimicrobial-stewardship-pharm', label: 'Antimicrobial Stewardship', description: 'Empiric antibiotic guide, antifungal selection, resistance management', icon: '🦠', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['inpatient','telemedicine','mdt_review'])) },
      { id: 'high-alert-medications', label: 'High-Alert Medications', description: 'Insulin safety, anticoagulation safety, chemotherapy safety', icon: '⚠️', activeCases: 0, pathways: [],
        encounterTypes: withFullHistory(pickEncounters(['inpatient','telemedicine'])) },
    ],
  },
];

export function getDepartment(key: string): DepartmentInfo | undefined {
  return WORKSPACE_DATA.find(d => d.key === key);
}

export function getUnit(deptKey: string, unitId: string): UnitInfo | undefined {
  return getDepartment(deptKey)?.units.find(u => u.id === unitId);
}

export function getDepartmentTotalActiveCases(): number {
  return WORKSPACE_DATA.reduce((sum, d) => sum + d.activeCases, 0);
}

export function getDepartmentTotalEncountersToday(): number {
  return WORKSPACE_DATA.reduce((sum, d) => sum + d.todayEncounters, 0);
}
