'use client';

import React, { useEffect, useState, useCallback } from 'react';
import { db } from '@/lib/firebase';
import {
  collection, addDoc, serverTimestamp, query, where,
  onSnapshot, orderBy, doc, updateDoc, Timestamp,
  DocumentData,
} from 'firebase/firestore';
import { writeTimelineEvent } from '@/lib/firebaseTimeline';

type AlertCategory = 'clinical' | 'operational' | 'medication' | 'lab' | 'system';
type AlertSeverity = 'info' | 'warning' | 'critical';
type AlertStatus = 'active' | 'acknowledged' | 'resolved' | 'escalated';

interface Alert {
  id?: string;
  patientId: string; patientName?: string;
  doctorId: string;
  category: AlertCategory;
  severity: AlertSeverity;
  title: string; message: string;
  status: AlertStatus;
  escalationLevel: number;
  createdBy: string; createdAt: Timestamp | any;
  acknowledgedAt?: Timestamp | any; acknowledgedBy?: string;
  resolvedAt?: Timestamp | any; resolvedBy?: string;
  linkedDocId?: string; linkedCollection?: string;
  autoGenerated?: boolean;
}

interface Props {
  patientId?: string; doctorId: string; doctorName: string;
  compact?: boolean;
}

const fmtTime = (ts: any) => {
  if (!ts) return '';
  const d = ts?.toDate ? ts.toDate() : new Date(ts);
  return d.toLocaleDateString('en-KE', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' });
};

const severityConfig: Record<AlertSeverity, { color: string; bg: string; icon: string }> = {
  info: { color: '#3b82f6', bg: '#3b82f610', icon: 'ℹ️' },
  warning: { color: '#f59e0b', bg: '#f59e0b10', icon: '⚠️' },
  critical: { color: '#ef4444', bg: '#ef444410', icon: '🚨' },
};

export default function AlertEscalationEngine({ patientId, doctorId, doctorName, compact }: Props) {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState<AlertStatus | 'all'>('active');
  const [showCompose, setShowCompose] = useState(false);
  const [formData, setFormData] = useState({ title: '', message: '', category: 'clinical' as AlertCategory, severity: 'warning' as AlertSeverity });
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    const col = collection(db, 'systemAlerts');
    const q = patientId
      ? query(col, where('patientId', '==', patientId), orderBy('createdAt', 'desc'))
      : query(col, where('doctorId', '==', doctorId), orderBy('createdAt', 'desc'));

    const unsub = onSnapshot(
      q,
      snap => { setAlerts(snap.docs.map(d => ({ id: d.id, ...(d.data() as DocumentData) } as Alert))); setLoading(false); },
      () => setLoading(false),
    );
    return () => unsub();
  }, [patientId, doctorId]);

  const displayAlerts = filter === 'all' ? alerts : alerts.filter(a => a.status === filter);
  const critical = alerts.filter(a => a.severity === 'critical' && a.status === 'active');
  const active = alerts.filter(a => a.status === 'active' || a.status === 'escalated');

  const handleAcknowledge = useCallback(async (alertId: string) => {
    await updateDoc(doc(db, 'systemAlerts', alertId), {
      status: 'acknowledged', acknowledgedAt: serverTimestamp(), acknowledgedBy: doctorId,
    });
  }, [doctorId]);

  const handleResolve = useCallback(async (alertId: string) => {
    await updateDoc(doc(db, 'systemAlerts', alertId), {
      status: 'resolved', resolvedAt: serverTimestamp(), resolvedBy: doctorId,
    });
  }, [doctorId]);

  const handleEscalate = useCallback(async (alertId: string, currentLevel: number) => {
    await updateDoc(doc(db, 'systemAlerts', alertId), {
      status: 'escalated', escalationLevel: currentLevel + 1,
    });
  }, []);

  const handleCreateAlert = useCallback(async () => {
    if (!formData.title.trim() || !formData.message.trim()) return;
    setSaving(true);
    try {
      const ref = await addDoc(collection(db, 'systemAlerts'), {
        patientId: patientId || '', doctorId, category: formData.category,
        severity: formData.severity, title: formData.title, message: formData.message,
        status: 'active', escalationLevel: 0, createdBy: doctorId,
        createdAt: serverTimestamp(), autoGenerated: false,
      });
      await writeTimelineEvent({
        patientId: patientId || '', type: 'alert_triggered',
        title: `${severityConfig[formData.severity].icon} ${formData.title}`,
        description: formData.message,
        severity: formData.severity, createdBy: doctorId,
        linkedDocId: ref.id, linkedCollection: 'systemAlerts',
      });
      setFormData({ title: '', message: '', category: 'clinical', severity: 'warning' });
      setShowCompose(false);
    } catch (e) { console.error('Create alert failed:', e); }
    setSaving(false);
  }, [formData, patientId, doctorId]);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: compact ? 8 : 12 }}>
      {/* Critical alert banner */}
      {critical.length > 0 && (
        <div style={{
          padding: compact ? 8 : 12, borderRadius: 10,
          background: '#ef444410', border: '1px solid #ef444430',
          borderLeft: '4px solid #ef4444',
        }}>
          <div style={{ fontWeight: 800, fontSize: compact ? 12 : 13, color: '#ef4444', marginBottom: 4 }}>
            🚨 {critical.length} Critical Alert{critical.length > 1 ? 's' : ''}
          </div>
          {critical.slice(0, compact ? 2 : 3).map(a => (
            <div key={a.id} style={{ fontSize: compact ? 10 : 11, color: 'var(--text-2)', marginTop: 2 }}>
              {a.title} — <span style={{ fontWeight: 600 }}>{a.message}</span>
              <button className="btn-action" style={{ fontSize: 9, padding: '2px 6px', marginLeft: 6 }}
                onClick={() => a.id && handleAcknowledge(a.id)}>
                Acknowledge
              </button>
            </div>
          ))}
        </div>
      )}

      {/* Summary bar */}
      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
        {([
          { id: 'active' as const, icon: '🔴', label: 'Active', count: active.length, color: '#ef4444' },
          { id: 'all' as const, icon: '📋', label: 'All', count: alerts.length, color: 'var(--muted)' },
          { id: 'acknowledged' as const, icon: '👁️', label: 'Acknowledged', count: alerts.filter(a => a.status === 'acknowledged').length, color: '#3b82f6' },
          { id: 'resolved' as const, icon: '✅', label: 'Resolved', count: alerts.filter(a => a.status === 'resolved').length, color: '#10b981' },
        ]).map(s => (
          <button key={s.id} className={`filter-chip ${filter === s.id ? 'active' : ''}`}
            onClick={() => setFilter(s.id)} style={{ fontSize: 10, padding: '3px 10px' }}>
            {s.icon} {s.label} ({s.count})
          </button>
        ))}
      </div>

      {/* Create alert */}
      {patientId && (
        <div style={{ display: 'flex', gap: 8 }}>
          <button className="btn-sm-accent" onClick={() => setShowCompose(!showCompose)} style={{ background: '#ef4444' }}>
            {showCompose ? '✕ Close' : '🚨 Raise Alert'}
          </button>
        </div>
      )}

      {showCompose && (
        <div style={{ padding: compact ? 10 : 14, borderRadius: 14, border: '2px solid #ef444440', background: 'var(--surface)', display: 'flex', flexDirection: 'column', gap: 8 }}>
          <div className="form-grid-2">
            <div className="field-col">
              <span className="field-lbl">Category</span>
              <select className="field-inp" value={formData.category} onChange={e => setFormData(prev => ({ ...prev, category: e.target.value as AlertCategory }))}>
                <option value="clinical">Clinical</option>
                <option value="operational">Operational</option>
                <option value="medication">Medication</option>
                <option value="lab">Lab</option>
                <option value="system">System</option>
              </select>
            </div>
            <div className="field-col">
              <span className="field-lbl">Severity</span>
              <select className="field-inp" value={formData.severity} onChange={e => setFormData(prev => ({ ...prev, severity: e.target.value as AlertSeverity }))}>
                <option value="info">ℹ️ Info</option>
                <option value="warning">⚠️ Warning</option>
                <option value="critical">🚨 Critical</option>
              </select>
            </div>
          </div>
          <div className="field-col">
            <span className="field-lbl">Title *</span>
            <input className="field-inp" placeholder="e.g. Deteriorating renal function"
              value={formData.title} onChange={e => setFormData(prev => ({ ...prev, title: e.target.value }))} />
          </div>
          <div className="field-col">
            <span className="field-lbl">Message *</span>
            <textarea className="field-ta" rows={3} placeholder="e.g. Creatinine rising from 120 to 350 over 48 hours. Urgent nephrology review needed."
              value={formData.message} onChange={e => setFormData(prev => ({ ...prev, message: e.target.value }))} />
          </div>
          <button className="btn-accent" style={{ background: '#ef4444' }} onClick={handleCreateAlert} disabled={saving || !formData.title.trim() || !formData.message.trim()}>
            {saving ? 'Creating...' : '🚨 Raise Alert'}
          </button>
        </div>
      )}

      {/* Alert list */}
      {loading ? (
        [1,2,3].map(i => <div key={i} className="skeleton" style={{ height: 48, borderRadius: 8, marginBottom: 4 }} />)
      ) : displayAlerts.length === 0 ? (
        <div style={{ textAlign: 'center', padding: 16, color: 'var(--muted)', fontSize: 12 }}>No alerts.</div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
          {displayAlerts.map(alert => {
            const sc = severityConfig[alert.severity];
            return (
              <div key={alert.id} style={{
                padding: compact ? 6 : 8, borderRadius: 8,
                background: sc.bg, border: `1px solid ${sc.color}25`,
                borderLeft: `3px solid ${sc.color}`,
                opacity: alert.status === 'resolved' ? 0.6 : 1,
              }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8 }}>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontWeight: 700, fontSize: compact ? 11 : 12 }}>
                      {sc.icon} {alert.title}
                    </div>
                    <div style={{ fontSize: compact ? 10 : 11, color: 'var(--text-2)', marginTop: 2 }}>{alert.message}</div>
                    <div style={{ display: 'flex', gap: 4, marginTop: 4, flexWrap: 'wrap' }}>
                      <span style={{ fontSize: 9, padding: '1px 5px', borderRadius: 99, background: sc.bg, color: sc.color, fontWeight: 600 }}>{alert.category}</span>
                      {alert.autoGenerated && <span style={{ fontSize: 9, padding: '1px 5px', borderRadius: 99, background: '#8b5cf610', color: '#8b5cf6', fontWeight: 600 }}>⚡ Auto</span>}
                      <span style={{ fontSize: 9, color: 'var(--muted)' }}>
                        Escalation: Level {alert.escalationLevel}
                      </span>
                    </div>
                  </div>
                  <div style={{ display: 'flex', gap: 3, flexShrink: 0, alignItems: 'center' }}>
                    <span style={{ fontSize: 9, color: 'var(--muted)', fontFamily: 'var(--mono)' }}>{fmtTime(alert.createdAt)}</span>
                    {alert.status === 'active' && (
                      <>
                        <button className="btn-action" style={{ fontSize: 9, padding: '2px 6px' }} onClick={() => alert.id && handleAcknowledge(alert.id)}>👁️</button>
                        <button className="btn-action" style={{ fontSize: 9, padding: '2px 6px', color: '#f59e0b' }} onClick={() => alert.id && handleEscalate(alert.id, alert.escalationLevel)}>⬆️</button>
                        <button className="btn-action" style={{ fontSize: 9, padding: '2px 6px', color: '#10b981' }} onClick={() => alert.id && handleResolve(alert.id)}>✅</button>
                      </>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
