import type { ImagingProtocol } from '../types/protocols'

export const PNEUMONIA_IMAGING_PROTOCOLS: ImagingProtocol[] = [
  {
    id: 'cxr_pa',
    name: 'Chest X-ray (PA + Lateral)',
    modality: 'xray',
    views: ['PA erect', 'Left lateral'],
    preparation: 'None — explain procedure to patient',
    contrast: false,
    urgency: 'stat',
    findingsExpected: [
      'Lobar consolidation',
      'Bronchopneumonia pattern',
      'Interstitial infiltrates',
      'Pleural effusion',
      'Cavitation',
      'Pneumothorax',
      'Miliary pattern',
      'Hilar lymphadenopathy',
      'Air bronchogram',
    ],
  },
  {
    id: 'chest_ct',
    name: 'Chest CT (High-Resolution)',
    modality: 'ct',
    views: ['Axial', 'Coronal', 'Sagittal'],
    preparation: 'IV access for contrast — check creatinine before contrast',
    contrast: true,
    urgency: 'urgent',
    findingsExpected: [
      'Consolidation with air bronchogram',
      'Ground-glass opacities',
      'Tree-in-bud nodules',
      'Cavitary lesions',
      'Pleural effusion / empyema',
      'Mediastinal lymphadenopathy',
      'Miliary nodules',
      'Interstitial thickening',
    ],
  },
  {
    id: 'ct_pa',
    name: 'CT Pulmonary Angiogram',
    modality: 'ct',
    views: ['Axial', 'Coronal', 'Sagittal MIP'],
    preparation: 'IV access — check creatinine — nil per mouth 4h',
    contrast: true,
    urgency: 'stat',
    findingsExpected: [
      'Pulmonary embolism (filling defect)',
      'Right ventricular strain',
      'Pulmonary infarction',
      'Alternative diagnosis',
    ],
  },
  {
    id: 'chest_ultrasound',
    name: 'Chest Ultrasound',
    modality: 'ultrasound',
    views: ['Longitudinal', 'Transverse', 'M-mode'],
    preparation: 'None',
    contrast: false,
    urgency: 'urgent',
    findingsExpected: [
      'Pleural effusion (quantified)',
      'Lung consolidation',
      'B-lines (interstitial syndrome)',
      'Pneumothorax (lung point)',
      'Diaphragm evaluation',
    ],
  },
]
