import type { LabProtocol } from '../types/protocols'

export const PNEUMONIA_LAB_PROTOCOLS: LabProtocol[] = [
  {
    id: 'cbc',
    name: 'Complete Blood Count',
    category: 'hematology',
    sample: 'EDTA whole blood',
    turnaroundMinutes: 60,
    interpretation: {
      neutrophilia: 'Supports bacterial infection — increase CAP probability',
      lymphocytosis: 'Supports viral etiology',
      leukopenia: 'Consider sepsis, HIV, or atypical infection',
      thrombocytopenia: 'Consider sepsis, DIC, or HIV',
      anemia: 'Chronic disease or acute blood loss',
      normal: 'Does not exclude pneumonia — may be early',
    },
    criticalValues: { hb_below_6: 'Urgent transfusion assessment', platelets_below_20: 'Risk of spontaneous bleeding', wbc_below_1: 'Neutropenic sepsis risk' },
  },
  {
    id: 'crp',
    name: 'C-Reactive Protein',
    category: 'biochemistry',
    sample: 'Serum',
    turnaroundMinutes: 60,
    interpretation: {
      above_100: 'Strongly supports bacterial infection — recommend antibiotics',
      above_40: 'Moderate bacterial probability',
      above_10: 'Mild inflammation — viral possible',
      normal: 'Viral or non-infectious etiology',
    },
    criticalValues: { above_300: 'Severe inflammation / sepsis' },
  },
  {
    id: 'procalcitonin',
    name: 'Procalcitonin',
    category: 'biochemistry',
    sample: 'Serum',
    turnaroundMinutes: 90,
    interpretation: {
      above_2: 'Strong bacterial infection — antibiotics indicated',
      above_0_5: 'Possible bacterial — consider antibiotics',
      above_0_25: 'Viral or mild bacterial',
      below_0_1: 'Viral etiology likely',
    },
    criticalValues: { above_10: 'Severe sepsis / septic shock' },
  },
  {
    id: 'blood_culture',
    name: 'Blood Culture x2',
    category: 'microbiology',
    sample: 'Blood (aerobic + anaerobic bottles)',
    turnaroundMinutes: 2880,
    interpretation: {
      positive: 'Identify organism and sensitivity',
      negative_at_48h: 'No growth — de-escalate if clinical improvement',
      contaminant: 'Likely skin flora — repeat if clinical concern',
    },
    criticalValues: { positive_gram_negative: 'Gram-negative sepsis — urgent antibiotics' },
  },
  {
    id: 'abg',
    name: 'Arterial Blood Gas',
    category: 'biochemistry',
    sample: 'Arterial blood',
    turnaroundMinutes: 15,
    interpretation: {
      ph_below_7_35: 'Acidosis — respiratory or metabolic',
      pao2_below_60: 'Hypoxemic respiratory failure',
      paco2_above_50: 'Hypercapnic respiratory failure',
      lactate_above_2: 'Tissue hypoperfusion / sepsis',
      hco3_below_22: 'Metabolic acidosis',
    },
    criticalValues: { ph_below_7_2: 'Severe acidosis — ICU review', pao2_below_40: 'Critical hypoxemia' },
  },
  {
    id: 'ue_creatinine',
    name: 'U&E / Creatinine',
    category: 'biochemistry',
    sample: 'Serum',
    turnaroundMinutes: 60,
    interpretation: {
      hyponatremia: 'SIADH — consider pneumonia, TB, or CNS cause',
      hypernatremia: 'Dehydration or diabetes insipidus',
      hypokalemia: 'Diuretics, diarrhea, or steroids',
      hyperkalemia: 'Renal impairment or medication effect',
      creatinine_above_106: 'Acute kidney injury — assess fluid status',
      urea_above_20: 'Pre-renal azotemia or GI bleed',
    },
    criticalValues: { potassium_above_6_5: 'Life-threatening hyperkalemia — urgent ECG', creatinine_above_500: 'Renal replacement therapy assessment' },
  },
  {
    id: 'lactate',
    name: 'Lactate',
    category: 'biochemistry',
    sample: 'Blood',
    turnaroundMinutes: 15,
    interpretation: {
      above_2: 'Tissue hypoperfusion — consider sepsis',
      above_4: 'Severe sepsis / septic shock — ICU assessment',
      above_8: 'Critical — high mortality risk',
    },
    criticalValues: { above_4: 'Sepsis protocol escalation' },
  },
  {
    id: 'bnp',
    name: 'BNP / NT-proBNP',
    category: 'biochemistry',
    sample: 'Serum',
    turnaroundMinutes: 60,
    interpretation: {
      bnp_above_400: 'Heart failure likely — differentiate from pneumonia',
      bnp_100_400: 'Intermediate — clinical correlation needed',
      bnp_below_100: 'Heart failure unlikely',
    },
    criticalValues: { bnp_above_1000: 'Severe heart failure — cardiology review' },
  },
  {
    id: 'sputum_gram',
    name: 'Sputum Gram Stain',
    category: 'microbiology',
    sample: 'Sputum',
    turnaroundMinutes: 60,
    interpretation: {
      gram_positive_diplococci: 'Streptococcus pneumoniae',
      gram_negative_rods: 'Klebsiella, Pseudomonas, or other GNB',
      gram_positive_cocci_clusters: 'Staphylococcus aureus',
      mixed_flora: 'Possible aspiration or contamination',
      no_organisms: 'May be atypical or viral',
    },
    criticalValues: { gram_negative_rods_moderate: 'Empiric coverage for GNB' },
  },
  {
    id: 'genexpert',
    name: 'GeneXpert MTB/RIF',
    category: 'microbiology',
    sample: 'Sputum or BAL',
    turnaroundMinutes: 120,
    interpretation: {
      mtb_detected_rif_sensitive: 'Active TB — start standard therapy',
      mtb_detected_rif_resistant: 'MDR-TB — refer to TB specialist',
      mtb_not_detected: 'TB not detected — clinical correlation needed',
      invalid: 'Repeat sample collection',
    },
    criticalValues: { rif_resistant: 'Infection control — airborne isolation — MDR-TB protocol' },
  },
]
