import type { MedicationProtocol } from '../types/protocols'

export const PNEUMONIA_MEDICATIONS: MedicationProtocol[] = [
  // ── First-line CAP (Kenya guidelines) ──
  {
    id: 'cap_ceftriaxone',
    diseaseId: 'community_acquired_pneumonia',
    drug: 'Ceftriaxone',
    route: 'IV',
    dose: '2 g',
    frequency: 'OD',
    duration: '5-7 days',
    contraindications: ['Known severe cephalosporin allergy', 'Previous anaphylaxis to beta-lactams'],
    allergies: ['Penicillin allergy (cross-reactivity ~5-10%)'],
    severity: 'moderate',
    alternativeIfAllergy: ['Levofloxacin 750 mg IV OD', 'Clarithromycin 500 mg IV BID'],
    notes: 'First-line empiric CAP treatment in Kenya. Administer over 30 min.',
  },
  {
    id: 'cap_azithromycin',
    diseaseId: 'community_acquired_pneumonia',
    drug: 'Azithromycin',
    route: 'PO',
    dose: '500 mg',
    frequency: 'OD',
    duration: '5 days',
    contraindications: ['QTc prolongation', 'Severe hepatic impairment'],
    allergies: ['Macrolide allergy (rare)'],
    severity: 'moderate',
    alternativeIfAllergy: ['Doxycycline 100 mg PO BID'],
    notes: 'Covers atypical pathogens. Monitor QT interval in elderly.',
  },
  {
    id: 'cap_levofloxacin',
    diseaseId: 'community_acquired_pneumonia',
    drug: 'Levofloxacin',
    route: 'IV/PO',
    dose: '750 mg',
    frequency: 'OD',
    duration: '5 days',
    contraindications: ['QTc prolongation', 'History of tendon rupture', 'Epilepsy', 'Myasthenia gravis'],
    allergies: ['Fluoroquinolone allergy'],
    severity: 'moderate',
    alternativeIfAllergy: ['Ceftriaxone + Azithromycin combination'],
    notes: 'Respiratory fluoroquinolone. Reserve for allergy or failure cases.',
  },
  {
    id: 'cap_doxycycline',
    diseaseId: 'community_acquired_pneumonia',
    drug: 'Doxycycline',
    route: 'PO',
    dose: '100 mg',
    frequency: 'BID',
    duration: '7 days',
    contraindications: ['Children <8 years', 'Pregnancy'],
    allergies: ['Tetracycline allergy'],
    severity: 'mild',
    alternativeIfAllergy: ['Azithromycin 500 mg PO OD'],
    notes: 'Covers atypical pathogens. Alternative for mild CAP.',
  },
  {
    id: 'cap_amoxicillin_clavulanate',
    diseaseId: 'community_acquired_pneumonia',
    drug: 'Amoxicillin/Clavulanate',
    route: 'PO',
    dose: '875/125 mg',
    frequency: 'BID',
    duration: '7 days',
    contraindications: ['Penicillin allergy', 'Cholestatic jaundice'],
    allergies: ['Penicillin allergy'],
    severity: 'mild',
    alternativeIfAllergy: ['Cefuroxime 500 mg PO BID'],
    notes: 'First-line for mild CAP in penicillin-tolerant patients.',
  },
  // ── Severe CAP / ICU ──
  {
    id: 'severe_cap_piperacillin_tazobactam',
    diseaseId: 'community_acquired_pneumonia',
    drug: 'Piperacillin/Tazobactam',
    route: 'IV',
    dose: '4.5 g',
    frequency: 'Q6H',
    duration: '7-10 days',
    contraindications: ['Penicillin allergy', 'Severe renal impairment (adjust dose)'],
    allergies: ['Penicillin allergy'],
    severity: 'severe',
    alternativeIfAllergy: ['Cefepime 2 g IV Q8H', 'Meropenem 1 g IV Q8H'],
    notes: 'ICU-level empiric coverage. Extended infusion preferred (4h).',
  },
  {
    id: 'severe_cap_vancomycin',
    diseaseId: 'community_acquired_pneumonia',
    drug: 'Vancomycin',
    route: 'IV',
    dose: '15-20 mg/kg',
    frequency: 'Q8-12H',
    duration: '7-10 days',
    contraindications: ['Previous red man syndrome', 'Severe renal impairment'],
    allergies: ['Vancomycin allergy (rare)'],
    severity: 'severe',
    alternativeIfAllergy: ['Linezolid 600 mg IV Q12H'],
    notes: 'Add if MRSA risk factors. Trough monitoring required (15-20 mcg/mL).',
  },
  // ── TB Treatment ──
  {
    id: 'tb_standard',
    diseaseId: 'tuberculosis',
    drug: 'Rifampicin + Isoniazid + Pyrazinamide + Ethambutol',
    route: 'PO',
    dose: 'Weight-based (RHZE)',
    frequency: 'OD',
    duration: '2 months (intensive phase)',
    contraindications: ['Severe hepatic failure', 'Previous drug-resistant TB'],
    allergies: ['Any first-line drug allergy — refer to TB clinic'],
    severity: 'moderate',
    alternativeIfAllergy: ['Individualized MDR regimen — TB specialist referral'],
    notes: 'Fixed-dose combination (FDC) preferred. Monitor LFTs at baseline, 2wk, 4wk.',
  },
  {
    id: 'tb_continuation',
    diseaseId: 'tuberculosis',
    drug: 'Rifampicin + Isoniazid',
    route: 'PO',
    dose: 'Weight-based (RH)',
    frequency: 'OD',
    duration: '4 months (continuation phase)',
    contraindications: ['Same as intensive phase'],
    allergies: ['Same as intensive phase'],
    severity: 'moderate',
    alternativeIfAllergy: ['Individualized regimen'],
    notes: 'Continue after intensive phase if culture conversion documented.',
  },
  // ── Supportive medications ──
  {
    id: 'paracetamol_fever',
    diseaseId: 'community_acquired_pneumonia',
    drug: 'Paracetamol',
    route: 'PO/IV',
    dose: '1 g',
    frequency: 'Q6H PRN',
    duration: 'Max 4g/day',
    contraindications: ['Severe hepatic impairment'],
    allergies: [],
    severity: 'mild',
    alternativeIfAllergy: ['Ibuprofen 400 mg PO TID PRN (if no contraindication)'],
    notes: 'For fever >38.5°C or pain.',
  },
  {
    id: 'saline_nebulization',
    diseaseId: 'community_acquired_pneumonia',
    drug: 'Normal Saline Nebulization',
    route: 'INH',
    dose: '3 mL',
    frequency: 'Q6H PRN',
    duration: 'As needed',
    contraindications: [],
    allergies: [],
    severity: 'mild',
    alternativeIfAllergy: [],
    notes: 'For thick secretions. Follow with chest physiotherapy if tolerated.',
  },
]
