import type { MonitoringProtocol } from '../types/protocols'

export const PNEUMONIA_MONITORING: MonitoringProtocol[] = [
  {
    id: 'monitoring_cap_moderate',
    diseaseId: 'community_acquired_pneumonia',
    severity: 'moderate',
    vitals: ['RR', 'HR', 'BP', 'Temp', 'SpO2'],
    vitalsFrequency: 'Q4H',
    urineOutput: true,
    urineOutputFrequency: 'Q8H',
    fluidBalance: true,
    dailyWeight: true,
    painScore: true,
    consciousness: true,
    oxygenMonitoring: true,
    special: ['NEWS score Q4H', 'CURB-65 on admission', 'Sputum character daily'],
  },
  {
    id: 'monitoring_cap_severe',
    diseaseId: 'community_acquired_pneumonia',
    severity: 'severe',
    vitals: ['RR', 'HR', 'BP (invasive if vasopressors)', 'Temp', 'SpO2 continuous', 'CVP if indicated'],
    vitalsFrequency: 'Q1H minimum',
    urineOutput: true,
    urineOutputFrequency: 'Q1H',
    fluidBalance: true,
    dailyWeight: true,
    painScore: true,
    consciousness: true,
    oxygenMonitoring: true,
    special: ['NEWS score Q1H', 'Lactate clearance Q2H', 'ABG Q4-6H or prn', 'Chest X-ray daily', 'Procalcitonin trend daily', 'Ventilator settings if intubated q1h'],
  },
  {
    id: 'monitoring_tb',
    diseaseId: 'tuberculosis',
    severity: 'moderate',
    vitals: ['Temp', 'RR', 'HR', 'BP', 'SpO2'],
    vitalsFrequency: 'Q6H',
    urineOutput: false,
    fluidBalance: false,
    dailyWeight: true,
    painScore: true,
    consciousness: true,
    oxygenMonitoring: false,
    special: ['LFTs weekly x4 then monthly', 'Sputum AFB monthly', 'Weight weekly', 'Chest X-ray at 2 months', 'Visual acuity if ethambutol (monthly)'],
  },
]
