import type { SupportiveCareProtocol } from '../types/protocols'

export const PNEUMONIA_SUPPORTIVE_CARE: SupportiveCareProtocol[] = [
  {
    id: 'oxygen_hypoxia',
    condition: 'SpO2 <92%',
    threshold: 'SpO2 <92% on room air',
    action: 'Start supplemental oxygen via nasal prongs at 2-5 L/min',
    route: 'Inhalation',
    details: 'Target SpO2 92-96%. Titrate flow to maintain target. If prongs insufficient, switch to simple face mask at 5-10 L/min or Venturi mask.',
    monitoring: 'Continuous pulse oximetry. Reassess after 5 min of each change.',
  },
  {
    id: 'oxygen_severe_hypoxia',
    condition: 'SpO2 <85% or RR >35',
    threshold: 'SpO2 <85% despite 5L NP',
    action: 'Escalate oxygen — non-rebreather mask 15 L/min. Assess for NIV/CPAP. Consider ICU referral.',
    route: 'Inhalation',
    details: 'Non-rebreather mask at 15 L/min. If no improvement, assess for HFNC, CPAP, or BiPAP. Prepare for possible intubation.',
    monitoring: 'Continuous monitoring. ABG after 30 min.',
  },
  {
    id: 'fluid_resuscitation',
    condition: 'SBP <90 mmHg or signs of shock',
    threshold: 'SBP <90 mmHg, lactate >2, or urine output <0.5 mL/kg/h',
    action: 'IV fluid bolus — Normal Saline 500 mL over 15-30 min. Reassess.',
    route: 'IV',
    details: 'Give 500 mL NS bolus. Reassess BP, HR, lactate, urine output. Repeat if no response after 30 min. Maximum 30 mL/kg crystalloid before considering vasopressors.',
    monitoring: 'BP q5min during bolus. HR, RR, SpO2 continuous. Urine output hourly.',
  },
  {
    id: 'vasopressor_shock',
    condition: 'Shock not responding to fluids',
    threshold: 'MAP <65 mmHg after 30 mL/kg crystalloid',
    action: 'Start norepinephrine infusion via central line',
    route: 'IV',
    details: 'Norepinephrine 0.05-0.5 mcg/kg/min, titrate to MAP ≥65 mmHg. Insert arterial line. Consider ICU transfer.',
    monitoring: 'Arterial BP continuous, CVP, ScvO2, lactate q2h, urine output hourly.',
  },
  {
    id: 'fever_management',
    condition: 'Temperature >39°C',
    threshold: 'Temp >39°C or patient distressed',
    action: 'Antipyretic — Paracetamol 1 g PO/IV',
    route: 'PO/IV',
    details: 'Paracetamol 1 g q6h PRN (max 4 g/day). Tepid sponging if no response. Reassess for infection source.',
    monitoring: 'Temp q1h until <38°C, then q4h.',
  },
  {
    id: 'nutrition',
    condition: 'All hospitalized pneumonia patients',
    threshold: 'Admission',
    action: 'Nutrition assessment within 24h. High-protein, high-calorie diet.',
    route: 'PO/NG',
    details: 'Dietitian referral. If oral intake inadequate >48h, consider NG feeding. Monitor albumin, pre-albumin.',
    monitoring: 'Daily weight. Food chart. Input/output.',
  },
  {
    id: 'dvt_prophylaxis',
    condition: 'Immobilized patients or ICU stay',
    threshold: 'Expected immobility >24h or ICU admission',
    action: 'SC heparin 5000 IU BID or enoxaparin 40 mg SC OD',
    route: 'SC',
    details: 'Start within 24h of admission unless contraindicated (active bleeding, coagulopathy). Use mechanical prophylaxis if anticoagulation contraindicated.',
    monitoring: 'Check for bleeding signs daily. Monitor platelet count if on heparin >5 days.',
  },
  {
    id: 'chest_physiotherapy',
    condition: 'Productive cough with difficulty clearing secretions',
    threshold: 'Ineffective cough or thick secretions',
    action: 'Chest physiotherapy — postural drainage, percussion, vibration',
    route: 'N/A',
    details: 'Physiotherapy referral. Deep breathing exercises. Incentive spirometry if available. Position patient semi-recumbent (30-45°).',
    monitoring: 'Sputum volume and character daily. Breath sounds before and after.',
  },
  {
    id: 'early_mobilization',
    condition: 'Stable pneumonia patients',
    threshold: 'Hemodynamically stable, SpO2 >90% on <4L O2',
    action: 'Early mobilization protocol — sit up, dangle legs, ambulate with assistance',
    route: 'N/A',
    details: 'Day 1: Sit up in bed, dangle legs x5 min. Day 2: Stand at bedside, ambulate to bathroom. Day 3: Ambulate in hallway with assistance.',
    monitoring: 'SpO2 and BP before and after each session. Borg dyspnea scale.',
  },
  {
    id: 'sepsis_bundle',
    condition: 'Sepsis / septic shock',
    threshold: 'qSOFA ≥2 or lactate >2',
    action: 'Sepsis 1-hour bundle: blood cultures, lactate, antibiotics, fluids, vasopressors',
    route: 'IV',
    details: '1. Measure lactate. 2. Obtain blood cultures before antibiotics. 3. Administer broad-spectrum antibiotics. 4. Begin 30 mL/kg crystalloid for hypotension. 5. Apply vasopressors if hypotensive during or after fluid resuscitation.',
    monitoring: 'Lactate clearance q2h. MAP >65 mmHg. Urine output >0.5 mL/kg/h.',
  },
]
