export interface PdfSection {
  title: string;
  content: string;
  subSections?: { heading: string; body: string }[];
}

export interface PdfDocument {
  title: string;
  subtitle: string;
  patientInfo: { label: string; value: string }[];
  date: string;
  sections: PdfSection[];
  redFlags?: string[];
  medications?: string[];
  followUp?: string;
  generatedBy: string;
  hospitalName: string;
  consultant?: string;
}

function renderDivider(): string {
  return '\n' + '─'.repeat(70) + '\n';
}

function renderSection(s: PdfSection, level: number): string {
  const heading = level === 1 ? `# ${s.title}` : level === 2 ? `## ${s.title}` : `### ${s.title}`;
  const body = s.content || '';
  const subSections = (s.subSections || [])
    .map(sub => `\n### ${sub.heading}\n${sub.body}`)
    .join('\n');
  return [heading, '', body, subSections].join('\n');
}

export function renderPdfText(doc: PdfDocument): string {
  const parts: string[] = [
    '='.repeat(70),
    doc.title.toUpperCase(),
    doc.subtitle,
    '='.repeat(70),
    '',
    `Hospital: ${doc.hospitalName}`,
    `Date: ${doc.date}`,
    `Generated: ${doc.generatedBy}`,
    doc.consultant ? `Consultant: ${doc.consultant}` : '',
    '',
    '─'.repeat(70),
    'PATIENT INFORMATION',
    '─'.repeat(70),
    '',
    doc.patientInfo.map(i => `${i.label}: ${i.value}`).join('\n'),
    '',
  ];

  for (const section of doc.sections) {
    parts.push(renderDivider());
    parts.push(renderSection(section, 1));
  }

  if (doc.redFlags && doc.redFlags.length > 0) {
    parts.push(renderDivider());
    parts.push('⚠ RED FLAGS');
    parts.push('');
    parts.push(doc.redFlags.map(r => `⚠ ${r}`).join('\n'));
  }

  if (doc.medications && doc.medications.length > 0) {
    parts.push(renderDivider());
    parts.push('MEDICATIONS');
    parts.push('');
    parts.push(doc.medications.map(m => `- ${m}`).join('\n'));
  }

  if (doc.followUp) {
    parts.push(renderDivider());
    parts.push('FOLLOW-UP PLAN');
    parts.push('');
    parts.push(doc.followUp);
  }

  parts.push('');
  parts.push('='.repeat(70));
  parts.push('* Generated by AMEXAN Clinical Reasoning System — LBO Module *');
  parts.push('* This is a computer-generated clinical document. Verify before use. *');
  parts.push('='.repeat(70));

  return parts.join('\n');
}

// ── Specific document builders ──────────────────────────────────────────────

export function buildClerkingPdf(params: {
  patientName: string; mrn: string; age: number; sex: string; ward: string; bed: string;
  presentingComplaint: string; hpi: string; pmh: string; medications: string; allergies: string;
  examSummary: string; ddx: string; plan: string; consultant: string; hospital: string;
}): PdfDocument {
  return {
    title: 'Clerking Note — Large Bowel Obstruction',
    subtitle: 'Emergency Surgical Admission',
    patientInfo: [
      { label: 'Name', value: params.patientName },
      { label: 'MRN', value: params.mrn },
      { label: 'Age/Sex', value: `${params.age} / ${params.sex}` },
      { label: 'Ward/Bed', value: `${params.ward} / ${params.bed}` },
    ],
    date: new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }),
    sections: [
      { title: 'Presenting Complaint', content: params.presentingComplaint },
      { title: 'History of Presenting Illness', content: params.hpi },
      { title: 'Past Medical History', content: params.pmh },
      { title: 'Medications & Allergies', content: `Medications: ${params.medications}\nAllergies: ${params.allergies}` },
      { title: 'Examination Findings', content: params.examSummary },
      { title: 'Differential Diagnosis', content: params.ddx },
      { title: 'Plan', content: params.plan },
    ],
    generatedBy: 'AMEXAN LBO Module',
    hospitalName: params.hospital,
    consultant: params.consultant,
  };
}

export function buildOperativeNotePdf(params: {
  patientName: string; mrn: string; procedure: string; surgeon: string; anaesthesia: string;
  preOpDx: string; postOpDx: string; findings: string; steps: string; bloodLoss: string;
  specimens: string[]; complications: string[]; disposition: string; hospital: string;
}): PdfDocument {
  return {
    title: 'Operative Note — Large Bowel Obstruction',
    subtitle: params.procedure,
    patientInfo: [
      { label: 'Name', value: params.patientName },
      { label: 'MRN', value: params.mrn },
      { label: 'Surgeon', value: params.surgeon },
      { label: 'Anaesthesia', value: params.anaesthesia },
    ],
    date: new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }),
    sections: [
      { title: 'Pre-operative Diagnosis', content: params.preOpDx },
      { title: 'Post-operative Diagnosis', content: params.postOpDx },
      { title: 'Procedure', content: params.procedure },
      { title: 'Findings', content: params.findings },
      { title: 'Procedure Details', content: params.steps },
      { title: 'Blood Loss', content: params.bloodLoss },
      { title: 'Specimens', content: params.specimens.join('\n') },
      { title: 'Complications', content: params.complications.length > 0 ? params.complications.join('\n') : 'None' },
      { title: 'Disposition', content: params.disposition },
    ],
    generatedBy: 'AMEXAN LBO Module',
    hospitalName: params.hospital,
  };
}

export function buildDischargeSummaryPdf(params: {
  patientName: string; mrn: string; admissionDate: string; dischargeDate: string;
  primaryDx: string; secondaryDx: string[]; procedures: string[]; hospitalCourse: string;
  medications: string[]; diet: string[]; activity: string[]; woundCare: string[]; stomaCare: string[];
  followUp: string[]; redFlags: string[]; hospital: string; consultant: string;
}): PdfDocument {
  return {
    title: 'Discharge Summary — Large Bowel Obstruction',
    subtitle: 'Post-operative Discharge',
    patientInfo: [
      { label: 'Name', value: params.patientName },
      { label: 'MRN', value: params.mrn },
      { label: 'Admission', value: params.admissionDate },
      { label: 'Discharge', value: params.dischargeDate },
    ],
    date: new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }),
    sections: [
      { title: 'Primary Diagnosis', content: params.primaryDx },
      { title: 'Secondary Diagnoses', content: params.secondaryDx.join('\n') },
      { title: 'Procedures Performed', content: params.procedures.map(p => `- ${p}`).join('\n') },
      { title: 'Hospital Course', content: params.hospitalCourse },
      { title: 'Medications on Discharge', content: params.medications.map(m => `- ${m}`).join('\n') },
      { title: 'Diet Instructions', content: params.diet.map(d => `- ${d}`).join('\n') },
      { title: 'Activity Restrictions', content: params.activity.map(a => `- ${a}`).join('\n') },
      { title: 'Wound Care', content: params.woundCare.map(w => `- ${w}`).join('\n') },
    ],
    redFlags: params.redFlags,
    medications: params.medications,
    followUp: params.followUp.join('; '),
    generatedBy: 'AMEXAN LBO Module',
    hospitalName: params.hospital,
    consultant: params.consultant,
  };
}
