/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * BOOK XVIII — CONSTITUTIONAL KNOWLEDGE ECOSYSTEM FRAMEWORK (CKEF) — Volume KE-1
 * Version 1.0
 *
 * The knowledge ecosystem constitution. Knowledge is not a document; knowledge
 * is an ecosystem. AMEXAN shall transform healthcare information into
 * understandable, actionable, personalized, visual, continuously evolving
 * knowledge that improves patient care, professional development,
 * organizational excellence, and public health.
 *
 * Constitutional Law KE-001: Healthcare knowledge is a living organizational asset.
 * ═══════════════════════════════════════════════════════════════════════════════
 */

import { ObjectType } from './book-I-objects';
import { ClinicalContext } from './book-III-context';
import { createRule, RuleCategory, RuleNode, RuleAction, RuleTrigger } from './book-IV-rules';

export const KNOWLEDGE_ECOSYSTEM_CONSTITUTION_VERSION = '1.0.0';

/**
 * CR-KE-001 — the supreme ecosystem rule.
 * Every knowledge output shall preserve provenance.
 */
export const CR_KE_001: RuleNode = createRule({
  id: 'CR-KE-001',
  name: 'Provenance Is Preserved in Every Knowledge Output',
  category: RuleCategory.Data,
  trigger: RuleTrigger.OnRead,
  conditions: [
    { field: 'output.type', operator: 'in', value: ['guideline', 'educational_material', 'summary', 'poster', 'brochure', 'visualization'] },
    { field: 'output.provenance', operator: 'not_exists', value: true },
  ],
  action: RuleAction.Block,
  priority: 100,
  targetTypes: [ObjectType.Guideline, ObjectType.Documentation, ObjectType.Evidence],
  contexts: [ClinicalContext.SystemLevel],
  explanation:
    'All organizational guidelines, educational materials, summaries, posters, brochures, and visualizations generated by AMEXAN shall preserve provenance. ' +
    'Every recommendation must retain its source, version, approving authority (where applicable), review date, and supporting references. ' +
    'User customizations remain layered on top of the canonical source rather than replacing it.',
  evidence: ['KE-1 Constitutional safeguard'],
  isActive: true,
  version: 1,
});

/** KE-001 — Knowledge is a living organizational asset. */
export const KE_001: RuleNode = createRule({
  id: 'KE-001',
  name: 'Knowledge Is a Living Organizational Asset',
  category: RuleCategory.Workflow,
  trigger: RuleTrigger.AfterCreate,
  conditions: [{ field: 'knowledge', operator: 'exists', value: true }],
  action: RuleAction.CreateTask,
  priority: 90,
  targetTypes: [ObjectType.ClinicalKnowledge],
  contexts: [ClinicalContext.SystemLevel],
  explanation: 'Every encounter, guideline, protocol, publication, educational material, reflection, audit, and discussion shall contribute to the organization\'s evolving knowledge ecosystem.',
  evidence: ['KE-1 Law KE-001'],
  isActive: true,
  version: 1,
});

/** KE-002 — Knowledge must become usable (never isolated PDFs). */
export const KE_002: RuleNode = createRule({
  id: 'KE-002',
  name: 'Knowledge Must Become Usable',
  category: RuleCategory.Data,
  trigger: RuleTrigger.AfterCreate,
  conditions: [{ field: 'resource.format', operator: 'in', value: ['pdf', 'docx', 'pptx', 'email', 'folder'] }],
  action: RuleAction.SetValue,
  priority: 85,
  targetTypes: [ObjectType.ClinicalKnowledge, ObjectType.Documentation],
  contexts: [ClinicalContext.SystemLevel],
  explanation: 'Knowledge shall never remain as isolated PDFs, Word documents, PowerPoints, emails, or folders. Every resource entering AMEXAN is transformed into structured, searchable, linked knowledge objects.',
  evidence: ['KE-1 Principle 1'],
  isActive: true,
  version: 1,
});

/** KE-003 — Every department owns a Living Knowledge Base. */
export const KE_003: RuleNode = createRule({
  id: 'KE-003',
  name: 'Department Living Knowledge Base',
  category: RuleCategory.Workflow,
  trigger: RuleTrigger.BeforeCreate,
  conditions: [{ field: 'department', operator: 'exists', value: true }],
  action: RuleAction.Require,
  priority: 80,
  targetTypes: [ObjectType.Department, ObjectType.ClinicalKnowledge],
  contexts: [ClinicalContext.SystemLevel],
  explanation: 'Every department owns a Living Knowledge Base containing protocols, SOPs, rounds, teaching files, cases, videos, pearls, research, complications, and lessons learned.',
  evidence: ['KE-1 Principle 2'],
  isActive: true,
  version: 1,
});

/** KE-004 — Guideline Builder with modular building blocks. */
export const KE_004: RuleNode = createRule({
  id: 'KE-004',
  name: 'Guideline Builder Uses Modular Blocks',
  category: RuleCategory.Workflow,
  trigger: RuleTrigger.BeforeCreate,
  conditions: [{ field: 'guideline', operator: 'exists', value: true }],
  action: RuleAction.Require,
  priority: 75,
  targetTypes: [ObjectType.Guideline],
  contexts: [ClinicalContext.SystemLevel],
  explanation: 'Organizations create guidelines using modular building blocks — definition, diagnosis, risk factors, workup, classification, investigations, treatment, follow-up — not static documents.',
  evidence: ['KE-1 Principle 3'],
  isActive: true,
  version: 1,
});

/** KE-005 — Guideline layering with inheritance. */
export const KE_005: RuleNode = createRule({
  id: 'KE-005',
  name: 'Guideline Layering Without Duplication',
  category: RuleCategory.Data,
  trigger: RuleTrigger.BeforeUpdate,
  conditions: [{ field: 'guideline', operator: 'exists', value: true }],
  action: RuleAction.Require,
  priority: 70,
  targetTypes: [ObjectType.Guideline],
  contexts: [ClinicalContext.SystemLevel],
  explanation: 'Every guideline exists in layers — global, country, professional society, organization, department, unit, personal. No duplication; inheritance; updates cascade safely.',
  evidence: ['KE-1 Principle 4'],
  isActive: true,
  version: 1,
});

/** KE-006 — One source, many outputs. */
export const KE_006: RuleNode = createRule({
  id: 'KE-006',
  name: 'One Source, Many Outputs',
  category: RuleCategory.UI,
  trigger: RuleTrigger.OnRead,
  conditions: [{ field: 'knowledge', operator: 'exists', value: true }],
  action: RuleAction.Show,
  priority: 65,
  targetTypes: [ObjectType.ClinicalKnowledge],
  contexts: [ClinicalContext.SystemLevel],
  explanation: 'One structured knowledge object publishes simultaneously to desktop, mobile, PDF, poster, slides, interactive flow, patient app, website, waiting-room screen, QR code, and printed booklet. The source remains single.',
  evidence: ['KE-1 Principle 5', 'KE-1 Principle 16'],
  isActive: true,
  version: 1,
});

/** KE-007 — Patient education adapts. */
export const KE_007: RuleNode = createRule({
  id: 'KE-007',
  name: 'Adaptive Patient Education',
  category: RuleCategory.Clinical,
  trigger: RuleTrigger.OnRead,
  conditions: [{ field: 'patient', operator: 'exists', value: true }],
  action: RuleAction.SetValue,
  priority: 60,
  targetTypes: [ObjectType.Patient, ObjectType.ClinicalKnowledge],
  contexts: [ClinicalContext.Clinical],
  explanation: 'Education adapts to diagnosis, age, language, pregnancy, culture, occupation, region, literacy, and technology access. One education never fits everyone.',
  evidence: ['KE-1 Principle 8'],
  isActive: true,
  version: 1,
});

/** KE-008 — Chronic disease education journeys. */
export const KE_008: RuleNode = createRule({
  id: 'KE-008',
  name: 'Chronic Disease Education Journeys',
  category: RuleCategory.Clinical,
  trigger: RuleTrigger.OnEvent,
  conditions: [{ field: 'diagnosis', operator: 'in', value: ['diabetes', 'hypertension', 'asthma', 'copd', 'heart_failure', 'ckd', 'cancer', 'hiv', 'tuberculosis'] }],
  action: RuleAction.CreateTask,
  priority: 55,
  targetTypes: [ObjectType.Patient, ObjectType.ClinicalKnowledge],
  contexts: [ClinicalContext.Clinical],
  explanation: 'Chronic disease patients receive continuous, progressing education journeys — education advances with the patient\'s stage, understanding, and clinical course rather than repeating the same leaflet.',
  evidence: ['KE-1 Principle 7'],
  isActive: true,
  version: 1,
});

/** KE-009 — Knowledge templates: nothing starts from a blank page. */
export const KE_009: RuleNode = createRule({
  id: 'KE-009',
  name: 'Constitutional Knowledge Templates',
  category: RuleCategory.UI,
  trigger: RuleTrigger.BeforeCreate,
  conditions: [{ field: 'resource', operator: 'exists', value: true }],
  action: RuleAction.Require,
  priority: 50,
  targetTypes: [ObjectType.Documentation, ObjectType.ClinicalKnowledge],
  contexts: [ClinicalContext.SystemLevel],
  explanation: 'Every educational resource has a constitutional template — one-page summary, ward protocol, patient brochure, infographic, teaching presentation, audit checklist, quick reference card. Nothing starts from a blank page.',
  evidence: ['KE-1 Principle 11'],
  isActive: true,
  version: 1,
});

/** KE-010 — Journal intelligence with permitted feeds. */
export const KE_010: RuleNode = createRule({
  id: 'KE-010',
  name: 'Journal Intelligence Ingests Only Permitted Sources',
  category: RuleCategory.Data,
  trigger: RuleTrigger.AfterCreate,
  conditions: [{ field: 'publication', operator: 'exists', value: true }],
  action: RuleAction.Require,
  priority: 45,
  targetTypes: [ObjectType.Evidence, ObjectType.ClinicalKnowledge],
  contexts: [ClinicalContext.SystemLevel],
  explanation: 'AMEXAN ingests trusted literature through licensed APIs or permitted feeds rather than indiscriminately scraping websites. Each article becomes citation, concepts, evidence level, and links to the original source — which is always preserved and cited.',
  evidence: ['KE-1 Principle 12', 'KI-1 Principle 15'],
  isActive: true,
  version: 1,
});

/** KE-011 — Knowledge comparison. */
export const KE_011: RuleNode = createRule({
  id: 'KE-011',
  name: 'Knowledge Comparison',
  category: RuleCategory.UI,
  trigger: RuleTrigger.OnRead,
  conditions: [{ field: 'guideline', operator: 'exists', value: true }],
  action: RuleAction.Show,
  priority: 40,
  targetTypes: [ObjectType.Guideline, ObjectType.Evidence],
  contexts: [ClinicalContext.SystemLevel],
  explanation: 'Clinicians compare hospital guideline vs WHO vs national guideline vs personal protocol. Differences become visible; reasoning becomes transparent.',
  evidence: ['KE-1 Principle 13'],
  isActive: true,
  version: 1,
});

/** KE-012 — Knowledge analytics measure effectiveness. */
export const KE_012: RuleNode = createRule({
  id: 'KE-012',
  name: 'Knowledge Analytics',
  category: RuleCategory.Reporting,
  trigger: RuleTrigger.Scheduled,
  conditions: [{ field: 'knowledge', operator: 'exists', value: true }],
  action: RuleAction.Notify,
  priority: 35,
  targetTypes: [ObjectType.ClinicalKnowledge],
  contexts: [ClinicalContext.SystemLevel],
  explanation: 'AMEXAN continuously measures most-used guidelines, ignored protocols, frequently misunderstood concepts, department learning gaps, and protocol adherence. Knowledge effectiveness becomes measurable.',
  evidence: ['KE-1 Principle 18'],
  isActive: true,
  version: 1,
});

/** All CKEF constitutional rules, ordered by priority. */
export const KNOWLEDGE_ECOSYSTEM_CONSTITUTIONAL_RULES: RuleNode[] = [
  CR_KE_001,
  KE_001,
  KE_002,
  KE_003,
  KE_004,
  KE_005,
  KE_006,
  KE_007,
  KE_008,
  KE_009,
  KE_010,
  KE_011,
  KE_012,
];

export function getKnowledgeEcosystemRule(ruleId: string): RuleNode | undefined {
  return KNOWLEDGE_ECOSYSTEM_CONSTITUTIONAL_RULES.find(r => r.id === ruleId);
}

export function isKnowledgeEcosystemConstitutionalRule(ruleId: string): boolean {
  return getKnowledgeEcosystemRule(ruleId) !== undefined;
}
