import { KnowledgeYamlParser, YamlKnowledgePackage } from '../knowledge-yaml-parser';

const parser = new KnowledgeYamlParser();

const pneumoniaYaml: YamlKnowledgePackage = {
  id: 'pkg_pneumonia',
  name: 'Pneumonia Knowledge Package',
  version: '1.0.0',
  description: 'Community-acquired pneumonia: symptoms, mechanisms, diagnostics, treatment',
  symptom: 'cough',
  disease: 'pneumonia',
  objects: [
    { id: 'sym_cough', type: 'symptom', name: 'Cough', description: 'Expulsion of air from the lungs', characteristics: ['productive', 'non-productive', 'hemoptysis'] },
    { id: 'sym_fever', type: 'symptom', name: 'Fever', description: 'Elevated body temperature', severity: 'moderate', onset: 'acute' },
    { id: 'sym_dyspnea', type: 'symptom', name: 'Dyspnea', description: 'Shortness of breath', severity: 'moderate' },
    { id: 'sym_pleuritic_pain', type: 'symptom', name: 'Pleuritic Chest Pain', description: 'Sharp chest pain worsened by breathing' },
    { id: 'sym_sputum', type: 'symptom', name: 'Sputum Production', description: 'Coughing up mucus', characteristics: ['purulent', 'blood-stained', 'rusty'] },
    { id: 'mech_alveolar_inflammation', type: 'mechanism', name: 'Alveolar Inflammation', description: 'Inflammation of alveoli due to infection' },
    { id: 'mech_consolidation', type: 'mechanism', name: 'Lung Consolidation', description: 'Solidification of lung tissue from exudate' },
    { id: 'mech_ventilation_perfusion_mismatch', type: 'mechanism', name: 'V/Q Mismatch', description: 'Mismatch between ventilation and perfusion' },
    { id: 'phen_hypoxia', type: 'phenotype', name: 'Hypoxia', description: 'Low oxygen in blood' },
    { id: 'phen_tachypnea', type: 'phenotype', name: 'Tachypnea', description: 'Rapid breathing' },
    { id: 'phen_crackles', type: 'phenotype', name: 'Crackles on Auscultation', description: 'Fine or coarse crackles heard on lung exam' },
    { id: 'phen_bronchial_breathing', type: 'phenotype', name: 'Bronchial Breathing', description: 'Abnormal breath sounds' },
    { id: 'dx_pneumonia', type: 'disease', name: 'Community-Acquired Pneumonia', description: 'Acute infection of lung parenchyma acquired outside hospital', severity: 'moderate', properties: { icd10: 'J18.9', typical_pathogens: ['Strep. pneumoniae', 'H. influenzae', 'M. catarrhalis'] } },
    { id: 'dx_tb', type: 'disease', name: 'Pulmonary Tuberculosis', description: 'Chronic infection by Mycobacterium tuberculosis', severity: 'severe', properties: { icd10: 'A15.0' } },
    { id: 'dx_bronchitis', type: 'disease', name: 'Acute Bronchitis', description: 'Inflammation of bronchial tubes, usually viral', severity: 'mild' },
    { id: 'inv_cbc', type: 'investigation', name: 'Complete Blood Count', description: 'WBC count, differential', properties: { priority: 1, typical_findings: 'leukocytosis with left shift' } },
    { id: 'inv_crp', type: 'investigation', name: 'C-Reactive Protein', description: 'Inflammatory marker', properties: { priority: 2 } },
    { id: 'inv_blood_culture', type: 'investigation', name: 'Blood Cultures', description: 'Two sets before antibiotics', properties: { priority: 3 } },
    { id: 'inv_sputum_culture', type: 'investigation', name: 'Sputum Culture', description: 'Gram stain and culture', properties: { priority: 3 } },
    { id: 'inv_chest_xray', type: 'investigation', name: 'Chest X-Ray', description: 'PA and lateral views', properties: { priority: 1, typical_findings: 'consolidation, air bronchograms' } },
    { id: 'inv_ct_chest', type: 'investigation', name: 'CT Chest', description: 'High-resolution CT', properties: { priority: 5 } },
    { id: 'inv_pulse_ox', type: 'investigation', name: 'Pulse Oximetry', description: 'Oxygen saturation', properties: { priority: 1 } },
    { id: 'trt_antibiotics', type: 'treatment', name: 'Antibiotics', description: 'Empiric antibiotics per local guidelines', properties: { first_line: 'Amoxicillin', alternatives: ['Doxycycline', 'Macrolide'] } },
    { id: 'trt_oxygen', type: 'treatment', name: 'Oxygen Therapy', description: 'Supplemental oxygen for hypoxia', properties: { target_spo2: '>92%' } },
    { id: 'trt_fluids', type: 'treatment', name: 'IV Fluids', description: 'Fluid resuscitation if septic' },
    { id: 'drug_amoxicillin', type: 'drug', name: 'Amoxicillin', description: 'First-line antibiotic for CAP', properties: { dose: '500mg-1g TDS', route: 'oral/IV', duration: '5-7 days' } },
    { id: 'drug_doxycycline', type: 'drug', name: 'Doxycycline', description: 'Alternative for penicillin allergy', properties: { dose: '200mg loading then 100mg OD', route: 'oral' } },
  ],
  relationships: [
    { source: 'sym_cough', target: 'mech_alveolar_inflammation', type: 'has_mechanism', confidence: 0.8 },
    { source: 'sym_fever', target: 'mech_alveolar_inflammation', type: 'has_mechanism', confidence: 0.7 },
    { source: 'sym_dyspnea', target: 'mech_ventilation_perfusion_mismatch', type: 'has_mechanism', confidence: 0.9 },
    { source: 'sym_pleuritic_pain', target: 'mech_alveolar_inflammation', type: 'has_mechanism', confidence: 0.6 },
    { source: 'sym_sputum', target: 'mech_alveolar_inflammation', type: 'has_mechanism', confidence: 0.85 },
    { source: 'mech_alveolar_inflammation', target: 'phen_hypoxia', type: 'produces', confidence: 0.7 },
    { source: 'mech_consolidation', target: 'phen_hypoxia', type: 'produces', confidence: 0.9 },
    { source: 'mech_alveolar_inflammation', target: 'phen_crackles', type: 'produces', confidence: 0.8 },
    { source: 'mech_consolidation', target: 'phen_bronchial_breathing', type: 'produces', confidence: 0.7 },
    { source: 'mech_ventilation_perfusion_mismatch', target: 'phen_hypoxia', type: 'produces', confidence: 0.9 },
    { source: 'mech_alveolar_inflammation', target: 'phen_tachypnea', type: 'produces', confidence: 0.6 },
    { source: 'phen_hypoxia', target: 'dx_pneumonia', type: 'suggests', confidence: 0.8 },
    { source: 'phen_crackles', target: 'dx_pneumonia', type: 'suggests', confidence: 0.85 },
    { source: 'phen_bronchial_breathing', target: 'dx_pneumonia', type: 'suggests', confidence: 0.75 },
    { source: 'phen_tachypnea', target: 'dx_pneumonia', type: 'suggests', confidence: 0.6 },
    { source: 'dx_pneumonia', target: 'inv_cbc', type: 'investigates', evidence: 'IDSA Guidelines 2023' },
    { source: 'dx_pneumonia', target: 'inv_crp', type: 'investigates', evidence: 'IDSA Guidelines 2023' },
    { source: 'dx_pneumonia', target: 'inv_blood_culture', type: 'investigates', evidence: 'SSC Guidelines' },
    { source: 'dx_pneumonia', target: 'inv_sputum_culture', type: 'investigates', evidence: 'BTS Guidelines' },
    { source: 'dx_pneumonia', target: 'inv_chest_xray', type: 'investigates', evidence: 'IDSA Guidelines 2023' },
    { source: 'dx_pneumonia', target: 'inv_ct_chest', type: 'investigates', evidence: 'When diagnosis uncertain' },
    { source: 'dx_pneumonia', target: 'inv_pulse_ox', type: 'investigates', evidence: 'Standard of care' },
    { source: 'dx_pneumonia', target: 'trt_antibiotics', type: 'treats', confidence: 0.95 },
    { source: 'dx_pneumonia', target: 'trt_oxygen', type: 'treats', evidence: 'BTS Oxygen Guidelines' },
    { source: 'dx_pneumonia', target: 'trt_fluids', type: 'treats', evidence: 'SSC Guidelines' },
  ],
  contexts: ['adult', 'immunocompetent', 'community'],
  rules: [
    { id: 'rule_pneumonia_severity', description: 'Calculate CURB-65 for pneumonia severity', when: 'diagnosis == pneumonia', then: 'calculate CURB-65 score', priority: 1 },
    { id: 'rule_pneumonia_icu', description: 'Admit to ICU if CURB-65 >= 3', when: 'CURB-65 >= 3', then: 'recommend ICU admission', priority: 2 },
  ],
  documentation: [
    { object: 'dx_pneumonia', template: 'Patient presents with {{duration}} of {{cough_character}} cough, fever, and dyspnea. Chest X-ray shows {{xray_findings}}. Diagnosed with community-acquired pneumonia.', variables: ['duration', 'cough_character', 'xray_findings'] },
  ],
};

const malariaYaml: YamlKnowledgePackage = {
  id: 'pkg_malaria',
  name: 'Malaria Knowledge Package',
  version: '1.0.0',
  description: 'Malaria: symptoms, mechanisms, diagnostics, treatment',
  symptom: 'fever',
  disease: 'malaria',
  objects: [
    { id: 'sym_fever_m', type: 'symptom', name: 'Fever', aliases: ['pyrexia'], severity: 'moderate', onset: 'acute' },
    { id: 'sym_chills', type: 'symptom', name: 'Chills and Rigors', description: 'Severe shaking chills' },
    { id: 'sym_headache_m', type: 'symptom', name: 'Headache', description: 'Often severe and frontal' },
    { id: 'sym_muscle_pain', type: 'symptom', name: 'Myalgia', description: 'Generalized muscle aches' },
    { id: 'sym_nausea_m', type: 'symptom', name: 'Nausea and Vomiting', description: 'GI symptoms common' },
    { id: 'mech_parasitemia', type: 'mechanism', name: 'Parasitemia', description: 'Plasmodium in blood' },
    { id: 'mech_hemolysis', type: 'mechanism', name: 'Hemolysis', description: 'Red blood cell destruction' },
    { id: 'phen_anemia', type: 'phenotype', name: 'Anemia', description: 'Low hemoglobin' },
    { id: 'phen_thrombocytopenia', type: 'phenotype', name: 'Thrombocytopenia', description: 'Low platelets' },
    { id: 'phen_splenomegaly', type: 'phenotype', name: 'Splenomegaly', description: 'Enlarged spleen' },
    { id: 'dx_malaria', type: 'disease', name: 'Malaria', description: 'Parasitic infection by Plasmodium species', severity: 'severe', properties: { icd10: 'B50-B54', species: ['P. falciparum', 'P. vivax', 'P. ovale', 'P. malariae'] } },
    { id: 'dx_severe_malaria', type: 'complication', name: 'Severe Malaria', description: 'Life-threatening organ dysfunction', severity: 'severe', properties: { criteria: ['cerebral malaria', 'severe anemia', 'respiratory distress', 'acidosis'] } },
    { id: 'inv_rdt', type: 'investigation', name: 'RDT', description: 'Rapid Diagnostic Test', properties: { priority: 1, turnaround: '15 minutes' } },
    { id: 'inv_blood_smear', type: 'investigation', name: 'Blood Smear', description: 'Thick and thin films', properties: { priority: 1, turnaround: '1 hour' } },
    { id: 'trt_artemisinin', type: 'treatment', name: 'Artemisinin Combination Therapy', description: 'First-line treatment' },
    { id: 'drug_artemether_lumefantrine', type: 'drug', name: 'Artemether/Lumefantrine', description: 'First-line ACT', properties: { dose: 'weight-based', duration: '3 days' } },
  ],
  relationships: [
    { source: 'sym_fever_m', target: 'mech_parasitemia', type: 'has_mechanism', confidence: 0.9 },
    { source: 'sym_chills', target: 'mech_parasitemia', type: 'has_mechanism', confidence: 0.85 },
    { source: 'sym_headache_m', target: 'mech_parasitemia', type: 'has_mechanism', confidence: 0.6 },
    { source: 'sym_muscle_pain', target: 'mech_parasitemia', type: 'has_mechanism', confidence: 0.5 },
    { source: 'mech_parasitemia', target: 'phen_anemia', type: 'produces', confidence: 0.8 },
    { source: 'mech_hemolysis', target: 'phen_anemia', type: 'produces', confidence: 0.9 },
    { source: 'mech_parasitemia', target: 'phen_thrombocytopenia', type: 'produces', confidence: 0.7 },
    { source: 'mech_parasitemia', target: 'phen_splenomegaly', type: 'produces', confidence: 0.75 },
    { source: 'phen_anemia', target: 'dx_malaria', type: 'suggests', confidence: 0.7 },
    { source: 'phen_thrombocytopenia', target: 'dx_malaria', type: 'suggests', confidence: 0.6 },
    { source: 'phen_splenomegaly', target: 'dx_malaria', type: 'suggests', confidence: 0.65 },
    { source: 'dx_malaria', target: 'dx_severe_malaria', type: 'complicates', confidence: 0.3 },
    { source: 'dx_malaria', target: 'inv_rdt', type: 'investigates', evidence: 'WHO Guidelines 2023' },
    { source: 'dx_malaria', target: 'inv_blood_smear', type: 'investigates', evidence: 'WHO Guidelines 2023' },
    { source: 'dx_malaria', target: 'trt_artemisinin', type: 'treats', confidence: 0.95 },
  ],
  contexts: ['endemic_region', 'tropical', 'all_ages'],
  rules: [
    { id: 'rule_malaria_severe', description: 'Assess for severe malaria criteria', when: 'diagnosis == malaria', then: 'check for severe malaria features', priority: 1 },
  ],
};

const utiYaml: YamlKnowledgePackage = {
  id: 'pkg_uti',
  name: 'UTI Knowledge Package',
  version: '1.0.0',
  description: 'Urinary Tract Infection: symptoms, diagnostics, treatment',
  symptom: 'dysuria',
  disease: 'uti',
  objects: [
    { id: 'sym_dysuria', type: 'symptom', name: 'Dysuria', description: 'Painful urination' },
    { id: 'sym_frequency', type: 'symptom', name: 'Urinary Frequency', description: 'Increased urination frequency' },
    { id: 'sym_urgency', type: 'symptom', name: 'Urgency', description: 'Sudden strong need to urinate' },
    { id: 'sym_suprapubic_pain', type: 'symptom', name: 'Suprapubic Pain', description: 'Pain above the pubic bone' },
    { id: 'sym_hematuria', type: 'symptom', name: 'Hematuria', description: 'Blood in urine' },
    { id: 'mech_bacterial_colonization', type: 'mechanism', name: 'Bacterial Colonization', description: 'Pathogens in urinary tract' },
    { id: 'mech_mucosal_inflammation', type: 'mechanism', name: 'Mucosal Inflammation', description: 'Inflammation of bladder lining' },
    { id: 'dx_uti', type: 'disease', name: 'Urinary Tract Infection', description: 'Bacterial infection of the urinary tract', severity: 'mild', properties: { icd10: 'N39.0', common_pathogens: ['E. coli', 'K. pneumoniae', 'Proteus'] } },
    { id: 'dx_pyelonephritis', type: 'disease', name: 'Acute Pyelonephritis', description: 'Kidney infection', severity: 'severe', properties: { icd10: 'N10' } },
    { id: 'inv_urinalysis', type: 'investigation', name: 'Urinalysis', description: 'Dipstick and microscopy', properties: { priority: 1, typical_findings: 'nitrites+, leukocytes+, WBCs' } },
    { id: 'inv_urine_culture', type: 'investigation', name: 'Urine Culture', description: 'Mid-stream specimen', properties: { priority: 2, turnaround: '48 hours' } },
    { id: 'trt_antibiotics_uti', type: 'treatment', name: 'Antibiotics', description: 'Empiric antibiotic for UTI' },
    { id: 'drug_nitrofurantoin', type: 'drug', name: 'Nitrofurantoin', description: 'First-line for uncomplicated UTI', properties: { dose: '100mg BD', duration: '5 days' } },
  ],
  relationships: [
    { source: 'sym_dysuria', target: 'mech_mucosal_inflammation', type: 'has_mechanism', confidence: 0.9 },
    { source: 'sym_frequency', target: 'mech_mucosal_inflammation', type: 'has_mechanism', confidence: 0.7 },
    { source: 'sym_urgency', target: 'mech_mucosal_inflammation', type: 'has_mechanism', confidence: 0.7 },
    { source: 'sym_suprapubic_pain', target: 'mech_mucosal_inflammation', type: 'has_mechanism', confidence: 0.8 },
    { source: 'mech_bacterial_colonization', target: 'mech_mucosal_inflammation', type: 'produces', confidence: 0.9 },
    { source: 'mech_mucosal_inflammation', target: 'dx_uti', type: 'suggests', confidence: 0.9 },
    { source: 'dx_uti', target: 'dx_pyelonephritis', type: 'complicates', confidence: 0.2 },
    { source: 'dx_uti', target: 'inv_urinalysis', type: 'investigates', evidence: 'EAU Guidelines 2023' },
    { source: 'dx_uti', target: 'inv_urine_culture', type: 'investigates', evidence: 'IDSA Guidelines' },
    { source: 'dx_uti', target: 'trt_antibiotics_uti', type: 'treats', confidence: 0.95 },
    { source: 'dx_pyelonephritis', target: 'inv_urinalysis', type: 'investigates' },
    { source: 'dx_pyelonephritis', target: 'inv_urine_culture', type: 'investigates' },
  ],
  contexts: ['adult', 'female', 'outpatient'],
  rules: [
    { id: 'rule_uti_uncomplicated', description: 'If uncomplicated UTI, treat empirically', when: 'no fever, no flank pain', then: 'prescribe nitrofurantoin', priority: 1 },
    { id: 'rule_uti_complicated', description: 'If complicated UTI, require culture', when: 'fever or flank pain or male or pregnancy', then: 'order culture and imaging', priority: 2 },
  ],
};

export const EXAMPLE_PACKAGES = [
  parser.parseObject(pneumoniaYaml),
  parser.parseObject(malariaYaml),
  parser.parseObject(utiYaml),
];

export { pneumoniaYaml, malariaYaml, utiYaml };