// ═══════════════════════════════════════════════════════════════════════════════
// Vomiting Manifestation Profiles
// Every disease that causes vomiting describes its typical vomiting pattern here.
// The engine uses these to ask discriminating questions and generate better HPI.
// ═══════════════════════════════════════════════════════════════════════════════

import type { VomitingManifestation } from '../diseaseNode';

/**
 * Vomiting manifestation profiles mapped by diseaseId.
 * Only diseases that commonly cause vomiting need an entry.
 * Diseases already defined in abdominal pain nodes are referenced by their existing ID.
 */
export const VOMITING_MANIFESTATIONS: Record<string, VomitingManifestation> = {

  // ── SURGICAL GI ───────────────────────────────────────────

  acute_appendicitis: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'sometimes',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: false,
    typicalDescription: 'Mild vomiting (1-3 episodes) that begins AFTER the pain onset. Non-projectile, non-feculent. Does not relieve the pain. Often preceded by nausea and anorexia.',
  },

  intestinal_obstruction: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'moderate_3_5',
    bilious: 'often',
    projectile: 'sometimes',
    feculent: 'often',
    reliefAfterVomiting: true,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'bile',
    associatedNausea: 'always',
    vomitingIsPrimary: false,
    typicalDescription: 'Repeated vomiting that may become bilious and later feculent in late obstruction. Vomiting may temporarily relieve distension and pain. High frequency indicates complete obstruction.',
  },

  perforated_peptic_ulcer: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Vomiting is not the dominant feature. May vomit once or twice after the sudden severe pain. Vomitus is typically stomach contents without bile.',
  },

  acute_cholecystitis: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'sometimes',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting accompany the RUQ pain, often after fatty meals. Vomiting is not severe (1-3 episodes) and does not relieve pain.',
  },

  acute_pancreatitis: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'severe_5_plus',
    bilious: 'often',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'bile',
    associatedNausea: 'always',
    vomitingIsPrimary: false,
    typicalDescription: 'Persistent, severe vomiting that does NOT relieve the epigastric pain. Patient often cannot keep anything down. Vomitus is bilious. A hallmark: vomiting is intractable.',
  },

  gastroenteritis: {
    timingRelativeToPain: 'before',
    typicalFrequency: 'moderate_3_5',
    bilious: 'sometimes',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: false,
    typicalDescription: 'Vomiting often begins BEFORE abdominal pain or simultaneously. Typically self-limited, associated with diarrhoea. Vomitus is stomach contents then bile.',
  },

  diverticulitis: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and occasional vomiting accompany the LLQ pain. Vomiting is not a dominant feature — present in about 20% of cases.',
  },

  // ── BOWEL OBSTRUCTION VARIANTS ────────────────────────────

  volvulus: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'severe_5_plus',
    bilious: 'always',
    projectile: 'sometimes',
    feculent: 'often',
    reliefAfterVomiting: true,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'bile',
    associatedNausea: 'always',
    vomitingIsPrimary: false,
    typicalDescription: 'Rapid-onset, severe vomiting. Early bilious vomiting (especially in sigmoid or caecal volvulus). May become feculent. Vomiting may temporarily relieve pain.',
  },

  intussusception: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'often',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: true,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'bile',
    associatedNausea: 'always',
    vomitingIsPrimary: false,
    typicalDescription: 'Vomiting occurs in episodes, often associated with colicky abdominal pain. May become bilious. Redcurrant jelly stool is late sign. Classic in infants with drawing-up of legs.',
  },

  incarcerated_hernia: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'moderate_3_5',
    bilious: 'sometimes',
    projectile: 'never',
    feculent: 'often',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: false,
    typicalDescription: 'Vomiting begins after groin or abdominal wall pain. Progresses from stomach contents to bilious to feculent as obstruction worsens.',
  },

  mesenteric_ischaemia: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'moderate_3_5',
    bilious: 'sometimes',
    projectile: 'never',
    feculent: 'sometimes',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Vomiting is common but not the dominant feature. Pain is out of proportion to examination. Vomitus may be bilious and later bloody.',
  },

  // ── HEPATOBILIARY ─────────────────────────────────────────

  cholangitis: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'sometimes',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting accompany the classic Charcot triad (RUQ pain, fever, jaundice). Vomiting is not the dominant feature.',
  },

  hepatitis: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_immediate',
    morningPredominance: true,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting are prominent prodromal symptoms before jaundice appears. Morning nausea is classic. Vomiting is non-bilious and mild.',
  },

  // ── PANCREATIC ────────────────────────────────────────────

  pancreatic_cancer: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting are common but mild. Often worse after meals. Associated with weight loss, anorexia, and epigastric pain radiating to back.',
  },

  // ── METABOLIC / ENDOCRINE ─────────────────────────────────

  dka: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'severe_5_plus',
    bilious: 'sometimes',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: true,
    typicalDescription: 'Profuse vomiting driven by acidosis. Often the presenting symptom of DKA. Associated with polyuria, polydipsia, dehydration, and Kussmaul breathing. Vomiting is intractable until acidosis corrects.',
  },

  addisonian_crisis: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'severe_5_plus',
    bilious: 'sometimes',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: true,
    typicalDescription: 'Persistent vomiting is a hallmark of adrenal crisis. Accompanied by abdominal pain, hypotension, hyperpigmentation, and hyponatraemia. Vomiting is intractable and contributes to circulatory collapse.',
  },

  hypercalcaemia: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Mild nausea and vomiting associated with constipation, confusion, and polyuria. Stones, bones, groans, psychiatric overtones.',
  },

  porphyria: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'moderate_3_5',
    bilious: 'sometimes',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Vomiting accompanies severe colicky abdominal pain, neuropsychiatric symptoms, and pink urine. Attacks are episodic.',
  },

  // ── PREGNANCY / OBSTETRIC ─────────────────────────────────

  hyperemesis_gravidarum: {
    timingRelativeToPain: 'no_pain',
    typicalFrequency: 'severe_5_plus',
    bilious: 'sometimes',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: true,
    typicalDescription: 'Severe, persistent vomiting in early pregnancy that leads to dehydration, weight loss, and electrolyte disturbance. Differs from morning sickness in severity and persistence throughout the day.',
  },

  ectopic_pregnancy: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting may occur but are not the dominant features. Pain and vaginal bleeding are key. Always suspect in reproductive-age woman with abdominal pain.',
  },

  // ── NEUROLOGICAL ──────────────────────────────────────────

  raised_icp: {
    timingRelativeToPain: 'no_pain',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'often',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: true,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'sometimes',
    vomitingIsPrimary: true,
    typicalDescription: 'Classic early-morning or postural vomiting that may be projectile. Often NOT preceded by nausea. Associated with headache, visual disturbances, and neurological deficits. Vomiting is due to direct medullary stimulation.',
  },

  migraine: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: true,
    relationToEating: 'unrelated',
    morningPredominance: true,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting commonly accompany migraine headaches. Vomiting may actually abort the migraine attack. Associated with photophobia, phonophobia, and visual aura.',
  },

  // ── TOXICOLOGICAL / DRUG ──────────────────────────────────

  organophosphate: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'severe_5_plus',
    bilious: 'sometimes',
    projectile: 'sometimes',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: true,
    typicalDescription: 'Profuse vomiting is an early sign of organophosphate poisoning. Accompanied by excessive salivation, lacrimation, urination, defecation, bronchospasm, and miosis (SLUDGE syndrome).',
  },

  // ── CARDIAC ───────────────────────────────────────────────

  inferior_mi: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting can be the presenting symptoms of inferior STEMI due to diaphragmatic irritation. Often dismissed as gastritis. Associated with chest discomfort, diaphoresis, and dyspnoea.',
  },

  // ── PYLORIC / GASTRIC OUTLET ──────────────────────────────

  gastric_outlet_obstruction: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'moderate_3_5',
    bilious: 'never',
    projectile: 'sometimes',
    feculent: 'never',
    reliefAfterVomiting: true,
    relationToEating: 'after_delayed',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: false,
    typicalDescription: 'Non-bilious vomiting of undigested or partially digested food eaten hours earlier. Vomiting provides relief. Peristaltic waves may be visible. Classic projectile vomiting in infants suggests pyloric stenosis.',
  },

  peptic_ulcer_disease: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: true,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and occasional vomiting may occur. In gastric ulcer, vomiting may relieve pain. In duodenal ulcer, vomiting is less common. Haematemesis indicates erosion into a vessel.',
  },

  // ── CYCLIC VOMITING ───────────────────────────────────────

  cyclic_vomiting: {
    timingRelativeToPain: 'no_pain',
    typicalFrequency: 'severe_5_plus',
    bilious: 'often',
    projectile: 'sometimes',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: true,
    typicalAppearance: 'bile',
    associatedNausea: 'always',
    vomitingIsPrimary: true,
    typicalDescription: 'Stereotyped episodes of intense vomiting lasting hours to days, with complete resolution between episodes. Episodes are identical in timing and intensity. Often triggered by stress or illness. No abdominal pain outside episodes.',
  },

  gastroparesis: {
    timingRelativeToPain: 'no_pain',
    typicalFrequency: 'moderate_3_5',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: true,
    relationToEating: 'after_delayed',
    morningPredominance: true,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: true,
    typicalDescription: 'Post-prandial vomiting of undigested food hours after eating. Early satiety, bloating, and epigastric discomfort. Common in diabetics with autonomic neuropathy. Vomiting provides relief of fullness.',
  },

  bulimia_nervosa: {
    timingRelativeToPain: 'no_pain',
    typicalFrequency: 'moderate_3_5',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'rare',
    vomitingIsPrimary: true,
    typicalDescription: 'Self-induced vomiting after binge eating. Patient may be secretive. Dental erosion, parotid swelling, Russell sign (knuckle calluses), and electrolyte disturbances. Vomiting is volitional, not reflex.',
  },

  // ── INFECTIOUS ────────────────────────────────────────────

  typhoid: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'sometimes',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and occasional vomiting in the first week. Step-ladder fever, relative bradycardia, rose spots, and abdominal pain dominate. Intestinal perforation is a late complication.',
  },

  malaria: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting accompany the fever cycles. Headache, myalgia, and splenomegaly are more prominent. In severe malaria, vomiting may contribute to dehydration.',
  },

  // ── PAEDIATRIC ────────────────────────────────────────────

  nec: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'moderate_3_5',
    bilious: 'often',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'bile',
    associatedNausea: 'often',
    vomitingIsPrimary: true,
    typicalDescription: 'Bilious vomiting in a neonate is NEC until proven otherwise. Associated with feeding intolerance, abdominal distension, and bloody stools. Seen in premature or low-birth-weight infants.',
  },

  malrotation: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'moderate_3_5',
    bilious: 'always',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'bile',
    associatedNausea: 'often',
    vomitingIsPrimary: true,
    typicalDescription: 'Bilious vomiting in a neonate is malrotation/midgut volvulus until proven otherwise. This is a surgical emergency. The infant may pass normal stools initially.',
  },

  hirschsprung: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'moderate_3_5',
    bilious: 'often',
    projectile: 'never',
    feculent: 'sometimes',
    reliefAfterVomiting: true,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'bile',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Vomiting is a late sign of Hirschsprung disease, indicating enterocolitis or complete obstruction. Bilious or feculent vomiting, abdominal distension, and failure to pass meconium.',
  },

  // ── VESTIBULAR (new disease IDs) ──────────────────────────

  vestibular_neuritis: {
    timingRelativeToPain: 'no_pain',
    typicalFrequency: 'moderate_3_5',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: true,
    typicalDescription: 'Sudden onset of severe vertigo with nausea and vomiting. No hearing loss. Nystagmus is present. Vomiting is driven by the vestibular mismatch — any head movement triggers it.',
  },

  labyrinthitis: {
    timingRelativeToPain: 'no_pain',
    typicalFrequency: 'moderate_3_5',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: true,
    typicalDescription: 'Vertigo with hearing loss and tinnitus. Nausea and vomiting are proportional to vertigo severity. May follow a viral upper respiratory infection.',
  },

  // ── GI ESOPHAGEAL ────────────────────────────────────────

  gerd: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: true,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Regurgitation of stomach contents, often after meals or when bending over. Heartburn is the dominant symptom. Vomiting is effortless regurgitation rather than true vomiting.',
  },

  esophagitis: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and occasional vomiting accompany painful swallowing (odynophagia) and retrosternal chest pain. Vomiting is not the dominant feature.',
  },

  achalasia: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: true,
    relationToEating: 'after_delayed',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'sometimes',
    vomitingIsPrimary: false,
    typicalDescription: 'Regurgitation of undigested food eaten hours earlier, especially when lying down. Difficulty swallowing both solids and liquids. No bile in regurgitated material because the obstruction is above the lower oesophageal sphincter.',
  },

  // ── GI GASTRIC ───────────────────────────────────────────

  gastritis: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: true,
    relationToEating: 'after_immediate',
    morningPredominance: true,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: false,
    typicalDescription: 'Mild nausea and occasional vomiting associated with epigastric pain or burning. Worse after meals. May have morning predominance. Vomiting of small amounts of stomach contents provides some relief.',
  },

  functional_dyspepsia: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: true,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Chronic nausea and occasional vomiting with no identifiable organic cause. Post-prandial fullness and early satiety. Symptoms are longstanding and do not progress.',
  },

  gastric_cancer: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea, anorexia, and early satiety are more common than vomiting. Late-stage vomiting of undigested food suggests gastric outlet obstruction. Associated with weight loss and epigastric mass.',
  },

  boerhaave: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Violent vomiting or retching followed by sudden severe chest or epigastric pain. Subcutaneous emphysema. Vomiting was the CAUSE of the oesophageal rupture, not a symptom of it.',
  },

  mallory_weiss: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'moderate_3_5',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'blood',
    associatedNausea: 'often',
    vomitingIsPrimary: true,
    typicalDescription: 'Forceful retching and vomiting followed by haematemesis. The tear is caused by the vomiting itself. Typical history: heavy alcohol use or bulimia, then blood in vomit after repeated retching.',
  },

  // ── GI SMALL BOWEL (Inflammatory) ────────────────────────

  crohns_disease: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'sometimes',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting occur during flares, especially with small bowel involvement. May indicate stricture or obstruction. Associated with diarrhoea, weight loss, and RLQ pain.',
  },

  ulcerative_colitis: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'sometimes',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting are not typical features of UC. May occur in severe flares or with toxic megacolon. Bloody diarrhoea and tenesmus dominate.',
  },

  food_poisoning: {
    timingRelativeToPain: 'before',
    typicalFrequency: 'severe_5_plus',
    bilious: 'often',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: true,
    typicalDescription: 'Rapid onset of vomiting within hours of eating contaminated food. Often accompanies diarrhoea. Self-limited. Multiple affected individuals from same meal source.',
  },

  // ── HEPATOBILIARY (additional) ───────────────────────────

  alcoholic_hepatitis: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_immediate',
    morningPredominance: true,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting are common in alcoholic hepatitis, especially in the morning. Associated with anorexia, RUQ pain, jaundice, and fever.',
  },

  liver_abscess: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting accompany high fever, RUQ pain, and weight loss. Vomiting is not the dominant feature — fever and pain are.',
  },

  hcc: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting are late features. Associated with weight loss, RUQ pain, ascites, and known liver disease.',
  },

  // ── PANCREATIC (additional) ──────────────────────────────

  chronic_pancreatitis: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting during acute exacerbations of chronic pancreatitis. Epigastric pain radiating to back, steatorrhoea, and weight loss between attacks.',
  },

  pancreatic_pseudocyst: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting due to gastric compression by the pseudocyst. Epigastric mass and pain persist after acute pancreatitis has resolved.',
  },

  // ── INFECTIOUS (additional) ──────────────────────────────

  dengue: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting accompany high fever, severe myalgia (breakbone fever), and rash. Vomiting may indicate severe dengue with plasma leakage.',
  },

  leptospirosis: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting accompany fever, myalgia, and conjunctival suffusion. Weil disease adds jaundice and renal failure.',
  },

  brucellosis: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting occur during febrile episodes. Undulant fever, arthralgia, and hepatosplenomegaly dominate.',
  },

  ascariasis: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'sometimes',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: true,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting may occur, especially when worms migrate. Vomiting of a worm (Ascaris) is pathognomonic. Associated with periumbilical pain and malnutrition in children.',
  },

  // ── UROLOGICAL ───────────────────────────────────────────

  pyelonephritis: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting accompany high fever, rigors, and loin pain. Dysuria and urinary frequency are the key urinary symptoms.',
  },

  ureteric_colic: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting are common during the severe colicky pain. Pain dominates — vomiting is a reflex response to the severe pain.',
  },

  // ── RESPIRATORY ──────────────────────────────────────────

  pneumonia: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'sometimes',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting may occur, especially in lower lobe pneumonia presenting as abdominal pain. Fever, cough, and dyspnoea dominate.',
  },

  dvt_pe: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'sometimes',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting can occur in massive PE due to haemodynamic compromise. Dyspnoea, chest pain, and syncope dominate.',
  },

  // ── PAEDIATRIC (additional) ──────────────────────────────

  mesenteric_adenitis: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting accompany RLQ pain and fever in children. Clinically mimics appendicitis but symptoms are milder. Often preceded by viral upper respiratory infection.',
  },

  // ── HAEMATOLOGICAL ───────────────────────────────────────

  sickle_cell_crisis: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting accompany severe abdominal pain during vaso-occlusive crisis. History of sickle cell disease, bone pain, and jaundice.',
  },

  // ── VASCULAR ─────────────────────────────────────────────

  ischaemic_colitis: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting accompany LLQ pain and bloody diarrhoea. Older patient with vascular risk factors.',
  },

  // ── OBSTETRIC / GYNAECOLOGICAL (additional) ──────────────

  threatened_abortion: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting may persist from early pregnancy. Vaginal bleeding and cramping lower abdominal pain are the key features.',
  },

  ovarian_torsion: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting are common with the sudden, severe unilateral pelvic pain. Pain is the dominant feature — vomiting accompanies the acute onset.',
  },

  ovarian_cyst_rupture: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting accompany the sudden onset of pelvic pain after rupture. Peritoneal irritation from cyst fluid may cause vomiting.',
  },

  pid: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting may occur in severe PID. Lower abdominal pain, vaginal discharge, and fever dominate. Cervical motion tenderness on examination.',
  },

  // ── DRUG-INDUCED / TOXICOLOGICAL ─────────────────────────

  medication_induced: {
    timingRelativeToPain: 'no_pain',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: true,
    typicalDescription: 'Nausea and vomiting temporally related to starting a new medication. Common culprits: opioids, NSAIDs, metformin, antibiotics, digoxin. Resolves on stopping the drug. No abdominal pain.',
  },

  alcohol_withdrawal: {
    timingRelativeToPain: 'no_pain',
    typicalFrequency: 'moderate_3_5',
    bilious: 'sometimes',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: true,
    typicalAppearance: 'bile',
    associatedNausea: 'always',
    vomitingIsPrimary: true,
    typicalDescription: 'Morning vomiting in a heavy drinker. Part of the alcohol withdrawal syndrome. Associated with tremors, tachycardia, anxiety, and autonomic hyperactivity.',
  },

  // ── ADDITIONAL NODE-LINKED PROFILES ──────────────────────

  // ── ADDITIONAL NODE-LINKED PROFILES ──────────────────────



  coeliac_disease: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_delayed',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting are less common than diarrhoea and weight loss. May occur after gluten ingestion. Bloating and fatigue are almost always present.',
  },

  constipation: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'sometimes',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea may accompany severe constipation. True vomiting is uncommon unless there is impaction or overflow. Bloating and straining dominate.',
  },

  constipation_simple: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'sometimes',
    vomitingIsPrimary: false,
    typicalDescription: 'Mild nausea may accompany simple constipation. Vomiting is rare. Hard stools and infrequent bowel movements are the core symptoms.',
  },

  ibs: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_immediate',
    morningPredominance: true,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea is common in IBS, especially in the morning or before stressful events. True vomiting is less common. Relief with defecation and alternating bowel habits are key discriminators.',
  },

  infectious_colitis: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'sometimes',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting can occur in infectious colitis, especially with bacterial pathogens. Bloody diarrhoea, fever, and tenesmus dominate. Vomiting is less prominent than diarrhoea.',
  },

  amoebic_colitis: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting accompany bloody diarrhoea with mucus and tenesmus. Fever and RUQ pain may be present. History of travel to endemic areas.',
  },

  meckel_diverticulitis: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting accompany RLQ pain that mimics appendicitis. Painless rectal bleeding (currant jelly) is more characteristic. Vomiting is less prominent than in appendicitis.',
  },

  cystitis: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'sometimes',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea may occur in severe cystitis, but vomiting is uncommon unless there is upper tract involvement (pyelonephritis). Dysuria, frequency, and urgency dominate.',
  },

  testicular_torsion: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting are common due to the severity of the testicular pain. The vomiting is a reflex response to sudden, severe scrotal pain. Nausea is almost always present.',
  },

  epididymitis: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'sometimes',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea is mild and uncommon. Vomiting is rare. Gradual onset of testicular pain, swelling, and dysuria dominate. Fever may be present.',
  },

  aortic_dissection: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting can accompany the sudden, tearing chest or back pain. The catastrophic pain and haemodynamic instability dominate. Vomiting is a secondary autonomic response.',
  },

  splenic_infarct: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting accompany sudden LUQ pain, often with referred pain to the left shoulder. Fever may be present. The pain is the dominant feature.',
  },

  splenic_rupture: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting can occur after trauma with LUQ pain and signs of haemorrhagic shock. Kehr sign (referred shoulder pain) is classic.',
  },

  endometriosis: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea is common during menstrual periods, especially with severe dysmenorrhea. Vomiting is less common. Cyclical pelvic pain, dyspareunia, and infertility are the core features.',
  },

  adenomyosis: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'sometimes',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea may occur with severe menstrual cramping. Vomiting is uncommon. Heavy menstrual bleeding and an enlarged, tender uterus dominate.',
  },

  fibroids: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'sometimes',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea is rare with fibroids unless there is degeneration (painful, enlarging fibroid) or pregnancy. Heavy menstrual bleeding and pelvic pressure are the dominant symptoms.',
  },

  ovarian_cancer: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and early satiety are common due to ascites and omental disease. Vomiting may occur in late-stage disease with bowel involvement. Abdominal distension and bloating dominate.',
  },

  miscarriage: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea may persist from early pregnancy or resolve with pregnancy loss. Vaginal bleeding and cramping lower abdominal pain are the key features.',
  },

  placenta_praevia: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'sometimes',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting are not typical of placenta praevia. Painless vaginal bleeding in the third trimester is the hallmark. Any vomiting is likely incidental.',
  },

  placental_abruption: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting may accompany the sudden, severe abdominal pain and vaginal bleeding. Uterine hypertonicity and fetal distress are the key features.',
  },

  preterm_labour: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'sometimes',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea may occur with the pain of contractions. Vomiting is not a dominant feature. Regular painful contractions and cervical change define the condition.',
  },

  uterine_rupture: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting can occur with the sudden catastrophic pain of uterine rupture. Maternal tachycardia, fetal bradycardia, and loss of uterine contour dominate.',
  },

  henoch_schonlein_purpura: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting can accompany the colicky abdominal pain in HSP. Palpable purpura on the legs, arthralgia, and renal involvement are the key diagnostic features.',
  },

  // ── REMAINING EXISTING NODES WITHOUT PROFILES ────────────

  aaa_rupture: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting may occur with the sudden catastrophic abdominal or back pain of a ruptured AAA. The haemorrhagic shock and severe pain dominate. Vomiting is a secondary autonomic response.',
  },

  abdominal_tb: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting accompany chronic abdominal pain, weight loss, and night sweats. The presentation is indolent. Ascites and abdominal mass may be present.',
  },

  budd_chiari: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting accompany acute RUQ pain, hepatomegaly, and ascites due to hepatic vein thrombosis. Jaundice may develop. The onset is typically acute.',
  },

  colon_cancer: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'feculent',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting occur late in colon cancer, typically when obstruction develops. Vomiting becomes feculent with distal obstruction. Weight loss, hematochezia, and change in bowel habits precede it.',
  },

  functional_abdominal_pain: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'sometimes',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea may accompany functional abdominal pain, but vomiting is not typical. The pain is chronic, without organic cause, and often associated with psychosocial stressors.',
  },

  herpes_zoster: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'sometimes',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting are uncommon in herpes zoster. The burning, dermatomal pain and vesicular rash dominate. Abdominal involvement may cause ileus.',
  },

  hydronephrosis: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting can accompany the flank pain of acute hydronephrosis. The pain is colicky and radiates to the groin. Chronic hydronephrosis is typically painless.',
  },

  lead_poisoning: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea, vomiting, and abdominal colic are classic features of lead poisoning. Associated with constipation, neuropathy, and behavioural changes. History of occupational or environmental exposure.',
  },

  pericarditis: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'sometimes',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea is mild and uncommon. The sharp, pleuritic chest pain that improves when leaning forward dominates. Vomiting is rare unless there is associated inferior MI.',
  },

  rectus_sheath_haematoma: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'sometimes',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting are not typical. The key feature is a focal, tender abdominal wall mass that is accentuated by tensing the rectus muscles. Anticoagulant use is the major risk factor.',
  },

  renal_abscess: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting accompany high fever, rigors, and flank pain. The patient appears septic. Unlike pyelonephritis, symptoms persist beyond 72 hours of antibiotics.',
  },

  strangulated_hernia: {
    timingRelativeToPain: 'after',
    typicalFrequency: 'moderate_3_5',
    bilious: 'often',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'after_immediate',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'always',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting are prominent as the hernia becomes strangulated. The irreducible, tender hernia mass with overlying skin changes is the key finding. Feculent vomiting indicates late obstruction.',
  },

  urinary_retention: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'sometimes',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea may accompany the severe suprapubic pain of acute urinary retention. Vomiting is uncommon. The palpable, distended bladder with inability to void is diagnostic.',
  },

  vasculitis_pan: {
    timingRelativeToPain: 'independent',
    typicalFrequency: 'mild_1_3',
    bilious: 'never',
    projectile: 'never',
    feculent: 'never',
    reliefAfterVomiting: false,
    relationToEating: 'unrelated',
    morningPredominance: false,
    typicalAppearance: 'stomach_contents',
    associatedNausea: 'often',
    vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting accompany the systemic vasculitis. Abdominal pain from mesenteric involvement, along with skin rash, neuropathy, and renal involvement. Multi-system disease is the clue.',
  },

  // ── MISSING3 NODES ───────────────────────────────────────────

  meningitis: {
    timingRelativeToPain: 'before', typicalFrequency: 'moderate_3_5',
    bilious: 'sometimes', projectile: 'often', feculent: 'never',
    reliefAfterVomiting: false, relationToEating: 'unrelated',
    morningPredominance: true, typicalAppearance: 'stomach_contents',
    associatedNausea: 'always', vomitingIsPrimary: false,
    typicalDescription: 'Vomiting may precede headache. Often projectile. Worse in the morning. Associated with severe headache, fever, and neck stiffness.',
  },
  sepsis: {
    timingRelativeToPain: 'after', typicalFrequency: 'moderate_3_5',
    bilious: 'sometimes', projectile: 'sometimes', feculent: 'never',
    reliefAfterVomiting: false, relationToEating: 'unrelated',
    morningPredominance: false, typicalAppearance: 'stomach_contents',
    associatedNausea: 'always', vomitingIsPrimary: false,
    typicalDescription: 'Vomiting is common in sepsis due to systemic inflammation, ileus, and metabolic disturbance. Non-projectile, may be bilious.',
  },
  pyloric_stenosis: {
    timingRelativeToPain: 'before', typicalFrequency: 'severe_5_plus',
    bilious: 'never', projectile: 'always', feculent: 'never',
    reliefAfterVomiting: true, relationToEating: 'after_immediate',
    morningPredominance: false, typicalAppearance: 'stomach_contents',
    associatedNausea: 'sometimes', vomitingIsPrimary: true,
    typicalDescription: 'Classic projectile, non-bilious vomiting immediately after feeds in an infant 3-6 weeks old. Hungry after vomiting.',
  },
  esophageal_cancer: {
    timingRelativeToPain: 'before', typicalFrequency: 'moderate_3_5',
    bilious: 'never', projectile: 'never', feculent: 'never',
    reliefAfterVomiting: false, relationToEating: 'after_delayed',
    morningPredominance: false, typicalAppearance: 'stomach_contents',
    associatedNausea: 'often', vomitingIsPrimary: true,
    typicalDescription: 'Regurgitation of undigested food hours after eating, with progressive dysphagia to solids then liquids. Weight loss prominent.',
  },
  cannabis_hyperemesis: {
    timingRelativeToPain: 'before', typicalFrequency: 'severe_5_plus',
    bilious: 'sometimes', projectile: 'sometimes', feculent: 'never',
    reliefAfterVomiting: false, relationToEating: 'unrelated',
    morningPredominance: false, typicalAppearance: 'stomach_contents',
    associatedNausea: 'always', vomitingIsPrimary: true,
    typicalDescription: 'Cyclic episodes of severe vomiting in chronic cannabis users. Compulsive hot showers/baths provide temporary relief.',
  },
  cholera: {
    timingRelativeToPain: 'before', typicalFrequency: 'severe_5_plus',
    bilious: 'often', projectile: 'never', feculent: 'never',
    reliefAfterVomiting: false, relationToEating: 'unrelated',
    morningPredominance: false, typicalAppearance: 'bile',
    associatedNausea: 'always', vomitingIsPrimary: true,
    typicalDescription: 'Vomiting follows profuse rice-water diarrhoea in endemic area. Persistent, severe, leading to rapid dehydration. Afebrile.',
  },
  meniere_disease: {
    timingRelativeToPain: 'no_pain', typicalFrequency: 'moderate_3_5',
    bilious: 'sometimes', projectile: 'never', feculent: 'never',
    reliefAfterVomiting: false, relationToEating: 'unrelated',
    morningPredominance: false, typicalAppearance: 'stomach_contents',
    associatedNausea: 'always', vomitingIsPrimary: false,
    typicalDescription: 'Severe nausea and vomiting with acute vertigo attacks lasting 20min-12h. Fluctuating hearing loss, tinnitus, aural fullness.',
  },
  benign_positional_vertigo: {
    timingRelativeToPain: 'no_pain', typicalFrequency: 'mild_1_3',
    bilious: 'never', projectile: 'never', feculent: 'never',
    reliefAfterVomiting: false, relationToEating: 'unrelated',
    morningPredominance: false, typicalAppearance: 'stomach_contents',
    associatedNausea: 'often', vomitingIsPrimary: false,
    typicalDescription: 'Mild nausea/vomiting triggered by head position changes. Episodes last seconds to minutes. No hearing loss.',
  },
  thyrotoxicosis: {
    timingRelativeToPain: 'after', typicalFrequency: 'mild_1_3',
    bilious: 'sometimes', projectile: 'never', feculent: 'never',
    reliefAfterVomiting: false, relationToEating: 'after_immediate',
    morningPredominance: false, typicalAppearance: 'stomach_contents',
    associatedNausea: 'always', vomitingIsPrimary: false,
    typicalDescription: 'Nausea and vomiting with tachycardia, tremor, heat intolerance, weight loss. More prominent in thyroid storm with fever and altered mental state.',
  },
  psychogenic_vomiting: {
    timingRelativeToPain: 'no_pain', typicalFrequency: 'mild_1_3',
    bilious: 'never', projectile: 'never', feculent: 'never',
    reliefAfterVomiting: false, relationToEating: 'after_immediate',
    morningPredominance: true, typicalAppearance: 'stomach_contents',
    associatedNausea: 'always', vomitingIsPrimary: true,
    typicalDescription: 'Vomiting triggered by psychological stress, anxiety, or panic. Often before stressful events or during meals. Minimal abdominal pain.',
  },
  postoperative_nv: {
    timingRelativeToPain: 'after', typicalFrequency: 'mild_1_3',
    bilious: 'sometimes', projectile: 'never', feculent: 'never',
    reliefAfterVomiting: false, relationToEating: 'unrelated',
    morningPredominance: false, typicalAppearance: 'stomach_contents',
    associatedNausea: 'always', vomitingIsPrimary: false,
    typicalDescription: 'Postoperative nausea/vomiting from anaesthetic agents, opioids, and surgical manipulation. Typically resolves within 24 hours.',
  },
  acute_liver_failure: {
    timingRelativeToPain: 'after', typicalFrequency: 'moderate_3_5',
    bilious: 'sometimes', projectile: 'never', feculent: 'never',
    reliefAfterVomiting: false, relationToEating: 'unrelated',
    morningPredominance: false, typicalAppearance: 'stomach_contents',
    associatedNausea: 'always', vomitingIsPrimary: false,
    typicalDescription: 'Vomiting from hepatic encephalopathy and metabolic disturbance. Associated with jaundice, coagulopathy, altered mental state.',
  },
};

/** Get all disease IDs that have vomiting manifestations */
export function getVomitingDiseaseIds(): string[] {
  return Object.keys(VOMITING_MANIFESTATIONS);
}

/** Get the vomiting manifestation for a specific disease */
export function getVomitingManifestation(diseaseId: string): VomitingManifestation | undefined {
  return VOMITING_MANIFESTATIONS[diseaseId];
}

/** Check if a disease has a vomiting manifestation */
export function hasVomitingManifestation(diseaseId: string): boolean {
  return diseaseId in VOMITING_MANIFESTATIONS;
}
