import type { SymptomQuestion, ClinicalObjectiveGroup, FactExtractionRule } from '../symptom-types';

export const FAMILY_OBJECTIVES: ClinicalObjectiveGroup[] = [
  { id: 'obj_family_structure', label: 'Family Structure', description: 'Document family composition and health', order: 1, required: true, questionIds: ['family_q_structure', 'family_q_hereditary'] },
  { id: 'obj_family_diseases', label: 'Family Diseases', description: 'Family history of significant diseases', order: 2, required: true, questionIds: ['family_q_diabetes', 'family_q_hypertension', 'family_q_asthma', 'family_q_tb', 'family_q_cancer', 'family_q_mental', 'family_q_sickle', 'family_q_heart'] },
  { id: 'obj_family_genetic', label: 'Genetic/Congenital', description: 'Family history of genetic or congenital conditions', order: 3, required: false, questionIds: ['family_q_congenital'] },
];

export const FAMILY_QUESTIONS: SymptomQuestion[] = [
  {
    id: 'family_q_structure',
    text: 'Who are the members of your immediate family?',
    alternatives: [
      { condition: { ageMax: 5 }, text: 'Who does the child live with?' },
    ],
    type: 'text',
    required: true,
    importance: 2,
    reasoningWeight: 10,
    factKey: 'family_structure',
    documentationPhrase: 'Family composition: {value}',
  },
  {
    id: 'family_q_hereditary',
    text: 'Is there any family history of hereditary or genetic conditions?',
    alternatives: [],
    type: 'boolean',
    required: true,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'family_hereditary',
    documentationPhrase: 'Family history of hereditary conditions: {value}',
  },
  {
    id: 'family_q_hypertension',
    text: 'Family history of high blood pressure?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'family_hypertension',
    documentationPhrase: 'Family history of hypertension',
  },
  {
    id: 'family_q_diabetes',
    text: 'Family history of diabetes?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'family_diabetes',
    documentationPhrase: 'Family history of diabetes mellitus',
  },
  {
    id: 'family_q_asthma',
    text: 'Family history of asthma or allergies?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 1,
    reasoningWeight: 10,
    factKey: 'family_asthma',
    documentationPhrase: 'Family history of asthma',
  },
  {
    id: 'family_q_tb',
    text: 'Family history of TB?',
    alternatives: [],
    type: 'boolean',
    required: true,
    importance: 3,
    reasoningWeight: 30,
    factKey: 'family_tb',
    documentationPhrase: 'Family history of tuberculosis',
  },
  {
    id: 'family_q_cancer',
    text: 'Family history of cancer?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'family_cancer',
    documentationPhrase: 'Family history of cancer',
  },
  {
    id: 'family_q_mental',
    text: 'Family history of mental illness?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 1,
    reasoningWeight: 10,
    factKey: 'family_mental',
    documentationPhrase: 'Family history of mental illness',
  },
  {
    id: 'family_q_sickle',
    text: 'Family history of sickle cell disease or trait?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'family_sickle',
    documentationPhrase: 'Family history of sickle cell disease',
  },
  {
    id: 'family_q_heart',
    text: 'Family history of heart disease (especially early onset <50 years)?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'family_heart_disease',
    documentationPhrase: 'Family history of heart disease',
  },
  {
    id: 'family_q_congenital',
    text: 'Does anyone in the family have a congenital or birth defect?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 1,
    reasoningWeight: 15,
    factKey: 'family_congenital',
    documentationPhrase: 'Family history of congenital condition',
  },
];

export const FAMILY_FACT_EXTRACTION: FactExtractionRule[] = [
  { questionId: 'family_q_structure', extract: (a) => [{ key: 'family_structure', value: String(a), type: 'reported', questionId: 'family_q_structure', documentationPhrase: 'Family: ' + String(a) }] },
  { questionId: 'family_q_hereditary', extract: (a) => [{ key: 'family_hereditary', value: a ? true : false, type: 'reported', questionId: 'family_q_hereditary', documentationPhrase: 'Hereditary conditions in family' }] },
  { questionId: 'family_q_hypertension', extract: (a) => a ? [{ key: 'family_hypertension', value: true, type: 'reported', questionId: 'family_q_hypertension', documentationPhrase: 'Family history of hypertension' }] : [] },
  { questionId: 'family_q_diabetes', extract: (a) => a ? [{ key: 'family_diabetes', value: true, type: 'reported', questionId: 'family_q_diabetes', documentationPhrase: 'Family history of diabetes' }] : [] },
  { questionId: 'family_q_asthma', extract: (a) => a ? [{ key: 'family_asthma', value: true, type: 'reported', questionId: 'family_q_asthma', documentationPhrase: 'Family history of asthma' }] : [] },
  { questionId: 'family_q_tb', extract: (a) => a ? [{ key: 'family_tb', value: true, type: 'reported', questionId: 'family_q_tb', documentationPhrase: 'Family history of TB' }] : [] },
  { questionId: 'family_q_cancer', extract: (a) => a ? [{ key: 'family_cancer', value: true, type: 'reported', questionId: 'family_q_cancer', documentationPhrase: 'Family history of cancer' }] : [] },
  { questionId: 'family_q_mental', extract: (a) => a ? [{ key: 'family_mental', value: true, type: 'reported', questionId: 'family_q_mental', documentationPhrase: 'Family history of mental illness' }] : [] },
  { questionId: 'family_q_sickle', extract: (a) => a ? [{ key: 'family_sickle', value: true, type: 'reported', questionId: 'family_q_sickle', documentationPhrase: 'Family history of sickle cell' }] : [] },
  { questionId: 'family_q_heart', extract: (a) => a ? [{ key: 'family_heart_disease', value: true, type: 'reported', questionId: 'family_q_heart', documentationPhrase: 'Family history of heart disease' }] : [] },
  { questionId: 'family_q_congenital', extract: (a) => a ? [{ key: 'family_congenital', value: true, type: 'reported', questionId: 'family_q_congenital', documentationPhrase: 'Family history of congenital condition' }] : [] },
];
