import type { SymptomQuestion, ClinicalObjectiveGroup, FactExtractionRule } from '../symptom-types';

export const GROWTH_OBJECTIVES: ClinicalObjectiveGroup[] = [
  { id: 'obj_growth_params', label: 'Growth Parameters', description: 'Document current growth measurements', order: 1, required: true, questionIds: ['growth_q_weight', 'growth_q_height', 'growth_q_hc'] },
  { id: 'obj_growth_trend', label: 'Growth Trend', description: 'Document growth trajectory', order: 2, required: true, questionIds: ['growth_q_birth_weight', 'growth_q_growth_curve'] },
  { id: 'obj_development', label: 'Developmental Milestones', description: 'Assess developmental progress', order: 3, required: true, questionIds: ['growth_q_motor', 'growth_q_language', 'growth_q_social', 'growth_q_concern'] },
];

export const GROWTH_QUESTIONS: SymptomQuestion[] = [
  {
    id: 'growth_q_weight',
    text: 'What is the child\'s current weight?',
    alternatives: [],
    type: 'text',
    required: true,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'growth_current_weight',
    documentationPhrase: 'Current weight: {value} kg',
  },
  {
    id: 'growth_q_height',
    text: 'What is the child\'s current height/length?',
    alternatives: [],
    type: 'text',
    required: false,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'growth_current_height',
    documentationPhrase: 'Current height: {value} cm',
  },
  {
    id: 'growth_q_hc',
    text: 'What is the head circumference?',
    alternatives: [
      { condition: { ageMin: 2 }, text: '', type: 'boolean' },
    ],
    type: 'text',
    required: false,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'growth_hc',
    documentationPhrase: 'Head circumference: {value} cm',
  },
  {
    id: 'growth_q_birth_weight',
    text: 'What was the birth weight?',
    alternatives: [],
    type: 'chips',
    chips: ['Normal (>2.5 kg)', 'Low birth weight (1.5-2.5 kg)', 'Very low birth weight (<1.5 kg)', 'Unknown'],
    required: true,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'growth_birth_weight',
    documentationPhrase: 'Birth weight: {value}',
  },
  {
    id: 'growth_q_growth_curve',
    text: 'Has the child\'s growth been following the expected curve?',
    alternatives: [],
    type: 'chips',
    chips: ['Following curve well', 'Faltering / plateau', 'Crossing centiles downward', 'Always been small', 'Unknown'],
    required: false,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'growth_trend',
    documentationPhrase: 'Growth trend: {value}',
  },
  {
    id: 'growth_q_motor',
    text: 'Has the child achieved age-appropriate motor milestones? (head control, sitting, crawling, walking)',
    alternatives: [],
    type: 'chips',
    chips: ['Achieved on time', 'Slightly delayed', 'Significantly delayed', 'Regressing (lost skills)', 'Unsure'],
    required: true,
    importance: 3,
    reasoningWeight: 25,
    factKey: 'growth_motor_milestones',
    documentationPhrase: 'Motor milestones: {value}',
  },
  {
    id: 'growth_q_language',
    text: 'How is the child\'s language development? (babbling, words, sentences)',
    alternatives: [],
    type: 'chips',
    chips: ['Appropriate for age', 'Delayed speech', 'Not speaking at all', 'Lost language skills', 'Unsure'],
    required: false,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'growth_language',
    documentationPhrase: 'Language development: {value}',
  },
  {
    id: 'growth_q_social',
    text: 'How is the child\'s social development? (smiling, playing, interacting)',
    alternatives: [],
    type: 'chips',
    chips: ['Appropriate for age', 'Poor eye contact', 'Not interactive', 'Withdrawn', 'Unsure'],
    required: false,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'growth_social',
    documentationPhrase: 'Social development: {value}',
  },
  {
    id: 'growth_q_concern',
    text: 'Do you have any concerns about the child\'s growth or development?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'growth_concern',
    documentationPhrase: 'Parental concern about growth/development',
  },
];

export const GROWTH_FACT_EXTRACTION: FactExtractionRule[] = [
  { questionId: 'growth_q_weight', extract: (a) => a ? [{ key: 'growth_current_weight', value: String(a), type: 'reported', questionId: 'growth_q_weight', documentationPhrase: 'Weight: ' + String(a) + ' kg' }] : [] },
  { questionId: 'growth_q_height', extract: (a) => a ? [{ key: 'growth_current_height', value: String(a), type: 'reported', questionId: 'growth_q_height', documentationPhrase: 'Height: ' + String(a) + ' cm' }] : [] },
  { questionId: 'growth_q_hc', extract: (a) => a ? [{ key: 'growth_hc', value: String(a), type: 'reported', questionId: 'growth_q_hc', documentationPhrase: 'HC: ' + String(a) + ' cm' }] : [] },
  { questionId: 'growth_q_birth_weight', extract: (a) => [{ key: 'growth_birth_weight', value: String(a), type: 'reported', questionId: 'growth_q_birth_weight', documentationPhrase: 'Birth weight: ' + String(a) }] },
  { questionId: 'growth_q_motor_milestones', extract: (a) => [{ key: 'growth_motor_milestones', value: String(a), type: 'reported', questionId: 'growth_q_motor_milestones', documentationPhrase: 'Motor: ' + String(a) }] },
  { questionId: 'growth_q_language', extract: (a) => a ? [{ key: 'growth_language', value: String(a), type: 'reported', questionId: 'growth_q_language', documentationPhrase: 'Language: ' + String(a) }] : [] },
  { questionId: 'growth_q_social', extract: (a) => a ? [{ key: 'growth_social', value: String(a), type: 'reported', questionId: 'growth_q_social', documentationPhrase: 'Social: ' + String(a) }] : [] },
  { questionId: 'growth_q_concern', extract: (a) => a ? [{ key: 'growth_concern', value: true, type: 'reported', questionId: 'growth_q_concern', documentationPhrase: 'Developmental concern raised' }] : [] },
];
