import type { SymptomQuestion, ClinicalObjectiveGroup, FactExtractionRule } from '../symptom-types';

export const IMMUNIZATION_OBJECTIVES: ClinicalObjectiveGroup[] = [
  { id: 'obj_immunization_status', label: 'Immunization Status', description: 'Document vaccination status against schedule', order: 1, required: true, questionIds: ['imm_q_vaccinated', 'imm_q_card_available', 'imm_q_missed_doses'] },
  { id: 'obj_immunization_details', label: 'Vaccine Details', description: 'Verify individual vaccines received', order: 2, required: true, questionIds: ['imm_q_bcg', 'imm_q_opv', 'imm_q_penta', 'imm_q_pcv', 'imm_q_rotavirus', 'imm_q_mr', 'imm_q_measles', 'imm_q_yellow_fever', 'imm_q_covid', 'imm_q_hpv'] },
  { id: 'obj_immunization_reactions', label: 'Post-Vaccination Reactions', description: 'Document adverse events following immunization', order: 3, required: false, questionIds: ['imm_q_reactions'] },
];

export const IMMUNIZATION_QUESTIONS: SymptomQuestion[] = [
  {
    id: 'imm_q_vaccinated',
    text: 'Is the child vaccinated / immunized?',
    alternatives: [
      { condition: { ageMax: 0.08 }, text: 'Has the baby received birth vaccinations? (BCG, OPV0)' },
      { condition: { ageMin: 18 }, text: 'Are your vaccinations up to date?' },
    ],
    type: 'boolean',
    required: true,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'immunization_vaccinated',
    documentationPhrase: 'Immunization status: up to date',
  },
  {
    id: 'imm_q_card_available',
    text: 'Is the immunization card / record available?',
    alternatives: [],
    type: 'boolean',
    required: true,
    importance: 1,
    reasoningWeight: 5,
    factKey: 'immunization_card',
    documentationPhrase: 'Immunization record available',
  },
  {
    id: 'imm_q_missed_doses',
    text: 'Are there any missed or delayed vaccinations?',
    alternatives: [],
    type: 'boolean',
    required: true,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'immunization_missed_doses',
    documentationPhrase: 'Missed vaccination doses',
  },
  {
    id: 'imm_q_bcg',
    text: 'BCG (tuberculosis) — given at birth?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 10,
    factKey: 'immunization_bcg',
    documentationPhrase: 'BCG given',
  },
  {
    id: 'imm_q_opv',
    text: 'Polio (OPV/IPV) — completed series?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 10,
    factKey: 'immunization_polio',
    documentationPhrase: 'Polio vaccination complete',
  },
  {
    id: 'imm_q_penta',
    text: 'Pentavalent (DPT-HepB-Hib) — 3 doses at 6, 10, 14 weeks?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 10,
    factKey: 'immunization_penta',
    documentationPhrase: 'Pentavalent complete',
  },
  {
    id: 'imm_q_pcv',
    text: 'Pneumococcal (PCV) — 3 doses?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 10,
    factKey: 'immunization_pcv',
    documentationPhrase: 'PCV complete',
  },
  {
    id: 'imm_q_rotavirus',
    text: 'Rotavirus vaccine — 2 doses at 6 and 10 weeks?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 10,
    factKey: 'immunization_rotavirus',
    documentationPhrase: 'Rotavirus vaccine given',
  },
  {
    id: 'imm_q_mr',
    text: 'Measles-Rubella (MR) — given at 9 months and 18 months?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 10,
    factKey: 'immunization_mr',
    documentationPhrase: 'MR/Measles vaccine given',
  },
  {
    id: 'imm_q_measles',
    text: 'Measles — 2nd dose received?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 10,
    factKey: 'immunization_measles_2',
    documentationPhrase: 'Measles 2nd dose given',
  },
  {
    id: 'imm_q_yellow_fever',
    text: 'Yellow Fever vaccine — if age-appropriate?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 10,
    factKey: 'immunization_yellow_fever',
    documentationPhrase: 'Yellow fever vaccine given',
  },
  {
    id: 'imm_q_covid',
    text: 'COVID-19 vaccine — received?',
    alternatives: [
      { condition: { ageMax: 12 }, text: '', type: 'boolean' },
    ],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 10,
    factKey: 'immunization_covid',
    documentationPhrase: 'COVID-19 vaccine given',
  },
  {
    id: 'imm_q_hpv',
    text: 'HPV vaccine — received (for girls 9-14 years)?',
    alternatives: [
      { condition: { sex: 'male' }, text: '', type: 'boolean' },
    ],
    type: 'boolean',
    required: false,
    importance: 1,
    reasoningWeight: 5,
    factKey: 'immunization_hpv',
    documentationPhrase: 'HPV vaccine given',
  },
  {
    id: 'imm_q_reactions',
    text: 'Has the child had any reaction to any vaccine?',
    alternatives: [],
    type: 'chips',
    chips: ['None', 'Fever', 'Rash', 'Swelling at injection site', 'Persistent crying', 'Seizure / convulsion', 'Severe allergic reaction'],
    required: false,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'immunization_reactions',
    documentationPhrase: 'Vaccine reactions: {value}',
  },
];

export const IMMUNIZATION_FACT_EXTRACTION: FactExtractionRule[] = [
  { questionId: 'imm_q_vaccinated', extract: (a) => [{ key: 'immunization_vaccinated', value: a ? true : false, type: 'reported', questionId: 'imm_q_vaccinated', documentationPhrase: a ? 'Immunizations up to date' : 'Immunizations not up to date' }] },
  { questionId: 'imm_q_missed_doses', extract: (a) => a ? [{ key: 'immunization_missed_doses', value: true, type: 'reported', questionId: 'imm_q_missed_doses', documentationPhrase: 'Missed vaccination doses' }] : [] },
  { questionId: 'imm_q_bcg', extract: (a) => a ? [{ key: 'immunization_bcg', value: true, type: 'reported', questionId: 'imm_q_bcg', documentationPhrase: 'BCG given' }] : [] },
  { questionId: 'imm_q_penta', extract: (a) => a ? [{ key: 'immunization_penta', value: true, type: 'reported', questionId: 'imm_q_penta', documentationPhrase: 'Pentavalent complete' }] : [] },
  { questionId: 'imm_q_mr', extract: (a) => a ? [{ key: 'immunization_mr', value: true, type: 'reported', questionId: 'imm_q_mr', documentationPhrase: 'Measles vaccine given' }] : [] },
  { questionId: 'imm_q_reactions', extract: (a) => a ? [{ key: 'immunization_reactions', value: String(a), type: 'reported', questionId: 'imm_q_reactions', documentationPhrase: 'Vaccine reaction: ' + String(a) }] : [] },
];
