import { PMH_OBJECTIVES, PMH_QUESTIONS, PMH_FACT_EXTRACTION } from './pmh';
import { DRUG_OBJECTIVES, DRUG_QUESTIONS, DRUG_FACT_EXTRACTION } from './drug';
import { ALLERGY_OBJECTIVES, ALLERGY_QUESTIONS, ALLERGY_FACT_EXTRACTION } from './allergy';
import { FAMILY_OBJECTIVES, FAMILY_QUESTIONS, FAMILY_FACT_EXTRACTION } from './family';
import { SOCIAL_OBJECTIVES, SOCIAL_QUESTIONS, SOCIAL_FACT_EXTRACTION } from './social';
import { OBGYN_OBJECTIVES, OBGYN_QUESTIONS, OBGYN_FACT_EXTRACTION } from './obgyn';
import { PERINATAL_OBJECTIVES, PERINATAL_QUESTIONS, PERINATAL_FACT_EXTRACTION } from './perinatal';
import { NUTRITION_OBJECTIVES, NUTRITION_QUESTIONS, NUTRITION_FACT_EXTRACTION } from './nutrition';
import { IMMUNIZATION_OBJECTIVES, IMMUNIZATION_QUESTIONS, IMMUNIZATION_FACT_EXTRACTION } from './immunization';
import { GROWTH_OBJECTIVES, GROWTH_QUESTIONS, GROWTH_FACT_EXTRACTION } from './growth';
import { ROS_OBJECTIVES, ROS_QUESTIONS, ROS_FACT_EXTRACTION } from './ros';

export {
  PMH_OBJECTIVES, PMH_QUESTIONS, PMH_FACT_EXTRACTION,
  DRUG_OBJECTIVES, DRUG_QUESTIONS, DRUG_FACT_EXTRACTION,
  ALLERGY_OBJECTIVES, ALLERGY_QUESTIONS, ALLERGY_FACT_EXTRACTION,
  FAMILY_OBJECTIVES, FAMILY_QUESTIONS, FAMILY_FACT_EXTRACTION,
  SOCIAL_OBJECTIVES, SOCIAL_QUESTIONS, SOCIAL_FACT_EXTRACTION,
  OBGYN_OBJECTIVES, OBGYN_QUESTIONS, OBGYN_FACT_EXTRACTION,
  PERINATAL_OBJECTIVES, PERINATAL_QUESTIONS, PERINATAL_FACT_EXTRACTION,
  NUTRITION_OBJECTIVES, NUTRITION_QUESTIONS, NUTRITION_FACT_EXTRACTION,
  IMMUNIZATION_OBJECTIVES, IMMUNIZATION_QUESTIONS, IMMUNIZATION_FACT_EXTRACTION,
  GROWTH_OBJECTIVES, GROWTH_QUESTIONS, GROWTH_FACT_EXTRACTION,
  ROS_OBJECTIVES, ROS_QUESTIONS, ROS_FACT_EXTRACTION,
};

export const ALL_HISTORY_LIBRARIES = {
  pmh: { objectives: PMH_OBJECTIVES, questions: PMH_QUESTIONS, factExtraction: PMH_FACT_EXTRACTION },
  drug: { objectives: DRUG_OBJECTIVES, questions: DRUG_QUESTIONS, factExtraction: DRUG_FACT_EXTRACTION },
  allergy: { objectives: ALLERGY_OBJECTIVES, questions: ALLERGY_QUESTIONS, factExtraction: ALLERGY_FACT_EXTRACTION },
  family: { objectives: FAMILY_OBJECTIVES, questions: FAMILY_QUESTIONS, factExtraction: FAMILY_FACT_EXTRACTION },
  social: { objectives: SOCIAL_OBJECTIVES, questions: SOCIAL_QUESTIONS, factExtraction: SOCIAL_FACT_EXTRACTION },
  obgyn: { objectives: OBGYN_OBJECTIVES, questions: OBGYN_QUESTIONS, factExtraction: OBGYN_FACT_EXTRACTION },
  perinatal: { objectives: PERINATAL_OBJECTIVES, questions: PERINATAL_QUESTIONS, factExtraction: PERINATAL_FACT_EXTRACTION },
  nutrition: { objectives: NUTRITION_OBJECTIVES, questions: NUTRITION_QUESTIONS, factExtraction: NUTRITION_FACT_EXTRACTION },
  immunization: { objectives: IMMUNIZATION_OBJECTIVES, questions: IMMUNIZATION_QUESTIONS, factExtraction: IMMUNIZATION_FACT_EXTRACTION },
  growth: { objectives: GROWTH_OBJECTIVES, questions: GROWTH_QUESTIONS, factExtraction: GROWTH_FACT_EXTRACTION },
  ros: { objectives: ROS_OBJECTIVES, questions: ROS_QUESTIONS, factExtraction: ROS_FACT_EXTRACTION },
} as const;
