import type { SymptomQuestion, ClinicalObjectiveGroup, FactExtractionRule } from '../symptom-types';

export const NUTRITION_OBJECTIVES: ClinicalObjectiveGroup[] = [
  { id: 'obj_nutrition_feeding', label: 'Feeding History', description: 'Assess feeding practices and dietary intake', order: 1, required: true, questionIds: ['nutrition_q_breastfeeding', 'nutrition_q_feeding_pattern', 'nutrition_q_complementary'] },
  { id: 'obj_nutrition_diet', label: 'Dietary Assessment', description: 'Diet quality, diversity, and restrictions', order: 2, required: true, questionIds: ['nutrition_q_diet_variety', 'nutrition_q_appetite', 'nutrition_q_restrictions'] },
  { id: 'obj_nutrition_anthropometry', label: 'Anthropometry', description: 'Growth measurements and nutritional status', order: 3, required: false, questionIds: ['nutrition_q_weight_trend', 'nutrition_q_muac'] },
];

export const NUTRITION_QUESTIONS: SymptomQuestion[] = [
  {
    id: 'nutrition_q_breastfeeding',
    text: 'Is the child currently breastfeeding?',
    alternatives: [
      { condition: { ageMax: 0.08 }, text: 'Is the baby breastfeeding? How often?' },
      { condition: { ageMin: 2 }, text: '', type: 'boolean' },
    ],
    type: 'chips',
    chips: ['Exclusive breastfeeding', 'Mixed feeding (breast + formula)', 'Formula only', 'Breastfeeding + complementary foods', 'Weaned / not breastfeeding', 'N/A'],
    required: true,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'nutrition_breastfeeding',
    documentationPhrase: 'Breastfeeding: {value}',
  },
  {
    id: 'nutrition_q_feeding_pattern',
    text: 'How often does the child feed? Is there any difficulty feeding?',
    alternatives: [],
    type: 'text',
    required: false,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'nutrition_feeding_pattern',
    documentationPhrase: 'Feeding pattern: {value}',
  },
  {
    id: 'nutrition_q_complementary',
    text: 'Has the child started complementary foods? What foods?',
    alternatives: [
      { condition: { ageMax: 0.5 }, text: '', type: 'boolean' },
    ],
    type: 'text',
    required: false,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'nutrition_complementary',
    documentationPhrase: 'Complementary feeding: {value}',
  },
  {
    id: 'nutrition_q_diet_variety',
    text: 'Describe a typical day\'s diet. (what foods, how many meals)',
    alternatives: [],
    type: 'text',
    required: true,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'nutrition_diet',
    documentationPhrase: 'Diet: {value}',
  },
  {
    id: 'nutrition_q_appetite',
    text: 'How is the appetite?',
    alternatives: [
      { condition: { ageMax: 5 }, text: 'How is the child\'s appetite?' },
    ],
    type: 'chips',
    chips: ['Good', 'Reduced', 'Poor / very little', 'Excessive', 'Selective / picky'],
    required: true,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'nutrition_appetite',
    documentationPhrase: 'Appetite: {value}',
  },
  {
    id: 'nutrition_q_restrictions',
    text: 'Are there any dietary restrictions? (medical, cultural, religious, allergy)',
    alternatives: [],
    type: 'text',
    required: false,
    importance: 1,
    reasoningWeight: 10,
    factKey: 'nutrition_restrictions',
    documentationPhrase: 'Dietary restrictions: {value}',
  },
  {
    id: 'nutrition_q_weight_trend',
    text: 'Is the child gaining weight appropriately? Any recent weight loss?',
    alternatives: [],
    type: 'chips',
    chips: ['Gaining well', 'Weight stable', 'Losing weight', 'Not gaining adequately', 'Unknown'],
    required: false,
    importance: 3,
    reasoningWeight: 25,
    factKey: 'nutrition_weight_trend',
    documentationPhrase: 'Weight trend: {value}',
  },
  {
    id: 'nutrition_q_muac',
    text: 'What is the MUAC?',
    alternatives: [],
    type: 'text',
    required: false,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'nutrition_muac',
    documentationPhrase: 'MUAC: {value} cm',
  },
];

export const NUTRITION_FACT_EXTRACTION: FactExtractionRule[] = [
  { questionId: 'nutrition_q_breastfeeding', extract: (a) => [{ key: 'nutrition_breastfeeding', value: String(a), type: 'reported', questionId: 'nutrition_q_breastfeeding', documentationPhrase: 'Feeding: ' + String(a) }] },
  { questionId: 'nutrition_q_diet', extract: (a) => [{ key: 'nutrition_diet', value: String(a), type: 'reported', questionId: 'nutrition_q_diet', documentationPhrase: 'Diet: ' + String(a) }] },
  { questionId: 'nutrition_q_appetite', extract: (a) => [{ key: 'nutrition_appetite', value: String(a), type: 'reported', questionId: 'nutrition_q_appetite', documentationPhrase: 'Appetite: ' + String(a) }] },
  { questionId: 'nutrition_q_weight_trend', extract: (a) => a ? [{ key: 'nutrition_weight_trend', value: String(a), type: 'reported', questionId: 'nutrition_q_weight_trend', documentationPhrase: 'Weight: ' + String(a) }] : [] },
  { questionId: 'nutrition_q_muac', extract: (a) => a ? [{ key: 'nutrition_muac', value: String(a), type: 'reported', questionId: 'nutrition_q_muac', documentationPhrase: 'MUAC: ' + String(a) }] : [] },
];
