import type { SymptomQuestion, ClinicalObjectiveGroup, FactExtractionRule } from '../symptom-types';

export const OBGYN_OBJECTIVES: ClinicalObjectiveGroup[] = [
  { id: 'obj_obgyn_menstrual', label: 'Menstrual History', description: 'Menarche, cycle, LMP, menopausal status', order: 1, required: true, questionIds: ['obgyn_q_menarche', 'obgyn_q_lmp', 'obgyn_q_cycle', 'obgyn_q_menopause'] },
  { id: 'obj_obgyn_obstetric', label: 'Obstetric History', description: 'Gravidity, parity, pregnancy outcomes', order: 2, required: true, questionIds: ['obgyn_q_gravidity', 'obgyn_q_parity', 'obgyn_q_complications'] },
  { id: 'obj_obgyn_contraception', label: 'Contraception', description: 'Current and past contraceptive use', order: 3, required: false, questionIds: ['obgyn_q_contraception'] },
  { id: 'obj_obgyn_gynecological', label: 'Gynecological History', description: 'Previous gynecological conditions and surgeries', order: 4, required: false, questionIds: ['obgyn_q_conditions', 'obgyn_q_cervical_smear'] },
];

export const OBGYN_QUESTIONS: SymptomQuestion[] = [
  {
    id: 'obgyn_q_menarche',
    text: 'At what age did you start menstruating?',
    alternatives: [{ condition: { ageMax: 10 }, text: '', type: 'text' }],
    type: 'text',
    required: true,
    importance: 2,
    reasoningWeight: 10,
    factKey: 'obgyn_menarche',
    documentationPhrase: 'Menarche at age {value}',
  },
  {
    id: 'obgyn_q_lmp',
    text: 'When was your last menstrual period (LMP)?',
    alternatives: [{ condition: { ageMax: 10 }, text: '', type: 'text' }],
    type: 'text',
    required: true,
    importance: 3,
    reasoningWeight: 30,
    factKey: 'obgyn_lmp',
    documentationPhrase: 'LMP: {value}',
  },
  {
    id: 'obgyn_q_cycle',
    text: 'What is your menstrual cycle like? (frequency, duration, regularity)',
    alternatives: [],
    type: 'chips',
    chips: ['Regular (21-35 day cycle)', 'Irregular', 'Prolonged bleeding >7 days', 'Heavy bleeding', 'Painful periods', 'Skipped periods'],
    required: false,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'obgyn_cycle',
    documentationPhrase: 'Menstrual cycle: {value}',
  },
  {
    id: 'obgyn_q_menopause',
    text: 'Have you reached menopause?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'obgyn_menopause',
    documentationPhrase: 'Menopausal',
  },
  {
    id: 'obgyn_q_gravidity',
    text: 'How many times have you been pregnant (gravidity)?',
    alternatives: [],
    type: 'text',
    required: true,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'obgyn_gravidity',
    documentationPhrase: 'Gravidity: {value}',
  },
  {
    id: 'obgyn_q_parity',
    text: 'How many children have you delivered (parity)?',
    alternatives: [],
    type: 'text',
    required: true,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'obgyn_parity',
    documentationPhrase: 'Parity: {value}',
  },
  {
    id: 'obgyn_q_complications',
    text: 'Did you have any complications in any pregnancy?',
    alternatives: [],
    type: 'multiple',
    chips: ['None', 'Miscarriage / abortion', 'Preterm delivery', 'Preeclampsia', 'Gestational diabetes', 'Post-partum hemorrhage', 'Caesarean section', 'Stillbirth', 'Ectopic pregnancy'],
    required: false,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'obgyn_complications',
    documentationPhrase: 'Obstetric complications: {value}',
  },
  {
    id: 'obgyn_q_contraception',
    text: 'Are you currently using any contraception?',
    alternatives: [],
    type: 'chips',
    chips: ['None', 'Oral contraceptive pill', 'Injectable (Depo-Provera)', 'Implant', 'IUD', 'Condoms', 'BTL / vasectomy', 'Lactational amenorrhea'],
    required: false,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'obgyn_contraception',
    documentationPhrase: 'Contraception: {value}',
  },
  {
    id: 'obgyn_q_conditions',
    text: 'Do you have any gynecological conditions? (fibroids, endometriosis, PCOS, infections)',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'obgyn_conditions',
    documentationPhrase: 'History of gynecological condition',
  },
  {
    id: 'obgyn_q_cervical_smear',
    text: 'When was your last cervical smear (Pap smear)?',
    alternatives: [],
    type: 'text',
    required: false,
    importance: 1,
    reasoningWeight: 5,
    factKey: 'obgyn_cervical_smear',
    documentationPhrase: 'Last cervical smear: {value}',
  },
];

export const OBGYN_FACT_EXTRACTION: FactExtractionRule[] = [
  { questionId: 'obgyn_q_lmp', extract: (a) => [{ key: 'obgyn_lmp', value: String(a), type: 'reported', questionId: 'obgyn_q_lmp', documentationPhrase: 'LMP: ' + String(a) }] },
  { questionId: 'obgyn_q_gravidity', extract: (a) => [{ key: 'obgyn_gravidity', value: String(a), type: 'reported', questionId: 'obgyn_q_gravidity', documentationPhrase: 'Gravida ' + String(a) }] },
  { questionId: 'obgyn_q_parity', extract: (a) => [{ key: 'obgyn_parity', value: String(a), type: 'reported', questionId: 'obgyn_q_parity', documentationPhrase: 'Para ' + String(a) }] },
  { questionId: 'obgyn_q_menarche', extract: (a) => a ? [{ key: 'obgyn_menarche', value: String(a), type: 'reported', questionId: 'obgyn_q_menarche', documentationPhrase: 'Menarche age ' + String(a) }] : [] },
  { questionId: 'obgyn_q_cycle', extract: (a) => a ? [{ key: 'obgyn_cycle', value: String(a), type: 'reported', questionId: 'obgyn_q_cycle', documentationPhrase: 'Cycle: ' + String(a) }] : [] },
  { questionId: 'obgyn_q_complications', extract: (a) => a ? [{ key: 'obgyn_complications', value: Array.isArray(a) ? a.join(', ') : String(a), type: 'reported', questionId: 'obgyn_q_complications', documentationPhrase: 'OB complications: ' + (Array.isArray(a) ? a.join(', ') : String(a)) }] : [] },
  { questionId: 'obgyn_q_contraception', extract: (a) => a ? [{ key: 'obgyn_contraception', value: String(a), type: 'reported', questionId: 'obgyn_q_contraception', documentationPhrase: 'Contraception: ' + String(a) }] : [] },
  { questionId: 'obgyn_q_conditions', extract: (a) => a ? [{ key: 'obgyn_conditions', value: true, type: 'reported', questionId: 'obgyn_q_conditions', documentationPhrase: 'History of gynecological condition' }] : [] },
];
