import type { SymptomQuestion, ClinicalObjectiveGroup, FactExtractionRule } from '../symptom-types';

export const PERINATAL_OBJECTIVES: ClinicalObjectiveGroup[] = [
  { id: 'obj_perinatal_antenatal', label: 'Antenatal History', description: 'Maternal health and pregnancy course', order: 1, required: true, questionIds: ['perinatal_q_antenatal_care', 'perinatal_q_maternal_illness', 'perinatal_q_medication_pregnancy', 'perinatal_q_ultrasound'] },
  { id: 'obj_perinatal_natal', label: 'Natal History', description: 'Labour, delivery, and condition at birth', order: 2, required: true, questionIds: ['perinatal_q_gestation', 'perinatal_q_labour', 'perinatal_q_delivery', 'perinatal_q_place_delivery', 'perinatal_q_condition_birth'] },
  { id: 'obj_perinatal_postnatal', label: 'Postnatal History', description: 'Neonatal adaptation and early course', order: 3, required: true, questionIds: ['perinatal_q_cried', 'perinatal_q_breathing', 'perinatal_q_feeding_neonatal', 'perinatal_q_jaundice', 'perinatal_q_vaccination_birth'] },
];

export const PERINATAL_QUESTIONS: SymptomQuestion[] = [
  {
    id: 'perinatal_q_antenatal_care',
    text: 'Did the mother attend antenatal care (ANC) during pregnancy?',
    alternatives: [],
    type: 'boolean',
    required: true,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'perinatal_anc',
    documentationPhrase: 'Mother attended antenatal care',
  },
  {
    id: 'perinatal_q_maternal_illness',
    text: 'Did the mother have any illness during pregnancy? (fever, hypertension, diabetes, infections)',
    alternatives: [],
    type: 'boolean',
    required: true,
    importance: 3,
    reasoningWeight: 25,
    factKey: 'perinatal_maternal_illness',
    documentationPhrase: 'Maternal illness during pregnancy',
  },
  {
    id: 'perinatal_q_medication_pregnancy',
    text: 'Did the mother take any medications during pregnancy?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'perinatal_medication_pregnancy',
    documentationPhrase: 'Maternal medication during pregnancy',
  },
  {
    id: 'perinatal_q_ultrasound',
    text: 'Did the mother have any ultrasound scans during pregnancy? Any abnormalities detected?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'perinatal_ultrasound',
    documentationPhrase: 'Ultrasound done during pregnancy',
  },
  {
    id: 'perinatal_q_gestation',
    text: 'What was the gestation at delivery? (weeks)',
    alternatives: [],
    type: 'chips',
    chips: ['Full term (37-42 weeks)', 'Late preterm (34-36 weeks)', 'Early preterm (<34 weeks)', 'Post-term (>42 weeks)', 'Unknown'],
    required: true,
    importance: 3,
    reasoningWeight: 25,
    factKey: 'perinatal_gestation',
    documentationPhrase: 'Delivered at {value}',
  },
  {
    id: 'perinatal_q_labour',
    text: 'How was the labour?',
    alternatives: [],
    type: 'chips',
    chips: ['Spontaneous onset, normal progress', 'Induced', 'Prolonged labour', 'Precipitous (very fast)', 'Obstructed labour', 'Unknown'],
    required: true,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'perinatal_labour',
    documentationPhrase: 'Labour: {value}',
  },
  {
    id: 'perinatal_q_delivery',
    text: 'How was the baby delivered?',
    alternatives: [],
    type: 'chips',
    chips: ['Spontaneous vaginal delivery (SVD)', 'Vacuum extraction', 'Forceps delivery', 'Caesarean section', 'Breech delivery'],
    required: true,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'perinatal_delivery',
    documentationPhrase: 'Delivery: {value}',
  },
  {
    id: 'perinatal_q_place_delivery',
    text: 'Where was the baby delivered?',
    alternatives: [],
    type: 'chips',
    chips: ['Hospital', 'Health centre', 'Home', 'On the way to facility', 'Traditional birth attendant'],
    required: true,
    importance: 1,
    reasoningWeight: 10,
    factKey: 'perinatal_place_delivery',
    documentationPhrase: 'Delivered at {value}',
  },
  {
    id: 'perinatal_q_condition_birth',
    text: 'What was the baby\'s condition at birth?',
    alternatives: [],
    type: 'chips',
    chips: ['Good — cried immediately', 'Required some stimulation', 'Required resuscitation', 'Not breathing at birth (APGAR low)', 'Unknown'],
    required: true,
    importance: 3,
    reasoningWeight: 30,
    factKey: 'perinatal_condition_birth',
    documentationPhrase: 'Condition at birth: {value}',
  },
  {
    id: 'perinatal_q_cried',
    text: 'Did the baby cry immediately after birth?',
    alternatives: [],
    type: 'boolean',
    required: true,
    importance: 3,
    reasoningWeight: 30,
    factKey: 'perinatal_cried',
    documentationPhrase: 'Cried immediately at birth',
  },
  {
    id: 'perinatal_q_breathing',
    text: 'Did the baby have any breathing difficulty after birth?',
    alternatives: [],
    type: 'boolean',
    required: true,
    importance: 3,
    reasoningWeight: 30,
    factKey: 'perinatal_breathing',
    documentationPhrase: 'Breathing difficulty at birth',
  },
  {
    id: 'perinatal_q_feeding_neonatal',
    text: 'How was the baby feeding in the first days of life?',
    alternatives: [],
    type: 'chips',
    chips: ['Breastfeeding well', 'Poor suck', 'Not able to breastfeed', 'Formula fed', 'NG tube feeding'],
    required: true,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'perinatal_early_feeding',
    documentationPhrase: 'Early feeding: {value}',
  },
  {
    id: 'perinatal_q_jaundice',
    text: 'Did the baby develop jaundice (yellowing of skin/eyes)?',
    alternatives: [],
    type: 'boolean',
    required: true,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'perinatal_jaundice',
    documentationPhrase: 'Neonatal jaundice',
  },
  {
    id: 'perinatal_q_vaccination_birth',
    text: 'Did the baby receive BCG and Polio (OPV0) at birth?',
    alternatives: [],
    type: 'boolean',
    required: true,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'perinatal_birth_vaccination',
    documentationPhrase: 'Received birth vaccinations',
  },
];

export const PERINATAL_FACT_EXTRACTION: FactExtractionRule[] = [
  { questionId: 'perinatal_q_gestation', extract: (a) => [{ key: 'perinatal_gestation', value: String(a), type: 'reported', questionId: 'perinatal_q_gestation', documentationPhrase: 'Gestation: ' + String(a) }] },
  { questionId: 'perinatal_q_condition_birth', extract: (a) => [{ key: 'perinatal_condition_birth', value: String(a), type: 'reported', questionId: 'perinatal_q_condition_birth', documentationPhrase: 'At birth: ' + String(a) }] },
  { questionId: 'perinatal_q_delivery', extract: (a) => [{ key: 'perinatal_delivery', value: String(a), type: 'reported', questionId: 'perinatal_q_delivery', documentationPhrase: 'Delivery: ' + String(a) }] },
  { questionId: 'perinatal_q_labour', extract: (a) => [{ key: 'perinatal_labour', value: String(a), type: 'reported', questionId: 'perinatal_q_labour', documentationPhrase: 'Labour: ' + String(a) }] },
  { questionId: 'perinatal_q_cried', extract: (a) => a ? [{ key: 'perinatal_cried', value: true, type: 'reported', questionId: 'perinatal_q_cried', documentationPhrase: 'Cried immediately at birth' }] : [] },
  { questionId: 'perinatal_q_breathing', extract: (a) => a ? [{ key: 'perinatal_breathing', value: true, type: 'reported', questionId: 'perinatal_q_breathing', documentationPhrase: 'Breathing difficulty at birth' }] : [] },
  { questionId: 'perinatal_q_jaundice', extract: (a) => a ? [{ key: 'perinatal_jaundice', value: true, type: 'reported', questionId: 'perinatal_q_jaundice', documentationPhrase: 'Neonatal jaundice' }] : [] },
  { questionId: 'perinatal_q_maternal_illness', extract: (a) => a ? [{ key: 'perinatal_maternal_illness', value: true, type: 'reported', questionId: 'perinatal_q_maternal_illness', documentationPhrase: 'Maternal illness in pregnancy' }] : [] },
  { questionId: 'perinatal_q_anc', extract: (a) => a ? [{ key: 'perinatal_anc', value: true, type: 'reported', questionId: 'perinatal_q_anc', documentationPhrase: 'ANC attendance' }] : [] },
  { questionId: 'perinatal_q_early_feeding', extract: (a) => [{ key: 'perinatal_early_feeding', value: String(a), type: 'reported', questionId: 'perinatal_q_early_feeding', documentationPhrase: 'Early feeding: ' + String(a) }] },
];
