import type { SymptomQuestion, ClinicalObjectiveGroup, FactExtractionRule } from '../symptom-types';

export const PMH_OBJECTIVES: ClinicalObjectiveGroup[] = [
  { id: 'obj_pmh_chronic', label: 'Chronic Diseases', description: 'Document all chronic medical conditions', order: 1, required: true, questionIds: ['pmh_q_conditions', 'pmh_q_hypertension', 'pmh_q_diabetes', 'pmh_q_asthma', 'pmh_q_tb', 'pmh_q_hiv', 'pmh_q_sickle_cell', 'pmh_q_heart_disease', 'pmh_q_stroke', 'pmh_q_mental_health'] },
  { id: 'obj_pmh_surgical', label: 'Surgical History', description: 'Previous surgeries and procedures', order: 2, required: false, questionIds: ['pmh_q_prior_surgeries', 'pmh_q_surgery_details'] },
  { id: 'obj_pmh_admissions', label: 'Admission History', description: 'Previous hospital admissions', order: 3, required: false, questionIds: ['pmh_q_prior_admissions', 'pmh_q_admission_details'] },
  { id: 'obj_pmh_transfusion', label: 'Transfusion History', description: 'Blood transfusion history', order: 4, required: false, questionIds: ['pmh_q_transfusion', 'pmh_q_transfusion_details'] },
  { id: 'obj_pmh_trauma', label: 'Trauma History', description: 'Significant past injuries', order: 5, required: false, questionIds: ['pmh_q_trauma'] },
];

export const PMH_QUESTIONS: SymptomQuestion[] = [
  {
    id: 'pmh_q_conditions',
    text: 'Do you have any chronic medical conditions?',
    alternatives: [
      { condition: { ageMax: 5 }, text: 'Does the child have any chronic medical conditions?' },
      { condition: { ageMax: 1 }, text: 'Does the baby have any medical problems diagnosed?' },
    ],
    type: 'multiple',
    chips: ['None', 'Hypertension', 'Diabetes', 'Asthma', 'TB', 'HIV', 'Sickle cell disease', 'Heart disease', 'Stroke', 'Epilepsy', 'Mental health condition', 'Thyroid disease', 'Cancer', 'Arthritis', 'Kidney disease', 'Liver disease', 'Other'],
    required: true,
    importance: 3,
    reasoningWeight: 30,
    factKey: 'pmh_conditions',
    documentationPhrase: 'Past medical history includes {value}',
  },
  {
    id: 'pmh_q_hypertension',
    text: 'Do you have high blood pressure?',
    alternatives: [{ condition: { ageMax: 13 }, text: '', type: 'boolean' }],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'pmh_hypertension',
    documentationPhrase: 'History of hypertension',
    dependencies: ['pmh_q_conditions'],
  },
  {
    id: 'pmh_q_diabetes',
    text: 'Do you have diabetes?',
    alternatives: [{ condition: { ageMax: 13 }, text: '', type: 'boolean' }],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 25,
    factKey: 'pmh_diabetes',
    documentationPhrase: 'History of diabetes mellitus',
    dependencies: ['pmh_q_conditions'],
  },
  {
    id: 'pmh_q_asthma',
    text: 'Do you have asthma or recurrent wheezing?',
    alternatives: [
      { condition: { ageMax: 5 }, text: 'Does the child have asthma?' },
      { condition: { ageMax: 1 }, text: 'Does the baby have wheezing episodes?' },
    ],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'pmh_asthma',
    documentationPhrase: 'History of asthma',
    dependencies: ['pmh_q_conditions'],
  },
  {
    id: 'pmh_q_tb',
    text: 'Have you ever been treated for TB?',
    alternatives: [
      { condition: { ageMax: 5 }, text: 'Has the child ever been treated for TB?' },
    ],
    type: 'boolean',
    required: false,
    importance: 3,
    reasoningWeight: 30,
    factKey: 'pmh_tb',
    documentationPhrase: 'Past history of tuberculosis',
    dependencies: ['pmh_q_conditions'],
  },
  {
    id: 'pmh_q_hiv',
    text: 'Do you know your HIV status?',
    alternatives: [
      { condition: { ageMax: 13 }, text: 'Was the child tested for HIV? (PMTCT/HEI)' },
    ],
    type: 'chips',
    chips: ['Negative', 'Positive — on treatment', 'Positive — not on treatment', 'Unknown / never tested'],
    required: false,
    importance: 3,
    reasoningWeight: 35,
    factKey: 'pmh_hiv_status',
    documentationPhrase: 'HIV status: {value}',
    dependencies: ['pmh_q_conditions'],
  },
  {
    id: 'pmh_q_sickle_cell',
    text: 'Do you have sickle cell disease or trait?',
    alternatives: [
      { condition: { ageMax: 5 }, text: 'Does the child have sickle cell disease?' },
    ],
    type: 'chips',
    chips: ['No', 'Sickle cell disease (SS)', 'Sickle cell trait (AS)', 'Unknown'],
    required: false,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'pmh_sickle_cell',
    documentationPhrase: 'Sickle cell status: {value}',
  },
  {
    id: 'pmh_q_heart_disease',
    text: 'Do you have any heart condition? (rheumatic, congenital, ischemic)',
    alternatives: [{ condition: { ageMax: 5 }, text: 'Does the child have a heart condition?' }],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 25,
    factKey: 'pmh_heart_disease',
    documentationPhrase: 'History of heart disease',
  },
  {
    id: 'pmh_q_stroke',
    text: 'Have you ever had a stroke or mini-stroke (TIA)?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 25,
    factKey: 'pmh_stroke',
    documentationPhrase: 'History of stroke/TIA',
  },
  {
    id: 'pmh_q_mental_health',
    text: 'Do you have any mental health condition? (depression, anxiety, bipolar, schizophrenia)',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'pmh_mental_health',
    documentationPhrase: 'History of mental health condition',
  },
  {
    id: 'pmh_q_prior_surgeries',
    text: 'Have you ever had surgery?',
    alternatives: [
      { condition: { ageMax: 5 }, text: 'Has the child ever had surgery?' },
    ],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'pmh_prior_surgeries',
    documentationPhrase: 'Previous surgery',
  },
  {
    id: 'pmh_q_surgery_details',
    text: 'What surgery(s) and when?',
    alternatives: [],
    type: 'text',
    required: false,
    importance: 1,
    reasoningWeight: 5,
    factKey: 'pmh_surgery_details',
    documentationPhrase: 'Previous surgeries: {value}',
    dependencies: ['pmh_q_prior_surgeries'],
  },
  {
    id: 'pmh_q_prior_admissions',
    text: 'Have you ever been admitted to hospital before?',
    alternatives: [
      { condition: { ageMax: 5 }, text: 'Has the child been admitted before?' },
    ],
    type: 'boolean',
    required: false,
    importance: 1,
    reasoningWeight: 10,
    factKey: 'pmh_prior_admissions',
    documentationPhrase: 'Prior hospital admissions',
  },
  {
    id: 'pmh_q_admission_details',
    text: 'Why were you admitted and when?',
    alternatives: [],
    type: 'text',
    required: false,
    importance: 1,
    reasoningWeight: 5,
    factKey: 'pmh_admission_details',
    documentationPhrase: 'Prior admissions: {value}',
    dependencies: ['pmh_q_prior_admissions'],
  },
  {
    id: 'pmh_q_transfusion',
    text: 'Have you ever received a blood transfusion?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'pmh_transfusion',
    documentationPhrase: 'History of blood transfusion',
  },
  {
    id: 'pmh_q_transfusion_details',
    text: 'When and why did you receive a transfusion?',
    alternatives: [],
    type: 'text',
    required: false,
    importance: 1,
    reasoningWeight: 5,
    factKey: 'pmh_transfusion_details',
    documentationPhrase: 'Transfusion: {value}',
    dependencies: ['pmh_q_transfusion'],
  },
  {
    id: 'pmh_q_trauma',
    text: 'Have you had any significant injuries or accidents?',
    alternatives: [],
    type: 'text',
    required: false,
    importance: 1,
    reasoningWeight: 5,
    factKey: 'pmh_trauma',
    documentationPhrase: 'Significant past trauma: {value}',
  },
];

export const PMH_FACT_EXTRACTION: FactExtractionRule[] = [
  { questionId: 'pmh_q_conditions', extract: (a) => [{ key: 'pmh_conditions', value: Array.isArray(a) ? a.join(', ') : String(a), type: 'reported', questionId: 'pmh_q_conditions', documentationPhrase: 'Past medical history: ' + (Array.isArray(a) ? a.join(', ') : String(a)) }] },
  { questionId: 'pmh_q_hypertension', extract: (a) => a ? [{ key: 'pmh_hypertension', value: true, type: 'reported', questionId: 'pmh_q_hypertension', documentationPhrase: 'History of hypertension' }] : [] },
  { questionId: 'pmh_q_diabetes', extract: (a) => a ? [{ key: 'pmh_diabetes', value: true, type: 'reported', questionId: 'pmh_q_diabetes', documentationPhrase: 'History of diabetes mellitus' }] : [] },
  { questionId: 'pmh_q_asthma', extract: (a) => a ? [{ key: 'pmh_asthma', value: true, type: 'reported', questionId: 'pmh_q_asthma', documentationPhrase: 'History of asthma' }] : [] },
  { questionId: 'pmh_q_tb', extract: (a) => a ? [{ key: 'pmh_tb', value: true, type: 'reported', questionId: 'pmh_q_tb', documentationPhrase: 'Past history of tuberculosis' }] : [] },
  { questionId: 'pmh_q_hiv_status', extract: (a) => [{ key: 'pmh_hiv_status', value: String(a), type: 'reported', questionId: 'pmh_q_hiv_status', documentationPhrase: 'HIV status: ' + String(a) }] },
  { questionId: 'pmh_q_sickle_cell', extract: (a) => [{ key: 'pmh_sickle_cell', value: String(a), type: 'reported', questionId: 'pmh_q_sickle_cell', documentationPhrase: 'Sickle cell: ' + String(a) }] },
  { questionId: 'pmh_q_heart_disease', extract: (a) => a ? [{ key: 'pmh_heart_disease', value: true, type: 'reported', questionId: 'pmh_q_heart_disease', documentationPhrase: 'History of heart disease' }] : [] },
  { questionId: 'pmh_q_stroke', extract: (a) => a ? [{ key: 'pmh_stroke', value: true, type: 'reported', questionId: 'pmh_q_stroke', documentationPhrase: 'History of stroke' }] : [] },
  { questionId: 'pmh_q_mental_health', extract: (a) => a ? [{ key: 'pmh_mental_health', value: true, type: 'reported', questionId: 'pmh_q_mental_health', documentationPhrase: 'History of mental health condition' }] : [] },
  { questionId: 'pmh_q_prior_surgeries', extract: (a) => a ? [{ key: 'pmh_prior_surgeries', value: true, type: 'reported', questionId: 'pmh_q_prior_surgeries', documentationPhrase: 'Previous surgery' }] : [] },
  { questionId: 'pmh_q_surgery_details', extract: (a) => [{ key: 'pmh_surgery_details', value: String(a), type: 'reported', questionId: 'pmh_q_surgery_details', documentationPhrase: 'Surgeries: ' + String(a) }] },
  { questionId: 'pmh_q_prior_admissions', extract: (a) => a ? [{ key: 'pmh_prior_admissions', value: true, type: 'reported', questionId: 'pmh_q_prior_admissions', documentationPhrase: 'Prior admissions' }] : [] },
  { questionId: 'pmh_q_transfusion', extract: (a) => a ? [{ key: 'pmh_transfusion', value: true, type: 'reported', questionId: 'pmh_q_transfusion', documentationPhrase: 'History of transfusion' }] : [] },
  { questionId: 'pmh_q_trauma', extract: (a) => [{ key: 'pmh_trauma', value: String(a), type: 'reported', questionId: 'pmh_q_trauma', documentationPhrase: 'Trauma: ' + String(a) }] },
];
