import type { SymptomQuestion, ClinicalObjectiveGroup, FactExtractionRule } from '../symptom-types';

export const ROS_OBJECTIVES: ClinicalObjectiveGroup[] = [
  { id: 'obj_ros_general', label: 'General / Constitutional', description: 'Weight, appetite, fatigue, fever', order: 1, required: true, questionIds: ['ros_q_general'] },
  { id: 'obj_ros_heent', label: 'HEENT', description: 'Head, eyes, ears, nose, throat symptoms', order: 2, required: false, questionIds: ['ros_q_heent'] },
  { id: 'obj_ros_respiratory', label: 'Respiratory', description: 'Cough, sputum, dyspnea, wheeze', order: 3, required: false, questionIds: ['ros_q_respiratory'] },
  { id: 'obj_ros_cardiovascular', label: 'Cardiovascular', description: 'Chest pain, palpitations, edema, syncope', order: 4, required: false, questionIds: ['ros_q_cardiovascular'] },
  { id: 'obj_ros_gastrointestinal', label: 'Gastrointestinal', description: 'Nausea, vomiting, diarrhea, abdominal pain', order: 5, required: false, questionIds: ['ros_q_gastrointestinal'] },
  { id: 'obj_ros_genitourinary', label: 'Genitourinary', description: 'Dysuria, frequency, discharge, menstrual', order: 6, required: false, questionIds: ['ros_q_genitourinary'] },
  { id: 'obj_ros_musculoskeletal', label: 'Musculoskeletal', description: 'Joint pain, swelling, back pain, muscle weakness', order: 7, required: false, questionIds: ['ros_q_musculoskeletal'] },
  { id: 'obj_ros_neurological', label: 'Neurological', description: 'Headache, dizziness, seizures, sensory/motor deficits', order: 8, required: false, questionIds: ['ros_q_neurological'] },
  { id: 'obj_ros_dermatological', label: 'Dermatological', description: 'Rash, itching, change in moles, skin lesions', order: 9, required: false, questionIds: ['ros_q_dermatological'] },
  { id: 'obj_ros_psychiatric', label: 'Psychiatric', description: 'Anxiety, depression, sleep, suicidal thoughts', order: 10, required: false, questionIds: ['ros_q_psychiatric'] },
  { id: 'obj_ros_endocrine', label: 'Endocrine', description: 'Thyroid, temperature tolerance, thirst, pigmentation', order: 11, required: false, questionIds: ['ros_q_endocrine'] },
  { id: 'obj_ros_hematological', label: 'Hematological / Lymphatic', description: 'Bleeding, bruising, lymphadenopathy', order: 12, required: false, questionIds: ['ros_q_hematological'] },
];

export const ROS_QUESTIONS: SymptomQuestion[] = [
  {
    id: 'ros_q_general',
    text: 'Any general symptoms? (weight change, appetite, fatigue, fevers, night sweats)',
    alternatives: [
      { condition: { ageMax: 5 }, text: 'Any general symptoms? (fever, tiredness, weight change)' },
    ],
    type: 'multiple',
    chips: ['None', 'Weight loss', 'Weight gain', 'Reduced appetite', 'Fatigue / malaise', 'Fever / chills', 'Night sweats', 'Weakness'],
    required: true,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'ros_general',
    documentationPhrase: 'General ROS: {value}',
  },
  {
    id: 'ros_q_heent',
    text: 'Any head, eye, ear, nose, or throat symptoms?',
    alternatives: [
      { condition: { ageMax: 5 }, text: 'Any symptoms affecting head, eyes, ears, nose, or throat?' },
    ],
    type: 'multiple',
    chips: ['None', 'Headache', 'Visual changes', 'Ear pain / discharge', 'Hearing loss', 'Ringing in ears', 'Nosebleeds', 'Nasal congestion', 'Sore throat', 'Dental pain', 'Mouth ulcers'],
    required: false,
    importance: 1,
    reasoningWeight: 10,
    factKey: 'ros_heent',
    documentationPhrase: 'HEENT ROS: {value}',
  },
  {
    id: 'ros_q_respiratory',
    text: 'Any respiratory symptoms?',
    alternatives: [
      { condition: { ageMax: 5 }, text: 'Any breathing or chest symptoms?' },
    ],
    type: 'multiple',
    chips: ['None', 'Cough', 'Sputum / phlegm', 'Hemoptysis (coughing blood)', 'Shortness of breath', 'Wheezing', 'Chest pain', 'Snoring / sleep apnea'],
    required: false,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'ros_respiratory',
    documentationPhrase: 'Respiratory ROS: {value}',
  },
  {
    id: 'ros_q_cardiovascular',
    text: 'Any cardiovascular symptoms?',
    alternatives: [
      { condition: { ageMax: 5 }, text: 'Any heart or circulation symptoms?' },
    ],
    type: 'multiple',
    chips: ['None', 'Chest pain / tightness', 'Palpitations', 'Shortness of breath on exertion', 'Leg swelling', 'Syncope (fainting)', 'High blood pressure'],
    required: false,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'ros_cardiovascular',
    documentationPhrase: 'Cardiovascular ROS: {value}',
  },
  {
    id: 'ros_q_gastrointestinal',
    text: 'Any gastrointestinal symptoms?',
    alternatives: [
      { condition: { ageMax: 5 }, text: 'Any tummy symptoms?' },
    ],
    type: 'multiple',
    chips: ['None', 'Nausea', 'Vomiting', 'Diarrhea', 'Constipation', 'Abdominal pain', 'Bloating', 'Blood in stool', 'Difficulty swallowing', 'Heartburn', 'Jaundice'],
    required: false,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'ros_gastrointestinal',
    documentationPhrase: 'GI ROS: {value}',
  },
  {
    id: 'ros_q_genitourinary',
    text: 'Any genitourinary symptoms?',
    alternatives: [
      { condition: { ageMax: 5 }, text: 'Any urinary symptoms?' },
      { condition: { ageMax: 13 }, text: 'Any genitourinary symptoms?', type: 'boolean' },
    ],
    type: 'multiple',
    chips: ['None', 'Painful urination', 'Frequent urination', 'Urgency', 'Blood in urine', 'Incontinence', 'Vaginal discharge', 'Genital sores', 'Testicular pain', 'Groin mass'],
    required: false,
    importance: 1,
    reasoningWeight: 15,
    factKey: 'ros_genitourinary',
    documentationPhrase: 'GU ROS: {value}',
  },
  {
    id: 'ros_q_musculoskeletal',
    text: 'Any musculoskeletal symptoms?',
    alternatives: [
      { condition: { ageMax: 5 }, text: 'Any joint or muscle symptoms?' },
    ],
    type: 'multiple',
    chips: ['None', 'Joint pain / swelling', 'Back pain', 'Muscle weakness', 'Muscle pain', 'Neck pain', 'Difficulty walking'],
    required: false,
    importance: 1,
    reasoningWeight: 15,
    factKey: 'ros_musculoskeletal',
    documentationPhrase: 'MSK ROS: {value}',
  },
  {
    id: 'ros_q_neurological',
    text: 'Any neurological symptoms?',
    alternatives: [
      { condition: { ageMax: 5 }, text: 'Any brain or nerve symptoms?' },
    ],
    type: 'multiple',
    chips: ['None', 'Headache', 'Dizziness', 'Seizures / fits', 'Numbness / tingling', 'Weakness', 'Tremor', 'Balance problems', 'Slurred speech', 'Memory loss', 'Loss of consciousness'],
    required: false,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'ros_neurological',
    documentationPhrase: 'Neuro ROS: {value}',
  },
  {
    id: 'ros_q_dermatological',
    text: 'Any skin symptoms?',
    alternatives: [
      { condition: { ageMax: 5 }, text: 'Any skin problems?' },
    ],
    type: 'multiple',
    chips: ['None', 'Rash', 'Itching (pruritus)', 'Change in mole', 'Skin sores / ulcers', 'Dry skin', 'Hair loss', 'Nail changes'],
    required: false,
    importance: 1,
    reasoningWeight: 10,
    factKey: 'ros_dermatological',
    documentationPhrase: 'Dermatological ROS: {value}',
  },
  {
    id: 'ros_q_psychiatric',
    text: 'Any mental health symptoms?',
    alternatives: [
      { condition: { ageMax: 12 }, text: 'Any behavioral or mood symptoms?' },
    ],
    type: 'multiple',
    chips: ['None', 'Anxiety / worry', 'Depression / low mood', 'Sleep problems', 'Hallucinations', 'Suicidal thoughts', 'Memory problems', 'Concentration difficulty'],
    required: false,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'ros_psychiatric',
    documentationPhrase: 'Psychiatric ROS: {value}',
  },
  {
    id: 'ros_q_endocrine',
    text: 'Any endocrine symptoms? (thyroid, temperature tolerance, thirst, skin changes)',
    alternatives: [
      { condition: { ageMax: 13 }, text: '', type: 'boolean' },
    ],
    type: 'multiple',
    chips: ['None', 'Heat / cold intolerance', 'Excessive thirst', 'Frequent urination', 'Swelling in neck', 'Change in skin color', 'Excessive sweating', 'Hair changes'],
    required: false,
    importance: 1,
    reasoningWeight: 10,
    factKey: 'ros_endocrine',
    documentationPhrase: 'Endocrine ROS: {value}',
  },
  {
    id: 'ros_q_hematological',
    text: 'Any blood / lymphatic symptoms? (bleeding, bruising, swollen nodes)',
    alternatives: [],
    type: 'multiple',
    chips: ['None', 'Easy bruising', 'Prolonged bleeding', 'Swollen lymph nodes', 'Pallor / looking pale', 'Frequent infections'],
    required: false,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'ros_hematological',
    documentationPhrase: 'Hematological ROS: {value}',
  },
];

export const ROS_FACT_EXTRACTION: FactExtractionRule[] = [
  { questionId: 'ros_q_general', extract: (a) => [{ key: 'ros_general', value: Array.isArray(a) ? a.join(', ') : String(a), type: 'reported', questionId: 'ros_q_general', documentationPhrase: 'General: ' + (Array.isArray(a) ? a.join(', ') : String(a)) }] },
  { questionId: 'ros_q_heent', extract: (a) => a && (!Array.isArray(a) || !a.includes('None')) ? [{ key: 'ros_heent', value: Array.isArray(a) ? a.join(', ') : String(a), type: 'reported', questionId: 'ros_q_heent', documentationPhrase: 'HEENT: ' + (Array.isArray(a) ? a.join(', ') : String(a)) }] : [] },
  { questionId: 'ros_q_respiratory', extract: (a) => a && (!Array.isArray(a) || !a.includes('None')) ? [{ key: 'ros_respiratory', value: Array.isArray(a) ? a.join(', ') : String(a), type: 'reported', questionId: 'ros_q_respiratory', documentationPhrase: 'Respiratory: ' + (Array.isArray(a) ? a.join(', ') : String(a)) }] : [] },
  { questionId: 'ros_q_cardiovascular', extract: (a) => a && (!Array.isArray(a) || !a.includes('None')) ? [{ key: 'ros_cardiovascular', value: Array.isArray(a) ? a.join(', ') : String(a), type: 'reported', questionId: 'ros_q_cardiovascular', documentationPhrase: 'CVS: ' + (Array.isArray(a) ? a.join(', ') : String(a)) }] : [] },
  { questionId: 'ros_q_gastrointestinal', extract: (a) => a && (!Array.isArray(a) || !a.includes('None')) ? [{ key: 'ros_gastrointestinal', value: Array.isArray(a) ? a.join(', ') : String(a), type: 'reported', questionId: 'ros_q_gastrointestinal', documentationPhrase: 'GI: ' + (Array.isArray(a) ? a.join(', ') : String(a)) }] : [] },
  { questionId: 'ros_q_genitourinary', extract: (a) => a && (!Array.isArray(a) || !a.includes('None')) ? [{ key: 'ros_genitourinary', value: Array.isArray(a) ? a.join(', ') : String(a), type: 'reported', questionId: 'ros_q_genitourinary', documentationPhrase: 'GU: ' + (Array.isArray(a) ? a.join(', ') : String(a)) }] : [] },
  { questionId: 'ros_q_musculoskeletal', extract: (a) => a && (!Array.isArray(a) || !a.includes('None')) ? [{ key: 'ros_musculoskeletal', value: Array.isArray(a) ? a.join(', ') : String(a), type: 'reported', questionId: 'ros_q_musculoskeletal', documentationPhrase: 'MSK: ' + (Array.isArray(a) ? a.join(', ') : String(a)) }] : [] },
  { questionId: 'ros_q_neurological', extract: (a) => a && (!Array.isArray(a) || !a.includes('None')) ? [{ key: 'ros_neurological', value: Array.isArray(a) ? a.join(', ') : String(a), type: 'reported', questionId: 'ros_q_neurological', documentationPhrase: 'Neuro: ' + (Array.isArray(a) ? a.join(', ') : String(a)) }] : [] },
  { questionId: 'ros_q_dermatological', extract: (a) => a && (!Array.isArray(a) || !a.includes('None')) ? [{ key: 'ros_dermatological', value: Array.isArray(a) ? a.join(', ') : String(a), type: 'reported', questionId: 'ros_q_dermatological', documentationPhrase: 'Derm: ' + (Array.isArray(a) ? a.join(', ') : String(a)) }] : [] },
  { questionId: 'ros_q_psychiatric', extract: (a) => a && (!Array.isArray(a) || !a.includes('None')) ? [{ key: 'ros_psychiatric', value: Array.isArray(a) ? a.join(', ') : String(a), type: 'reported', questionId: 'ros_q_psychiatric', documentationPhrase: 'Psych: ' + (Array.isArray(a) ? a.join(', ') : String(a)) }] : [] },
  { questionId: 'ros_q_endocrine', extract: (a) => a && (!Array.isArray(a) || !a.includes('None')) ? [{ key: 'ros_endocrine', value: Array.isArray(a) ? a.join(', ') : String(a), type: 'reported', questionId: 'ros_q_endocrine', documentationPhrase: 'Endocrine: ' + (Array.isArray(a) ? a.join(', ') : String(a)) }] : [] },
  { questionId: 'ros_q_hematological', extract: (a) => a && (!Array.isArray(a) || !a.includes('None')) ? [{ key: 'ros_hematological', value: Array.isArray(a) ? a.join(', ') : String(a), type: 'reported', questionId: 'ros_q_hematological', documentationPhrase: 'Heme: ' + (Array.isArray(a) ? a.join(', ') : String(a)) }] : [] },
];
