import type { SymptomQuestion, ClinicalObjectiveGroup, FactExtractionRule } from '../symptom-types';

export const SOCIAL_OBJECTIVES: ClinicalObjectiveGroup[] = [
  { id: 'obj_social_occupation', label: 'Occupation / School', description: 'Document occupational/school history', order: 1, required: true, questionIds: ['social_q_occupation', 'social_q_work_hazards'] },
  { id: 'obj_social_lifestyle', label: 'Lifestyle', description: 'Smoking, alcohol, substance use', order: 2, required: true, questionIds: ['social_q_smoking', 'social_q_alcohol', 'social_q_substance'] },
  { id: 'obj_social_living', label: 'Living Situation', description: 'Housing, support, environment', order: 3, required: false, questionIds: ['social_q_living', 'social_q_water', 'social_q_pets'] },
  { id: 'obj_social_economic', label: 'Socioeconomic', description: 'Economic and social support', order: 4, required: false, questionIds: ['social_q_support'] },
];

export const SOCIAL_QUESTIONS: SymptomQuestion[] = [
  {
    id: 'social_q_occupation',
    text: 'What is your occupation?',
    alternatives: [
      { condition: { ageMax: 5 }, text: 'What class is the child in at school?' },
      { condition: { ageMax: 18, ageMin: 6 }, text: 'Are you in school? What grade?' },
    ],
    type: 'text',
    required: true,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'social_occupation',
    documentationPhrase: 'Occupation: {value}',
  },
  {
    id: 'social_q_work_hazards',
    text: 'Are you exposed to any hazards at work? (dust, chemicals, fumes, heavy lifting)',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 2,
    reasoningWeight: 15,
    factKey: 'social_work_hazards',
    documentationPhrase: 'Occupational hazards present',
  },
  {
    id: 'social_q_smoking',
    text: 'Do you smoke tobacco?',
    alternatives: [
      { condition: { ageMax: 13 }, text: '', type: 'boolean' },
    ],
    type: 'chips',
    chips: ['Never smoked', 'Current smoker', 'Ex-smoker', 'Passive smoker (household)'],
    required: true,
    importance: 3,
    reasoningWeight: 25,
    factKey: 'social_smoking',
    documentationPhrase: 'Smoking status: {value}',
  },
  {
    id: 'social_q_alcohol',
    text: 'Do you drink alcohol?',
    alternatives: [
      { condition: { ageMax: 18 }, text: '', type: 'boolean' },
    ],
    type: 'chips',
    chips: ['Never', 'Social / occasional', 'Regular (daily or weekly)', 'Heavy / binge drinking', 'Ex-drinker'],
    required: true,
    importance: 2,
    reasoningWeight: 20,
    factKey: 'social_alcohol',
    documentationPhrase: 'Alcohol use: {value}',
  },
  {
    id: 'social_q_substance',
    text: 'Do you use any recreational drugs?',
    alternatives: [
      { condition: { ageMax: 18 }, text: '', type: 'boolean' },
    ],
    type: 'boolean',
    required: false,
    importance: 3,
    reasoningWeight: 25,
    factKey: 'social_substance_use',
    documentationPhrase: 'Recreational drug use',
  },
  {
    id: 'social_q_living',
    text: 'Where do you live? (housing type, number of rooms, occupants)',
    alternatives: [],
    type: 'text',
    required: false,
    importance: 1,
    reasoningWeight: 10,
    factKey: 'social_living',
    documentationPhrase: 'Housing: {value}',
  },
  {
    id: 'social_q_water',
    text: 'What is your source of drinking water?',
    alternatives: [],
    type: 'chips',
    chips: ['Piped / tap water', 'Borehole / well', 'River / stream', 'Bottled', 'Rainwater harvesting'],
    required: false,
    importance: 1,
    reasoningWeight: 10,
    factKey: 'social_water_source',
    documentationPhrase: 'Water source: {value}',
  },
  {
    id: 'social_q_pets',
    text: 'Do you have any pets or livestock at home?',
    alternatives: [],
    type: 'boolean',
    required: false,
    importance: 1,
    reasoningWeight: 10,
    factKey: 'social_pets',
    documentationPhrase: 'Has pets or livestock',
  },
  {
    id: 'social_q_support',
    text: 'Do you have adequate social and financial support?',
    alternatives: [],
    type: 'chips',
    chips: ['Good support', 'Partial support', 'No support / struggling'],
    required: false,
    importance: 1,
    reasoningWeight: 10,
    factKey: 'social_support',
    documentationPhrase: 'Social support: {value}',
  },
];

export const SOCIAL_FACT_EXTRACTION: FactExtractionRule[] = [
  { questionId: 'social_q_occupation', extract: (a) => [{ key: 'social_occupation', value: String(a), type: 'reported', questionId: 'social_q_occupation', documentationPhrase: 'Occupation: ' + String(a) }] },
  { questionId: 'social_q_work_hazards', extract: (a) => a ? [{ key: 'social_work_hazards', value: true, type: 'reported', questionId: 'social_q_work_hazards', documentationPhrase: 'Occupational hazards' }] : [] },
  { questionId: 'social_q_smoking', extract: (a) => [{ key: 'social_smoking', value: String(a), type: 'reported', questionId: 'social_q_smoking', documentationPhrase: 'Smoking: ' + String(a) }] },
  { questionId: 'social_q_alcohol', extract: (a) => [{ key: 'social_alcohol', value: String(a), type: 'reported', questionId: 'social_q_alcohol', documentationPhrase: 'Alcohol: ' + String(a) }] },
  { questionId: 'social_q_substance', extract: (a) => a ? [{ key: 'social_substance_use', value: true, type: 'reported', questionId: 'social_q_substance', documentationPhrase: 'Recreational drug use' }] : [] },
  { questionId: 'social_q_living', extract: (a) => a ? [{ key: 'social_living', value: String(a), type: 'reported', questionId: 'social_q_living', documentationPhrase: 'Housing: ' + String(a) }] : [] },
  { questionId: 'social_q_water', extract: (a) => a ? [{ key: 'social_water_source', value: String(a), type: 'reported', questionId: 'social_q_water', documentationPhrase: 'Water: ' + String(a) }] : [] },
  { questionId: 'social_q_pets', extract: (a) => a ? [{ key: 'social_pets', value: true, type: 'reported', questionId: 'social_q_pets', documentationPhrase: 'Has pets/livestock' }] : [] },
  { questionId: 'social_q_support', extract: (a) => a ? [{ key: 'social_support', value: String(a), type: 'reported', questionId: 'social_q_support', documentationPhrase: 'Support: ' + String(a) }] : [] },
];
