// ═══════════════════════════════════════════════════════════════════════════════
// AMEXAN PRESENTATION CONSTITUTION (BOOK VIII · Volume VIII-A)
//
// The 18 master dashboard families. Every actor in the system resolves into one
// of these families; no actor-specific application is ever hardcoded.
//
//  50 roles  →  18 dashboards  →  dynamic widgets
//
// This file is pure constitution. No UI, no logic, no persistence.
// ═══════════════════════════════════════════════════════════════════════════════

import type {
  AssignmentKind, DashboardFamilyId, DashboardLayerId, FamilyRoleMap,
  NavigationItem, PresentationWidget, QuickAction, ResolvedWorkspace,
} from './types';

export const DASHBOARD_FAMILIES: readonly FamilyRoleMap[] = [
  { familyId: 'executive', label: 'Executive Dashboard', roles: ['facility_administrator', 'ceo', 'hospital_director', 'medical_superintendent', 'county_director', 'regional_director', 'national_director'] },
  { familyId: 'clinical_leadership', label: 'Clinical Leadership Dashboard', roles: ['medical_director', 'nursing_director', 'chief_pharmacist', 'head_of_laboratory', 'chief_radiologist', 'head_of_surgery'] },
  { familyId: 'department', label: 'Department Dashboard', roles: ['department_head', 'unit_head', 'section_lead'] },
  { familyId: 'ward', label: 'Ward Dashboard', roles: ['ward_in_charge', 'charge_nurse', 'ward_consultant'] },
  { familyId: 'clinician', label: 'Clinician Dashboard', roles: ['consultant', 'specialist', 'medical_officer', 'clinical_officer', 'dentist'] },
  { familyId: 'resident', label: 'Resident Dashboard', roles: ['resident', 'registrar', 'senior_registrar'] },
  { familyId: 'student', label: 'Student Dashboard', roles: ['medical_student', 'nursing_student', 'pharmacy_student', 'resident_in_training', 'intern'] },
  { familyId: 'nursing', label: 'Nursing Dashboard', roles: ['registered_nurse', 'senior_nurse', 'midwife', 'enrolled_nurse', 'nurse_educator'] },
  { familyId: 'pharmacy', label: 'Pharmacy Dashboard', roles: ['pharmacist', 'pharmacy_technologist', 'chief_pharmacist'] },
  { familyId: 'laboratory', label: 'Laboratory Dashboard', roles: ['laboratory_scientist', 'laboratory_technologist', 'pathologist'] },
  { familyId: 'radiology', label: 'Radiology Dashboard', roles: ['radiologist', 'radiographer', 'sonographer'] },
  { familyId: 'theatre', label: 'Theatre Dashboard', roles: ['surgeon', 'anaesthetist', 'scrub_nurse', 'recovery_nurse', 'ot_technician'] },
  { familyId: 'emergency', label: 'Emergency Dashboard', roles: ['emergency_team', 'trauma_team', 'emergency_physician', 'emergency_nurse'] },
  { familyId: 'telemedicine', label: 'Telemedicine Dashboard', roles: ['remote_clinician', 'virtual_nurse', 'telehealth_coordinator'] },
  { familyId: 'research', label: 'Research Dashboard', roles: ['researcher', 'biostatistician', 'study_coordinator'] },
  { familyId: 'finance', label: 'Finance Dashboard', roles: ['finance_officer', 'insurance_officer', 'billing_officer', 'revenue_officer'] },
  { familyId: 'hr', label: 'HR Dashboard', roles: ['hr_officer', 'recruitment_officer', 'training_officer', 'payroll_officer'] },
  { familyId: 'ict', label: 'ICT Dashboard', roles: ['ict_officer', 'infrastructure_engineer', 'cybersecurity_officer', 'support_engineer', 'developer'] },
  { familyId: 'patient', label: 'Patient Dashboard', roles: ['patient', 'guardian'] },
];

// Constitutional note: a role may legitimately belong to more than one family
// (e.g., chief_pharmacist is both Clinical Leadership and Pharmacy). The engine is
// deterministic: it returns the most specific operational family that declares the
// role — the last declaration in the constitutional registry — so a Chief Pharmacist
// receives the Pharmacy operating system, not the aggregated leadership one.
export function resolveFamily(roles: string[]): DashboardFamilyId | undefined {
  let resolved: DashboardFamilyId | undefined;
  for (const role of roles) {
    for (const family of DASHBOARD_FAMILIES) {
      if (family.roles.includes(role.toLowerCase())) resolved = family.familyId;
    }
  }
  return resolved;
}

// ── Family label lookup ────────────────────────────────────────────────────────

export function familyLabel(familyId: DashboardFamilyId): string {
  return DASHBOARD_FAMILIES.find(f => f.familyId === familyId)?.label ?? `${familyId} Dashboard`;
}

// ── Navigation (constitutional — generated per family) ─────────────────────────

export const FAMILY_NAVIGATION: Readonly<Record<DashboardFamilyId, NavigationItem[]>> = {
  executive: [
    { key: 'overview', label: 'Overview', active: true },
    { key: 'departments', label: 'Departments', active: true },
    { key: 'staff', label: 'Staff', active: true },
    { key: 'patients', label: 'Patients', active: true },
    { key: 'operations', label: 'Operations', active: true },
    { key: 'quality', label: 'Quality', active: true },
    { key: 'finance', label: 'Finance', active: true },
    { key: 'inventory', label: 'Inventory', active: true },
    { key: 'analytics', label: 'Analytics', active: true },
    { key: 'research', label: 'Research', active: true },
    { key: 'settings', label: 'Settings', permission: 'administrate', active: true },
  ],
  clinical_leadership: [
    { key: 'overview', label: 'Overview', active: true },
    { key: 'patients', label: 'Patients', active: true },
    { key: 'quality', label: 'Quality', active: true },
    { key: 'protocols', label: 'Protocols', active: true },
    { key: 'teaching', label: 'Teaching', active: true },
    { key: 'research', label: 'Research', active: true },
    { key: 'analytics', label: 'Analytics', active: true },
  ],
  department: [
    { key: 'overview', label: 'Executive Summary', active: true },
    { key: 'operations', label: 'Clinical Operations', active: true },
    { key: 'patients', label: 'Patients', active: true },
    { key: 'admissions', label: 'Admissions', active: true },
    { key: 'wards', label: 'Ward Management', active: true },
    { key: 'clinics', label: 'Clinics', active: true },
    { key: 'theatre', label: 'Theatre', active: true },
    { key: 'staff', label: 'Staff', active: true },
    { key: 'education', label: 'Education', active: true },
    { key: 'research', label: 'Research', active: true },
    { key: 'quality', label: 'Quality', active: true },
    { key: 'resources', label: 'Resources', active: true },
    { key: 'intelligence', label: 'Intelligence', active: true },
    { key: 'analytics', label: 'Analytics', active: true },
    { key: 'communications', label: 'Communications', active: true },
    { key: 'reports', label: 'Reports', active: true },
    { key: 'protocols', label: 'Protocols', active: true },
    { key: 'settings', label: 'Settings', permission: 'administrate', active: true },
  ],
  ward: [
    { key: 'home', label: 'Ward Status', active: true },
    { key: 'patient_flow', label: 'Patient Flow', active: true },
    { key: 'bed_management', label: 'Bed Management', active: true },
    { key: 'nursing_operations', label: 'Nursing Operations', active: true },
    { key: 'medical_operations', label: 'Medical Operations', active: true },
    { key: 'ward_round', label: 'Ward Round', active: true },
    { key: 'medications', label: 'Medication', active: true },
    { key: 'investigations', label: 'Investigations', active: true },
    { key: 'procedures', label: 'Procedures', active: true },
    { key: 'equipment', label: 'Equipment', active: true },
    { key: 'infection', label: 'Infection Prevention', active: true },
    { key: 'clinical_intelligence', label: 'Clinical Intelligence', active: true },
    { key: 'emergency', label: 'Emergency Alerts', active: true },
    { key: 'communication', label: 'Communication', active: true },
    { key: 'teaching', label: 'Teaching', active: true },
    { key: 'quality', label: 'Quality', active: true },
    { key: 'analytics', label: 'Analytics', active: true },
    { key: 'reports', label: 'Reports', active: true },
    { key: 'settings', label: 'Settings', active: true },
  ],
  clinician: [
    { key: 'patients', label: 'Patients', active: true },
    { key: 'admissions', label: 'Admissions', active: true },
    { key: 'ward_round', label: 'Ward Round', active: true },
    { key: 'operating_list', label: 'Operating List', active: true },
    { key: 'clinics', label: 'Clinics', active: true },
    { key: 'emergency_referrals', label: 'Emergency Referrals', active: true },
    { key: 'critical_alerts', label: 'Critical Alerts', active: true },
    { key: 'clinical_intelligence', label: 'Clinical Intelligence', active: true },
    { key: 'orders', label: 'Orders', active: true },
    { key: 'results', label: 'Results', active: true },
    { key: 'investigations', label: 'Investigations', active: true },
    { key: 'imaging', label: 'Imaging', active: true },
    { key: 'procedures', label: 'Procedures', active: true },
    { key: 'decision_support', label: 'Decision Support', active: true },
    { key: 'protocols', label: 'Protocols', active: true },
    { key: 'research', label: 'Research', active: true },
    { key: 'education', label: 'Teaching', active: true },
    { key: 'messages', label: 'Messages', active: true },
    { key: 'telemedicine', label: 'Telemedicine', active: true },
    { key: 'analytics', label: 'Analytics', active: true },
    { key: 'quality', label: 'Quality', active: true },
    { key: 'reports', label: 'Reports', active: true },
    { key: 'preferences', label: 'Preferences', active: true },
    { key: 'settings', label: 'Settings', active: true },
  ],
  resident: [
    { key: 'my_patients', label: 'My Patients', active: true },
    { key: 'shift', label: 'Shift', active: true },
    { key: 'ward_round', label: 'My Ward Round', active: true },
    { key: 'admissions', label: 'Admissions', active: true },
    { key: 'history', label: 'History', active: true },
    { key: 'examination', label: 'Examination', active: true },
    { key: 'clinical_reasoning', label: 'Clinical Reasoning', active: true },
    { key: 'orders', label: 'Orders', active: true },
    { key: 'investigations', label: 'Investigations', active: true },
    { key: 'results', label: 'Results', active: true },
    { key: 'medications', label: 'Medication', active: true },
    { key: 'procedures', label: 'Procedures', active: true },
    { key: 'escalation', label: 'Escalation', active: true },
    { key: 'handover', label: 'Handover', active: true },
    { key: 'theatre', label: 'Theatre Prep', active: true },
    { key: 'clinic', label: 'Clinic', active: true },
    { key: 'emergency', label: 'Emergency', active: true },
    { key: 'communication', label: 'Communication', active: true },
    { key: 'learning', label: 'Learning', active: true },
    { key: 'competencies', label: 'Competencies', active: true },
    { key: 'supervisor', label: 'Supervisor', active: true },
    { key: 'logbook', label: 'Logbook', active: true },
    { key: 'analytics', label: 'Personal Analytics', active: true },
  ],
  student: [
    { key: 'dashboard', label: 'Dashboard', active: true },
    { key: 'today_patients', label: "Today's Patients", active: true },
    { key: 'logbook', label: 'Clinical Logbook', active: true },
    { key: 'competencies', label: 'Competencies', active: true },
    { key: 'ward_rounds', label: 'Ward Rounds', active: true },
    { key: 'clinics', label: 'Clinics', active: true },
    { key: 'theatre', label: 'Theatre', active: true },
    { key: 'procedures', label: 'Procedures', active: true },
    { key: 'simulation', label: 'Simulation', active: true },
    { key: 'assignments', label: 'Assignments', active: true },
    { key: 'research', label: 'Research', active: true },
    { key: 'portfolio', label: 'Portfolio', active: true },
    { key: 'assessments', label: 'Assessments', active: true },
    { key: 'feedback', label: 'Feedback', active: true },
    { key: 'learning_resources', label: 'Learning Resources', active: true },
    { key: 'analytics', label: 'Analytics', active: true },
    { key: 'settings', label: 'Settings', active: true },
  ],
  nursing: [
    { key: 'home', label: 'Home', active: true },
    { key: 'my_patients', label: 'Patients', active: true },
    { key: 'medication_schedule', label: 'Medication', active: true },
    { key: 'medication_administration', label: 'Medication Administration', active: true },
    { key: 'observations', label: 'Observations', active: true },
    { key: 'care_plans', label: 'Care Plans', active: true },
    { key: 'ward_board', label: 'Ward Board', active: true },
    { key: 'ward_census', label: 'Ward Census', active: true },
    { key: 'admissions', label: 'Admissions', active: true },
    { key: 'discharges', label: 'Discharges', active: true },
    { key: 'procedures', label: 'Procedures', active: true },
    { key: 'wounds', label: 'Wounds', active: true },
    { key: 'fluid_balance', label: 'Fluid Balance', active: true },
    { key: 'infusions', label: 'Infusions', active: true },
    { key: 'tasks', label: 'Tasks', active: true },
    { key: 'handover', label: 'Handover', active: true },
    { key: 'vitals', label: 'Vitals', active: true },
    { key: 'safety', label: 'Safety', active: true },
    { key: 'staffing', label: 'Staffing', active: true },
    { key: 'communication', label: 'Communication', active: true },
    { key: 'patient_education', label: 'Patient Education', active: true },
    { key: 'education', label: 'Education', active: true },
    { key: 'reports', label: 'Reports', active: true },
    { key: 'analytics', label: 'Analytics', active: true },
    { key: 'settings', label: 'Settings', active: true },
  ],
  pharmacy: [
    { key: 'dashboard', label: 'Dashboard', active: true },
    { key: 'prescriptions', label: 'Prescriptions', active: true },
    { key: 'dispensing', label: 'Dispensing', active: true },
    { key: 'medication_review', label: 'Medication Review', active: true },
    { key: 'inventory', label: 'Inventory', active: true },
    { key: 'procurement', label: 'Procurement', active: true },
    { key: 'compounding', label: 'Compounding', active: true },
    { key: 'controlled_drugs', label: 'Controlled Drugs', active: true },
    { key: 'ward_supply', label: 'Ward Supply', active: true },
    { key: 'clinical_pharmacy', label: 'Clinical Pharmacy', active: true },
    { key: 'drug_information', label: 'Drug Information', active: true },
    { key: 'pharmacovigilance', label: 'Pharmacovigilance', active: true },
    { key: 'interactions', label: 'Interactions', active: true },
    { key: 'antibiotic_stewardship', label: 'Antibiotic Stewardship', active: true },
    { key: 'insurance', label: 'Insurance', active: true },
    { key: 'reports', label: 'Reports', active: true },
    { key: 'analytics', label: 'Analytics', active: true },
    { key: 'settings', label: 'Settings', active: true },
  ],
  laboratory: [
    { key: 'dashboard', label: 'Dashboard', active: true },
    { key: 'specimens', label: 'Specimens', active: true },
    { key: 'workbench', label: 'Workbench', active: true },
    { key: 'accessions', label: 'Accessions', active: true },
    { key: 'requests', label: 'Requests', active: true },
    { key: 'sections', label: 'Sections', active: true },
    { key: 'analyzers', label: 'Analyzers', active: true },
    { key: 'quality_control', label: 'Quality Control', active: true },
    { key: 'blood_bank', label: 'Blood Bank', active: true },
    { key: 'histopathology', label: 'Histopathology', active: true },
    { key: 'microbiology', label: 'Microbiology', active: true },
    { key: 'molecular', label: 'Molecular', active: true },
    { key: 'poct', label: 'POCT', active: true },
    { key: 'results', label: 'Results', active: true },
    { key: 'critical_values', label: 'Critical Results', active: true },
    { key: 'reporting', label: 'Reporting', active: true },
    { key: 'surveillance', label: 'Surveillance', active: true },
    { key: 'research', label: 'Research', active: true },
    { key: 'reagents', label: 'Reagents', active: true },
    { key: 'analytics', label: 'Analytics', active: true },
    { key: 'settings', label: 'Settings', active: true },
  ],
  radiology: [
    { key: 'dashboard', label: 'Dashboard', active: true },
    { key: 'requests', label: 'Requests', active: true },
    { key: 'scheduling', label: 'Scheduling', active: true },
    { key: 'modalities', label: 'Modalities', active: true },
    { key: 'worklist', label: 'Worklist', active: true },
    { key: 'studies', label: 'Studies', active: true },
    { key: 'image_acquisition', label: 'Image Acquisition', active: true },
    { key: 'reporting', label: 'Reporting', active: true },
    { key: 'pacs', label: 'PACS', active: true },
    { key: 'ai_review', label: 'AI Review', active: true },
    { key: 'interventional', label: 'Interventional', active: true },
    { key: 'critical_findings', label: 'Critical Findings', active: true },
    { key: 'radiation_safety', label: 'Radiation Safety', active: true },
    { key: 'equipment', label: 'Equipment', active: true },
    { key: 'teaching_files', label: 'Teaching Files', active: true },
    { key: 'research', label: 'Research', active: true },
    { key: 'analytics', label: 'Analytics', active: true },
    { key: 'settings', label: 'Settings', active: true },
  ],
  theatre: [
    { key: 'theatre_list', label: 'Theatre List', active: true },
    { key: 'schedule', label: 'Schedule', active: true },
    { key: 'instruments', label: 'Instruments', active: true },
    { key: 'recovery', label: 'Recovery', active: true },
    { key: 'anaesthesia', label: 'Anaesthesia', active: true },
    { key: 'sterilization', label: 'Sterilization', active: true },
  ],
  emergency: [
    { key: 'triage', label: 'Triage', active: true },
    { key: 'resuscitation', label: 'Resuscitation', active: true },
    { key: 'ambulances', label: 'Ambulances', active: true },
    { key: 'critical_patients', label: 'Critical Patients', active: true },
    { key: 'beds', label: 'Available Beds', active: true },
    { key: 'blood', label: 'Blood', active: true },
    { key: 'trauma', label: 'Trauma Alerts', active: true },
  ],
  telemedicine: [
    { key: 'dashboard', label: 'Dashboard', active: true },
    { key: 'virtual_clinics', label: 'Virtual Clinics', active: true },
    { key: 'appointments', label: 'Appointments', active: true },
    { key: 'waiting_room', label: 'Waiting Room', active: true },
    { key: 'live_consultations', label: 'Live Consultations', active: true },
    { key: 'messages', label: 'Messages', active: true },
    { key: 'remote_monitoring', label: 'Remote Monitoring', active: true },
    { key: 'home_care', label: 'Home Care', active: true },
    { key: 'community_health', label: 'Community Health', active: true },
    { key: 'referrals', label: 'Referrals', active: true },
    { key: 'tele_mdt', label: 'Tele MDT', active: true },
    { key: 'patient_education', label: 'Patient Education', active: true },
    { key: 'analytics', label: 'Analytics', active: true },
    { key: 'reports', label: 'Reports', active: true },
    { key: 'settings', label: 'Settings', active: true },
  ],
  research: [
    { key: 'dashboard', label: 'Dashboard', active: true },
    { key: 'studies', label: 'Studies', active: true },
    { key: 'protocols', label: 'Protocols', active: true },
    { key: 'ethics', label: 'Ethics', active: true },
    { key: 'participants', label: 'Participants', active: true },
    { key: 'recruitment', label: 'Recruitment', active: true },
    { key: 'crfs', label: 'CRFs', active: true },
    { key: 'datasets', label: 'Datasets', active: true },
    { key: 'biobank', label: 'Biobank', active: true },
    { key: 'statistics', label: 'Statistics', active: true },
    { key: 'ai_datasets', label: 'AI Datasets', active: true },
    { key: 'publications', label: 'Publications', active: true },
    { key: 'grants', label: 'Grants', active: true },
    { key: 'teaching', label: 'Teaching', active: true },
    { key: 'collaborations', label: 'Collaborations', active: true },
    { key: 'analytics', label: 'Analytics', active: true },
    { key: 'settings', label: 'Settings', active: true },
  ],
  finance: [
    { key: 'dashboard', label: 'Dashboard', active: true },
    { key: 'revenue', label: 'Revenue Cycle', active: true },
    { key: 'billing', label: 'Billing', active: true },
    { key: 'patients', label: 'Patients', active: true },
    { key: 'insurance', label: 'Insurance', active: true },
    { key: 'claims', label: 'Claims', active: true },
    { key: 'payments', label: 'Payments', active: true },
    { key: 'payroll', label: 'Payroll', active: true },
    { key: 'budgets', label: 'Budgets', active: true },
    { key: 'procurement', label: 'Procurement', active: true },
    { key: 'suppliers', label: 'Suppliers', active: true },
    { key: 'accounting', label: 'Accounting', active: true },
    { key: 'assets', label: 'Assets', active: true },
    { key: 'reports', label: 'Reports', active: true },
    { key: 'analytics', label: 'Analytics', active: true },
    { key: 'settings', label: 'Settings', active: true },
  ],
  hr: [
    { key: 'dashboard', label: 'Dashboard', active: true },
    { key: 'employees', label: 'Employees', active: true },
    { key: 'recruitment', label: 'Recruitment', active: true },
    { key: 'credentialing', label: 'Credentialing', active: true },
    { key: 'onboarding', label: 'Onboarding', active: true },
    { key: 'departments', label: 'Departments', active: true },
    { key: 'assignments', label: 'Assignments', active: true },
    { key: 'scheduling', label: 'Scheduling', active: true },
    { key: 'performance', label: 'Performance', active: true },
    { key: 'competencies', label: 'Competencies', active: true },
    { key: 'training', label: 'Training', active: true },
    { key: 'leave', label: 'Leave', active: true },
    { key: 'payroll', label: 'Payroll', active: true },
    { key: 'succession', label: 'Succession', active: true },
    { key: 'reports', label: 'Reports', active: true },
    { key: 'analytics', label: 'Analytics', active: true },
    { key: 'settings', label: 'Settings', active: true },
  ],
  ict: [
    { key: 'dashboard', label: 'Dashboard', active: true },
    { key: 'infrastructure', label: 'Infrastructure', active: true },
    { key: 'servers', label: 'Servers', active: true },
    { key: 'cloud', label: 'Cloud', active: true },
    { key: 'networks', label: 'Networks', active: true },
    { key: 'devices', label: 'Devices', active: true },
    { key: 'biomedical', label: 'Biomedical Devices', active: true },
    { key: 'integrations', label: 'Integrations', active: true },
    { key: 'cybersecurity', label: 'Cybersecurity', active: true },
    { key: 'identity', label: 'Identity', active: true },
    { key: 'backups', label: 'Backups', active: true },
    { key: 'disaster_recovery', label: 'Disaster Recovery', active: true },
    { key: 'deployments', label: 'Deployments', active: true },
    { key: 'monitoring', label: 'Monitoring', active: true },
    { key: 'support', label: 'Support', active: true },
    { key: 'analytics', label: 'Analytics', active: true },
    { key: 'settings', label: 'Settings', active: true },
  ],
  patient: [
    { key: 'dashboard', label: 'Dashboard', active: true },
    { key: 'timeline', label: 'My Timeline', active: true },
    { key: 'appointments', label: 'Appointments', active: true },
    { key: 'telemedicine', label: 'Telemedicine', active: true },
    { key: 'records', label: 'Medical Records', active: true },
    { key: 'medications', label: 'Medications', active: true },
    { key: 'laboratory', label: 'Laboratory', active: true },
    { key: 'imaging', label: 'Imaging', active: true },
    { key: 'procedures', label: 'Procedures', active: true },
    { key: 'admissions', label: 'Admissions', active: true },
    { key: 'vaccinations', label: 'Vaccinations', active: true },
    { key: 'pregnancy', label: 'Pregnancy', active: true },
    { key: 'chronic', label: 'Chronic Diseases', active: true },
    { key: 'insurance', label: 'Insurance', active: true },
    { key: 'billing', label: 'Billing', active: true },
    { key: 'family', label: 'Family', active: true },
    { key: 'consent', label: 'Consent', active: true },
    { key: 'education', label: 'Education', active: true },
    { key: 'community', label: 'Community', active: true },
    { key: 'emergency_card', label: 'Emergency Card', active: true },
    { key: 'settings', label: 'Settings', active: true },
  ],
};

// ── Layers (every dashboard has five) ──────────────────────────────────────────

export const DASHBOARD_LAYERS: readonly { id: DashboardLayerId; label: string }[] = [
  { id: 'overview', label: 'Overview' },
  { id: 'operations', label: 'Operations' },
  { id: 'communication', label: 'Communication' },
  { id: 'learning', label: 'Learning' },
  { id: 'analytics', label: 'Analytics' },
];

// ── Quick actions (constitutional per family) ─────────────────────────────────

export const FAMILY_QUICK_ACTIONS: Readonly<Record<DashboardFamilyId, QuickAction[]>> = {
  executive: [
    { key: 'new_department', label: 'New Department', context: 'administration' },
    { key: 'new_staff', label: 'New Staff', context: 'administration' },
    { key: 'import_hr', label: 'Import HR', context: 'administration' },
    { key: 'import_hmis', label: 'Import HMIS', context: 'administration' },
    { key: 'generate_report', label: 'Generate Report', context: 'administration' },
  ],
  clinical_leadership: [
    { key: 'new_encounter', label: 'New Encounter', context: 'clinic' },
    { key: 'quality_review', label: 'Quality Review', context: 'administration' },
    { key: 'protocol_update', label: 'Protocol Update', context: 'teaching' },
  ],
  department: [
    { key: 'open_ward', label: 'Open Ward', context: 'ward_round' },
    { key: 'new_encounter', label: 'New Encounter', context: 'clinic' },
    { key: 'staff_schedule', label: 'Staff Schedule', context: 'administration' },
    { key: 'new_study', label: 'New Study', context: 'research' },
    { key: 'new_audit', label: 'New Audit', context: 'administration' },
    { key: 'protocol_update', label: 'Protocol Update', context: 'teaching' },
    { key: 'generate_report', label: 'Generate Report', context: 'administration' },
  ],
  ward: [
    { key: 'handover', label: 'Handover', context: 'ward_round' },
    { key: 'record_vitals', label: 'Record Vitals', context: 'ward_round' },
    { key: 'medication_round', label: 'Medication Round', context: 'ward_round', permission: 'prescribe' },
    { key: 'admit', label: 'Admit Patient', context: 'ward_round' },
    { key: 'transfer', label: 'Transfer', context: 'ward_round' },
    { key: 'escalate', label: 'Escalate', context: 'emergency_call' },
    { key: 'discharge', label: 'Discharge', context: 'ward_round' },
  ],
  clinician: [
    { key: 'new_encounter', label: 'New Encounter', context: 'clinic' },
    { key: 'prescribe', label: 'Prescribe', context: 'clinic', permission: 'prescribe' },
    { key: 'request_lab', label: 'Request Lab', context: 'clinic', permission: 'order_lab' },
    { key: 'request_ct', label: 'Request CT', context: 'clinic', permission: 'order_imaging' },
    { key: 'refer', label: 'Refer', context: 'clinic' },
    { key: 'discharge', label: 'Discharge', context: 'clinic', permission: 'discharge' },
  ],
  resident: [
    { key: 'new_admission', label: 'New Admission', context: 'clinic' },
    { key: 'new_encounter', label: 'New Encounter', context: 'clinic' },
    { key: 'request_lab', label: 'Request Lab', context: 'clinic', permission: 'order_lab' },
    { key: 'escalate', label: 'Escalate to Consultant', context: 'clinic' },
    { key: 'handover', label: 'Handover', context: 'ward_round' },
    { key: 'log_procedure', label: 'Log Procedure', context: 'teaching', permission: 'prescribe' },
    { key: 'prepare_theatre', label: 'Theatre Prep', context: 'theatre' },
    { key: 'discharge_summary', label: 'Discharge Summary', context: 'clinic' },
  ],
  student: [
    { key: 'new_case', label: 'New Case', context: 'clinic' },
    { key: 'log_procedure', label: 'Log Procedure', context: 'teaching' },
    { key: 'submit_logbook', label: 'Submit Logbook', context: 'teaching' },
    { key: 'draft_note', label: 'Draft Note', context: 'teaching' },
    { key: 'request_assessment', label: 'Request Assessment', context: 'teaching' },
    { key: 'ward_round', label: 'Ward Round', context: 'ward_round' },
    { key: 'simulation', label: 'Simulation', context: 'teaching' },
    { key: 'research_task', label: 'Research Task', context: 'research' },
    { key: 'tutor', label: 'AI Tutor', context: 'teaching' },
  ],
  nursing: [
    { key: 'record_vitals', label: 'Record Vitals', context: 'ward_round' },
    { key: 'medication_round', label: 'Medication Round', context: 'ward_round', permission: 'prescribe' },
    { key: 'administer_medication', label: 'Administer Medication', context: 'ward_round', permission: 'prescribe' },
    { key: 'scan_patient', label: 'Scan Patient', context: 'ward_round' },
    { key: 'care_plan', label: 'Care Plan', context: 'ward_round' },
    { key: 'handover', label: 'Handover', context: 'ward_round' },
    { key: 'observation', label: 'Observation', context: 'ward_round' },
    { key: 'wound_care', label: 'Wound Care', context: 'ward_round' },
    { key: 'fluid_balance', label: 'Fluid Balance', context: 'ward_round' },
    { key: 'admit', label: 'Admit', context: 'ward_round' },
    { key: 'discharge', label: 'Discharge Prep', context: 'ward_round' },
  ],
  pharmacy: [
    { key: 'verify_prescription', label: 'Verify Prescription', context: 'pharmacy' },
    { key: 'dispense', label: 'Dispense', context: 'pharmacy' },
    { key: 'barcode_verify', label: 'Barcode Verify', context: 'pharmacy' },
    { key: 'clinical_check', label: 'Clinical Check', context: 'pharmacy' },
    { key: 'counsel_patient', label: 'Counsel Patient', context: 'pharmacy' },
    { key: 'restock', label: 'Restock', context: 'pharmacy' },
    { key: 'purchase_order', label: 'Purchase Order', context: 'pharmacy' },
    { key: 'report_adr', label: 'Report ADR', context: 'pharmacy' },
    { key: 'controlled_drug_log', label: 'Controlled Drug Log', context: 'pharmacy' },
  ],
  laboratory: [
    { key: 'receive_specimen', label: 'Receive Specimen', context: 'laboratory' },
    { key: 'accept_specimen', label: 'Accept Specimen', context: 'laboratory' },
    { key: 'label_verify', label: 'Barcode Verify', context: 'laboratory' },
    { key: 'process_sample', label: 'Process Sample', context: 'laboratory' },
    { key: 'enter_results', label: 'Enter Results', context: 'laboratory' },
    { key: 'verify_results', label: 'Verify Results', context: 'laboratory' },
    { key: 'release_results', label: 'Release Results', context: 'laboratory' },
    { key: 'critical_call', label: 'Call Critical Value', context: 'laboratory' },
    { key: 'qc_check', label: 'QC Check', context: 'laboratory' },
    { key: 'analyzer_monitor', label: 'Monitor Analyzer', context: 'laboratory' },
    { key: 'reflex_test', label: 'Reflex Test', context: 'laboratory' },
  ],
  radiology: [
    { key: 'accept_request', label: 'Accept Request', context: 'radiology' },
    { key: 'schedule_study', label: 'Schedule Study', context: 'radiology' },
    { key: 'safety_screen', label: 'Safety Screen', context: 'radiology' },
    { key: 'protocol', label: 'Set Protocol', context: 'radiology' },
    { key: 'acquire_study', label: 'Acquire Study', context: 'radiology' },
    { key: 'upload_images', label: 'Upload Images', context: 'radiology' },
    { key: 'ai_review', label: 'AI Review', context: 'radiology' },
    { key: 'report_study', label: 'Report Study', context: 'radiology' },
    { key: 'critical_call', label: 'Call Critical Finding', context: 'radiology' },
    { key: 'check_queue', label: 'Check Queue', context: 'radiology' },
  ],
  theatre: [
    { key: 'start_case', label: 'Start Case', context: 'theatre' },
    { key: 'schedule', label: 'Schedule', context: 'theatre' },
    { key: 'instrument_check', label: 'Instrument Check', context: 'theatre' },
  ],
  emergency: [
    { key: 'triage', label: 'Triage Patient', context: 'emergency_call' },
    { key: 'resuscitation', label: 'Resuscitation', context: 'emergency_call' },
    { key: 'request_bed', label: 'Request Bed', context: 'emergency_call' },
    { key: 'request_blood', label: 'Request Blood', context: 'emergency_call' },
  ],
  telemedicine: [
    { key: 'start_consultation', label: 'Start Consultation', context: 'telemedicine' },
    { key: 'monitoring', label: 'Remote Monitoring', context: 'telemedicine' },
    { key: 'referral', label: 'Referral', context: 'telemedicine' },
    { key: 'asynchronous', label: 'Asynchronous', context: 'telemedicine' },
    { key: 'home_care', label: 'Home Care', context: 'telemedicine' },
    { key: 'tele_icu', label: 'Tele-ICU', context: 'telemedicine' },
    { key: 'escalate', label: 'Emergency Escalation', context: 'emergency_call' },
    { key: 'patient_education', label: 'Patient Education', context: 'telemedicine' },
  ],
  research: [
    { key: 'new_study', label: 'New Study', context: 'research' },
    { key: 'protocol', label: 'Draft Protocol', context: 'research' },
    { key: 'ethics_submit', label: 'Submit Ethics', context: 'research' },
    { key: 'consent', label: 'Consent', context: 'research' },
    { key: 'recruit', label: 'Recruit', context: 'research' },
    { key: 'crf', label: 'Enter CRF', context: 'research' },
    { key: 'dataset', label: 'Dataset', context: 'research' },
    { key: 'analyze', label: 'Analyze', context: 'research' },
    { key: 'publish', label: 'Publication', context: 'research' },
  ],
  finance: [
    { key: 'new_bill', label: 'New Bill', context: 'administration' },
    { key: 'cashier', label: 'Cashier', context: 'administration' },
    { key: 'payment', label: 'Record Payment', context: 'administration' },
    { key: 'claim', label: 'Insurance Claim', context: 'administration' },
    { key: 'validate_claim', label: 'Validate Claim', context: 'administration' },
    { key: 'reconciliation', label: 'Reconcile', context: 'administration' },
    { key: 'purchase_order', label: 'Purchase Order', context: 'administration' },
    { key: 'payroll_run', label: 'Run Payroll', context: 'administration' },
    { key: 'report', label: 'Financial Report', context: 'administration' },
  ],
  hr: [
    { key: 'vacancy', label: 'Post Vacancy', context: 'administration' },
    { key: 'applications', label: 'Review Applications', context: 'administration' },
    { key: 'interview', label: 'Schedule Interview', context: 'administration' },
    { key: 'verify_credentials', label: 'Verify Credentials', context: 'administration' },
    { key: 'onboard', label: 'Onboard', context: 'administration' },
    { key: 'assign', label: 'Assign Department', context: 'administration' },
    { key: 'roster', label: 'Build Roster', context: 'administration' },
    { key: 'leave_request', label: 'Leave Request', context: 'administration' },
    { key: 'appraisal', label: 'Start Appraisal', context: 'administration' },
    { key: 'promote', label: 'Promote', context: 'administration' },
    { key: 'payroll', label: 'Payroll', context: 'administration' },
  ],
  ict: [
    { key: 'ticket', label: 'New Ticket', context: 'administration' },
    { key: 'incident', label: 'Report Incident', context: 'administration' },
    { key: 'deploy', label: 'Deploy', context: 'administration' },
    { key: 'backup', label: 'Run Backup', context: 'administration' },
    { key: 'failover', label: 'Failover', context: 'administration' },
    { key: 'integration', label: 'New Integration', context: 'administration' },
    { key: 'enroll_device', label: 'Enroll Device', context: 'administration' },
    { key: 'security_scan', label: 'Security Scan', context: 'administration' },
    { key: 'monitor', label: 'System Monitoring', context: 'administration' },
  ],
  patient: [
    { key: 'book_appointment', label: 'Book Appointment', context: 'clinic' },
    { key: 'teleconsult', label: 'Teleconsult', context: 'telemedicine' },
    { key: 'refill', label: 'Refill Prescription', context: 'pharmacy' },
    { key: 'upload', label: 'Upload Document', context: 'clinic' },
    { key: 'symptom', label: 'Symptom Checker', context: 'clinic' },
    { key: 'home_reading', label: 'Home Reading', context: 'clinic' },
    { key: 'consent', label: 'Manage Consent', context: 'clinic' },
    { key: 'pay', label: 'Pay Bill', context: 'administration' },
  ],
};

// ── Workspace resolution from assignment ───────────────────────────────────────

export function workspaceForAssignment(assignmentKind?: AssignmentKind): ResolvedWorkspace {
  if (!assignmentKind) return { key: 'overview', label: 'Overview', familyId: 'executive', kind: 'overview' };
  const labels: Record<AssignmentKind, string> = {
    ward_round: 'Ward Round', clinic: 'Clinic', theatre: 'Theatre',
    administration: 'Administration', meeting: 'Meeting', research: 'Research',
    teaching: 'Teaching', emergency_call: 'Emergency', icu: 'ICU',
    on_call: 'On Call', laboratory: 'Laboratory', pharmacy: 'Pharmacy',
    radiology: 'Radiology', telemedicine: 'Telemedicine', community_health: 'Community Health',
  };
  return { key: assignmentKind, label: labels[assignmentKind], familyId: 'executive', kind: assignmentKind };
}

// ── Constitutional rules ───────────────────────────────────────────────────────

export const PRESENTATION_RULES: readonly string[] = [
  'Authentication never chooses a dashboard',
  'Identity never chooses a dashboard',
  'Roles alone never choose a dashboard',
  'Assignment has higher priority than employment',
  'Capabilities override generic role behavior',
  'Preferences personalize presentation, never business logic',
  'Every dashboard must degrade gracefully if one widget fails',
  'The Presentation Engine never contains clinical reasoning',
  'Every actor sees only what permissions and active context allow',
  'Pages never contain business logic; business logic never contains UI',
];

export function buildWidget(
  type: string,
  title: string,
  familyId: DashboardFamilyId,
  priority: number,
  opts: {
    size?: PresentationWidget['size'];
    refreshIntervalSeconds?: number;
    permission?: string;
    layer?: DashboardLayerId;
    data?: Record<string, unknown>;
  } = {},
): PresentationWidget {
  return {
    id: `${familyId}-${type}`,
    type,
    title,
    familyId,
    layer: opts.layer ?? 'overview',
    size: opts.size ?? 'md',
    priority,
    refreshIntervalSeconds: opts.refreshIntervalSeconds ?? 60,
    visible: true,
    permission: opts.permission,
    data: opts.data ?? {},
  };
}